/** A saturation of 90%, a score of 3, and a range nobody on this chart is comparing it with. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const OXYGEN_TARGET_SCALE_A_SCORE_THAT_SHOULD_BE_LOWER: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'oxygen-target-scale-a-score-that-should-be-lower', version: '0.1.0', maturity: 'preview',
    title: 'A score that should be lower', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 8, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-medical-surgical-nursing-oxygen-target-scale-two-documents-before-one-verdict', statement: 'Read both documents before calling them mismatched.', measure: 'The prescribed target range and the documented scale decision were read, the observation chart and the scale it is scored on were read, and only then was the disagreement recorded, because a mismatch is a statement about two documents and recording it from one was refused, without learner examination, diagnosis, or treatment selection.' },
      { id: 'recognize-medical-surgical-nursing-oxygen-target-scale-a-number-compared-with-the-wrong-range', statement: 'Recognize a number compared against the wrong range.', measure: 'The saturation was recalculated on the prescribed scale, falling from 3 to 0 with the measurement unchanged, and carrying the higher of the two scales was refused because it preserves a comparison with a range nobody prescribed and hands the next reader a total they cannot reproduce.' },
      { id: 'record-medical-surgical-nursing-oxygen-target-scale-what-a-corrected-score-does-not-supply', statement: 'State what the corrected score does and does not supply.', measure: 'The record stated that only the score changed, that what the correction removes is a reason to give oxygen she does not need, and that it supplies no evidence she is well, and reading the fall as an improvement was refused because nothing about her changed in that minute.' },
      { id: 'activate-medical-surgical-nursing-oxygen-target-scale-a-decision-that-is-not-the-wards-to-make', statement: 'Route the scale decision to a competent decision maker.', measure: 'The documented decision and the prescribed range were taken to the qualified team for confirmation with the mismatch and the recalculated score attached, and switching scales on the strength of the diagnosis alone was refused because the scale requires confirmed hypercapnic respiratory failure, a prescribed range, and a recorded decision.' },
      { id: 'review-medical-surgical-nursing-oxygen-target-scale-boundaries-and-their-certainty', statement: 'Review the boundaries and their certainty.', measure: 'That the guideline itself warns a patient inside the prescribed range scores points on the ordinary scale and that this may prompt staff to raise the inspired oxygen and put her at risk, that one randomised trial found lower mortality with a titrated strategy while the guideline states it is not known whether the range is ideal, and that the second scale has not been shown to detect deterioration better than the first were all kept explicit.' },
      { id: 'handoff-medical-surgical-nursing-oxygen-target-scale-a-corrected-score-handed-over-as-corrected', statement: 'Hand the corrected score over as corrected.', measure: 'The handoff preserved the prescribed range with its documented decision, that the chart had been scored on the ordinary scale, that the saturation did not change when the score fell, and that the correction removes a reason to give oxygen rather than supplying evidence of improvement, with cause and outcome left uncertified.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: [
        'Royal College of Physicians. National Early Warning Score (NEWS) 2: Standardising the assessment of acute-illness severity in the NHS. Updated report of a working party. London: RCP, 2017. Chart 1 publishes both SpO2 scales: Scale 1 scores 91% or below as 3, 92-93% as 2, 94-95% as 1, and 96% or above as 0; Scale 2 scores 88-92%, or 93% or above on air, as 0. Recommendation 25 confines Scale 2 to patients with hypercapnic respiratory failure confirmed on blood gas who require supplemental oxygen, with a prescribed target of 88-92%. The requirement is a property of the admission rather than of the current minute, which is why Scale 2 carries a band for 93% or above on air. Recommendation 26 requires the decision to be made by a competent clinical decision maker and recorded in the notes. The chart directs that the section not being used is crossed out.',
        'O’Driscoll BR, Howard LS, Earis J, Mak V; British Thoracic Society Emergency Oxygen Guideline Group. BTS guideline for oxygen use in adults in healthcare and emergency settings. Thorax. 2017;72(Suppl 1):ii1-ii90. doi:10.1136/thoraxjnl-2016-209729. States the 88-92% target for patients at risk of hypercapnic respiratory failure (Grade A for chronic obstructive pulmonary disease, evidence level 1+), that it is not known whether 88-92% is the ideal range, and that patients within 88-92% score points on the earlier early-warning score and that this may prompt nursing staff to increase the inspired oxygen and put the patient at risk.',
        'Austin MA, Wills KE, Blizzard L, Walters EH, Wood-Baker R. Effect of high flow oxygen on mortality in chronic obstructive pulmonary disease patients in prehospital setting: randomised controlled trial. BMJ. 2010;341:c5462. doi:10.1136/bmj.c5462. Cluster-randomised by paramedic rather than by patient; intention-to-treat mortality 21/226 (9%) with high-flow oxygen versus 7/179 (4%) with titrated oxygen, relative risk 0.42 (95% CI 0.20-0.89), P=0.02. Thirty-seven percent of the confirmed cases received non-protocol treatment, and in the per-protocol analysis the difference did not reach significance.',
        'Tirkkonen J, Karlsson S, Skrifvars MB. National early warning score (NEWS) and the new alternative SpO2 scale during rapid response team reviews: a prospective observational study. Scand J Trauma Resusc Emerg Med. 2019;27:111. doi:10.1186/s13049-019-0691-6. In 886 rapid-response reviews, applying Scale 2 to the 11.7% with confirmed hypercapnic respiratory failure did not improve discrimination for either immediate or in-hospital outcome.',
      ] },
    limitations: ['oxygen-target-scale-observation-and-documents-are-authored',
      'oxygen-target-scale-controls-are-reading-and-recording-only',
      'oxygen-target-scale-a-corrected-score-is-not-reassurance'],
  },
  patient: {
    ageYears: 71, sex: 'female', heightCm: 159, weightKg: 58, asaClass: 3,
    diagnosis: 'Authored observation chart scored against a target range nobody prescribed for this patient',
    procedure: 'calm document reading, score reconciliation, escalation of a decision, and handoff practice',
    comorbidities: ['Chronic obstructive pulmonary disease with hypercapnic respiratory failure confirmed on blood gas; day 3 of an admission with an exacerbation'],
    medications: ['All oxygen, prescribing, and treatment decisions remain qualified-team work'],
    allergies: ['No known drug allergies'], fasting: 'Not relevant to the nursing fixture',
    baseline: { heartRateBpm: 84, meanArterialMmHg: 92, strokeVolumeMl: 62,
      hemoglobinGPerDl: 13.8, bloodVolumeMl: 4_100, coreTemperatureC: 36.8,
      arterialStiffness: 1.3, baroreflexGain: 0.6, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Awake and protecting the airway in the supplied fixture' },
    respiratory: { profile: 'healthy' },
  },
  equipment: { monitoring: ['nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask',
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 400, respiratoryRateBpm: 12,
      freshGasFlowLPerMin: 10, delivering: false } }, formulary: [],
  timeline: [
    { id: 'oxygen-target-scale-presentation', type: 'narrative', target: 'oxygen-target-scale', atTick: 0,
      severity: 'warning', message: 'A 71-year-old with chronic obstructive pulmonary disease is on day three of an admission with an exacerbation. Hypercapnic respiratory failure was confirmed on blood gas, and a respiratory review two days ago prescribed a target saturation range of 88 to 92% and recorded in the notes the decision to score her on the second oxygen-saturation scale. She has needed controlled oxygen at intervals through this admission and is breathing air at present. Authored observations are pulse 84/min, blood pressure 128/74 mmHg, respiratory rate 18/min, temperature 36.8 C, and oxygen saturation 90% breathing air. She is awake, alert, and speaking in full sentences. The observation chart at the end of the bed is scored on the first scale, and the saturation row reads 3.' },
    { id: 'oxygen-target-scale-evidence', type: 'narrative', target: 'oxygen-target-scale-evidence', atTick: 0,
      severity: 'warning', message: 'Ninety percent on air is exactly where she was prescribed to be. The first scale scores 91% or below as 3, because for most patients that is a deviation. The second scale, published on the same chart for patients like her, scores 88 to 92% as 0, and is the only part of the score that also penalises being too high on oxygen. It applies to her whether or not she happens to be breathing oxygen at this moment: it carries its own band for 93% or above on air precisely because these patients move on and off it. The number in the chart is not wrong; the range it is being compared with is. The guideline that sets the 88 to 92% target says in terms that patients within it score points on the ordinary score and that this may prompt staff to increase the inspired oxygen to reach a normal-looking figure and put the patient at risk, which is the sequence this chart has set up. Two things bound how far the correction goes. The evidence for targeting rather than flooding is strong, and rests substantially on one cluster-randomised trial that found lower mortality with a titrated strategy, yet the same guideline states plainly that it is not known whether 88 to 92% is the ideal range. And the second scale has not been shown to find deterioration that the first misses: the one study to compare them found no improvement in discrimination. Correcting the scale removes a false alarm. It does not add a reassurance.' },
    { id: 'oxygen-target-scale-boundary', type: 'narrative', target: 'oxygen-target-scale-boundary', atTick: 0,
      severity: 'warning', message: 'Read the prescription and the documented scale decision; read the observation chart and the scale it is scored on; record that the two disagree, as a statement about the documents rather than about her; rescore the saturation on the prescribed scale; state what the rescore changes and what it does not; take the documented decision to the qualified team for confirmation, because changing which scale a patient is scored on belongs to a competent clinical decision maker and is recorded in the notes; review the boundaries and their certainty; and arrange observation on the corrected chart with the unused section crossed out and with each saturation recorded alongside whether she was breathing air. Raising the inspired oxygen to lift the saturation, assuming the diagnosis by itself sets the scale, reading the lower score as an improvement, and scoring both scales and carrying the higher are all refused. Recording a mismatch before both documents are read is refused, and so is rescoring before the mismatch is recorded, because replacing one number with another leaves no trace of why. No drug, dose, route, fluid, oxygen device, flow rate, inspired concentration, or procedure is exposed; the learner performs no examination beyond reading the chart and orders no test. After elapsed simulated time a colleague reads the score of 3 and offers to put oxygen on her, which is the named harm arriving as a helpful offer. If confirmation is requested, the qualified team later confirms the documented decision and the prescribed range, records that the wrong chart was in use, and records that a corrected score is not a statement that she is well. The saturation does not move during this rehearsal, because a drifting number would let a learner treat the drift as the answer. No individualized effect, treatment causality, cause, eligibility, disposition, prognosis, or outcome is reported. Qualified teams retain the prescription, the scale decision, oxygen, and every treatment decision. After another elapsed interval, hand off the prescribed range and its documented decision, the scale the chart had been using, the recalculated score, disposition, and outcome uncertainty. The controls do not take history; examine beyond reading the chart; acquire or interpret laboratory, imaging, or another test; diagnose; select, set, or deliver a drug, dose, route, fluid, oxygen, or device; perform a procedure; determine eligibility, disposition, or prognosis; or predict response, cause, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'oxygen-target-scale-trajectory', objectiveId: 'reconcile-medical-surgical-nursing-oxygen-target-scale-two-documents-before-one-verdict', question: 'Why can a mismatch not be recorded from one document?' },
    { id: 'oxygen-target-scale-recognition', objectiveId: 'recognize-medical-surgical-nursing-oxygen-target-scale-a-number-compared-with-the-wrong-range', question: 'What changed between the score of 3 and the score of 0?' },
    { id: 'oxygen-target-scale-limits', objectiveId: 'record-medical-surgical-nursing-oxygen-target-scale-what-a-corrected-score-does-not-supply', question: 'What does the corrected score remove, and what does it not add?' },
    { id: 'oxygen-target-scale-activation', objectiveId: 'activate-medical-surgical-nursing-oxygen-target-scale-a-decision-that-is-not-the-wards-to-make', question: 'Whose decision is the scale, and what does it require?' },
    { id: 'oxygen-target-scale-boundaries', objectiveId: 'review-medical-surgical-nursing-oxygen-target-scale-boundaries-and-their-certainty', question: 'What does the guideline say it does not know about the range?' },
    { id: 'oxygen-target-scale-handoff', objectiveId: 'handoff-medical-surgical-nursing-oxygen-target-scale-a-corrected-score-handed-over-as-corrected', question: 'How should the next nurse read a score that fell without the patient changing?' },
  ] },
};
