import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { ACUTE_PULMONARY_EDEMA_RESPIRATORY_SUPPORT_REASSESSMENT } from './scenarios/acute-pulmonary-edema-respiratory-support-reassessment';
import { APE_SUPPORT_FIXTURES } from './acute-pulmonary-edema-respiratory-support-reassessment-fixtures';
import { APE_SUPPORT_TUTOR_VERSION } from './tutor/acute-pulmonary-edema-respiratory-support-reassessment-guidance';
import { APE_SUPPORT_DEMONSTRATION_VERSION } from './demo/acute-pulmonary-edema-respiratory-support-reassessment-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Like the other Respiratory Medicine lessons this one declares five
 * objectives rather than six, so `observable-objectives` is already satisfied
 * and only the two runtime requirements remain.
 */
export function apeSupportCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'respiratory-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== APE_SUPPORT_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || APE_SUPPORT_FIXTURES.contentVersion !== '0.1.0'
    || APE_SUPPORT_FIXTURES.seed !== 7370
    || APE_SUPPORT_TUTOR_VERSION !== '0.1.0' || APE_SUPPORT_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(ACUTE_PULMONARY_EDEMA_RESPIRATORY_SUPPORT_REASSESSMENT)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['acute-pulmonary-edema-respiratory-support-reassessment-fixtures.ts binds seed 7370 and content 0.1.0 to expert, cause-review-before-recognition error, recovery, and no-action paths. The arrival state, the delivered-care record, the 30-minute observations, the interface sampling and the two blood gases are authored constants; no edema, diuresis, vasodilator or support-response model is claimed, and no outcome follows from any choice. tests/integration/acute-pulmonary-edema-support-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through five recorded steps on the shared simulation clock, and the handoff is time-gated: it refuses until simulated time has passed since the escalation. What moves is what has been reconciled, named and called; what does not move is the congestion, the acidemia, or the precipitant.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions separate correct initial care from the trajectory since, name progressive hypoxemic, hypercapnic, acidemic failure from the mentation, effort, oxygenation, ventilation and acid-base evidence together rather than any single value, read the treated pressure and persistent congestion while ischemia, arrhythmia, mechanical disease, infection, embolism, treatment effect, renal and medication factors stay open, activate respiratory, critical-care and airway-capable help for a failure already established, and hand off. Order is enforced rather than suggested, and refusal names the missing step. The lesson examines nobody, acquires or interprets no monitoring, blood gas, ECG, imaging or ultrasound, selects or changes no oxygen device, flow, FiO₂, interface, mode, pressure, PEEP or ventilator setting, starts or operates no noninvasive support, delivers or titrates no medication, performs no airway procedure, and determines no disposition.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at active-deterioration handoff. Later actions cannot restart an ended branch, and the ending certifies no delivered oxygen or medication, no started noninvasive support or selected setting, no airway procedure, no determined disposition, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that went to the precipitants before naming the failure can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['acute-pulmonary-edema-respiratory-support-reassessment-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 7370 for deterministic replay through the shared engine, including the time-gated handoff.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${APE_SUPPORT_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent. Worked example ${APE_SUPPORT_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. Both separate the experienced team's correct initial care — upright, monitored noninvasive support with titrated oxygen, a loop diuretic and a pressure-appropriate vasodilator — from where she has ended up, and note that her pressure has genuinely come down from 196/118 to 108/68. The failure is then named from the mentation, the effort and the gas together: a respiratory rate of 34 that is now 12, single words, a saturation of 86% on an authored FiO₂ of 0.60, an end-tidal CO₂ of 60, and a pH of 7.18 with a PaCO₂ of 68. The falling rate is fatigue rather than improvement — the same trap as the asthma lab, reached here through a treatment that is working on the thing it was aimed at. The treated pressure is read as afterload rather than shock and the persistent crackles as unresolved congestion, with ischemia, arrhythmia, mechanical disease, infection, embolism, treatment effect and renal and medication factors all open. The escalation deliberately follows that review rather than preceding it, because the help being called is airway-capable help for a failure that has been established. A test asserts nothing anywhere touches the support or its settings, delivers a drug, or performs an airway procedure. tests/unit/ape-support-demonstration.test.ts and tests/ui/respiratory-ape-support.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
