import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { COPD_EXACERBATION_TRANSITION_REASSESSMENT } from './scenarios/copd-exacerbation-transition-reassessment';
import { COPD_TRANSITION_FIXTURES } from './copd-exacerbation-transition-reassessment-fixtures';
import { COPD_TRANSITION_TUTOR_VERSION } from './tutor/copd-exacerbation-transition-reassessment-guidance';
import { COPD_TRANSITION_DEMONSTRATION_VERSION } from './demo/copd-exacerbation-transition-reassessment-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Like the other Respiratory Medicine lessons this one declares five
 * objectives rather than six, so `observable-objectives` is already satisfied
 * and only the two runtime requirements remain.
 */
export function copdTransitionCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'respiratory-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== COPD_TRANSITION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || COPD_TRANSITION_FIXTURES.contentVersion !== '0.1.0'
    || COPD_TRANSITION_FIXTURES.seed !== 7328
    || COPD_TRANSITION_TUTOR_VERSION !== '0.1.0' || COPD_TRANSITION_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(COPD_EXACERBATION_TRANSITION_REASSESSMENT)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['copd-exacerbation-transition-reassessment-fixtures.ts binds seed 7328 and content 0.1.0 to expert, medication-before-function error, recovery, and no-action paths. The pre-admission baseline, the delivered-care record, the day-three observations, the corridor walk and the medication reconciliation are authored constants; no recovery, oxygen-need, rehabilitation or follow-up model is claimed, and no outcome follows from any choice. tests/integration/copd-exacerbation-transition-reassessment-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions reconcile the recovery against who she was before admission, review the residual respiratory and oxygen needs from the corridor walk without settling long-term oxygen from an acute snapshot, review the maintenance and acute medication plan including technique errors already found by a qualified therapist, coordinate the rehabilitation, self-management, comorbidity review and follow-up that remain unarranged, and hand off unresolved work. Order is enforced rather than suggested, and refusal names the missing step. The lesson delivers no treatment or oxygen, determines no long-term oxygen eligibility, selects no regimen, performs or grades no inhaler technique, enrolls nobody in rehabilitation, guarantees no appointment, and determines no disposition.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at unresolved-transition handoff. Later actions cannot restart an ended branch, and the ending certifies no determined long-term oxygen eligibility, no selected regimen, no performed technique, no rehabilitation enrollment, no guaranteed appointment, no determined disposition, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that went to the medication plan before looking at what she can do can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['copd-exacerbation-transition-reassessment-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 7328 for deterministic replay through the shared engine, including the time-gated handoff.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${COPD_TRANSITION_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent. Worked example ${COPD_TRANSITION_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. Both start from who she was before this admission rather than from today's numbers — independent, walking about 200 metres, resting saturation 92%, no home oxygen — and both then put the corridor walk ahead of everything else, because that is where the answer is: she pauses after thirty metres, desaturates to 86%, and takes three minutes to come back to 91%. Symptoms and gas exchange improved and function did not, and function is what decides whether home works. The oxygen question is refused rather than answered, since a desaturation on day three of an exacerbation does not establish long-term oxygen eligibility, which is assessed when she is stable. The inhaler-technique errors a qualified therapist already found are named as a finding to carry rather than something to re-grade, and as mattering more than any change of drug, because a maintenance inhaler she cannot use is not a maintenance inhaler. The rehabilitation, self-management, comorbidity review and follow-up are named as the parts most likely to be skipped and most likely to matter, and as requested rather than secured. A test asserts nothing anywhere delivers treatment or oxygen, settles the oxygen eligibility, selects a regimen, grades a technique, or guarantees an appointment. tests/unit/copd-exacerbation-transition-demonstration.test.ts and tests/ui/respiratory-copd-exacerbation-transition.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
