import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { HIGH_FLOW_NASAL_OXYGEN_ESCALATION } from './scenarios/high-flow-nasal-oxygen-escalation';
import { HIGH_FLOW_OXYGEN_FIXTURES } from './high-flow-nasal-oxygen-escalation-fixtures';
import { HIGH_FLOW_OXYGEN_TUTOR_VERSION } from './tutor/high-flow-nasal-oxygen-escalation-guidance';
import { HIGH_FLOW_OXYGEN_DEMONSTRATION_VERSION } from './demo/high-flow-nasal-oxygen-escalation-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function highFlowOxygenEscalationCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'respiratory-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== HIGH_FLOW_OXYGEN_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || HIGH_FLOW_OXYGEN_FIXTURES.contentVersion !== '0.1.0'
    || HIGH_FLOW_OXYGEN_FIXTURES.seed !== 2471
    || HIGH_FLOW_OXYGEN_TUTOR_VERSION !== '0.1.0' || HIGH_FLOW_OXYGEN_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(HIGH_FLOW_NASAL_OXYGEN_ESCALATION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['high-flow-nasal-oxygen-escalation-fixtures.ts binds seed 2471 and content 0.1.0 to expert, two-decision-point wrong-choice error, recovery, and no-action paths. The four-day history, the imaging report, the twenty minutes of verified functioning reservoir-mask oxygen, the fixed gas, the suitability report and the fixed thirty-minute response are authored constants; no oxygenation, device-response or outcome model is claimed, and no outcome follows from any choice. tests/integration/high-flow-nasal-oxygen-escalation-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, and two of them are time-gated: the thirty-minute response refuses until simulated time has passed since the selection, and the handoff refuses until time has passed again. Unsupported choices are recorded events that move nothing, and this lesson offers them at two separate moments: continuing conventional oxygen or reaching for a bilevel trial first before the selection, and calling the failure resolved or standing the monitoring down after the thirty-minute response. Each is answered and leaves the patient exactly as he was.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile an inadequate trajectory on documented functioning conventional oxygen, review suitability, monitoring and airway-capable rescue readiness alongside his documented interface preference, select a closely monitored high-flow nasal oxygen trial as a goal, read the fixed thirty-minute response after elapsed time, preserve the monitoring and failure guards, and hand off. Four further choices are deliberately offered and refused across two decision points: unchanged conventional oxygen has already been shown inadequate, a bilevel-first trial can be reasonable in selected acute hypoxemic failure but is not this authored nonhypercapnic case-specific first choice, marking the failure resolved contradicts a partial response on substantial remaining support, and reducing monitoring removes the observation the trial depends on. The lesson examines nobody, acquires or interprets no blood gas, imaging or other test, calculates no ROX index or PaO₂/FiO₂ ratio, diagnoses nothing, selects or delivers no oxygen, medication, suction, mask ventilation or intubation, chooses no source, device, cannula, fit, flow, temperature, humidification, FiO₂, oxygen target, NIV mode, interface, pressure, PEEP, backup rate, trigger or cycle, operates no equipment, performs no proning or other procedure, and determines no disposition, prognosis or outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at thirty-minute handoff with the trial still running and the pathogen still unresolved. Later actions cannot restart an ended branch, and the ending certifies no proven durable success, no learner-performed intubation, no determined disposition, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual is a clinical one rather than an ordering slip: the recovery path stays on conventional oxygen, tries a bilevel trial first, then after the response marks the failure resolved and stands the monitoring down — and all four refusals stay visible in the transcript after the correct choices are made from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['high-flow-nasal-oxygen-escalation-fixtures.ts binds exact-content expert, wrong-support-goal, recovery, and no-action pathways to seed 2471 for deterministic replay through the shared engine, including both time gates and all four refused choices.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${HIGH_FLOW_OXYGEN_TUTOR_VERSION} read the learner's own recorded steps, and as in the support-selection lesson the tutor also reads the wrong turn just taken, answering each refused goal with its own prose. Staying on conventional oxygen is named as a decision rather than a neutral pause — the mask is documented as functioning and has already failed to make him adequate. A bilevel-first trial is explicitly not treated as a misunderstanding: NIV and CPAP can be reasonable in selected acute hypoxemic failure, and this is simply not the case where either is the first choice, in a man with no acidotic hypercapnia, no cardiogenic-edema pattern, and a documented preference for a nasal interface. Worked example ${HIGH_FLOW_OXYGEN_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff without making either wrong choice, and its narration is generated from the tutor's own prose so the two cannot drift apart. Both open on the fact that the oxygen is working and he is still not managing, and read the alkalotic gas as the sign of a man working hard rather than a reassurance. Both treat his interface preference as clinical rather than courteous, because tolerability is part of whether the trial works. Both name delayed intubation as the specific harm this trial risks and a guard written in advance as what prevents it, and both note what the lesson deliberately refuses to compute — no ROX index and no PaO₂/FiO₂ ratio, because the delivered reservoir-mask FiO₂ was never known. At the second decision point the tutor answers those two refusals as well: better is not resolved when none of the improved numbers was achieved on room air, and standing the observation down feels like proportionate care while removing the thing that would catch the failure — the window where he looks well being exactly the window in which delayed intubation happens. A test asserts nothing anywhere examines him, interprets a gas, or sets a flow, temperature, humidification or FiO₂. tests/unit/high-flow-nasal-oxygen-escalation-demonstration.test.ts and tests/ui/respiratory-high-flow-nasal-oxygen-escalation.test.tsx verify observed response, both wrong-choice prompts, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
