import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { NEUROMUSCULAR_RESPIRATORY_FAILURE_REASSESSMENT } from './scenarios/neuromuscular-respiratory-failure-reassessment';
import { NEUROMUSCULAR_RESPIRATORY_FAILURE_FIXTURES } from './neuromuscular-respiratory-failure-reassessment-fixtures';
import { NEUROMUSCULAR_RESPIRATORY_FAILURE_TUTOR_VERSION } from './tutor/neuromuscular-respiratory-failure-reassessment-guidance';
import { NEUROMUSCULAR_RESPIRATORY_FAILURE_DEMONSTRATION_VERSION } from './demo/neuromuscular-respiratory-failure-reassessment-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function neuromuscularRespiratoryFailureCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'respiratory-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== NEUROMUSCULAR_RESPIRATORY_FAILURE_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || NEUROMUSCULAR_RESPIRATORY_FAILURE_FIXTURES.contentVersion !== '0.1.0'
    || NEUROMUSCULAR_RESPIRATORY_FAILURE_FIXTURES.seed !== 3158
    || NEUROMUSCULAR_RESPIRATORY_FAILURE_TUTOR_VERSION !== '0.1.0' || NEUROMUSCULAR_RESPIRATORY_FAILURE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(NEUROMUSCULAR_RESPIRATORY_FAILURE_REASSESSMENT)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['neuromuscular-respiratory-failure-reassessment-fixtures.ts binds seed 3158 and content 0.1.0 to expert, ownership-before-review error, recovery, and no-action paths. The three-month functional and cough decline, the two-week symptom progression, the serial FVC, SNIP and peak-cough-flow reports, the room-air blood gas, and the radiograph and neurologic reports are authored constants; no ventilatory, respiratory-muscle or treatment-response model is claimed, and no outcome follows from any choice. tests/integration/neuromuscular-respiratory-failure-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock. Escalation and the bulbar, cough and alternatives review are parallel lanes rather than a sequence, shared ownership waits for both, and the handoff is time-gated: it refuses until simulated time has passed since ownership was coordinated. What moves is what has been reconciled, recognized, connected, kept open and owned; what does not move is the diagnosis, the device, or the outcome.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile three months of decline against two weeks of new symptoms, establish progressive ventilatory failure from the convergent whole pattern rather than one cutoff, connect experienced respiratory-ventilation, critical-care and airway-capable evaluation without waiting for a complete cause review, keep the motor neuron disease central while aspiration, infection, mucus retention, atelectasis, pulmonary embolism, lung, cardiac, metabolic, endocrine, medication, other neuromuscular, central and test-quality causes stay open, coordinate respiratory, neurology, speech and swallowing, nutrition, physiotherapy, nursing, primary-care and caregiver ownership around documented preferences, and hand off. The lesson examines nobody, acquires, performs, scores or interprets no oximetry, capnography, blood gas, spirometry, FVC, SNIP, peak cough flow, sleep, imaging, swallowing, cough or neurologic test, diagnoses nothing, selects or delivers no oxygen, ventilation, interface, mode, setting, cough assistance, suction, drug or nutrition, performs no airway procedure, and determines no disposition, prognosis or outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at active-risk handoff. Later actions cannot restart an ended branch, and the ending certifies no determined diagnosis, no selected support device, no airway procedure, no determined disposition, no prognosis, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that agreed who owned the plan before anyone had reviewed his cough, swallowing and triggers can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['neuromuscular-respiratory-failure-reassessment-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 3158 for deterministic replay through the shared engine, including the parallel lanes and the time-gated handoff.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${NEUROMUSCULAR_RESPIRATORY_FAILURE_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent. Worked example ${NEUROMUSCULAR_RESPIRATORY_FAILURE_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, and its narration is generated from the tutor's own prose so the two cannot drift apart. Both name the room-air saturation of 94% as the number most likely to reassure and the one that says least about whether he is ventilating, then let orthopnea, the supine abdominal paradox, the weak cough, the hypercapnia and the convergent serial FVC, SNIP and peak-cough-flow decline establish the pattern together rather than through any single threshold. Both insist experienced evaluation is connected before the cause review is finished, and both distinguish activating that evaluation from choosing a treatment. Both keep the radiograph, temperature, glucose and neurologic report as findings that narrow the field and permanently exclude nothing, and both treat his short-phrase dysarthric speech as clinical work rather than a courtesy, with preferences documented rather than inferred. A test asserts nothing anywhere examines him, acquires or interprets a test, or selects oxygen, a device, a setting, cough assistance or a nutrition plan. tests/unit/neuromuscular-respiratory-failure-demonstration.test.ts and tests/ui/respiratory-neuromuscular-respiratory-failure.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
