import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { NONINVASIVE_VENTILATION_SELECTION } from './scenarios/noninvasive-ventilation-selection';
import { NIV_SELECTION_FIXTURES } from './noninvasive-ventilation-selection-fixtures';
import { NIV_SELECTION_TUTOR_VERSION } from './tutor/noninvasive-ventilation-selection-guidance';
import { NIV_SELECTION_DEMONSTRATION_VERSION } from './demo/noninvasive-ventilation-selection-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function noninvasiveVentilationSelectionCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'respiratory-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== NIV_SELECTION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || NIV_SELECTION_FIXTURES.contentVersion !== '0.1.0'
    || NIV_SELECTION_FIXTURES.seed !== 8634
    || NIV_SELECTION_TUTOR_VERSION !== '0.1.0' || NIV_SELECTION_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(NONINVASIVE_VENTILATION_SELECTION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['noninvasive-ventilation-selection-fixtures.ts binds seed 8634 and content 0.1.0 to expert, wrong-modality error, recovery, and no-action paths. The baseline gas, the arrival severity, the verified hour of controlled oxygen, bronchodilator, antimuscarinic, corticosteroid and antibiotic therapy, the repeat gas, the suitability report and the fixed first-hour response are authored constants; no ventilatory, device-response or outcome model is claimed, and no outcome follows from any choice. tests/integration/noninvasive-ventilation-selection-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, and two of them are time-gated: the first-hour response refuses until simulated time has passed since the selection, and the handoff refuses until time has passed again. Uniquely in this module, an unsupported support goal is a recorded event that moves nothing — selecting CPAP alone or high-flow nasal oxygen alone is answered and leaves the patient exactly as she was.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile an hour of verified correct therapy against persistent acidotic hypercapnia, review suitability and rapid rescue readiness without treating the report as a contraindication checklist, select a closely monitored bilevel NIV trial as a goal, read the fixed first-hour response after elapsed time, name the continuation and failure guards, and hand off. Two further support goals are deliberately offered and refused: CPAP alone provides distending pressure rather than ventilatory assistance, and high-flow nasal oxygen alone may support oxygenation while the acidosis continues. The lesson examines nobody, acquires or interprets no blood gas, imaging or other test, diagnoses nothing, selects or delivers no oxygen, medication, sedation, suction, mask ventilation or intubation, chooses no device, interface, fit, pressure, PEEP, backup rate, trigger, cycle, flow or FiO₂, operates no ventilator, decides no ceiling of care, and determines no disposition, prognosis or outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at first-hour handoff with the trial still running. Later actions cannot restart an ended branch, and the ending certifies no proven durable NIV success, no learner-performed intubation, no decided ceiling of care, no determined disposition, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual here is stronger than an ordering slip: the recovery path tries CPAP alone, then high-flow alone, and both refusals stay visible in the transcript after the correct selection is made from the same position.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['noninvasive-ventilation-selection-fixtures.ts binds exact-content expert, wrong-modality, recovery, and no-action pathways to seed 8634 for deterministic replay through the shared engine, including both time gates and both refused support goals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${NIV_SELECTION_TUTOR_VERSION} read the learner's own recorded steps, and this lesson's tutor also reads the wrong turn they just took: the engine publishes which unsupported goal was last offered, so the tutor answers CPAP alone and high-flow alone with different prose instead of repeating one generic beat. CPAP is named as the right tool for a different problem — it holds the airway open and does not do the breathing — and high-flow as the choice that risks a better-looking saturation while the acidosis carries on; both note that nothing changed, because nothing about her changed. Worked example ${NIV_SELECTION_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff without ever making the wrong choice, and its narration is generated from the tutor's own prose so the two cannot drift apart. Both open by asking what an hour of correct treatment has already failed to fix, and are explicit that none of that care was the learner's to give and all of it was right. Both refuse to let the suitability report become a checklist, both insist a trial without a failure guard is an assumption with a mask on it, and both keep every device setting with the qualified staff who own it. A test asserts nothing anywhere examines her, interprets a gas, or sets an interface, pressure, backup rate or FiO₂. tests/unit/noninvasive-ventilation-selection-demonstration.test.ts and tests/ui/respiratory-noninvasive-ventilation-selection.test.tsx verify observed response, the two wrong-choice prompts, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
