import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { OBESITY_HYPOVENTILATION_REASSESSMENT } from './scenarios/obesity-hypoventilation-reassessment';
import { OBESITY_HYPOVENTILATION_FIXTURES } from './obesity-hypoventilation-reassessment-fixtures';
import { OBESITY_HYPOVENTILATION_TUTOR_VERSION } from './tutor/obesity-hypoventilation-reassessment-guidance';
import { OBESITY_HYPOVENTILATION_DEMONSTRATION_VERSION } from './demo/obesity-hypoventilation-reassessment-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function obesityHypoventilationCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'respiratory-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== OBESITY_HYPOVENTILATION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || OBESITY_HYPOVENTILATION_FIXTURES.contentVersion !== '0.1.0'
    || OBESITY_HYPOVENTILATION_FIXTURES.seed !== 5192
    || OBESITY_HYPOVENTILATION_TUTOR_VERSION !== '0.1.0' || OBESITY_HYPOVENTILATION_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(OBESITY_HYPOVENTILATION_REASSESSMENT)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['obesity-hypoventilation-reassessment-fixtures.ts binds seed 5192 and content 0.1.0 to expert, one-lane recognition error, recovery, and no-action paths. The twelve-month symptom history, the authored BMI, the serum total CO₂ and awake arterial gas, the attended sleep report, the spirometry, imaging, TSH and neurologic reports are authored constants; no ventilatory, sleep or treatment-response model is claimed, and no outcome follows from any choice. tests/integration/obesity-hypoventilation-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock. The awake gas and the sleep-plus-open-causes review are parallel lanes rather than a sequence, the convergent working pattern waits for both, and the handoff is time-gated: it refuses until simulated time has passed since the shared plan. What moves is what has been reconciled, read, recognized and owned; what does not move is the diagnosis, the device, or the causality.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions start from symptoms and daytime function rather than body size, read the awake gas without letting a raised bicarbonate stand in for a diagnosis, read the attended sleep study while lung, cardiac, pulmonary-vascular, neurologic, neuromuscular, chest-wall, endocrine, metabolic, medication, substance, central-control and technical contributors stay open, record a convergent working pattern that no single number establishes, coordinate respectful respiratory, sleep, primary-care, cardiometabolic and weight-health ownership around preferences and access, and hand off. The lesson examines nobody, calculates no BMI or AHI, acquires, performs, scores or interprets no bicarbonate, blood gas, oximetry, capnography, spirometry, imaging or sleep study, diagnoses no OHS, OSA or cause, selects or delivers no oxygen, CPAP, NIV, interface, mode, pressure, backup rate, drug, weight target, nutrition plan, bariatric procedure or treatment, counsels no driving, changes no body weight, and determines no disposition, prognosis or outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at convergent-pattern handoff with the work still open. Later actions cannot restart an ended branch, and the ending certifies no learner-determined diagnosis, no proven obesity causality, no selected device, no determined disposition, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that reached for a conclusion on the sleep study alone can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['obesity-hypoventilation-reassessment-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 5192 for deterministic replay through the shared engine, including the parallel evidence lanes and the time-gated handoff.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${OBESITY_HYPOVENTILATION_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent, and because the two evidence lanes are order-free the tutor names whichever lane is still empty rather than insisting on a sequence. Worked example ${OBESITY_HYPOVENTILATION_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, and its narration is generated from the tutor's own prose so the two cannot drift apart. Both open on twelve months of symptoms and a shrinking walking distance, and name the BMI of 43.3 as one authored fact among those and the one most likely to be mistaken for the whole assessment. Both let the awake gas establish compensated hypercapnia while calling a raised bicarbonate a reasonable prompt to measure PaCO₂ rather than a diagnosis, and both note how much the clean spirometry, imaging, TSH and neurologic reports do not exclude. Both then refuse to diagnose from any single number — not BMI, not bicarbonate, not saturation, not PaCO₂, and not an AHI of 48, however striking — and record a convergent pattern instead. Both treat how the plan is discussed as clinical work, with preferences and access documented rather than inferred. A test asserts nothing anywhere examines her, calculates or interprets a test, or selects oxygen, a device, a pressure, a weight target or a procedure. tests/unit/obesity-hypoventilation-demonstration.test.ts and tests/ui/respiratory-obesity-hypoventilation.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
