import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-delivery-room-nicu-sending-receiving-transport-and-family-handoff-support', 'Activate sending, receiving, transport, and family handoff support.', 'Named sending, receiving, transport, respiratory, monitoring, documentation, family-communication, dignity, and escalation ownership were confirmed first.'],
  ['reconcile-delivery-room-nicu-gestation-perinatal-birth-resuscitation-current-state-parent-and-whole-dyad', 'Connect gestation, perinatal context, birth, resuscitation, current state, parent, and whole dyad.', 'The supplied gestation, birth indication and clock, initial condition, intervention-response timeline, current support and physiology, pending data, parent, and destination facts were connected without learner history, examination, monitoring, or record interpretation.'],
  ['review-delivery-room-nicu-patient-assessment-situation-safety-background-actions-timing-ownership-and-next-step-content', 'Review patient, assessment, situation, safety, background, actions, timing, ownership, and next-step content.', 'The minimum structured handoff content preserved what happened, what is happening, what remains dangerous, who owns it, and what comes next without claiming a completed learner handoff.'],
  ['review-qualified-delivery-room-nicu-transport-continuity-receiving-readiness-check-back-and-family-boundaries', 'Review qualified transport continuity, receiving readiness, check-back, and family boundaries.', 'Qualified respiratory, thermal and monitoring continuity, equipment and route readiness, receiver questions and check-back, documentation, escalation, parent explanation, dignity, and reunification planning were reviewed without learner transport or communication.'],
  ['review-delivery-room-nicu-fixed-receiver-check-back-and-ten-minute-arrival-report', 'Review the fixed receiver check-back and 10-minute arrival report.', 'The authored receiver confirmation and arrival trajectory were reviewed without claiming learner communication, transport, monitoring, treatment effect, durable stability, disposition, or outcome.'],
  ['handoff-delivery-room-nicu-respiratory-thermal-glucose-neurologic-infection-feeding-family-and-outcome-risk', 'Hand off respiratory, thermal, glucose, neurologic, infection, feeding, family, and outcome risk.', 'The handoff preserved deterioration, support, temperature, glucose, neurologic, infection, pending-data, feeding, parent, escalation, disposition, and outcome uncertainty.'],
] as const;

export const DELIVERY_ROOM_TO_NICU_HANDOFF: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'delivery-room-to-nicu-handoff', version: '0.1.0', maturity: 'preview', title: 'Delivery room to NICU: transfer the whole story', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 8, difficulty: 'intermediate', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['American Heart Association and American Academy of Pediatrics. Part 5: Neonatal Resuscitation: 2025 Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care. Pediatrics. 2026;157(1):e2025074352.', 'Agency for Healthcare Research and Quality. Implement Teamwork and Communication for Perinatal Safety. TeamSTEPPS Perinatal Safety Module.'] }, limitations: ['delivery-room-nicu-perinatal-resuscitation-current-parent-receiver-and-arrival-reports-are-authored', 'delivery-room-nicu-controls-activate-reconcile-review-check-back-and-handoff-only', 'no-live-delivery-room-nicu-exam-monitor-support-transport-communication-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'female', heightCm: 45, weightKg: 2.1, asaClass: 4, diagnosis: 'Supplied late-preterm postresuscitation transition requiring NICU transfer', procedure: 'structured transfer-content, qualified transport-boundary, receiver check-back, and active-risk handoff practice', comorbidities: ['34 weeks 2 days; emergency cesarean birth for a supplied prolonged fetal-heart-rate deceleration'], medications: [], allergies: ['No known allergies'], fasting: 'Feeding, glucose, fluid, and nutrition support remain qualified-team work', baseline: { heartRateBpm: 142, meanArterialMmHg: 40, strokeVolumeMl: 20, hemoglobinGPerDl: 17, bloodVolumeMl: 800, coreTemperatureC: 36.5, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Spontaneous breathing with mild grunting and retractions during supplied CPAP support' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.3, tidalVolumeMl: 21, respiratoryRateBpm: 40, freshGasFlowLPerMin: 6, delivering: false } }, formulary: [],
  timeline: [
    { id: 'delivery-room-to-nicu-handoff-presentation', type: 'narrative', target: 'delivery-room-to-nicu-handoff', atTick: 0, severity: 'warning', message: 'A 2.1 kg newborn girl at 34 weeks 2 days is 12 minutes old after emergency cesarean birth for a supplied prolonged fetal-heart-rate deceleration. Qualified records report initial apnea with heart rate 76/min, warmth, positioning, drying, stimulation and airway assessment, then effective face-mask ventilation beginning at 50 seconds with visible chest movement and heart-rate rise to 118/min at 2 minutes. Spontaneous breathing emerged by 4 minutes. No compression, epinephrine, access, fluid, blood, or alternative airway is authored. Current qualified assessment supplies heart rate 142/min, respiratory rate 58/min with mild grunting and retractions, preductal SpO2 93% during CPAP 5 cm H2O and oxygen 30%, axillary temperature 36.5°C, capillary refill 2 seconds, and glucose and cord gas pending. The NICU has accepted transfer. Her recovering parent has heard that she is breathing but has not yet received a complete update.' },
    { id: 'delivery-room-to-nicu-handoff-boundary', type: 'narrative', target: 'delivery-room-to-nicu-handoff-boundary', atTick: 0, severity: 'warning', message: 'Confirm named sending, receiving, transport, respiratory, monitoring, documentation, escalation, parent-communication, dignity, and reunification ownership. Connect gestation, perinatal context, birth indication and clock, initial condition, initial-step and ventilation timeline, response, current respiratory and thermal support, current physiology, pending glucose and cord gas, absent interventions, parent state, preferences, support, destination, and whole dyad. Review a structured transfer of patient, assessment, situation, safety concerns, background, actions, timing, ownership, and next steps; preserve both positive and negative facts, response and nonresponse, equipment and support continuity, route and destination readiness, deterioration triggers, receiver questions, check-back, documentation, and parent communication. A fixed receiver check-back confirms: late-preterm newborn; initial apnea and heart rate 76/min; effective ventilation from 50 seconds with heart-rate response; spontaneous breathing by 4 minutes; no compressions, epinephrine, access, fluid, blood or alternative airway; current CPAP 5 cm H2O with oxygen 30%; temperature 36.5°C; glucose and cord gas pending; respiratory, thermal, glucose, neurologic, infection, feeding, family and escalation risks still open; NICU team owns monitoring and anticipatory care on arrival while the delivery-room team owns continuity until explicit transfer. A fixed qualified-team report 10 minutes after NICU arrival supplies heart rate 140/min, respiratory rate 54/min with persistent mild retractions, preductal SpO2 94% during the same reported support, axillary temperature 36.4°C, capillary refill 2 seconds, glucose 52 mg/dL, cord gas still pending, and parent update and reunification planning underway. This report does not prove learner handoff, shared understanding, transport, monitoring, support delivery, treatment effect, durable stability, diagnosis, feeding safety, disposition, or outcome. Controls do not take a history; examine, score, measure, monitor, obtain or interpret a record, glucose, gas or another test; diagnose; warm or cool; operate CPAP, oxygen, a monitor or another device; select a setting; give respiratory support; ventilate; manage an airway; obtain access; give glucose, fluid, blood, drug or dose; feed; resuscitate; move, position or transport the newborn; call, speak, listen, check back, document, counsel or update a parent or team; perform another procedure; determine disposition; or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `delivery-room-to-nicu-handoff-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
