import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-ineffective-neonatal-ventilation-qualified-airway-ventilation-clock-and-dyad-response', 'Activate qualified airway, ventilation, clock, and dyad response.', 'A ventilation-capable newborn team with explicit leader, airway, ventilation, heart-rate, monitoring, timekeeping, recording, parent communication, dignity, and support roles was activated first.'],
  ['reconcile-ineffective-neonatal-ventilation-birth-clock-interface-chest-movement-heart-rate-and-whole-dyad', 'Connect the birth clock, interface, chest movement, heart rate, and whole dyad.', 'The supplied birth, initial-step, ventilation, interface, chest-movement, heart-rate, oxygenation, thermal, parent, and support facts were connected without learner examination or device handling.'],
  ['recognize-ineffective-neonatal-ventilation-from-absent-heart-rate-rise-without-cause-closure', 'Recognize ineffective ventilation from absent heart-rate rise without cause closure.', 'Absent heart-rate rise, supported by absent chest movement, triggered immediate effectiveness review while leak, obstruction, position, pressure, equipment, lung, airway, and other causes stayed open.'],
  ['review-qualified-neonatal-ventilation-correction-alternative-airway-and-compression-boundary', 'Review qualified ventilation correction, alternative-airway, and compression boundaries.', 'Qualified correction of mask leak and obstruction, reassessment of chest movement and heart rate, alternative-airway readiness, warmth, monitoring, and escalation were reviewed before any compression branch.'],
  ['review-ineffective-neonatal-ventilation-fixed-two-minute-qualified-response-report', 'Review the fixed 2-minute qualified-team response report.', 'The authored response after qualified correction was reviewed without claiming learner ventilation, technical skill, durable breathing, stable transition, disposition, or outcome.'],
  ['handoff-ineffective-neonatal-ventilation-airway-respiratory-neurologic-parent-and-outcome-risk', 'Hand off airway, respiratory, neurologic, parent, and outcome risk.', 'The handoff preserved ventilation effectiveness, recurrent leak or obstruction, airway, lung, oxygenation, heart-rate, thermal, glucose, neurologic, etiologic, parent-dyad, escalation, disposition, and outcome uncertainty.'],
] as const;

export const INEFFECTIVE_VENTILATION_CORRECTION: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'ineffective-ventilation-correction', version: '0.1.0', maturity: 'preview', title: 'Ineffective newborn ventilation: correct before escalating', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'intermediate', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Lee HC, Strand ML, Finan E, et al. Part 5: Neonatal Resuscitation: 2025 American Heart Association and American Academy of Pediatrics Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care. Pediatrics. 2026;157(1):e2025074352.'] }, limitations: ['ineffective-neonatal-ventilation-birth-interface-response-parent-and-qualified-course-reports-are-authored', 'ineffective-neonatal-ventilation-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-ineffective-neonatal-ventilation-exam-monitor-device-oxygen-airway-compression-drug-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'female', heightCm: 49, weightKg: 3.2, asaClass: 2, diagnosis: 'Supplied ineffective face-mask ventilation pattern during term neonatal resuscitation', procedure: 'ventilation-effectiveness recognition, qualified correction review, reassessment, and active-risk handoff practice', comorbidities: ['38 weeks 6 days by supplied obstetric dating; cesarean birth after nonreassuring fetal surveillance'], medications: ['No newborn medication has been administered'], allergies: ['No known allergies'], fasting: 'Newborn feeding readiness remains qualified-team work after stabilization', baseline: { heartRateBpm: 78, meanArterialMmHg: 42, strokeVolumeMl: 20, hemoglobinGPerDl: 17, bloodVolumeMl: 800, coreTemperatureC: 36.5, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.3, difficultMaskVentilation: false, assessment: 'Apneic with absent visible chest movement during supplied qualified face-mask ventilation; leak or obstruction remains unlocalized' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 24, respiratoryRateBpm: 40, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'ineffective-neonatal-ventilation-presentation', type: 'narrative', target: 'ineffective-ventilation-correction-transition', atTick: 0, severity: 'critical', message: 'A 3.2 kg newborn girl is 80 seconds old after cesarean birth at 38 weeks 6 days. Qualified staff report apnea after initial steps and 30 seconds of face-mask assisted ventilation, but no visible chest movement and no heart-rate rise: heart rate changed from 82/min to 78/min. Preductal SpO2 is 68% with a reliable signal, temperature is 36.5°C, and the mask, airway position, leak, obstruction, delivered pressure, device, and lung response require immediate qualified reassessment. The awake parent cannot see the newborn and asks for an update.' },
    { id: 'ineffective-neonatal-ventilation-boundary', type: 'narrative', target: 'ineffective-ventilation-correction-transition-boundary', atTick: 0, severity: 'warning', message: 'Activate trained newborn airway and ventilation help with leader, airway and ventilation owner, heart-rate assessor, monitoring, timekeeping, recording, equipment, parent communication, dignity, and support roles. Connect gestation, risks, birth and resuscitation clocks, completed initial steps, interface, ventilation interval, chest movement, heart-rate trajectory, oxygenation signal, temperature, equipment, parent state, preferences, support, and whole dyad. A rise in heart rate is the primary sign of effective ventilation; chest movement is secondary. When heart rate remains below 100/min and does not increase during face-mask ventilation, qualified staff immediately correct common mask leak or airway obstruction, reassess position, delivered ventilation, chest movement, heart rate, equipment and lung response, and use an alternative airway when needed. Do not proceed to compressions unless heart rate remains below 60/min despite adequate ventilation after corrective steps, preferably through an alternative airway. A fixed qualified-team report at 2 minutes supplies corrected mask leak, visible chest movement, heart rate risen to 118/min, preductal SpO2 76% with the same reliable signal, and emerging irregular spontaneous respirations while assisted ventilation continues. This response does not prove durable breathing, stable transition, absence of airway or lung disease, neurologic safety, disposition, or outcome. Controls do not examine, score, measure, monitor or interpret tests; position, dry, warm, suction or stimulate; separate; handle a mask or device; choose or deliver pressure, rate, PEEP or oxygen; ventilate; perform corrective steps; place an airway; perform compressions; obtain access; give fluid, glucose, drug or dose; feed; resuscitate; transport; counsel; perform another procedure; determine disposition; or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `ineffective-neonatal-ventilation-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
