import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-meconium-stained-transition-prepared-newborn-airway-and-dyad-support', 'Activate prepared newborn, airway, and dyad support.', 'A trained newborn-capable clinician, airway-ready birth team, shared clock, parent communication, dignity, and support ownership were confirmed first.'],
  ['reconcile-meconium-stained-transition-fluid-breathing-tone-heart-rate-airway-and-whole-dyad', 'Connect fluid, breathing, tone, heart rate, airway, and the whole dyad.', 'The supplied meconium, birth-clock, breathing, tone, heart-rate, airway-visibility, thermal, parent, and support facts were connected without learner examination or scoring.'],
  ['recognize-vigorous-meconium-stained-transition-without-routine-suction', 'Recognize vigorous meconium-stained transition without routine suction.', 'Breathing or crying, good tone, adequate heart rate, and no visible obstruction supported transition care without treating meconium alone as a suction indication.'],
  ['review-qualified-selective-airway-clearing-observation-and-escalation-boundaries', 'Review qualified selective-airway-clearing, observation, and escalation boundaries.', 'Qualified protected transition care, ongoing respiratory observation, and obstruction-triggered airway-clearing boundaries were reviewed without learner care delivery.'],
  ['review-meconium-stained-transition-fixed-thirty-minute-qualified-report', 'Review the fixed 30-minute qualified-team report.', 'The authored stable respiratory report was reviewed without claiming learner care, excluded respiratory disease, durable safety, disposition, or outcome.'],
  ['handoff-meconium-stained-transition-respiratory-thermal-feeding-parent-and-outcome-risk', 'Hand off respiratory, thermal, feeding, parent, and outcome risk.', 'The handoff preserved evolving respiratory, airway-obstruction, thermal, glucose, feeding, infection, parent-dyad, escalation, disposition, and outcome uncertainty.'],
] as const;

export const MECONIUM_STAINED_TRANSITION: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'meconium-stained-transition', version: '0.1.0', maturity: 'preview', title: 'Meconium-stained transition: observe, do not suction routinely', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'introductory', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Lee HC, Strand ML, Finan E, et al. Part 5: Neonatal Resuscitation: 2025 American Heart Association and American Academy of Pediatrics Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care. Pediatrics. 2026;157(1):e2025074352.'] }, limitations: ['meconium-stained-transition-birth-fluid-newborn-parent-and-qualified-course-reports-are-authored', 'meconium-stained-transition-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-meconium-transition-exam-monitor-score-suction-airway-resuscitation-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'female', heightCm: 50, weightKg: 3.3, asaClass: 2, diagnosis: 'Supplied vigorous term transition after birth through thin meconium-stained fluid', procedure: 'selective-airway-clearing recognition, observation review, reassessment, and active-risk handoff practice', comorbidities: ['40 weeks 1 day by supplied obstetric dating; vaginal birth through thin meconium-stained amniotic fluid'], medications: ['No newborn medication has been administered'], allergies: ['No known allergies'], fasting: 'Feeding readiness and support remain qualified-team work', baseline: { heartRateBpm: 138, meanArterialMmHg: 46, strokeVolumeMl: 20, hemoglobinGPerDl: 17, bloodVolumeMl: 800, coreTemperatureC: 36.8, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Spontaneous strong cry with mouth and nose visible; no supplied airway obstruction' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 24, respiratoryRateBpm: 40, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'meconium-stained-transition-presentation', type: 'narrative', target: 'meconium-stained-transition', atTick: 0, severity: 'info', message: 'A 3.3 kg newborn girl has just been born vaginally at 40 weeks 1 day through thin meconium-stained amniotic fluid. At 30 seconds, qualified staff report spontaneous breathing with a strong cry, good flexed tone, heart rate 138/min, temperature 36.8°C, a visible mouth and nose, and no apparent airway obstruction or increased work of breathing. She is dried, warmly covered, and supervised skin-to-skin with her awake parent, who asks whether the meconium means she needs suctioning.' },
    { id: 'meconium-stained-transition-boundary', type: 'narrative', target: 'meconium-stained-transition-boundary', atTick: 0, severity: 'warning', message: 'Confirm trained newborn-capable and airway-ready attendance, shared clock, communication, dignity, and parent support. Connect gestation, birth, meconium character, breathing or crying, tone, heart rate, temperature, position, airway visibility, parent state, preferences, support, and whole dyad. Routine oral, nasal, or tracheal suctioning is not recommended solely because fluid is meconium stained. A newborn who breathes well or cries can remain in protected skin-to-skin transition care with warmth and ongoing respiratory observation. Qualified staff reserve airway clearing for apparent obstruction; when ventilation is required and appears obstructed, selective mouth or nose suction may be considered, and tracheal suction belongs only to the uncommon apparent tracheal-obstruction branch when ventilation remains ineffective despite corrective steps. A fixed qualified-team report at 30 minutes supplies regular breathing without apnea, grunting, retractions, or cyanosis; heart rate 132/min, preductal SpO2 96%, temperature 36.7°C, visible airway, and continued supervised skin-to-skin care. This snapshot does not exclude evolving meconium aspiration or other respiratory disease, prove durable safety, feeding success, disposition, or outcome. Controls do not examine, score, measure, monitor or interpret tests; position, dry, warm, suction or stimulate; separate; handle a device; give oxygen; ventilate; place or manage an airway; compress; obtain access; give fluid, glucose, drug or dose; feed; resuscitate; transport; counsel; perform another procedure; diagnose meconium aspiration; determine disposition; or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `meconium-stained-transition-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
