import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-neonatal-sepsis-newborn-infection-respiratory-circulatory-and-family-support', 'Activate newborn infection, respiratory, circulatory, and family support.', 'A trained newborn team, infection pathway, respiratory and circulatory support, shared clock, parent communication, dignity, and transfer ownership were confirmed first.'],
  ['reconcile-neonatal-sepsis-maternal-risk-clock-clinical-change-physiology-and-whole-dyad', 'Connect maternal risk, clock, clinical change, physiology, and the whole dyad.', 'The supplied maternal fever, rupture, GBS and antibiotic context, age, trajectory, temperature, breathing, perfusion, feeding, parent, and support facts were connected without learner history, examination, measurement, or test interpretation.'],
  ['recognize-clinically-ill-newborn-sepsis-risk-without-calculator-laboratory-or-diagnosis-closure', 'Recognize clinically ill newborn sepsis risk without calculator, laboratory, or diagnosis closure.', 'New multisystem clinical illness after relevant perinatal risk supported immediate qualified sepsis evaluation and treatment without letting a score or isolated test overrule the infant or claiming a diagnosis.'],
  ['review-qualified-neonatal-sepsis-culture-antimicrobial-support-investigation-and-reassessment-boundaries', 'Review qualified culture, antimicrobial, support, investigation, and reassessment boundaries.', 'Qualified culture before antibiotics when it does not delay care, locally protocolized empiric antimicrobials, respiratory, circulatory and thermal support, targeted investigation, serial reassessment, and stewardship boundaries were reviewed without learner care delivery.'],
  ['review-neonatal-sepsis-fixed-one-hour-qualified-report', 'Review the fixed 1-hour qualified-team report.', 'The authored partial physiologic response and pending-culture report was reviewed without claiming learner treatment, proven effect, excluded infection or meningitis, durable stability, disposition, or outcome.'],
  ['handoff-neonatal-sepsis-respiratory-circulatory-neurologic-culture-family-and-outcome-risk', 'Hand off respiratory, circulatory, neurologic, culture, family, and outcome risk.', 'The handoff preserved deterioration, shock, respiratory failure, meningitis, culture, antimicrobial, organ, glucose, feeding, family, stewardship, transfer, disposition, and outcome uncertainty.'],
] as const;

export const NEONATAL_SEPSIS: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'neonatal-sepsis', version: '0.1.0', maturity: 'preview', title: 'Neonatal sepsis: clinical change outranks a score', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 8, difficulty: 'intermediate', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Puopolo KM, Benitz WE, Zaoutis TE; AAP Committees on Fetus and Newborn and Infectious Diseases. Management of Neonates Born at 35 0/7 Weeks Gestation With Suspected or Proven Early-Onset Bacterial Sepsis. Pediatrics. 2018;142(6):e20182894.', 'National Institute for Health and Care Excellence. Neonatal infection: antibiotics for prevention and treatment (NG195). 2021, current online recommendations.'] }, limitations: ['neonatal-sepsis-maternal-risk-newborn-parent-and-qualified-course-reports-are-authored', 'neonatal-sepsis-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-neonatal-sepsis-history-exam-monitor-culture-antimicrobial-support-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'male', heightCm: 50, weightKg: 3.2, asaClass: 4, diagnosis: 'Supplied clinically ill term newborn with early-onset infection risk', procedure: 'clinical deterioration recognition, qualified sepsis-pathway boundary review, reassessment, and active-risk handoff practice', comorbidities: ['38 weeks 5 days; maternal intrapartum temperature 38.6°C, rupture of membranes 22 hours, GBS status unknown, maternal antibiotics 1 hour before birth'], medications: ['Qualified locally protocolized empiric neonatal antimicrobials begin only in the later authored report'], allergies: ['No known allergies'], fasting: 'Feeding ability, glucose, and nutrition support remain qualified-team work', baseline: { heartRateBpm: 172, meanArterialMmHg: 40, strokeVolumeMl: 20, hemoglobinGPerDl: 17, bloodVolumeMl: 800, coreTemperatureC: 35.9, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Spontaneous tachypnea with grunting and retractions; no supplied apnea or obstruction' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 24, respiratoryRateBpm: 40, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'neonatal-sepsis-presentation', type: 'narrative', target: 'neonatal-sepsis', atTick: 0, severity: 'critical', message: 'A 3.2 kg newborn boy is 10 hours old after birth at 38 weeks 5 days. Maternal records supply intrapartum temperature 38.6°C, rupture of membranes for 22 hours, unknown GBS status, and maternal antibiotics started 1 hour before birth. After initially regular transition, qualified staff now report lethargy, poor feeding, temperature 35.9°C, heart rate 172/min, respiratory rate 68/min with grunting and subcostal retractions, preductal SpO2 93% on room air, and capillary refill 4 seconds. No apnea, seizure, focal sign, rash, major blood loss, or known congenital anomaly is authored. No newborn culture, CRP, blood count, glucose, gas, imaging, or antimicrobial has yet been completed. His parent is present and frightened by the change.' },
    { id: 'neonatal-sepsis-boundary', type: 'narrative', target: 'neonatal-sepsis-boundary', atTick: 0, severity: 'critical', message: 'Confirm trained newborn, infection, respiratory, circulatory, airway-ready, laboratory, pharmacy, transport, and family support; shared clock; communication; dignity; and follow-up ownership. Connect maternal fever, rupture, GBS and antibiotic context, birth and deterioration clock, prior transition, new behavior and feeding change, temperature, breathing, oxygenation, perfusion, parent state, preferences, support, and whole dyad. New multisystem clinical illness after relevant perinatal risk requires immediate qualified sepsis evaluation and treatment; a risk calculator intended to support structured assessment cannot overrule a clinically ill infant, and no isolated blood count, CRP, or other laboratory result can diagnose or exclude early-onset sepsis. Qualified staff obtain blood culture before antibiotics when this does not delay treatment, begin locally protocolized empiric neonatal antimicrobials and respiratory, circulatory, glucose and thermal support, investigate targeted competing causes and meningitis when appropriate and safe, reassess serially, and narrow or stop therapy using the complete clinical and microbiologic trajectory. A fixed qualified-team report 1 hour after culture collection, empiric antimicrobials, warming, oxygen and circulatory support supplies temperature 36.5°C, heart rate 154/min, respiratory rate 58/min with persistent mild retractions, preductal SpO2 96% during reported support, capillary refill 3 seconds, glucose 68 mg/dL, and blood culture pending. This partial response does not prove treatment effect, diagnose sepsis, exclude bacteremia, meningitis, infection or another cause, establish durable stability, determine antimicrobial duration, transfer or disposition, or predict outcome. Controls do not take a history; examine, score, measure, monitor, obtain or interpret culture, CRP, blood count, glucose, gas, imaging, lumbar puncture or another test; calculate risk; diagnose; warm or cool; give oxygen; provide respiratory or circulatory support; obtain access; give fluid, glucose, antimicrobial, drug or dose; feed; handle a device; ventilate; place or manage an airway; resuscitate; transport; counsel; perform another procedure; determine antimicrobial selection or duration, transfer or disposition; or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `neonatal-sepsis-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
