import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-neonatal-bradycardia-qualified-compression-ventilation-clock-and-dyad-response', 'Activate qualified compression, ventilation, clock, and dyad response.', 'A trained advanced newborn-resuscitation team with explicit leadership, ventilation, compression, heart-rate, monitoring, timekeeping, recording, access-readiness, parent communication, dignity, and support ownership was activated first.'],
  ['reconcile-neonatal-bradycardia-adequate-ventilation-heart-rate-airway-oxygenation-and-whole-dyad', 'Connect adequate ventilation, heart rate, airway, oxygenation, and the whole dyad.', 'The supplied birth, ventilation-effectiveness, alternative-airway, heart-rate, oxygenation, thermal, parent, and support facts were connected without learner examination or procedure.'],
  ['recognize-neonatal-bradycardia-compression-threshold-after-adequate-ventilation', 'Recognize the compression threshold only after adequate ventilation.', 'Persistent heart rate below 60/min after 30 seconds of qualified ventilation that visibly inflated the lungs triggered the compression branch without skipping ventilation verification.'],
  ['review-qualified-neonatal-compression-ventilation-coordination-and-epinephrine-boundary', 'Review qualified compression-ventilation coordination and the epinephrine boundary.', 'Qualified coordinated support, airway and oxygen strategy, heart-rate reassessment, access readiness, and the later epinephrine boundary were reviewed without learner care delivery.'],
  ['review-neonatal-bradycardia-fixed-three-minute-qualified-response-report', 'Review the fixed 3-minute qualified-team response report.', 'The authored early response was reviewed without claiming learner resuscitation, universal treatment effect, durable recovery, disposition, or outcome.'],
  ['handoff-neonatal-bradycardia-respiratory-circulatory-neurologic-parent-and-outcome-risk', 'Hand off respiratory, circulatory, neurologic, parent, and outcome risk.', 'The handoff preserved recurrent bradycardia, ventilation, airway, oxygenation, perfusion, thermal, glucose, neurologic, etiologic, parent-dyad, escalation, disposition, and outcome uncertainty.'],
] as const;

export const NEONATAL_BRADYCARDIA: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'neonatal-bradycardia', version: '0.1.0', maturity: 'preview', title: 'Neonatal bradycardia: verify ventilation before compressions', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'intermediate', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Lee HC, Strand ML, Finan E, et al. Part 5: Neonatal Resuscitation: 2025 American Heart Association and American Academy of Pediatrics Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care. Pediatrics. 2026;157(1):e2025074352.'] }, limitations: ['neonatal-bradycardia-birth-ventilation-airway-parent-and-qualified-course-reports-are-authored', 'neonatal-bradycardia-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-neonatal-bradycardia-exam-monitor-ventilation-airway-compression-access-drug-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'male', heightCm: 48, weightKg: 3.1, asaClass: 3, diagnosis: 'Supplied persistent severe neonatal bradycardia after adequate qualified ventilation', procedure: 'compression-threshold recognition, qualified coordination review, reassessment, and active-risk handoff practice', comorbidities: ['39 weeks 1 day by supplied obstetric dating; emergency cesarean birth after placental abruption concern'], medications: ['No newborn medication has been administered'], allergies: ['No known allergies'], fasting: 'Newborn feeding readiness remains qualified-team work after stabilization', baseline: { heartRateBpm: 48, meanArterialMmHg: 40, strokeVolumeMl: 20, hemoglobinGPerDl: 16.5, bloodVolumeMl: 800, coreTemperatureC: 36.4, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.4, difficultMaskVentilation: false, assessment: 'Supplied qualified alternative airway with visible chest movement; placement and effectiveness remain direct-team findings' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'tracheal-tube', ventilator: { mode: 'manual', fio2: 1, tidalVolumeMl: 23, respiratoryRateBpm: 30, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'neonatal-bradycardia-presentation', type: 'narrative', target: 'neonatal-bradycardia-transition', atTick: 0, severity: 'critical', message: 'A 3.1 kg newborn boy is 2 minutes old after emergency cesarean birth at 39 weeks 1 day for placental-abruption concern. Qualified staff report apnea and persistent heart rate 48/min after ventilation correction, placement of an alternative airway, and 30 seconds of ventilation that visibly inflates the chest. Preductal SpO2 is 62% with a reliable signal and temperature is 36.4°C. The awake parent cannot see the newborn and asks whether his heart rate is improving.' },
    { id: 'neonatal-bradycardia-boundary', type: 'narrative', target: 'neonatal-bradycardia-transition-boundary', atTick: 0, severity: 'warning', message: 'Activate a trained advanced newborn-resuscitation team with leader, ventilation and airway owner, compression owner, heart-rate assessor, monitoring, timekeeping, recording, access and medication readiness, equipment, parent communication, dignity, and support roles. Connect birth and resuscitation clocks, completed initial steps, ventilation correction, alternative airway, visible chest movement, heart-rate trajectory, oxygenation signal, temperature, bleeding risk, parent state, preferences, support, and whole dyad. Chest compressions are indicated when heart rate remains below 60/min despite 30 seconds of ventilation that inflates the lungs; ventilation must be optimized before compressions. Qualified staff coordinate compressions and ventilation, reassess heart rate, maintain warmth, monitor oxygenation, and prepare access and epinephrine only for the later branch if heart rate does not reach 60/min after optimized ventilation and compressions. A fixed qualified-team report at 3 minutes supplies heart rate risen to 74/min after 60 seconds of coordinated compressions and ventilation, preductal SpO2 71% with the same reliable signal, and compressions stopped while assisted ventilation and direct assessment continue. This authored estimate does not prove durable circulation, breathing, stable transition, cause, neurologic safety, disposition, or outcome. Controls do not examine, score, measure, monitor or interpret tests; position, suction or stimulate; handle a mask or device; choose or deliver oxygen, pressure, rate or PEEP; ventilate; place or verify an airway; compress; obtain access; give fluid, blood, glucose, epinephrine or another drug or dose; feed; resuscitate; transport; counsel; perform another procedure; determine disposition; or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `neonatal-bradycardia-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
