import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-neonatal-apnea-qualified-newborn-airway-clock-and-dyad-support', 'Activate qualified newborn, airway, clock, and dyad support.', 'A trained ventilation-capable newborn team, leader, airway owner, heart-rate assessor, timekeeper, recorder, parent communication, dignity, and support ownership were activated first.'],
  ['reconcile-neonatal-apnea-gestation-birth-clock-breathing-heart-rate-tone-temperature-and-whole-dyad', 'Connect gestation, birth clock, breathing, heart rate, tone, temperature, and the whole dyad.', 'The supplied antenatal, intrapartum, birth, initial-step, breathing, heart-rate, tone, thermal, parent, preference, and support facts were connected without learner examination or scoring.'],
  ['recognize-neonatal-apnea-ventilation-threshold-without-cause-or-outcome-closure', 'Recognize the neonatal apnea ventilation threshold without cause or outcome closure.', 'Persistent apnea after initial steps and a supplied heart rate below 100/min triggered ventilation-priority review while causes and outcomes stayed open.'],
  ['review-neonatal-apnea-qualified-effective-ventilation-heart-rate-and-escalation-readiness', 'Review qualified effective ventilation, heart-rate response, and escalation readiness.', 'Qualified assisted ventilation within the first minute, chest movement, heart-rate response, oxygen and airway escalation readiness, warmth, monitoring, and parent communication were reviewed without learner care delivery.'],
  ['review-neonatal-apnea-fixed-ninety-second-qualified-response-report', 'Review the fixed 90-second qualified-team response report.', 'The authored early response was reviewed without claiming learner ventilation, durable breathing, stable transition, neurologic safety, disposition, or outcome.'],
  ['handoff-neonatal-apnea-respiratory-thermal-glucose-neurologic-parent-and-outcome-risk', 'Hand off respiratory, thermal, glucose, neurologic, parent, and outcome risk.', 'The handoff preserved recurrent apnea, ventilation effectiveness, respiratory, oxygenation, airway, heart-rate, thermal, glucose, neurologic, etiologic, parent-dyad, surveillance, disposition, and outcome uncertainty.'],
] as const;

export const NEONATAL_APNEA: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'neonatal-apnea', version: '0.1.0', maturity: 'preview', title: 'Neonatal apnea: ventilation is the priority', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'introductory', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Lee HC, Strand ML, Finan E, et al. Part 5: Neonatal Resuscitation: 2025 American Heart Association and American Academy of Pediatrics Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care. Pediatrics. 2026;157(1):e2025074352.'] }, limitations: ['neonatal-apnea-birth-initial-step-newborn-parent-and-qualified-course-reports-are-authored', 'neonatal-apnea-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-neonatal-apnea-exam-monitor-score-ventilation-oxygen-airway-drug-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'male', heightCm: 51, weightKg: 3.5, asaClass: 2, diagnosis: 'Supplied term neonatal apnea after initial steps with heart rate below 100/min', procedure: 'ventilation-threshold recognition, qualified response review, reassessment, and active-risk handoff practice', comorbidities: ['39 weeks 2 days by supplied obstetric dating; urgent vaginal birth after a prolonged fetal-heart deceleration'], medications: ['No newborn medication has been administered'], allergies: ['No known allergies'], fasting: 'Newborn feeding readiness remains qualified-team work after stabilization', baseline: { heartRateBpm: 92, meanArterialMmHg: 44, strokeVolumeMl: 20, hemoglobinGPerDl: 17, bloodVolumeMl: 800, coreTemperatureC: 36.6, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Apneic after qualified initial steps with no supplied airway obstruction; qualified ventilation-capable team is present' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 25, respiratoryRateBpm: 40, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'neonatal-apnea-presentation', type: 'narrative', target: 'neonatal-apnea-transition', atTick: 0, severity: 'critical', message: 'A 3.5 kg newborn boy has just been born vaginally at 39 weeks 2 days after a prolonged fetal-heart deceleration. A prepared newborn team reports warmth, positioning, drying, stimulation, and airway assessment completed by qualified staff. At 40 seconds after birth he remains apneic without sustained crying; supplied heart rate is 92/min, tone is reduced, temperature is 36.6°C, and no airway obstruction is reported. The awake parent can see the team and asks what is happening.' },
    { id: 'neonatal-apnea-boundary', type: 'narrative', target: 'neonatal-apnea-transition-boundary', atTick: 0, severity: 'warning', message: 'Activate a trained ventilation-capable newborn team with leader, airway and ventilation owner, heart-rate assessor, timekeeper, recorder, equipment check, parent communication, dignity, and support. Connect gestation, antenatal and intrapartum risks, birth method and clock, cord status, completed initial steps, breathing, heart rate, tone, temperature, position, airway assessment, parent state, preferences, support, and whole dyad. A newborn who does not breathe within the first 60 seconds or has a heart rate below 100/min despite initial steps should receive assisted ventilation; effective lung ventilation, indicated by a rising heart rate, is the priority. Qualified staff begin assisted ventilation before 60 seconds, assess chest movement and heart-rate response, maintain warmth, monitor oxygenation and heart rate, and prepare ventilation-corrective steps, alternative airway, oxygen titration, compressions, access, medication, and transfer only if the evolving response indicates them. A fixed qualified-team report at 90 seconds supplies visible chest movement, heart rate risen to 126/min, and spontaneous irregular respirations emerging while assisted ventilation and direct assessment continue. This early response does not prove durable spontaneous breathing, stable transition, neurologic safety, cause, disposition, or outcome. Controls do not examine, score, measure, monitor or interpret tests; position, dry, warm, suction or stimulate; separate; give oxygen; ventilate; manage an airway; perform corrective steps or compressions; obtain access; give fluid, glucose, drug or dose; feed; resuscitate; transport; counsel; perform another procedure; determine disposition; or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `neonatal-apnea-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
