import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-preterm-respiratory-distress-newborn-respiratory-thermal-and-family-support', 'Activate newborn respiratory, thermal, and family support.', 'A trained preterm-newborn team, CPAP-capable support, shared clock, thermal plan, parent communication, dignity, and transfer ownership were confirmed first.'],
  ['reconcile-preterm-respiratory-distress-gestation-breathing-work-heart-rate-oxygenation-temperature-and-whole-dyad', 'Connect gestation, breathing, work, heart rate, oxygenation, temperature, and the whole dyad.', 'The supplied gestation, birth clock, spontaneous breathing, work, heart rate, preductal oxygenation, thermal, parent, and support facts were connected without learner examination or monitoring interpretation.'],
  ['recognize-spontaneously-breathing-preterm-respiratory-distress-suitable-for-qualified-initial-cpap', 'Recognize spontaneously breathing preterm respiratory distress suitable for qualified initial CPAP.', 'Spontaneous breathing with grunting, retractions, adequate heart rate, and low preductal saturation supported a qualified CPAP-first branch without routine intubation or false stability.'],
  ['review-qualified-cpap-oxygen-thermal-monitoring-and-escalation-boundaries', 'Review qualified CPAP, oxygen, thermal, monitoring, and escalation boundaries.', 'Qualified CPAP, preductal pulse-oximetry-guided oxygen titration, wrap and hat thermal protection, temperature surveillance, and apnea or ineffective-breathing escalation boundaries were reviewed without learner care delivery.'],
  ['review-preterm-respiratory-distress-fixed-ten-minute-qualified-report', 'Review the fixed 10-minute qualified-team report.', 'The authored respiratory and thermal report was reviewed without claiming learner care, durable response, excluded disease, disposition, or outcome.'],
  ['handoff-preterm-respiratory-distress-breathing-oxygen-thermal-glucose-infection-family-and-outcome-risk', 'Hand off breathing, oxygen, thermal, glucose, infection, family, and outcome risk.', 'The handoff preserved evolving respiratory failure, apnea, oxygen exposure, air leak, thermal, glucose, infection, family, escalation, transfer, disposition, and outcome uncertainty.'],
] as const;

export const PRETERM_RESPIRATORY_DISTRESS: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'preterm-respiratory-distress', version: '0.1.1', maturity: 'preview', title: 'Preterm respiratory distress: support spontaneous breathing', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 7, difficulty: 'introductory', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.1', sources: ['Lee HC, Strand ML, Finan E, et al. Part 5: Neonatal Resuscitation: 2025 American Heart Association and American Academy of Pediatrics Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care. Pediatrics. 2026;157(1):e2025074352.', 'Wyckoff MH, Greif R, Morley PT, et al. Neonatal Life Support: 2025 International Liaison Committee on Resuscitation Consensus on Science With Treatment Recommendations. Pediatrics. 2026;157(1):e2025074766.'] }, limitations: ['preterm-respiratory-distress-gestation-newborn-parent-and-qualified-course-reports-are-authored', 'preterm-respiratory-distress-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-preterm-newborn-exam-monitor-score-cpap-oxygen-thermal-airway-resuscitation-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'male', heightCm: 40, weightKg: 2, asaClass: 3, diagnosis: 'Supplied spontaneous breathing with respiratory distress after birth at 29 weeks 4 days', procedure: 'preterm respiratory-support recognition, boundary review, reassessment, and active-risk handoff practice', comorbidities: ['29 weeks 4 days by supplied obstetric dating; cesarean birth after maternal severe preeclampsia'], medications: ['No newborn medication has been administered'], allergies: ['No known allergies'], fasting: 'Nutrition and glucose support remain qualified-team work', baseline: { heartRateBpm: 154, meanArterialMmHg: 40, strokeVolumeMl: 20, hemoglobinGPerDl: 17, bloodVolumeMl: 800, coreTemperatureC: 36.5, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.3, difficultMaskVentilation: false, assessment: 'Spontaneous breathing with grunting and retractions; no supplied apnea or airway obstruction' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.3, tidalVolumeMl: 8, respiratoryRateBpm: 40, freshGasFlowLPerMin: 5, delivering: false } }, formulary: [],
  timeline: [
    { id: 'preterm-respiratory-distress-presentation', type: 'narrative', target: 'preterm-respiratory-distress', atTick: 0, severity: 'warning', message: 'A 1.25 kg newborn boy has just been born by cesarean delivery at 29 weeks 4 days after maternal severe preeclampsia. At 90 seconds, qualified staff report spontaneous breathing, grunting, intercostal and subcostal retractions, heart rate 154/min, respiratory rate 68/min, preductal SpO2 62%, and temperature 36.5°C. No apnea, gasping, apparent airway obstruction, cyanotic congenital anomaly, or major blood loss is authored. He is under a radiant warmer in a plastic wrap and hat. The parent is awake and asks what support he needs.' },
    { id: 'preterm-respiratory-distress-boundary', type: 'narrative', target: 'preterm-respiratory-distress-boundary', atTick: 0, severity: 'warning', message: 'Confirm trained preterm-newborn, CPAP-capable, airway-ready, thermal, transport, and family support; shared clock; communication; and dignity. Connect gestation, birth, spontaneous breathing, work of breathing, heart rate, preductal oxygenation, temperature, parent state, preferences, support, and whole dyad. For a spontaneously breathing preterm infant requiring respiratory support, qualified initial CPAP is reasonable rather than routine intubation and mechanical ventilation. Preductal pulse oximetry guides oxygen titration; for less than 32 weeks, 30% to 100% is a reasonable initial range, and this case authors a qualified-team 30% start rather than a universal prescription. Plastic wrap, head covering, and careful temperature monitoring address hypothermia while avoiding hyperthermia. Apnea, gasping, heart rate below 100/min, or ineffective breathing belongs to the positive-pressure-ventilation escalation branch, not this CPAP-only lesson. A fixed qualified-team report at 10 minutes supplies ongoing CPAP, oxygen titrated to 35%, preductal SpO2 90%, heart rate 148/min, respiratory rate 62/min, temperature 36.6°C, persistent mild grunting and retractions, and no observed apnea. This snapshot does not prove adequate ventilation, exclude respiratory distress syndrome, infection, air leak, congenital disease, or other pathology, establish durable stability, determine transfer or disposition, or predict outcome. Controls do not examine, score, measure, monitor or interpret tests; dry, stimulate, position, wrap, warm or cool; handle CPAP, oxygen, pulse oximetry, ventilation or another device; select or change settings; suction; place or manage an airway; compress; obtain access; give fluid, glucose, surfactant, drug or dose; feed; resuscitate; transport; counsel; perform another procedure; diagnose; determine disposition; or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `preterm-respiratory-distress-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
