import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-term-newborn-transition-prepared-newborn-and-dyad-support', 'Activate prepared newborn and parent-dyad support.', 'A trained newborn-capable clinician, birth team, timekeeper, family communication, dignity, and support ownership were confirmed first.'],
  ['reconcile-term-newborn-transition-gestation-birth-breathing-tone-heart-rate-temperature-and-whole-dyad', 'Connect gestation, birth, breathing, tone, heart rate, temperature, and the whole dyad.', 'The supplied antenatal, intrapartum, birth-clock, breathing, tone, heart-rate, thermal, parent, preference, and support facts were connected without learner examination or scoring.'],
  ['recognize-term-newborn-transition-without-resuscitation-or-well-newborn-closure', 'Recognize normal term transition without resuscitation or well-newborn closure.', 'Breathing or crying, good tone, and adequate heart rate supported ongoing transition care while apnea, respiratory difficulty, thermal instability, and other evolving risk stayed visible.'],
  ['review-term-newborn-transition-qualified-cord-skin-to-skin-thermal-and-observation-care', 'Review qualified cord, skin-to-skin, thermal, and observation care.', 'Qualified deferred cord clamping, drying, protected skin-to-skin positioning, warm covering, airway visibility, breathing and temperature observation, and feeding support were reviewed without learner care delivery.'],
  ['review-term-newborn-transition-fixed-one-hour-qualified-report', 'Review the fixed 1-hour qualified-team report.', 'The authored stable transition report was reviewed without claiming a learner intervention, durable safety, discharge readiness, feeding success, or outcome.'],
  ['handoff-term-newborn-transition-breathing-temperature-feeding-parent-and-outcome-risk', 'Hand off breathing, temperature, feeding, parent, and outcome risk.', 'The handoff preserved apnea, respiratory difficulty, thermal, glucose and feeding, infection, jaundice, parent-dyad, surveillance, escalation, disposition, and outcome uncertainty.'],
] as const;

export const TERM_NEWBORN_TRANSITION: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'term-newborn-transition', version: '0.1.0', maturity: 'preview', title: 'Term newborn transition: protect the quiet start', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'introductory', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Lee HC, Strand ML, Finan E, et al. Part 5: Neonatal Resuscitation: 2025 American Heart Association and American Academy of Pediatrics Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care. Pediatrics. 2026;157(1):e2025074352.', 'International Liaison Committee on Resuscitation Neonatal Life Support Task Force. Neonatal Life Support: 2025 International Consensus on Cardiopulmonary Resuscitation and Emergency Cardiovascular Care Science With Treatment Recommendations. Pediatrics. 2026;157(1):e2025074766.'] }, limitations: ['term-newborn-transition-antenatal-birth-newborn-parent-and-qualified-course-reports-are-authored', 'term-newborn-transition-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-term-newborn-exam-monitor-score-cord-care-resuscitation-feeding-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'female', heightCm: 50, weightKg: 3.4, asaClass: 1, diagnosis: 'Supplied uncomplicated term newborn transition after vaginal birth', procedure: 'normal-transition recognition, qualified protective-care review, reassessment, and active-risk handoff practice', comorbidities: ['39 weeks 4 days by supplied obstetric dating; singleton cephalic vaginal birth after uncomplicated labour'], medications: ['No newborn medication has been administered'], allergies: ['No known allergies'], fasting: 'Newborn feeding readiness and support remain qualified-team work', baseline: { heartRateBpm: 142, meanArterialMmHg: 46, strokeVolumeMl: 20, hemoglobinGPerDl: 17, bloodVolumeMl: 800, coreTemperatureC: 36.8, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.1, difficultMaskVentilation: false, assessment: 'Spontaneously breathing or crying with good tone; mouth and nose remain visible during supported skin-to-skin care' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 24, respiratoryRateBpm: 40, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'term-newborn-transition-presentation', type: 'narrative', target: 'term-newborn-transition', atTick: 0, severity: 'info', message: 'A 3.4 kg newborn girl has just been born vaginally at 39 weeks 4 days after an uncomplicated labour. Qualified staff report spontaneous breathing and a strong cry, good flexed tone, heart rate 142/min, temperature 36.8°C, and no antenatal or intrapartum risk factor requiring immediate resuscitation. She is skin-to-skin on her awake parent, dried and covered with a warm blanket while her mouth and nose remain visible. The cord is intact and the shared birth clock reads 20 seconds. The parent asks whether everything is all right.' },
    { id: 'term-newborn-transition-boundary', type: 'narrative', target: 'term-newborn-transition-boundary', atTick: 0, severity: 'warning', message: 'Confirm a trained and equipped newborn-capable clinician, birth-team roles, shared clock, communication, dignity, and family support. Connect gestation, antenatal and intrapartum risks, birth method and clock, breathing or crying, tone, heart rate, color in context, temperature, position, airway visibility, parent state, preferences, support, and whole dyad. Most newborns do not need resuscitation: a term newborn who is breathing or crying with good tone and an adequate heart rate can receive deferred cord clamping for at least 60 seconds in most instances, prompt drying, protected skin-to-skin care, warm coverings, ongoing breathing and temperature evaluation, and feeding support. Low oxygen saturation is expected in the first minutes and is not interpreted alone; suction, separation, supplemental oxygen, stimulation, ventilation, drugs, or another resuscitation step are not routine in this supplied stable pattern. A fixed qualified-team report at 1 hour supplies uninterrupted supervised skin-to-skin care, regular breathing without apnea or increased work, heart rate 136/min, axillary temperature 36.7°C, visible airway, and feeding cues with qualified feeding support beginning. This snapshot does not prove durable respiratory or thermal safety, glucose stability, feeding success, discharge readiness, or outcome. Controls do not examine, score, measure, monitor or interpret tests, clamp or cut the cord, position, dry, warm, suction, stimulate, separate, give oxygen, ventilate, manage an airway, perform compressions, obtain access, give fluid, glucose, drug or dose, feed, resuscitate, transport, counsel, perform another procedure, determine disposition, or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `term-newborn-transition-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
