import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-neonatal-thermoregulation-newborn-thermal-glucose-feeding-and-family-support', 'Activate newborn thermal, glucose, feeding, and family support.', 'A trained newborn team, thermal and glucose pathway, feeding and escalation support, shared clock, parent communication, dignity, and follow-up ownership were confirmed first.'],
  ['reconcile-neonatal-thermoregulation-gestation-admission-temperature-environment-trajectory-physiology-and-whole-dyad', 'Connect gestation, admission temperature, environment, trajectory, physiology, and the whole dyad.', 'The supplied gestation, size, admission and current temperature, transfer and warming-continuity gap, behavior, feeding, breathing, glucose, parent, and support facts were connected without learner history, examination, measurement, or test interpretation.'],
  ['recognize-unintentional-neonatal-hypothermia-requiring-qualified-rewarming-without-rate-cause-or-diagnosis-closure', 'Recognize unintentional neonatal hypothermia requiring qualified rewarming without rate, cause, or diagnosis closure.', 'Verified axillary temperature 35.5°C after an initially normal admission value supported immediate qualified rewarming and evaluation without prescribing an unsupported rate, overlooking illness, or claiming a diagnosis.'],
  ['review-qualified-neonatal-rewarming-monitoring-glucose-feeding-cause-and-hyperthermia-prevention-boundaries', 'Review qualified rewarming, monitoring, glucose, feeding, cause, and hyperthermia-prevention boundaries.', 'Locally protocolized warm-chain restoration, frequent or continuous temperature monitoring, glucose and feeding protection, cause review, serial reassessment, and hyperthermia prevention were reviewed without learner care delivery.'],
  ['review-neonatal-thermoregulation-fixed-forty-five-minute-qualified-report', 'Review the fixed 45-minute qualified-team report.', 'The authored partial temperature and clinical trajectory was reviewed without claiming learner treatment, a prescribed rewarming rate, proven effect, excluded illness, durable stability, disposition, or outcome.'],
  ['handoff-neonatal-thermoregulation-temperature-glucose-feeding-infection-neurologic-family-and-outcome-risk', 'Hand off temperature, glucose, feeding, infection, neurologic, family, and outcome risk.', 'The handoff preserved recurrent hypothermia, overheating, glucose, feeding, respiratory, infection, neurologic, environment, family, transfer, disposition, and outcome uncertainty.'],
] as const;

export const THERMOREGULATION_FAILURE: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'thermoregulation-failure', version: '0.1.0', maturity: 'preview', title: 'Thermoregulation failure: restore the warm chain', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 7, difficulty: 'introductory', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['American Heart Association and American Academy of Pediatrics. Part 5: Neonatal Resuscitation: 2025 Guidelines for Cardiopulmonary Resuscitation and Emergency Cardiovascular Care. Pediatrics. 2026;157(1):e2025074352.', 'World Health Organization. Thermal protection of the newborn: a practical guide. WHO_RHT_MSM_97.2. 1997.'] }, limitations: ['neonatal-thermoregulation-gestation-temperature-environment-parent-and-qualified-course-reports-are-authored', 'neonatal-thermoregulation-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-neonatal-thermoregulation-exam-temperature-monitor-warming-glucose-feed-procedure-disposition-or-outcome'] },
  patient: { ageYears: 0, sex: 'female', heightCm: 46, weightKg: 2.4, asaClass: 3, diagnosis: 'Supplied unintentional neonatal hypothermia after a warming-continuity gap', procedure: 'thermal-risk recognition, qualified rewarming-boundary review, reassessment, and active-risk handoff practice', comorbidities: ['35 weeks 4 days; admission axillary temperature 36.6°C before a supplied transfer and warming-continuity gap'], medications: [], allergies: ['No known allergies'], fasting: 'Feeding ability, glucose, and nutrition support remain qualified-team work', baseline: { heartRateBpm: 126, meanArterialMmHg: 42, strokeVolumeMl: 20, hemoglobinGPerDl: 17, bloodVolumeMl: 800, coreTemperatureC: 35.5, arterialStiffness: 0.6, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Spontaneous regular breathing without supplied apnea, obstruction, or increased work' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 24, respiratoryRateBpm: 40, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'thermoregulation-failure-presentation', type: 'narrative', target: 'thermoregulation-failure', atTick: 0, severity: 'warning', message: 'A 2.4 kg newborn girl is 3 hours old after birth at 35 weeks 4 days. Qualified records supply admission axillary temperature 36.6°C, followed by a transfer and warming-continuity gap. A repeated verified axillary temperature is now 35.5°C. Staff report sleepiness and difficulty sustaining a feed, heart rate 126/min, respiratory rate 48/min with regular breathing and no increased work, preductal SpO2 97% on room air, capillary refill 3 seconds, and glucose 58 mg/dL. No apnea, cyanosis, seizure, focal sign, fever, rash, major blood loss, known congenital anomaly, or eligibility for therapeutic hypothermia is authored. Her parent is present and distressed that she became cold.' },
    { id: 'thermoregulation-failure-boundary', type: 'narrative', target: 'thermoregulation-failure-boundary', atTick: 0, severity: 'warning', message: 'Confirm trained newborn, thermal, glucose, feeding, respiratory, escalation, and family support; shared clock; communication; dignity; and follow-up ownership. Connect gestation, size, admission and current temperature, measurement site and repeat, environment, transfer and warming continuity, behavior, feeding, breathing, oxygenation, perfusion, glucose, parent state, preferences, support, and whole dyad. A verified axillary temperature of 35.5°C after an initially normal value requires immediate qualified rewarming and evaluation. Restore the warm chain using the current local protocol, monitor temperature frequently or continuously, protect glucose and feeding, review environmental and clinical causes including infection, reassess the whole newborn, and avoid hyperthermia. Evidence does not support prescribing one optimal rapid or slow rewarming rate. Therapeutic hypothermia is a separate strictly protocolized pathway for eligible hypoxic-ischemic encephalopathy and is not authored here. A fixed qualified-team report after 45 minutes of locally protocolized rewarming supplies axillary temperature 36.3°C, heart rate 134/min, respiratory rate 44/min with regular breathing, preductal SpO2 97% on room air, capillary refill 2 seconds, glucose 64 mg/dL, improved alertness, and feeding assessment continuing. This partial trajectory remains below the normal temperature range and does not prescribe a rewarming rate, prove treatment effect, determine cause, exclude infection or other illness, establish durable thermal or glucose stability, prove feeding success, determine disposition, or predict outcome. Controls do not take a history; examine, score, measure, monitor, obtain or interpret temperature, glucose or another test; diagnose; warm or cool; use skin-to-skin care; operate an incubator, radiant warmer or another device; select a set point or rewarming rate; feed; give glucose, fluid, drug or dose; obtain access; give oxygen; provide respiratory support; ventilate; place or manage an airway; resuscitate; transport; counsel; perform another procedure; determine disposition; or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `thermoregulation-failure-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
