/** Septic shock: a label the treatment creates rather than one the patient arrives with. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const SEPTIC_SHOCK_A_LABEL_THE_TREATMENT_CREATES: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'septic-shock-a-label-the-treatment-creates', version: '0.1.1', maturity: 'preview',
    title: 'Septic shock: a label the treatment creates', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 8, difficulty: 'advanced', objectives: [
      { id: 'reconcile-infectious-disease-septic-shock-hypoperfusion-before-any-label', statement: 'Reconcile measured hypoperfusion before any label.', measure: 'Mean arterial pressure 60 mmHg, heart rate 118/min, lactate 3.6 mmol/L, capillary refill 4.1 s, and no vasopressor running were recorded as measured, without learner history, examination, sampling, classification, or treatment selection.' },
      { id: 'recognize-infectious-disease-septic-shock-two-criteria-have-no-truth-value-yet', statement: 'Recognize that two criteria have no truth value yet.', measure: 'The classification was recorded as open with its reason: vasopressor dependence and a post-resuscitation lactate cannot be evaluated before the resuscitation has happened, so the label is not withheld out of caution but is genuinely not yet decidable.' },
      { id: 'activate-infectious-disease-septic-shock-critical-care-on-the-pattern-not-the-name', statement: 'Activate critical care on the pattern, not the name.', measure: 'Critical care was activated on the perfusion pattern with monitoring arranged, and declaring the label early, reading the lactate as hypoxia, resuscitating to a normal lactate, and raising the pressure target were each refused.' },
      { id: 'review-infectious-disease-septic-shock-targets-and-their-grades', statement: 'Review the targets with their grades attached.', measure: 'A mean pressure target of 65 mmHg over higher targets on moderate certainty, an initial range of 60 to 65 mmHg for patients 65 or older on low certainty, at least 30 mL/kg of crystalloid as a conditional suggestion on low certainty, fluids before vasopressors on very low certainty with a carve-out for unstable shock, and serial lactate guiding decrement rather than normalization were all kept explicit.' },
      { id: 'record-infectious-disease-septic-shock-bounded-intent-that-is-also-the-measurement', statement: 'Record bounded intent that is also the measurement.', measure: 'Resuscitation intent was recorded without selecting a fluid volume, rate, vasoactive agent, dose, or endpoint; the completed authored trial then held the mean pressure at 68 mmHg on vasopressor support with a lactate of 3.1 mmol/L, making all three parts of the definition readable for the first time.' },
      { id: 'handoff-infectious-disease-septic-shock-a-label-that-reflects-a-treatment', statement: 'Hand off a label that reflects a treatment.', measure: 'The handoff preserved the measured state before treatment, the recorded reason the classification was open, whether intent fell inside the one-hour ceiling, and that the label reflects a treatment as much as a patient, with organism, treatment effect, and outcome left uncertified.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.1', sources: [
        'Singer M, Deutschman CS, Seymour CW, et al. The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3). JAMA. 2016;315(8):801-810. doi:10.1001/jama.2016.0287. Box 3: septic shock is identified by a clinical construct of sepsis with persisting hypotension requiring vasopressors to maintain MAP >= 65 mmHg and a serum lactate > 2 mmol/L despite adequate volume resuscitation. The task force states that criteria for adequate fluid resuscitation and for need for vasopressor therapy could not be explicitly specified because these are highly user dependent.',
        'Prescott HC, Antonelli M, Alhazzani W, et al. Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock 2026. Crit Care Med. Published 2026-03-23. doi:10.1097/CCM.0000000000007075. Initial MAP target 65 mmHg over higher targets, strong recommendation, moderate certainty; for adults 65 or older an initial range of 60 to 65 mmHg, conditional, low certainty; at least 30 mL/kg crystalloid in the first 3 hours, conditional, low certainty; initial crystalloid followed by vasopressor support if hypotension persists, conditional, very low certainty, with a carve-out for concurrent vasopressors in unstable shock; serial lactate to guide resuscitation, conditional, low certainty, individualized after the initial bolus by lactate decrement rather than continuing fluids until normalization. Statement numbers were not retrievable; wording taken from the issuing society guideline page.',
        'Levy B. Lactate and shock state: the metabolic view. Curr Opin Crit Care. 2006. PMID 18323749. Hyperlactatemia in sepsis is substantially driven by epinephrine-stimulated aerobic glycolysis in skeletal muscle and by reduced hepatic clearance, so an elevated lactate is not a direct reading of tissue oxygen debt.',
      ] },
    limitations: ['septic-shock-presentation-and-trial-response-are-authored',
      'septic-shock-controls-are-recording-and-bounded-intent-only',
      'septic-shock-targets-are-comparative-and-low-certainty'],
  },
  patient: {
    ageYears: 71, sex: 'male', heightCm: 174, weightKg: 78, asaClass: 3,
    diagnosis: 'Authored infection-associated hypoperfusion whose septic shock classification is undecidable before resuscitation',
    procedure: 'calm measurement recording, open classification, bounded resuscitation intent, and handoff practice',
    comorbidities: ['Hypertension; unwell for two days with fever, rigors, and reduced oral intake'],
    medications: ['Fluid, vasoactive, antimicrobial, and steroid decisions remain qualified-team work'],
    allergies: ['No known drug allergies'], fasting: 'Not relevant to the infectious-disease fixture',
    baseline: { heartRateBpm: 118, meanArterialMmHg: 60, strokeVolumeMl: 52,
      hemoglobinGPerDl: 11.8, bloodVolumeMl: 5_100, coreTemperatureC: 38.9,
      arterialStiffness: 1.3, baroreflexGain: 0.5, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Drowsy but rousable, protecting the airway in the supplied fixture' },
    respiratory: { profile: 'healthy' },
  },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask',
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 480, respiratoryRateBpm: 12,
      freshGasFlowLPerMin: 10, delivering: false } }, formulary: [],
  timeline: [
    { id: 'septic-shock-presentation', type: 'narrative', target: 'septic-shock', atTick: 0,
      severity: 'warning', message: 'A 71-year-old with hypertension has been unwell for two days with fever, rigors, and reduced oral intake. Authored monitor state is sinus tachycardia 118/min, BP 84/48 mmHg (mean 60), RR 26/min, SpO2 94% in air, and T 38.9 C. He is drowsy but rousable and protecting his airway. No vasopressor is running and no fluid resuscitation has completed. There is no authored airway compromise, rash, focal neurologic deficit, or hemorrhage.' },
    { id: 'septic-shock-evidence', type: 'narrative', target: 'septic-shock-evidence', atTick: 0,
      severity: 'warning', message: 'Supplied laboratory evidence is lactate 3.6 mmol/L, white cells 17.1 x10^9/L, creatinine 132 µmol/L, and base excess -6.1 mmol/L, with capillary refill 4.1 s. This is hypoperfusion with infection suspected. It is not yet septic shock, and that is a statement about the definition rather than about the severity: septic shock requires vasopressors to maintain a mean arterial pressure at or above 65 mmHg and a lactate above 2 mmol/L despite adequate fluid resuscitation. No vasopressor is running and no resuscitation has completed, so two of those three parts have no truth value yet. The consensus task force that wrote the definition stated that criteria for adequate fluid resuscitation and for need for vasopressor therapy could not be explicitly specified, because they are highly user dependent.' },
    { id: 'septic-shock-boundary', type: 'narrative', target: 'septic-shock-boundary', atTick: 0,
      severity: 'warning', message: 'Record the hypoperfusion as measured; activate critical care on the perfusion pattern rather than on a label, because the team is needed before the name is settled; record the classification as open with its reason; record bounded qualified-team resuscitation intent inside the one-hour ceiling this tier carries; review the targets with their grades attached; and arrange continuous monitoring, because the trial is also the measurement and an unmonitored trial measures nothing. Applying the label now, reading the lactate as a measure of tissue hypoxia, continuing fluids until the lactate normalizes, and raising the mean pressure target above 65 mmHg are all refused. No fluid volume, rate, vasoactive agent, dose, endpoint, antimicrobial, steroid, or procedure is exposed. After elapsed simulated time from the recorded intent, the authored resuscitation completes: the mean pressure is held at 68 mmHg on vasopressor support and the lactate remains 3.1 mmol/L, so all three parts of the definition become readable together for the first time. The label did not arrive with the patient; it arrived with the treatment, and a different team treating differently could have produced a different label for the same person. That is a property of the definition, not a failure of care. If one hour elapses with no resuscitation intent recorded, the ceiling is reported as passed rather than hidden. An initial mean pressure target of 65 mmHg is recommended over higher targets on moderate certainty, and 60 to 65 mmHg is suggested for adults 65 or older on low certainty, so the target is a floor with a tolerance band rather than a proven optimum. An elevated lactate in sepsis reflects adrenergically stimulated aerobic glycolysis and reduced hepatic clearance as well as perfusion, so it is not an oxygen-debt meter. No individualized effect, treatment causality, organism, source confirmation, eligibility, disposition, prognosis, or outcome is reported. Qualified teams retain fluid and vasoactive decisions, the antimicrobial pathway, source control, steroid questions, and all treatment decisions. After another elapsed interval, hand off the measured state before treatment, the recorded reason the classification was open, whether intent fell inside the ceiling, disposition, and outcome uncertainty. The controls do not take history; examine; acquire or interpret observations, laboratory, imaging, or another test; classify; diagnose; select or deliver a drug, dose, route, fluid, oxygen, or device; perform a procedure; determine eligibility, disposition, or prognosis; or predict response, organism, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'septic-shock-trajectory', objectiveId: 'reconcile-infectious-disease-septic-shock-hypoperfusion-before-any-label', question: 'What was measurable before any treatment had run?' },
    { id: 'septic-shock-recognition', objectiveId: 'recognize-infectious-disease-septic-shock-two-criteria-have-no-truth-value-yet', question: 'Which parts of the definition could not be evaluated yet, and why?' },
    { id: 'septic-shock-activation', objectiveId: 'activate-infectious-disease-septic-shock-critical-care-on-the-pattern-not-the-name', question: 'Why does activation not wait for the classification?' },
    { id: 'septic-shock-boundaries', objectiveId: 'review-infectious-disease-septic-shock-targets-and-their-grades', question: 'What does each target recommend, and on what certainty of evidence?' },
    { id: 'septic-shock-reassessment', objectiveId: 'record-infectious-disease-septic-shock-bounded-intent-that-is-also-the-measurement', question: 'What did the completed trial make readable that was not readable before?' },
    { id: 'septic-shock-handoff', objectiveId: 'handoff-infectious-disease-septic-shock-a-label-that-reflects-a-treatment', question: 'In what sense does this label describe the treatment as well as the patient?' },
  ] },
};
