import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { ACUTE_KIDNEY_INJURY_WITH_FLUID_OVERLOAD } from './scenarios/acute-kidney-injury-with-fluid-overload';
import { AKI_FLUID_OVERLOAD_FIXTURES } from './aki-fluid-overload-fixtures';
import { AKI_FLUID_OVERLOAD_TUTOR_VERSION } from './tutor/aki-fluid-overload-guidance';
import { AKI_FLUID_OVERLOAD_DEMONSTRATION_VERSION } from './demo/aki-fluid-overload-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so the shared audit satisfies the observable-objectives cap;
 * meaningful-progression is supplied by hand as across this module, because the
 * timeline is two narratives with no state event.
 */
export function akiFluidOverloadCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'critical-care' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== AKI_FLUID_OVERLOAD_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || AKI_FLUID_OVERLOAD_FIXTURES.contentVersion !== '0.1.0'
    || AKI_FLUID_OVERLOAD_FIXTURES.seed !== 2748
    || AKI_FLUID_OVERLOAD_TUTOR_VERSION !== '0.1.0'
    || AKI_FLUID_OVERLOAD_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(ACUTE_KIDNEY_INJURY_WITH_FLUID_OVERLOAD)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['aki-fluid-overload-fixtures.ts binds seed 2748 and content 0.1.0 to expert, support-before-the-free-step error, recovery, and no-action paths. The sixty-seven-year-old intubated woman on ICU day 3 after septic shock at creatinine 3.4 mg/dL from a 1.0 mg/dL baseline, urine 0.15 mL/kg/h over 12 hours, cumulative balance +8.2 L, weight 82 kg from 73 kg, SpO2 91% on FiO2 0.50, HR 104/min, MAP 72 mmHg on low reported vasoactive support and temperature 37.4°C, the reported increasing bilateral interstitial and alveolar oedema, the adequate loop-diuretic challenge that produced 40 mL over 6 hours, and the authored 6-hour response of net −1.1 L with SpO2 95% on an unchanged FiO2 0.50, HR 96/min, MAP 74 mmHg, potassium 5.1 mmol/L and pH 7.31 are authored constants; no kidney, fluid-kinetic or kidney-support model is claimed, and no outcome follows from any choice. tests/integration/aki-fluid-overload-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals, and the fluid-plan step carries the lesson: nine kilograms of water arrived one reasonable infusion at a time, the cheapest intervention available is to stop adding to it, and the engine refuses to let the kidney-support conversation happen before that has been recorded. The context review is gated ahead of the fluid plan so obstruction, abdominal pressure, perfusion and the other causes people stop looking for once "septic AKI" is written down are still open. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions recognize a harmful kidney, fluid and organ trajectory and activate critical-care, nephrology, nursing, respiratory-therapy and pharmacy help while refusing to treat any single creatinine, urea, urine-output or fluid-percentage value as an automatic kidney-support trigger; review urine, balance, weight, respiratory support, perfusion, potassium, ECG, acid-base, urea, uraemic complications, obstruction, toxin, infection treatment, medications, contrast, haemodynamics, abdominal pressure and intrinsic causes without closing urgency, reversibility, recovery, goals or prescription; stop nonessential fluid and sodium in the plan and reconcile infusions, antimicrobials, medications and nutrition while preserving perfusion and necessary treatment, recording the poor reported diuretic response without blind repeated escalation; activate individualized kidney-support planning with urgent initiation preserved for life-threatening imbalance and haemodynamics, access, modality, dose, anticoagulation, clearance, net removal, goals, preferences and resources left as expert decisions; and reassess the authored response. The lesson counts nothing, restricts nothing, changes no nutrition, doses and delivers no fluid or diuretic, cannulates nobody, starts no circuit, diagnoses nothing, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment on an authored 6-hour response — net −1.1 L, SpO2 95% on an unchanged FiO2 0.50, HR 96/min, MAP 74 mmHg, potassium 5.1 mmol/L, pH 7.31 — in which oliguria persists. Later actions cannot restart an ended branch, and the ending is explicit about what the improvement is: the lung is carrying less water because water is being removed, not because the kidney started working. Ongoing removal, haemodynamic tolerance, solute control, modality, medication dosing, nutrition, kidney recovery, duration, prognosis and outcome all remain open.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one nine kilograms invites: the common-error path recognises the trajectory and goes straight to the kidney-support conversation, skipping both the cause review and the free step of stopping the intake that is still running, and meets one of five because the engine gates it. The recovery path reaches for the context before the trajectory has been recognised and is refused, reaches for kidney support before the intake has been stopped and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['aki-fluid-overload-fixtures.ts binds exact-content expert, support-before-the-free-step error, recovery, and no-action pathways to seed 2748 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${AKI_FLUID_OVERLOAD_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step, because this lesson has no unordered lane. The reflex it works against is arguing about dialysis before doing the free thing. The recognition beat calls the nine-kilogram weight change the honest number, because it is the same fluid the balance chart claims measured a way that does not depend on anyone writing down a flush, and names the direction — intake still exceeds output, so tomorrow is worse by default. The context beat lists the causes people stop looking for once "septic AKI" is written down, including the one that makes the fluid its own reason for the fluid: 8.2 litres of oedema raises abdominal pressure and a raised abdominal pressure causes oliguria. The fluid beat is the lesson — the litres arrived as carriers, diluents, flushes, antimicrobials in 250 mL and maintenance nobody cancelled, restriction is not under-resuscitation, and recording a 40 mL response to an adequate challenge is what stops the fourth larger dose given because the third did nothing. The support beat keeps one thing unambiguous, that life-threatening imbalance justifies urgent initiation, and says accelerated initiation is a position rather than a rule because the trials that asked whether starting earlier helps did not find that it does. Worked example ${AKI_FLUID_OVERLOAD_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the reassessment and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere names a diuretic dose, starts a circuit, picks a modality or net removal rate, or claims the kidney is recovering. tests/unit/aki-fluid-overload-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/critical-care-aki-fluid-overload.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
