import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { CARDIOGENIC_SHOCK } from './scenarios/cardiogenic-shock';
import { CARDIOGENIC_SHOCK_FIXTURES } from './cardiogenic-shock-fixtures';
import { CARDIOGENIC_SHOCK_TUTOR_VERSION } from './tutor/cardiogenic-shock-guidance';
import { CARDIOGENIC_SHOCK_DEMONSTRATION_VERSION } from './demo/cardiogenic-shock-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so the shared audit satisfies the observable-objectives cap.
 * As across this module the timeline is two narratives with no state event, so
 * meaningful-progression is supplied by hand; seven satisfied in all, and the
 * two runtime requirements outstanding.
 */
export function cardiogenicShockCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'critical-care' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== CARDIOGENIC_SHOCK_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || CARDIOGENIC_SHOCK_FIXTURES.contentVersion !== '0.1.0'
    || CARDIOGENIC_SHOCK_FIXTURES.seed !== 4390
    || CARDIOGENIC_SHOCK_TUTOR_VERSION !== '0.1.0'
    || CARDIOGENIC_SHOCK_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(CARDIOGENIC_SHOCK)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['cardiogenic-shock-fixtures.ts binds seed 4390 and content 0.1.0 to expert, bridge-before-the-heart error, recovery, and no-action paths. The acute anterior STEMI pattern deteriorating while the catheterization pathway is mobilised, the invasive 78/48 mmHg at a MAP of 58 with HR 112/min in sinus, cool mottled extremities, capillary refill 5 seconds, new confusion, 10 mL of urine in the last hour and a lactate rising from 3.1 to 4.8 mmol/L, the 91% on supplemental oxygen at RR 28/min with bilateral crackles, the fixed ECG reporting persistent anterior ST elevation, and the fixed echo reporting severe left-ventricular systolic dysfunction with anterior and apical akinesis, a preserved right ventricle, no effusion, no reported acute severe mitral regurgitation or ventricular-septal defect and bilateral B-lines are authored constants; no haemodynamic, vasopressor or reperfusion model is claimed, and no outcome follows from any choice. tests/integration/cardiogenic-shock-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals, and the position of the bridge inside the chain is the argument: a vasopressor recorded before the phenotype is a guess about a heart nobody has looked at, and a device escalated before the culprit vessel is opened is treating the consequence of an artery that is still shut. Recognition precedes the phenotype review, the phenotype precedes the bridge, the bridge precedes cause control, and cause control precedes the reassessment. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions recognize the worsening hypoperfusion and activate experienced shock and catheterization help off the trajectory rather than a diagnosis; review the acute-MI cause, the left-sided congested phenotype and the immediate mechanical, rhythm, right-heart and noncardiac alternatives; record perfusion-linked vasopressor bridge intent without primary fluid loading; prioritize prompt culprit-vessel revascularization ahead of unselected device escalation or routine multivessel treatment; and reassess pressure, perfusion, congestion, rhythm, gas exchange and organ trajectory. The lesson examines nobody, acquires no monitoring or test, diagnoses nothing, delivers no oxygen or drug, obtains no access, selects no dose, images nothing, catheterizes, revascularizes, supports, transfers and dispositions nobody, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded trajectory reassessment on an authored response that improves. Later actions cannot restart an ended branch, and the ending is explicit that improvement at this point means the bridge is doing what a bridge does rather than that the shock is treated: the artery is the shock and it is not open yet. The revascularization decisions, the device questions, the shock team\'s work and the organ trajectory all stay open.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one a low pressure invites: the common-error path recognises the shock and reaches straight for the bridge without looking at the heart — a vasopressor chosen for a phenotype nobody has established — and meets one of five, because the engine gates the bridge behind the phenotype review and everything after it becomes unavailable. The recovery path reviews the phenotype before the shock has been named and is refused, reaches for cause control before the bridge that holds him through it and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['cardiogenic-shock-fixtures.ts binds exact-content expert, bridge-before-the-heart error, recovery, and no-action pathways to seed 4390 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${CARDIOGENIC_SHOCK_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step, because this lesson has no unordered lane. The reflex it works against is the fluid, and the module now teaches both halves of that: a MAP of 58 with a rising lactate pulls hard towards a bolus, this patient's left ventricle is already failing into lungs full of B-lines, and the same instinct that is right in the septic-shock lesson is wrong here. The bridge beat says so directly and points at the other lesson, because the pair is the teaching. The recognition beat calls the MAP the least interesting number on the screen and gives the reason team activation is a step of its own: it takes time you do not have later, and it should happen off the trajectory rather than off a diagnosis. The phenotype beat treats the echo's negatives as the load-bearing part — a tamponade, a right-ventricular infarct, an acute severe mitral regurgitation or a ruptured septum each make this a different emergency, and two of them need a surgeon rather than a vasopressor. The cause beat explains why support layered onto an artery that is still shut is expensive, invasive and not the fix. The reassessment beat refuses to let improvement close anything, because the artery is the shock. Worked example ${CARDIOGENIC_SHOCK_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the reassessment, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts that no beat anywhere names a vasopressor dose, a pressure target, a device, or a fluid volume. tests/unit/cardiogenic-shock-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/critical-care-cardiogenic-shock.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
