import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { DELAYED_VASOPRESSOR_DELIVERY } from './scenarios/delayed-vasopressor-delivery';
import { DELAYED_VASOPRESSOR_DELIVERY_FIXTURES } from './delayed-vasopressor-delivery-fixtures';
import { DELAYED_VASOPRESSOR_DELIVERY_TUTOR_VERSION } from './tutor/delayed-vasopressor-delivery-guidance';
import { DELAYED_VASOPRESSOR_DELIVERY_DEMONSTRATION_VERSION } from './demo/delayed-vasopressor-delivery-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so the shared audit satisfies the observable-objectives cap;
 * meaningful-progression is supplied by hand as across this module, because the
 * timeline is two narratives with no state event.
 */
export function delayedVasopressorDeliveryCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'critical-care' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== DELAYED_VASOPRESSOR_DELIVERY_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || DELAYED_VASOPRESSOR_DELIVERY_FIXTURES.contentVersion !== '0.1.0'
    || DELAYED_VASOPRESSOR_DELIVERY_FIXTURES.seed !== 5218
    || DELAYED_VASOPRESSOR_DELIVERY_TUTOR_VERSION !== '0.1.0'
    || DELAYED_VASOPRESSOR_DELIVERY_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(DELAYED_VASOPRESSOR_DELIVERY)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['delayed-vasopressor-delivery-fixtures.ts binds seed 5218 and content 0.1.0 to expert, classify-before-the-trace error, recovery, and no-action paths. The fifty-eight-year-old woman in septic shock at MAP 54 mmHg, HR 124/min, refill 5 seconds, urine 8 mL/h, mottling above the knees, lactate 5.6 mmol/L, EtCO2 29 mmHg and SpO2 95% on FiO2 0.40, the pump displaying RUNNING at 1 mL/h for 6 minutes, and the declared setup of a drug-free 0.6 mL downstream segment beyond the mixing point, 2 mL/h carrier flow, a patent dedicated central lumen, no occlusion alarm and no detected drug arrival are authored constants; no infusion, pump or pharmacokinetic model is claimed, and no outcome follows from any choice. tests/integration/delayed-vasopressor-delivery-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals, and the first step carries the lesson: a pump reading RUNNING is a claim about a motor rather than about a patient, and the engine holds command, line transit, patient delivery and physiologic effect apart as four separate states. The trace is gated behind that reconciliation and the classification behind the trace, so the good-fitting answer cannot be reached before the 0.6 mL of drug-free downstream volume it rests on has been reviewed. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions reconcile the RUNNING command and elapsed time against persistent shock and the fixed record of no catheter-tip arrival; trace the labeled syringe, pump fit and event log, tubing compliance and resistance, valves and connectors, mixing point, 0.6 mL downstream segment, 2 mL/h carrier, stopcock state and level, dedicated catheter and occlusion status; classify the fixed pattern as dead-space transit and startup delay while keeping wrong drug, concentration, rate, route, access, occlusion, extravasation, incompatibility, pump fault, changing shock and measurement error open; activate bedside nursing, pharmacy, critical care and the local device-specific safe-start or changeover protocol with an explicit guard against flushing concentrated vasopressor into the patient; and reassess delivery evidence separately from perfusion. The lesson inspects, measures, calculates, primes, purges, flushes, boluses, programs, prescribes, compounds and delivers nothing, manipulates no equipment, diagnoses no shock, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment on an authored response — documented drug arrival, MAP 67 mmHg, HR 108/min, refill 3 seconds, EtCO2 32 mmHg, unchanged SpO2 95% on FiO2 0.40 and temperature 38.9°C — that claims no source control, dose adequacy, line durability, later perfusion or outcome. Later actions cannot restart an ended branch, and the ending separates the one thing this lesson was about, delivery now evidenced rather than assumed, from the improvement in perfusion that does not follow from it.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one a good-fitting answer invites: the common-error path reconciles the discordance and jumps straight to naming dead-space and startup delay, skipping the trace the classification rests on, and meets one of five because the engine gates it. The recovery path reaches for the trace before the discordance has been reconciled and is refused, reaches for the safety plan before the pattern it answers and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['delayed-vasopressor-delivery-fixtures.ts binds exact-content expert, classify-before-the-trace error, recovery, and no-action pathways to seed 5218 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${DELAYED_VASOPRESSOR_DELIVERY_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step, because this lesson has no unordered lane. The reflex it works against is trusting the display: the pump says RUNNING, so the drug must be going in, and six minutes of unchanged shock gets explained away as a very sick patient rather than investigated. The discordance beat holds the four states apart and says that unchanged numbers are not a failure to respond until arrival has been shown. The path beat sits with the 0.6 mL: at 1 mL/h against a 2 mL/h carrier, a drug-free downstream segment is a transit time on the order of the six minutes being watched, and syringe and plunger compliance mean a pump at a low rate can be turning without having pushed a full column. The classification beat names the pattern and immediately says what a good fit does not exclude, because a good fit is when a differential gets abandoned. The protocol beat carries the second reflex, the fix that hurts: knowing a dead-space segment holds concentrated vasopressor makes flushing it obvious, and that is an uncontrolled bolus into a woman with a MAP of 54 — and the correct manoeuvre is device-specific and cannot be recited, so the local protocol and the people are the answer. Worked example ${DELAYED_VASOPRESSOR_DELIVERY_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the reassessment and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere flushes or primes the line, programs the pump, names a dose or rate to set, or claims the shock is treated. tests/unit/delayed-vasopressor-delivery-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/critical-care-delayed-vasopressor-delivery.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
