import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { VENTILATOR_DYSSYNCHRONY } from './scenarios/ventilator-dyssynchrony';
import { DYSSYNCHRONY_FIXTURES } from './dyssynchrony-fixtures';
import { DYSSYNCHRONY_TUTOR_VERSION } from './tutor/dyssynchrony-guidance';
import { DYSSYNCHRONY_DEMONSTRATION_VERSION } from './demo/dyssynchrony-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so the shared audit satisfies the observable-objectives cap;
 * meaningful-progression is supplied by hand as across this module, because the
 * timeline is two narratives with no state event.
 */
export function dyssynchronyCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'critical-care' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== DYSSYNCHRONY_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || DYSSYNCHRONY_FIXTURES.contentVersion !== '0.1.0'
    || DYSSYNCHRONY_FIXTURES.seed !== 6142
    || DYSSYNCHRONY_TUTOR_VERSION !== '0.1.0'
    || DYSSYNCHRONY_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(VENTILATOR_DYSSYNCHRONY)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['dyssynchrony-fixtures.ts binds seed 6142 and content 0.1.0 to expert, correct-before-you-explain error, recovery, and no-action paths. The intubated patient awake enough to signal discomfort with visible inspiratory effort on volume control at 420 mL and 18/min with PEEP 8 cm H2O and FiO2 0.40, the fixed twenty-breath observation with pressure-time scooping, early cycling followed by continued effort and 8 double-triggered breaths, the stacked delivered volume reaching 760 mL, the peak of 30 cm H2O against a passive plateau of 22 cm H2O recorded beforehand, and the SpO2 of 93%, HR 104/min, MAP 77 mmHg, pH 7.31 and PaCO2 50 mmHg are authored constants; no respiratory-mechanics, analgesia or sedation model is claimed, and no outcome follows from any choice. tests/integration/dyssynchrony-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals, and the driver review sits between the graphics and the classification on purpose: a patient fighting a ventilator can be fighting something that has nothing to do with the ventilator, so pain, drive, the airway, secretions, the circuit and auto-PEEP are excluded as the reason before anybody decides the interaction itself is the problem. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions integrate patient effort with the pressure, flow, volume and delivered-breath observations; review pain, respiratory drive, airway, secretions, circuit, auto-PEEP, gas exchange and circulation before changing support; classify the bounded flow-starvation and premature-cycling pattern without treating every irregular breath as equivalent, linking the double triggering to excess delivered volume and ongoing effort; record analgesia-first and respiratory-therapy adjustment intent that matches flow and cycling while preserving lung-protective limits and avoiding reflex deep-sedation or paralysis claims; and reassess comfort, effort, graphics, delivered volume, pressures, gas exchange and circulation. The lesson examines nobody, measures no pain or sedation, handles no airway or equipment, acquires no waveform, diagnoses nothing, selects no mode or setting, prescribes or delivers no drug, paralyses nobody, samples no blood, performs no procedure, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment on an authored 10-minute response that improves. Later actions cannot restart an ended branch, and the ending claims no universal settings: what matched this man\'s flow demand is his rather than a number to carry to the next patient. The reassessment is deliberately plural because either half alone misleads — a patient who looks settled while his delivered volume is still stacking has not been helped, and tidy graphics in a distressed patient have not helped either.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one a fighting patient invites: the common-error path reads the graphics and goes straight to a correction, skipping the drivers that might explain why he is fighting and the classification that says which mismatch this is, and meets one of five because the engine gates the correction behind both. The recovery path reaches for the drivers before the patient and the graphics have been read together and is refused, reaches for the correction before the pattern has been classified and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['dyssynchrony-fixtures.ts binds exact-content expert, correct-before-you-explain error, recovery, and no-action pathways to seed 6142 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${DYSSYNCHRONY_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step, because this lesson has no unordered lane. The reflex it works against is sedation: a man visibly fighting a ventilator is the commonest reason a team reaches for a bolus or a paralytic, and everything on his screen says he is trying to breathe and being refused. Sedating him would remove the evidence rather than the cause, and the correction beat refuses both by name. The graphics beat reads the three findings as one sentence — scooping is a patient pulling harder than the set flow, early cycling ends the breath while he is still asking for it, and the double triggering is where 760 mL from a set 420 comes from. The drivers beat gives the reason it precedes the classification and singles out pain and an unmet drive, since he is awake enough to say he is uncomfortable and his pH of 7.31 with a PaCO2 of 50 mmHg is a chemical reason to want more breath; it also flags auto-PEEP, which the previous lesson established and which looks exactly like a patient who cannot get a breath. The classification beat treats the double triggering as a consequence rather than a third finding and says why being specific matters, because ineffective or reverse triggering would need a different correction. The correction beat puts analgesia first because pain is a driver rather than a nuisance. Worked example ${DYSSYNCHRONY_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the reassessment and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere sedates, paralyses, names a drug or a dose, or selects a flow or cycling setting. tests/unit/dyssynchrony-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/critical-care-dyssynchrony.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
