import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { ICU_HANDOFF_WITH_HIDDEN_DETERIORATION } from './scenarios/icu-handoff-with-hidden-deterioration';
import { ICU_HANDOFF_FIXTURES } from './icu-handoff-fixtures';
import { ICU_HANDOFF_TUTOR_VERSION } from './tutor/icu-handoff-guidance';
import { ICU_HANDOFF_DEMONSTRATION_VERSION } from './demo/icu-handoff-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other —
 * including the neonatology module's delivery-room handoff.
 */
export function icuHandoffCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'critical-care' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== ICU_HANDOFF_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || ICU_HANDOFF_FIXTURES.contentVersion !== '0.1.0'
    || ICU_HANDOFF_FIXTURES.seed !== 8419
    || ICU_HANDOFF_TUTOR_VERSION !== '0.1.0'
    || ICU_HANDOFF_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(ICU_HANDOFF_WITH_HIDDEN_DETERIORATION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['icu-handoff-fixtures.ts binds seed 8419 and content 0.1.0 to expert, escalate-before-the-cross-check error, recovery, and no-action paths. The fifty-seven-year-old intubated woman with septic shock from suspected cholangitis and pending source control, the outgoing "stable septic shock on low-dose support" headline, the fixed 90-minute record of HR 94 to 118/min, MAP 70 to 64 mmHg while reported norepinephrine rose 0.08 to 0.22 mcg/kg/min, capillary refill 2 to 5 seconds, lactate 3.1 to 5.8 mmol/L, urine 30 to 5 mL/h and EtCO2 35 to 30 mmHg on unchanged ventilation at SpO2 96% on FiO2 0.35 and temperature 39.1°C, and the authored 15-minute bridge response of HR 108/min, MAP 70 mmHg, EtCO2 33 mmHg, SpO2 96% on an unchanged FiO2 0.35 and temperature 38.9°C are authored constants; no shock, communication or handover model is claimed, and no outcome follows from any choice. tests/integration/icu-handoff-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals, and the cross-check step carries the lesson: "stable septic shock on low-dose support" is a sentence, ninety minutes of dated numbers say the opposite, and the engine refuses both escalation and acceptance until the claim has been checked against the patient. Readiness is gated ahead of content so the handover is not given to someone half-listening, and content ahead of the cross-check because you cannot verify what you did not hear. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions establish receiver identity, shared attention, monitoring continuity, question opportunity and uninterrupted bedside coverage before content transfer; receive the headline, summary, active support, dated data, task list, pending source control and contingencies as claims requiring bedside verification rather than ground truth; cross-check the dated trends against the patient, monitor, airway and circuit, access, infusion path, pumps, concentrations, rates, compatibility, medications, labs, urine, orders and documentation while keeping alternate causes open; escalate the corrected worsening-shock state to critical care, nursing, pharmacy, respiratory therapy and urgent source control with priorities, failure triggers, contingencies and named task ownership; and synthesize before acknowledging responsibility. The lesson assesses nobody, communicates with nobody, delivers no treatment, controls no source, diagnoses nothing, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded synthesis and acceptance on an authored 15-minute bridge response — HR 108/min, MAP 70 mmHg, EtCO2 33 mmHg, SpO2 96% on an unchanged FiO2 0.35, temperature 38.9°C. Later actions cannot restart an ended branch, and the ending is explicit that the bridge is not evidence about what is wrong with her: the lactate, the urine, the source control, the durability, the recovery and the outcome all remain open.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one a confident headline invites: the common-error path establishes readiness, receives the content, and escalates on the strength of what it was told, skipping the cross-check that is the only thing separating "stable" from ninety minutes of numbers saying otherwise, and meets two of five because the engine gates the rest. The recovery path reaches for the content before anyone is ready to receive it and is refused, reaches for acceptance before the corrected state has been escalated and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['icu-handoff-fixtures.ts binds exact-content expert, escalate-before-the-cross-check error, recovery, and no-action pathways to seed 8419 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${ICU_HANDOFF_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step, because this lesson has no unordered lane. The reflex it works against is inheriting the headline: a conclusion is the most efficient thing in a handover and the part nobody re-derives. The readiness beat says why the least interesting step is first — a handover given to someone half-listening in a corridor is where the sentence stops being examined — and is explicit that the things which actually degrade handovers, staffing and workload and interruptions, are not measured. The content beat frames every item as a claim and declines to make that distrust of the outgoing clinician, who has been awake for twelve hours watching a number move slowly, which is exactly when a trend is invisible from the inside. The cross-check beat reads the second trend carefully: a pressure that fell while the support nearly tripled is worse than a pressure that fell, because the number was held up, and a falling EtCO2 on unchanged ventilation is cardiac output leaving rather than a lung problem. It also checks the infusion path, because a vasopressor that is not arriving looks exactly like one that is not working. The escalation beat puts names on tasks, since unowned tasks at shift change are the ones that do not happen. Worked example ${ICU_HANDOFF_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the acceptance and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere titrates the vasopressor, orders an intervention, blames the outgoing clinician, or claims the shock is under control. tests/unit/icu-handoff-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/critical-care-icu-handoff.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
