import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { INTRACRANIAL_HYPERTENSION } from './scenarios/intracranial-hypertension';
import { INTRACRANIAL_HYPERTENSION_FIXTURES } from './intracranial-hypertension-fixtures';
import { INTRACRANIAL_HYPERTENSION_TUTOR_VERSION } from './tutor/intracranial-hypertension-guidance';
import { INTRACRANIAL_HYPERTENSION_DEMONSTRATION_VERSION } from './demo/intracranial-hypertension-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so the shared audit satisfies the observable-objectives cap;
 * meaningful-progression is supplied by hand as across this module, because the
 * timeline is two narratives with no state event.
 */
export function intracranialHypertensionCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'critical-care' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== INTRACRANIAL_HYPERTENSION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || INTRACRANIAL_HYPERTENSION_FIXTURES.contentVersion !== '0.1.0'
    || INTRACRANIAL_HYPERTENSION_FIXTURES.seed !== 6407
    || INTRACRANIAL_HYPERTENSION_TUTOR_VERSION !== '0.1.0'
    || INTRACRANIAL_HYPERTENSION_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(INTRACRANIAL_HYPERTENSION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['intracranial-hypertension-fixtures.ts binds seed 6407 and content 0.1.0 to expert, treat-before-you-ask-why error, recovery, and no-action paths. The thirty-four-year-old intubated man six hours from severe blunt traumatic brain injury and lesion evacuation, the parenchymal monitor reporting ICP 28 mmHg for 8 minutes on a consistent waveform against MAP 82 mmHg for a calculated CPP of 54 mmHg, the treatment threshold of 22 mmHg, the unchanged right 4 mm sluggish and left 3 mm reactive pupils, diffuse oedema with no reported new evacuable lesion, 10° head elevation with neck rotation, intermittent dyssynchrony, EtCO2 40 mmHg, sodium 140 mmol/L, temperature 37.7°C, and the fixed 15-minute response of ICP 19 mmHg, MAP 84 mmHg and CPP 65 mmHg are authored constants; no intracranial-pressure, cerebral-autoregulation or osmotherapy model is claimed, and no outcome follows from any choice. tests/integration/intracranial-hypertension-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals, and the protection step carries the lesson: an ICP of 28 has a famous treatment attached, and the engine puts the free interventions first. The context review is gated ahead of protection so the 10° head elevation with a rotated neck — a partly obstructed venous outflow that no osmotherapy opens — is found before anything is reached for, and the hyperosmolar rescue is gated behind protection so it arrives as one step in an order rather than the first move. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions recognize a sustained ICP and inadequate CPP pattern as a pattern rather than a diagnosis or prognosis and activate neurocritical, neurosurgical, nursing, respiratory-therapy and pharmacy help; review monitor fidelity, examination, imaging, systemic physiology and reversible drivers without closing any of them; activate neutral positioning and individualized elevation for venous drainage with oxygenation, ventilation, perfusion, temperature, analgesia, sedation, synchrony, glucose, sodium and seizure-surveillance protection, individualizing CPP within 60-70 mmHg without forcing it above 70 and declining prolonged prophylactic aggressive hyperventilation; activate an individualized hyperosmolar rescue intent behind agent-suitability, sodium, chloride, osmolality, renal, volume, access, fluid-balance and response guardrails; and reassess ICP and CPP against durability, examination, imaging and escalation that stay open. The lesson positions, measures, ventilates, doses and delivers nothing, selects no universal agent, formulation, concentration, dose or route, diagnoses nothing, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment on an authored 15-minute response — ICP 19 mmHg, MAP 84 mmHg, CPP 65 mmHg, HR 84/min, SpO2 97%, EtCO2 38 mmHg, temperature 37.5°C, unchanged pupils and no new herniation sign — that claims no durable control, no recovery and no outcome. Later actions cannot restart an ended branch, and the ending is explicit that an immediate pressure response says nothing about monitor fidelity, recurrence, the examination, repeat imaging, or whether a drain or an operation follows.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one a treatable number invites: the common-error path recognises the crisis and reaches straight for first-tier protection, skipping the context review that finds the rotated neck and the dyssynchrony the protection step exists to act on, and meets one of five because the engine gates it. The recovery path reaches for the context before the pattern has been recognised and is refused, reaches for the osmotherapy before the free interventions that precede it and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['intracranial-hypertension-fixtures.ts binds exact-content expert, treat-before-you-ask-why error, recovery, and no-action pathways to seed 6407 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${INTRACRANIAL_HYPERTENSION_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step, because this lesson has no unordered lane. The reflex it works against is reaching for the osmotherapy, and the second is treating the ICP alone when the number the brain experiences is the perfusion pressure underneath it. The recognition beat reads the pair rather than the number and makes "sustained" do work: eight minutes of a consistent waveform is a pattern, not a transient, and not a diagnosis either. The context beat starts with monitor fidelity, because a wrong number is treated exactly as enthusiastically as a right one, and ends on the two findings that can be changed without a drug. The protection beat is the lesson: a neck rotated at 10° of elevation is a partly obstructed jugular, CPP is individualized inside 60-70 rather than forced above 70 because pushing pressure buys pulmonary and cardiac harm without buying brain, and prolonged prophylactic aggressive hyperventilation is declined because lowering the carbon dioxide constricts the vessels that were delivering the blood — a good number out of a worse brain. The rescue beat states the lean without turning it into a rule: the cited guideline conditionally favours hypertonic sodium for initial TBI-related ICP management and mannitol remains an effective alternative when sodium is unsuitable, and his sodium of 140 is an input rather than a green light. Worked example ${INTRACRANIAL_HYPERTENSION_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the reassessment and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere names an agent dose or concentration, sets a ventilator target, moves the patient, or claims durable control. tests/unit/intracranial-hypertension-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/critical-care-intracranial-hypertension.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
