import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { RIGHT_VENTRICULAR_FAILURE } from './scenarios/right-ventricular-failure';
import { RV_FAILURE_FIXTURES } from './rv-failure-fixtures';
import { RV_FAILURE_TUTOR_VERSION } from './tutor/rv-failure-guidance';
import { RV_FAILURE_DEMONSTRATION_VERSION } from './demo/rv-failure-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so the shared audit satisfies the observable-objectives cap;
 * meaningful-progression is supplied by hand as across this module, because the
 * timeline is two narratives with no state event.
 */
export function rvFailureCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'critical-care' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== RV_FAILURE_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || RV_FAILURE_FIXTURES.contentVersion !== '0.1.0'
    || RV_FAILURE_FIXTURES.seed !== 7208
    || RV_FAILURE_TUTOR_VERSION !== '0.1.0'
    || RV_FAILURE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(RIGHT_VENTRICULAR_FAILURE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['rv-failure-fixtures.ts binds seed 7208 and content 0.1.0 to expert, support-before-the-filling-pressures error, recovery, and no-action paths. The pulmonary arterial hypertension with worsening oedema and abdominal distension after several days of poor intake and interrupted pulmonary-vascular therapy, the MAP of 58 mmHg with HR 116/min, capillary refill 5 seconds, cool extremities, slowing mentation, urine 12 mL/h and a lactate risen from 2.8 to 4.3 mmol/L, the elevated JVP with no reported B-lines at 91% on supplemental oxygen, the echo reporting a severely dilated right ventricle with reduced systolic function, systolic septal flattening, a small underfilled left ventricle and no effusion or acute severe left-sided valve lesion, and the panel reporting a central venous pressure of 18 mmHg, a wedge of 10 mmHg and a cardiac index of 1.8 L/min/m2 are authored constants; no haemodynamic, pulmonary-vascular or diuretic model is claimed, and no outcome follows from any choice. tests/integration/rv-failure-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals, and the chain puts the phenotype ahead of the support for a specific reason: this is the lesson where both of the obvious moves are wrong, and the two filling pressures are what establish that. A learner who records support before reading a central venous pressure of 18 against a wedge of 10 is choosing between a diuretic and a bolus without the finding that rules out both reflexes. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions recognize right-ventricular failure from congestion and underperfusion together and activate specialist shock help; integrate the fixed echo and haemodynamic pattern while keeping acute triggers and dangerous alternatives open and without treating one value as diagnostic; record an expert-selected support intent that protects systemic perfusion, oxygenation, acid-base balance, rhythm and the pressure-loaded right ventricle while avoiding indiscriminate fluid, automatic decongestion and universal targets; keep the reversible-precipitant and specialist pulmonary-vascular therapy pathways active; and reassess perfusion, congestion, rhythm, oxygenation, the right-ventricular pattern, filling pressure, output and organ trajectory. The lesson examines nobody, acquires or interprets no monitoring, ECG, laboratory, echo, catheter or imaging data, calculates and diagnoses nothing, changes no oxygen or ventilation, delivers no fluid, diuresis or drug, obtains no access, selects no dose, performs no procedure, provides no mechanical support, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded trajectory reassessment on an authored response that improves. Later actions cannot restart an ended branch, and the ending claims neither resolution nor a universal endpoint: she is still congested, still underperfused, and still off the therapy that was interrupted. The reassessment is deliberately plural because a patient whose problem is a pressure-loaded ventricle can look better on one axis while another is quietly worse.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one her appearance invites: the common-error path recognises the trajectory and records support without reading the two filling pressures that decide which reflex would have been wrong, and meets one of five because the engine gates support behind the phenotype review. The recovery path reads the phenotype before the trajectory has been named and is refused, reaches for the triggers before the support they are reviewed alongside and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['rv-failure-fixtures.ts binds exact-content expert, support-before-the-filling-pressures error, recovery, and no-action pathways to seed 7208 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${RV_FAILURE_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step, because this lesson has no unordered lane. The reflex it works against is whichever one the learner reaches for first, because this patient invites two opposite ones and punishes both: she is grossly congested, which asks for a diuretic, and hypotensive and underperfused, which asks for fluid. The recognition beat makes congestion without pulmonary oedema in a patient who is not perfusing the finding that locates the problem on the right, and names the interrupted therapy as the part of the history most likely to explain why now. The phenotype beat reads the two filling pressures against each other — 18 on the right and 10 on the left is where the congestion is and where it is not — and says the small left ventricle is small because the right one is not delivering to it rather than because she is dry, with the septal flattening as the same fact seen a second way. The support beat states plainly that neither reflex is forbidden as a matter of principle and that what is excluded is doing either automatically. The triggers beat notes that hypoxia and acidosis are both consequences of her state and causes of it worsening, and that restarting interrupted pulmonary-vascular therapy is a specialist decision rather than a resumption. Worked example ${RV_FAILURE_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the reassessment and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere names a diuretic, a fluid volume, a pressure target, or a pulmonary-vascular agent. tests/unit/rv-failure-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/critical-care-rv-failure.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
