import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { UNPLANNED_EXTUBATION } from './scenarios/unplanned-extubation';
import { UNPLANNED_EXTUBATION_FIXTURES } from './unplanned-extubation-fixtures';
import { UNPLANNED_EXTUBATION_TUTOR_VERSION } from './tutor/unplanned-extubation-guidance';
import { UNPLANNED_EXTUBATION_DEMONSTRATION_VERSION } from './demo/unplanned-extubation-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so the shared audit satisfies the observable-objectives cap;
 * meaningful-progression is supplied by hand as across this module, because the
 * timeline is two narratives with no state event.
 */
export function unplannedExtubationCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'critical-care' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== UNPLANNED_EXTUBATION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || UNPLANNED_EXTUBATION_FIXTURES.contentVersion !== '0.1.0'
    || UNPLANNED_EXTUBATION_FIXTURES.seed !== 9375
    || UNPLANNED_EXTUBATION_TUTOR_VERSION !== '0.1.0'
    || UNPLANNED_EXTUBATION_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(UNPLANNED_EXTUBATION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['unplanned-extubation-fixtures.ts binds seed 9375 and content 0.1.0 to expert, right-answer-without-the-panel error, recovery, and no-action paths. The disconnect alarm after repositioning with the tracheal tube visibly outside the mouth, the respiratory rate of 36/min with accessory-muscle use, hoarse weak voice, weak cough and pooled secretions, the SpO2 of 86% despite face-mask oxygen, the authored arterial panel at pH 7.27 and PaCO2 58 mmHg, the new drowsiness, the HR of 116/min and MAP of 78 mmHg, and the absence of any continuous exhaled-carbon-dioxide signal without an airway are authored constants; no airway, oxygenation or reintubation model is claimed, and no outcome follows from any choice. tests/integration/unplanned-extubation-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals, and the tolerance assessment sits between the support and the airway plan for a specific reason: a large share of unplanned extubations never need reintubation, this one does, and the engine makes the learner establish which kind it is before the plan so that a correct decision is a conclusion rather than a reflex that happened to land. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions support oxygenation and call experienced ICU and airway help after the unplanned extubation; assess airway patency, work of breathing, oxygenation, ventilation, mental status, secretions and circulation rather than assuming every unplanned extubation fails; recognize the convergent post-extubation respiratory failure and choose prompt reintubation; record experienced-team preoxygenation and reintubation intent without using noninvasive support to delay a failing airway; and confirm the reported new airway, reassess the patient and hand off a prevention review. The lesson examines nobody, acquires no monitoring, delivers no oxygen, ventilates nobody by mask, gives no drug, handles no airway equipment, intubates nobody, images nothing, diagnoses nothing, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment carrying reported placement evidence, the whole-patient response, and a securement, sedation, mobility, staffing and communication review handed off as intent. Later actions cannot restart an ended branch. Placement evidence comes first and is reported rather than assumed, which is the point in a patient who has just demonstrated what happens when everyone believes an airway is secure, and a correctly placed tube in a patient who is not improving is still a problem.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual here is unusual and deliberate: the common-error path reaches the *correct* decision — prompt reintubation — without ever reading the panel that establishes it, and meets one of five because the engine gates the airway plan behind the tolerance assessment and the classification. That is the same reflex that reintubates the patients who would have been fine, so the lesson refuses to reward it. The recovery path reaches for the tolerance panel before anybody has called for help and is refused, reaches for the airway plan before the trajectory has been classified and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['unplanned-extubation-fixtures.ts binds exact-content expert, right-answer-without-the-panel error, recovery, and no-action pathways to seed 9375 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${UNPLANNED_EXTUBATION_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step, because this lesson has no unordered lane. The reflex it works against is not the wrong answer but arriving at the right one without looking, and the assessment beat defends that step explicitly: a team that reintubates on the phrase rather than on the patient will also reintubate the ones who would have been fine. The support beat treats announcing the event as a step rather than a courtesy, since the people who need to know cannot infer it from an alarm, and notes what was lost with the tube — there is no continuous exhaled carbon dioxide without one. The classification beat counts four independent axes converging, with the trajectory as the one that decides it. The plan beat names the more dangerous opposite mistake: noninvasive support in a failing airway makes the numbers look better for a while in a patient who cannot protect his airway and is getting drowsier, and the time it buys is taken from the intubation that will happen anyway, under worse conditions — while being clear that noninvasive support has a real place in the patients this panel does not describe. The reassessment beat puts placement evidence first because this is the patient who has just demonstrated what happens when an airway is assumed secure. Worked example ${UNPLANNED_EXTUBATION_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the reassessment and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere intubates, names a drug or a blade, or claims noninvasive support has no place. tests/unit/unplanned-extubation-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/critical-care-unplanned-extubation.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
