import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { STEMI_RECOGNITION_AND_FIRST_ACTIONS } from './scenarios/stemi-recognition-and-first-actions';
import { CLINIC_STEMI_FIXTURES } from './clinic-stemi-fixtures';
import { CLINIC_STEMI_TUTOR_VERSION } from './tutor/clinic-stemi-guidance';
import { CLINIC_STEMI_DEMONSTRATION_VERSION } from './demo/clinic-stemi-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so this lesson satisfies the shared observable-objectives
 * cap and leaves only the two runtime requirements outstanding.
 */
export function clinicStemiCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'cardiology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== CLINIC_STEMI_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.1' || CLINIC_STEMI_FIXTURES.contentVersion !== '0.1.1'
    || CLINIC_STEMI_FIXTURES.seed !== 3391
    || CLINIC_STEMI_TUTOR_VERSION !== '0.1.0' || CLINIC_STEMI_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(STEMI_RECOGNITION_AND_FIRST_ACTIONS)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['clinic-stemi-fixtures.ts binds seed 3391 and content 0.1.1 to expert, screened-but-uncalled error, recovery, and no-action paths. The non-PCI clinic setting, the 22 minutes of ongoing symptoms, the fixed 12-lead report of ST elevation in II, III and aVF with reciprocal depression in I and aVL, the physiology at 128/76 with a heart rate of 62 and 96% on room air, the authored absences, and the two receiving-pathway questions left open — right-ventricular involvement and evolving bradyarrhythmia or atrioventricular block — are authored constants; no infarct, reperfusion or outcome model is claimed, and no outcome follows from any choice. tests/integration/clinic-stemi-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through five recorded steps on the shared simulation clock. The transfer activation and the danger screen are unordered against each other, and the clinic bridge refuses until both are recorded; one time gate sits before the reassessment and handoff. The declared objective order lists the danger screen before the activation while the tray offers the activation first, which is the lesson\'s argument rather than an inconsistency: the call goes out while the screening happens rather than after it.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions reconcile the ongoing symptom against the fixed diagnostic ECG; activate EMS and the regional STEMI system with the ECG transmitted and the system-selected receiving team pre-alerted, rejecting private transport and biomarker or paperwork delay; screen current danger, alternatives, bleeding, allergy and oxygenation in parallel rather than as a precondition; record a setting-bounded bridge of aspirin suitability, monitoring, defibrillation readiness, access and transport intent; and reassess before handing off. The lesson examines nobody, acquires or interprets no ECG or test, diagnoses no real patient, prescribes or delivers no aspirin or other drug, selects no P2Y12 inhibition, anticoagulation, fibrinolysis, PCI, nitrate or opioid therapy, performs no procedure, determines no disposition, and predicts no complication or outcome. Destination and reperfusion selection stay with the regional pathway, and routine oxygen is explicitly not selected at the authored saturation.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment and handoff with the patient still in the clinic awaiting transport. Later actions cannot restart an ended branch, and the ending certifies pciCapableSetting false, biomarkerDelayUsed false, downstreamTherapySelected false and no delivered treatment, and preserves right-ventricular involvement and evolving block as open questions for the receiving team rather than conclusions.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the delay the lesson exists to refuse: the common-error path screens the dangers thoroughly and correctly with nobody called, then reaches for the bridge before the route is open, meeting two of five. The recovery path reaches for the bridge before there is a pattern, takes the unordered pair screen-first, and clears the handoff time gate on the second attempt, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['clinic-stemi-fixtures.ts binds exact-content expert, screened-but-uncalled error, recovery, and no-action pathways to seed 3391 for deterministic replay through the shared engine, including the order refusals and the handoff time gate.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${CLINIC_STEMI_TUTOR_VERSION} read the learner's own recorded steps, and one of the five exists only for the state where the screen is done and nobody has been called. What the tutor holds is a setting: this is a clinic without a catheter laboratory, and almost everything a learner might reach for belongs to somebody down the road, so the two things that are genuinely theirs are the call and the honesty of the handover. The opening beat says the tissue clock started before she arrived and everything after either shortens the delay or lengthens it. The parallel beat argues the sequencing directly — the screening does not have to finish before the call goes out — and refuses private transport and biomarker delay by name, with the observation that a troponin an hour from now will say what is already known. The danger beat treats right-ventricular involvement and evolving block as items for the pre-alert rather than conclusions, and explains why an inferior pattern makes nitrates somebody else's decision. The bridge beat names routine oxygen at 96% as a habit rather than a treatment, and says why downstream therapy is not selected here. The handoff beat asks for the things the receiving team cannot reconstruct: the exact onset time, when the transmitted ECG was taken, and what has changed since. Worked example ${CLINIC_STEMI_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, taking the unordered pair activation-first as the order the lesson argues for rather than the only one the engine allows, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts that no beat anywhere gives aspirin, selects a downstream therapy, orders oxygen, or names a destination. tests/unit/clinic-stemi-demonstration.test.ts verifies observed response and every beat against the real engine, and tests/ui/cardiology-clinic-stemi.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
