import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { NSTEMI_RISK_REASSESSMENT } from './scenarios/nstemi-risk-reassessment';
import { NSTEMI_RISK_FIXTURES } from './nstemi-risk-fixtures';
import { NSTEMI_RISK_TUTOR_VERSION } from './tutor/nstemi-risk-guidance';
import { NSTEMI_RISK_DEMONSTRATION_VERSION } from './demo/nstemi-risk-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Five objectives, so this lesson satisfies the shared observable-objectives
 * cap and leaves only the two runtime requirements outstanding.
 */
export function nstemiRiskCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'cardiology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== NSTEMI_RISK_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || NSTEMI_RISK_FIXTURES.contentVersion !== '0.1.0'
    || NSTEMI_RISK_FIXTURES.seed !== 4218
    || NSTEMI_RISK_TUTOR_VERSION !== '0.1.0' || NSTEMI_RISK_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(NSTEMI_RISK_REASSESSMENT)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['nstemi-risk-fixtures.ts binds seed 4218 and content 0.1.0 to expert, inherited-stability error, recovery, and no-action paths. The 25 minutes of pressure five hours earlier with the patient pain-free now, the high-sensitivity troponin rising from 18 to 146 ng/L above the assay-specific 99th percentile, the initial ECG report of horizontal ST depression in V4-V6 and the repeat showing new lateral T-wave inversion, the physiology at 132/78, and the absent shock, recurrent pain, heart failure, arrhythmia, arrest, mechanical complication and recurrent dynamic ST change are authored constants; no ischemic, assay or outcome model is claimed, and no outcome follows from any choice. tests/integration/nstemi-risk-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through five recorded steps on the shared simulation clock in a strict line with no time gate, as in the stable-chest-pain lesson: the trajectory before the verification, the verification before the very-high-risk re-screen, the re-screen before the strategy, and the strategy before the monitoring and handoff. Each step refuses until its predecessor is recorded, and the third refusal is the one the lesson is built on, since it is what stops a strategy being recorded on inherited stability.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five declared decisions reconcile the serial symptom, ECG-report and assay-bounded troponin trajectory as one moving picture rather than three findings; verify the authored NSTEMI conclusion while keeping myocardial-injury alternatives in the assessment; re-screen the very-high-risk features now rather than inheriting an earlier observation; record an inpatient invasive strategy whose exact timing follows the applicable region and pathway; and record monitoring, deterioration triggers, ownership and the next reassessment. The lesson examines nobody, acquires or interprets no test, calculates no score, diagnoses nothing, prescribes or delivers no treatment, chooses no procedure, determines no universal timing or disposition, and predicts no prognosis or outcome. One authoring detail is worth recording for the next reader: the action ids and the declared objective ids are not the same list — the fourth objective is classify-nstemi-invasive-strategy while the accepted action is record-nstemi-invasive-strategy — so the identity guard compares against the objective ids explicitly rather than reusing the action list as every other lesson does.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at recorded monitoring and handoff with an inpatient strategy and no timing, no procedure and no disposition claimed. Later actions cannot restart an ended branch, and the ending certifies ischemicRisk as the authored high band, currentVeryHighRisk false, exactScoreCalculated false and procedurePerformed false, and preserves the myocardial-injury alternatives as open rather than excluded.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all five objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the inheritance the lesson exists to refuse: the common-error path reads the trajectory and verifies the conclusion correctly, then records a strategy without re-screening the very-high-risk features that would have changed it, meeting two of five. The recovery path additionally verifies before reconciling and takes the same inherited-stability reflex, and still completes in order from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['nstemi-risk-fixtures.ts binds exact-content expert, inherited-stability error, recovery, and no-action pathways to seed 4218 for deterministic replay through the shared engine, including both order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${NSTEMI_RISK_TUTOR_VERSION} read the learner's own recorded steps. The failure the tutor is built around is inheritance — a patient screened once, found stable, and treated as stable for the rest of the admission — so the opening beat ends on the observation that 132/78 is where she is rather than where she has been, and the re-screen beat says the word carrying the weight is "now", because a patient with a rising troponin and an evolving ECG can acquire a very-high-risk feature between two conversations. The trajectory beat explains why the three findings only mean something together: a rise on serial sampling is what separates infarction from a chronically elevated value, an assay-specific threshold is why a number without its assay means nothing, and an ECG that changed between two recordings says more than either alone. The verification beat states the conclusion plainly and then keeps myocarditis, pulmonary embolism, tachyarrhythmia, sepsis, renal impairment and takotsubo in the room, because a rising troponin is myocardial injury and infarction is one cause of it. The strategy beat treats bleeding risk as load-bearing rather than a footnote, since the same catheter that treats the ischemic risk raises the bleeding one, and leaves timing to the regional pathway. Worked example ${NSTEMI_RISK_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts that no beat anywhere states a score, names an hour for angiography, prescribes a drug, or excludes an alternative. tests/unit/nstemi-risk-demonstration.test.ts verifies observed response and every beat against the real engine, and tests/ui/cardiology-nstemi-risk.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
