import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PACEMAKER_CAPTURE_FAILURE } from './scenarios/pacemaker-capture-failure';
import { PACEMAKER_CAPTURE_FAILURE_FIXTURES } from './pacemaker-capture-failure-fixtures';
import { PACEMAKER_CAPTURE_FAILURE_TUTOR_VERSION } from './tutor/pacemaker-capture-failure-guidance';
import { PACEMAKER_CAPTURE_FAILURE_DEMONSTRATION_VERSION } from './demo/pacemaker-capture-failure-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives exceed the shared observable-objectives cap of five, and the
 * timeline is three narratives with no state event so the shared
 * meaningful-progression rule does not fire either. This sidecar supplies seven
 * requirements including that one, and leaves three outstanding: the objectives
 * cap and the two runtime items.
 */
export function pacemakerCaptureFailureCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'cardiology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PACEMAKER_CAPTURE_FAILURE_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || PACEMAKER_CAPTURE_FAILURE_FIXTURES.contentVersion !== '0.1.0'
    || PACEMAKER_CAPTURE_FAILURE_FIXTURES.seed !== 1739
    || PACEMAKER_CAPTURE_FAILURE_TUTOR_VERSION !== '0.1.0'
    || PACEMAKER_CAPTURE_FAILURE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PACEMAKER_CAPTURE_FAILURE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['pacemaker-capture-failure-fixtures.ts binds seed 1739 and content 0.1.0 to expert, troubleshoot-before-rescue error, recovery, and no-action paths. The dual-chamber pacemaker implanted three years ago for complete AV block, the 99.8% ventricular pacing and absence of a reliable intrinsic rhythm above 30/min, the fixed ten-second report of ten pacing artifacts of which six are not followed by a paced QRS, the mechanical pulse of 32/min at 84/52 mmHg with 97% on room air, the interrogation report of a battery not at elective replacement with 6.1 years estimated, a programmed output of 2.5 V at 0.4 ms against a threshold that rose from 0.75 V to 3.5 V, an RV impedance that rose from 520 to 1,860 ohms with stable atrial values and intermittent nonphysiologic electrogram noise, the potassium of 4.2 mmol/L, magnesium of 2.0 mg/dL and pH of 7.39 with an unremarkable radiograph and quiet pocket, and the authored restoration of capture at 70/min and 114/68 mmHg are authored constants; no pacing, capture, threshold or impedance model is claimed, and no outcome follows from any choice. tests/integration/pacemaker-capture-failure-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is three narratives with no non-narrative state event. The progression lives in the engine\'s refusals, and the shape carries a deliberate argument. After the pattern is recognised, the rescue, the device-system review and the cause review are open at once and in any order, and the later panel refuses until all three have landed. Putting the rescue inside the unordered group rather than ahead of it is the design decision: the lesson refuses to make troubleshooting a prerequisite for keeping a dependent patient perfused, and equally refuses to let a rescue close the review. Two time gates then separate the experienced team\'s reported response from the closing handoff.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile symptoms, pulse, perfusion, pacing artifacts, QRS complexes and mechanical signals before naming capture failure; activate acute bradycardia rescue, backup pacing readiness and device expertise without waiting for complete troubleshooting; review the authored dependency, battery, output, threshold, sensing, impedance-trend and stored-electrogram report without interrogating or programming anything; review lead, generator, myocardial, metabolic, ischemic, medication, procedure and measurement contributors without assigning one mechanism; review the experienced team\'s reported restoration of electrical and mechanical capture without claiming learner delivery or durable repair; and hand off capture surveillance, unresolved system integrity, rescue triggers and named electrophysiology ownership. The lesson examines nobody, acquires or interprets no ECG, telemetry, interrogation, laboratory or imaging report, diagnoses no mechanism, paces nothing, assesses no capture, interrogates or programs no device, selects no output, manipulates no lead, delivers no treatment, determines no disposition or prognosis, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded handoff on an authored report of restored capture at 70/min with resolved presyncope, achieved by a manufacturer- and lead-specific temporary programming change made by the treating team and never exposed as a recipe. Later actions cannot restart an ended branch, and the ending certifies initialPulsePresent and electricalCaptureFailureAuthored both true alongside eight restraint flags all false, including pacingDeliveredByLearner, deviceInterrogatedByLearner, deviceProgrammedByLearner, outputSelectedByLearner and leadManipulatedByLearner. Captured again is explicitly not repaired: the threshold climbed for a reason and the impedance jumped for a reason, and a programming change that outruns the problem has not fixed it.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual is the one a device problem invites: the common-error path recognises the pattern and then works through both troubleshooting lanes correctly while the rescue is never activated, meeting three of six — every review it performed was right, and a dependent man at 32/min and 84/52 mmHg waited for an explanation. The engine refuses the later panel because the rescue lane is one of the three it requires. The recovery path reviews before recognising and is refused, takes the unordered triple in a different order with the rescue last — which the engine accepts without comment — walks into both elapsed-time gates before clearing them, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['pacemaker-capture-failure-fixtures.ts binds exact-content expert, troubleshoot-before-rescue error, recovery, and no-action pathways to seed 1739 for deterministic replay through the shared engine, including the opening order refusal, the all-three-lanes refusal on the later panel, and both elapsed-time refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Seven observed-state prompts at version ${PACEMAKER_CAPTURE_FAILURE_TUTOR_VERSION} read the learner's own recorded steps — seven rather than six because the unordered triple needs a beat for the state where none of the three has been taken. The reflex the tutor works against is the monitor rate: the screen shows a paced rhythm at the programmed rate while the patient has a pulse of 32, because six of ten artifacts are not followed by a QRS, and the recognition beat states the distinction as plainly as it can — a spike is an electrical event and a heartbeat is a mechanical one, and the display is counting the wrong thing. The second reflex is the interesting one, and the unordered group exists to defeat it: this is a device problem and device problems invite troubleshooting, so the rescue beat gives the reason it cannot queue, and the reason is arithmetic rather than judgment — at 32/min with no intrinsic escape above 30/min the margin is measured in a handful of beats. The device beat reads the interrogation as trends rather than a verdict and says which single finding explains the noncapture: the output did not change and the threshold climbed past it. The causes beat is careful that a narrowed differential is not a closed one, since a radiograph showing no obvious fracture does not exclude one. The panel beat insists that the programming change belongs to that team, that device and that lead, and that temporary is the word doing the work. Worked example ${PACEMAKER_CAPTURE_FAILURE_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the handoff, taking the rescue first — a choice the lesson argues for rather than merely permits — and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts that no beat anywhere programs a device, names an output, claims a fracture, or turns an impedance into a threshold. tests/unit/pacemaker-capture-failure-worked-example.test.ts verifies the unordered triple and every beat against the real engine, and tests/ui/cardiology-pacemaker-capture-failure.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
