import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { TORSADES_DE_POINTES } from './scenarios/torsades-de-pointes';
import { TORSADES_FIXTURES } from './torsades-fixtures';
import { TORSADES_TUTOR_VERSION } from './tutor/torsades-guidance';
import { TORSADES_DEMONSTRATION_VERSION } from './demo/torsades-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives exceed the shared observable-objectives cap of five, so this
 * lesson leaves three requirements outstanding rather than two.
 */
export function torsadesCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'cardiology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== TORSADES_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || TORSADES_FIXTURES.contentVersion !== '0.1.0'
    || TORSADES_FIXTURES.seed !== 7712
    || TORSADES_TUTOR_VERSION !== '0.1.0'
    || TORSADES_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(TORSADES_DE_POINTES)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['torsades-fixtures.ts binds seed 7712 and content 0.1.0 to expert, magnesium-while-she-is-still-in-it error, recovery, and no-action paths. The rhythm-change event, the sustained polymorphic VT near 220/min with a weak palpable pulse, the physiology at 74/42 with acute confusion, cool pale skin and 96% on room air, the fixed pre-event report of sinus bradycardia at 52/min with a QTc of 560 ms, the pre-event potassium of 3.0 mmol/L, magnesium of 1.5 mg/dL, reduced kidney function, poor intake and QT-active medication, the authored post-team report of sinus bradycardia at 52/min with 112/68 mmHg, and the later check without recurrence are authored constants; no defibrillation, electrolyte or repolarization model is claimed, and no outcome follows from any choice. tests/integration/torsades-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson is a strict chain and then a fork, and the chain is the argument. Recognition, the unsynchronized-shock intent and the elapsed post-shock review must happen in that order, and the engine refuses the cause and magnesium work until the shock intent is recorded — the delay a learner who knows the word torsades is most likely to introduce is the delay the engine will not accept. Only afterwards do the long-QT context and the recurrence-suppression intent become an unordered pair, with the handoff refusing until both have landed. Two time gates enforce elapsed time: the post-team report refuses until a tick has passed since the shock intent, and the handoff refuses until a tick has passed since the later of the two closing lanes.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile the fixed sustained polymorphic VT report, the mechanical pulse, the compromise and the preceding long-QT context while keeping torsades distinct from monomorphic VT, from fibrillation and from a rate-only reading; record immediate unsynchronized-shock intent without waiting for magnesium, a cause checklist, synchronization or an energy calculation; review the elapsed authored post-team rhythm and the persistent QT risk it does not resolve; review QT-active medications and interactions, kidney function, bradycardia and pauses, electrolytes, and ischemic, structural and inherited context without proving one cause; record long-QT-bounded magnesium, electrolyte-correction, culprit-medication, monitoring and expert-strategy intent; and hand off persistent risk, recurrence and pulse-loss triggers, open work and owners. The lesson examines nobody, acquires or interprets no pulse, ECG, monitor, laboratory or imaging data, diagnoses no cause, selects no shock energy or sedation, operates no defibrillator, delivers no shock, CPR, oxygen, magnesium, electrolyte, medication, infusion, pacing or isoproterenol, assesses no capture, chooses no device, determines no disposition or prognosis, and predicts no recurrence or outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded recurrence-risk handoff on an authored later check that remains sinus bradycardia at 52/min with preserved perfusion and no recurrence in this interval. Later actions cannot restart an ended branch, and the ending certifies initialPulsePresent true, shockDeliveredByLearner false and treatmentDeliveredByLearner false — the treating team shocked her, the learner recorded intent, and one quiet interval is explicitly not durable freedom from recurrence.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual is the one the name invites: the common-error path recognises the rhythm correctly and then reaches for the magnesium and the QT while she is still in it, meeting one of six — the engine refuses both, because the cause work is gated behind the shock intent, and the rest of the lesson never becomes available. The recovery path records the shock intent before the pattern and the pulse have been reconciled and is refused, walks into both elapsed-time gates before clearing them, takes the closing pair in the other order — which the engine accepts without comment — and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['torsades-fixtures.ts binds exact-content expert, magnesium-while-she-is-still-in-it error, recovery, and no-action pathways to seed 7712 for deterministic replay through the shared engine, including the opening order refusal, the shock-before-cause refusal, both elapsed-time refusals, and the both-lanes refusal on the handoff.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Seven observed-state prompts at version ${TORSADES_TUTOR_VERSION} read the learner's own recorded steps — seven rather than six because the closing unordered pair needs a beat for the state where neither lane has been taken. The reflex the tutor works against is the word torsades itself: knowing the name pulls straight towards magnesium and the QT, and both are the second half of this lesson. The recognition beat asks for the pattern and the pulse in the same breath and says what each one changes. The shock beat gives the specific mechanical reason unsynchronized is not a preference — the complexes vary beat to beat, so a synchronizing machine has nothing to fire on and will sit there refusing while she gets worse. The post-shock beat says twice that the team delivered the shock, and points out that converting to 52 with a QTc of 560 ms is the substrate that produced the arrhythmia rather than an escape from it. The context beat lists five contributors and refuses to pick one, including the bradycardia she has just converted into. The recurrence beat holds the boundary that makes magnesium appropriate here and not for a normal QT. The handoff beat says one quiet interval proves nothing about the next. Worked example ${TORSADES_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the handoff, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts that no beat anywhere names an energy, a dose, a sedative, or a single proven cause. tests/unit/torsades-demonstration.test.ts verifies both closing orderings and every beat against the real engine, and tests/ui/cardiology-torsades.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
