/** Post-emergency hyperkalemic conduction reassessment without learner treatment delivery. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const HYPERKALEMIC_CONDUCTION_DISTURBANCE: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'hyperkalemic-conduction-disturbance', version: '0.1.0', maturity: 'draft',
    title: 'Hyperkalemic conduction disturbance', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 8, difficulty: 'advanced', objectives: [
      { id: 'reconcile-hyperkalemic-conduction-trajectory', statement: 'Reconcile the confirmed pretreatment hyperkalemia and conduction disturbance with the reported emergency treatment and current stable whole-patient state.', measure: 'The serial potassium, rhythm, QRS, pulse, perfusion, and reported-care facts were kept in the correct order without claiming one sole cause.' },
      { id: 'review-hyperkalemic-conduction-calcium-response', statement: 'Review the authored post-calcium conduction change without mistaking membrane stabilization for potassium removal.', measure: 'Narrower QRS and clearer atrial activity did not become a claim that potassium had fallen or the emergency had resolved.' },
      { id: 'review-hyperkalemic-conduction-shift-surveillance', statement: 'Review the reported shifting treatment and the required serial potassium, glucose, hypoglycemia, and rebound surveillance.', measure: 'No new drug, dose, route, glucose rescue, or live kinetic effect was selected or delivered.' },
      { id: 'review-hyperkalemic-conduction-removal-and-device-restraint', statement: 'Review kidney, medication, illness, removal, and owner context while deferring permanent-device conclusions during correction of a reversible metabolic disturbance.', measure: 'Renal and cause-control work remained explicit, and persistent conduction disease after correction remained an expert reevaluation trigger.' },
      { id: 'review-hyperkalemic-conduction-later-panel', statement: 'After elapsed time, review the authored later potassium, glucose, rhythm, QRS, and perfusion panel.', measure: 'Improvement remained a bounded serial report rather than proof of sole causation, durable resolution, or outcome.' },
      { id: 'handoff-hyperkalemic-conduction-reassessment', statement: 'After the later panel, hand off continued potassium, glucose, ECG, rebound, contributor, device-reevaluation, and ownership work.', measure: 'The exact open work and change triggers were recorded without prescribing treatment, pacing, disposition, or prognosis.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'UK Kidney Association. Clinical Practice Guideline: Management of Hyperkalaemia in Adults. October 2023.',
        'Lindner G, Burdmann EA, Clase CM, et al. Acute hyperkalemia in the emergency department: a summary from a Kidney Disease: Improving Global Outcomes conference. Eur J Emerg Med. 2020;27:329-337.',
        'Kusumoto FM, Schoenfeld MH, Barrett C, et al. 2018 ACC/AHA/HRS Guideline on the Evaluation and Management of Patients With Bradycardia and Cardiac Conduction Delay. Circulation. 2019;140:e382-e482.',
      ] },
    limitations: ['hyperkalemic-conduction-record-treatment-and-response-are-authored',
      'hyperkalemic-conduction-controls-record-review-restraint-and-handoff-only',
      'no-live-hyperkalemia-treatment-kinetics-pacing-device-or-outcome'],
  },
  patient: { ageYears: 72, sex: 'female', heightCm: 164, weightKg: 67, asaClass: 4,
    diagnosis: 'Authored hyperkalemic conduction disturbance after reported emergency treatment; residual cause remains open',
    procedure: 'Post-emergency conduction, surveillance, and device-restraint reassessment',
    comorbidities: ['Chronic kidney disease', 'Heart failure with reduced ejection fraction'],
    medications: ['Potassium-raising therapies are reported for clinician-led reconciliation'],
    allergies: ['No known drug allergies'],
    fasting: 'Monitored post-emergency consultation; not relevant to this lesson',
    baseline: { heartRateBpm: 52, meanArterialMmHg: 86, strokeVolumeMl: 60,
      hemoglobinGPerDl: 11.9, bloodVolumeMl: 4500, coreTemperatureC: 36.7,
      arterialStiffness: 1.2, baroreflexGain: 0.78, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Alert, speaking comfortably, warm, with a palpable regular pulse' },
    respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'],
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 440,
      respiratoryRateBpm: 16, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'hyperkalemic-conduction-rhythm', type: 'rhythm-change', target: 'hyperkalemic-conduction',
      atTick: 0, severity: 'warning',
      message: 'The teaching monitor shows the current organized slow rhythm with attenuated P waves, widened conduction, a prominent narrow T wave, and a mechanical pulse. It supports pattern rehearsal but does not diagnose hyperkalemia or intrinsic conduction disease.' },
    { id: 'hyperkalemic-conduction-presentation', type: 'narrative',
      target: 'hyperkalemic-conduction-disturbance', atTick: 0, severity: 'warning',
      message: 'Cardiology receives a monitored post-emergency handoff for a 72-year-old woman with chronic kidney disease and HFrEF after poor intake and acute kidney injury. The fixed pretreatment record reported nonhemolyzed potassium 6.9 mmol/L, HR 38/min with a palpable pulse, attenuated P waves, and QRS 154 ms. Reported IV calcium has already occurred. The current fixed report shows HR 52/min, clearer P waves, QRS 112 ms, BP 118/70 mmHg, SpO\u2082 97% on room air, alert mentation, and warm perfusion. Potassium remains 6.9 mmol/L in the authored immediate post-calcium record; no potassium-lowering effect is attributed to calcium. Reported insulin-glucose and a locally selected adjunct shifting path are already underway.' },
    { id: 'hyperkalemic-conduction-boundary', type: 'narrative',
      target: 'hyperkalemic-conduction-disturbance-boundary', atTick: 0, severity: 'advisory',
      message: 'Reconcile the serial potassium, conduction, pulse, perfusion, and reported-care record. Review why post-calcium conduction improvement does not remove potassium, then review shifting-treatment glucose, potassium, hypoglycemia, and rebound surveillance. Review kidney, medication, illness, removal, and owner context while deferring permanent-device conclusions during correction of a potentially reversible disturbance. After real elapsed time, a fixed later panel reports potassium 5.8 mmol/L, glucose 92 mg/dL, sinus rhythm 62/min, QRS 98 ms, and preserved perfusion. Improvement does not prove sole causation, durable resolution, or outcome. Examination; specimen, ECG, monitoring, or imaging acquisition or interpretation; diagnosis; calcium, insulin, glucose, beta-agonist, binder, dialysis, medication, or rescue delivery; dose or target selection; live kinetics; pacing eligibility, device choice, implantation, programming, or capture; disposition, prognosis, recurrence, and outcome are not simulated.' },
  ],
  debrief: { rubric: [
    { id: 'hyperkalemic-conduction-trajectory', objectiveId: 'reconcile-hyperkalemic-conduction-trajectory', question: 'How did the pretreatment and current potassium, conduction, pulse, perfusion, and reported-care facts fit together?' },
    { id: 'hyperkalemic-conduction-calcium', objectiveId: 'review-hyperkalemic-conduction-calcium-response', question: 'What changed after reported calcium, and why did that not establish potassium removal or resolution?' },
    { id: 'hyperkalemic-conduction-shift', objectiveId: 'review-hyperkalemic-conduction-shift-surveillance', question: 'Which potassium, glucose, hypoglycemia, and rebound surveillance remained necessary after reported shifting treatment?' },
    { id: 'hyperkalemic-conduction-removal', objectiveId: 'review-hyperkalemic-conduction-removal-and-device-restraint', question: 'Which removal and contributor work remained, and why were permanent-device conclusions deferred?' },
    { id: 'hyperkalemic-conduction-later-panel', objectiveId: 'review-hyperkalemic-conduction-later-panel', question: 'What improved in the elapsed later panel, and what did that serial report not prove?' },
    { id: 'hyperkalemic-conduction-handoff', objectiveId: 'handoff-hyperkalemic-conduction-reassessment', question: 'Which surveillance, rebound, contributor, device-reevaluation, trigger, and ownership details were handed off?' },
  ] },
};
