/** Renal-retinal hypertensive-emergency reassessment without learner treatment delivery. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const HYPERTENSIVE_EMERGENCY: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'hypertensive-emergency', version: '0.1.0', maturity: 'draft',
    title: 'Hypertensive emergency', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 9, difficulty: 'advanced', objectives: [
      { id: 'reconcile-hypertensive-emergency-measurement-and-trajectory', statement: 'Verify the authored measurement conditions and reconcile the repeated pressure, symptoms, medication interruption, and whole-patient trajectory.', measure: 'A correctly measured persistent pressure trajectory prompted urgent review without using the number alone.' },
      { id: 'review-hypertensive-emergency-organ-injury', statement: 'Identify acute renal and retinal target-organ injury while screening other current organ emergencies and deterioration triggers.', measure: 'The emergency rested on new or worsening organ injury rather than marked pressure alone.' },
      { id: 'review-hypertensive-emergency-phenotype-and-causes', statement: 'Review the renal-retinal phenotype, medication interruption, and open primary and secondary contributors without assigning one cause.', measure: 'Current snapshots separated this lesson from pulmonary edema, ACS, aortic syndrome, stroke, ICH, and pregnancy without permanently excluding change.' },
      { id: 'record-hypertensive-emergency-controlled-reduction-intent', statement: 'Record prompt monitored, syndrome-specific pressure-control intent without selecting a drug, dose, infusion rate, universal target, or rapid normalization.', measure: 'The control frame preserved perfusion and organ-specific pathways without a browser recipe.' },
      { id: 'review-hypertensive-emergency-later-panel', statement: 'After elapsed time, review the authored 45-minute pressure, symptoms, perfusion, and neurologic panel without claiming learner-delivered response.', measure: 'Directional improvement did not become a drug-effect, resolution, or outcome claim.' },
      { id: 'handoff-hypertensive-emergency-reassessment', statement: 'After another elapsed interval, hand off the authored 3-hour renal-retinal, pressure, symptom, cause, treatment, and ownership trajectory.', measure: 'Ongoing visual symptoms and kidney injury remained open without determining disposition, prognosis, or outcome.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'Jones DW, Ferdinand KC, Taler SJ, et al. 2025 AHA/ACC/AANP/AAPA/ABC/ACCP/ACPM/AGS/AMA/ASPC/NMA/PCNA/SGIM Guideline for the Prevention, Detection, Evaluation and Management of High Blood Pressure in Adults. Circulation. 2025. doi:10.1161/CIR.0000000000001356.',
        'Bress AP, Anderson TS, Flack JM, et al. The Management of Elevated Blood Pressure in the Acute Care Setting: A Scientific Statement From the American Heart Association. Hypertension. 2024;81:e94-e106. doi:10.1161/HYP.0000000000000238.',
      ] },
    limitations: ['hypertensive-emergency-findings-and-panels-are-authored',
      'hypertensive-emergency-controls-record-review-and-intent-only',
      'no-live-hypertensive-emergency-testing-treatment-procedure-disposition-or-outcome'],
  },
  patient: { ageYears: 58, sex: 'female', heightCm: 165, weightKg: 76, asaClass: 4,
    diagnosis: 'Authored renal-retinal hypertensive emergency',
    procedure: 'Hypertensive-emergency reassessment in a monitored cardiac unit',
    comorbidities: ['Hypertension'], medications: ['Antihypertensive regimen interrupted after a 3-week refill gap'],
    allergies: ['No known drug allergies'], fasting: 'Acute cardiac admission; fasting state not represented',
    baseline: { heartRateBpm: 86, meanArterialMmHg: 167, strokeVolumeMl: 66,
      hemoglobinGPerDl: 12.6, bloodVolumeMl: 4700, coreTemperatureC: 36.8,
      arterialStiffness: 1.4, baroreflexGain: 0.65, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Alert, coherent, nonfocal, and speaking complete sentences' },
    respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'],
    airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21,
      tidalVolumeMl: 500, respiratoryRateBpm: 16, freshGasFlowLPerMin: 10, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'hypertensive-emergency-presentation', type: 'narrative',
      target: 'hypertensive-emergency-reassessment', atTick: 0, severity: 'critical',
      message: 'A 58-year-old woman with hypertension and a 3-week refill interruption reports 3 days of headache and bilateral blurred vision. An initial authored pressure was 238/134 mmHg. After documented rest, correct positioning, and a correctly sized cuff, current repeated readings are right arm 236/132 and left arm 232/130 mmHg. HR is 86/min in sinus rhythm, RR 16/min, SpO₂ 98% on room air, and temperature 36.8°C. She is alert, coherent, nonfocal, and warm. Marked pressure alone does not establish hypertensive emergency.' },
    { id: 'hypertensive-emergency-organ-injury', type: 'narrative',
      target: 'hypertensive-emergency-reassessment', atTick: 0, severity: 'critical',
      message: 'Fixed fundus report: bilateral flame hemorrhages, cotton-wool spots, and optic-disc edema. Creatinine is 2.1 mg/dL compared with 0.9 mg/dL 6 months earlier; urinalysis reports 2+ protein and microscopic hematuria. Platelets are 214,000/µL and hemoglobin 12.6 g/dL. This authored acute renal-retinal target-organ injury plus the verified pressure trajectory establishes hypertensive emergency in this case; the controls do not perform fundoscopy, collect a specimen, or interpret a real test.' },
    { id: 'hypertensive-emergency-phenotype', type: 'narrative',
      target: 'hypertensive-emergency-reassessment', atTick: 0, severity: 'warning',
      message: 'Fixed ECG reports sinus rhythm, LVH, and no acute ischemic change. Lungs are clear; fixed echo reports LVEF 60%, concentric LVH, no acute heart-failure finding, and no effusion. No chest or back pain, dyspnea, pregnancy, pulmonary edema, ACS trajectory, pressure or pulse asymmetry, focal deficit, seizure, altered mentation, or aortic pattern is authored now. These are snapshots and change triggers, not permanent exclusions. Medication access, adherence, kidney disease, substances, interactions, and primary and secondary contributors remain open rather than assigned to the refill gap alone.' },
    { id: 'hypertensive-emergency-boundary', type: 'narrative',
      target: 'hypertensive-emergency-reassessment-boundary', atTick: 0, severity: 'warning',
      message: 'Reconcile verified measurement and trajectory, then review acute target-organ injury. Review phenotype and causes while recording prompt monitored, syndrome-specific controlled-reduction intent in parallel. No drug, dose, infusion rate, fixed percentage, universal target, or rapid normalization is selected; pulmonary edema, ACS, aortic disease, ICH, ischemic stroke, pregnancy, and toxicologic syndromes require their own current pathways. After a later engine tick, a fixed experienced-team 45-minute report gives BP 212/122 mmHg, HR 82/min, alert nonfocal mentation, easing headache, persistent visual symptoms, warm perfusion, and no chest or back pain or dyspnea. After another later tick, a fixed 3-hour report gives BP 188/106 mmHg, HR 80/min, improved headache, vision not worse, alert nonfocal mentation, clear lungs, urine output 38 mL/h, and creatinine 2.1 mg/dL. These authored reports do not represent learner treatment or establish resolution. The controls do not examine; acquire or interpret monitoring, ECG, imaging, fundoscopy, or laboratory data; diagnose a real patient; select or deliver a drug, fluid, oxygen, ventilation, or another treatment; perform a procedure; determine disposition or prognosis; or predict outcome.' },
  ],
  debrief: { rubric: [
    { id: 'hypertensive-emergency-measurement', objectiveId: 'reconcile-hypertensive-emergency-measurement-and-trajectory', question: 'Which measurement, repeat-pressure, symptom, medication, and whole-patient facts made the trajectory reliable without using the number alone?' },
    { id: 'hypertensive-emergency-organ-injury', objectiveId: 'review-hypertensive-emergency-organ-injury', question: 'Which acute retinal and renal findings distinguished emergency from marked pressure without acute organ injury?' },
    { id: 'hypertensive-emergency-phenotype', objectiveId: 'review-hypertensive-emergency-phenotype-and-causes', question: 'Which current competing emergency findings were absent, which changes remained triggers, and which causes stayed open?' },
    { id: 'hypertensive-emergency-reduction', objectiveId: 'record-hypertensive-emergency-controlled-reduction-intent', question: 'Why was pressure-control intent prompt and monitored but free of a universal target, rapid normalization, drug, dose, or infusion recipe?' },
    { id: 'hypertensive-emergency-later-panel', objectiveId: 'review-hypertensive-emergency-later-panel', question: 'What changed at the authored 45-minute panel, and why was it not learner-delivered treatment response or resolution?' },
    { id: 'hypertensive-emergency-handoff', objectiveId: 'handoff-hypertensive-emergency-reassessment', question: 'Which renal-retinal injury, symptoms, pressure, causes, treatment work, owners, and triggers remained open at 3 hours?' },
  ] },
};
