/** Pulseless transition despite authored transcutaneous electrical capture. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const TRANSCUTANEOUS_PACING_MECHANICAL_CAPTURE_REASSESSMENT: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'transcutaneous-pacing-mechanical-capture-reassessment', version: '0.1.0', maturity: 'preview',
    title: 'Transcutaneous pacing mechanical capture reassessment', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 9, difficulty: 'advanced', objectives: [
      { id: 'reconcile-transcutaneous-pacing-electrical-and-mechanical-capture', statement: 'Reconcile the fixed pacing artifacts, paced QRS and T-wave complexes, central pulse assessment, pleth, arterial waveform, pressure, and perfusion.', measure: 'Authored electrical capture remained distinct from absent mechanical capture and pulse loss.' },
      { id: 'activate-transcutaneous-pacing-pulseless-response', statement: 'Activate the nonshockable pulseless response immediately without waiting for complete pacing or cause review.', measure: 'Pulse loss opened uninterrupted arrest care without treating paced QRS complexes as circulation.' },
      { id: 'review-transcutaneous-pacing-open-causes-and-bridge', statement: 'Review open reversible causes and future pacing-bridge needs while pulseless care continues.', measure: 'Cause and bridge review did not delay arrest care, assign one mechanism, or select a drug, device, or procedure.' },
      { id: 'handoff-transcutaneous-pacing-reassessment', statement: 'After elapsed time, hand off active resuscitation, capture findings, open causes, and future pacing-bridge ownership.', measure: 'The handoff preserved ongoing pulseless care and left return of circulation, disposition, prognosis, and outcome unreported.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'Wigginton JG, Agarwal S, Bartos JA, et al. Part 9: Adult Advanced Life Support: 2025 American Heart Association Guidelines for CPR and ECC. Circulation. 2025;152(suppl 2):S538-S577. doi:10.1161/CIR.0000000000001376.',
        'Kusumoto FM, Schoenfeld MH, Barrett C, et al. 2018 ACC/AHA/HRS Guideline on the Evaluation and Management of Patients With Bradycardia and Cardiac Conduction Delay. Circulation. 2019;140:e382-e482. doi:10.1161/CIR.0000000000000628.',
      ] },
    limitations: ['transcutaneous-pacing-capture-and-perfusion-findings-are-authored',
      'transcutaneous-pacing-controls-record-recognition-review-and-handoff-only',
      'no-live-transcutaneous-pacing-arrest-treatment-procedure-disposition-or-outcome'],
  },
  patient: { ageYears: 68, sex: 'female', heightCm: 165, weightKg: 70, asaClass: 4,
    diagnosis: 'Authored complete heart block followed by pulseless electrical activity despite transcutaneous electrical capture',
    procedure: 'Mechanical-capture rescue and reassessment in a monitored Cardiology unit',
    comorbidities: ['Complete atrioventricular block', 'Hypertension'],
    medications: ['Medication list under urgent reconciliation'], allergies: ['No known drug allergies'],
    fasting: 'Acute cardiac admission; fasting state not represented',
    baseline: { heartRateBpm: 25, meanArterialMmHg: 50, strokeVolumeMl: 48,
      hemoglobinGPerDl: 12.8, bloodVolumeMl: 4600, coreTemperatureC: 36.6,
      arterialStiffness: 1.2, baroreflexGain: 0.8, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Unresponsive with agonal breaths after the authored pulse-loss transition' },
    respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'arterial-line', 'pulse-oximetry', 'temperature'],
    airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21,
      tidalVolumeMl: 450, respiratoryRateBpm: 20, freshGasFlowLPerMin: 10, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'transcutaneous-pacing-mechanical-capture-presentation', type: 'narrative',
      target: 'transcutaneous-pacing-mechanical-capture-reassessment', atTick: 0,
      severity: 'critical',
      message: 'In a monitored Cardiology unit, a 68-year-old woman with reported complete atrioventricular block becomes confused, cool, and poorly perfused with ventricular rate and central pulse 24/min and BP 70/40 mmHg. An experienced team initiates transcutaneous pacing. A fixed 10-second report then shows pacing stimuli at 70/min, each followed by a broad QRS and distinct T wave, establishing authored electrical capture rather than artifact or afterpotential in this case. She becomes unresponsive with agonal breaths; the fixed assessment reports no carotid or femoral pulse, a nonpulsatile existing arterial line, nonpulsatile pleth, and unobtainable BP. This is absent mechanical capture with pulse loss and pulseless electrical activity, not persistent bradycardia. The controls do not examine, palpate, acquire or interpret ECG or waveforms, or assess capture.' },
    { id: 'transcutaneous-pacing-electrical-without-mechanical-capture', type: 'rhythm-change',
      target: 'paced-electrical-no-mechanical-capture', atTick: 0, severity: 'critical',
      message: 'The live teaching trace now shows authored paced electrical activity at 70/min with no mechanical arterial or pleth pulse.' },
    { id: 'transcutaneous-pacing-mechanical-capture-context', type: 'narrative',
      target: 'transcutaneous-pacing-mechanical-capture-reassessment', atTick: 0,
      severity: 'warning',
      message: 'Electrical capture does not establish circulation. Activate uninterrupted nonshockable-arrest care before reviewing open metabolic, ischemic, mechanical, myocardial, medication, conduction, electrode, connection, device, and measurement causes or future pacing-bridge needs. No output, current, pulse width, pad placement, drug, dose, or procedure is shown or selected.' },
    { id: 'transcutaneous-pacing-mechanical-capture-boundary', type: 'narrative',
      target: 'transcutaneous-pacing-mechanical-capture-reassessment-boundary', atTick: 0,
      severity: 'warning',
      message: 'Reconcile electrical and mechanical capture first, activate the pulseless response immediately, and then review open causes and future pacing-bridge needs while uninterrupted nonshockable-arrest care continues. After a later engine tick, hand off the fixed electrical-capture and absent-mechanical-capture evidence, active resuscitation, cause work, bridge questions, and owners. Return of spontaneous circulation, subsequent perfusion, neurologic status, disposition, prognosis, and outcome are intentionally unreported. The controls do not examine; palpate a pulse; acquire or interpret ECG, monitoring, laboratory, or imaging data; place pads; operate a pacer; select rate, output, current, pulse width, energy, drug, dose, sedation, or pacing modality; deliver pacing, CPR, or treatment; perform a procedure; determine disposition or prognosis; or predict outcome.' },
  ],
  debrief: { rubric: [
    { id: 'transcutaneous-pacing-capture-reconciliation', objectiveId: 'reconcile-transcutaneous-pacing-electrical-and-mechanical-capture', question: 'Which fixed findings established electrical capture, and which established absent mechanical capture and pulse loss?' },
    { id: 'transcutaneous-pacing-pulseless-response', objectiveId: 'activate-transcutaneous-pacing-pulseless-response', question: 'Why did paced QRS complexes not delay the nonshockable pulseless response?' },
    { id: 'transcutaneous-pacing-causes-bridge', objectiveId: 'review-transcutaneous-pacing-open-causes-and-bridge', question: 'Which causes and future pacing-bridge questions remained open during pulseless care?' },
    { id: 'transcutaneous-pacing-handoff', objectiveId: 'handoff-transcutaneous-pacing-reassessment', question: 'Which active resuscitation, capture, cause, bridge, and ownership work remained open without a reported outcome?' },
  ] },
};
