/** Antepartum concealed-hemorrhage pattern with maternal and fetal compromise. */
import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['reconcile-obstetrics-abruption-pain-visible-blood-maternal-physiology-fetal-context-and-whole-person', 'Connect pain, visible blood, maternal physiology, fetal context, and whole person.', 'The fixed clock, pain, visible blood, maternal state, uterine pattern, fetal report, coagulation evidence, support needs, and whole person were connected without learner measurement, examination, interpretation, calculation, or diagnosis.'],
  ['recognize-obstetrics-abruption-concealed-hemorrhage-pattern-without-visible-volume-ultrasound-or-single-cause-closure', 'Recognize concealed hemorrhage without visible-volume, ultrasound-, or single-cause closure.', 'Maternal-fetal compromise with a supplied abruption pattern was recognized while visible volume, ultrasound, uterine findings, fetal findings, and one cause remained insufficient.'],
  ['activate-obstetrics-abruption-hemorrhage-anesthesia-blood-bank-operating-room-neonatal-and-dignity-ownership', 'Bring hemorrhage, anesthesia, blood-bank, operating-room, neonatal, and dignity-centered owners together.', 'Qualified simultaneous resuscitation, delivery-readiness, coagulation, neonatal, pain, privacy, consent, communication, and support ownership began without learner treatment or delivery selection.'],
  ['review-obstetrics-abruption-supplied-perfusion-uterine-fetal-coagulation-placental-and-competing-cause-boundary', 'Review supplied perfusion, uterine, fetal, coagulation, placental, and competing-cause evidence.', 'Supplied maternal, fetal, uterine, coagulation, placental-location, rupture, previa, vasa-previa, labor, trauma, and non-obstetric boundaries were integrated without learner acquisition, interpretation, diagnosis, or exclusion.'],
  ['record-obstetrics-abruption-bounded-qualified-resuscitation-coagulation-and-urgent-delivery-intent-with-strict-later-review', 'Record bounded resuscitation, coagulation, and urgent-delivery intent, then review the strict later report.', 'Qualified simultaneous hemorrhage, blood-bank, coagulation, anesthesia, operating-room, delivery and neonatal intent was recorded without learner product, dose, route, volume, target, technique, procedure, delivery, or treatment-effect claim.'],
  ['handoff-obstetrics-abruption-concealed-loss-shock-coagulopathy-fetal-delivery-neonatal-bereavement-and-outcome-risk', 'Hand off concealed loss, shock, coagulopathy, fetal, delivery, neonatal, bereavement, and outcome risk.', 'The handoff preserved total loss, shock, coagulopathy, fetal compromise, delivery, anesthesia, neonatal, pathology, recurrence, dignity, support, disposition, fertility, and outcome uncertainty.'],
] as const;

export const CONCEALED_PLACENTAL_ABRUPTION_HEMORRHAGE: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'concealed-placental-abruption-hemorrhage', version: '0.1.0', maturity: 'draft', title: 'Concealed hemorrhage: trust the whole maternal-fetal pattern', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 7, difficulty: 'advanced', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Smith CD, Lee A. Placental abruption. BJA Education. 2024;24(9):305-308. PMID 39234154.', 'Royal College of Obstetricians and Gynaecologists. Antepartum Haemorrhage. Green-top Guideline No. 63. 2011.'] }, limitations: ['concealed-abruption-maternal-fetal-coagulation-and-response-pattern-are-authored', 'concealed-abruption-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-concealed-abruption-exam-trace-imaging-blood-drug-anesthesia-delivery-disposition-or-outcome'] },
  patient: { ageYears: 34, sex: 'female', heightCm: 166, weightKg: 78, asaClass: 4, diagnosis: 'Authored concealed antepartum hemorrhage with maternal-fetal compromise and open causes', procedure: 'concealed-hemorrhage recognition, coordinated ownership, reassessment, and handoff practice', comorbidities: ['36 weeks 4 days pregnant'], medications: ['Prenatal medication history remains supplied context'], allergies: ['No known drug allergies'], fasting: 'Intake and anesthesia planning remain qualified-team work', baseline: { heartRateBpm: 126, meanArterialMmHg: 68, strokeVolumeMl: 54, hemoglobinGPerDl: 9.8, bloodVolumeMl: 5000, coreTemperatureC: 36.8, arterialStiffness: 1, baroreflexGain: 1.2, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Restless and pale but conversant; no authored airway obstruction or respiratory failure' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 500, respiratoryRateBpm: 26, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'concealed-abruption-presentation', type: 'narrative', target: 'concealed-placental-abruption-hemorrhage-transition', atTick: 0, severity: 'critical', message: 'A 34-year-old at 36 weeks 4 days has 35 minutes of abrupt constant abdominal and back pain. Only 80 mL dark blood is externally collected, but qualified staff report a tense tender uterus, pallor, restlessness, HR 126/min, BP 92/56 mmHg (MAP 68), RR 26/min, pulse-coherent room-air SpO2 98%, T 36.8°C, fetal baseline 170/min with minimal variability and recurrent late decelerations, hemoglobin 9.8 g/dL, platelets 112 × 10^9/L, fibrinogen 1.5 g/L, INR 1.4 and lactate 4.0 mmol/L. There is no authored placenta previa on the supplied prior placental-location record, major trauma, seizure, severe hypertension, focal deficit, chest pain, hypoxemia, or cardiac arrest.' },
    { id: 'concealed-abruption-boundary', type: 'narrative', target: 'concealed-placental-abruption-hemorrhage-transition-boundary', atTick: 0, severity: 'warning', message: 'Connect pain, visible blood, maternal physiology, uterine pattern, fetal context, coagulation and whole person; recognize concealed hemorrhage with a supplied abruption pattern without equating visible blood with total loss or using ultrasound or one cause to close the diagnosis; bring qualified obstetric hemorrhage, anesthesia, nursing, blood-bank, operating-room, neonatal, pain, privacy, consent, communication and support ownership together; review perfusion, fetal, coagulation, placental-location, rupture, previa, vasa-previa, labor, trauma and non-obstetric boundaries; then record bounded simultaneous resuscitation, coagulation and urgent-delivery intent. After elapsed time, a strict fixed 10-minute report supplies HR 118/min, BP 98/60 mmHg (MAP 73), RR 22/min, SpO2 99% on supplied support, persistent fetal compromise, 120 mL visible cumulative blood, operating-room readiness, and unresolved total loss, coagulation, anesthesia and delivery. Controls do not examine, measure, calculate, interpret fetal monitoring, acquire or interpret tests or imaging, diagnose, prescribe, deliver fluid or blood, select anesthesia, perform a procedure or delivery, determine disposition, or predict fertility or maternal/newborn outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `concealed-abruption-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
