import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-obstetrics-failed-intubation-oxygenation-anesthesia-obstetric-theatre-newborn-and-support-response', 'Declare failed intubation and activate oxygenation-first shared ownership.', 'The failed airway was named after the supplied attempt limit and experienced help, obstetric, theatre, newborn, communication, dignity, and support ownership were activated first.'],
  ['reconcile-obstetrics-failed-intubation-attempts-device-ventilation-aspiration-fetus-and-whole-person', 'Connect attempts, rescue device, ventilation, aspiration, fetal urgency, and the whole person.', 'The supplied airway and maternal-fetal context was connected without learner examination, monitoring interpretation, diagnosis, or treatment.'],
  ['review-obstetrics-failed-intubation-attempt-limit-oxygenation-cico-awareness-and-aspiration-boundaries', 'Review attempt-limit, oxygenation, CICO, awareness, and aspiration boundaries.', 'Adequate authored oxygenation did not erase device, aspiration, awareness, displacement, deterioration, or CICO risk.'],
  ['review-obstetrics-failed-intubation-individualized-wake-or-proceed-and-parallel-readiness', 'Review the individualized wake-or-proceed decision and parallel readiness.', 'Maternal, fetal, staff, surgical, aspiration, device, airway-hazard, birth, newborn, and support factors were reviewed without a learner decision or procedure.'],
  ['review-obstetrics-failed-intubation-fixed-three-minute-qualified-course-report', 'Review the fixed 3-minute qualified-team course report.', 'The authored report was reviewed without claiming learner airway care, surgery, delivery, fetal recovery, or outcome.'],
  ['handoff-obstetrics-failed-intubation-airway-aspiration-awareness-birth-newborn-support-and-outcome-risk', 'Hand off airway, aspiration, awareness, birth, newborn, support, and outcome risk.', 'The handoff preserved airway, device, oxygenation, aspiration, awareness, maternal, fetal, birth, newborn, disposition, and outcome uncertainty.'],
] as const;

export const FAILED_OBSTETRIC_INTUBATION_OXYGENATION_FIRST: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'failed-obstetric-intubation-oxygenation-first', version: '0.1.0', maturity: 'draft', title: 'Failed obstetric intubation: oxygenation first', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Mushambi MC, Kinsella SM, Popat M, et al. OAA/DAS guidelines for difficult and failed tracheal intubation in obstetrics. Anaesthesia. 2015;70:1286-1306.'] }, limitations: ['failed-obstetric-intubation-attempt-airway-device-maternal-fetal-and-qualified-course-reports-are-authored', 'failed-obstetric-intubation-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-failed-obstetric-intubation-airway-monitor-anesthesia-drug-surgery-birth-procedure-or-outcome'] },
  patient: { ageYears: 33, sex: 'female', heightCm: 168, weightKg: 92, asaClass: 4, diagnosis: 'Supplied failed tracheal intubation with adequate qualified rescue-device oxygenation during category-1 caesarean birth', procedure: 'obstetric failed-intubation declaration, oxygenation-first coordination, individualized decision-boundary review, reassessment, and active-risk handoff practice', comorbidities: ['39 weeks 1 day pregnant; persistent fetal bradycardia after qualified intrauterine resuscitative measures'], medications: ['General-anesthesia induction and neuromuscular-blocking drugs were administered by qualified anesthesia staff; products, doses, timing, effects, and reversal remain outside learner control'], allergies: ['No known drug allergies'], fasting: 'Ate 3 hours ago; aspiration risk remains active qualified-team work', baseline: { heartRateBpm: 112, meanArterialMmHg: 78, strokeVolumeMl: 66, hemoglobinGPerDl: 11.5, bloodVolumeMl: 5200, coreTemperatureC: 36.7, arterialStiffness: 1, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.8, difficultMaskVentilation: true, assessment: 'Qualified staff report 2 unsuccessful tracheal-intubation attempts, declared failure, and effective ventilation through a second-generation supraglottic airway; no learner airway examination or intervention occurs' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'capnography', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 1, tidalVolumeMl: 480, respiratoryRateBpm: 12, freshGasFlowLPerMin: 10, delivering: true } }, formulary: [],
  timeline: [
    { id: 'failed-obstetric-intubation-presentation', type: 'narrative', target: 'failed-obstetric-intubation-oxygenation-first-transition', atTick: 0, severity: 'critical', message: 'A 33-year-old at 39 weeks 1 day required category-1 caesarean birth for fetal bradycardia persisting at 68/min after qualified intrauterine resuscitative measures. A neuraxial technique was not functional, so qualified staff induced general anesthesia. Two tracheal-intubation attempts were unsuccessful and failed intubation has been declared. Experienced help is present. Qualified staff report effective ventilation through a second-generation supraglottic airway with sustained waveform capnography, bilateral air entry, HR 112/min, BP 106/64 mmHg (MAP 78), delivered RR 12/min, SpO2 nadir 93% and now 97%, temperature 36.7°C, and fetal baseline 70/min. No airway bleeding, stridor, or visible swelling is supplied, but device displacement, aspiration, awareness, oxygenation deterioration, and progression to can’t-intubate-can’t-oxygenate remain possible. The patient is anesthetized and cannot participate in the discussion.' },
    { id: 'failed-obstetric-intubation-boundary', type: 'narrative', target: 'failed-obstetric-intubation-oxygenation-first-transition-boundary', atTick: 0, severity: 'warning', message: 'Declare the failed intubation, protect oxygenation, stop repeated laryngoscopy, and activate experienced anesthesia and airway, obstetric, theatre, newborn, nursing, pharmacy, critical-care, leadership, timekeeping, documentation, communication, dignity, family, and staff-support ownership. Connect attempts, device and seal, capnography and ventilation, oxygenation trend, aspiration and awareness risk, maternal state, fetal urgency, surgical complexity, staff experience, alternative anesthesia, airway hazards, and the whole person. Adequate oxygenation is not CICO, yet preparation for deterioration remains qualified-team work. The wake-or-proceed decision is individualized and revisited by the qualified team; no single fetal rate, device, or urgency label decides it. A fixed qualified-team report 3 minutes after declaration supplies stable second-generation supraglottic ventilation, sustained capnography with ETCO2 34 mmHg, HR 108/min, BP 110/66 mmHg (MAP 81), delivered RR 12/min, support-coherent SpO2 98%, fetal baseline still 70/min, no supplied airway hazard, and a documented multidisciplinary decision that surgery is essential and proceeding while airway rescue readiness continues. Incision has begun; delivery, newborn condition, aspiration, awareness, airway injury, treatment effect, disposition, and outcomes remain unresolved. Controls do not examine, measure, interpret monitoring, diagnose, attempt intubation, manipulate a mask or airway device, ventilate, give oxygen, release cricoid pressure, position, suction, perform front-of-neck access, give fluid, blood, anesthetic, reversal or another drug, choose a dose, device, airway, wake-or-proceed decision, anesthesia or birth plan, perform surgery, delivery, newborn care or another procedure, transfer, determine disposition, or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `failed-obstetric-intubation-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
