import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-obstetrics-high-neuraxial-block-airway-anesthesia-obstetric-theatre-newborn-and-support-response', 'Activate the high-neuraxial-block, airway-capable, obstetric, theatre, newborn, and support response.', 'The rapidly ascending maternal emergency triggered qualified shared ownership and close reassurance first.'],
  ['reconcile-obstetrics-high-neuraxial-block-injection-clock-level-breathing-arms-circulation-fetus-and-whole-person', 'Connect the injection clock, block level, breathing, arm strength, circulation, fetal context, and whole person.', 'The supplied trajectory was connected without learner examination, block assessment, monitoring interpretation, diagnosis, or treatment.'],
  ['review-obstetrics-high-neuraxial-block-rapid-progression-awareness-and-alternative-cause-boundaries', 'Review rapid progression, awareness, and alternative-cause boundaries.', 'The high-block pattern stayed highly concerning while vasovagal, aortocaval, toxicity, embolic, hemorrhagic, cardiopulmonary, and other causes remained open.'],
  ['review-obstetrics-high-neuraxial-block-parallel-airway-ventilation-circulation-uterine-displacement-fetal-birth-and-support-readiness', 'Review parallel airway, ventilation, circulation, uterine-displacement, fetal, birth, and support readiness.', 'Qualified simultaneous priorities were reviewed without learner airway, oxygen, ventilation, position, fluid, vasopressor, drug, dose, anesthesia, or birth actions.'],
  ['review-obstetrics-high-neuraxial-block-fixed-four-minute-qualified-support-report', 'Review the fixed 4-minute qualified support report.', 'The authored report was reviewed without claiming learner treatment, block resolution, fetal recovery, birth, or outcome.'],
  ['handoff-obstetrics-high-neuraxial-block-airway-circulation-block-fetal-birth-awareness-support-and-outcome-risk', 'Hand off airway, circulation, block, fetal, birth, awareness, support, and outcome risk.', 'The handoff preserved respiratory, cardiovascular, block-recession, fetal, birth, awareness, psychological, disposition, and outcome uncertainty.'],
] as const;

export const HIGH_NEURAXIAL_BLOCK_OBSTETRIC_COORDINATION: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'high-neuraxial-block-obstetric-coordination', version: '0.1.0', maturity: 'preview', title: 'High neuraxial block: stay close, act together', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Obstetric Anaesthetists’ Association. Obstetric Quick Reference Handbook: High central neuraxial block. Version 1, updated 2024.', 'Griffiths SK, Russell R, et al. Intrathecal catheter placement after inadvertent dural puncture in the obstetric population. Anaesthesia. 2024.'] }, limitations: ['high-neuraxial-block-injection-level-maternal-fetal-and-qualified-support-reports-are-authored', 'high-neuraxial-block-obstetric-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-high-neuraxial-block-exam-monitor-infusion-airway-circulation-drug-birth-procedure-or-outcome'] },
  patient: { ageYears: 31, sex: 'female', heightCm: 168, weightKg: 84, asaClass: 4, diagnosis: 'Supplied rapidly ascending high-neuraxial-block pattern after labour-epidural top-up for urgent caesarean birth', procedure: 'pregnancy-specific high-neuraxial-block recognition, qualified-response coordination, reassessment, and active-risk handoff practice', comorbidities: ['38 weeks 6 days pregnant; urgent caesarean birth was planned for a deteriorating fetal-heart pattern before the maternal block emergency'], medications: ['Qualified anesthesia staff stopped the epidural top-up when symptoms began; product, concentration, dose, catheter location, and spread remain outside learner control'], allergies: ['No known drug allergies'], fasting: 'Intrapartum intake, aspiration risk, and emergency airway planning remain qualified-team work', baseline: { heartRateBpm: 52, meanArterialMmHg: 54, strokeVolumeMl: 58, hemoglobinGPerDl: 11.3, bloodVolumeMl: 5000, coreTemperatureC: 36.8, arterialStiffness: 1, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.3, difficultMaskVentilation: false, assessment: 'Awake and frightened, with a weak voice, difficulty breathing, progressive arm weakness, and no authored airway obstruction' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 500, respiratoryRateBpm: 8, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'high-neuraxial-block-presentation', type: 'narrative', target: 'high-neuraxial-block-obstetric-coordination-transition', atTick: 0, severity: 'critical', message: 'A 31-year-old at 38 weeks 6 days received a labour-epidural top-up from qualified anesthesia staff 4 minutes ago for urgent caesarean birth after a deteriorating fetal-heart pattern. Over 90 seconds she developed rapidly ascending numbness, progressive arm weakness, difficulty breathing, and a weak voice while remaining awake and frightened. Qualified examination supplies bilateral sensory change to C6 and worsening hand grip. HR is 52/min, BP 78/42 mmHg (MAP 54), shallow RR 8/min, pulse-coherent room-air SpO2 96%, and temperature 36.8°C. The supplied fetal baseline is 90/min. Qualified staff have stopped injection, called for help, begun manual uterine displacement, and stayed close to reassure her. Product, concentration, dose, catheter location, exact block extent, airway trajectory, cause, and birth outcome remain unresolved.' },
    { id: 'high-neuraxial-block-boundary', type: 'narrative', target: 'high-neuraxial-block-obstetric-coordination-transition-boundary', atTick: 0, severity: 'warning', message: 'Activate qualified senior anesthesia and airway, obstetric, midwifery or nursing, theatre, newborn, pharmacy, critical-care, leadership, timekeeping, documentation, communication, dignity, family, and staff-support ownership now. Connect the injection clock, ascending sensory and motor findings, breathing, voice, consciousness, circulation, aortocaval context, fetal pattern, distress, and whole person. Rapid progression may reach apnea or unconsciousness, but vasovagal events, aortocaval compression, local-anesthetic toxicity, embolism, concealed hemorrhage, allergy, medication error, primary airway or cardiopulmonary causes, and other diagnoses remain open. Qualified airway and ventilation support, oxygen, circulation and vasopressor support, uterine displacement, monitoring, awareness prevention, fetal surveillance, birth planning, reassurance and post-event review proceed in parallel. A fixed qualified-team report 4 minutes after activation supplies airway-capable respiratory and circulation support underway, HR 78/min, BP 104/64 mmHg (MAP 77), supported RR 14/min, support-coherent SpO2 99%, fetal baseline 118/min, persistent arm weakness and a weak voice, and no loss of consciousness. Block recession, definitive airway need, fetal recovery, anesthesia course, birth timing or route, delivery, newborn state, awareness, disposition and outcomes remain unresolved. Controls do not examine or assess a block, measure, acquire or interpret monitoring, diagnose, stop or operate an infusion, position, give oxygen or ventilation, manage an airway, give fluid, vasopressor or another drug, choose product, dose, concentration, route, rate, target, anesthesia or birth plan, perform delivery or another procedure, assess a newborn, determine disposition, or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `high-neuraxial-block-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
