/** Postpartum infection plus organ dysfunction with open source and mimic boundaries. */
import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['reconcile-obstetrics-sepsis-postpartum-clock-infection-organ-dysfunction-and-whole-person', 'Connect the postpartum clock, infection pattern, organ dysfunction, and whole person.', 'The fixed birth and rupture timing, symptoms, physiology, alertness, urine, uterine, lochia, kidney, lactate, newborn, and whole-person state were connected without learner measurement, examination, sampling, calculation, or diagnosis.'],
  ['recognize-obstetrics-maternal-sepsis-emergency-without-fever-score-source-or-single-value-closure', 'Recognize a maternal-sepsis emergency without fever-, score-, source-, or single-value closure.', 'Suspected infection plus otherwise unexplained organ dysfunction was recognized as an emergency while one screen, value, or presumed source remained insufficient.'],
  ['activate-obstetrics-sepsis-obstetric-critical-care-anesthesia-nursing-pharmacy-microbiology-source-newborn-and-dignity-ownership', 'Bring qualified sepsis, source, newborn, and dignity-centered owners together.', 'Qualified resuscitation, antimicrobial, source-control, organ-support, newborn, pain, privacy, and communication ownership began without learner treatment or disposition selection.'],
  ['review-obstetrics-sepsis-supplied-infectious-noninfectious-culture-lactate-perfusion-and-source-boundary', 'Review supplied infectious, noninfectious, culture, lactate, perfusion, and source evidence.', 'Supplied infection, perfusion, organ, culture, lactate, source, hemorrhage, hypertensive, medication, and thromboembolic boundaries were integrated without learner acquisition, interpretation, diagnosis, or exclusion.'],
  ['record-obstetrics-sepsis-bounded-qualified-immediate-care-source-control-intent-and-strict-later-review', 'Record bounded immediate-care and source-control intent, then review the strict later report.', 'Qualified cultures-without-delay, lactate, antimicrobial, response-guided resuscitation, source-control, and organ-support intent was recorded without learner product, dose, route, volume, target, procedure, delivery, or treatment-effect claim.'],
  ['handoff-obstetrics-sepsis-shock-source-organ-antimicrobial-vte-newborn-survivor-and-outcome-risk', 'Hand off shock, source, organ, antimicrobial, VTE, newborn, survivor, and outcome risk.', 'The handoff preserved shock, repeat perfusion, source control, antimicrobial review, organ support, VTE, dignity, newborn support, survivor needs, disposition, and outcome uncertainty.'],
] as const;

export const MATERNAL_SEPSIS_POSTPARTUM_DETERIORATION: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'maternal-sepsis-postpartum-deterioration', version: '0.1.0', maturity: 'draft', title: 'Maternal sepsis: see organ dysfunction and move together', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 7, difficulty: 'intermediate', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Society for Maternal-Fetal Medicine. Consult Series #67: Maternal sepsis. 2023; reaffirmed 2025; ACOG endorsed.', 'World Health Organization. Statement on maternal sepsis. 2017.'] }, limitations: ['maternal-sepsis-postpartum-infection-organ-and-response-pattern-are-authored', 'maternal-sepsis-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-maternal-sepsis-exam-score-test-drug-fluid-vasopressor-procedure-disposition-or-outcome'] },
  patient: { ageYears: 29, sex: 'female', heightCm: 168, weightKg: 82, asaClass: 4, diagnosis: 'Authored postpartum infection plus organ-dysfunction pattern with open source and mimics', procedure: 'maternal-sepsis recognition, coordinated ownership, reassessment, and handoff practice', comorbidities: ['38 hours after unplanned cesarean birth following 24 hours of ruptured membranes'], medications: ['Postoperative medicines remain supplied history and outside learner control'], allergies: ['No known drug allergies'], fasting: 'Postpartum intake and critical-care planning remain qualified-team work', baseline: { heartRateBpm: 132, meanArterialMmHg: 64, strokeVolumeMl: 52, hemoglobinGPerDl: 10.2, bloodVolumeMl: 4700, coreTemperatureC: 39.1, arterialStiffness: 1, baroreflexGain: 1.2, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Slowed responses but oriented; no authored airway obstruction or respiratory failure' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 500, respiratoryRateBpm: 28, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'maternal-sepsis-presentation', type: 'narrative', target: 'maternal-sepsis-postpartum-deterioration-transition', atTick: 0, severity: 'critical', message: 'A 29-year-old woman is 38 hours after an unplanned cesarean birth following 24 hours of ruptured membranes. Qualified staff report temperature 39.1°C, HR 132/min, BP 88/52 mmHg (MAP 64), RR 28/min, pulse-coherent room-air SpO2 96%, slowed but oriented responses, reduced urine output, uterine tenderness, malodorous lochia, WBC 19.4 × 10^9/L, creatinine 1.4 mg/dL from 0.7, and lactate 4.2 mmol/L. There is no authored major bleeding, severe hypertension, seizure, focal deficit, chest pain, hypoxemia, urticaria, or cardiac arrest.' },
    { id: 'maternal-sepsis-boundary', type: 'narrative', target: 'maternal-sepsis-postpartum-deterioration-transition-boundary', atTick: 0, severity: 'warning', message: 'Recognize suspected infection plus otherwise unexplained organ dysfunction as a maternal-sepsis emergency without requiring fever, one score, one value, microbiology, or source confirmation. Bring obstetric, critical-care, anesthesia, nursing, pharmacy, microbiology, source-control, organ-support, newborn-support and dignity-centered ownership together; review infectious and noninfectious causes, cultures-without-delay, lactate, perfusion, source, hemorrhage, hypertensive, medication and thromboembolic uncertainty; then record bounded qualified immediate-care and source-control intent. After elapsed time, a strict fixed 30-minute qualified-team report supplies HR 122/min, BP 94/58 mmHg (MAP 70), RR 24/min, SpO2 98% on supplied support, temperature 39.0°C, clearer responses, urine output and repeat lactate pending, and source control unresolved. Controls do not examine, score, measure, sample, calculate, diagnose, prescribe, deliver treatment, perform source control, determine disposition, or predict response or outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `maternal-sepsis-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
