import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-obstetrics-maternal-arrest-prepared-resuscitation-obstetric-anesthesia-delivery-newborn-and-dignity-response-now', 'Activate the prepared pregnancy cardiac-arrest response and arrest clock now.', 'Qualified standard resuscitation, pregnancy-specific, obstetric, anesthesia, in-place delivery readiness, newborn, hemorrhage, communication, dignity, family and staff-support ownership was activated immediately.'],
  ['reconcile-obstetrics-maternal-arrest-clock-responsiveness-breathing-pulse-rhythm-pregnancy-and-whole-person', 'Connect the arrest clock, responsiveness, breathing, pulse, rhythm, pregnancy context, and whole person.', 'The supplied arrest facts and pregnancy context were connected without learner pulse check, examination, measurement, monitoring interpretation, or diagnosis.'],
  ['review-obstetrics-maternal-arrest-supplied-pregnancy-modifications-and-airway-priority-boundary', 'Review supplied pregnancy modifications and airway-priority boundaries.', 'Pregnancy-specific resuscitation responsibilities were reviewed without learner compression, uterine-displacement, airway, access, fetal-monitor, rhythm, drug, shock, or procedure action.'],
  ['review-obstetrics-maternal-arrest-reversible-causes-delivery-newborn-and-hemorrhage-readiness-boundary', 'Review open causes plus delivery, newborn, and hemorrhage readiness.', 'Open obstetric and general causes and qualified in-place delivery, newborn, hemorrhage and rescue readiness were reviewed without delaying resuscitation or learner diagnosis, treatment, eligibility, or procedure selection.'],
  ['review-obstetrics-maternal-arrest-fixed-minute-four-active-resuscitation-and-delivery-readiness-report', 'Review the fixed minute-4 active-resuscitation and delivery-readiness report.', 'The authored minute-4 report was reviewed without claiming delivery completion, maternal circulation, newborn condition, cause, treatment effect, disposition, or outcome.'],
  ['handoff-obstetrics-maternal-arrest-active-arrest-cause-procedure-hemorrhage-newborn-family-and-outcome-risk', 'Hand off active arrest, cause, procedure, hemorrhage, newborn, family-support, and outcome risk.', 'The handoff preserved unresolved maternal arrest, cause, procedure, hemorrhage, newborn, family, staff, disposition, prognosis, and outcome risk.'],
] as const;

export const MATERNAL_CARDIAC_ARREST_COORDINATED_RESPONSE: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'maternal-cardiac-arrest-coordinated-response', version: '0.1.0', maturity: 'preview', title: 'Maternal cardiac arrest: coordinated care', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 7, difficulty: 'advanced', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['American Heart Association. 2025 Guidelines for CPR and ECC: Adult and Pediatric Special Circumstances of Resuscitation, section 19.3.', 'American Heart Association. Cardiac Arrest in Pregnancy Algorithm. 2025.', 'Alliance for Innovation on Maternal Health. Cardiac Conditions in Obstetric Care Patient Safety Bundle. 2025.'] }, limitations: ['maternal-arrest-clock-pulse-rhythm-pregnancy-delivery-and-minute-four-reports-are-authored', 'maternal-arrest-controls-activate-reconcile-prepare-review-reassess-and-handoff-only', 'no-live-maternal-arrest-cpr-airway-drug-monitor-delivery-procedure-disposition-or-outcome'] },
  patient: { ageYears: 32, sex: 'female', heightCm: 167, weightKg: 82, asaClass: 5, diagnosis: 'Witnessed maternal cardiac arrest with supplied nonshockable rhythm and cause unresolved', procedure: 'maternal cardiac arrest recognition, pregnancy-specific coordination, minute-4 reassessment, and active-risk handoff practice', comorbidities: ['32 weeks 4 days pregnant; no known structural heart disease'], medications: ['No IV magnesium infusion is running'], allergies: ['No known drug allergies'], fasting: 'Emergency airway, aspiration, and delivery planning remain qualified-team work', baseline: { heartRateBpm: 48, meanArterialMmHg: 40, strokeVolumeMl: 25, hemoglobinGPerDl: 11.4, bloodVolumeMl: 5400, coreTemperatureC: 36.8, arterialStiffness: 1, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.3, difficultMaskVentilation: false, assessment: 'Unresponsive without normal breathing; qualified airway and ventilation care is already part of the active arrest response' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg'], ventilator: { mode: 'manual', fio2: 1, tidalVolumeMl: 500, respiratoryRateBpm: 10, freshGasFlowLPerMin: 10, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'maternal-arrest-presentation', type: 'narrative', target: 'maternal-cardiac-arrest-coordinated-response-transition', atTick: 0, severity: 'critical', message: 'A 32-year-old at 32 weeks 4 days became suddenly unresponsive on the obstetric unit 30 seconds before this learner surface opened. Qualified staff report no normal breathing and no central pulse on a simultaneous 10-second check; the monitor shows organized narrow-complex electrical activity at 48/min without mechanical circulation. Her fundal height is reported above the umbilicus. One qualified team member has begun standard chest compressions on a firm surface while calling for help. No return of spontaneous circulation is reported. A pre-arrest fetal report is no longer displayed. No preceding major external hemorrhage, seizure, fever, severe hypertension, rash, anesthetic exposure, trauma, known cardiac disease, recent medication or transfusion, or confirmed cause is authored. No IV magnesium infusion is running.' },
    { id: 'maternal-arrest-boundary', type: 'narrative', target: 'maternal-cardiac-arrest-coordinated-response-transition-boundary', atTick: 0, severity: 'warning', message: 'Activate the prepared pregnancy cardiac-arrest team and arrest clock now. Qualified teams own high-quality minimally interrupted standard resuscitation, manual left lateral uterine displacement, early airway management, upper-body access, rhythm-appropriate care, stopping fetal monitoring, reversible-cause work, and preparation at arrest recognition for resuscitative delivery at the arrest location if circulation does not return, with the goal of delivery by minute 5. Obstetric, anesthesia, resuscitation, nursing, pharmacy, surgical, blood-bank, neonatal, communication, dignity, family and staff-support work runs in parallel. A fixed report authored at arrest minute 4 supplies persistent organized electrical activity at 42/min without a central pulse, blood pressure, pleth waveform or return of spontaneous circulation. Qualified resuscitation, uterine displacement, airway and ventilation care continue, and the qualified obstetric operator reports that resuscitative delivery is beginning at the arrest location while advanced life support continues. The lesson stops before delivery completion. Maternal circulation, fetal or newborn condition, cause, treatment effect, hemorrhage, procedures, disposition, prognosis and outcomes remain unresolved. Controls do not assess pulse, examine, measure, interpret monitoring, perform compressions or uterine displacement, select rhythm care, oxygen, ventilation, airway, access, fluid, blood, drug, dose, shock, ECMO, delivery or another procedure, operate fetal monitoring, transfer, terminate resuscitation, determine disposition, or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `maternal-arrest-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
