import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-obstetrics-oxytocin-tachysystole-qualified-obstetric-fetal-and-support-response', 'Activate the qualified obstetric, fetal-surveillance, and support response.', 'Senior obstetric, midwifery, anesthesia, newborn, communication, dignity, and support ownership was activated first.'],
  ['reconcile-obstetrics-oxytocin-tachysystole-infusion-contraction-fetal-maternal-and-whole-person-context', 'Connect oxytocin, contractions, fetal trajectory, maternal state, and the whole person.', 'The supplied infusion, uterine-activity, fetal-heart, labour, maternal, preference, and support facts were connected without learner examination or monitoring interpretation.'],
  ['recognize-obstetrics-oxytocin-tachysystole-with-fetal-heart-deterioration-without-single-trace-closure', 'Recognize tachysystole with fetal-heart deterioration without single-trace closure.', 'The whole supplied trajectory triggered action while artifact, maternal and fetal alternatives and evolving risk remained open.'],
  ['review-obstetrics-oxytocin-tachysystole-qualified-source-stop-position-cause-and-birth-readiness', 'Review qualified source-stop, position, cause, surveillance, and birth readiness.', 'Qualified oxytocin stop, non-supine position, cause correction, escalation and birth readiness were reviewed without routine oxygen, reflex fluid, learner treatment, or a universal sequence.'],
  ['review-obstetrics-oxytocin-tachysystole-fixed-six-minute-qualified-recovery-report', 'Review the fixed 6-minute qualified-team report.', 'The authored partial recovery was reviewed without claiming learner treatment, durable fetal safety, restart eligibility, birth, or outcome.'],
  ['handoff-obstetrics-oxytocin-tachysystole-recurrence-fetal-birth-medication-maternal-and-outcome-risk', 'Hand off recurrence, fetal, birth, medication, maternal, and outcome risk.', 'The handoff preserved recurrence, hypoxia, surveillance, oxytocin, alternative-cause, birth, newborn, maternal, and outcome uncertainty.'],
] as const;

export const OXYTOCIN_ASSOCIATED_UTERINE_TACHYSYSTOLE: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'oxytocin-associated-uterine-tachysystole', version: '0.1.0', maturity: 'preview', title: 'Oxytocin-associated tachysystole: reduce the load', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['American College of Obstetricians and Gynecologists. First and Second Stage Labor Management. Clinical Practice Guideline No. 8. Obstet Gynecol. 2024;143:144-162.', 'National Institute for Health and Care Excellence. Intrapartum care. NICE guideline NG235. Updated 2025.', 'National Institute for Health and Care Excellence. Fetal monitoring in labour. NICE guideline NG229. Updated 2026.'] }, limitations: ['oxytocin-tachysystole-infusion-contraction-fetal-maternal-and-qualified-course-reports-are-authored', 'oxytocin-tachysystole-controls-activate-reconcile-review-reassess-and-handoff-only', 'no-live-oxytocin-tachysystole-exam-monitor-infusion-position-oxygen-fluid-drug-birth-procedure-or-outcome'] },
  patient: { ageYears: 27, sex: 'female', heightCm: 167, weightKg: 79, asaClass: 2, diagnosis: 'Supplied oxytocin-associated uterine-tachysystole pattern with fetal-heart deterioration during term labour', procedure: 'threshold-aware recognition, qualified corrective-response coordination, reassessment, and active-risk handoff practice', comorbidities: ['40 weeks 1 day pregnant in first labour; oxytocin augmentation follows a qualified diagnosis of delayed active labour'], medications: ['Oxytocin infusion is running under qualified staff control; product, concentration, line, dose, rate, and increment history remain outside learner control'], allergies: ['No known drug allergies'], fasting: 'Labour intake and possible anesthesia planning remain qualified-team work', baseline: { heartRateBpm: 92, meanArterialMmHg: 86, strokeVolumeMl: 72, hemoglobinGPerDl: 11.5, bloodVolumeMl: 5000, coreTemperatureC: 36.9, arterialStiffness: 1, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Awake, breathing comfortably, and frightened by the alarm; no maternal airway concern is supplied' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 500, respiratoryRateBpm: 18, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'oxytocin-tachysystole-presentation', type: 'narrative', target: 'oxytocin-associated-uterine-tachysystole-transition', atTick: 0, severity: 'critical', message: 'A 27-year-old at 40 weeks 1 day is in first labour with oxytocin augmentation after a qualified diagnosis of delayed active labour. Qualified staff report 6 contractions in each 10-minute window averaged over the last 30 minutes, lasting 70 to 90 seconds, after the latest infusion increase 20 minutes ago. The supplied fetal-heart report changed from a 140/min baseline with moderate variability and no decelerations to a 155/min baseline with minimal variability and recurrent late decelerations to 95/min. The mother is awake and frightened, HR 92/min, BP 122/68 mmHg (MAP 86), RR 18/min, room-air SpO2 98%, and temperature 36.9°C. No hypotension, fever, fresh bleeding, atypical constant pain, meconium, or signal-loss concern is supplied. Oxytocin is still running under qualified staff control; product, concentration, line, dose, rate, and increment history remain outside learner control.' },
    { id: 'oxytocin-tachysystole-boundary', type: 'narrative', target: 'oxytocin-associated-uterine-tachysystole-transition-boundary', atTick: 0, severity: 'warning', message: 'Activate senior obstetric, midwifery or nursing, anesthesia, newborn, pharmacy, theatre, leadership, timekeeping, documentation, communication, dignity, family, and staff-support ownership. Connect the oxytocin and change clock, contraction frequency and duration, fetal baseline, variability and deceleration trajectory, maternal observations, labour progress, position, bleeding, pain, temperature, medications, preferences, support, and whole person. More than 5 contractions in 10 minutes averaged over 30 minutes is tachysystole; always connect it with the associated fetal-heart pattern and whole clinical picture. Qualified staff stop oxytocin, support a non-supine position, verify maternal and fetal signals, review reversible maternal, uterine, placental, cord, medication and fetal causes, maintain continuous surveillance, and prepare tocolysis or expedited birth if indicated. Do not add routine maternal facial oxygen when she is not hypoxemic, or reflex fluid without hypotension or sepsis. A fixed qualified-team report 6 minutes after activation supplies oxytocin stopped, 4 contractions in the latest 10 minutes, fetal baseline 145/min with moderate variability and no recurrent late deceleration for 4 minutes, unchanged maternal physiology, and continued one-to-one surveillance. This early recovery does not determine durable fetal safety, cause, oxytocin restart, labour or birth plan, newborn state, disposition, or outcome. Controls do not examine, palpate, measure, acquire or interpret monitoring or tests, diagnose, operate an infusion, position, give oxygen, fluid, tocolytic or another drug or dose, perform fetal stimulation, amnioinfusion, anesthesia, surgery, delivery, newborn care, another procedure, determine restart or birth strategy, determine disposition, or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `oxytocin-tachysystole-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
