/** Postpartum severe-hypertension and multi-organ warning pattern with open causes and outcomes. */
import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['reconcile-obstetrics-postpartum-preeclampsia-clock-symptoms-pressure-organs-newborn-and-whole-person', 'Connect the postpartum clock, symptoms, pressure, organs, newborn context, and whole person.', 'The fixed birth clock, patient-reported symptoms, qualified pressures, physiology, laboratory report, newborn context, support needs, and whole person were connected without learner interviewing, measurement, examination, calculation, interpretation, or diagnosis.'],
  ['recognize-obstetrics-persistent-severe-postpartum-hypertension-and-supplied-preeclampsia-pattern-without-waiting-for-proteinuria', 'Recognize persistent severe postpartum hypertension and the supplied presumptive preeclampsia pattern without waiting for proteinuria.', 'Two properly obtained severe-range readings established the treatment emergency; proteinuria was not required, and no single finding established every cause.'],
  ['activate-obstetrics-postpartum-severe-hypertension-protocol-qualified-obstetric-response-and-patient-centered-support-now', 'Activate the severe-hypertension protocol, qualified obstetric response, and patient-centered support now.', 'Immediate protocol-based pressure response and seizure-prevention assessment began while organ and alternative-cause evaluation continued in parallel, without learner product, dose, route, target, treatment, separation, or disposition selection.'],
  ['review-obstetrics-postpartum-preeclampsia-supplied-neurologic-pulmonary-hematologic-renal-hepatic-medication-and-competing-cause-boundary', 'Review supplied neurologic, pulmonary, hematologic, renal, hepatic, medication, and competing-cause evidence.', 'Supplied pressure-quality, symptom, platelet, liver, kidney, urine, lung, neurologic, medication, hemorrhage, infection, thrombotic, vascular and other competing-cause boundaries were integrated without learner acquisition, interpretation, diagnosis, exclusion, or eligibility determination.'],
  ['review-obstetrics-postpartum-preeclampsia-fixed-later-pressure-symptom-organ-and-support-report', 'Review the fixed later pressure, symptom, organ, and support report.', 'The report authored as 30 minutes after qualified protocol activation was reviewed without learner product, dose, rate, target, route, access, test, procedure, disposition, or treatment-effect claim.'],
  ['handoff-obstetrics-postpartum-preeclampsia-recurrent-pressure-seizure-stroke-pulmonary-hellp-renal-newborn-follow-up-and-outcome-risk', 'Hand off recurrent pressure, seizure, stroke, pulmonary, HELLP, renal, newborn, follow-up, and outcome risk.', 'The handoff preserved neurologic, seizure, recurrent-pressure, pulmonary, hematologic, hepatic, renal, medication, newborn, feeding, trauma-informed support, prompt follow-up, longer-term cardiovascular and outcome uncertainty.'],
] as const;

export const POSTPARTUM_SEVERE_PREECLAMPSIA_WARNING_SIGNS: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'postpartum-severe-preeclampsia-warning-signs', version: '0.1.0', maturity: 'preview', title: 'Postpartum severe preeclampsia: listen, connect, escalate', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 7, difficulty: 'advanced', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['American College of Obstetricians and Gynecologists. Practice Bulletin No. 222: Gestational Hypertension and Preeclampsia. 2020; reaffirmed 2026.', 'Alliance for Innovation on Maternal Health. Severe Hypertension in Pregnancy Patient Safety Bundle. Revised 2022.', 'Society for Maternal-Fetal Medicine. Quality metric for timely postpartum follow-up after severe hypertension. 2022; reaffirmed 2025.'] }, limitations: ['postpartum-severe-preeclampsia-clock-symptom-pressure-organ-and-response-pattern-are-authored', 'postpartum-severe-preeclampsia-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-postpartum-preeclampsia-pressure-exam-test-drug-magnesium-airway-disposition-or-outcome'] },
  patient: { ageYears: 32, sex: 'female', heightCm: 165, weightKg: 76, asaClass: 4, diagnosis: 'Persistent severe postpartum hypertension with a supplied presumptive preeclampsia-with-severe-features pattern and open causes', procedure: 'postpartum severe preeclampsia recognition, coordinated ownership, reassessment, and handoff practice', comorbidities: ['Six days after term vaginal birth; no authored antepartum hypertension'], medications: ['Postpartum medicines remain supplied history and outside learner control'], allergies: ['No known drug allergies'], fasting: 'Postpartum intake and emergency planning remain qualified-team work', baseline: { heartRateBpm: 96, meanArterialMmHg: 133, strokeVolumeMl: 70, hemoglobinGPerDl: 11.3, bloodVolumeMl: 4650, coreTemperatureC: 36.7, arterialStiffness: 1, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Alert and conversant; no authored seizure, airway obstruction, or respiratory failure' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 480, respiratoryRateBpm: 20, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'postpartum-severe-preeclampsia-presentation', type: 'narrative', target: 'postpartum-severe-preeclampsia-warning-signs-transition', atTick: 0, severity: 'critical', message: 'A 32-year-old is 6 days after a term vaginal birth and had no authored antepartum hypertension. For 4 hours she has reported a severe headache, flashing visual spots, and severe persistent right upper-quadrant or epigastric pain not accounted for by the supplied history. Qualified staff report correctly obtained BP 178/114 and 174/112 mmHg 15 minutes apart, HR 96/min, RR 20/min, pulse-coherent room-air SpO2 97%, T 36.7°C, platelets 88 × 10^9/L, creatinine 1.2 mg/dL from 0.7, and AST 96 U/L and ALT 88 U/L, both more than twice the supplied local upper limit of normal. Urine protein-to-creatinine ratio and hemolysis evaluation are pending. She is alert and conversant with her newborn and chosen support person nearby. There is no authored seizure, focal deficit, chest pain, dyspnea, hypoxemia, fever, major bleeding, or cardiac arrest.' },
    { id: 'postpartum-severe-preeclampsia-boundary', type: 'narrative', target: 'postpartum-severe-preeclampsia-warning-signs-transition-boundary', atTick: 0, severity: 'warning', message: 'Connect the postpartum clock, patient-reported symptoms, qualified pressures, organ evidence, newborn context, and whole person; recognize the two persistent severe-range pressures as an immediate treatment emergency while integrating the supplied presumptive preeclampsia-with-severe-features pattern without waiting for urine protein or closing every cause; activate the severe-hypertension protocol and qualified obstetric response now, with pressure treatment as soon as possible and within 60 minutes of the first severe reading while seizure-prevention assessment, measurement-quality, brain, vision, lung, platelet, liver, kidney, urine, medicine, hemorrhage, infection, thrombotic, vascular and other cause evaluation proceeds in parallel. A fixed later qualified-team report, authored as 30 minutes after activation, supplies BP 152/98 mmHg, HR 92/min, RR 18/min, room-air SpO2 98%, T 36.7°C, improved but persistent headache and visual spots, no reported seizure, repeat laboratories pending, and neurologic, pulmonary, hematologic, renal, hepatic and longer-term risk unresolved. This single pressure is no longer severe-range but remains hypertensive; it does not establish durable control, a target, or treatment effect. Controls do not interview, measure, examine, calculate, acquire or interpret tests, diagnose, prescribe, deliver treatment, manage a seizure or airway, determine separation, feeding, transfer, disposition or follow-up, or predict response or outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `postpartum-severe-preeclampsia-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
