/** Early postpartum hemorrhage with a supplied uterine-atony pattern and open competing causes. */
import type { Scenario } from '@anesthesia/scenarios/types';

export const POSTPARTUM_HEMORRHAGE_UTERINE_ATONY: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'postpartum-hemorrhage-uterine-atony', version: '0.1.0', maturity: 'preview',
    title: 'Postpartum hemorrhage: act early and keep every cause open', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 7, difficulty: 'intermediate',
    objectives: [
      { id: 'reconcile-obstetrics-atony-hemorrhage-birth-clock-measured-loss-physiology-tone-and-whole-person', statement: 'Reconcile the birth clock, measured loss, physiology, uterine tone, and whole person.', measure: 'The fixed postpartum timing, 650 mL-and-rising measured loss, bleeding, symptoms, perfusion, uterine tone, and whole-person state were connected without learner measurement, examination, calculation, or diagnosis.' },
      { id: 'recognize-obstetrics-atony-postpartum-hemorrhage-and-atony-pattern-without-threshold-tone-or-single-cause-closure', statement: 'Recognize postpartum hemorrhage and an atony pattern without threshold-, tone-, or single-cause closure.', measure: 'The early actionable hemorrhage and supplied atony pattern were recognized while trauma, tissue, thrombin, rupture, inversion, and concealed bleeding remained open.' },
      { id: 'activate-obstetrics-atony-hemorrhage-obstetric-anesthesia-nursing-blood-bank-operating-room-and-dignity-ownership', statement: 'Activate obstetric, anesthesia, nursing, blood-bank, operating-room, and dignity-centered ownership.', measure: 'Qualified hemorrhage, resuscitation, blood-bank, escalation, newborn-support, privacy, pain, and communication ownership began together without learner treatment or disposition selection.' },
      { id: 'review-obstetrics-atony-supplied-tone-placenta-tract-coagulation-perfusion-and-competing-cause-boundary', statement: 'Review supplied uterine, placental, genital-tract, coagulation, perfusion, and competing-cause evidence.', measure: 'Supplied tone, gross placental report, symptoms, perfusion, laboratory boundaries, and the still-open causes were integrated without learner examination, testing, interpretation, diagnosis, or exclusion.' },
      { id: 'record-obstetrics-atony-bounded-qualified-motive-bundle-escalation-intent-and-strict-later-review', statement: 'Record bounded qualified MOTIVE-bundle and escalation intent, then review the strict later report.', measure: 'Qualified massage, oxytocic, tranexamic-acid, fluid, examination, and escalation intent was recorded as a bundle without a learner product, dose, route, rate, procedure, delivery, or treatment-effect claim; the fixed later report was reviewed.' },
      { id: 'handoff-obstetrics-atony-recurrent-bleeding-shock-coagulopathy-blood-procedure-newborn-and-outcome-risk', statement: 'Hand off recurrent bleeding, shock, coagulopathy, blood, procedure, newborn, and outcome risk.', measure: 'The handoff preserved cumulative loss, recurrent bleeding, shock, coagulopathy, blood-bank, operative escalation, pain, privacy, feeding/newborn support, disposition, fertility, and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['World Health Organization, FIGO, and ICM. Consolidated guidelines for the prevention, diagnosis and treatment of postpartum haemorrhage. 2025.', 'American College of Obstetricians and Gynecologists. Practice Bulletin No. 183: Postpartum Hemorrhage. 2017; reaffirmed 2024.'] },
    limitations: ['obstetric-atony-birth-loss-tone-and-response-pattern-are-authored', 'obstetric-atony-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-obstetric-atony-measurement-exam-drug-fluid-blood-procedure-disposition-or-outcome'],
  },
  patient: { ageYears: 31, sex: 'female', heightCm: 165, weightKg: 76, asaClass: 4, diagnosis: 'Authored early postpartum hemorrhage with a uterine-atony pattern and open competing causes', procedure: 'early hemorrhage recognition, bundled ownership, reassessment, and handoff practice', comorbidities: ['Eight minutes after an uncomplicated term vaginal birth'], medications: ['Supplied prophylactic uterotonic before the learner surface; product and dose are outside this lab'], allergies: ['No known drug allergies'], fasting: 'Postpartum intake and anesthesia planning remain qualified-team work', baseline: { heartRateBpm: 118, meanArterialMmHg: 70, strokeVolumeMl: 55, hemoglobinGPerDl: 10.8, bloodVolumeMl: 4_600, coreTemperatureC: 36.7, arterialStiffness: 1, baroreflexGain: 1.2, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Conversant, dizzy and pale; no authored airway obstruction or respiratory failure' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 500, respiratoryRateBpm: 24, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'obstetric-atony-presentation', type: 'narrative', target: 'postpartum-hemorrhage-uterine-atony-transition', atTick: 0, severity: 'critical', message: 'A 31-year-old woman is 8 minutes after an uncomplicated term vaginal birth. Qualified staff report cumulative measured blood loss 650 mL and rising, ongoing active vaginal bleeding, a boggy enlarged uterus, HR 118/min, BP 94/58 mmHg (MAP 70), RR 24/min, pulse-coherent room-air SpO2 98%, temperature 36.7°C, pallor, dizziness, and preserved conversation. The placenta is reported delivered and grossly complete. There is no authored seizure, severe hypertension, chest pain, hypoxemia, focal deficit, uterine inversion, visible major genital trauma, or cardiac arrest.' },
    { id: 'obstetric-atony-boundary', type: 'narrative', target: 'postpartum-hemorrhage-uterine-atony-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile birth timing, objective loss, bleeding, symptoms, perfusion, uterine tone and whole person; recognize actionable postpartum hemorrhage plus a supplied atony pattern without waiting for 1,000 mL or closing trauma, tissue, thrombin, rupture, inversion or concealed bleeding; activate obstetric hemorrhage, anesthesia, nursing, monitoring, blood-bank, operating-room, newborn-support and dignity-centered ownership; then review supplied tone, gross placental report, genital-tract and coagulation uncertainty, hypoperfusion, laboratory and competing-cause boundaries. The learner may record only a bounded qualified MOTIVE-bundle and escalation intent. No product, dose, formula, threshold, rate, route, access, massage technique, examination, fluid, blood component, uterotonic, tranexamic acid, tamponade, procedure, surgery, hysterectomy, transport or delivery is exposed. After elapsed simulated time, a strict fixed 10-minute qualified-team report supplies HR 104/min, BP 102/64 mmHg (MAP 77), RR 20/min, SpO2 99% on supplied support, temperature 36.7°C, a firmer uterus, and visibly slower bleeding. Cumulative loss, hemoglobin trajectory, coagulation, concealed bleeding, durable control, treatment effect, transfusion or procedure need, disposition, fertility, recovery, and maternal or newborn outcome remain open. After another elapsed interval, hand off recurrent bleeding, shock, coagulopathy, hypothermia, blood-bank and operative escalation, pain, privacy, communication, feeding and newborn support, disposition and outcome risk. Controls do not measure blood loss; take history; examine; calculate; acquire or interpret monitoring, laboratory, placental, genital-tract, coagulation or imaging evidence; diagnose or exclude; select or deliver a drug, dose, route, fluid, blood component, oxygen, access, device, massage, examination, tamponade, procedure or surgery; determine eligibility, protocol, disposition, prognosis or safety; or predict response, fertility, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'obstetric-atony-trajectory', objectiveId: 'reconcile-obstetrics-atony-hemorrhage-birth-clock-measured-loss-physiology-tone-and-whole-person', question: 'Which postpartum timing, measured-loss, bleeding, symptom, perfusion, uterine-tone, and whole-person findings established the trajectory?' },
    { id: 'obstetric-atony-recognition', objectiveId: 'recognize-obstetrics-atony-postpartum-hemorrhage-and-atony-pattern-without-threshold-tone-or-single-cause-closure', question: 'Why was the hemorrhage actionable now, and why could a boggy uterus not close every competing cause?' },
    { id: 'obstetric-atony-support', objectiveId: 'activate-obstetrics-atony-hemorrhage-obstetric-anesthesia-nursing-blood-bank-operating-room-and-dignity-ownership', question: 'Which clinical, blood-bank, escalation, newborn, privacy, pain, and communication owners needed to begin together?' },
    { id: 'obstetric-atony-evidence', objectiveId: 'review-obstetrics-atony-supplied-tone-placenta-tract-coagulation-perfusion-and-competing-cause-boundary', question: 'How did the supplied tone and placental report narrow work without excluding trauma, tissue, thrombin, or concealed bleeding?' },
    { id: 'obstetric-atony-reassessment', objectiveId: 'record-obstetrics-atony-bounded-qualified-motive-bundle-escalation-intent-and-strict-later-review', question: 'What did the bundled intent and strict later report establish without proving a treatment effect or durable control?' },
    { id: 'obstetric-atony-handoff', objectiveId: 'handoff-obstetrics-atony-recurrent-bleeding-shock-coagulopathy-blood-procedure-newborn-and-outcome-risk', question: 'Which bleeding, shock, coagulopathy, procedural, dignity, newborn, fertility, and outcome risks stayed open?' },
  ] },
};
