import type { Scenario } from '@anesthesia/scenarios/types';

const objectives = [
  ['activate-obstetrics-afe-coordinated-obstetric-anesthesia-critical-care-cardiopulmonary-hemorrhage-newborn-and-dignity-response', 'Activate coordinated qualified maternal, hemorrhage, newborn, communication, and dignity-centered response.', 'Qualified obstetric, anesthesia, critical-care, oxygenation and ventilation, hemodynamic, cardiopulmonary, nursing, pharmacy, coagulation and hemorrhage, blood-bank, operating-room, arrest-ready, newborn, communication, and support ownership began immediately without learner treatment selection or delivery.'],
  ['reconcile-obstetrics-afe-birth-clock-symptom-order-cardiorespiratory-state-bleeding-coagulation-newborn-and-whole-person', 'Connect the birth clock, symptom order, cardiorespiratory state, bleeding, coagulation, newborn context, and whole person.', 'The supplied birth timing, abrupt breathing and circulation change, alertness, bleeding, coagulation, newborn, support, and whole-person trajectory was connected without learner examination, measurement, calculation, interpretation, or diagnosis.'],
  ['recognize-obstetrics-afe-rapid-maternal-collapse-and-coagulopathy-pattern-without-diagnostic-closure', 'Recognize a rapid maternal-collapse-and-coagulopathy pattern compatible with suspected amniotic fluid embolism without diagnostic closure.', 'The supplied peripartum cardiorespiratory collapse preceding diffuse bleeding and coagulopathy triggered an emergency response while AFE and dangerous alternatives remained open.'],
  ['review-obstetrics-afe-supplied-cardiac-pulmonary-hemorrhage-coagulation-uterine-anesthetic-thrombotic-infectious-allergic-and-competing-cause-boundary', 'Review supplied cardiac, pulmonary, hemorrhage, coagulation, uterine, anesthetic, thrombotic, infectious, allergic, and competing-cause evidence.', 'Supplied and open evidence stayed coupled without learner acquisition, interpretation, diagnosis, exclusion, treatment, or eligibility determination.'],
  ['review-obstetrics-afe-fixed-later-breathing-circulation-bleeding-coagulation-and-support-report', 'Review the fixed later breathing, circulation, bleeding, coagulation, and support report.', 'The report authored as 12 minutes after qualified activation was reviewed without a learner treatment, procedure, delivery, disposition, or treatment-effect claim.'],
  ['handoff-obstetrics-afe-hypoxemia-shock-coagulopathy-bleeding-arrest-procedure-newborn-family-support-and-outcome-risk', 'Hand off hypoxemia, shock, coagulopathy, bleeding, arrest, procedure, newborn, family-support, and outcome risk.', 'The handoff preserved unresolved cardiopulmonary, hemorrhage, coagulation, arrest, procedural, maternal, newborn, family, staff-support, and outcome uncertainty.'],
] as const;

export const SUSPECTED_AMNIOTIC_FLUID_EMBOLISM_PATTERN: Scenario = {
  schemaVersion: 1,
  metadata: { id: 'suspected-amniotic-fluid-embolism-pattern', version: '0.1.0', maturity: 'preview', title: 'Suspected amniotic fluid embolism pattern', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 7, difficulty: 'advanced', objectives: objectives.map(([id, statement, measure]) => ({ id, statement, measure })), clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Society for Maternal-Fetal Medicine Patient Safety and Quality Committee. Checklist for initial management of amniotic fluid embolism—Updated 2026. Pregnancy. 2026;2:e70364.', 'Society for Maternal-Fetal Medicine; Pacheco LD, Saade G, Hankins GDV, Clark SL. Amniotic fluid embolism: diagnosis and management. Am J Obstet Gynecol. 2016;215:B16-B24. PMID 26987420.', 'Clark SL, Romero R, Dildy GA, et al. Proposed diagnostic criteria for the case definition of amniotic fluid embolism in research studies. Am J Obstet Gynecol. 2016;215:408-412. PMID 27372270.', 'American Heart Association. 2025 Guidelines for CPR and ECC: Adult and Pediatric Special Circumstances of Resuscitation, section 19.4.'] }, limitations: ['afe-birth-cardiorespiratory-coagulopathy-and-later-reports-are-authored', 'afe-controls-reconcile-recognize-activate-review-reassess-and-handoff-only', 'no-live-afe-exam-test-diagnosis-treatment-airway-blood-arrest-delivery-procedure-disposition-or-outcome'] },
  patient: { ageYears: 32, sex: 'female', heightCm: 165, weightKg: 74, asaClass: 5, diagnosis: 'Supplied rapid maternal cardiorespiratory-collapse-and-coagulopathy pattern with suspected amniotic fluid embolism and dangerous alternatives open', procedure: 'suspected amniotic fluid embolism pattern recognition, coordinated ownership, reassessment, and active-risk handoff practice', comorbidities: ['Twelve minutes after term birth and placental delivery'], medications: ['No learner-delivered medication or blood product'], allergies: ['No known drug allergies; anaphylaxis remains an open alternative'], fasting: 'Emergency aspiration, airway, and support planning remain qualified-team work', baseline: { heartRateBpm: 132, meanArterialMmHg: 53, strokeVolumeMl: 40, hemoglobinGPerDl: 10.6, bloodVolumeMl: 4500, coreTemperatureC: 36.8, arterialStiffness: 1, baroreflexGain: 1, fixedStrokeVolume: true }, airway: { difficulty: 0.25, difficultMaskVentilation: false, assessment: 'One-word responses with spontaneous breathing; airway and respiratory support are supplied qualified-team work' }, respiratory: { profile: 'term-pregnancy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 500, respiratoryRateBpm: 34, freshGasFlowLPerMin: 10, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'afe-presentation', type: 'narrative', target: 'suspected-amniotic-fluid-embolism-pattern-transition', atTick: 0, severity: 'critical', message: 'A 32-year-old is 12 minutes after a term birth and placental delivery. Eight minutes ago she abruptly reported difficulty breathing, became cyanotic, confused and profoundly hypotensive before major visible bleeding. At event onset a qualified report supplied a central pulse, HR 132/min, BP 74/42 mmHg, RR 34/min, pulse-coherent room-air SpO2 78%, T 36.8°C, one-word responses, cool mottled perfusion, a firm midline uterus, and 180 mL cumulative measured blood loss. A sample drawn when loss was 240 mL supplies platelets 68 × 10^9/L from 221, fibrinogen 105 mg/dL from 430, PT 18.6 seconds, INR 1.7, aPTT 52 seconds, hemoglobin 10.6 g/dL from 12.1, and lactate 5.4 mmol/L. The newborn is with a qualified neonatal team. No cardiac arrest, seizure, fever, rash, angioedema, dominant wheeze, focal neurologic deficit, antecedent abdominal or back pain, or focal surgical bleeding source is authored.' },
    { id: 'afe-boundary', type: 'narrative', target: 'suspected-amniotic-fluid-embolism-pattern-transition-boundary', atTick: 0, severity: 'warning', message: 'Connect the birth clock and the order of abrupt breathing, circulation, alertness, bleeding, coagulation, newborn and whole-person change; recognize a rapid maternal-collapse-and-coagulopathy emergency compatible with suspected amniotic fluid embolism without diagnostic closure; activate qualified obstetric, anesthesia, nursing, critical-care, respiratory, cardiology, pharmacy, blood-bank, laboratory, operating-room, newborn, communication, dignity and family-support ownership now. Pulmonary thromboembolism, air embolism, myocardial or other cardiac disease, anesthetic complication, anaphylaxis, sepsis, hemorrhage and other causes remain open in parallel. The Clark criteria are for research reporting, not a learner-applied bedside score. A fixed qualified-team report, authored as 12 minutes after activation, supplies a central pulse, HR 124/min, BP 86/50 mmHg, RR 28/min, pulse-coherent SpO2 94% on unspecified qualified-team support and T 36.7°C. She opens her eyes to voice but does not reliably follow commands; perfusion remains cool and mottled. Cumulative vaginal loss is 850 mL and rising, the uterus remains firm, vascular-access sites ooze, and repeat platelets are 44 × 10^9/L, fibrinogen 72 mg/dL, PT 23.4 seconds, INR 2.2, aPTT 68 seconds, hemoglobin 8.8 g/dL and lactate 6.0 mmol/L. This is persistent shock, respiratory compromise and progressive coagulopathy and hemorrhage, not recovery. Cardiopulmonary cause, procedures, durable control and outcomes remain open. This does not establish treatment effect, respiratory or hemodynamic recovery, bleeding or coagulopathy control, procedure completion, disposition, or maternal or newborn outcome. Controls do not examine, measure, interpret, diagnose, prescribe, oxygenate, ventilate, establish access, transfuse, resuscitate, deliver treatment, perform CPR, select delivery or a procedure, determine disposition, or predict outcome.' },
  ],
  debrief: { rubric: objectives.map(([id, statement], index) => ({ id: `afe-${index + 1}`, objectiveId: id, question: `${statement} What remained outside learner control?` })) },
};
