import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import { PrerenderedBody } from '@routes/Prerendered';
import { ActionCockpit, crisisResponseAvailability, type ActionCockpitProps } from '@anesthesia/ui/ActionCockpit';
import { UNITED_STATES } from '@anesthesia/region/profiles';
import { MATERNAL_TO_NEONATAL_RESUSCITATION_HANDOFF as SCENARIO } from '../../src/modules/obstetrics/scenarios/maternal-to-neonatal-resuscitation-handoff';
const markup = (assessment: NonNullable<ActionCockpitProps['resuscitation']['obstetricsMaternalNeonatalHandoffAssessment']>) => renderToStaticMarkup(createElement(ActionCockpit, { scenario: SCENARIO, region: UNITED_STATES, infusions: [], hypnoticLine: { connected: true, inspected: false }, resuscitation: { epinephrineEffectFraction: 0, epinephrineTotalMicrograms: 0, lastEpinephrineTick: null, crystalloidTotalMl: 0, dantroleneTotalMg: 0, dantroleneEffectFraction: 0, lastDantroleneTick: null, activeCooling: false, obstetricsMaternalNeonatalHandoffAssessment: assessment }, lastExposure: null, syringeRemaining: {}, ventilator: { mode: 'manual', tidalVolumeMl: 480, respiratoryRateBpm: 12, fio2: 0.21, peep: 0, delivering: false, sevofluranePercent: 0, freshGasFlowLPerMin: 2 }, intubated: false, airwayAttempts: 0, lastGrade: null, jawThrustCpapSecondsRemaining: 0, airwayDevice: 'facemask', supraglotticInsertionSecondsRemaining: 0, helpRequestedAtTick: null, muscleRigidityFraction: 0, onBolus: () => {}, onInfusion: () => {}, onHypnoticLine: () => {}, onFluid: () => {}, onVentilator: () => {}, onLaryngoscopy: () => {}, onAirwayManeuver: () => {}, onEpinephrine: () => {}, onDantrolene: () => {}, onCallForHelp: () => {}, onAirwayDevice: () => {}, onActiveCooling: () => {}, onDrugCard: () => {}, onObstetricsMaternalNeonatalHandoffResponse: () => {} } satisfies ActionCockpitProps));
describe('Obstetrics maternal-to-neonatal resuscitation-handoff experience', () => {
  it('is discoverable at its exact calm route', () => { const index = renderToStaticMarkup(createElement(PrerenderedBody, { path: '/obstetrics' })); expect(index).toContain('href="/obstetrics/scenario/maternal-to-neonatal-resuscitation-handoff"'); expect(index).toContain('Maternal-to-neonatal resuscitation handoff'); const route = renderToStaticMarkup(createElement(PrerenderedBody, { path: '/obstetrics/scenario/maternal-to-neonatal-resuscitation-handoff' })); expect(route).toContain('<h1>Maternal-to-neonatal resuscitation handoff</h1>'); });
  it('fails closed and exposes one calm cognitive action at a time', () => { expect(crisisResponseAvailability(SCENARIO).hasObstetricsMaternalNeonatalHandoffResponse).toBe(true); expect(crisisResponseAvailability({ ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }).hasObstetricsMaternalNeonatalHandoffResponse).toBe(false); const states = [{ supportAtTick: null, contextAtTick: null, safetyAtTick: null, transferAtTick: null, reassessmentAtTick: null, handoffAtTick: null }, { supportAtTick: 1, contextAtTick: null, safetyAtTick: null, transferAtTick: null, reassessmentAtTick: null, handoffAtTick: null }, { supportAtTick: 1, contextAtTick: 1, safetyAtTick: null, transferAtTick: null, reassessmentAtTick: null, handoffAtTick: null }, { supportAtTick: 1, contextAtTick: 1, safetyAtTick: 1, transferAtTick: null, reassessmentAtTick: null, handoffAtTick: null }, { supportAtTick: 1, contextAtTick: 1, safetyAtTick: 1, transferAtTick: 1, reassessmentAtTick: null, handoffAtTick: null }, { supportAtTick: 1, contextAtTick: 1, safetyAtTick: 1, transferAtTick: 1, reassessmentAtTick: 2, handoffAtTick: null }, { supportAtTick: 1, contextAtTick: 1, safetyAtTick: 1, transferAtTick: 1, reassessmentAtTick: 2, handoffAtTick: 3 }]; expect(states.map((state) => (markup(state).match(/<button/g) ?? []).length)).toEqual([1,1,1,1,1,1,0]); expect(markup(states[0]!)).toContain('Two patients. Two teams. One clear transfer.'); const later = markup(states[4]!); expect(later).toContain('A rising heart rate is encouraging, not the end of the story.'); expect(later).toContain('Review the fixed 5-minute report'); expect((later.match(/role="status"/g) ?? [])).toHaveLength(1); for (const html of states.map(markup)) { const buttons = [...html.matchAll(/<button[^>]*>(.*?)<\/button>/g)].map((match) => match[1]); expect(buttons.join(' ')).not.toMatch(/examin|monitor|resuscitat|oxygen|ventilat|airway|compress|drug|dose|surgery|birth|deliver|transport|cool|disposition/iu); } });
});
