import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { CHOLINERGIC_PESTICIDE_RESPIRATORY_FAILURE } from './scenarios/cholinergic-pesticide-respiratory-failure';
import { CHOLINERGIC_FIXTURES } from './cholinergic-pesticide-respiratory-failure-fixtures';
import { CHOLINERGIC_TUTOR_VERSION } from './tutor/cholinergic-pesticide-respiratory-failure-guidance';
import { CHOLINERGIC_DEMONSTRATION_VERSION } from './demo/cholinergic-pesticide-respiratory-failure-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * `observable-objectives` is deliberately not answered here. This scenario
 * declares six objectives against a cap of five, which is a content-design
 * decision affecting scenarios across several modules rather than something
 * this file may settle on its own. The shared audit keeps naming it.
 */
export function cholinergicCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'toxicology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== CHOLINERGIC_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || CHOLINERGIC_FIXTURES.contentVersion !== '0.1.0'
    || CHOLINERGIC_FIXTURES.seed !== 5629
    || CHOLINERGIC_TUTOR_VERSION !== '0.1.0' || CHOLINERGIC_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(CHOLINERGIC_PESTICIDE_RESPIRATORY_FAILURE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['cholinergic-pesticide-respiratory-failure-fixtures.ts binds seed 5629 and content 0.1.0 to expert, treat-before-protecting error, recovery, and no-action paths. The presentation in still-wet clothing, the supplied respiratory and laboratory set, and the fixed 30-minute post-decontamination report are authored constants; no absorption, cholinesterase, antidote, or ventilation model is claimed, and no outcome follows from any choice. tests/integration/cholinergic-pesticide-respiratory-failure-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, two of them time-gated: the bounded atropine, pralidoxime, benzodiazepine-if-needed, airway and decontamination intent refuses until simulated time has passed since the evidence review, and the handoff refuses until time has passed since that. What moves is the chest rather than the man: the secretions clear while the weakness does not.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions name the wet clothing as a finding about the room, name all three halves of the cholinergic pattern while refusing mnemonic-only and cholinesterase-only closure, protect the room before treating the patient in it, read the secretions, bronchospasm and weakness as one respiratory problem with an early airway question, record bounded qualified intents, and hand off active risk. Order is enforced rather than suggested, and refusal names the missing step. The lesson takes no history, acquires or interprets nothing, and selects no protective equipment, clothing removal, washing method, oxygen, suction, fluid, atropine, pralidoxime, benzodiazepine, dose, route, access, airway, ventilation setting, or neuromuscular blocker.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at active-risk handoff. Later actions cannot restart an ended branch, and the ending certifies no confirmed diagnosis, no proven treatment effect, no complete decontamination, no durable ventilation, no neuromuscular recovery, no proven co-worker safety, no excluded seizure, no determined disposition, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that went to the patient before the room was protected can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['cholinergic-pesticide-respiratory-failure-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 5629 for deterministic replay through the shared engine, including the two time-gated checkpoints.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${CHOLINERGIC_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent and coached withholds the single non-urgent beat. Worked example ${CHOLINERGIC_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. This is the only lesson in the module where the first thing to protect is not the patient, and both spend a whole beat arguing rather than asserting it: he is hypoxic and drowning in secretions, he is also still wearing the concentrate in a room where nobody is protected yet, and PPE and decontamination come first because a second and third patient would delay him far longer than decontamination does. Both refuse the two shortcuts this poisoning invites — the mnemonic, which names the muscarinic half and hides the nicotinic weakness and central depression that actually kill, and the plasma cholinesterase, which marks the exposure rather than grading him. Both read the bronchorrhea, bronchospasm, weak cough and weak neck flexion as one respiratory problem with an early rather than eventual airway question. The ending refuses the tempting equivalence: the secretions dry, the saturation reaches 96%, and the fasciculations and proximal weakness do not move, so drying secretions is not neuromuscular recovery and delayed intermediate syndrome is still ahead. A test asserts nothing anywhere calls him recovered, calls the decontamination complete, or selects a neuromuscular blocker. tests/unit/cholinergic-pesticide-respiratory-failure-demonstration.test.ts and tests/ui/toxicology-cholinergic-pesticide-respiratory-failure.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
