import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { DELAYED_LOCAL_ANESTHETIC_CNS_CARDIAC_TOXICITY } from './scenarios/delayed-local-anesthetic-cns-cardiac-toxicity';
import { DELAYED_LAST_FIXTURES } from './delayed-local-anesthetic-cns-cardiac-toxicity-fixtures';
import { DELAYED_LAST_TUTOR_VERSION } from './tutor/delayed-local-anesthetic-cns-cardiac-toxicity-guidance';
import { DELAYED_LAST_DEMONSTRATION_VERSION } from './demo/delayed-local-anesthetic-cns-cardiac-toxicity-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * `observable-objectives` is deliberately not answered here. This scenario
 * declares six objectives against a cap of five, which is a content-design
 * decision affecting scenarios across several modules rather than something
 * this file may settle on its own. The shared audit keeps naming it.
 */
export function delayedLastCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'toxicology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== DELAYED_LAST_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || DELAYED_LAST_FIXTURES.contentVersion !== '0.1.0'
    || DELAYED_LAST_FIXTURES.seed !== 5828
    || DELAYED_LAST_TUTOR_VERSION !== '0.1.0' || DELAYED_LAST_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(DELAYED_LOCAL_ANESTHETIC_CNS_CARDIAC_TOXICITY)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['delayed-local-anesthetic-cns-cardiac-toxicity-fixtures.ts binds seed 5828 and content 0.1.0 to expert, nobody-goes-to-the-pump error, recovery, and no-action paths. The presentation, the supplied ECG, the blood-gas and chemistry set, and the fixed 20-minute report are authored constants; no absorption, conduction, lipid, or resuscitation model is claimed, and no outcome follows from any choice. tests/integration/delayed-local-anesthetic-cns-cardiac-toxicity-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, two of them time-gated: the bounded source, airway, seizure, lipid, acid-base, modified-resuscitation and extracorporeal intent refuses until simulated time has passed since the evidence review, and the handoff refuses until time has passed since that. What moves is the conduction interval rather than the diagnosis, and the drug already in her tissue is still arriving when it has moved.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions say the catheter is still in place before anything else, name the CNS and cardiac phases as one event while refusing classic-sequence-, clock-, symptom-, seizure- and ECG-only closure, give source cessation an owner in the same breath as the airway and the lipid, read the wide QRS and the acidemia as one loop, record bounded qualified intents, and hand off active risk. Order is enforced rather than suggested, and refusal names the missing step. The lesson takes no history, handles no catheter, excludes nothing, and selects no oxygen setting, sedative, lipid product, dose, route, rhythm intervention, airway device, or circuit.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at active-risk handoff. Later actions cannot restart an ended branch, and the ending certifies no confirmed diagnosis, no excluded alternative, no proven treatment effect, no durable seizure control, rhythm stability or perfusion, no neurologic or airway recovery, no acid-base, electrolyte or lipid safety, no proven source completeness, no determined rescue eligibility, safety or disposition, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run in which the room went to the patient and nobody went to the pump can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['delayed-local-anesthetic-cns-cardiac-toxicity-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 5828 for deterministic replay through the shared engine, including the two time-gated checkpoints.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${DELAYED_LAST_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent and coached withholds the single non-urgent beat. Worked example ${DELAYED_LAST_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. Both are built on the two things that make this presentation hard. Thirty-eight hours after the block nobody is thinking about local anesthetic, and the quiet warnings — metallic taste, tinnitus, perioral tingling — arrived twelve minutes before the convulsion and were never going to be the loud part; so the tidy textbook sequence is named as the thing least worth relying on. And the source is a pump, which means a room doing excellent resuscitation can leave it running: the airway, the seizure, the rhythm and the pressure are all somebody's reflex, and stopping the infusion is nobody's by default, so source cessation gets an owner in the same breath as the airway and the lipid. Both read the QRS of 124 ms with the pH of 7.28 as a loop rather than a list, because acidemia worsens sodium-channel blockade and hypoventilation feeds the acidemia, and both keep the pump unverified rather than cleared. Lipid and extracorporeal eligibility stay specialist-led questions neither determines. The ending hands off a narrower QRS that has not finished narrowing, because drug already in tissue keeps arriving after the pump stops. A test asserts nothing anywhere handles the catheter, excludes an alternative, determines eligibility, or calls the rhythm stable. tests/unit/delayed-local-anesthetic-cns-cardiac-toxicity-demonstration.test.ts and tests/ui/toxicology-delayed-local-anesthetic-cns-cardiac-toxicity.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
