import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { MAGNESIUM_SULFATE_TOXICITY_RECOGNITION } from './scenarios/magnesium-sulfate-toxicity-recognition';
import { MAGNESIUM_TOXICITY_FIXTURES } from './magnesium-sulfate-toxicity-recognition-fixtures';
import { MAGNESIUM_TOXICITY_TUTOR_VERSION } from './tutor/magnesium-sulfate-toxicity-recognition-guidance';
import { MAGNESIUM_TOXICITY_DEMONSTRATION_VERSION } from './demo/magnesium-sulfate-toxicity-recognition-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * `observable-objectives` is deliberately not answered here: this scenario
 * declares six objectives against a cap of five, which is a content-design
 * decision affecting scenarios across several modules rather than something
 * this file may settle on its own.
 */
export function magnesiumToxicityCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'obstetrics' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== MAGNESIUM_TOXICITY_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || MAGNESIUM_TOXICITY_FIXTURES.contentVersion !== '0.1.0'
    || MAGNESIUM_TOXICITY_FIXTURES.seed !== 7244
    || MAGNESIUM_TOXICITY_TUTOR_VERSION !== '0.1.0' || MAGNESIUM_TOXICITY_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(MAGNESIUM_SULFATE_TOXICITY_RECOGNITION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['magnesium-sulfate-toxicity-recognition-fixtures.ts binds seed 7244 and content 0.1.0 to expert, assess-before-calling error, recovery, and no-action paths. The supplied dosing record, the renal decline, the clinical findings, the reported level with all three units, and the fixed 5-minute report are authored constants; no magnesium, clearance, antidote or recovery model is claimed, and no outcome follows from any choice. tests/integration/magnesium-sulfate-toxicity-recognition-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, two of them time-gated: the fixed 5-minute report refuses until simulated time has passed since the readiness review, and the handoff refuses until time has passed since that. What moves is a partial clinical response; what does not move is the magnesium already in her, or the renal function that let it accumulate.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions bring airway-capable anesthesia, obstetrics, critical care, pharmacy and support ownership before any further review, connect the magnesium exposure to the falling renal clearance and the respiratory, reflex and neurologic findings, hold the level as supporting rather than replacing clinical assessment while postpartum, medication, airway, neurologic, metabolic and cardiopulmonary alternatives stay open, review the source-stop, airway, ventilation, antidote, monitoring, newborn and support readiness in parallel, review the fixed report, and hand off unresolved risk. Order is enforced rather than suggested, and every later step refuses until the response has been activated. The lesson examines nobody, interprets no monitoring or laboratory, diagnoses nothing, changes no infusion, manages no airway, delivers no oxygen or ventilation, selects and delivers no antidote, performs no seizure care or procedure, and assesses no newborn.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at unresolved-risk handoff. Later actions cannot restart an ended branch, and the ending certifies no complete reversal, no proven magnesium clearance, no renal recovery, no treatment effect, no newborn safety, no safety disposition, and no maternal, newborn or other outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that assessed the severity before calling for airway help can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['magnesium-sulfate-toxicity-recognition-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 7244 for deterministic replay through the shared engine, including the two time-gated checkpoints.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${MAGNESIUM_TOXICITY_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent and coached withholds the single non-urgent beat. Worked example ${MAGNESIUM_TOXICITY_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. Both open by getting airway-capable help into the room before working anything out, and both name why: a respiratory rate of nine with absent reflexes is respiratory failure arriving quietly, and magnesium toxicity does not look dramatic until it is very late. The mechanism is read as one thing rather than two — a 4 g load and 2 g an hour for twelve hours against a urine output of 70 mL in four hours and a creatinine risen from 0.8 to 1.9, so the dose never changed and her ability to remove it did. The reported level is held as a supporting document rather than the assessment: it is quoted in all three units because confusing mg/dL, mmol/L and mEq/L is a documented source of error, and it was drawn before the infusion stopped, so it describes a moment that has passed while the reflexes and the breathing describe now. Magnesium is not allowed to close the differential. The source-stop, airway, antidote and monitoring are held as one parallel readiness, and stopping the infusion is named as the beginning rather than the end because it removes the cause and not the magnesium already in her. The ending gives back a partial response, which is not a reversal. A test asserts nothing anywhere examines her, changes an infusion, manages an airway, delivers oxygen or ventilation, or selects calcium. tests/unit/magnesium-sulfate-toxicity-recognition-demonstration.test.ts and tests/ui/obstetrics-magnesium-sulfate-toxicity-recognition.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
