import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { OXYTOCIN_ASSOCIATED_UTERINE_TACHYSYSTOLE } from './scenarios/oxytocin-associated-uterine-tachysystole';
import { OXYTOCIN_TACHYSYSTOLE_FIXTURES } from './oxytocin-associated-uterine-tachysystole-fixtures';
import { OXYTOCIN_TACHYSYSTOLE_TUTOR_VERSION } from './tutor/oxytocin-associated-uterine-tachysystole-guidance';
import { OXYTOCIN_TACHYSYSTOLE_DEMONSTRATION_VERSION } from './demo/oxytocin-associated-uterine-tachysystole-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * `observable-objectives` is deliberately not answered here: this scenario
 * declares six objectives against a cap of five, which is a content-design
 * decision affecting scenarios across several modules rather than something
 * this file may settle on its own.
 */
export function oxytocinTachysystoleCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'obstetrics' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== OXYTOCIN_TACHYSYSTOLE_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || OXYTOCIN_TACHYSYSTOLE_FIXTURES.contentVersion !== '0.1.0'
    || OXYTOCIN_TACHYSYSTOLE_FIXTURES.seed !== 7300
    || OXYTOCIN_TACHYSYSTOLE_TUTOR_VERSION !== '0.1.0' || OXYTOCIN_TACHYSYSTOLE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(OXYTOCIN_ASSOCIATED_UTERINE_TACHYSYSTOLE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['oxytocin-associated-uterine-tachysystole-fixtures.ts binds seed 7300 and content 0.1.0 to expert, study-before-calling error, recovery, and no-action paths. The infusion history, the contraction frequency and duration, the fetal-heart trajectory, and the fixed 6-minute report are authored constants; no uterine, placental, fetal or recovery model is claimed, and no outcome follows from any choice. tests/integration/oxytocin-associated-uterine-tachysystole-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, two of them time-gated: the fixed 6-minute report refuses until simulated time has passed since the readiness review, and the handoff refuses until time has passed since that. What moves is an early partial fetal recovery; what does not move is the recurrence risk, the restart decision, or the alternative causes.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions bring senior obstetric, midwifery, anesthesia, newborn and support ownership first, connect the infusion increase to the contraction pattern and the fetal change, name tachysystole with fetal deterioration on the trajectory rather than a single trace while artifact, maternal and fetal alternatives stay open, review the qualified source-stop, position, cause correction, surveillance and birth readiness, review the fixed report, and hand off unresolved risk. Order is enforced rather than suggested, and every later step refuses until the response has been activated. The lesson examines and palpates nobody, interprets no monitoring or tests, diagnoses nothing, operates no infusion, changes no position, delivers no oxygen or fluid, selects no drug or dose, performs no fetal stimulation or amnioinfusion, performs no anesthesia, surgery, delivery or newborn care.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at unresolved-risk handoff. Later actions cannot restart an ended branch, and the ending certifies no proven fetal recovery, no determined restart eligibility, no determined birth plan, no newborn safety, no safety disposition, and no maternal, newborn or other outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that studied the trace before calling for help can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['oxytocin-associated-uterine-tachysystole-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 7300 for deterministic replay through the shared engine, including the two time-gated checkpoints.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${OXYTOCIN_TACHYSYSTOLE_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent and coached withholds the single non-urgent beat. Worked example ${OXYTOCIN_TACHYSYSTOLE_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. Both bring senior help in before studying anything, because the drug that produced this is still running and the interval spent interpreting is an interval the fetus spends under the same contractions. The infusion increase and the fetal change are read as cause and effect: six contractions in every ten-minute window lasting seventy to ninety seconds leave too little time in between, and the time in between is when the placenta refills. The recognition is made on the trajectory rather than one trace — a baseline that rose, variability that fell and decelerations that appeared, together, after an increase — because reading one snapshot lets each of those be argued away separately; and naming it still leaves artifact, maternal causes and an evolving fetal problem open. The first correction is named as stopping the cause, and two reflexive additions are refused: routine oxygen for a fetal heart-rate pattern is not supported, and a fluid bolus without hypotension treats the monitor rather than the mother. The ending gives back an early partial recovery and a cause that could be repeated. A test asserts nothing anywhere examines or palpates her, operates the infusion, changes a position, delivers oxygen or fluid, or plans a birth. tests/unit/oxytocin-associated-uterine-tachysystole-demonstration.test.ts and tests/ui/obstetrics-oxytocin-associated-uterine-tachysystole.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
