import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { SHOULDER_DYSTOCIA_COGNITIVE_SEQUENCE } from './scenarios/shoulder-dystocia-cognitive-sequence';
import { SHOULDER_DYSTOCIA_FIXTURES } from './shoulder-dystocia-cognitive-sequence-fixtures';
import { SHOULDER_DYSTOCIA_TUTOR_VERSION } from './tutor/shoulder-dystocia-cognitive-sequence-guidance';
import { SHOULDER_DYSTOCIA_DEMONSTRATION_VERSION } from './demo/shoulder-dystocia-cognitive-sequence-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * `observable-objectives` is deliberately not answered here: this scenario
 * declares six objectives against a cap of five, which is a content-design
 * decision affecting scenarios across several modules rather than something
 * this file may settle on its own.
 */
export function shoulderDystociaCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'obstetrics' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== SHOULDER_DYSTOCIA_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || SHOULDER_DYSTOCIA_FIXTURES.contentVersion !== '0.1.0'
    || SHOULDER_DYSTOCIA_FIXTURES.seed !== 7202
    || SHOULDER_DYSTOCIA_TUTOR_VERSION !== '0.1.0' || SHOULDER_DYSTOCIA_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(SHOULDER_DYSTOCIA_COGNITIVE_SEQUENCE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['shoulder-dystocia-cognitive-sequence-fixtures.ts binds seed 7202 and content 0.1.0 to expert, understand-before-calling error, recovery, and no-action paths. The head delivery, the failed gentle traction, and the fixed case-specific delivery report are authored constants; no maneuver, force, injury or resolution model is claimed, and no outcome follows from any choice. tests/integration/shoulder-dystocia-cognitive-sequence-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, two of them time-gated: the fixed delivery report refuses until simulated time has passed since the escalation review, and the handoff refuses until time has passed since that. What moves is the organization around her and, at the report, the birth itself; what does not move is anyone’s injury status, which stays undetermined at the end.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions name the emergency and start the head-delivery clock with a leader, a timekeeper, the newborn team and someone with her, take the birth facts as given, review the stop-pushing, no-fundal-pressure, no-forceful-traction and first-line position boundaries, review the qualified escalation maneuvers, the access-only role of episiotomy, the rare rescue options and the contemporaneous record, review the fixed case-specific report, and hand off unresolved risk. Order is enforced rather than suggested, and every later step refuses until the emergency has been called. The lesson examines nobody, applies no traction or pressure, directs no pushing, changes no position, performs no maneuver, episiotomy, delivery or newborn care, and selects no drug, dose, route or procedure.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at unresolved-risk handoff. Later actions cannot restart an ended branch, and the ending certifies no determined maternal or newborn injury, no treatment effect, no safety disposition, and no maternal, newborn or other outcome — a completed birth is not a completed assessment.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that took in the situation before calling the emergency can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['shoulder-dystocia-cognitive-sequence-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 7202 for deterministic replay through the shared engine, including the two time-gated checkpoints.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${SHOULDER_DYSTOCIA_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent and coached withholds the single non-urgent beat. Worked example ${SHOULDER_DYSTOCIA_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. Both open by saying the word out loud, because that is what brings the extra hands, and both start the clock at the delivery of the head rather than at the moment anyone realized, since every later decision is timed against it. Both take the failed gentle traction as the diagnosis rather than something to repeat, and both set the prenatal size estimates aside as having neither predicted this nor ruled it out. The central teaching is that the first two instructions are things to stop: fundal pressure drives the shoulder harder into the pubic bone, continued pushing does the same, and repeating the traction with more force is the specific mechanism by which a brachial plexus is stretched. The escalation is held as a menu rather than a script, because the maneuvers are ordered by convenience and reversibility rather than by evidence that one must precede another, and an episiotomy makes room for hands rather than for the shoulder — the obstruction is bone. Someone records times throughout, because that record is the only version of those two minutes that survives. The ending gives back a birth that happened and two people nobody has examined. A test asserts nothing anywhere examines her, applies traction or pressure, changes a position, or performs a maneuver, episiotomy or delivery. tests/unit/shoulder-dystocia-cognitive-sequence-demonstration.test.ts and tests/ui/obstetrics-shoulder-dystocia-cognitive-sequence.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
