import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PEDIATRIC_INJURY_SAFEGUARDING_ESCALATION } from './scenarios/pediatric-injury-safeguarding-escalation';
import { PEDIATRIC_INJURY_SAFEGUARDING_FIXTURES } from './pediatric-injury-safeguarding-fixtures';
import { PEDIATRIC_INJURY_SAFEGUARDING_TUTOR_VERSION } from './tutor/pediatric-injury-safeguarding-guidance';
import { PEDIATRIC_INJURY_SAFEGUARDING_DEMONSTRATION_VERSION } from './demo/pediatric-injury-safeguarding-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function pediatricInjurySafeguardingCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'pediatrics' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PEDIATRIC_INJURY_SAFEGUARDING_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || PEDIATRIC_INJURY_SAFEGUARDING_FIXTURES.contentVersion !== '0.1.0'
    || PEDIATRIC_INJURY_SAFEGUARDING_FIXTURES.seed !== 2758
    || PEDIATRIC_INJURY_SAFEGUARDING_TUTOR_VERSION !== '0.1.0'
    || PEDIATRIC_INJURY_SAFEGUARDING_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PEDIATRIC_INJURY_SAFEGUARDING_ESCALATION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['pediatric-injury-safeguarding-fixtures.ts binds seed 2758 and content 0.1.0 to expert, skipped-alternatives error, recovery, and no-action paths. The independently mobile two-year-old, the reported forward trip onto a carpeted level floor, the fixed qualified whole-child examination and stable physiology, the supplied objective skin description of a posterior left pinna bruise, three clustered right lateral torso bruises and two anterior-shin bruises with bruise age deliberately not inferred from colour, the fixed experienced-team statement that the reported mechanism does not adequately account for that distribution, the authored history absences, and the fixed later supervised-setting checkpoint are authored constants; no bruising, healing or outcome model is claimed, and no outcome follows from any choice. tests/integration/pediatric-injury-safeguarding-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock as a strict line with two time gates at the end: the alternatives and information-boundary review refuses until qualified safeguarding and immediate-safety ownership is recorded, the later safety state refuses until simulated time has passed since that review, and the handoff is gated on another elapsed tick. This engine case authors no refusable choice; what it refuses is order and time.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile the supplied record while keeping observation separate from inference; recognize a safeguarding concern requiring further evaluation at exactly that width, without diagnosing abuse, attributing anything to a person, or ruling on a caregiver\'s credibility; activate qualified pediatric safeguarding ownership together with immediate-safety ownership; keep the medical alternatives genuinely open and the information need-to-know and source-aware; review the strictly later safety state; and hand off. This lesson has the largest refusal surface in the module and it is not only clinical. The learner does not examine, assess development, take a history, interview a caregiver, solicit a disclosure, collect free text or anything identifying, identify, date, photograph or body-map a bruise, calculate a screening rule, acquire or interpret a test or image, diagnose abuse, name a perpetrator, judge credibility, confront or separate a caregiver, determine a reporting threshold, select a jurisdiction or agency, contact an agency, submit a referral or a legal report, decide custody, remove a child, or determine a safety plan, placement, disposition, prognosis or outcome. The locally governed multi-agency pathway is named as locally governed, and no threshold, agency or duty is taught as the answer.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at handoff with a concern raised and nothing concluded. Later actions cannot restart an ended branch, and the ending certifies no proven abuse, no identified perpetrator, no determined caregiver credibility, no excluded medical mimic, no excluded occult injury, no proven immediate or durable safety, no excluded future harm, no completed referral, no completed legal reporting, no determined custody, no discharge readiness, no determined disposition, and no predicted prognosis or outcome. medicalAlternativesRemainOpen is a fixed true that never becomes false, which is the discipline the whole lesson is built on.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual is the one this subject invites: the common-error path raises the concern and activates ownership correctly, then reaches for the later safety state having never reviewed the medical alternatives or the information boundary — a learner who has raised a concern and skipped the part that keeps it honest, meeting three of six. The recovery path names the concern before reading the record it rests on, reaches for the alternatives review before ownership, and walks into both time gates before clearing them, and still reaches a correct handoff from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['pediatric-injury-safeguarding-fixtures.ts binds exact-content expert, skipped-alternatives error, recovery, and no-action pathways to seed 2758 for deterministic replay through the shared engine, including both order refusals and both time gates.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${PEDIATRIC_INJURY_SAFEGUARDING_TUTOR_VERSION} read the learner's own recorded steps. There is no wrong-turn prose because the engine authors no refusable choice, and the restraint this tutor carries is ethical as much as clinical. The opening beat reads the objective description without interpretation and gives the one piece of pattern knowledge the lesson turns on — shins are where mobile toddlers bruise, ears and lateral torso are not — while noting that bruise age is deliberately not inferred from colour because it cannot reliably be. The concern beat is the centre of the lesson: the true sentence is narrower than the tempting one, widening it invents a finding nobody has made, and narrowing it back into an accident because the child looks well and the caregiver seems plausible is how these are missed. The ownership beat lists what the learner is not doing as specifically as what they are, and names the multi-agency pathway as locally governed rather than universal. The alternatives beat says plainly that a child with an untested coagulopathy looks exactly like this, and so does a family whose ordinary practice a clinician has not recognized, and sets the information boundary at need-to-know and source-aware with no solicited disclosure and no free text. The later beat allows that a stable child in a safe room is genuinely reassuring about this hour and establishes nothing about the next one. The handoff ends on the sentence the lesson exists for: somebody will decide those things, it is not you, and it is not today. Worked example ${PEDIATRIC_INJURY_SAFEGUARDING_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts that no beat anywhere diagnoses abuse, names a person, judges credibility, confronts or separates a caregiver, or submits a referral or report. tests/unit/pediatric-injury-safeguarding-demonstration.test.ts verifies observed response and every beat against the real engine, including that identifyingInformationCollected and freeTextDisclosureCollected are false on every frame, and tests/ui/pediatrics-safeguarding.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
