import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PEDIATRIC_FOREIGN_BODY_AIRWAY_OBSTRUCTION } from './scenarios/pediatric-foreign-body-airway-obstruction';
import { PEDIATRIC_FBAO_FIXTURES } from './pediatric-fbao-fixtures';
import { PEDIATRIC_FBAO_TUTOR_VERSION } from './tutor/pediatric-fbao-guidance';
import { PEDIATRIC_FBAO_DEMONSTRATION_VERSION } from './demo/pediatric-fbao-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function pediatricFbaoCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'pediatrics' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PEDIATRIC_FBAO_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || PEDIATRIC_FBAO_FIXTURES.contentVersion !== '0.1.0'
    || PEDIATRIC_FBAO_FIXTURES.seed !== 8371
    || PEDIATRIC_FBAO_TUTOR_VERSION !== '0.1.0' || PEDIATRIC_FBAO_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PEDIATRIC_FOREIGN_BODY_AIRWAY_OBSTRUCTION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['pediatric-fbao-fixtures.ts binds seed 8371 and content 0.1.0 to expert, premature-transition error, recovery, and no-action paths. The witnessed whole-grape event with the object and its location unconfirmed, the initial effective-cough findings including audible airflow and a normal voice between coughs at 98% on air, the authored absences, the fixed minute-2 severe-responsive report at 91% and falling with a central pulse present, and the fixed minute-3 unresponsive report with electrical activity at 132/min and pulse status deliberately not supplied are authored constants; no obstruction, maneuver-response or outcome model is claimed, and no outcome follows from any choice. tests/integration/pediatric-fbao-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock in a shape that appears nowhere else in the module: a strict deterioration ladder with an elapsed-time gate at every rung rather than one checkpoint near the end. Effective cough, then severe-but-responsive, then unresponsive, each refusing until simulated time has passed since the rung below it, and the handoff gated on a fourth. Each rung has a different correct answer, and the gates are what stop a learner arriving at the bottom before the child does. This engine case authors no refusable choice; what it refuses is order and time.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile the witnessed event against a child who is still moving air; preserve that effective cough with continuous surveillance and explicitly no back blows, no chest or abdominal thrusts and no blind finger sweep; recognize the loss of audible airflow as the transition rather than as improvement; activate the qualified responsive-child choking pathway; activate the qualified unresponsive-child CPR and airway-check pathway when responsiveness is lost; and hand off. The lesson examines nobody, assesses no responsiveness, pulse, airway or cough, acquires or interprets no ECG or test, visualizes, sweeps, suctions or removes no object, chooses or performs no back blow, chest or abdominal thrust, ventilation, compression, CPR sequence, oxygen, airway device, laryngoscopy, bronchoscopy, device operation, procedure, drug or treatment, determines no disposition, predicts no prognosis, and reports no recovery, return of circulation or outcome. The tray reviews only a visible object and exposes no blind sweep at any rung.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at handoff with the object never seen and the obstruction not reported relieved. Later actions cannot restart an ended branch, and the ending certifies no learner examination, cough or pulse assessment, no learner maneuver, sweep, suction or laryngoscopy, no learner compression, ventilation or drug, no reported object clearance, no proven complete clearance, no excluded aspiration or airway injury, no proven treatment effect, no declared cardiac arrest, no proven pulse loss, no reported return of circulation, no durable recovery, and no determined disposition or outcome. Pulse status at the bottom rung is deliberately unavailable, so an unresponsive child with a visible ECG trace is never called an arrest.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual is impatience rather than a wrong maneuver: the common-error path preserves the effective cough correctly and then declares the severe transition in the same minute, which is a learner deciding the child has deteriorated before he has, meeting two of six. The recovery path preserves the cough before reading the event at all and then walks into all three deterioration gates before clearing them, and still reaches a correct handoff from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['pediatric-fbao-fixtures.ts binds exact-content expert, premature-transition error, recovery, and no-action pathways to seed 8371 for deterministic replay through the shared engine, including the order refusals and all three deterioration time gates plus the handoff gate.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${PEDIATRIC_FBAO_TUTOR_VERSION} read the learner's own recorded steps. There is no wrong-turn prose because the engine authors no refusable choice; what this tutor has to carry is that each rung of the ladder has a different right answer, and that the first one is to do nothing to him. The opening beat makes the sound the triage — loud coughing and a normal voice mean air is moving past the obstruction. The effective-cough beat names itself the hardest instruction in the lesson, explains why intervening on a child who is still moving air can convert a partial obstruction into a complete one, and forbids the blind finger sweep specifically as a way to push a grape past where a cough can reach. The transition beat says that silence in a choking child is not improvement but the loss of the airflow that was doing the work. The responsive beat hands every maneuver to the qualified team. The unresponsive beat is careful about what was withheld: pulse status is not supplied, an ECG trace at 132 is not a pulse, and this is an unresponsive child who is not breathing normally rather than a declared arrest. Worked example ${PEDIATRIC_FBAO_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts nothing anywhere performs a back blow, thrust, sweep, suction or laryngoscopy, and that no beat declares an arrest, proves a pulse loss or reports clearance. tests/unit/pediatric-fbao-demonstration.test.ts verifies observed response and every beat against the real engine, and tests/ui/pediatrics-fbao.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
