import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PEDIATRIC_SUPRAVENTRICULAR_TACHYCARDIA } from './scenarios/pediatric-supraventricular-tachycardia';
import { PEDIATRIC_SVT_FIXTURES } from './pediatric-svt-fixtures';
import { PEDIATRIC_SVT_TUTOR_VERSION } from './tutor/pediatric-svt-guidance';
import { PEDIATRIC_SVT_DEMONSTRATION_VERSION } from './demo/pediatric-svt-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function pediatricSvtCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'pediatrics' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PEDIATRIC_SVT_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || PEDIATRIC_SVT_FIXTURES.contentVersion !== '0.1.0'
    || PEDIATRIC_SVT_FIXTURES.seed !== 4903
    || PEDIATRIC_SVT_TUTOR_VERSION !== '0.1.0' || PEDIATRIC_SVT_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PEDIATRIC_SUPRAVENTRICULAR_TACHYCARDIA)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['pediatric-svt-fixtures.ts binds seed 4903 and content 0.1.0 to expert, unowned-rhythm error, recovery, and no-action paths. The abrupt onset 45 minutes earlier, the fixed rhythm-change event putting a regular narrow-complex 210/min rhythm on the teaching monitor, the supplied ECG description of QRS 70 ms with nonvariable RR intervals and no visible P waves as a probable pattern without an established mechanism, the whole-child findings with a blood pressure of 96/60 against a refill of 4 seconds and weak peripheral pulses, the authored absences, and the fixed later sinus-rhythm report are authored constants; no electrophysiological, conversion or outcome model is claimed, and no outcome follows from any choice. tests/integration/pediatric-svt-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock as a strict line, as in the anaphylaxis lesson rather than the six unordered-pair lessons: the support, causes, heart-failure and deterioration review refuses until qualified rhythm-care ownership is recorded, because a rhythm that has run for 45 minutes in a child with cold hands is not a thing to review first. Two time gates follow, on the later report and on the handoff. This engine case authors no refusable choice; what it refuses is order and time.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile the 45-minute clock, the supplied rhythm description and the whole-child state; recognize perfusion compromise underneath a normal blood pressure, which is the boundary that makes the next step urgent rather than routine; activate qualified pediatric rhythm-care and resuscitation ownership before anything broader; hold support, contributors, heart failure and the deterioration boundary in parallel; review the strictly later fixed report; and hand off. The lesson examines and monitors nobody, assesses no pulse, acquires or interprets no ECG or other test, diagnoses nothing and assigns no mechanism, performs no vagal maneuver, places no access, selects no modality, drug, product, concentration, dose, route, volume, rate, device, energy or sedation, performs no cardioversion or other procedure, and determines no disposition, prognosis, recurrence or outcome. The entire escalation ladder from vagal maneuver to cardioversion stays with the qualified team.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at handoff on a reported sinus rhythm with the mechanism, the cause and the recurrence risk all open. Later actions cannot restart an ended branch, and the ending certifies no learner examination, ECG acquisition or interpretation, no learner diagnosis or mechanism assignment, no learner maneuver, access, modality, drug, dose or energy, no proven SVT, no excluded sinus tachycardia, no proven mechanism or cause, no proven treatment effect, no durable conversion, no durable recovery, no excluded heart failure, deterioration or recurrence, no determined disposition, and no outcome. The lesson is explicit that no learner-delivered intervention preceded the conversion, because the learner delivered none.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual is what the engine ordering exists to refuse: the common-error path recognizes the compromise correctly and then reviews the support and deterioration risks while a 45-minute rhythm still has no owner, meeting two of six. The recovery path takes that refusal, corrects it, and walks into both time gates before clearing them, and still reaches a correct handoff from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['pediatric-svt-fixtures.ts binds exact-content expert, unowned-rhythm error, recovery, and no-action pathways to seed 4903 for deterministic replay through the shared engine, including both order refusals and both time gates.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${PEDIATRIC_SVT_TUTOR_VERSION} read the learner's own recorded steps. There is no wrong-turn prose because the engine authors no refusable choice. What the tutor holds instead is a child who is compromised without being unstable in the way the word usually gets used. The opening beat starts the clock at 45 minutes and says what separates this from a sinus tachycardia — the abruptness and the fixed rate, against a rhythm that would vary and would have a reason — then puts the reassuring numbers and the cold hands in the same sentence. The recognition beat names the trap directly: a normal blood pressure is not the same as adequate perfusion, and compensating is a thing children do well right up until they stop. The care beat hands the entire ladder to the qualified team and says why the ordering exists. The safety beat raises pre-excitation as unexcluded and therefore load-bearing for what is safe. The later beat treats conversion as where the cardiology question starts rather than stops, and states plainly that no learner-delivered intervention preceded it. Worked example ${PEDIATRIC_SVT_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts nothing anywhere examines him, reads the ECG, performs a maneuver, or selects a drug, dose, modality or energy. tests/unit/pediatric-svt-demonstration.test.ts verifies observed response and every beat against the real engine, including that the reported sinus rhythm never flips svtFinallyProven, sinusTachycardiaExcluded, mechanismProven, causeProven, treatmentEffectProven, durableConversionProven, heartFailureExcluded or recurrenceExcluded, and tests/ui/pediatrics-svt.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding. The identity guard is the one place this lesson differs from its siblings: its timeline is not all narrative, so the guard asserts the opening rhythm-change event rather than assuming its absence.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
