import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PEDIATRIC_DIABETIC_KETOACIDOSIS } from './scenarios/pediatric-diabetic-ketoacidosis';
import { PEDIATRIC_DKA_FIXTURES } from './pediatric-dka-fixtures';
import { PEDIATRIC_DKA_TUTOR_VERSION } from './tutor/pediatric-dka-guidance';
import { PEDIATRIC_DKA_DEMONSTRATION_VERSION } from './demo/pediatric-dka-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function pediatricDkaCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'pediatrics' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PEDIATRIC_DKA_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || PEDIATRIC_DKA_FIXTURES.contentVersion !== '0.1.0'
    || PEDIATRIC_DKA_FIXTURES.seed !== 9514
    || PEDIATRIC_DKA_TUTOR_VERSION !== '0.1.0' || PEDIATRIC_DKA_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PEDIATRIC_DIABETIC_KETOACIDOSIS)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['pediatric-dka-fixtures.ts binds seed 9514 and content 0.1.0 to expert, unwatched-protocol error, recovery, and no-action paths. The two-week polyuric history and the one-day deterioration, the whole-child findings, the supplied venous panel of glucose 468 mg/dL, beta-hydroxybutyrate 5.6 mmol/L, pH 7.14, bicarbonate 8, potassium 4.6 and sodium 132, the supplied experienced-team classification, the authored absences including the absent cerebral-injury warning cluster, and the fixed minute-60 repeat panel are authored constants; no glycemic, ketone, acid-base, osmolar or outcome model is claimed, and no outcome follows from any choice. tests/integration/pediatric-dka-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, in the branching shape it shares with pediatric septic shock and dehydration. Qualified care ownership and the neurological-metabolic safety review are unordered against each other: either may be recorded first, and the later report refuses until both are active and simulated time has passed since whichever landed second. The handoff is gated on another elapsed tick. This engine case authors no refusable choice; what it refuses is order and time.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile the supplied illness, whole-child state and fixed biochemical panel as one story rather than a child plus a set of numbers; recognize that hyperglycemia, ketonemia and metabolic acidosis together establish authored DKA while glucose alone does not, and draw two boundaries — no current shock, and no current cerebral-injury warning cluster stated as a description of this minute rather than an exclusion; activate experienced pediatric, diabetes, nursing, pharmacy and laboratory ownership of locally protocolized fluid, insulin, glucose, electrolyte, access, monitoring and escalation work; keep serial neurological, circulatory, metabolic and precipitant review running in parallel; review the strictly later fixed report; and hand off. The tray shows one clear current action per card except at the recognition step, where it deliberately offers both halves of the unordered pair at once. The lesson examines nobody, performs no neurological examination, calculates no dehydration percentage, corrected sodium, osmolality, anion gap, deficit, maintenance, dose or rate, diagnoses or grades nothing, acquires or interprets no test, chooses or delivers no oral, intravenous or intraosseous fluid, solution, bolus, volume, rate, insulin, dextrose, potassium, phosphate, bicarbonate, access, device, drug, procedure or treatment, and determines no disposition, prognosis, recurrence or outcome. No universal sequence, threshold or formula is taught, and the real differences between local protocols are named as differences rather than resolved.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at handoff on improving fixed trends with DKA and neurological-metabolic surveillance still active, and with the precipitant unidentified. Later actions cannot restart an ended branch, and the ending certifies no learner diagnosis or severity grade, no learner calculation of any kind, no learner-selected fluid, insulin, electrolyte, dose, rate or access, no proven treatment effect, no biochemical resolution, no excluded cerebral injury, no durable recovery, no discharge readiness, no determined disposition, and no outcome. cerebralInjuryExcluded stays false for the whole lesson, including after the improving report.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual is a protocol with nobody watching her brain: the common-error path activates qualified care correctly and reaches for the later report having never set the neurological-metabolic review, meeting three of six. The recovery path takes the unordered pair in the opposite order, safety before care, and walks into both time gates before clearing them, and still reaches a correct handoff from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['pediatric-dka-fixtures.ts binds exact-content expert, unwatched-protocol error, recovery, and no-action pathways to seed 9514 for deterministic replay through the shared engine, including the order refusal, the parallel-care refusal, and both time gates.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Seven observed-state prompts at version ${PEDIATRIC_DKA_TUTOR_VERSION} read the learner's own recorded steps. There is no wrong-turn prose because the engine authors no refusable choice; what the tutor refuses to let a learner do is turn an absence into an exclusion. The opening beat reads the child and the panel as one story and points out that the deep breathing and the abdominal pain are already explained by the panel rather than being a second illness, which is how a child in this state ends up with a surgical referral. The recognition beat says three findings make this rather than one, and then draws both boundaries: not in shock, and no cerebral-injury warning cluster right now — a description of this minute, not an exclusion, which is why neurological surveillance is a step of its own rather than a footnote. Three of the seven prompts cover the three ways the unordered pair can be half done. The safety beat names what the repetition is for: no single sign proves cerebral injury and no single sign excludes it. The later beat treats uniformly improving numbers as the moment to be most careful, and says the surveillance does not relax because the numbers did. Worked example ${PEDIATRIC_DKA_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, taking the pair care-first as one valid order rather than the required one, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts nothing anywhere examines her, performs a neurological examination, calculates a corrected sodium, osmolality or deficit, or selects a fluid, insulin, dose, rate or access. tests/unit/pediatric-dka-demonstration.test.ts verifies observed response and every beat against the real engine, including both orders of the unordered pair and that the improving report never flips cerebralInjuryExcluded, and tests/ui/pediatrics-dka.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
