import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PEDIATRIC_SEPSIS } from './scenarios/pediatric-sepsis';
import { PEDIATRIC_SEPSIS_FIXTURES } from './pediatric-sepsis-fixtures';
import { PEDIATRIC_SEPSIS_TUTOR_VERSION } from './tutor/pediatric-sepsis-guidance';
import { PEDIATRIC_SEPSIS_DEMONSTRATION_VERSION } from './demo/pediatric-sepsis-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * Six objectives, so the shared objectives cap stays outstanding here
 * alongside the two runtime requirements.
 */
export function pediatricSepsisCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'pediatrics' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PEDIATRIC_SEPSIS_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || PEDIATRIC_SEPSIS_FIXTURES.contentVersion !== '0.1.0'
    || PEDIATRIC_SEPSIS_FIXTURES.seed !== 5188
    || PEDIATRIC_SEPSIS_TUTOR_VERSION !== '0.1.0' || PEDIATRIC_SEPSIS_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PEDIATRIC_SEPSIS)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['pediatric-sepsis-fixtures.ts binds seed 5188 and content 0.1.0 to expert, premature-trajectory error, recovery, and no-action paths. The thirty-hour febrile history with dysuria and flank discomfort, the probable but unconfirmed urinary source, the minute-25 qualified-care record, the minute-35 findings with platelets 82,000, INR 1.5 and lactate 2.6, the supplied Phoenix classification of 2 coagulation and 0 cardiovascular points, the fixed minute-120 report, and the absences that narrow without excluding are authored constants; no infection, antimicrobial-response or outcome model is claimed, and no outcome follows from any choice. tests/integration/pediatric-sepsis-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock. Unlike the other pediatrics lessons written so far, this engine case authors no refusable choice: what it refuses is order and time. Each step refuses until its predecessor is recorded, and two are additionally time-gated — the later report and the handoff each refuse until simulated time has passed, so a trajectory cannot be declared in the minute the source review was recorded.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions reconcile the supplied infection, coagulation dysfunction, whole-child state and qualified-care record; draw the sepsis-without-shock boundary in both directions, so that no routine fluid bolus is reached for and preserved pressure is not read as low risk; confirm continuing pediatric, nursing, pharmacy, laboratory and escalation ownership of care already delivered; hold source, organ, alternative-cause and deterioration work in parallel without waiting for every result; review the strictly later fixed report; and hand off. The tray shows one clear current action per card. The lesson examines nobody, calculates no Phoenix, PEWS or SIRS score, diagnoses nothing, acquires or interprets no culture, specimen, lactate, gas, laboratory test or image, identifies no source or pathogen, chooses or delivers no antimicrobial, drug, dose, concentration, route, interval, intravenous or intraosseous access, fluid, bolus, volume, rate, vasoactive, oxygen, device, flow, ventilation, airway maneuver, source-control procedure or treatment, and determines no disposition, prognosis or outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at handoff on improved physiology with unchanged coagulation dysfunction and an unconfirmed source. Later actions cannot restart an ended branch, and the ending certifies no learner diagnosis, no learner-calculated score, no learner-selected antimicrobial, dose or route, no confirmed source or pathogen, no proven treatment effect, no durable recovery, no determined disposition, and no outcome — and preserves shock surveillance, bleeding surveillance, and the alternative sources and causes that thirty hours of fever leaves open.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. The counterfactual is impatience rather than over-treatment: the common-error path does everything correctly and then asks for the later report in the same minute it recorded the source review, meeting four of six. The recovery path additionally reaches for care ownership before there is a pattern to own and for the source review before the boundary is drawn, and still reaches a correct handoff from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['pediatric-sepsis-fixtures.ts binds exact-content expert, premature-trajectory error, recovery, and no-action pathways to seed 5188 for deterministic replay through the shared engine, including both order refusals and both time gates.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${PEDIATRIC_SEPSIS_TUTOR_VERSION} read the learner's own recorded steps. There is no wrong-turn prose here because the engine authors no refusable choice; the failure mode the tutor answers is quieter than a bad choice, being a boy who is awake, warm and normotensive and does not look like the emergency his platelet count says he is. The opening beat separates what makes this sepsis — platelets of 82,000, an INR of 1.5, a lactate of 2.6 — from the fever and tachycardia that are its context rather than a shortcut to it. The boundary beat is deliberately two-directional: no current shock means no routine fluid bolus is authored, because a bolus given to a child who is not shocked buys nothing and costs something, and preserved pressure, refill, pulse quality, mentation and oxygenation describe this minute rather than establishing low risk. The ownership beat names what stays with the qualified team and observes that care nobody owns is care that quietly stops. The source beat holds pending cultures and organ trends together, since waiting for every result is how a wrong source survives the afternoon and claiming the source is how the alternative gets missed. The later beat says plainly that the physiology got better and the organ dysfunction did not. Worked example ${PEDIATRIC_SEPSIS_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff, and its narration is generated from the tutor's own prose so the two cannot drift apart. A test asserts nothing anywhere examines him, calculates the score, names a pathogen, or selects an antimicrobial, dose, route, fluid or bolus. tests/unit/pediatric-sepsis-demonstration.test.ts verifies observed response and every beat against the real engine, and tests/ui/pediatrics-sepsis.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'observable-objectives', status: 'missing', evidence: ['Six declared objectives exceed the five the shared catalog counts as independently observable within one session.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
