/**
 * The cardiology module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a cardiology scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const CARDIOLOGY_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'stable-chest-pain-history-likelihood-and-plan-are-authored',
    headline: 'The symptom history, risk factors, resting ECG report, likelihood tier, and testing discussion are authored teaching facts.',
    simplification: 'One outpatient has a fixed stable exertional pattern and a fixed not-very-low risk-factor-weighted clinical-likelihood label without a calculated score.',
    whereItMisleads: 'Treating the screen as history-taking, examination, ECG interpretation, risk calculation, diagnosis, test selection, or prediction for a real person.',
    correctUnderstanding: 'Real evaluation integrates the full patient history, examination, ECG, risk factors, preferences, comorbidity, local expertise, access, and serial change.',
    briefIn: ['stable-chest-pain-evaluation'],
  },
  {
    id: 'stable-chest-pain-controls-record-review-and-shared-plan-intent-only',
    headline: 'The ordered buttons record review, shared-plan, follow-up, and safety-net intent; they do not deliver cardiovascular care.',
    simplification: 'Five clicks stand in for clinical assessment, likelihood estimation, shared decision-making, testing discussion, follow-up, and communication.',
    whereItMisleads: 'Equating button order with history, examination, communication, diagnostic reasoning, test selection, documentation, or cardiology competence.',
    correctUnderstanding: 'Actual care requires a patient-specific clinical evaluation, meaningful shared decisions, local testing pathways, clear communication, and longitudinal follow-up.',
    briefIn: ['stable-chest-pain-evaluation'],
  },
  {
    id: 'no-live-cardiac-testing-diagnosis-prescribing-prognosis-or-outcome',
    headline: 'The lab does not acquire or interpret cardiac tests, calculate a score, diagnose, prescribe, determine disposition, or predict outcome.',
    simplification: 'No examination, exercise-capacity measurement, ECG acquisition, calcium score, CCTA, stress test, angiography, treatment, event, or outcome is modeled.',
    whereItMisleads: 'Using the authored likelihood tier as a patient-specific tool, assuming one universal test, or inferring coronary disease, ischemia, safety, prognosis, or treatment benefit.',
    correctUnderstanding: 'Use current local pathways and qualified clinical judgment to evaluate acute change, estimate likelihood, select or defer testing, manage risk, and arrange follow-up.',
    briefIn: ['stable-chest-pain-evaluation'],
  },
  {
    id: 'nstemi-serial-findings-and-risk-tier-are-authored',
    headline: 'The symptom course, serial ECG reports, troponin values, NSTEMI conclusion, and high-risk tier are authored teaching facts.',
    simplification: 'One inpatient has a fixed resolved symptom episode, dynamic ECG reports, assay-bounded troponin rise, and no current very-high-risk feature without live acquisition or calculation.',
    whereItMisleads: 'Treating the bedside trace as a diagnostic 12-lead, the troponin values as transferable between assays, or the authored risk tier as a patient-specific score or diagnosis.',
    correctUnderstanding: 'Real assessment integrates current symptoms, examination, serial diagnostic ECGs, assay-specific troponin change, competing injury causes, comorbidity, and repeated risk assessment.',
    briefIn: ['nstemi-risk-reassessment'],
  },
  {
    id: 'nstemi-controls-record-reassessment-and-plan-intent-only',
    headline: 'The ordered controls record serial review, danger screening, strategy, monitoring, and ownership intent; they do not deliver ACS care.',
    simplification: 'Five clicks stand in for multidisciplinary assessment, communication, regional pathway use, bleeding-risk review, monitoring, and handoff.',
    whereItMisleads: 'Equating the sequence with examination, ECG or laboratory interpretation, risk calculation, prescribing, communication, angiography planning, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified teams, real-time assessment, verified test results, local ACS pathways, patient-specific treatment, communication, and repeated response review.',
    briefIn: ['nstemi-risk-reassessment'],
  },
  {
    id: 'no-live-nstemi-testing-scoring-treatment-procedure-prognosis-or-outcome',
    headline: 'The lab does not acquire tests, calculate scores, prescribe, perform angiography or revascularization, determine universal timing, or predict outcome.',
    simplification: 'No live ECG, troponin, imaging, GRACE or bleeding score, medication, transfer, angiography, PCI, surgery, infarct trajectory, complication, or outcome is modeled.',
    whereItMisleads: 'Copying a fictional value or timing, using one regional strategy everywhere, assuming pain resolution lowers risk, or inferring procedural benefit, prognosis, or safety.',
    correctUnderstanding: 'Use current regional guidance and local pathways to integrate evolving ischemic and bleeding risk, patient preferences, capability, treatment, invasive timing, and longitudinal care.',
    briefIn: ['nstemi-risk-reassessment'],
  },
  {
    id: 'clinic-stemi-symptoms-ecg-and-stability-are-authored',
    headline: 'The symptom trajectory, diagnostic ECG report, stability, and complication screen are authored teaching facts.',
    simplification: 'One outpatient clinic record supplies fixed symptoms, an inferior-STEMI 12-lead report, vital signs, and selected negative findings without live acquisition or interpretation.',
    whereItMisleads: 'Treating the teaching monitor as a diagnostic 12-lead or the fixed complication screen as examination, diagnosis, or proof that the patient will remain stable.',
    correctUnderstanding: 'Real care requires immediate EMS and regional-system activation plus repeated whole-patient, diagnostic-ECG, rhythm, conduction, right-ventricular, mechanical, bleeding, and alternate-diagnosis assessment.',
    briefIn: ['stemi-recognition-and-first-actions'],
  },
  {
    id: 'clinic-stemi-controls-record-escalation-transfer-and-bridge-intent-only',
    headline: 'The controls record recognition, parallel escalation, clinic-bridge, and handoff intent; they do not deliver STEMI care.',
    simplification: 'Five clicks stand in for EMS activation, regional coordination, patient assessment, monitored transport preparation, aspirin-suitability review, communication, and reassessment.',
    whereItMisleads: 'Equating button order with examination, ECG interpretation, drug administration, transport, communication, reperfusion selection, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified teams, immediate system activation, verified findings, patient-specific treatment, real transport, explicit communication, and continuous reassessment.',
    briefIn: ['stemi-recognition-and-first-actions'],
  },
  {
    id: 'no-live-ecg-testing-diagnosis-drug-delivery-reperfusion-disposition-or-outcome',
    headline: 'The lab does not interpret tests, diagnose a real patient, deliver drugs, select reperfusion, transport, determine disposition, or predict outcome.',
    simplification: 'No live ECG, biomarker, imaging, oxygen, aspirin, P2Y12 inhibitor, anticoagulant, fibrinolytic, nitrate, opioid, PCI, transport, complication, or outcome is modeled.',
    whereItMisleads: 'Waiting on a checklist or biomarker, copying the fictional record, assuming one destination or reperfusion strategy, or inferring safety or treatment effect.',
    correctUnderstanding: 'Use current regional protocols and qualified EMS, emergency, and cardiology judgment to activate the system immediately, individualize treatment and destination, and reassess continuously.',
    briefIn: ['stemi-recognition-and-first-actions'],
  },
  {
    id: 'heart-failure-status-response-and-precipitant-are-authored',
    headline: 'The congestion, perfusion, treatment report, serial response, laboratory values, and precipitant context are authored teaching facts.',
    simplification: 'One inpatient has fixed HFrEF, partial decongestion after reported treatment, warm perfusion, a small creatinine change, and residual congestion.',
    whereItMisleads: 'Treating the screen as history, examination, monitoring, fluid-balance verification, laboratory or imaging interpretation, diagnosis, treatment-response measurement, or prognosis for a real person.',
    correctUnderstanding: 'Real assessment verifies treatment delivery and integrates serial symptoms, examination, weight, intake and output, urine output, oxygenation, hemodynamics, kidney function, electrolytes, imaging context, and precipitants.',
    briefIn: ['acute-decompensated-heart-failure'],
  },
  {
    id: 'heart-failure-controls-record-review-and-transition-intent-only',
    headline: 'The ordered controls record status, response, tolerance, transition, readiness, and ownership intent; they do not deliver heart-failure care.',
    simplification: 'Five clicks stand in for multidisciplinary inpatient assessment, individualized decongestion, medication review, education, transition planning, and follow-up.',
    whereItMisleads: 'Equating button order with examination, fluid management, prescribing, medication reconciliation, nursing, pharmacy, dietitian, education, discharge, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified teams, verified measurements and treatment delivery, patient-specific decisions, medication reconciliation, education, communication, and repeated bedside reassessment.',
    briefIn: ['acute-decompensated-heart-failure'],
  },
  {
    id: 'no-live-heart-failure-exam-testing-dosing-treatment-disposition-prognosis-or-outcome',
    headline: 'The lab does not examine, acquire tests, calculate targets or doses, prescribe, deliver treatment, select a regimen, determine disposition, or predict outcome.',
    simplification: 'No live examination, weight, balance, urine output, laboratory test, imaging, medication, dose, fluid target, dry weight, response, discharge, readmission, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying a fictional value as a target, using creatinine or fluid balance alone, assuming clinic weight equals euvolemia, selecting a universal regimen, or inferring readiness or benefit from partial improvement.',
    correctUnderstanding: 'Use current local pathways and qualified multidisciplinary judgment to verify response, individualize decongestion and guideline-directed therapy, correct precipitants, establish readiness, and arrange longitudinal care.',
    briefIn: ['acute-decompensated-heart-failure'],
  },
  {
    id: 'af-rvr-rhythm-duration-risk-and-response-are-authored',
    headline: 'The AF report, stability, duration uncertainty, ventricular function, risk tier, contributor screen, and response are authored teaching facts.',
    simplification: 'One stable patient has fixed AF at 142/min, uncertain duration, preserved LVEF, a not-low stroke-risk label without a score, and a fixed lower-rate response that remains AF.',
    whereItMisleads: 'Treating the teaching trace as a diagnostic ECG, the fixed stability as examination, or the authored duration, contributor, risk, and response record as patient-specific assessment or prediction.',
    correctUnderstanding: 'Real AF care verifies the rhythm and repeatedly integrates hemodynamics, symptoms, perfusion, heart failure, duration, prior history, triggers, ventricular function, thromboembolic and bleeding risk, preferences, and response.',
    briefIn: ['atrial-fibrillation-with-rapid-response'],
  },
  {
    id: 'af-rvr-controls-record-review-and-plan-intent-only',
    headline: 'The ordered controls record stability, context, rate, stroke-prevention, reassessment, and ownership intent; they do not deliver AF care.',
    simplification: 'Five clicks stand in for history, examination, diagnostic review, patient-specific treatment planning, shared decision-making, monitoring, communication, and follow-up.',
    whereItMisleads: 'Equating button order with ECG interpretation, risk calculation, medication selection, anticoagulation, cardioversion planning, communication, documentation, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified assessment, a diagnostic ECG, current local pathways, patient-specific rate and rhythm decisions, validated stroke-risk review, shared decisions, and repeated follow-up.',
    briefIn: ['atrial-fibrillation-with-rapid-response'],
  },
  {
    id: 'no-live-af-rvr-ecg-scoring-prescribing-cardioversion-prognosis-or-outcome',
    headline: 'The lab does not interpret an ECG, calculate a score, prescribe or deliver treatment, decide anticoagulation or cardioversion eligibility, or predict outcome.',
    simplification: 'No live ECG, laboratory test, imaging, risk score, rate target, medication, anticoagulant, dose, rhythm conversion, cardioversion, ablation, disposition, recurrence, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using heart rate alone for instability, copying a target or agent, assuming a lower rate removes AF or stroke risk, inferring AF onset from symptom onset, or treating one pathway as universal.',
    correctUnderstanding: 'Use current local AF guidance and qualified judgment to determine stability, duration, contributors, rate or rhythm strategy, stroke prevention, cardioversion safety, monitoring, and longitudinal care.',
    briefIn: ['atrial-fibrillation-with-rapid-response'],
  },
  {
    id: 'post-infarction-shock-findings-support-and-response-are-authored',
    headline: 'The post-PCI findings, verified initial support, worsening perfusion trajectory, consultation context, and later response are authored teaching facts.',
    simplification: 'One non-advanced-center record supplies fixed treatment, pressure, brain, skin, kidney, lactate, congestion, ECG, echo, rhythm, and bleeding snapshots.',
    whereItMisleads: 'Treating the screen as live examination, monitoring, test interpretation, diagnosis, durable culprit-vessel patency, or proof of one shock cause.',
    correctUnderstanding: 'Real care verifies evolving findings and repeatedly reopens ischemic, mechanical, right-heart, rhythm, bleeding, vasodilated, obstructive, treatment, and device contributors.',
    briefIn: ['post-infarction-cardiogenic-shock-escalation'],
  },
  {
    id: 'post-infarction-shock-controls-record-consultation-bridge-and-handoff-intent-only',
    headline: 'The controls record trajectory review, cause review, consultation, bridge, and handoff intent; they do not deliver shock care or authorize transfer.',
    simplification: 'Five clicks stand in for multidisciplinary assessment, regional consultation, potential-transfer evaluation, individualized stabilization planning, communication, and reassessment.',
    whereItMisleads: 'Equating button order with examination, treatment, device selection, transfer acceptance, transport, communication, documentation, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified teams, verified real-time data, patient-specific support, candidacy and risk review, accepting-center decisions, safe transport planning, and repeated reassessment.',
    briefIn: ['post-infarction-cardiogenic-shock-escalation'],
  },
  {
    id: 'no-live-post-infarction-shock-testing-treatment-device-transfer-or-outcome',
    headline: 'The lab does not acquire tests, diagnose, prescribe, deliver treatment, select or place a device, perform a procedure or transfer, or predict outcome.',
    simplification: 'No live monitoring, laboratory test, ECG, echo, angiography, hemodynamics, drug, fluid, target, device, PCI, surgery, transport, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying a fictional value, assuming a higher pressure resolves shock, selecting routine support, or treating regional consultation as transfer authorization.',
    correctUnderstanding: 'Use current guidance, local pathways, qualified multidisciplinary judgment, regional consultation, shared decisions, and serial assessment for real cardiogenic-shock care.',
    briefIn: ['post-infarction-cardiogenic-shock-escalation'],
  },
  {
    id: 'stable-regular-narrow-rhythm-context-and-response-are-authored',
    headline: 'The regular narrow rhythm, current stability, context, nonconversion, and later sinus response are authored teaching facts.',
    simplification: 'One monitored record supplies fixed rhythm, pressure, perfusion, symptom, contraindication, readiness, and response snapshots without live acquisition.',
    whereItMisleads: 'Treating the teaching trace as a diagnostic ECG, rate as a stability test, or conversion as proof of AVNRT, cure, recurrence risk, or prognosis.',
    correctUnderstanding: 'Real care verifies rhythm and repeatedly integrates whole-patient stability, mechanism alternatives, causes, contraindications, response, adverse effects, preferences, and recurrence.',
    briefIn: ['regular-narrow-complex-tachycardia'],
  },
  {
    id: 'stable-regular-narrow-controls-record-review-and-treatment-intent-only',
    headline: 'The controls record review, monitored readiness, vagal and adenosine intent, response, and follow-up; they do not perform treatment.',
    simplification: 'Six clicks stand in for clinical assessment, monitored preparation, coached maneuver, medication planning, observation, communication, and follow-up.',
    whereItMisleads: 'Equating button order with examination, ECG interpretation, IV placement, maneuver quality, drug preparation or delivery, communication, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified teams, verified findings, real monitoring and access, patient-specific contraindication review, safe treatment delivery, and repeated reassessment.',
    briefIn: ['regular-narrow-complex-tachycardia'],
  },
  {
    id: 'no-live-regular-narrow-ecg-diagnosis-drug-cardioversion-ablation-or-outcome',
    headline: 'The lab does not interpret an ECG, diagnose a mechanism, perform a maneuver, deliver medication, cardiovert, ablate, or predict outcome.',
    simplification: 'No live examination, ECG, laboratory test, vagal effort, access, dose, drug, shock, procedure, disposition, recurrence, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying the fictional values, assuming universal adenosine suitability, treating nonconversion or conversion as diagnostic, or inferring durable success.',
    correctUnderstanding: 'Use current resuscitation and rhythm guidance, local protocols, qualified judgment, patient preferences, and longitudinal cardiology care for real tachycardia.',
    briefIn: ['regular-narrow-complex-tachycardia'],
  },
  {
    id: 'stable-wide-complex-rhythm-context-and-responses-are-authored',
    headline: 'The pulsed regular monomorphic wide rhythm, stability, treating-team medication course, nonresponse, and sinus report are authored teaching facts.',
    simplification: 'One monitored record supplies fixed rhythm, pressure, perfusion, history, laboratory, readiness, and response snapshots.',
    whereItMisleads: 'Treating the teaching trace as diagnostic, declaring every WCT to be VT, or reading conversion as proof, cure, recurrence risk, or prognosis.',
    correctUnderstanding: 'Real care repeatedly verifies pulse, stability, morphology, causes, contraindications, response, adverse effects, and pathway changes.',
    briefIn: ['wide-complex-tachycardia'],
  },
  {
    id: 'stable-wide-complex-controls-record-review-readiness-and-treatment-intent-only',
    headline: 'The controls record review, readiness, an authored medication path, escalation intent, and follow-up; they do not deliver treatment.',
    simplification: 'Seven clicks stand in for expert assessment, monitored preparation, treating-team care, observation, communication, and follow-up.',
    whereItMisleads: 'Equating button order with ECG interpretation, access, medication preparation or delivery, synchronization, shock delivery, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified teams, verified findings, local protocols, safe delivery, immediate pathway switching, and repeated reassessment.',
    briefIn: ['wide-complex-tachycardia'],
  },
  {
    id: 'no-live-wide-complex-diagnosis-dose-drug-delivery-cardioversion-device-decision-or-outcome',
    headline: 'The lab does not diagnose a mechanism, dose or deliver a drug, operate a defibrillator, cardiovert, decide device therapy, or predict outcome.',
    simplification: 'No live exam, ECG, laboratory test, access, dose, infusion rate, drug delivery, energy, sedation, shock, procedure, disposition, recurrence, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying values, stacking agents, using verapamil or diltiazem, generalizing the authored sequence, or applying it to unstable, polymorphic, or pulseless rhythms.',
    correctUnderstanding: 'Use current resuscitation guidance, local protocols, qualified judgment, expert consultation, and longitudinal cardiology care for real WCT.',
    briefIn: ['wide-complex-tachycardia'],
  },
  {
    id: 'symptomatic-sinus-bradycardia-record-context-and-correlation-are-authored',
    headline: 'The sinus rhythm, stable physiology, symptom diary, monitor report, contributor context, and correlation are authored teaching facts.',
    simplification: 'One return-visit record supplies fixed rhythm, pressure, symptoms, ECG, patch, laboratory, medication, and exclusion snapshots.',
    whereItMisleads: 'Treating the teaching trace as diagnostic, calling a low rate unstable, or reading correlation as proof of one cause, pacing eligibility, benefit, or prognosis.',
    correctUnderstanding: 'Real care verifies symptoms and rhythm over time and integrates acute stability, alternative causes, reversible context, patient goals, and evolving evidence.',
    briefIn: ['symptomatic-sinus-bradycardia-reassessment'],
  },
  {
    id: 'symptomatic-sinus-bradycardia-controls-record-review-referral-and-handoff-only',
    headline: 'The controls record stability, two parallel review lanes, shared pacing evaluation, and handoff; they do not deliver care.',
    simplification: 'Five clicks stand in for history, examination, diagnostic review, counseling, shared decisions, communication, and follow-up.',
    whereItMisleads: 'Equating button order with examination, ECG or monitor interpretation, medication management, counseling quality, device selection, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified assessment, verified longitudinal evidence, individualized reversible-cause work, shared decisions, and repeated follow-up.',
    briefIn: ['symptomatic-sinus-bradycardia-reassessment'],
  },
  {
    id: 'no-live-bradycardia-diagnosis-medication-change-pacing-procedure-or-outcome',
    headline: 'The lab does not diagnose sinus-node dysfunction, change medication, pace, choose or implant a device, or predict outcome.',
    simplification: 'No live exam, ECG, monitor, test, medication change, oxygen, atropine, infusion, pacing, device, procedure, disposition, recurrence, prognosis, benefit, or outcome is modeled.',
    whereItMisleads: 'Using one rate or pause cutoff, stopping necessary therapy, treating chronic symptoms as acute compromise, or applying this SND pathway to high-grade AV block.',
    correctUnderstanding: 'Use current specialty and acute-care guidance, qualified judgment, patient preferences, and explicit pathway switching for real bradycardia.',
    briefIn: ['symptomatic-sinus-bradycardia-reassessment'],
  },
  {
    id: 'complete-heart-block-rhythm-stability-and-context-are-authored',
    headline: 'The complete AV block, escape rhythm, pulse, stability, symptoms, and initial cause panel are authored teaching facts.',
    simplification: 'One urgent rhythm-unit record supplies a fixed diagnostic ECG description, physiology, history, and initial reversible and structural context.',
    whereItMisleads: 'Treating the teaching waveform as a diagnostic ECG, confusing atrial rate with the perfusing ventricular rate, or reading current stability as low risk.',
    correctUnderstanding: 'Real care verifies rhythm, pulse, perfusion, evolving compromise, acquired and reversible context, and pacing needs with qualified teams and real data.',
    briefIn: ['complete-heart-block'],
  },
  {
    id: 'complete-heart-block-controls-record-review-escalation-and-handoff-only',
    headline: 'The controls record review, pacing-capable escalation, elapsed reassessment, and definitive evaluation handoff; they do not deliver care.',
    simplification: 'Five clicks stand in for assessment, continuous monitoring, access and rescue readiness, consultation, shared decisions, communication, and handoff.',
    whereItMisleads: 'Equating button order with examination, ECG interpretation, pad placement, pacing, capture assessment, counseling quality, transfer, or cardiology competence.',
    correctUnderstanding: 'Actual care requires verified findings, qualified teams, immediate pathway switching when compromise develops, and patient-specific temporary and permanent pacing decisions.',
    briefIn: ['complete-heart-block'],
  },
  {
    id: 'no-live-heart-block-diagnosis-treatment-pacing-capture-device-or-outcome',
    headline: 'The lab does not diagnose cause, deliver treatment, pace, assess capture, choose or implant a device, or predict outcome.',
    simplification: 'No live exam, test acquisition or interpretation, oxygen, drug, infusion, pacing setting, sedation, temporary or permanent device, procedure, disposition, prognosis, benefit, or outcome is modeled.',
    whereItMisleads: 'Using rate alone, delaying escalation for atropine or a complete cause panel, inferring capture from monitor complexes, or copying fictional device choices.',
    correctUnderstanding: 'Use current specialty and acute-care guidance, local resources, qualified judgment, shared decisions, and explicit rescue and arrest pathway switching.',
    briefIn: ['complete-heart-block'],
  },
  {
    id: 'torsades-rhythm-pulse-long-qt-context-and-response-are-authored',
    headline: 'The torsades pattern, weak pulse, prolonged-QT context, compromise, and post-team sinus report are authored teaching facts.',
    simplification: 'One monitored-unit record supplies fixed pre-event ECG, rhythm, physiology, laboratory, medication, kidney, and response snapshots.',
    whereItMisleads: 'Treating the teaching waveform as a diagnostic ECG, measuring QT during polymorphic VT, or reading the authored sinus report as proof of cure or one cause.',
    correctUnderstanding: 'Real care verifies pulse and perfusion immediately, uses real ECG and monitoring, treats sustained polymorphic VT as electrically unstable, and reassesses continuously.',
    briefIn: ['torsades-de-pointes'],
  },
  {
    id: 'torsades-controls-record-rescue-prevention-and-handoff-intent-only',
    headline: 'The controls record unsynchronized-shock intent, later review, long-QT recurrence prevention, and handoff; they do not deliver care.',
    simplification: 'Six clicks stand in for emergency assessment, team activation, defibrillation, monitoring, treatment, consultation, communication, and handoff.',
    whereItMisleads: 'Equating button order with pulse or ECG interpretation, shock delivery, magnesium administration, electrolyte correction, pacing, or cardiology competence.',
    correctUnderstanding: 'Actual care requires qualified teams, immediate unsynchronized shock for sustained polymorphic VT, cause-specific treatment, and explicit arrest-pathway switching if the pulse is lost.',
    briefIn: ['torsades-de-pointes'],
  },
  {
    id: 'no-live-torsades-diagnosis-shock-medication-pacing-device-or-outcome',
    headline: 'The lab does not diagnose cause, choose energy, shock, medicate, correct electrolytes, pace, operate a device, or predict outcome.',
    simplification: 'No live exam, test acquisition or interpretation, oxygen, CPR, shock, drug, infusion, electrolyte, pacing, capture, device, procedure, disposition, recurrence, prognosis, benefit, or outcome is modeled.',
    whereItMisleads: 'Delaying shock for magnesium or a checklist, synchronizing polymorphic VT, generalizing magnesium to normal-QT polymorphic VT, or copying fictional values.',
    correctUnderstanding: 'Use current resuscitation guidance, local protocols, verified patient data, qualified judgment, toxicology or electrophysiology expertise, and continuous reassessment.',
    briefIn: ['torsades-de-pointes'],
  },
  {
    id: 'hyperkalemic-conduction-record-treatment-and-response-are-authored',
    headline: 'The pretreatment chemistry and rhythm, reported emergency care, and serial response are authored teaching facts.',
    simplification: 'One post-emergency record supplies fixed potassium, ECG, glucose, prior-care, and current-stability snapshots.',
    whereItMisleads: 'Treating the teaching waveform as diagnostic, assuming one potassium value proves cause, or reading conduction improvement as potassium removal.',
    correctUnderstanding: 'Real care verifies treatment delivery, serial ECG and laboratory findings, pulse and perfusion, glucose, rebound, and alternative causes with qualified teams.',
    briefIn: ['hyperkalemic-conduction-disturbance'],
  },
  {
    id: 'hyperkalemic-conduction-controls-record-review-restraint-and-handoff-only',
    headline: 'The controls record serial review, device restraint, and handoff; they do not deliver treatment or make device decisions.',
    simplification: 'Six clicks stand in for longitudinal record review, consultation, multidisciplinary care, communication, and handoff.',
    whereItMisleads: 'Equating button order with examination, ECG or laboratory interpretation, treatment delivery, pacing, device eligibility, or cardiology competence.',
    correctUnderstanding: 'Actual care uses verified data, qualified teams, current local protocols, continuous monitoring, and patient-specific pacing and device judgment.',
    briefIn: ['hyperkalemic-conduction-disturbance'],
  },
  {
    id: 'no-live-hyperkalemia-treatment-kinetics-pacing-device-or-outcome',
    headline: 'The lab does not model live treatment, potassium or glucose kinetics, pacing, a device, or outcome.',
    simplification: 'No live exam, specimen, ECG, laboratory, drug, dialysis, pacing, capture, device, disposition, prognosis, benefit, or outcome is modeled.',
    whereItMisleads: 'Inferring that calcium lowers potassium, temporary shifting removes potassium, ECG normalization resolves the disturbance, or a reversible state establishes a permanent-device indication.',
    correctUnderstanding: 'Use current protocols, serial verified findings, qualified judgment, and explicit reassessment of reversible and persistent conduction disturbance.',
    briefIn: ['hyperkalemic-conduction-disturbance'],
  },
  {
    id: 'pericardial-tamponade-findings-and-response-are-authored',
    headline: 'The pretreatment tamponade findings, reported drainage, and serial response are fixed teaching facts.',
    simplification: 'One record supplies fixed symptoms, perfusion, pressure, examination claims, echo findings, prior drainage, catheter output, and short-interval reassessment without acquiring any of them.',
    whereItMisleads: 'Treating one sign, effusion size, echo finding, drainage volume, or directional response as a universal diagnostic rule or proof of imaging competence, procedure success, or cure.',
    correctUnderstanding: 'Real tamponade is a clinical diagnosis integrating the patient trajectory with verified findings and imaging; response and risk vary with etiology, accumulation, physiology, and treatment.',
    briefIn: ['pericardial-tamponade'],
  },
  {
    id: 'pericardial-tamponade-drainage-is-prior-care',
    headline: 'Pericardiocentesis and catheter care are reported prior care, not learner-delivered procedures.',
    simplification: 'Controls review a fixed prior-care report and surveillance plan without selecting an approach, handling equipment, draining fluid, manipulating a catheter, assessing technical success, or applying a removal threshold.',
    whereItMisleads: 'Equating button order with pericardiocentesis, catheter-management, complication-recognition, imaging-guidance, or procedural competence.',
    correctUnderstanding: 'Drainage and catheter decisions require experienced operators, verified imaging and physiology, appropriate equipment, local protocols, and supervised procedural training.',
    briefIn: ['pericardial-tamponade'],
  },
  {
    id: 'pericardial-tamponade-etiology-and-recurrence-remain-open',
    headline: 'Active cancer, serosanguineous fluid, improvement, and one stable interval do not prove etiology or freedom from recurrence.',
    simplification: 'Selected fluid studies remain pending, alternate causes stay open, and the case ends after one fixed short-interval reassessment without a durable recurrence trajectory.',
    whereItMisleads: 'Labeling the effusion malignant or idiopathic from context or appearance, treating improvement as cure, or using the fictional interval to predict recurrence or prognosis.',
    correctUnderstanding: 'Etiology-directed testing, serial clinical and imaging reassessment, complication surveillance, and patient-specific follow-up remain necessary after drainage.',
    briefIn: ['pericardial-tamponade'],
  },
  {
    id: 'no-pericardial-testing-procedure-treatment-disposition-prognosis-or-outcome',
    headline: 'The lab does not diagnose cause, acquire tests, perform drainage, deliver treatment, manage a catheter, determine disposition, or predict outcome.',
    simplification: 'No live examination, ECG, monitoring, imaging, sampling, fluid or drug delivery, pericardiocentesis, surgery, catheter action, complication management, disposition, prognosis, recurrence, or outcome is modeled.',
    whereItMisleads: 'Using completion as evidence of diagnostic, imaging, procedural, catheter-care, treatment, oncology, disposition, or prognostic competence.',
    correctUnderstanding: 'Use current specialty guidance, verified patient data, qualified multidisciplinary judgment, local pathways, explicit deterioration triggers, and continued reassessment.',
    briefIn: ['pericardial-tamponade'],
  },
  {
    id: 'right-ventricular-infarction-findings-are-authored',
    headline: 'The right-sided ECG, echo, pressure, perfusion, rhythm, congestion, and later findings are authored reports.',
    simplification: 'One fixed record stands in for serial history, examination, ECG, imaging, monitoring, laboratory review, and team communication.',
    whereItMisleads: 'Treating V4R, clear lungs, JVP, one pressure, or one echo snapshot as universal diagnostic proof, a fluid target, or evidence of acquired interpretation skill.',
    correctUnderstanding: 'Real RV-infarction assessment integrates acute ischemia, whole-patient perfusion and congestion, serial verified ECG and imaging, dangerous alternatives, and current reperfusion pathways.',
    briefIn: ['right-ventricular-infarction'],
  },
  {
    id: 'right-ventricular-infarction-controls-record-review-and-handoff-only',
    headline: 'The controls record review, guardrails, reperfusion readiness, and handoff; they do not deliver care.',
    simplification: 'Five clicks stand in for multidisciplinary acute coronary care, repeated assessment, treatment selection, monitoring, consultation, and handoff.',
    whereItMisleads: 'Equating button order with ECG or echo interpretation, medication judgment, fluid responsiveness, PCI, rhythm rescue, or treatment competence.',
    correctUnderstanding: 'Actual care requires qualified teams, verified findings, continuous reassessment, patient-specific hemodynamic decisions, and uninterrupted time-sensitive reperfusion work.',
    briefIn: ['right-ventricular-infarction'],
  },
  {
    id: 'no-live-right-ventricular-infarction-testing-treatment-reperfusion-or-outcome',
    headline: 'The lab does not acquire tests, deliver fluid or medication, perform reperfusion, select a device, or predict outcome.',
    simplification: 'No live examination, ECG, imaging, laboratory, catheter, fluid, nitrate, diuretic, vasoactive, antithrombotic, oxygen, PCI, pacing, device, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using completion as evidence of diagnostic, imaging, prescribing, fluid-management, reperfusion, device, rescue, disposition, or prognostic competence.',
    correctUnderstanding: 'Use current acute-coronary guidance, local protocols, verified patient data, qualified multidisciplinary judgment, and explicit rhythm, conduction, shock, mechanical, and pulse-loss rescue pathways.',
    briefIn: ['right-ventricular-infarction'],
  },
  {
    id: 'hypertensive-emergency-findings-and-panels-are-authored',
    headline: 'The pressure, measurement conditions, examination, fundoscopy, laboratory, ECG, echo, and later panels are authored teaching facts.',
    simplification: 'One fixed record stands in for repeated measurement, serial history and examination, monitoring, fundoscopy, specimen collection, ECG, imaging, and team communication.',
    whereItMisleads: 'Treating marked pressure alone as emergency, interpreting a fictional test as a learned skill, or treating the 45-minute and 3-hour snapshots as a universal response trajectory.',
    correctUnderstanding: 'Real hypertensive emergency requires verified measurement plus acute target-organ damage, current syndrome assessment, qualified teams, and serial patient-specific reassessment.',
    briefIn: ['hypertensive-emergency'],
  },
  {
    id: 'hypertensive-emergency-controls-record-review-and-intent-only',
    headline: 'The controls record review, controlled-reduction intent, elapsed panels, and handoff; they do not deliver care.',
    simplification: 'Six clicks stand in for monitored acute care, repeated assessment, treatment selection and titration, specialty consultation, communication, and handoff.',
    whereItMisleads: 'Equating button order with examination, diagnosis, prescribing, pressure targets, treatment delivery, monitoring, or emergency-care competence.',
    correctUnderstanding: 'Actual care uses the current organ-injury syndrome, verified patient data, local protocols, qualified judgment, appropriate monitoring, and explicit deterioration pathways.',
    briefIn: ['hypertensive-emergency'],
  },
  {
    id: 'no-live-hypertensive-emergency-testing-treatment-procedure-disposition-or-outcome',
    headline: 'The lab does not acquire tests, select or deliver treatment, perform a procedure, determine disposition, or predict outcome.',
    simplification: 'No live examination, pressure measurement, monitoring, ECG, fundoscopy, laboratory, imaging, drug, dose, infusion, oxygen, fluid, ventilation, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as a drug or target recipe, rapidly normalizing pressure, or using completion as evidence of diagnostic, prescribing, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use current guidance, syndrome-specific pathways, verified measurements and organ findings, qualified multidisciplinary judgment, local treatment protocols, and continuous reassessment.',
    briefIn: ['hypertensive-emergency'],
  },
  {
    id: 'pacemaker-capture-failure-findings-are-authored',
    headline: 'The pulse, perfusion, ECG, device-system, cause, and later-capture findings are authored teaching reports.',
    simplification: 'One fixed record stands in for examination, pulse confirmation, ECG and monitoring review, device interrogation, imaging, laboratory testing, and team communication.',
    whereItMisleads: 'Treating pacing artifacts as proof of capture, one output, threshold, impedance, or pacing percentage as a universal cutoff, or the later report as proof of a durable repair.',
    correctUnderstanding: 'Real capture assessment joins electrical activity to pulse or arterial waveform, patient perfusion, device-specific interrogation, serial trends, likely dependency, reversible causes, and expert reassessment.',
    briefIn: ['pacemaker-capture-failure'],
  },
  {
    id: 'pacemaker-capture-failure-controls-record-review-and-handoff-only',
    headline: 'The controls record recognition, rescue activation, authored review, elapsed reassessment, and handoff; they do not operate a device.',
    simplification: 'Six clicks stand in for acute bradycardia rescue, device and electrophysiology teamwork, interrogation, cause review, temporary stabilization, and definitive planning.',
    whereItMisleads: 'Equating button order with pulse assessment, capture testing, device interrogation or programming, backup pacing, lead management, or emergency-care competence.',
    correctUnderstanding: 'Actual care requires immediate perfusion support, qualified device expertise, manufacturer- and lead-specific data, backup pacing capability, continuous capture confirmation, and patient-specific definitive planning.',
    briefIn: ['pacemaker-capture-failure'],
  },
  {
    id: 'no-live-pacemaker-capture-testing-programming-pacing-procedure-or-outcome',
    headline: 'The lab does not test capture, interrogate or program a device, deliver pacing, manipulate a lead, perform a procedure, or predict outcome.',
    simplification: 'No live examination, pulse palpation, ECG, monitoring, imaging, laboratory, interrogation, magnet use, output or mode selection, transcutaneous or transvenous pacing, drug, lead revision or extraction, generator replacement, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying fictional settings as a recipe or using completion as evidence of diagnostic, resuscitation, device, programming, procedural, lead-management, disposition, or prognostic competence.',
    correctUnderstanding: 'Use current resuscitation and pacing guidance, verified mechanical capture, device-specific expertise, local rescue pathways, continuous reassessment, and shared definitive lead and system decisions.',
    briefIn: ['pacemaker-capture-failure'],
  },
  {
    id: 'transcutaneous-pacing-capture-and-perfusion-findings-are-authored',
    headline: 'The bradycardia, paced complexes, pulse-loss, waveform, pressure, and perfusion findings are authored teaching reports.',
    simplification: 'One fixed record stands in for repeated examination, pulse checks, ECG and waveform review, pressure measurement, device assessment, and team communication.',
    whereItMisleads: 'Treating pacing artifacts or paced QRS complexes as proof of circulation, treating the fixed pattern as a reusable diagnostic rule, or treating the handoff as a reported recovery.',
    correctUnderstanding: 'Effective capture requires verified mechanical circulation using pulse or arterial waveform and whole-patient perfusion; a pulseless patient needs uninterrupted guideline-based arrest care.',
    briefIn: ['transcutaneous-pacing-mechanical-capture-reassessment'],
  },
  {
    id: 'transcutaneous-pacing-controls-record-recognition-review-and-handoff-only',
    headline: 'The controls record recognition, pathway activation, open-cause and bridge review, and handoff; they do not deliver resuscitation or pacing.',
    simplification: 'Four clicks stand in for immediate nonshockable-arrest teamwork, cause review, future pacing planning, communication, and elapsed handoff.',
    whereItMisleads: 'Equating button order with pulse assessment, ECG interpretation, device operation, pacing, CPR, medication, procedure, or resuscitation competence.',
    correctUnderstanding: 'Actual care requires qualified teams, continuous high-quality resuscitation, verified circulation, reversible-cause treatment, device-specific expertise, and local protocols.',
    briefIn: ['transcutaneous-pacing-mechanical-capture-reassessment'],
  },
  {
    id: 'no-live-transcutaneous-pacing-arrest-treatment-procedure-disposition-or-outcome',
    headline: 'The lab does not assess capture, operate a pacer, deliver arrest care, perform a procedure, determine disposition, or predict outcome.',
    simplification: 'No examination, pulse palpation, ECG or waveform interpretation, pad placement, setting selection, pacing, CPR mechanics, drug, dose, sedation, access, procedure, return of circulation, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as a recipe or using completion as evidence of capture assessment, pacing, resuscitation, prescribing, procedural, disposition, or prognostic competence.',
    correctUnderstanding: 'Use current resuscitation and bradycardia guidance, device instructions, verified mechanical capture, qualified pacing and arrest teams, continuous reassessment, and patient-specific definitive planning.',
    briefIn: ['transcutaneous-pacing-mechanical-capture-reassessment'],
  },
];
