/**
 * The critical-care module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a critical-care scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const CRITICAL_CARE_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'pulse-oximeter-artifact-display-and-corroboration-are-authored',
    headline: 'The false 82% display, poor pleth, pulse mismatch, arterial panel, and clean-site response are fixed teaching facts, not device predictions.',
    simplification: 'One declared motion and low-local-perfusion state produces a fixed false 82% '
      + 'display, pulse-rate mismatch, and noisy low-amplitude pleth while canonical oxygenation '
      + 'remains stable. Real devices filter, delay, alarm, fail, and recover differently.',
    whereItMisleads: 'Predicting how far or how fast a particular monitor will drift, or treating '
      + 'a similar discordance as proof that the reading is artifact.',
    correctUnderstanding: 'Judge the whole patient, signal quality, pulse-rate coherence, probe '
      + 'site and perfusion, trend, and independent oxygenation evidence. Support an unstable '
      + 'patient while checking the signal, and keep true hypoxemia and other limitations open.',
    briefIn: ['pulse-oximeter-motion-artifact'],
  },
  {
    id: 'pulse-oximeter-controls-record-review-intent-only',
    headline: 'Pulse-oximeter controls reveal authored observations; they do not inspect, reposition, or validate a real probe or monitor.',
    simplification: 'Button presses reveal fixed pleth, pulse-rate, probe-site, perfusion, patient, '
      + 'arterial-panel, and reassessment facts without any physical action or device interaction.',
    whereItMisleads: 'Using completion as evidence of probe-placement, perfusion-assessment, blood '
      + 'sampling, monitor-configuration, or troubleshooting skill.',
    correctUnderstanding: 'Those are physical and local-device competencies requiring supervised '
      + 'practice, applicable instructions, and real equipment.',
    briefIn: ['pulse-oximeter-motion-artifact'],
  },
  {
    id: 'no-live-probe-assessment-arterial-sampling-diagnosis-treatment-or-outcome',
    headline: 'The case does not examine the patient, sample blood, diagnose artifact or hypoxemia, deliver care, or predict outcome.',
    simplification: 'All observations, arterial values, and the clean-site response are authored '
      + 'proxies. No oxygen, treatment, escalation, or monitor action occurs.',
    whereItMisleads: 'Reading the fixed arterial panel as a performed test, the improved display as '
      + 'proof of diagnosis, or the stable patient as permission to delay support in real instability.',
    correctUnderstanding: 'Clinical assessment, support, testing, diagnosis, treatment, and '
      + 'reassessment occur in parallel according to the patient and local systems.',
    briefIn: ['pulse-oximeter-motion-artifact'],
  },
  {
    id: 'ards-findings-settings-and-response-are-authored',
    headline: 'The ARDS context, gases, pressures, synchrony, circulation, settings, and response are authored facts, not measurements or predictions.',
    simplification: 'One fixed adult moves from a high plateau-pressure pattern to fixed protective-setting and reassessment panels.',
    whereItMisleads: 'Treating the screen as diagnosis, blood-gas sampling, ventilator measurement, mechanics, or individualized response prediction.',
    correctUnderstanding: 'Real ARDS care requires verified airway and ventilator data, serial whole-patient assessment, and individualized multidisciplinary management.',
    briefIn: ['ards-lung-protective-ventilation'],
  },
  {
    id: 'ards-ventilator-reassessment-peep-and-prone-controls-are-proxies',
    headline: 'Ventilator, reassessment, PEEP, oxygen, and prone buttons record intents; they do not perform ICU care.',
    simplification: 'The interface enforces an evidence-based sequence without programming equipment, measuring pressure, titrating support, or turning a patient.',
    whereItMisleads: 'Equating ordered controls with respiratory-therapy, ventilator, sedation, paralysis, proning, monitoring, or team competence.',
    correctUnderstanding: 'Use trained teams, verified equipment, current protocols, serial gas and mechanics review, and explicit device and hemodynamic safeguards.',
    briefIn: ['ards-lung-protective-ventilation'],
  },
  {
    id: 'no-live-ards-diagnosis-ventilator-management-proning-procedure-or-outcome',
    headline: 'The case does not diagnose ARDS, manage a ventilator, prone, perform procedures, select ECMO, or predict outcome.',
    simplification: 'Alternate lung and cardiac disease, dead space, auto-PEEP, chest-wall effects, contraindications, sedation, paralysis, fluids, and liberation are absent.',
    whereItMisleads: 'Using actual weight for tidal volume, normalizing gas values at the expense of protection, or treating a prone control as procedural skill.',
    correctUnderstanding: 'Base tidal volume on predicted body weight, limit inspiratory pressure, reassess the whole patient, and escalate with trained ICU teams.',
    briefIn: ['ards-lung-protective-ventilation'],
  },
  {
    id: 'escalating-hypoxemia-findings-and-response-are-authored',
    headline: 'The saturation trend, gas, equipment, airway, chest, pressure, circulation, and response panels are authored facts.',
    simplification: 'One fixed ventilated adult progresses through a reproducible decline, structured bedside panel, and 15-minute reassessment.',
    whereItMisleads: 'Treating the screen as signal validation, examination, measurement, diagnosis, or an individualized response prediction.',
    correctUnderstanding: 'Real deterioration requires immediate support, verified signals and equipment, direct examination, serial data, and expert reassessment.',
    briefIn: ['escalating-hypoxemia'],
  },
  {
    id: 'escalating-hypoxemia-equipment-airway-and-examination-controls-are-proxies',
    headline: 'Source, circuit, capnography, tube, suction-path, chest, and support buttons record intents; they do not perform ICU care.',
    simplification: 'The interface enforces an outside-in reasoning sequence without touching equipment, passing a catheter, examining the chest, or delivering oxygen.',
    whereItMisleads: 'Equating ordered buttons with respiratory-therapy, airway, ventilator, examination, troubleshooting, rescue, or team competence.',
    correctUnderstanding: 'Use trained teams, continuous monitoring, verified backup oxygenation, equipment-specific checks, and direct airway and chest assessment.',
    briefIn: ['escalating-hypoxemia'],
  },
  {
    id: 'no-live-hypoxemia-diagnosis-ventilator-management-procedure-or-outcome',
    headline: 'The case does not diagnose hypoxemia, manage a ventilator, perform rescue procedures, or predict outcome.',
    simplification: 'Tube and circuit intermittency, pneumothorax, embolism, edema, atelectasis, infection, bronchospasm, shunt severity, recruitment, and advanced rescue remain unresolved.',
    whereItMisleads: 'Assuming a passed check excludes danger, copying the fixed response, or delaying imaging, direct reassessment, or escalation.',
    correctUnderstanding: 'Support oxygenation, search systematically, keep dangerous alternatives open, obtain indicated tests, and individualize support with the ICU team.',
    briefIn: ['escalating-hypoxemia'],
  },
  {
    id: 'dyssynchrony-patient-graphics-drivers-and-response-are-authored',
    headline: 'The effort, graphics, mechanics, driver, classification, and response panels are authored facts.',
    simplification: 'One fixed adult has a reproducible flow-starvation and premature-cycling pattern with double triggering and a fixed 10-minute response.',
    whereItMisleads: 'Treating the screen as physical assessment, waveform acquisition, phenotype diagnosis, or individualized response prediction.',
    correctUnderstanding: 'Real dyssynchrony requires direct patient assessment, ventilator graphics and mechanics, airway and equipment checks, and serial expert interpretation.',
    briefIn: ['ventilator-dyssynchrony'],
  },
  {
    id: 'dyssynchrony-waveform-ventilator-and-analgesia-controls-are-proxies',
    headline: 'Patient, waveform, driver, analgesia, flow, cycling, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface enforces a reasoning sequence without examining the patient, acquiring graphics, programming a ventilator, or delivering analgesia.',
    whereItMisleads: 'Equating ordered controls with respiratory-therapy, waveform, ventilator, airway, pain, sedation, prescribing, or team competence.',
    correctUnderstanding: 'Use trained bedside teams, validated assessment, equipment-specific graphics and mechanics, cause-directed care, and explicit lung-protection safeguards.',
    briefIn: ['ventilator-dyssynchrony'],
  },
  {
    id: 'no-live-dyssynchrony-diagnosis-ventilator-prescribing-procedure-or-outcome',
    headline: 'The case does not diagnose dyssynchrony, prescribe drugs, program a ventilator, perform procedures, or predict outcome.',
    simplification: 'Trigger, cycling, reverse-trigger, ineffective-effort, auto-PEEP, obstructive, neurologic, metabolic, airway, device, sedation, and disease phenotypes are incomplete.',
    whereItMisleads: 'Assuming one graphic proves a mechanism, copying an adjustment, or using deep sedation or paralysis as a generic waveform treatment.',
    correctUnderstanding: 'Name the phase and likely mechanism, treat reversible drivers, preserve lung protection, adjust support with the ICU team, and reassess the patient and delivered breath.',
    briefIn: ['ventilator-dyssynchrony'],
  },
  {
    id: 'auto-peep-flow-mechanics-and-response-are-authored',
    headline: 'The flow, timing, pressure, hold, gas, circulation, and response panels are authored facts.',
    simplification: 'One fixed adult has reproducible obstructive dynamic hyperinflation, a valid passive hold, and a fixed 10-minute response.',
    whereItMisleads: 'Treating the screen as physical assessment, waveform or mechanics acquisition, diagnosis, or individualized response prediction.',
    correctUnderstanding: 'Real auto-PEEP assessment combines the patient, real-time graphics, valid mechanics, airway and equipment checks, gas exchange, and serial hemodynamics.',
    briefIn: ['auto-peep'],
  },
  {
    id: 'auto-peep-expiratory-hold-airway-and-ventilator-controls-are-proxies',
    headline: 'Flow review, expiratory hold, obstruction treatment, ventilator adjustment, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface enforces a reasoning sequence without examining the patient, acquiring a waveform, occluding flow, manipulating equipment, or delivering treatment.',
    whereItMisleads: 'Equating ordered controls with respiratory-therapy, mechanics, airway, ventilator, prescribing, procedural, or team competence.',
    correctUnderstanding: 'Use trained bedside teams, equipment-specific graphics and mechanics, valid passive measurements, cause-directed care, and immediate reassessment.',
    briefIn: ['auto-peep'],
  },
  {
    id: 'no-live-auto-peep-diagnosis-ventilator-prescribing-procedure-or-outcome',
    headline: 'The case does not diagnose auto-PEEP, prescribe drugs, program a ventilator, perform procedures, or predict outcome.',
    simplification: 'Heterogeneous time constants, airway closure, active effort, alternate obstruction, pneumothorax, equipment faults, emergencies, and external-PEEP responses are incomplete.',
    whereItMisleads: 'Assuming one graphic or hold proves the mechanism, copying fixed settings, or applying external PEEP without checking flow limitation and response.',
    correctUnderstanding: 'Treat the cause, preserve expiratory time and lung protection, individualize support with the ICU team, and recheck the patient, graphics, mechanics, gas, and circulation.',
    briefIn: ['auto-peep'],
  },
  {
    id: 'mucus-plugging-findings-clearance-and-response-are-authored',
    headline: 'The secretion, sounds, graphics, mechanics, clearance, imaging, and response panels are authored facts.',
    simplification: 'One fixed adult has convergent retained-secretion indicators, partial central-airway improvement, and a persistent focal concern.',
    whereItMisleads: 'Treating the screen as examination, equipment inspection, waveform acquisition, secretion removal, imaging, diagnosis, or response prediction.',
    correctUnderstanding: 'Real assessment combines the patient, artificial airway, circuit, graphics, mechanics, gas exchange, circulation, retrieved material, and serial findings.',
    briefIn: ['mucus-plugging'],
  },
  {
    id: 'mucus-plugging-suction-imaging-and-airway-controls-are-proxies',
    headline: 'Oxygen, suction, imaging, and airway-evaluation buttons record intents; they do not perform care.',
    simplification: 'The interface enforces indication and reassessment without preoxygenating, suctioning, removing secretions, imaging, or performing bronchoscopy.',
    whereItMisleads: 'Equating ordered controls with airway, suction, respiratory-therapy, imaging, bronchoscopy, procedural, or team competence.',
    correctUnderstanding: 'Use trained teams, indicated equipment-specific clearance, complication safeguards, and immediate whole-patient reassessment.',
    briefIn: ['mucus-plugging'],
  },
  {
    id: 'no-live-mucus-plugging-diagnosis-suction-bronchoscopy-or-outcome',
    headline: 'The case does not diagnose mucus plugging, teach suction or bronchoscopy, or predict outcome.',
    simplification: 'Tube migration or obstruction, pneumothorax, atelectasis, consolidation, blood, foreign body, peripheral secretions, recurrence, and complications are incomplete.',
    whereItMisleads: 'Assuming one sign proves a plug, copying a suction technique, using routine saline, or treating bronchoscopy as routine secretion removal.',
    correctUnderstanding: 'Support oxygenation, establish an indication, clear the artificial airway safely, prove the response, and escalate unresolved focal physiology.',
    briefIn: ['mucus-plugging'],
  },
  {
    id: 'unplanned-extubation-findings-failure-and-response-are-authored',
    headline: 'The unplanned event, tolerance findings, failure classification, airway response, and handoff are authored facts.',
    simplification: 'One fixed adult deteriorates after tube displacement and then improves on a reported post-reintubation panel.',
    whereItMisleads: 'Treating the screen as examination, gas sampling, monitoring acquisition, diagnosis, airway confirmation, investigation, or response prediction.',
    correctUnderstanding: 'Real assessment integrates airway protection, work, oxygenation, ventilation, neurologic state, secretions, circulation, trend, and goals of care.',
    briefIn: ['unplanned-extubation'],
  },
  {
    id: 'unplanned-extubation-oxygen-airway-and-confirmation-controls-are-proxies',
    headline: 'Oxygenation, help, reintubation, and confirmation buttons record intents; they do not perform care.',
    simplification: 'The interface enforces an ordered cognitive response without delivering oxygen, ventilating, selecting drugs or equipment, intubating, or confirming placement.',
    whereItMisleads: 'Equating button order with airway, respiratory-therapy, critical-care, team, equipment, or procedural competence.',
    correctUnderstanding: 'Use trained teams, local emergency-airway systems, preoxygenation, hemodynamic preparation, backup planning, placement confirmation, and serial reassessment.',
    briefIn: ['unplanned-extubation'],
  },
  {
    id: 'no-live-unplanned-extubation-diagnosis-airway-procedure-or-outcome',
    headline: 'The case does not diagnose extubation failure, teach airway management, assign fault, or predict outcome.',
    simplification: 'Alternative tolerance trajectories, upper-airway obstruction, aspiration, arrest, difficult reintubation, NIV exceptions, goals-of-care limits, and complications are incomplete.',
    whereItMisleads: 'Automatically reintubating every event, delaying this failing airway with noninvasive support, copying an airway plan, or blaming one person.',
    correctUnderstanding: 'Support immediately, decide from the whole patient, act promptly when failure converges, prove the new airway, and learn from the system non-punitively.',
    briefIn: ['unplanned-extubation'],
  },
  {
    id: 'sbt-readiness-trial-failure-and-recovery-are-authored',
    headline: 'The readiness, trial, intolerance, recovery, and reversible-driver panels are authored facts.',
    simplification: 'One fixed adult appears ready for a trial, develops convergent intolerance at 30 minutes, and recovers after reported restoration of prior support.',
    whereItMisleads: 'Treating the screen as examination, monitoring acquisition, ventilator measurement, gas sampling, diagnosis, or response prediction.',
    correctUnderstanding: 'Real SBT assessment integrates the improving cause, patient, airway, breathing pattern, work, gas exchange, circulation, comfort, and trajectory.',
    briefIn: ['spontaneous-breathing-trial'],
  },
  {
    id: 'sbt-ventilator-assessment-and-support-controls-are-proxies',
    headline: 'Readiness, trial, support-restoration, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface enforces an ordered cognitive rehearsal without programming a ventilator, changing oxygen, measuring, treating, or extubating.',
    whereItMisleads: 'Equating button order with respiratory-therapy, ventilator, airway, liberation, assessment, or team competence.',
    correctUnderstanding: 'Use a standardized local protocol, trained teams, continuous observation, explicit stop criteria, safe support restoration, and serial reassessment.',
    briefIn: ['spontaneous-breathing-trial'],
  },
  {
    id: 'no-live-sbt-prescribing-extubation-or-outcome',
    headline: 'The case does not prescribe an SBT method, decide extubation, treat failure, or predict outcome.',
    simplification: 'Alternative trial methods, durations, thresholds, disease trajectories, airway risk, secretion burden, neurologic limits, goals of care, and post-extubation support are incomplete.',
    whereItMisleads: 'Requiring RSBI, increasing FiO₂ to mask intolerance, pushing through failure, copying one threshold, or treating SBT success as extubation permission.',
    correctUnderstanding: 'Standardize readiness and method locally, keep FiO₂ visible, stop when intolerance converges, correct contributors, repeat assessment, and make a separate extubation decision.',
    briefIn: ['spontaneous-breathing-trial'],
  },
  {
    id: 'post-intubation-hypotension-findings-mechanism-and-response-are-authored',
    headline: 'The pressure, perfusion, danger, dynamic-response, mechanism, and support panels are authored facts.',
    simplification: 'One fixed septic adult develops severe hypotension after intubation, appears fluid responsive, and improves after a bounded support proxy.',
    whereItMisleads: 'Treating the screen as examination, pressure acquisition, equipment inspection, ultrasound, passive leg raise, diagnosis, or response prediction.',
    correctUnderstanding: 'Real assessment integrates signal validity, perfusion, airway and ventilation, timing, drugs, preload, tone, pump, obstruction, bleeding, allergy, and serial response.',
    briefIn: ['post-intubation-hypotension'],
  },
  {
    id: 'post-intubation-hypotension-fluid-vasopressor-and-assessment-controls-are-proxies',
    headline: 'Help, dynamic assessment, fluid, vasopressor, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface enforces ordered reasoning without examining, performing a leg raise, choosing access or dose, administering fluid or drug, or changing ventilation.',
    whereItMisleads: 'Equating button order with hemodynamic, airway, respiratory-therapy, prescribing, procedural, equipment, or ICU competence.',
    correctUnderstanding: 'Use trained teams, immediate stabilization, cause-directed evaluation, individualized support, safe delivery systems, and frequent whole-patient reassessment.',
    briefIn: ['post-intubation-hypotension'],
  },
  {
    id: 'no-live-post-intubation-shock-diagnosis-prescribing-procedure-or-outcome',
    headline: 'The case does not diagnose shock, choose universal fluid or vasopressor therapy, perform procedures, or predict outcome.',
    simplification: 'Occult bleeding, pulmonary embolism, tension physiology, tamponade, pump failure, anaphylaxis, auto-PEEP, tube problems, drug effects, and septic trajectories are incomplete.',
    whereItMisleads: 'Assuming timing proves one cause, giving unbounded fluid, copying a vasopressor plan, or stopping alternate-cause review when pressure improves.',
    correctUnderstanding: 'Validate, stabilize, search rapidly, use dynamic and serial response to constrain support, and keep the underlying shock work open.',
    briefIn: ['post-intubation-hypotension'],
  },
  {
    id: 'cardiogenic-shock-findings-phenotype-and-response-are-authored',
    headline: 'The perfusion, ECG, echo, congestion, phenotype, and response panels are authored facts.',
    simplification: 'One fixed acute-MI patient has a congested LV-predominant shock pattern and a bounded early response.',
    whereItMisleads: 'Treating the screen as examination, monitoring, ECG or echo acquisition or interpretation, diagnosis, staging, or outcome prediction.',
    correctUnderstanding: 'Real shock care repeatedly integrates trajectory, perfusion, cause, ventricular phenotype, congestion, rhythm, invasive data when needed, and response.',
    briefIn: ['cardiogenic-shock'],
  },
  {
    id: 'cardiogenic-shock-support-and-revascularization-controls-are-proxies',
    headline: 'Team, support, revascularization, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface enforces ordered reasoning without delivering oxygen or drugs, choosing access or dose, catheterizing, revascularizing, transferring, or placing support.',
    whereItMisleads: 'Equating button order with cardiovascular, critical-care, prescribing, imaging, catheterization, revascularization, device, or transfer competence.',
    correctUnderstanding: 'Use multidisciplinary shock systems, safe delivery, prompt cause control, and frequent phenotype- and trajectory-linked reassessment.',
    briefIn: ['cardiogenic-shock'],
  },
  {
    id: 'no-live-cardiogenic-shock-diagnosis-prescribing-device-procedure-or-outcome',
    headline: 'The case does not diagnose cardiogenic shock, prescribe a universal support target, select a device, perform revascularization, or predict outcome.',
    simplification: 'Mechanical complications, evolving right-heart or mixed shock, arrhythmia, bleeding, infection, and other causes remain incomplete.',
    whereItMisleads: 'Copying the bridge, withholding all fluid in every phenotype, choosing a routine device, or stopping evaluation when pressure improves.',
    correctUnderstanding: 'Stabilize perfusion, identify and treat the cause promptly, reassess serially, and individualize hemodynamic and temporary support with expert teams.',
    briefIn: ['cardiogenic-shock'],
  },
  {
    id: 'mixed-shock-findings-hemodynamics-and-response-are-authored',
    headline: 'The perfusion, cardiac, infection, catheter, phenotype, and response panels are authored facts.',
    simplification: 'One fixed post-MI patient with pneumonia has low output, high filling pressure, low vascular resistance, and a bounded early response.',
    whereItMisleads: 'Treating the screen as examination, catheter placement, monitoring or test acquisition, calculation, diagnosis, staging, or outcome prediction.',
    correctUnderstanding: 'Real mixed-shock assessment repeatedly integrates cause, output, filling pressure, vascular tone, treatment context, congestion, perfusion, and organ trajectory.',
    briefIn: ['mixed-shock'],
  },
  {
    id: 'mixed-shock-support-and-cause-control-actions-are-proxies',
    headline: 'Team, support, cause-control, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface orders reasoning without delivering oxygen, fluid, or drugs, choosing access or dose, treating infection or ischemia, or placing support.',
    whereItMisleads: 'Equating button order with cardiac, critical-care, catheter, prescribing, infectious-disease, procedural, device, or transfer competence.',
    correctUnderstanding: 'Use multidisciplinary teams, safe delivery, parallel cause control, and frequent physiology- and trajectory-linked reassessment.',
    briefIn: ['mixed-shock'],
  },
  {
    id: 'right-ventricular-failure-findings-hemodynamics-and-response-are-authored',
    headline: 'The examination, echo, hemodynamics, and response are authored teaching facts.',
    simplification: 'One fixed pulmonary-hypertension patient has systemic congestion, low output, a pressure-loaded RV pattern, and a bounded early response.',
    whereItMisleads: 'Treating the screen as examination, monitoring, echo or catheter acquisition or interpretation, calculation, diagnosis, staging, or outcome prediction.',
    correctUnderstanding: 'Real RV-failure assessment repeatedly integrates cause, congestion, tissue perfusion, rhythm, oxygenation, RV and LV interaction, filling pressures, output, treatment context, and organ trajectory.',
    briefIn: ['right-ventricular-failure'],
  },
  {
    id: 'right-ventricular-failure-support-and-trigger-actions-are-proxies',
    headline: 'Team, support, trigger, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface orders reasoning without delivering oxygen, ventilation, fluid, diuresis, pulmonary-vascular therapy, vasopressors, inotropes, or trigger treatment.',
    whereItMisleads: 'Equating button order with pulmonary-hypertension, cardiac, critical-care, prescribing, imaging, catheter, procedural, device, or transfer competence.',
    correctUnderstanding: 'Actual support is individualized to cause and trajectory by experienced teams, with repeated assessment and no automatic fluid, decongestion, drug, target, or device rule.',
    briefIn: ['right-ventricular-failure'],
  },
  {
    id: 'no-live-right-ventricular-failure-diagnosis-prescribing-procedure-or-outcome',
    headline: 'The case does not diagnose RV failure, prescribe support, perform procedures, select mechanical support, or predict outcome.',
    simplification: 'The trigger search, disease-specific therapy, longitudinal congestion, and escalation pathway remain incomplete.',
    whereItMisleads: 'Copying the panel as cutoffs, applying the same preload plan to every patient, or stopping evaluation when pressure improves.',
    correctUnderstanding: 'Use current local protocols and pulmonary-hypertension, cardiac, shock, imaging, catheter, pharmacy, procedural, and device expertise for real care.',
    briefIn: ['right-ventricular-failure'],
  },
  {
    id: 'massive-pulmonary-embolism-findings-support-and-response-are-authored',
    headline: 'The PE, RV, shock, ventilation, support, and response panels are authored teaching facts.',
    simplification: 'One confirmed Category E2R patient has fixed refractory cardiopulmonary failure and a bounded post-bridge response.',
    whereItMisleads: 'Treating the screen as examination, monitoring, CT, echo, laboratory or hemodynamic acquisition or interpretation, diagnosis, staging, or outcome prediction.',
    correctUnderstanding: 'Real high-risk PE care repeatedly integrates confirmation, shock and respiratory severity, RV function, bleeding, perfusion, ventilation, organ trajectory, resources, and response.',
    briefIn: ['massive-pulmonary-embolism'],
  },
  {
    id: 'massive-pulmonary-embolism-ecmo-and-reperfusion-actions-are-proxies',
    headline: 'Support, ECMO, reperfusion, and reassessment buttons record intents; they do not perform rescue care.',
    simplification: 'The interface orders reasoning without delivering oxygen, ventilation, anticoagulation, fluid, or drugs, cannulating, initiating ECMO, or removing clot.',
    whereItMisleads: 'Equating button order with PERT, shock, perfusion, ECMO, prescribing, catheter, surgical, resuscitation, device, or transfer competence.',
    correctUnderstanding: 'VA-ECMO requires expert candidacy and safe systems, supports circulation and oxygenation rather than removing thrombus, and does not make adjunctive reperfusion automatically beneficial.',
    briefIn: ['massive-pulmonary-embolism'],
  },
  {
    id: 'no-live-massive-pulmonary-embolism-diagnosis-prescribing-device-or-outcome',
    headline: 'The case does not diagnose PE, prescribe therapy, perform CPR or procedures, manage ECMO, or predict outcome.',
    simplification: 'Bleeding, candidacy, cannulation, complications, longitudinal organ recovery, thrombus strategy, and disposition remain incomplete.',
    whereItMisleads: 'Copying the panel as universal thresholds, treating VA-ECMO as clot treatment, or assuming every supported patient needs the same adjunctive intervention.',
    correctUnderstanding: 'Use current protocols and multidisciplinary PE, shock, perfusion, ECMO, pharmacy, imaging, catheter, surgical, and resuscitation expertise for real care.',
    briefIn: ['massive-pulmonary-embolism'],
  },
  {
    id: 'upper-gi-hemorrhage-findings-and-response-are-authored',
    headline: 'The bleeding, perfusion, laboratory, airway, source, and response panels are authored teaching facts.',
    simplification: 'One recurrent nonvariceal ulcer bleed has a fixed ICU presentation and bounded post-bridge response.',
    whereItMisleads: 'Treating the screen as examination, monitoring, specimen or test acquisition or interpretation, diagnosis, hemostasis confirmation, or outcome prediction.',
    correctUnderstanding: 'Real upper-GI-bleed care repeatedly integrates active bleeding, airway, tissue perfusion, laboratory trend, comorbidity, medications, source, treatment, resources, and serial response.',
    briefIn: ['upper-gi-hemorrhage'],
  },
  {
    id: 'upper-gi-hemorrhage-resuscitation-and-hemostasis-actions-are-proxies',
    headline: 'Resuscitation, transfusion, endoscopy, embolization, surgery, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface orders reasoning without obtaining access or tests, delivering oxygen, fluid, blood products or drugs, managing an airway, or performing hemostasis.',
    whereItMisleads: 'Equating button order with hemorrhage, blood-bank, endoscopy, interventional-radiology, surgical, airway, prescribing, procedural, or transfer competence.',
    correctUnderstanding: 'Actual resuscitation and hemostasis are individualized to active bleeding, physiology, comorbidity, prior treatment, local protocols, resources, and repeated assessment.',
    briefIn: ['upper-gi-hemorrhage'],
  },
  {
    id: 'no-live-upper-gi-hemorrhage-diagnosis-transfusion-procedure-or-outcome',
    headline: 'The case does not diagnose GI bleeding, prescribe transfusion, manage an airway, perform procedures, or predict outcome.',
    simplification: 'Variceal disease, drug regimens, transfusion complications, procedural findings, recurrent bleeding, longitudinal organ recovery, and disposition remain incomplete.',
    whereItMisleads: 'Treating 7 g/dL as a universal trigger, assuming improved pressure proves hemostasis, or applying a nonvariceal pathway to suspected variceal bleeding.',
    correctUnderstanding: 'Use current local protocols and GI, critical-care, blood-bank, pharmacy, airway, interventional-radiology, and surgical expertise for real care.',
    briefIn: ['upper-gi-hemorrhage'],
  },
  {
    id: 'critical-care-status-epilepticus-findings-and-response-are-authored',
    headline: 'The EEG, neurologic, airway, ventilation, perfusion, laboratory, and response panels are authored teaching facts.',
    simplification: 'One refractory-status patient has fixed persistent electrographic seizures and a bounded post-pathway response.',
    whereItMisleads: 'Treating the screen as examination, monitoring or EEG acquisition or interpretation, diagnosis, seizure quantification, prognosis, or outcome prediction.',
    correctUnderstanding: 'Real refractory-status care repeatedly integrates clinical state, EEG, medication delivery, airway, ventilation, perfusion, temperature, organ function, cause, adverse effects, and serial response.',
    briefIn: [],
  },
  {
    id: 'critical-care-status-epilepticus-eeg-anesthetic-and-cause-actions-are-proxies',
    headline: 'EEG, continuous-anesthetic, organ-support, cause, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface orders reasoning without acquiring EEG, delivering oxygen, ventilation, fluid or drugs, managing an airway, or treating a cause.',
    whereItMisleads: 'Equating button order with neurocritical-care, epilepsy, EEG, pharmacy, airway, prescribing, procedural, imaging, or transfer competence.',
    correctUnderstanding: 'Actual therapy and monitoring are individualized to EEG, cause, physiology, organ function, adverse effects, local protocols, and expert reassessment.',
    briefIn: [],
  },
  {
    id: 'no-live-critical-care-status-epilepticus-diagnosis-prescribing-eeg-airway-or-outcome',
    headline: 'The case does not diagnose status, interpret EEG, prescribe therapy, manage an airway, perform procedures, or predict outcome.',
    simplification: 'Agent selection, dosing, EEG target, duration, weaning, recurrence, cause treatment, complications, recovery, and prognosis remain incomplete.',
    whereItMisleads: 'Assuming absent movement proves seizure control, applying one anesthetic or burst-suppression target universally, or treating a brief EEG response as durable recovery.',
    correctUnderstanding: 'Use current local protocols and neurocritical-care, epilepsy, EEG, pharmacy, airway, critical-care, imaging, infectious, immune, toxicology, and procedural expertise for real care.',
    briefIn: [],
  },
  {
    id: 'post-arrest-temperature-findings-and-response-are-authored',
    headline: 'The ROSC, neurologic, temperature, perfusion, ventilation, seizure, cause, and response panels are authored teaching facts.',
    simplification: 'One unresponsive post-arrest patient has a fixed febrile presentation and bounded temperature response.',
    whereItMisleads: 'Treating the screen as examination, monitoring, EEG, laboratory or imaging acquisition or interpretation, diagnosis, neuroprognostication, or outcome prediction.',
    correctUnderstanding: 'Real post-arrest care repeatedly integrates arrest context, cause, brain, temperature, airway, ventilation, perfusion, rhythm, seizures, organ function, treatment, and serial response.',
    briefIn: ['targeted-temperature-management'],
  },
  {
    id: 'post-arrest-temperature-control-and-guardrail-actions-are-proxies',
    headline: 'Temperature protocol, cooling, warming, shivering, organ-support, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface orders reasoning without measuring temperature, delivering oxygen, ventilation, fluid or drugs, or using a cooling or warming device.',
    whereItMisleads: 'Equating button order with post-arrest, temperature-device, nursing, pharmacy, airway, prescribing, procedural, or transfer competence.',
    correctUnderstanding: 'Actual temperature control is individualized within current guidance using local protocols, trained teams, continuous measurement, systemic guardrails, and repeated reassessment.',
    briefIn: ['targeted-temperature-management'],
  },
  {
    id: 'no-live-post-arrest-temperature-prescribing-device-prognosis-or-outcome',
    headline: 'The case does not prescribe a target, use a temperature device, manage shivering, prognosticate, or predict outcome.',
    simplification: 'Target selection, device, sedation, shivering therapy, complications, duration beyond 36 hours, rewarming, cause treatment, organ recovery, and prognosis remain incomplete.',
    whereItMisleads: 'Assuming 33°C or any other target is universally superior, using rapid cold-fluid loading, rewarming too quickly, or treating temperature response as neurologic recovery.',
    correctUnderstanding: 'Use current local protocols and post-arrest, cardiac, neurologic, nursing, pharmacy, airway, temperature-device, and prognostication expertise for real care.',
    briefIn: ['targeted-temperature-management'],
  },
  {
    id: 'intracranial-hypertension-findings-and-response-are-authored',
    headline: 'The ICP, CPP, examination, imaging, systemic, driver, and response panels are authored teaching facts.',
    simplification: 'One post-operative severe-TBI patient has a fixed monitored pressure pattern and bounded immediate response.',
    whereItMisleads: 'Treating the screen as examination, ICP waveform or other monitoring acquisition or interpretation, CPP calculation, imaging review, diagnosis, prognosis, or outcome prediction.',
    correctUnderstanding: 'Real intracranial-hypertension care repeatedly integrates monitor fidelity and trend, examination, imaging, injury, physiology, interventions, adverse effects, and serial response.',
    briefIn: ['intracranial-hypertension'],
  },
  {
    id: 'intracranial-hypertension-protection-and-rescue-actions-are-proxies',
    headline: 'Positioning, systemic protection, hyperosmolar rescue, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface orders reasoning without positioning the patient, acquiring monitoring, or delivering oxygen, ventilation, fluid, or drugs.',
    whereItMisleads: 'Equating button order with neurocritical-care, neurosurgical, nursing, respiratory, pharmacy, prescribing, procedural, imaging, or transfer competence.',
    correctUnderstanding: 'Actual care is individualized to injury, monitor validity, examination, imaging, autoregulation, physiology, response, local protocols, and expert reassessment.',
    briefIn: ['intracranial-hypertension'],
  },
  {
    id: 'no-live-icp-monitoring-hyperosmolar-prescribing-procedure-prognosis-or-outcome',
    headline: 'The case does not monitor ICP, prescribe osmotherapy, use a drain, image, operate, prognosticate, or predict outcome.',
    simplification: 'Threshold duration, CPP target, agent, concentration, dose, route, fluid strategy, later tiers, drain use, repeat imaging, surgery, recovery, and prognosis remain incomplete.',
    whereItMisleads: 'Treating 22 mmHg as an isolated automatic trigger, forcing CPP above 70, prescribing one hyperosmolar recipe universally, or equating immediate pressure response with recovery.',
    correctUnderstanding: 'Use current local protocols and neurocritical-care, neurosurgical, nursing, respiratory, pharmacy, imaging, procedural, and prognostication expertise for real care.',
    briefIn: ['intracranial-hypertension'],
  },
  {
    id: 'aki-fluid-overload-findings-and-response-are-authored',
    headline: 'The kidney, fluid, weight, respiratory, metabolic, cause, and response panels are authored teaching facts.',
    simplification: 'One severe-AKI patient has fixed harmful fluid accumulation, a poor reported diuretic response, and a bounded immediate trajectory.',
    whereItMisleads: 'Treating the screen as examination, monitoring, fluid accounting, laboratory or imaging acquisition or interpretation, diagnosis, kidney-recovery assessment, or outcome prediction.',
    correctUnderstanding: 'Real AKI care repeatedly integrates baseline and trend, urine, balance, weight, organ function, perfusion, electrolytes, acid-base state, symptoms, causes, treatment, goals, and serial response.',
    briefIn: ['acute-kidney-injury-with-fluid-overload'],
  },
  {
    id: 'aki-fluid-and-kidney-support-actions-are-proxies',
    headline: 'Fluid-limit, diuretic-review, kidney-support, and reassessment buttons record intents; they do not perform care.',
    simplification: 'The interface orders reasoning without measuring balance, changing intake, delivering diuretics, placing access, or providing kidney support.',
    whereItMisleads: 'Equating button order with critical-care, nephrology, nursing, respiratory, pharmacy, nutrition, prescribing, procedural, kidney-support, or transfer competence.',
    correctUnderstanding: 'Actual de-resuscitation and kidney support are individualized to demand, capacity, physiology, complications, recovery potential, preferences, resources, and repeated expert reassessment.',
    briefIn: ['acute-kidney-injury-with-fluid-overload'],
  },
  {
    id: 'no-live-aki-diagnosis-diuretic-kidney-support-prescribing-procedure-or-outcome',
    headline: 'The case does not diagnose AKI, prescribe diuretics, place access, deliver kidney support, determine recovery, or predict outcome.',
    simplification: 'Volume assessment, diuretic strategy, exact urgency, access, modality, dose, anticoagulation, fluid removal, medication clearance, nutrition, duration, recovery, and goals remain incomplete.',
    whereItMisleads: 'Starting support from one creatinine or BUN value, accelerating every severe AKI case, repeating diuretics blindly, or treating immediate negative balance as kidney recovery.',
    correctUnderstanding: 'Use current local protocols and critical-care, nephrology, nursing, respiratory, pharmacy, nutrition, procedural, and shared-decision expertise for real care.',
    briefIn: ['acute-kidney-injury-with-fluid-overload'],
  },
  {
    id: 'severe-acidemia-gas-causes-and-response-are-authored',
    headline: 'The blood gas, chemistry, compensation, causes, and response are authored teaching facts.',
    simplification: 'One septic-shock patient has a fixed repeated sample, mixed metabolic and respiratory acidemia, AKI, and bounded immediate trajectory.',
    whereItMisleads: 'Treating the screen as sample acquisition, validation, calculation, examination, monitoring, ECG, laboratory, acid-base or cause diagnosis, clearance assessment, or outcome prediction.',
    correctUnderstanding: 'Real acidemia care repeatedly confirms sampling and integrates pH, PaCO₂, bicarbonate, electrolytes, albumin, anion gap, lactate, ketones, perfusion, ventilation, kidney function, toxins, treatment, and serial response.',
    briefIn: ['severe-acidemia'],
  },
  {
    id: 'severe-acidemia-stabilization-actions-are-proxies',
    headline: 'Ventilation, cause, buffer, kidney-support, and reassessment buttons record reasoning; they do not perform care.',
    simplification: 'The interface orders a fixed response without assessing mechanics, setting a ventilator, restoring perfusion, controlling infection, or delivering fluid, drugs, antidotes, or kidney support.',
    whereItMisleads: 'Equating button order with airway, ventilation, critical-care, nursing, respiratory, pharmacy, nephrology, toxicology, procedural, or source-control competence.',
    correctUnderstanding: 'Actual stabilization balances safe ventilatory compensation, oxygen delivery, perfusion, cause control, electrolytes, fluid burden, buffer risks, kidney capacity, and repeated expert reassessment.',
    briefIn: ['severe-acidemia'],
  },
  {
    id: 'no-live-acid-base-diagnosis-ventilation-buffer-kidney-support-prescribing-or-outcome',
    headline: 'The case does not diagnose acid-base disease, set ventilation, prescribe buffer, deliver kidney support, or predict outcome.',
    simplification: 'Sampling, formulas, ventilation, fluid and vasoactive care, bicarbonate formulation and delivery, electrolyte and toxin treatment, access, kidney-support prescription, source control, and recovery remain incomplete.',
    whereItMisleads: 'Using one pH as a diagnosis, universal bicarbonate or kidney-support trigger, normal-pH ventilation target, hemodynamic promise, or mortality claim.',
    correctUnderstanding: 'Use current local protocols and critical-care, respiratory, nursing, pharmacy, nephrology, toxicology, infectious-disease, procedural, and shared-decision expertise for real care.',
    briefIn: ['severe-acidemia'],
  },
  {
    id: 'icu-hidden-deterioration-handoff-content-and-response-are-authored',
    headline: 'The outgoing summary, bedside trends, hidden deterioration, and response are authored teaching facts.',
    simplification: 'One shift-change case uses fixed content and a fixed worsening-shock trajectory that contradicts the word stable.',
    whereItMisleads: 'Treating the screen as patient identification, examination, monitoring, trend acquisition, device or infusion verification, laboratory interpretation, record reconciliation, diagnosis, or outcome prediction.',
    correctUnderstanding: 'Real receivers verify identity, current physiology, dated trends, active support from source to patient, devices, medications, orders, pending work, contingencies, and the bedside examination.',
    briefIn: ['icu-handoff-with-hidden-deterioration'],
  },
  {
    id: 'icu-handoff-controls-record-events-not-communication-or-care',
    headline: 'Handoff buttons record ordered events; they do not measure communication or perform escalation or care.',
    simplification: 'Fixed clicks stand in for shared attention, content receipt, bedside cross-check, escalation, receiver synthesis, acceptance, and reassessment.',
    whereItMisleads: 'Equating button order with voice, language, listening, questioning, nonverbal behavior, interruption handling, teamwork, hierarchy, bedside assessment, escalation, or clinical competence.',
    correctUnderstanding: 'Handoff quality depends on accurate local content, trained people, protected attention, active receiver scrutiny, questions, closed-loop synthesis, explicit ownership, and real action.',
    briefIn: ['icu-handoff-with-hidden-deterioration'],
  },
  {
    id: 'no-live-handoff-verification-escalation-treatment-transfer-or-outcome',
    headline: 'The case does not verify a patient, communicate, escalate, treat, transfer responsibility, or predict outcome.',
    simplification: 'Staffing, workload, documentation, EHR use, patient and family participation, device checks, treatment, source control, transfer, disposition, and later trajectory remain incomplete.',
    whereItMisleads: 'Using the interface as a universal script, accepting the outgoing label without bedside reconciliation, or treating a recorded acknowledgment as real transfer of responsibility.',
    correctUnderstanding: 'Use local policy and critical-care, nursing, respiratory, pharmacy, source-control, safety, and communication expertise for real handoffs and deterioration.',
    briefIn: ['icu-handoff-with-hidden-deterioration'],
  },
  {
    id: 'ventilator-disconnection-alarm-findings-reserve-and-response-are-authored',
    headline: 'The alarm, delivered-breath findings, falling oxygen reserve, circuit state, and response are authored teaching facts.',
    simplification: 'One fully dependent ventilated patient has fixed command-delivery discordance, a complete circuit discontinuity, and a bounded restored-support response.',
    whereItMisleads: 'Treating the screen as alarm hearing or interpretation, examination, monitoring, waveform or ventilator-data acquisition, circuit or airway inspection, diagnosis, reserve prediction, or outcome prediction.',
    correctUnderstanding: 'Real clinicians integrate the patient, airway, independent physiology, delivered versus commanded ventilation, pressure, capnography, circuit, ventilator, gas source, alarm configuration, and serial response.',
    briefIn: ['ventilator-circuit-disconnection'],
  },
  {
    id: 'ventilator-disconnection-controls-record-intent-not-device-handling-or-care',
    headline: 'Bridge, inspect, restore, and reassess buttons record intents; they do not handle equipment or deliver care.',
    simplification: 'The interface orders a fixed response without oxygenating, ventilating, tracing tubing, reconnecting a circuit, securing components, or programming a ventilator.',
    whereItMisleads: 'Equating button order with critical-care, nursing, respiratory-therapy, airway, equipment, alarm-management, troubleshooting, procedural, or transfer competence.',
    correctUnderstanding: 'Actual response requires immediate patient support, skilled hands-on inspection and correction, device-specific knowledge, local backup systems, and whole-patient reassessment.',
    briefIn: ['ventilator-circuit-disconnection'],
  },
  {
    id: 'no-live-circuit-inspection-oxygen-ventilation-reconnection-or-outcome',
    headline: 'The case does not inspect a circuit, deliver oxygen or ventilation, reconnect equipment, configure alarms, or predict outcome.',
    simplification: 'Connection location, circuit accessories, airway state, backup device, technique, alarm timing and priority, oxygen-reserve course, durability, and later outcome remain incomplete.',
    whereItMisleads: 'Copying the 10-second teaching delay to another device, silencing an alarm without bedside assessment, trusting commanded settings, or treating reconnection alone as closure.',
    correctUnderstanding: 'Use the specific device instructions, local policy, and critical-care, nursing, respiratory, airway, biomedical, and safety expertise for real equipment events.',
    briefIn: ['ventilator-circuit-disconnection'],
  },
  {
    id: 'vasopressor-delivery-setup-mechanics-and-response-are-authored',
    headline: 'The pump record, tubing setup, delivery delay, shock findings, and response are authored teaching facts.',
    simplification: 'One septic-shock patient has a fixed microinfusion path, delayed catheter-tip arrival, and bounded perfusion response.',
    whereItMisleads: 'Treating the screen as pump-log, pressure, flow, line, catheter, laboratory, or monitoring acquisition or interpretation; shock diagnosis; transit calculation; or outcome prediction.',
    correctUnderstanding: 'Real delivery depends on the specific syringe, pump, mechanical fit, tubing compliance and resistance, valves, connectors, mixing point, downstream volume, carrier, pressure gradients, access, device settings, and serial patient response.',
    briefIn: ['delayed-vasopressor-delivery'],
  },
  {
    id: 'vasopressor-delivery-controls-record-review-and-protocol-intent-only',
    headline: 'Path-review, classification, protocol, and reassessment buttons record intents; they do not manipulate an infusion.',
    simplification: 'The interface orders systems reasoning without touching a syringe, pump, tubing, stopcock, connector, catheter, or patient.',
    whereItMisleads: 'Equating button order with nursing, pharmacy, critical-care, infusion, device, sterile, prescribing, calculation, troubleshooting, or procedural competence.',
    correctUnderstanding: 'Actual correction requires trained bedside staff, the specific device instructions, a validated local protocol, correct medication and access verification, sterile technique, and repeated delivery and patient assessment.',
    briefIn: ['delayed-vasopressor-delivery'],
  },
  {
    id: 'no-live-infusion-calculation-manipulation-drug-delivery-or-outcome',
    headline: 'The case does not calculate, prime, purge, flush, bolus, program, prescribe, compound, or deliver a vasopressor.',
    simplification: 'Concentration, dose, universal transit formula, priming volume, pressure matching, device feature, changeover technique, and ongoing shock prescription remain incomplete.',
    whereItMisleads: 'Copying the fictional setup into care, flushing concentrated drug into a patient, using one formula for a compliant multi-infusion system, or treating a pressure response as proof of one cause.',
    correctUnderstanding: 'Use local medication and device policy plus nursing, pharmacy, critical-care, biomedical, vascular-access, and safety expertise for real high-consequence infusions.',
    briefIn: ['delayed-vasopressor-delivery'],
  },
  {
    id: 'tube-migration-position-ventilation-and-response-are-authored',
    headline: 'The tube marks, unilateral ventilation, pressures, gas exchange, typed migration, and response are authored teaching facts.',
    simplification: 'One ventilated ICU patient has a fixed post-turn change, right-mainstem position, and bounded multi-signal response.',
    whereItMisleads: 'Treating the screen as patient examination, auscultation, monitoring or ventilator-data acquisition, depth measurement, cuff or securement inspection, diagnosis, or outcome prediction.',
    correctUnderstanding: 'Real clinicians reassess the patient, airway, bilateral ventilation, capnography, delivered breaths, pressures, circuit, securement, depth, oxygenation, and serial response after movement.',
    briefIn: ['endotracheal-tube-migration-after-repositioning'],
  },
  {
    id: 'tube-migration-controls-record-assessment-support-and-correction-intent-only',
    headline: 'Recognition, support, review, correction, and reassessment buttons record intents; they do not perform airway care.',
    simplification: 'Five ordered clicks stand in for skilled team escalation, immediate support, airway-position assessment, experienced correction, resecurement, and response proof.',
    whereItMisleads: 'Equating button order with critical-care, respiratory-therapy, airway, examination, equipment, procedural, teamwork, or crisis-management competence.',
    correctUnderstanding: 'Actual response requires immediate support, experienced hands, local airway and device procedures, physical reassessment, and repeated whole-patient verification.',
    briefIn: ['endotracheal-tube-migration-after-repositioning'],
  },
  {
    id: 'no-live-auscultation-tube-handling-imaging-diagnosis-or-outcome',
    headline: 'The case does not examine or turn a patient, auscultate, inspect equipment, manipulate a tube, acquire imaging, diagnose, or predict outcome.',
    simplification: 'The 22 cm and 25 cm marks and 3-minute response belong only to this authored case; depth, anatomy, technique, alternatives, durability, disposition, and later outcome remain incomplete.',
    whereItMisleads: 'Copying the fictional depth as a target, using capnography alone to prove correct depth, physically correcting a tube without immediate support and skilled verification, or closing alternate causes too early.',
    correctUnderstanding: 'Use patient-specific anatomy and findings, experienced airway help, local policy, appropriate confirmation methods, and critical-care and respiratory expertise for real airway-position events.',
    briefIn: ['endotracheal-tube-migration-after-repositioning'],
  },
  {
    id: 'septic-shock-resuscitation-trajectory-and-response-are-authored',
    headline: 'The prior-care record, perfusion trajectory, dynamic response, lung panel, suspected source, and 10-minute response are authored teaching facts.',
    simplification: 'One ICU patient has fixed persistent hypoperfusion after reported early therapy, a 2% passive-leg-raise response, diffuse B-lines, and a bounded later panel.',
    whereItMisleads: 'Treating the screen as examination, monitoring, sample or ultrasound acquisition or interpretation, delivery verification, fluid-responsiveness measurement, shock classification, or outcome prediction.',
    correctUnderstanding: 'Real resuscitation repeatedly integrates verified treatment delivery, pressure, brain, skin, kidney, lactate context, dynamic response, lung tolerance, cardiac function, source, and serial trajectory.',
    briefIn: ['septic-shock-resuscitation'],
  },
  {
    id: 'septic-shock-resuscitation-controls-record-review-and-plan-intent-only',
    headline: 'Context, perfusion, fluid-response, support, source-control, and reassessment buttons record review and plan intents only.',
    simplification: 'Five ordered clicks stand in for multidisciplinary bedside assessment and an individualized resuscitation and source-control loop.',
    whereItMisleads: 'Equating button order with critical-care, nursing, pharmacy, respiratory, ultrasound, hemodynamic, medication, procedural, source-control, or teamwork competence.',
    correctUnderstanding: 'Actual care requires trained teams, local protocols, verified delivery and access, skilled measurements, patient-specific targets, direct procedures, and repeated response assessment.',
    briefIn: ['septic-shock-resuscitation'],
  },
  {
    id: 'no-live-sepsis-measurement-prescribing-source-control-or-outcome',
    headline: 'The case does not examine, measure, sample, scan, calculate, diagnose, prescribe, deliver treatment, perform source control, or predict outcome.',
    simplification: 'The reported 30 mL/kg, +2% response, B-lines, hemodynamic values, suspected biliary source, and short response belong only to this authored case.',
    whereItMisleads: 'Copying a value as a universal cutoff, chasing MAP or lactate with unselected fluid, assuming a running command reached the patient, delaying source control, or inferring recovery from modest improvement.',
    correctUnderstanding: 'Use current local sepsis and device protocols plus critical-care, nursing, pharmacy, respiratory, infectious-disease, procedural, surgical, and source-control expertise for real care.',
    briefIn: ['septic-shock-resuscitation'],
  },
  {
    id: 'no-live-mixed-shock-diagnosis-prescribing-hemodynamic-procedure-or-outcome',
    headline: 'The case does not diagnose mixed shock, define universal catheter cutoffs, prescribe support, perform procedures, or predict outcome.',
    simplification: 'Concurrent treatment alters hemodynamics, and evolving mechanical, right-heart, obstructive, bleeding, medication, infection, and equipment causes remain incomplete.',
    whereItMisleads: 'Copying the numbers as cutoffs, giving the same support to every phenotype, loading fluid despite congestion, or letting a mixed label close either cause.',
    correctUnderstanding: 'Treat proposed ranges as prompts, interpret them in treatment context, support perfusion, address every active cause, and reassess serially.',
    briefIn: ['mixed-shock'],
  },
];
