/**
 * The endocrine-metabolic module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a endocrine-metabolic scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const ENDOCRINE_METABOLIC_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'perioperative-diabetes-authored-contrasts',
    headline: 'Glucose, ketones, and vital signs follow authored contrasts, not insulin kinetics.',
    simplification: 'The adult pump-interruption lesson has fixed untreated and response checkpoints at 30 and 60 minutes. Acidosis, dose response, insulin overlap, and surgery are not modeled.',
    whereItMisleads: 'Teaching clocks become safe waiting intervals, modest ketonemia becomes a DKA diagnosis, or fixed responses become expected clinical results.',
    correctUnderstanding: 'Restore reliable insulin delivery promptly and reassess as needed. Acidosis and other diagnostic components require qualified evaluation; this lesson predicts neither DKA nor its resolution.',
    briefIn: ['perioperative-diabetes-insulin-continuity'],
  },
  {
    id: 'perioperative-diabetes-individualized-care',
    headline: 'Insulin continuity is verified care, not a universal pump, dose, or infusion instruction.',
    simplification: 'Qualified alternative insulin coverage and individualized fasting planning are dose-free requests. The planning request does not trigger a biochemical effect.',
    whereItMisleads: 'Fasting is treated as a reason to omit all insulin, a pump restart is assumed to prove delivery, or all fasting patients receive identical insulin and substrate infusions.',
    correctUnderstanding: 'Choose a reliable regimen with qualified oversight, including device suitability, insulin, substrate, fluids, electrolytes, monitoring, and procedural changes. Preserve appropriate patient participation and individualized local care.',
    briefIn: ['perioperative-diabetes-insulin-continuity'],
  },
  {
    id: 'perioperative-diabetes-observed-findings',
    headline: 'A glucose-only check does not update older ketones or authorize surgery.',
    simplification: 'Separate timestamps distinguish glucose-only checks from requested full glucose, ketone, and bedside observations. No CGM or automatic laboratory stream is modeled.',
    whereItMisleads: 'A better glucose value, accepted care, or elapsed time becomes proof of ketone correction, surgical readiness, or permission to interrupt insulin.',
    correctUnderstanding: 'Use appropriate point-of-care and full clinical reassessment; CGM may be an adjunct. Handoff preserves continuing treatment and review, not discharge, automatic clearance, or competence certification.',
    briefIn: ['perioperative-diabetes-insulin-continuity'],
  },
  {
    id: 'refeeding-authored-contrasts',
    headline: 'Electrolyte and vital-sign changes are authored contrasts, not replacement kinetics.',
    simplification: 'Fixed partial, comprehensive, recurrent, and combined-care branches use 30- and 60-minute observation checkpoints. No dose, route, calorie calculation, or physiologic nutrition solver exists.',
    whereItMisleads: 'A learner treats a response clock as a safe wait or expects the same numerical response in a patient.',
    correctUnderstanding: 'Qualified care and reassessment are individualized. Teaching clocks and instructor stops are not clinical deadlines or predictions of arrhythmia, injury, or recovery.',
    briefIn: ['refeeding-electrolyte-shift'],
  },
  {
    id: 'refeeding-individualized-nutrition',
    headline: 'Nutrition review does not prescribe a universal rate or stop all feeding.',
    simplification: 'The selected adult already has severe feeding-associated electrolyte deterioration. A dose-free request covers individualized nutrition, dextrose, fluid, and advancement review.',
    whereItMisleads: 'The lesson is generalized to every at-risk patient, or reducing or stopping all nutrition is treated as universally required or forbidden.',
    correctUnderstanding: 'Guidance differs on prevention and feeding advancement. Qualified teams balance current severity, ongoing nutrition needs, supplementation, and local protocols; other causes remain open.',
    briefIn: ['refeeding-electrolyte-shift'],
  },
  {
    id: 'refeeding-observed-findings',
    headline: 'A better phosphate result alone does not establish correction or durable safety.',
    simplification: 'Only explicit reassessment reveals new phosphate, potassium, and magnesium values. Thiamine creates no invented immediate laboratory effect.',
    whereItMisleads: 'Accepted care, elapsed time, or a single historical result is mistaken for normalization, thiamine sufficiency, or discharge readiness.',
    correctUnderstanding: 'Continue qualified assessment of all deficiencies, symptoms, rhythm, fluid balance, nutrition, and cause. This interface cannot assess hands-on care or certify competence.',
    briefIn: ['refeeding-electrolyte-shift'],
  },
  {
    id: 'avp-deficiency-authored-checkpoints',
    headline: 'Circulation, urine, and sodium changes are authored contrasts, not treatment kinetics.',
    simplification: 'The 15-minute circulation, 30-minute urine, and 120-minute combined-care checkpoints are fixed. Unrequested laboratory findings remain private; later requested values remain historical. Teaching stops bound untreated and unfinished branches.',
    whereItMisleads: 'A learner waits for a timer, assumes a fixed fluid or desmopressin response, or equates less urine with corrected sodium.',
    correctUnderstanding: 'Reassess whenever needed. Circulation, water balance, medication effect, and sodium require individualized monitoring. No volume, dose, infusion-rate, kidney-function, or brain-injury model is provided.',
    briefIn: ['hypernatremic-dehydration-avp-deficiency'],
  },
  {
    id: 'avp-deficiency-known-diagnosis',
    headline: 'Established isolated AVP deficiency is supplied, not diagnosed by the learner.',
    simplification: 'Medication omission and limited water access occur in an adult with a known diagnosis. Depleted circulation initially masks large urine losses. Other pituitary deficits and renal AVP resistance are outside this case.',
    whereItMisleads: 'A learner rules out known AVP deficiency from low initial urine output or applies this pathway to every cause of hypernatremia or diabetes.',
    correctUnderstanding: 'Assess the person, medication history, hydration, renal function, and other possible causes. Known prescribed treatment does not require a new diagnostic laboratory gate after circulation restoration.',
    briefIn: ['hypernatremic-dehydration-avp-deficiency'],
  },
  {
    id: 'avp-deficiency-qualified-water-plan',
    headline: 'Water replacement and desmopressin are qualified care requests, not prescriptions.',
    simplification: 'Both profiles share one selected fluid-first pathway. Independent water and medication requests follow restored circulation; neither administrative review nor a new laboratory click gates them. The later response remains hypernatremic.',
    whereItMisleads: 'A learner treats an authored delay as mandatory, blindly repeats desmopressin, rapidly targets normal sodium, or declares safe discharge after a partial response.',
    correctUnderstanding: 'Qualified teams individualize correction, monitor combined water and antidiuretic effects, and review swallowing, medication reliability, and water access. Unknown duration is not acute sodium loading. Handoff transfers unresolved care.',
    briefIn: ['hypernatremic-dehydration-avp-deficiency'],
  },
  {
    id: 'hyponatremia-correction-authored-checkpoints',
    headline: 'Sodium and urine changes are authored contrasts, not predicted water balance or drug effects.',
    simplification: 'Water diuresis at 30 minutes, excessive rise at 60 minutes without control, a 60-minute response checkpoint, and 120- or 240-minute teaching stops are fictional. Results appear only when requested; they remain historical afterward.',
    whereItMisleads: 'A learner waits for a teaching timer, assumes a fixed desmopressin or fluid effect, or reads an old sodium result as current.',
    correctUnderstanding: 'Reassess promptly and as clinically required. Water losses and sodium can change unpredictably. The model has no fluid-balance solver, dose kinetics, ODS outcome prediction, or proven safety endpoint.',
    briefIn: ['hyponatremia-aquaresis-and-overcorrection'],
  },
  {
    id: 'hyponatremia-correction-high-risk-window',
    headline: 'Transfer and relowering never reset the original correction window or erase the observed peak.',
    simplification: 'This selected high-risk patient starts one hour after sodium 106 mmol/L, already at 111. Both profiles use an explicit 4–6 mmol/L daily goal and an 8 mmol/L ceiling in any 24 hours; general regional recommendations differ.',
    whereItMisleads: 'A learner treats 111 as the starting baseline, targets normal sodium, applies this ceiling universally, or assumes relowering removes prior exposure.',
    correctUnderstanding: 'Preserve pretreatment values, timings, and the maximum observed rise. Unknown duration and high-risk features require qualified conservative planning. Improved appearance does not exclude later neurologic harm; no safe margin or guaranteed ODS prevention is established here.',
    briefIn: ['hyponatremia-aquaresis-and-overcorrection'],
  },
  {
    id: 'hyponatremia-correction-qualified-care',
    headline: 'Water-loss control and relowering are qualified requests, not prescriptions or discharge clearance.',
    simplification: 'Reactive water-loss management requires an observed emerging problem. After an observed breach, qualified control and relowering can be requested in either order without administrative prerequisites. Prophylactic clamp strategies and actual replacement prescriptions are outside this lesson.',
    whereItMisleads: 'A learner considers all early clamp strategies wrong, treats thiazide use as proof of SIADH, delays rescue for an acknowledgment, ignores potassium contribution, or withholds necessary resuscitation from an unstable patient.',
    correctUnderstanding: 'Qualified teams individualize water-loss control, relowering, potassium and nutrition treatment, and cause assessment. Continue sodium, urine, potassium, neurologic, and cause surveillance over the next 24–48 hours. Handoff transfers active care; it does not prove recovery.',
    briefIn: ['hyponatremia-aquaresis-and-overcorrection'],
  },
  {
    id: 'hypocalcemia-authored-response-and-recurrence',
    headline: 'Relief, recurrence, and calcium changes are authored contrasts, not treatment kinetics.',
    simplification: 'Five-minute delay, 30-minute no-rescue takeover, 15-minute initial relief, 45-minute recurrence without magnesium or continuing care, 60-minute complete-care partial stabilization, and 180-minute unfinished stop are fictional lesson clocks. Calcium remains low; magnesium and the supplied QTc do not normalize.',
    whereItMisleads: 'A learner waits for a timer, predicts recurrence at a fixed minute, or assumes symptom relief proves corrected calcium, magnesium, or cardiac risk.',
    correctUnderstanding: 'Treat promptly and reassess as clinically required. The rate and durability of response vary. These fixed calcium, pulse, and breathing changes demonstrate contrasting branches; they neither prescribe reassessment intervals nor predict an individual outcome.',
    briefIn: ['hypocalcemic-tetany-rescue-and-recurrence'],
  },
  {
    id: 'hypocalcemia-qualified-care-and-cause-limits',
    headline: 'Emergency calcium does not wait for the cause panel; dose and delivery skills are not assessed.',
    simplification: 'Calcium rescue includes qualified ECG monitoring and has no acknowledgment or laboratory prerequisite. Supplied cause review unlocks selected magnesium and continuing-care pathways; their buttons do not demonstrate replacement, activated-vitamin-D effect, or corrected laboratory values.',
    whereItMisleads: 'A learner delays calcium until magnesium is normal, treats oral calcium alone as sufficient for severe tetany, or interchanges calcium preparations by volume.',
    correctUnderstanding: 'Qualified teams provide monitored rescue while evaluating and treating the cause. Low magnesium needs correction alongside care. Calcium preparation, elemental content, dose, rate, access, renal considerations, activated vitamin D, and laboratory monitoring require individualized clinical decisions.',
    briefIn: ['hypocalcemic-tetany-rescue-and-recurrence'],
  },
  {
    id: 'hypocalcemia-postoperative-airway-and-handoff',
    headline: 'The fixed QTc is not a live measurement, and early postoperative improvement is not recovery.',
    simplification: 'The fictional person initially has a patent airway, no supplied neck hematoma, and a fixed ECG report with QTc 520 ms. No evolving QT waveform, seizure, airway obstruction, permanent hypoparathyroidism, or discharge outcome is modeled.',
    whereItMisleads: 'Every postoperative airway symptom is attributed to calcium, an ordinary trace is treated as QT normalization, or one low PTH and brief symptom relief establish permanent disease or discharge readiness.',
    correctUnderstanding: 'Post-thyroidectomy airway deterioration needs urgent qualified evaluation, including hematoma risk. Continue symptom, ECG, calcium, magnesium, phosphate, renal and vitamin D review. Early parathyroid dysfunction may recover; handoff transfers active risk and does not prove chronic hypoparathyroidism or independent stability.',
    briefIn: ['hypocalcemic-tetany-rescue-and-recurrence'],
  },
  {
    id: 'hypercalcemia-authored-bridge-states',
    headline: 'Volume and calcium changes are authored contrasts, not fluid or drug kinetics.',
    simplification: 'Separate 15-minute hydration and 4-hour calcitonin checkpoints change fixed observations. Missing urgent care flags at 15 minutes, stops at 30 minutes, and any unfinished branch stops at six hours. No antiresorptive effect is modeled.',
    whereItMisleads: 'A learner treats a clock as permission to wait, assumes hydration cannot lower calcium clinically, or attributes the four-hour calcium change to an antiresorptive.',
    correctUnderstanding: 'Treat and reassess promptly. Hydration can lower calcium clinically; this lesson isolates circulatory response for teaching. Antiresorptive responses take longer and vary. Calcium remains severely elevated at the authored bridge endpoint; no response magnitude or recovery is guaranteed.',
    briefIn: ['hypercalcemic-crisis-volume-and-bridge'],
  },
  {
    id: 'hypercalcemia-cardiorenal-and-treatment-limits',
    headline: 'Qualified pathways do not prescribe fluid volumes, diuretic timing, or a specific antiresorptive.',
    simplification: 'Tailored hydration includes immediate bedside volume assessment. A separate supplied cardiorenal review is required before the generic antiresorptive choice; it does not require new tests or completed rehydration.',
    whereItMisleads: 'A learner delays hydration for a button, gives unlimited fluid in HFpEF or CKD, uses routine diuresis before rehydration, or treats denosumab as mandatory and risk-free.',
    correctUnderstanding: 'Individualize fluids and monitor for overload. Review renal function before IV bisphosphonates and individualize antiresorptive selection and safety checks. Diuretics may be appropriate for overload, not routine calcium treatment. Oliguria or congestion requires qualified renal and critical-care reassessment, not automatic dialysis.',
    briefIn: ['hypercalcemic-crisis-volume-and-bridge'],
  },
  {
    id: 'hypercalcemia-hcm-and-handoff-boundaries',
    headline: 'This malignancy-specific bridge ends in continuing care, not normalized calcium or cancer control.',
    simplification: 'A fictional patient with known metastatic breast cancer receives a selected severe-HCM pathway. A fresh fluid and bridge observation plus accepted care permits handoff while calcium remains 14.8 mg/dL.',
    whereItMisleads: 'The same treatment is generalized to every hypercalcemia cause, calcitonin is continued indefinitely, or early improvement is taken as discharge readiness.',
    correctUnderstanding: 'Cause-specific care differs. Calcitonin is limited to 48–72 hours because its effect wanes. Continue calcium, volume, kidney, magnesium, phosphate, vitamin D, and treatment-safety review with oncology ownership and escalation when clinically required.',
    briefIn: ['hypercalcemic-crisis-volume-and-bridge'],
  },
  {
    id: 'myxedema-authored-support-states',
    headline: 'Oxygenation, ventilation, and systemic response are authored contrasts, not treatment kinetics.',
    simplification: 'Oxygen alone changes saturation but not carbon-dioxide retention. Qualified ventilation changes the respiratory state after five authored minutes; complete care permits a later partial-support state.',
    whereItMisleads: 'A learner treats a five-, 15-, 30-, 60-, or 180-minute checkpoint as a safe delay, a predicted response, or a clinical deadline.',
    correctUnderstanding: 'Assess the patient continuously and respond to deterioration immediately. Every time and numeric state is fictional; improvement under support is not thyroid recovery.',
    briefIn: ['myxedema-coma-ventilation-and-steroid-sequence'],
  },
  {
    id: 'myxedema-qualified-team-not-procedures',
    headline: 'Qualified-care choices do not teach doses, airway procedures, warming devices, or electrolyte correction.',
    simplification: 'One supportive-care choice bundles monitored passive thermal protection, individualized circulatory/metabolic support, and precipitant investigation and treatment.',
    whereItMisleads: 'A learner equates a button with performed intubation, an appropriate fluid load, corrected sodium or glucose, or a complete diagnosis.',
    correctUnderstanding: 'Qualified clinicians individualize organ support, empiric infection treatment, serial laboratory review, and ongoing endocrine care. Other causes of altered consciousness and shock must remain under investigation.',
    briefIn: ['myxedema-coma-ventilation-and-steroid-sequence'],
  },
  {
    id: 'myxedema-sequence-and-recovery-limits',
    headline: 'Steroids precede the selected T4 pathway; no artificial wait, universal T3 rule, or recovery clearance is modeled.',
    simplification: 'Empiric steroid coverage is checked before qualified levothyroxine. Endpoints are ongoing-care handoff or instructor takeover, with persistent illness.',
    whereItMisleads: 'A learner delays thyroid therapy for a nonexistent interval, treats T3 as always necessary or forbidden, or uses a better saturation or early TSH result as proof of recovery.',
    correctUnderstanding: 'The 2026 consensus and ATA guidance emphasize individualized therapy, cardiac risk, clinical reassessment, and continued monitoring. Normal oxygen saturation does not prove adequate ventilation; early improvement does not permit extubation or discharge.',
    briefIn: ['myxedema-coma-ventilation-and-steroid-sequence'],
  },
  {
    id: 'thyroid-authored-checkpoints',
    headline: 'Patient states and early-support checkpoints are authored, not thyroid or drug kinetics.',
    simplification: 'Fixed presentation, incomplete-care deterioration, early partial-support response, and instructor-takeover states respond to bounded decisions and elapsed time.',
    whereItMisleads: 'A learner treats the five-minute, 30-minute, two-hour, or four-hour teaching clock as a safe delay, outcome forecast, or expected treatment response.',
    correctUnderstanding: 'Reassess frequently and escalate for deterioration immediately. The two-hour observation after complete care remains febrile and tachycardic; marked improvement generally takes 24–72 hours and varies by patient.',
    briefIn: ['thyroid-storm-hemodynamic-risk'],
  },
  {
    id: 'thyroid-qualified-treatment-not-prescribing',
    headline: 'Buttons coordinate qualified care; they do not prescribe drugs, doses, fluids, or procedures.',
    simplification: 'Antithyroid and supportive pathways are bundled intentions. A focused supplied circulation assessment informs individualized rate-control review without selecting a drug.',
    whereItMisleads: 'A learner equates a completed pathway with prescribing competence, automatic beta-blocker safety, or completed diagnostic and organ-support work.',
    correctUnderstanding: 'Care requires qualified endocrine and critical-care teams, local protocols, repeated assessment, individualized treatment and monitoring, and investigation and treatment of triggers and alternative causes.',
    briefIn: ['thyroid-storm-hemodynamic-risk'],
  },
  {
    id: 'thyroid-sequence-and-recovery-boundaries',
    headline: 'One selected iodine sequence is rehearsed; another guideline pathway and later recovery are not simulated.',
    simplification: 'The 2026 joint consensus/ATA pathway requires at least one hour after antithyroid therapy before iodine. Rehearsal ends at continuing-care handoff or instructor takeover.',
    whereItMisleads: 'A learner labels all concurrent iodine treatment unsafe, withholds other urgent care during the interval, or treats a slower pulse as resolution.',
    correctUnderstanding: 'JTA/JES permits concurrent treatment for selected synthesis-driven hyperthyroidism. Steroids, support, and precipitant care proceed now. Continuing ICU care, clinical and biochemical reassessment, and definitive planning remain necessary.',
    briefIn: ['thyroid-storm-hemodynamic-risk'],
  },
  {
    id: 'adrenal-authored-response-not-kinetics',
    headline: 'Pressure, alertness, and response checkpoints are authored states, not cortisol or fluid kinetics.',
    simplification: 'Fixed 5-minute incomplete-rescue, 10-minute combined-response, and 30-minute takeover checkpoints create distinct decision paths. Initial laboratory values do not update automatically.',
    whereItMisleads: 'A learner treats a checkpoint as permission to delay care or as an individual treatment-response prediction.',
    correctUnderstanding: 'Suspected crisis requires immediate qualified rescue with frequent reassessment. Response, fluid needs, laboratory trends, and shock causes vary; the numeric states here are fictional.',
    briefIn: ['adrenal-crisis-treatment-before-tests'],
  },
  {
    id: 'adrenal-rescue-not-dose-or-technique',
    headline: 'Rescue actions represent qualified steroid and fluid pathways, not dosing or administration technique.',
    simplification: 'The learner selects dose-free parenteral hydrocortisone and isotonic saline pathways, with no rate, volume, access, preparation, or individualized prescription controls.',
    whereItMisleads: 'A successful action is taken as competence to prescribe, prepare, or administer emergency treatment.',
    correctUnderstanding: 'Real treatment follows qualified protocols and repeated assessment. Diagnostic sampling should not delay rescue. Other causes of shock and the precipitating illness need parallel care.',
    briefIn: ['adrenal-crisis-treatment-before-tests'],
  },
  {
    id: 'adrenal-handoff-not-resolution',
    headline: 'Improvement and a completed handoff do not establish recovery or safe discharge.',
    simplification: 'A bounded handoff ends the rehearsal after observed response and continuity planning, without modeling later steroid taper, electrolyte correction, or recurrence.',
    whereItMisleads: 'The improved pressure is treated as diagnostic proof or permission to stop treatment or send the patient home.',
    correctUnderstanding: 'Ongoing steroid coverage, monitoring, precipitant treatment, education, emergency identification and supplies, medication access, and follow-up require qualified ownership.',
    briefIn: ['adrenal-crisis-treatment-before-tests'],
  },
  {
    id: 'adult-hypoglycemia-authored-timed-states-not-kinetics',
    headline: 'Glucose, alertness, recurrence, and rescue responses are authored timed states, not drug kinetics.',
    simplification: 'The model uses fixed observation and response checkpoints and an instructor-takeover stop, with no individualized glucose kinetics.',
    whereItMisleads: 'A learner treats the numeric response or recurrence time as a prediction for another patient.',
    correctUnderstanding: 'The clock creates a rehearsal of reassessment and recurrence. Real responses vary and require repeated qualified assessment.',
    briefIn: ['severe-hypoglycemia-recurrence'],
  },
  {
    id: 'adult-hypoglycemia-qualified-rescue-not-dose-or-technique',
    headline: 'The rescue choice represents qualified team care, not dosing or IV technique.',
    simplification: 'The only rescue is a fixed simulated pathway; unsafe oral treatment is refused and no drug formulation, concentration, dose, rate, or access can be selected.',
    whereItMisleads: 'A button is treated as medication-administration competence or a universal rescue regimen.',
    correctUnderstanding: 'Use local protocols and qualified clinical judgment. This lesson teaches noticing, safe priorities, timing, reassessment, and handoff.',
    briefIn: ['severe-hypoglycemia-recurrence'],
  },
  {
    id: 'adult-hypoglycemia-handoff-not-durable-recovery',
    headline: 'A completed handoff does not prove durable recovery or safe discharge.',
    simplification: 'The branch stops after monitored handoff or instructor takeover without a later clinical outcome.',
    whereItMisleads: 'A normal observed glucose or completed scenario is mistaken for resolved medication, nutrition, neurologic, or recurrence risk.',
    correctUnderstanding: 'Continued surveillance and individualized cause, medication, nutrition, and prevention work remain necessary.',
    briefIn: ['severe-hypoglycemia-recurrence'],
  },
  {
    id: 'hhs-panels-osmolality-trajectory-qualified-care-and-later-report-are-authored',
    headline: 'The HHS panels, osmolality trajectory, qualified care, and later report are authored.',
    simplification: 'Two fixed reports illustrate correction without modeling glucose, sodium, urea, osmolality, fluid, insulin, or kidney kinetics.',
    whereItMisleads: 'A learner assumes that an average decline proves safe correction between measurements or that better glucose proves HHS resolution.',
    correctUnderstanding: 'Qualified serial clinical and biochemical assessment, including cognition and urine output, is required. Persistent hyperosmolality keeps this fictional case unresolved.',
    briefIn: ['hhs-osmolality-trajectory'],
  },
  {
    id: 'hhs-controls-activate-reconcile-recognize-review-reassess-and-handoff-only',
    headline: 'The HHS controls confirm support, connect facts, recognize, review, reassess, and hand off only.',
    simplification: 'The six ordered actions record cognitive review, not delivery of qualified-team care.',
    whereItMisleads: 'A button is mistaken for fluid replacement, insulin administration, monitoring, or a real clinical handoff.',
    correctUnderstanding: 'This rehearsal cannot assess treatment delivery, bedside technique, or team performance.',
    briefIn: ['hhs-osmolality-trajectory'],
  },
  {
    id: 'no-live-hhs-testing-calculation-fluid-insulin-electrolyte-correction-or-outcome',
    headline: 'This lab does not test, calculate, prescribe, correct HHS, or determine outcome.',
    simplification: 'There is no learner-selected fluid, insulin, electrolyte, medication, dose, rate, route, access, infusion, nutrition, or disposition.',
    whereItMisleads: 'The fictional panels are used as a bedside calculator, protocol, or prediction for a real patient.',
    correctUnderstanding: 'Use local protocols and qualified individualized assessment. This preview is not clinical decision support.',
    briefIn: ['hhs-osmolality-trajectory'],
  },
  {
    id: 'dka-resolution-initial-treatment-current-panels-overlap-and-later-report-are-authored',
    headline: 'The DKA diagnosis, treatment, biochemical panels, basal overlap, and later report are authored.',
    simplification: 'Fixed qualified-team reports stand in for history, examination, fluid and medication delivery, serial glucose, ketone, electrolyte, gas and kidney testing, nutrition assessment, precipitant review, insulin access, basal administration, and transition planning. The engine does not calculate ketone clearance, chloride balance, insulin kinetics, potassium shifts, or individualized transition physiology.',
    whereItMisleads: 'Treating lower glucose, a closed anion gap, improved symptoms, the later resolution panel, or basal-overlap report as learner testing, treatment, universal response, transition success, durable stability, discharge readiness, or outcome.',
    correctUnderstanding: 'DKA resolution depends on plasma ketone plus pH or bicarbonate criteria, not glucose or anion gap alone. Safe transition also needs qualified insulin continuity, electrolyte surveillance, individualized nutrition, precipitant care, access, education, and follow-up.',
    briefIn: ['dka-resolution-transition'],
  },
  {
    id: 'dka-resolution-controls-activate-reconcile-recognize-review-reassess-and-handoff-only',
    headline: 'The controls activate support, connect supplied facts, recognize, review, reassess, and hand off only.',
    simplification: 'Six cognitive actions stand in for concurrent qualified endocrine, nursing, pharmacy, laboratory, electrolyte, nutrition, education, precipitant, insulin-access, transition, discharge-planning, and follow-up work.',
    whereItMisleads: 'Equating button order with diagnosis, laboratory interpretation, insulin prescribing, infusion operation, fluid or electrolyte management, nutrition, education, transition performance, or competence.',
    correctUnderstanding: 'Real DKA transition requires direct assessment, current local protocols, qualified teams, verified laboratory trajectories, medication reconciliation, basal coverage, patient-specific nutrition and hypoglycemia risk, and recurrence prevention.',
    briefIn: ['dka-resolution-transition'],
  },
  {
    id: 'no-live-dka-resolution-history-exam-laboratory-fluid-electrolyte-insulin-nutrition-transition-disposition-or-outcome',
    headline: 'The lab does not test, prescribe, deliver insulin, transition treatment, determine disposition, or report outcome.',
    simplification: 'No live history; examination; measurement; glucose, ketone, anion-gap, electrolyte, gas, kidney or other test acquisition, calculation or interpretation; diagnosis; fluid, electrolyte, dextrose, insulin, bicarbonate, drug, dose, concentration, rate, route or access selection or delivery; infusion operation; feeding or nutrition prescription; maintenance-insulin calculation; basal-insulin administration; IV-insulin discontinuation; precipitant treatment; education; counseling; prescription; access or follow-up arrangement; transition; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as an insulin, dextrose, fluid, potassium, nutrition, overlap, discharge, or patient-specific treatment calculator; treating a fixed report as permission to stop an infusion; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, the current local DKA and inpatient-diabetes pathways, trained teams, reliable laboratory and medication systems, individualized bridging and nutrition plans, patient-centered access and education, and hands-on training.',
    briefIn: ['dka-resolution-transition'],
  },
];
