/**
 * The infectious-disease module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a infectious-disease scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const INFECTIOUS_DISEASE_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'meningococcal-sepsis-presentation-and-response-are-authored',
    headline: 'The presentation, laboratory values, and one-hour response are authored contrasts.',
    simplification: 'The case supplies one fixed presentation, a ten-minute untreated deterioration, and a fixed one-hour review after recorded intent. No host response, bacterial growth, antimicrobial pharmacology, or fluid-responsiveness model runs underneath.',
    whereItMisleads: 'These clocks become expected disease kinetics, a safe observation window, a guaranteed response to correct action, or evidence that the rising C-reactive protein means treatment failure.',
    correctUnderstanding: 'Real meningococcal sepsis varies widely in speed and trajectory, and correct early action does not guarantee recovery. Inflammatory markers rise for hours regardless of treatment. No individual patient course follows from this authored model.',
    briefIn: ['meningococcal-sepsis-recognition-and-escalation'],
  },
  {
    id: 'meningococcal-sepsis-controls-are-recognition-and-intent-only',
    headline: 'Recorded intent is not a prescription and not delivered treatment.',
    simplification: 'The learner records bounded qualified-team antimicrobial and fluid intent. No agent, dose, route, preparation, access, infusion, bolus volume, oxygen setting, or vasoactive choice exists, and the critical-care referral only asks a qualified team to review the need.',
    whereItMisleads: 'Recording intent is read as having given the drug, chosen a regimen, started vasoactive support, or completed source control.',
    correctUnderstanding: 'Antimicrobial selection and delivery, fluid volume, vasoactive and access decisions, lumbar puncture and imaging timing, source control, public-health notification, and contact prophylaxis all remain qualified-team work outside this rehearsal.',
    briefIn: ['meningococcal-sepsis-recognition-and-escalation'],
  },
  {
    id: 'meningococcal-sepsis-timing-and-fluid-ceiling-are-regionally-contested',
    headline: 'The antimicrobial clock and the fluid ceiling are not settled internationally.',
    simplification: 'The case anchors on a one-hour antimicrobial target for a strongly suspected, high-pretest-probability presentation, and states that the United Kingdom single-bolus cap and the international paediatric first-hour ceiling disagree for this weight.',
    whereItMisleads: 'The one-hour target is generalised to every undifferentiated fever, or one region\u2019s fluid ceiling is treated as the only defensible number.',
    correctUnderstanding: 'The strongest evidence for immediate antimicrobials is in septic shock and in named high-probability syndromes like this one; blanket one-hour mandates for undifferentiated presentations remain disputed. Fluid volumes are individualised and region-dependent. Follow local guidance with qualified teams.',
    briefIn: ['meningococcal-sepsis-recognition-and-escalation'],
  },
  {
    id: 'obstructed-kidney-presentation-and-response-are-authored',
    headline: 'The presentation, laboratory values, and both six-hour contrasts are authored.',
    simplification: 'The case supplies one fixed presentation, a six-hour untreated deterioration on appropriate antimicrobials, and a fixed six-hour post-decompression assessment. No infection, drainage, kidney-recovery, or antimicrobial model runs underneath, and the imaging finding is given rather than acquired.',
    whereItMisleads: 'These clocks become validated decompression deadlines, a safe observation window, or proof that drainage caused the improvement.',
    correctUnderstanding: 'Real infected obstruction varies widely in speed and trajectory. The observational evidence linking earlier drainage to survival is confounded by indication, because sicker patients are drained faster. No individual patient course, and no causal effect, follows from this authored model.',
    briefIn: ['obstructed-infected-kidney-decompression'],
  },
  {
    id: 'obstructed-kidney-controls-are-recognition-activation-and-intent-only',
    headline: 'Recorded decompression intent is not a placed drain, and the antimicrobials are a premise.',
    simplification: 'The learner records bounded qualified-team intent for urgent decompression and defers definitive stone treatment. No modality, access, anaesthetic, operator, timing, antimicrobial, dose, fluid, or oxygen setting exists, and no procedure is performed.',
    whereItMisleads: 'Recording intent is read as having drained the kidney, or the lesson is taken to confirm that the running antimicrobial therapy was the right choice.',
    correctUnderstanding: 'Appropriate antimicrobial therapy is asserted as a premise of this fiction, not demonstrated; the scenario cannot teach whether an agent was correct. Drainage modality, access, timing, operator, anaesthetic care, kidney-function management, and definitive stone treatment all remain qualified-team work.',
    briefIn: ['obstructed-infected-kidney-decompression'],
  },
  {
    id: 'obstructed-kidney-timing-and-modality-are-not-established-by-evidence',
    headline: 'No guideline sets an hour threshold, and no trial separates the two drainage routes.',
    simplification: 'The case states that urological bodies recommend urgent drainage strongly on low-grade evidence, while the sepsis guidance supplying a six-hour figure grades it conditional on very-low-certainty evidence. It marks neither nephrostomy nor stenting as correct.',
    whereItMisleads: 'A learner infers a defensible deadline in hours, treats one drainage route as the right answer, or uses an inflammatory marker to decide or time decompression.',
    correctUnderstanding: 'Timing is urgent but unnumbered, and the choice of route belongs to the qualified team based on local resources and patient factors. Inflammatory markers are not established decision tools here. One major urological urosepsis section is currently withdrawn pending review, and the complicated-urinary-infection antibiotic trials rarely enrolled patients with obstruction, stones, or drains at all.',
    briefIn: ['obstructed-infected-kidney-decompression'],
  },
  {
    id: 'febrile-neutropenia-presentation-and-response-are-authored',
    headline: 'Both elapsed contrasts are authored, and neither is a validated deadline.',
    simplification: 'The case supplies one fixed presentation, an untreated contrast in which temperature falls and perfusion fails, and a treated contrast in which observations settle while the marker keeps climbing. No marrow, host-response, organism, or antimicrobial model runs underneath.',
    whereItMisleads: 'The clocks become a validated biological cliff, a safe observation window, or proof that the recorded intent caused the improvement.',
    correctUnderstanding: 'Real febrile neutropenia varies widely, and the timing evidence specific to this population is sparse and conflicting. Falling temperature and an absent leucocytosis are consistent with worsening infection in someone who cannot mount a count; a rising marker after treatment is its lag catching up. No causal effect follows from this authored model.',
    briefIn: ['febrile-neutropenia-blind-examination'],
  },
  {
    id: 'febrile-neutropenia-controls-are-recognition-activation-and-intent-only',
    headline: 'Recorded intent is not a delivered dose, and the agent is never chosen here.',
    simplification: 'The learner records bounded qualified-team intent for immediate empiric intravenous therapy according to local protocol. No agent, dose, route, combination, duration, de-escalation, antifungal, growth-factor, or prophylaxis decision exists.',
    whereItMisleads: 'Recording intent is read as the first dose having reached the patient, or the lesson is taken to endorse a particular regimen.',
    correctUnderstanding: 'Guidance deliberately delegates the agent to local microbiology policy, so no regimen is implied. Antimicrobial selection, delivery, review once cultures return, duration, and every de-escalation decision remain qualified-team work, as does the antimicrobial-stewardship counterweight this lesson cannot teach.',
    briefIn: ['febrile-neutropenia-blind-examination'],
  },
  {
    id: 'febrile-neutropenia-timing-and-risk-scores-rest-on-thin-dated-evidence',
    headline: 'The one-hour target is a safety margin, and the risk scores do not decide treatment.',
    simplification: 'The case states that the widely quoted one-hour figure is a system-design margin rather than a validated threshold, that one major guideline says only immediately, and that risk scores stratify disposition after the emergency response has begun.',
    whereItMisleads: 'A learner treats one hour as a biological cliff, or uses a low-risk score to defer or withhold empiric therapy, which is an off-label use of the instrument.',
    correctUnderstanding: 'Population-specific timing studies are few and conflicting, with any signal appearing later than one hour rather than at it. Risk scores are calculated at fever onset, do not update, are not validated in children, and the newer one is not validated in blood cancers or unstable patients. Low-risk strata still carry real complication rates. This field is also still running on guidance published between 2010 and 2018.',
    briefIn: ['febrile-neutropenia-blind-examination'],
  },
  {
    id: 'necrotizing-infection-presentation-and-progression-are-authored',
    headline: 'The progression is authored and happens whatever the learner records.',
    simplification: 'The case supplies one fixed presentation and one fixed progression four simulated hours later. No infection, tissue, perfusion, or operative model runs underneath, and the derived risk score is a stated number rather than a live calculation.',
    whereItMisleads: 'The clock becomes a validated operative deadline, or the unchanged progression is read as the learner having made no difference.',
    correctUnderstanding: 'The disease advances because only an operation treats it, and the operation happens after this rehearsal ends. What the learner changes is whether the surgical team is already mobilized when it arrives. Real presentations vary widely in speed, and no individual course follows from this authored model.',
    briefIn: ['necrotizing-infection-score-cannot-exclude'],
  },
  {
    id: 'necrotizing-infection-controls-are-recognition-activation-and-intent-only',
    headline: 'Exploration is the only test that excludes this, and it is not in the rehearsal.',
    simplification: 'The learner reconciles pain, marks and times the border, requests urgent surgical review, and records bounded antimicrobial intent per local protocol. No agent, dose, route, imaging order, incision, extent, or theatre time exists, and no procedure is performed.',
    whereItMisleads: 'Requesting review is read as the operation having happened, or antimicrobial intent is read as treatment of the infected tissue.',
    correctUnderstanding: 'Antimicrobials do not treat dead tissue and are recorded alongside surgery, never instead of it. The decision to explore, its timing and extent, imaging, critical-care support, and every operative judgement remain qualified-team work. The scenario ends with the diagnosis unconfirmed because only exploration can confirm or exclude it.',
    briefIn: ['necrotizing-infection-score-cannot-exclude'],
  },
  {
    id: 'necrotizing-infection-score-and-timing-evidence-are-weak-and-confounded',
    headline: 'The score cannot exclude, and the clock is observational.',
    simplification: 'The case states the score was derived against selected severe-cellulitis controls, that its pooled sensitivity at the usual cutoff is near two-thirds, and that it counts late physiology. It also states the low sensitivity of crepitus and bullae, and that imaging must not delay exploration.',
    whereItMisleads: 'A learner uses the score to rule out, treats absent late signs as reassurance, or reads the survival benefit of earlier surgery as a proven causal threshold.',
    correctUnderstanding: 'Roughly one confirmed case in three scores below the cutoff, so a low score changes nothing about what to do. Earlier surgery is consistently associated with survival across observational studies, but that evidence is confounded by indication in both directions, since the obviously fulminant reach theatre fastest and also die most, while the too-unstable are delayed. There is no randomised trial and no validated hour threshold. One published review disagrees about the score, having pooled mean scores in confirmed cases rather than sensitivity in suspected ones.',
    briefIn: ['necrotizing-infection-score-cannot-exclude'],
  },
  {
    id: 'endocarditis-presentation-and-decompensation-are-authored',
    headline: 'The decompensation is authored and happens whatever the learner records.',
    simplification: 'The case supplies one fixed presentation and one fixed decompensation 45 simulated minutes later. No valve, haemodynamic, antimicrobial, or embolic model runs underneath, and the echocardiographic findings are given rather than acquired.',
    whereItMisleads: 'The clock becomes a validated operative deadline, or the unchanged decompensation is read as the learner having made no difference.',
    correctUnderstanding: 'The valve fails because the treatment is an operation that happens after this rehearsal ends. What the learner changes is whether the surgical team is already engaged when it arrives. Real presentations vary widely, and no individual course follows from this authored model.',
    briefIn: ['endocarditis-mechanical-failure-on-a-surgical-clock'],
  },
  {
    id: 'endocarditis-controls-are-recognition-activation-and-referral-intent-only',
    headline: 'Recorded referral intent is not an accepted transfer or a completed operation.',
    simplification: 'The learner recognizes mechanical failure, convenes the endocarditis team with a surgical centre, records bounded intent for urgent assessment and transfer, reviews the boundary, and arranges surveillance. No operation, prosthesis, theatre time, anaesthetic plan, antimicrobial, dose, fluid, diuretic, vasoactive agent, or oxygen setting exists.',
    whereItMisleads: 'Recording intent is read as the patient having been accepted, transferred, or operated on, or the running antimicrobial course is read as inadequate.',
    correctUnderstanding: 'The antimicrobial course is appropriate and is working; that is the premise, not the problem. The surgical decision and its timing, the transfer, antimicrobial duration, critical-care support, and every operative judgement remain qualified-team work.',
    briefIn: ['endocarditis-mechanical-failure-on-a-surgical-clock'],
  },
  {
    id: 'endocarditis-surgical-timing-tiers-are-consensus-not-trial-validated',
    headline: 'The urgency tiers are consensus, and the classic examination sign is absent by design.',
    simplification: 'The case states that the surgical timing tiers are consensus operationalizations of urgency rather than randomised-trial thresholds, that vegetation size is not a standalone trigger, and that acute severe regurgitation narrows rather than widens the pulse pressure.',
    whereItMisleads: 'A learner treats a tier as a validated deadline, uses vegetation size alone to decide surgery, or excludes severe regurgitation because the pulse pressure is not wide and the murmur is quiet.',
    correctUnderstanding: 'The collapsing pulse and wide pulse pressure belong to chronic regurgitation, where the ventricle has had time to dilate; acute severe regurgitation gives a normal or narrow pulse pressure, a soft or absent first heart sound, and a short murmur that is easily missed. The size threshold operates together with an embolic episode or another indication. The one major trial in this area enrolled a narrow, stable population that does not generalise to a decompensating patient, and the United States statement predates the European guidance this case follows.',
    briefIn: ['endocarditis-mechanical-failure-on-a-surgical-clock'],
  },
  {
    id: 'severe-pneumonia-presentation-and-deterioration-are-authored',
    headline: 'Both instruments and both states are authored, and nothing is hidden.',
    simplification: 'The case supplies one fixed presentation and one fixed deterioration two simulated hours later, with both scores stated rather than calculated by the learner. No respiratory, gas-exchange, antimicrobial, or fluid model runs underneath, and the chest radiograph is described rather than shown.',
    whereItMisleads: 'The clock becomes a validated escalation deadline, or the score catching up is read as the learner having been vindicated by a number.',
    correctUnderstanding: 'The mortality score was always going to rise once the patient deteriorated. That it did is not evidence the score was useful for deciding where the patient should be. Real presentations vary widely, and no individual course follows from this authored model.',
    briefIn: ['severe-pneumonia-the-score-answered-another-question'],
  },
  {
    id: 'severe-pneumonia-controls-are-recognition-activation-and-intent-only',
    headline: 'A review is requested; a bed is never allocated.',
    simplification: 'The learner reconciles the two instruments, recognizes the mismatch, requests critical-care review, records bounded escalation intent, reviews the boundary, and arranges surveillance. No oxygen device, flow, ventilation mode or pressure, fluid volume, vasoactive agent, antimicrobial, steroid, or procedure exists.',
    whereItMisleads: 'Requesting review is read as the patient having been accepted or moved, or the recorded intent is read as a treatment plan.',
    correctUnderstanding: 'The level-of-care decision belongs to the receiving team. Whether a critical-care bed exists is the real-world constraint that most often determines what actually happens, and this rehearsal deliberately does not model capacity or rationing.',
    briefIn: ['severe-pneumonia-the-score-answered-another-question'],
  },
  {
    id: 'severe-pneumonia-triage-tools-have-no-randomised-outcome-evidence',
    headline: 'No severity tool has been shown to improve outcomes when used for triage.',
    simplification: 'The case states that the mortality score is validated for thirty-day death and to support admission rather than level of care, that its pooled discrimination for predicting critical-care admission is about 0.69, and that the severity criteria are the instrument built for the level-of-care question.',
    whereItMisleads: 'A learner treats either instrument as an order, or reads the association between delayed escalation and worse outcomes as a proven causal threshold.',
    correctUnderstanding: 'The severity criteria have never been formally re-derived and their items carry unequal weight; even they are an aid to judgement rather than an automatic admission. The delay-harm evidence is observational and confounded by indication. One national guideline uses the mortality score alongside clinical judgement rather than in isolation, and the two bodies publishing on this condition are, as of 2025, publicly split, so there is no single voice to appeal to. Regional pathways differ: one runs a mortality score then severity criteria, the other runs a disposition ladder that may never compute the criteria at all.',
    briefIn: ['severe-pneumonia-the-score-answered-another-question'],
  },
  {
    id: 'toxic-shock-presentation-and-deterioration-are-authored',
    headline: 'Both states are authored, and neither definition can close in either.',
    simplification: 'The case supplies one fixed presentation and one fixed deterioration four simulated hours later. No toxin, host-response, microbiological, or antimicrobial model runs underneath, and the culture result never returns.',
    whereItMisleads: 'The clock becomes a validated deadline, or the accumulating criteria are read as a rising probability of a confirmed diagnosis.',
    correctUnderstanding: 'More criteria satisfied is not closer to confirmation in any measurable sense. Desquamation belongs to a week or two from now and an organism either grows or does not; neither is a matter of degree. Real presentations vary widely, and no individual course follows from this authored model.',
    briefIn: ['toxic-shock-a-definition-that-cannot-close'],
  },
  {
    id: 'toxic-shock-controls-are-recognition-activation-and-intent-only',
    headline: 'Source control is already done, and no adjunct is ever chosen.',
    simplification: 'The learner recognizes the pattern, activates critical care, requests cultures, records bounded treatment intent, records the definition status openly, reviews the boundary, and arranges surveillance. Source control for the documented focus was completed by the qualified team before the rehearsal begins.',
    whereItMisleads: 'A learner infers that removing a focus is part of this lesson, or that the recorded intent selects an anti-toxin agent or immunoglobulin.',
    correctUnderstanding: 'Source control is deliberately off-stage so this scenario carries only the definitional lesson; a separate shipped scenario teaches source control as its own axis. Antimicrobial selection, the anti-toxin question, immunoglobulin, fluid volume, and vasoactive choice are all qualified-team decisions this lesson does not expose, and the immunoglobulin evidence in particular is contested.',
    briefIn: ['toxic-shock-a-definition-that-cannot-close'],
  },
  {
    id: 'toxic-shock-definitions-are-surveillance-instruments-not-bedside-rules',
    headline: 'These definitions count cases; they do not decide treatment.',
    simplification: 'The case states that one definition requires desquamation one to two weeks after the rash and the other requires isolation of the organism, so neither can close at the bedside, and that the same pending culture answers one and violates the other.',
    whereItMisleads: 'A learner declares a confirmed case, excludes the diagnosis because thresholds are not crossed, treats a four-hour no-growth result as negative, or reads the negative-culture requirement as evidence against infection.',
    correctUnderstanding: 'These are surveillance instruments built to count cases consistently across populations. The negative-culture clause excludes other diagnoses rather than denying infection, and it is the toxin rather than a bloodstream organism that makes the patient shocked. Reported case fatality spans a wide range across published series, so no single figure is asserted. The definitions have not been revised in over a decade despite a documented international rise in invasive infection, which changed alerting and contact management rather than the definitions. One national surveillance system has no equivalent definition for the staphylococcal form at all, and units differ between regions.',
    briefIn: ['toxic-shock-a-definition-that-cannot-close'],
  },
  {
    id: 'possible-sepsis-presentation-and-resolution-are-authored',
    headline: 'One authored resolution stands in for a genuinely two-sided question.',
    simplification: 'The case supplies one fixed presentation and one authored resolution in which concern persists and a source is found. No infection, host-response, or antimicrobial model runs underneath.',
    whereItMisleads: 'A learner concludes that investigation always confirms infection, and therefore that the tier was academic.',
    correctUnderstanding: 'In comparable populations roughly a third of patients treated empirically for suspected sepsis turn out to have no bacterial infection, with viral illness, volume overload, drug effect, and hypovolaemia among the commonest alternatives. The other resolution is real and common; this scenario authors the one where concern persists, so that the ceiling still binds and the lesson cannot be read as permission to stand down.',
    briefIn: ['possible-sepsis-a-clock-that-runs-either-way'],
  },
  {
    id: 'possible-sepsis-controls-are-recording-and-bounded-intent-only',
    headline: 'There is no waiting action, and the learner never assigns the tier.',
    simplification: 'The learner records the time of first suspicion, records the uncertainty, requests a time-limited assessment against the displayed ceiling, records bounded antimicrobial intent, reviews the tiers, and arranges close monitoring. No agent, dose, route, combination, fluid volume, vasoactive agent, or procedure exists.',
    whereItMisleads: 'A bounded assessment is read as permission to observe, or the learner believes classifying the likelihood tier is part of the job.',
    correctUnderstanding: 'Observation and a time-limited assessment against a recorded ceiling are different decisions, and only the second is what the guidance permits. The likelihood classification belongs to the qualified team, and the operational definitions separating possible from probable were not retrievable at authoring time, so this lesson deliberately does not supply them.',
    briefIn: ['possible-sepsis-a-clock-that-runs-either-way'],
  },
  {
    id: 'possible-sepsis-tiers-rest-on-very-low-certainty-and-a-contested-measure',
    headline: 'Conditional does not mean optional, and the measure has not softened.',
    simplification: 'The case states the tiered structure, the one-hour target for shock and for probable or definite sepsis, and the three-hour ceiling for possible sepsis without shock.',
    whereItMisleads: 'A learner reads conditional as optional, or reads the three-hour path as a general licence to be slower.',
    correctUnderstanding: 'Every tier rests on very low certainty of evidence, including the strong recommendations, so the grades separate confidence in the direction rather than the importance of acting. The national quality measure is still built around the one-hour clock and has moved into value-based purchasing, so a three-hour path can be guideline-endorsed and still be measured against a faster clock; that tension is a system fact for the debrief rather than a clinical instruction. Statement numbers for the current guidance were not retrievable at authoring time, so wording is taken from the issuing society page rather than the article.',
    briefIn: ['possible-sepsis-a-clock-that-runs-either-way'],
  },
  {
    id: 'septic-shock-presentation-and-trial-response-are-authored',
    headline: 'One authored trial response stands in for a genuinely variable one.',
    simplification: 'The case supplies one fixed presentation and one authored resuscitation response in which the mean pressure is held at 68 mmHg on vasopressor support with a lactate of 3.1 mmol/L. No fluid, vasoactive, host-response, or antimicrobial model runs underneath.',
    whereItMisleads: 'A learner concludes that resuscitation reliably produces this response, or that the label was inevitable.',
    correctUnderstanding: 'The response to a fluid trial varies, and so therefore does the label. Roughly one in five patients meeting older septic shock criteria fail the current ones, almost all by missing the lactate threshold while on vasopressors. This scenario authors one response so the definitional point can be made cleanly; it is not evidence about how often that response occurs.',
    briefIn: ['septic-shock-a-label-the-treatment-creates'],
  },
  {
    id: 'septic-shock-controls-are-recording-and-bounded-intent-only',
    headline: 'The learner never selects a fluid, an agent, or a target.',
    simplification: 'The learner records measured hypoperfusion, activates critical care, records the classification as open, records bounded resuscitation intent, reviews the targets, arranges monitoring, and reassesses. No fluid volume, rate, vasoactive agent, dose, endpoint, antimicrobial, steroid, or procedure exists.',
    whereItMisleads: 'The bounded intent is read as a fluid prescription, or the refusal to apply the label early is read as diagnostic hesitancy.',
    correctUnderstanding: 'The resuscitation is qualified-team work throughout. Declining to apply the label before the trial is not hesitancy: two of the three criteria describe a treatment that has not happened, so they have no truth value yet. The consensus task force declined to define what makes resuscitation adequate, precisely because it is user dependent.',
    briefIn: ['septic-shock-a-label-the-treatment-creates'],
  },
  {
    id: 'septic-shock-targets-are-comparative-and-low-certainty',
    headline: 'The pressure target is comparative, and the lactate is not an oxygen meter.',
    simplification: 'The case states a mean arterial pressure target of 65 mmHg, an age-specific range of 60 to 65 mmHg, at least 30 mL/kg of crystalloid in the first three hours, and serial lactate to guide resuscitation.',
    whereItMisleads: 'A learner reads 65 as a proven optimum, 30 mL/kg as a mandate, or a falling lactate as a measure of restored tissue oxygenation.',
    correctUnderstanding: 'The recommendation is 65 over higher targets on moderate certainty; it does not establish 65 as superior to lower, and 60 to 65 is now suggested for adults 65 or older. The fluid volume is a conditional suggestion on low certainty, hedged with an explicit warning about over-resuscitation, and restrictive and liberal strategies have not separated on mortality. An elevated lactate in sepsis reflects adrenergically stimulated aerobic glycolysis and reduced hepatic clearance as well as perfusion, so guidance directs individualizing after the initial bolus by watching the decrement rather than continuing fluids until normalization.',
    briefIn: ['septic-shock-a-label-the-treatment-creates'],
  },
  {
    id: 'meningitis-imaging-presentation-and-scan-result-are-authored',
    headline: 'One authored scan result stands in for a distribution of them.',
    simplification: 'The case supplies one fixed presentation and one authored scan reporting no space-occupying lesion and no midline shift, changing no management. No infection, imaging, or antimicrobial model runs underneath, and the neurology deliberately never changes.',
    whereItMisleads: 'A learner concludes that pre-puncture imaging is always negative, or that a scan can be skipped on that basis.',
    correctUnderstanding: 'Scans before lumbar puncture are usually normal and rarely alter management, but not always, and the features that would change the answer are exactly the ones that can evolve during a wait. The neurology is held still here so the disagreement between the criteria sets stays visible; a deterioration would make this a different lesson about escalation, in which imaging may well be indicated under every set.',
    briefIn: ['meningitis-imaging-a-rule-that-does-not-agree'],
  },
  {
    id: 'meningitis-imaging-controls-are-recording-and-comparison-only',
    headline: 'The learner records and compares; nobody here orders a scan.',
    simplification: 'The learner records the triggering features and their absences, activates time-critical ownership, records bounded antimicrobial intent, compares five published criteria sets, reviews the boundaries, and arranges monitoring. No agent, dose, route, combination, adjunct, imaging request, interpretation, lumbar puncture, or procedure exists.',
    whereItMisleads: 'A learner believes choosing the imaging pathway was theirs to make, or that comparing the criteria sets is how the decision is made in practice.',
    correctUnderstanding: 'In most settings the pathway follows the local rule set rather than a bedside judgement, which is why the authored progression has the unit apply its own criteria and send the patient for imaging without the learner choosing it. Recognizing which rule set you are standing in is the transferable skill; adjudicating between them at the bedside is not.',
    briefIn: ['meningitis-imaging-a-rule-that-does-not-agree'],
  },
  {
    id: 'meningitis-imaging-criteria-disagreement-is-the-lesson-not-a-verdict',
    headline: 'This scenario does not tell you which criteria set is right.',
    simplification: 'The case states five published criteria sets and what each says about this one patient, alongside a cohort study associating prompt lumbar puncture with lower mortality and more patients treated inside the hour.',
    whereItMisleads: 'A learner reads the scenario as endorsing the most permissive rule set, or as evidence that imaging before puncture causes death.',
    correctUnderstanding: 'The mortality comparison is observational and confounding by indication is not excluded: sicker patients are imaged more often. What the evidence supports is that the disagreement is real, that the delay is measurable, and that one widely cited set is archived by its own issuing society with a 2004 data cutoff. Which set a unit adopts is a governance decision made above the bedside, and this scenario reports the disagreement rather than settling it.',
    briefIn: ['meningitis-imaging-a-rule-that-does-not-agree'],
  },
];
