/**
 * The neonatology module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a neonatology scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const NEONATOLOGY_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'term-newborn-transition-antenatal-birth-newborn-parent-and-qualified-course-reports-are-authored',
    headline: 'The antenatal, birth, newborn, parent, qualified care, and 1-hour transition reports are authored.',
    simplification: 'Fixed reports stand in for record review, newborn examination and observation, shared-clock documentation, cord care, drying, skin-to-skin positioning, thermal protection, feeding support, parent assessment, communication, and serial review. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal hemodynamic validation.',
    whereItMisleads: 'Treating gestation, breathing, tone, heart rate, temperature, absent supplied risks, or the stable 1-hour report as learner findings, universal reassurance thresholds, care effects, discharge readiness, prognosis, or outcome.',
    correctUnderstanding: 'Normal transition still requires prepared attendance, direct ongoing breathing and temperature observation, protected positioning, parent-dyad support, and immediate escalation when the pattern changes.',
    briefIn: ['term-newborn-transition'],
  },
  {
    id: 'term-newborn-transition-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls confirm support, connect supplied facts, review transition and protective care, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, obstetric, midwifery, nursing, feeding, leadership, timekeeping, documentation, communication, dignity, parent, family, staff-support, escalation, and handoff work.',
    whereItMisleads: 'Equating button order with newborn examination, scoring, observation, cord care, positioning, thermal care, feeding support, communication quality, or competence.',
    correctUnderstanding: 'Real newborn care is concurrent, physical, relational, time-aware, locally protocolized, and responsive to change. Cognitive sequence practice cannot replace direct care or hands-on simulation.',
    briefIn: ['term-newborn-transition'],
  },
  {
    id: 'no-live-term-newborn-exam-monitor-score-cord-care-resuscitation-feeding-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, score, monitor, perform cord or thermal care, feed, resuscitate, determine disposition, or report outcome.',
    simplification: 'No live breathing, heart-rate, tone, color, temperature, glucose, feeding, parent or other assessment; Apgar scoring; cord clamping; positioning; drying; warming; suction; stimulation; separation; oxygen; ventilation; airway care; compressions; access; fluid; glucose; drug or dose; feeding; resuscitation; transport; counseling; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as newborn assessment, cord, skin-to-skin, warming, oxygen, feeding, resuscitation, discharge, or outcome instruction; delaying trained care for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local newborn-transition and resuscitation protocols, trained teams, protected parent-newborn positioning, respectful communication, and hands-on simulation.',
    briefIn: ['term-newborn-transition'],
  },
  {
    id: 'neonatal-apnea-birth-initial-step-newborn-parent-and-qualified-course-reports-are-authored',
    headline: 'The birth, initial steps, apnea, heart-rate, parent, qualified ventilation, and 90-second reports are authored.',
    simplification: 'Fixed reports stand in for record review, newborn examination, heart-rate and oxygenation assessment, initial steps, mask ventilation, chest-movement assessment, thermal care, response monitoring, parent communication, and serial review. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal physiology validation.',
    whereItMisleads: 'Treating the birth clock, apnea, heart rate, tone, temperature, visible chest movement, or early response as learner findings, universal technical success, durable breathing, stable transition, prognosis, or outcome.',
    correctUnderstanding: 'Apnea or gasping and heart rate below 100/min after initial steps require immediate qualified assisted ventilation, direct assessment of effectiveness, heart-rate response, warmth, monitoring, and escalation when indicated.',
    briefIn: ['neonatal-apnea'],
  },
  {
    id: 'neonatal-apnea-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate qualified help, connect supplied facts, review threshold and readiness, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, airway, ventilation, heart-rate, monitoring, thermal, pharmacy, transport, leadership, timekeeping, documentation, communication, dignity, parent, family, staff-support, escalation, and handoff work.',
    whereItMisleads: 'Equating button order with examination, scoring, ventilation skill, mask seal, airway management, oxygen titration, medication choice, communication quality, or competence.',
    correctUnderstanding: 'Real newborn resuscitation is concurrent, physical, time-critical, team-based, locally protocolized, and verified through direct chest-movement and heart-rate response. Cognitive practice cannot replace hands-on simulation.',
    briefIn: ['neonatal-apnea'],
  },
  {
    id: 'no-live-neonatal-apnea-exam-monitor-score-ventilation-oxygen-airway-drug-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, score, monitor, ventilate, give oxygen or a drug, manage an airway, determine disposition, or report outcome.',
    simplification: 'No live breathing, heart-rate, tone, color, temperature, glucose, neurologic, parent or other assessment; Apgar scoring; position; drying; warming; suction; stimulation; separation; oxygen; mask ventilation; seal or pressure correction; alternative airway; compressions; access; fluid; glucose; drug or dose; feeding; resuscitation; transport; counseling; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as ventilation technique, oxygen, airway, compression, medication, transfer, or disposition instruction; delaying trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local neonatal-resuscitation protocols and equipment, immediate trained teams, continuous response assessment, respectful parent communication, and hands-on simulation.',
    briefIn: ['neonatal-apnea'],
  },
  {
    id: 'ineffective-neonatal-ventilation-birth-interface-response-parent-and-qualified-course-reports-are-authored',
    headline: 'The birth, interface, response, parent, qualified correction, and 2-minute reports are authored.',
    simplification: 'Fixed reports stand in for record review, newborn examination, heart-rate and oxygenation assessment, mask and airway assessment, ventilation delivery, chest-movement review, corrective steps, thermal care, equipment checks, parent communication, and serial reassessment. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal physiology validation.',
    whereItMisleads: 'Treating the birth clock, interface, absent chest movement, heart-rate trajectory, oxygenation, corrected leak, or early response as learner findings, technical performance, durable breathing, stable transition, prognosis, or outcome.',
    correctUnderstanding: 'Failure of heart rate to rise during newborn ventilation requires immediate qualified effectiveness correction, with chest movement as a secondary sign and escalation based on the response to adequate ventilation.',
    briefIn: ['ineffective-ventilation-correction'],
  },
  {
    id: 'ineffective-neonatal-ventilation-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate qualified help, connect supplied facts, review effectiveness and correction boundaries, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, airway, ventilation, heart-rate, monitoring, thermal, equipment, pharmacy, transport, leadership, timekeeping, documentation, communication, dignity, parent, family, staff-support, escalation, and handoff work.',
    whereItMisleads: 'Equating button order with examination, scoring, mask seal, ventilation skill, corrective-step performance, airway management, oxygen titration, compression readiness, communication quality, or competence.',
    correctUnderstanding: 'Real newborn resuscitation is concurrent, physical, time-critical, team-based, locally protocolized, and verified through direct heart-rate and chest-movement reassessment. Cognitive practice cannot replace hands-on simulation.',
    briefIn: ['ineffective-ventilation-correction'],
  },
  {
    id: 'no-live-ineffective-neonatal-ventilation-exam-monitor-device-oxygen-airway-compression-drug-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, monitor, handle a device, ventilate, manage an airway, compress, give oxygen or a drug, determine disposition, or report outcome.',
    simplification: 'No live breathing, heart-rate, chest-movement, tone, color, temperature, glucose, neurologic, parent or other assessment; scoring; mask or device handling; position; suction; stimulation; separation; pressure, rate, PEEP or oxygen selection; ventilation; corrective step; airway placement; compression; access; fluid; glucose; drug or dose; feeding; resuscitation; transport; counseling; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as mask ventilation, corrective-step, oxygen, airway, compression, medication, transfer, or disposition instruction; delaying trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local neonatal-resuscitation protocols and equipment, immediate trained teams, continuous response assessment, respectful parent communication, and hands-on simulation.',
    briefIn: ['ineffective-ventilation-correction'],
  },
  {
    id: 'neonatal-bradycardia-birth-ventilation-airway-parent-and-qualified-course-reports-are-authored',
    headline: 'The birth, adequate-ventilation, airway, heart-rate, parent, qualified response, and 3-minute reports are authored.',
    simplification: 'Fixed reports stand in for record review, newborn examination, heart-rate and oxygenation assessment, ventilation correction and delivery, airway placement and verification, chest movement, compressions, thermal care, equipment and access readiness, parent communication, and serial reassessment. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal physiology validation.',
    whereItMisleads: 'Treating ventilation adequacy, airway placement, chest movement, heart rate 48/min, oxygenation, or the early heart-rate rise as learner findings, technical performance, universal treatment effect, durable recovery, prognosis, or outcome.',
    correctUnderstanding: 'Persistent heart rate below 60/min triggers compressions only after qualified ventilation has demonstrably inflated the lungs; ongoing response and cause assessment remain essential.',
    briefIn: ['neonatal-bradycardia'],
  },
  {
    id: 'neonatal-bradycardia-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate qualified help, connect supplied facts, review threshold and coordination boundaries, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, airway, ventilation, compression, heart-rate, monitoring, thermal, equipment, access, pharmacy, transport, leadership, timekeeping, documentation, communication, dignity, parent, family, staff-support, escalation, and handoff work.',
    whereItMisleads: 'Equating button order with examination, scoring, ventilation or airway verification, compression skill, oxygen strategy, access or medication readiness, communication quality, or competence.',
    correctUnderstanding: 'Real advanced newborn resuscitation is concurrent, physical, time-critical, team-based, locally protocolized, and verified through direct assessment. Cognitive practice cannot replace hands-on simulation.',
    briefIn: ['neonatal-bradycardia'],
  },
  {
    id: 'no-live-neonatal-bradycardia-exam-monitor-ventilation-airway-compression-access-drug-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, monitor, ventilate, place an airway, compress, obtain access, give a drug, determine disposition, or report outcome.',
    simplification: 'No live breathing, heart-rate, chest-movement, tone, color, temperature, perfusion, glucose, neurologic, parent or other assessment; scoring; device handling; pressure, rate, PEEP or oxygen selection; ventilation; airway placement or verification; compression; access; fluid; blood; glucose; epinephrine or other drug or dose; feeding; resuscitation; transport; counseling; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as ventilation, airway, compression, oxygen, access, epinephrine, fluid, blood, transfer, or disposition instruction; delaying trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local neonatal-resuscitation protocols and equipment, immediate trained teams, continuous response assessment, respectful parent communication, and hands-on simulation.',
    briefIn: ['neonatal-bradycardia'],
  },
  {
    id: 'meconium-stained-transition-birth-fluid-newborn-parent-and-qualified-course-reports-are-authored',
    headline: 'The birth, meconium, newborn, parent, qualified care, and 30-minute respiratory reports are authored.',
    simplification: 'Fixed reports stand in for record review, newborn examination and observation, fluid characterization, airway assessment, thermal care, protected skin-to-skin positioning, parent assessment, communication, and serial review. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal physiology validation.',
    whereItMisleads: 'Treating meconium character, breathing, tone, heart rate, airway visibility, absent supplied obstruction, or the stable 30-minute report as learner findings, excluded disease, durable safety, feeding success, prognosis, or outcome.',
    correctUnderstanding: 'Meconium staining increases observation needs but does not itself justify routine suction; direct respiratory and airway assessment determines whether selective clearing or resuscitation is needed.',
    briefIn: ['meconium-stained-transition'],
  },
  {
    id: 'meconium-stained-transition-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls confirm support, connect supplied facts, review transition and selective-airway-clearing boundaries, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, obstetric, midwifery, nursing, airway, thermal, feeding, leadership, timekeeping, documentation, communication, dignity, parent, family, staff-support, escalation, and handoff work.',
    whereItMisleads: 'Equating button order with newborn examination, scoring, respiratory observation, suction or airway judgment, thermal care, communication quality, or competence.',
    correctUnderstanding: 'Real newborn care is concurrent, physical, relational, time-aware, locally protocolized, and responsive to obstruction or respiratory change. Cognitive practice cannot replace direct care or hands-on simulation.',
    briefIn: ['meconium-stained-transition'],
  },
  {
    id: 'no-live-meconium-transition-exam-monitor-score-suction-airway-resuscitation-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, score, monitor, suction, manage an airway, resuscitate, determine disposition, or report outcome.',
    simplification: 'No live breathing, heart-rate, tone, color, temperature, obstruction, glucose, feeding, parent or other assessment; scoring; positioning; drying; warming; suction; stimulation; separation; device handling; oxygen; ventilation; airway care; compression; access; fluid; glucose; drug or dose; feeding; resuscitation; transport; counseling; procedure; diagnosis of meconium aspiration; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as suction, airway, oxygen, respiratory-treatment, feeding, transfer, or disposition instruction; delaying trained assessment for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local newborn-transition and resuscitation protocols, trained teams, selective airway clearing only when indicated, respectful parent communication, and hands-on simulation.',
    briefIn: ['meconium-stained-transition'],
  },
  {
    id: 'preterm-respiratory-distress-gestation-newborn-parent-and-qualified-course-reports-are-authored',
    headline: 'The gestation, newborn, parent, qualified support, and 10-minute respiratory reports are authored.',
    simplification: 'Fixed reports stand in for record review, newborn examination and observation, work-of-breathing assessment, preductal pulse oximetry, CPAP and oxygen operation, thermal care, parent assessment, communication, and serial review. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal physiology validation.',
    whereItMisleads: 'Treating gestation, breathing, work, heart rate, oxygenation, temperature, or the 10-minute report as learner findings, proof of adequate ventilation, excluded disease, durable stability, prognosis, or outcome.',
    correctUnderstanding: 'A spontaneously breathing preterm infant with distress may benefit from qualified CPAP, oxygen titrated to verified preductal saturation, thermal protection, continuous reassessment, and escalation when breathing becomes ineffective.',
    briefIn: ['preterm-respiratory-distress'],
  },
  {
    id: 'preterm-respiratory-distress-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls confirm support, connect supplied facts, review respiratory and thermal boundaries, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, respiratory, airway, thermal, monitoring, transport, nursing, leadership, timekeeping, documentation, communication, dignity, parent, family, staff-support, escalation, and handoff work.',
    whereItMisleads: 'Equating button order with newborn examination, monitoring interpretation, CPAP or oxygen operation, thermal care, airway judgment, communication quality, or competence.',
    correctUnderstanding: 'Real preterm stabilization is concurrent, physical, time-critical, team-based, locally protocolized, and continuously reassessed. Cognitive practice cannot replace direct care or hands-on simulation.',
    briefIn: ['preterm-respiratory-distress'],
  },
  {
    id: 'no-live-preterm-newborn-exam-monitor-score-cpap-oxygen-thermal-airway-resuscitation-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, score, monitor, operate CPAP or oxygen, provide thermal or airway care, resuscitate, determine disposition, or report outcome.',
    simplification: 'No live breathing, heart-rate, work, color, temperature, oxygenation, glucose, neurologic, parent or other assessment; scoring; positioning; drying; stimulation; wrapping; warming or cooling; device handling; CPAP; oxygen; setting selection; suction; ventilation; airway care; compression; access; fluid; glucose; surfactant; drug or dose; feeding; resuscitation; transport; counseling; procedure; diagnosis; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as CPAP, oxygen, thermal, airway, surfactant, respiratory-treatment, transfer, or disposition instruction; delaying trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local neonatal-resuscitation and preterm-stabilization protocols and equipment, immediate trained teams, continuous response assessment, respectful parent communication, and hands-on simulation.',
    briefIn: ['preterm-respiratory-distress'],
  },
  {
    id: 'neonatal-hypoglycemia-risk-signs-glucose-parent-and-qualified-course-reports-are-authored',
    headline: 'The risk, signs, glucose values, parent, qualified care, and 30-minute reports are authored.',
    simplification: 'Fixed reports stand in for history, newborn examination, bedside and laboratory glucose acquisition, assay limitations, neurologic and feeding assessment, thermal care, parent assessment, locally protocolized treatment, and serial review. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal physiology validation.',
    whereItMisleads: 'Treating jitteriness, feeding difficulty, glucose values, or the later improved value as learner findings, a universal definition, predicted brain injury, proven treatment effect, excluded cause, durable stability, prognosis, or outcome.',
    correctUnderstanding: 'Neonatal glucose decisions combine verified values, clinical signs, age, risk, assay, repeat trajectory, and the current local pathway. Borderline thresholds and treatment details vary.',
    briefIn: ['neonatal-hypoglycemia'],
  },
  {
    id: 'neonatal-hypoglycemia-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls confirm support, connect supplied facts, review local-protocol boundaries, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, glucose, feeding, neurologic, laboratory, endocrine, metabolic, nursing, leadership, timekeeping, documentation, communication, dignity, parent, family, escalation, and follow-up work.',
    whereItMisleads: 'Equating button order with history, examination, glucose measurement or interpretation, diagnosis, feeding, dextrose treatment, access, communication quality, or competence.',
    correctUnderstanding: 'Real neonatal hypoglycemia care is concurrent, physical, relational, time-aware, assay-aware, locally protocolized, and serially reassessed. Cognitive practice cannot replace direct care.',
    briefIn: ['neonatal-hypoglycemia'],
  },
  {
    id: 'no-live-neonatal-hypoglycemia-exam-glucose-test-feed-dextrose-drug-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, measure or interpret glucose, feed, give dextrose or another drug, determine disposition, or report outcome.',
    simplification: 'No live history, breathing, heart-rate, neurologic, temperature, feeding, parent or other assessment; scoring; glucose or test acquisition or interpretation; diagnosis; feeding; glucose gel; IV dextrose; fluid; drug or dose; access; thermal care; device handling; oxygen; ventilation; airway care; resuscitation; transport; counseling; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as a universal threshold, assay, feeding, glucose-gel, IV-dextrose, access, monitoring, transfer, or disposition instruction; delaying trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, validated glucose methods, the current local neonatal-hypoglycemia pathway, immediate trained teams for abnormal signs, serial reassessment, respectful parent communication, and hands-on training.',
    briefIn: ['neonatal-hypoglycemia'],
  },
  {
    id: 'neonatal-sepsis-maternal-risk-newborn-parent-and-qualified-course-reports-are-authored',
    headline: 'The maternal risk, newborn illness, parent, qualified care, and 1-hour report are authored.',
    simplification: 'Fixed reports stand in for maternal and newborn history, newborn examination, clinical monitoring, culture and laboratory acquisition, respiratory and circulatory assessment, thermal and glucose care, parent assessment, locally protocolized antimicrobials, investigation, and serial review. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal sepsis physiology validation.',
    whereItMisleads: 'Treating risk factors, multisystem illness, partial physiologic improvement, or a pending culture as learner findings, a calculator result, proven treatment effect, diagnosis, exclusion, durable stability, antimicrobial-duration decision, prognosis, or outcome.',
    correctUnderstanding: 'A clinically ill newborn needs immediate qualified assessment and treatment. Maternal risk, the infant trajectory, direct findings, microbiology, targeted investigation, and serial response all matter; no calculator or isolated laboratory value safely closes the case.',
    briefIn: ['neonatal-sepsis'],
  },
  {
    id: 'neonatal-sepsis-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls confirm support, connect supplied facts, review qualified boundaries, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, infection, respiratory, circulatory, airway-ready, laboratory, pharmacy, nursing, leadership, timekeeping, documentation, communication, dignity, parent, family, stewardship, transport, and follow-up work.',
    whereItMisleads: 'Equating button order with history, examination, risk calculation, culture or test work, diagnosis, antimicrobial or supportive treatment, communication quality, or competence.',
    correctUnderstanding: 'Real neonatal sepsis care is concurrent, physical, relational, time-critical, locally protocolized, microbiology-aware, and serially reassessed. Cognitive practice cannot replace direct care.',
    briefIn: ['neonatal-sepsis'],
  },
  {
    id: 'no-live-neonatal-sepsis-history-exam-monitor-culture-antimicrobial-support-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, test, diagnose, give antimicrobials or support, determine disposition, or report outcome.',
    simplification: 'No live history; newborn examination or scoring; measurement or monitoring; culture, CRP, blood count, glucose, gas, imaging, lumbar puncture, or other test acquisition or interpretation; risk calculation; diagnosis; thermal care; oxygen; respiratory or circulatory support; access; fluid; glucose; antimicrobial, drug, dose, route, or duration selection; feeding; device handling; ventilation; airway care; resuscitation; transport; counseling; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as a risk-calculator, culture, antimicrobial, dose, support, meningitis-evaluation, stewardship, transfer, or disposition instruction; delaying trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, the current local neonatal-infection pathway, prompt trained teams, culture before antibiotics only when it does not delay treatment, continuous supportive care and reassessment, respectful parent communication, and hands-on training.',
    briefIn: ['neonatal-sepsis'],
  },
  {
    id: 'neonatal-thermoregulation-gestation-temperature-environment-parent-and-qualified-course-reports-are-authored',
    headline: 'The gestation, temperatures, environment, parent, qualified rewarming, and 45-minute report are authored.',
    simplification: 'Fixed reports stand in for history, newborn examination, temperature and glucose acquisition, measurement-site limits, environmental and transfer review, feeding assessment, parent assessment, locally protocolized warm-chain care, device surveillance, cause evaluation, and serial review. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal thermal physiology validation.',
    whereItMisleads: 'Treating 35.5°C, the warming-continuity gap, or the later 36.3°C as learner findings, a prescribed rewarming rate, proven treatment effect, determined cause, excluded illness, durable stability, prognosis, or outcome.',
    correctUnderstanding: 'Newborn thermal care combines verified temperature, gestation, size, environment, transfer, direct clinical findings, glucose and feeding risk, illness review, continuous warm-chain care, serial measurement, and avoidance of hyperthermia.',
    briefIn: ['thermoregulation-failure'],
  },
  {
    id: 'neonatal-thermoregulation-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls confirm support, connect supplied facts, review qualified boundaries, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified newborn, thermal, glucose, feeding, respiratory, nursing, medical, infection, neurologic, leadership, timekeeping, documentation, communication, dignity, parent, family, escalation, transfer, and follow-up work.',
    whereItMisleads: 'Equating button order with history, examination, temperature or glucose measurement, diagnosis, warming, device operation, feeding, communication quality, or competence.',
    correctUnderstanding: 'Real neonatal thermoregulation care is concurrent, physical, relational, environment-aware, locally protocolized, continuously monitored, and serially reassessed. Cognitive practice cannot replace direct care.',
    briefIn: ['thermoregulation-failure'],
  },
  {
    id: 'no-live-neonatal-thermoregulation-exam-temperature-monitor-warming-glucose-feed-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, measure temperature, warm, feed, give glucose, determine disposition, or report outcome.',
    simplification: 'No live history; newborn examination or scoring; temperature, glucose, monitoring or other test acquisition or interpretation; diagnosis; warming or cooling; skin-to-skin care; incubator, radiant-warmer or other device operation; set-point or rewarming-rate selection; feeding; glucose, fluid, drug, dose, route or access; oxygen or respiratory support; ventilation; airway care; resuscitation; transport; counseling; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as warmer, incubator, set-point, rewarming-rate, glucose, feeding, therapeutic-hypothermia, transfer, or disposition instruction; delaying trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, calibrated temperature measurement, the current local thermal-care and illness pathways, immediate trained teams, protocolized rewarming with frequent or continuous monitoring, glucose and feeding protection, respectful parent communication, and hands-on training.',
    briefIn: ['thermoregulation-failure'],
  },
  {
    id: 'delivery-room-nicu-perinatal-resuscitation-current-parent-receiver-and-arrival-reports-are-authored',
    headline: 'The perinatal context, resuscitation, current state, parent, receiver check-back, and arrival report are authored.',
    simplification: 'Fixed records stand in for maternal and newborn history, newborn examination, resuscitation chronology, monitor and record review, respiratory and thermal support, pending data, parent assessment, sender-receiver interaction, transport, arrival assessment, and serial review. Hidden adult-oriented engine-schema minimums are scaffolding, not neonatal transport physiology validation.',
    whereItMisleads: 'Treating the resuscitation record, receiver check-back, arrival physiology, glucose, pending cord gas, or parent update as learner findings, performed communication, shared understanding, transport, proven treatment effect, durable stability, prognosis, or outcome.',
    correctUnderstanding: 'Safe transition preserves accurate chronology, current support and response, absent actions, pending data, safety concerns, equipment continuity, questions, check-back, explicit responsibility, next steps, escalation triggers, and family continuity.',
    briefIn: ['delivery-room-to-nicu-handoff'],
  },
  {
    id: 'delivery-room-nicu-controls-activate-reconcile-review-check-back-and-handoff-only',
    headline: 'The controls confirm ownership, connect supplied facts, review content and boundaries, read fixed reports, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified sending, receiving, transport, respiratory, monitoring, nursing, medical, documentation, leadership, timekeeping, escalation, communication, dignity, parent, family, and reunification work.',
    whereItMisleads: 'Equating button order with history, examination, record interpretation, handoff accuracy, listening, check-back, shared understanding, transport, parent communication, documentation, or competence.',
    correctUnderstanding: 'Real handoff is an interactive transfer of information, authority, and responsibility with questions, clarification, confirmation, continuity, and adaptation to the receiving team and family.',
    briefIn: ['delivery-room-to-nicu-handoff'],
  },
  {
    id: 'no-live-delivery-room-nicu-exam-monitor-support-transport-communication-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, monitor, support, transport, communicate, determine disposition, or report outcome.',
    simplification: 'No live history; newborn examination or scoring; monitor, record, glucose, gas or other test acquisition or interpretation; diagnosis; warming or cooling; CPAP, oxygen, monitor or device operation; setting selection; respiratory support; ventilation; airway care; access; glucose, fluid, blood, drug or dose; feeding; resuscitation; movement, positioning or transport; calling, speaking, listening, check-back, documentation, counseling, parent update; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as CPAP, oxygen, transport-equipment, route, handoff-script, documentation, parent-communication, transfer, or disposition instruction; delaying a real transition for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, the current local neonatal-resuscitation, transport and NICU pathways, trained sending and receiving teams, reliable equipment, closed-loop communication, explicit ownership, respectful parent support, and hands-on team simulation.',
    briefIn: ['delivery-room-to-nicu-handoff'],
  },
  {
    id: 'neonatal-tension-pneumothorax-support-change-asymmetry-compromise-and-response-are-authored',
    headline: 'The respiratory support, sudden deterioration, asymmetric findings, compromise, and response are authored.',
    simplification: 'Fixed qualified-team reports stand in for history, direct examination, auscultation, circuit and airway checks, monitoring, imaging, gas and test interpretation, oxygenation, ventilation, decompression, drain preparation, analgesia, and serial reassessment. Hidden adult-oriented engine-schema minimums are scaffolding, not validated neonatal respiratory mechanics or pleural-pressure physiology.',
    whereItMisleads: 'Treating the unilateral findings, presumed mechanism, vital-sign trajectory, device report, or partial postdecompression improvement as learner findings, diagnostic confirmation, excluded alternatives, proven treatment effect, resolved air leak, durable stability, prognosis, or outcome.',
    correctUnderstanding: 'A suddenly deteriorating newborn during positive-pressure support needs immediate direct qualified assessment of airway, breathing, circulation, equipment, asymmetric findings, and reversible threats; significant cardiopulmonary compromise with suspected tension pneumothorax demands urgent locally protocolized action.',
    briefIn: ['neonatal-tension-pneumothorax'],
  },
  {
    id: 'neonatal-tension-pneumothorax-controls-activate-reconcile-recognize-review-reassess-and-handoff-only',
    headline: 'The controls activate support, connect supplied facts, recognize, review, reassess, and hand off only.',
    simplification: 'Six cognitive actions stand in for concurrent qualified neonatal emergency leadership, airway and ventilator assessment, oxygenation and ventilation, decompression, drain, monitoring, analgesia, imaging, nursing, documentation, family, dignity, escalation, transfer, and follow-up work.',
    whereItMisleads: 'Equating button order with examination, diagnosis, crisis leadership, equipment use, procedural skill, clinical judgment, communication, documentation, or competence.',
    correctUnderstanding: 'Real neonatal tension pneumothorax care requires trained teams, direct findings, hands-on equipment and procedural competence, local pathways, human factors, serial reassessment, and family-centered communication.',
    briefIn: ['neonatal-tension-pneumothorax'],
  },
  {
    id: 'no-live-neonatal-tension-pneumothorax-exam-device-support-decompression-drain-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, operate support, decompress, drain, determine disposition, or report outcome.',
    simplification: 'No live history; examination, auscultation, transillumination, imaging, measurement, monitoring, gas or test acquisition or interpretation; circuit, airway, ventilator, oxygen or device check or operation; pressure, volume, rate, oxygen, PEEP, equipment, needle, catheter, drain or site selection; positioning; oxygenation; ventilation; airway care; decompression; drainage; analgesia; access; fluid, blood, drug or dose; resuscitation; transport; communication; documentation; counseling; parent update; diagnosis; procedure; disposition; prognosis; or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as needle, catheter, drain, landmark, ventilator, oxygen, analgesia, imaging, transport, or disposition instruction; delaying real emergency care for a click or radiograph; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, the current local neonatal emergency and pneumothorax pathway, appropriate monitoring and equipment, qualified procedural teams, immediate escalation, serial reassessment, respectful parent support, and hands-on simulation.',
    briefIn: ['neonatal-tension-pneumothorax'],
  },
];
