/**
 * The neurology module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a neurology scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const NEUROLOGY_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'minor-nondisabling-stroke-deficit-function-imaging-care-and-later-state-are-authored',
    headline: 'The clock, deficit, individualized function, imaging, physiology, care context, and later trajectory are authored.',
    simplification: 'Fixed qualified reports stand in for history, neurological and functional examination, NIHSS, glucose, CT and CTA, disability review, mimic assessment, treatment-strategy review, surveillance, and serial reassessment.',
    whereItMisleads: 'Treating the fictional values, NIHSS, functional statements, imaging, negative snapshots, nondisabling label, strict-later stability, or care intent as learner-acquired evidence, universal disability classification, diagnosis, eligibility decision, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires immediate verified stroke-system assessment, patient-specific function and goals, direct examination, appropriate imaging and testing, qualified treatment decisions, and continuous neurological and whole-patient reassessment.',
    briefIn: ['minor-nondisabling-acute-ischemic-stroke'],
  },
  {
    id: 'minor-nondisabling-stroke-controls-reconcile-review-recognize-record-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, fixed-context review, individualized boundary recognition, qualified intent, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced stroke neurology, emergency, nursing, pharmacy, radiology, rehabilitation, and prevention assessment, treatment planning, monitoring, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, NIHSS or disability assessment, imaging interpretation, diagnosis, mimic exclusion, prescribing, drug delivery, reperfusion adjudication, surveillance skill, rehabilitation assessment, disposition, or stroke competence.',
    correctUnderstanding: 'Actual care requires the patient, trained stroke teams, current local pathways, verified patient-specific data, individualized disability assessment rather than score alone, qualified treatment, and continuous change-triggered reassessment.',
    briefIn: ['minor-nondisabling-acute-ischemic-stroke'],
  },
  {
    id: 'no-live-minor-stroke-exam-score-imaging-drug-reperfusion-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, score, image, choose or deliver a drug, perform reperfusion, decide disposition, or report outcome.',
    simplification: 'No live history, neurological or functional examination, NIHSS calculation, glucose or pressure measurement, CT, CTA, ECG, laboratory or swallowing-test acquisition or interpretation, diagnosis, mimic exclusion, disability or eligibility adjudication, antiplatelet product, combination, dose, duration, route, access, prescription, preparation or delivery, thrombolytic, blood-pressure treatment, EVT, procedure, rehabilitation prescription, admission, discharge, prognosis, or outcome is modeled.',
    whereItMisleads: 'Treating low NIHSS or a sensory syndrome as automatically nondisabling, treating no LVO as low risk, copying fictional values into care, assuming one antiplatelet strategy is universal, reading short-window stability as resolution, treating normal CT as ischemic-stroke exclusion, or using completion as clinical competence.',
    correctUnderstanding: 'Use verified patient findings, individualized functional consequences and preferences, current stroke guidance, qualified teams, patient-specific bleeding and etiologic context, appropriate imaging and testing, and repeated neurological surveillance.',
    briefIn: ['minor-nondisabling-acute-ischemic-stroke'],
  },
  {
    id: 'basilar-lvo-clock-neurologic-imaging-selection-and-later-state-are-authored',
    headline: 'The clock, neurological findings, imaging, selection context, care ownership, and later state are authored.',
    simplification: 'Fixed qualified reports stand in for history, examination, NIHSS and mRS, glucose, CT, CTA, pc-ASPECTS, mimic review, endovascular and airway planning, and serial reassessment.',
    whereItMisleads: 'Treating fictional values, scores, imaging, negative snapshots, secretion handling, ownership, or later persistence as learner-acquired evidence, diagnosis, eligibility, treatment effect, durable airway safety, or predicted course.',
    correctUnderstanding: 'Real care requires immediate verified stroke-system assessment, direct examination, appropriate imaging, qualified individualized reperfusion and airway decisions, and continuous neurological and whole-patient reassessment.',
    briefIn: ['basilar-artery-occlusion-escalation'],
  },
  {
    id: 'basilar-lvo-controls-reconcile-review-recognize-activate-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, fixed-evidence review, escalation recognition, qualified ownership, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced stroke neurology, emergency, nursing, neuroradiology, neurointerventional, airway, critical-care, and transport assessment, treatment planning, monitoring, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, score or imaging interpretation, eligibility adjudication, airway management, transfer, thrombectomy, reperfusion assessment, team performance, disposition, or stroke competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current local pathways, verified patient-specific data, qualified treatment decisions, rapid endovascular access, and continuous change-triggered reassessment.',
    briefIn: ['basilar-artery-occlusion-escalation'],
  },
  {
    id: 'no-live-basilar-lvo-exam-score-imaging-drug-airway-transfer-thrombectomy-reperfusion-disposition-or-outcome',
    headline: 'The lab does not examine, score, image, choose a drug, manage an airway, transfer, perform thrombectomy, or report outcome.',
    simplification: 'No live history, examination, NIHSS, mRS or pc-ASPECTS calculation, glucose or pressure measurement, imaging or test acquisition or interpretation, diagnosis, eligibility adjudication, drug, dose, route, blood-pressure target, airway device, transport, EVT technique, reperfusion grade, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using supplied selection facts as universal eligibility, delaying escalation for a treatment response, treating current secretion handling as durable airway safety, treating negative snapshots as exclusions, copying fictional values into care, or using completion as clinical competence.',
    correctUnderstanding: 'Use verified patient findings, current stroke guidance, qualified multidisciplinary teams, local systems, individualized benefit-risk decisions, prompt endovascular escalation, airway readiness, and repeated surveillance.',
    briefIn: ['basilar-artery-occlusion-escalation'],
  },
  {
    id: 'cerebellar-ich-clock-neurologic-imaging-care-and-later-state-are-authored',
    headline: 'The clock, neurological findings, imaging, physiology, care ownership, and later deterioration are authored.',
    simplification: 'Fixed qualified reports stand in for history, examination, glucose, CT, hemorrhage-volume review, posterior-fossa threat assessment, airway surveillance, multidisciplinary escalation, and serial reassessment.',
    whereItMisleads: 'Treating fictional findings, volumes, negative snapshots, later hydrocephalus or brainstem compression, weaker cough, or named ownership as learner-acquired evidence, modeled physiology, diagnosis, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires direct repeated assessment, verified imaging, trained stroke, neurocritical, neurosurgical, airway, radiology, and nursing teams, patient-specific decisions, and continuous deterioration surveillance.',
    briefIn: ['spontaneous-cerebellar-intracerebral-hemorrhage'],
  },
  {
    id: 'cerebellar-ich-controls-reconcile-review-recognize-activate-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, fixed-context review, danger recognition, qualified ownership, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced neurological, neurocritical, neurosurgical, emergency, airway, radiology, nursing, and transfer assessment, planning, monitoring, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, image or airway assessment, hemorrhage-volume calculation, treatment selection, surgical decision-making, team performance, transfer, disposition, or clinical competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current pathways, verified findings, rapid escalation, individualized goals and treatment decisions, and continuous change-triggered reassessment.',
    briefIn: ['spontaneous-cerebellar-intracerebral-hemorrhage'],
  },
  {
    id: 'no-live-cerebellar-ich-exam-score-imaging-drug-airway-device-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, score, image, prescribe, manage an airway or device, perform a procedure, decide disposition, or report outcome.',
    simplification: 'No live history, examination, score or volume calculation, glucose or vital measurement, CT or other test acquisition or interpretation, diagnosis, drug, blood-pressure target, reversal, oxygen, airway device, ventilation, drain, surgery, procedure, transfer mechanics, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using one volume or finding as an isolated universal rule, treating absent initial hydrocephalus as reassurance, delaying escalation until herniation, copying fictional values into care, inferring functional benefit, or using completion as clinical competence.',
    correctUnderstanding: 'Use verified serial patient findings, current ICH guidance, qualified multidisciplinary teams, locally available capabilities, patient-specific goals, and urgent individualized response to posterior-fossa deterioration.',
    briefIn: ['spontaneous-cerebellar-intracerebral-hemorrhage'],
  },
  {
    id: 'asah-deterioration-clock-neurologic-imaging-care-and-later-state-are-authored',
    headline: 'The aSAH day, aneurysm record, deficit clock, neurological findings, imaging, physiology, care, and later state are authored.',
    simplification: 'Fixed qualified reports stand in for history, examination, glucose, sodium, CT, CTA, CTP, captured-interval EEG, aneurysm-treatment review, neurocritical and neurovascular escalation, and serial reassessment.',
    whereItMisleads: 'Treating fictional findings, a secured-aneurysm record, vascular narrowing, perfusion delay, negative snapshots, scheduled care, later deterioration, or named ownership as learner-acquired evidence, diagnosis, treatment effect, or a predicted course.',
    correctUnderstanding: 'Real care requires direct repeated assessment, verified multimodal evidence, trained neurocritical, neurovascular, radiology, EEG, nursing, airway, and rescue teams, patient-specific decisions, and continuous deterioration surveillance.',
    briefIn: ['aneurysmal-subarachnoid-hemorrhage-deterioration'],
  },
  {
    id: 'asah-deterioration-controls-reconcile-review-recognize-activate-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, supplied-evidence review, possible-DCI recognition, qualified ownership, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced neurological, neurocritical, neurovascular, emergency, airway, radiology, EEG, nursing, and rescue assessment, planning, monitoring, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, score or imaging interpretation, DCI diagnosis, aneurysm assessment, EEG interpretation, hemodynamic or airway management, angiography, endovascular care, team performance, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current pathways, verified findings, rapid change-triggered escalation, individualized diagnosis and treatment decisions, and continuous reassessment.',
    briefIn: ['aneurysmal-subarachnoid-hemorrhage-deterioration'],
  },
  {
    id: 'no-live-asah-exam-score-imaging-eeg-drug-hemodynamic-airway-endovascular-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, score, image, interpret EEG, prescribe, manage hemodynamics or an airway, perform a procedure, or report outcome.',
    simplification: 'No live history, examination, score, glucose or vital measurement, CT, CTA, CTP, angiography, EEG or other test acquisition or interpretation, diagnosis, drug, dose, route, fluid, pressure target, oxygen, airway device, endovascular treatment, procedure, transfer mechanics, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Equating angiographic narrowing with DCI, delaying urgent escalation until a research-definition clock is met, treating negative CT or EEG snapshots as permanent exclusions, assuming a secured aneurysm eliminates recurrence risk, applying prophylactic augmentation or hypervolemia, copying fictional values into care, or using completion as competence.',
    correctUnderstanding: 'Use verified serial findings, current aSAH guidance, qualified multidisciplinary teams, locally available capabilities, patient-specific diagnosis and rescue decisions, and repeated surveillance without confusing research definitions with bedside delay.',
    briefIn: ['aneurysmal-subarachnoid-hemorrhage-deterioration'],
  },
  {
    id: 'focal-motor-status-clock-semiology-care-and-later-state-are-authored',
    headline: 'The clock, visible motor evolution, recovery, physiology, prior care, and later trajectory are authored.',
    simplification: 'Fixed qualified reports stand in for witness history, seizure timing and semiology, examination, monitoring, glucose testing, initial rescue care, airway and cause review, escalation, and serial reassessment.',
    whereItMisleads: 'Treating the fictional clock, visible clonus, absent recovery, negative snapshots, prior-care record, later persistence, or named ownership as learner-acquired evidence, treatment response, universal timing rule, diagnosis, injury, or predicted course.',
    correctUnderstanding: 'Real care requires immediate direct assessment, verified patient-specific data, qualified seizure and airway-capable teams, continuous monitoring and reassessment, and locally governed individualized treatment.',
    briefIn: ['focal-motor-status-epilepticus-escalation'],
  },
  {
    id: 'focal-motor-status-controls-reconcile-recognize-activate-review-reassess-and-handoff-only',
    headline: 'The controls record trajectory reconciliation, status recognition, qualified ownership, safety review, later motor review, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced neurological, emergency, resuscitation, airway, nursing, pharmacy, laboratory, imaging, and EEG assessment, treatment, escalation, and handoff.',
    whereItMisleads: 'Equating button order with history, examination, seizure timing, monitoring, testing, diagnosis, medication, airway management, EEG interpretation, procedure, team performance, disposition, or seizure-care competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current local pathways, verified findings, individualized treatment, continuous airway and systemic support, and change-triggered reassessment.',
    briefIn: ['focal-motor-status-epilepticus-escalation'],
  },
  {
    id: 'no-live-seizure-exam-monitor-test-eeg-drug-dose-airway-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, monitor, test, interpret EEG, prescribe, manage an airway, perform a procedure, or report outcome.',
    simplification: 'No live history, examination, seizure timing, glucose or vital acquisition, monitoring, imaging, laboratory or EEG acquisition or interpretation, diagnosis, medicine, dose, route, access, oxygen, airway device, ventilation, infusion, anesthetic, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Treating reduced movement as seizure resolution, diagnosing nonconvulsive status from impaired recovery alone, inventing a universal focal-status clock, treating fixed negatives as exclusions, copying fictional values into care, or using completion as clinical competence.',
    correctUnderstanding: 'Use direct verified findings, qualified seizure and airway-capable teams, current guidance and local protocols, appropriate monitoring and tests, individualized rescue decisions, and continuous reassessment.',
    briefIn: ['focal-motor-status-epilepticus-escalation'],
  },
  {
    id: 'ncse-clock-fluctuation-signs-imaging-eeg-and-later-state-are-authored',
    headline: 'The clinical clock, fluctuation, subtle signs, tests, qualified EEG report, and later state are authored.',
    simplification: 'Fixed reports stand in for witness history, examination, monitoring, glucose and sodium testing, CT and CTA, EEG placement and acquisition, specialist interpretation, clinical correlation, cause review, and serial reassessment.',
    whereItMisleads: 'Treating the fictional fluctuation, gaze deviation, negative snapshots, seizure burden, qualified report, persistent symptoms, or named ownership as learner-acquired evidence, a universally diagnostic pattern, treatment response, or predicted course.',
    correctUnderstanding: 'Real care requires immediate direct assessment, verified patient-specific data, qualified EEG interpretation in clinical context, broad cause evaluation, airway-capable support, individualized treatment, and continuous reassessment.',
    briefIn: ['nonconvulsive-status-epilepticus-recognition'],
  },
  {
    id: 'ncse-controls-reconcile-suspect-activate-review-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, suspicion, qualified ownership, alternatives review, report review, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced neurological, neurophysiology, emergency, resuscitation, airway, nursing, pharmacy, laboratory, imaging, and infectious evaluation, treatment, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, nonconvulsive-status diagnosis, EEG acquisition or interpretation, medication or airway management, procedure, team performance, disposition, or clinical competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current local pathways, verified findings, individualized diagnosis and treatment, and continuous safety and neurological reassessment.',
    briefIn: ['nonconvulsive-status-epilepticus-recognition'],
  },
  {
    id: 'no-live-ncse-exam-monitor-test-eeg-interpretation-drug-airway-procedure-or-outcome',
    headline: 'The lab does not examine, monitor, test, acquire or interpret EEG, prescribe, manage an airway, perform a procedure, or report outcome.',
    simplification: 'No live history, examination, seizure timing, glucose, sodium or vital acquisition, monitoring, imaging, laboratory or EEG acquisition or interpretation, diagnosis, medicine, dose, route, access, oxygen, airway device, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Diagnosing NCSE from clinical features alone, treating a fixed EEG report as learner interpretation, treating negative CT or CTA snapshots as exclusions, copying fictional values into care, or using completion as competence.',
    correctUnderstanding: 'Use direct verified findings, qualified EEG and airway-capable teams, current guidance and local protocols, appropriate monitoring and tests, individualized treatment decisions, and continuous reassessment.',
    briefIn: ['nonconvulsive-status-epilepticus-recognition'],
  },
  {
    id: 'myasthenic-crisis-clock-weakness-mechanics-trigger-and-later-airway-state-are-authored',
    headline: 'The clock, fatigable weakness, bulbar and respiratory findings, mechanics, likely trigger, and later airway state are authored.',
    simplification: 'Fixed reports stand in for history, examination, oximetry, blood gas, serial FVC and MIP, imaging, medication reconciliation, secretion and swallowing assessment, trigger evaluation, airway management, ventilation, and reassessment.',
    whereItMisleads: 'Treating fictional serial values, preserved saturation, basilar opacity, supplied ventilation requirement, or named ownership as learner-acquired evidence, one universal threshold, proven trigger, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires immediate serial multimodal assessment, verified data, qualified neurological and airway-capable teams, patient-specific airway and treatment decisions, cause evaluation, and continuous reassessment.',
    briefIn: ['myasthenic-crisis-escalation'],
  },
  {
    id: 'myasthenic-crisis-controls-reconcile-recognize-activate-review-reassess-and-handoff-only',
    headline: 'The controls record trajectory reconciliation, impending-crisis recognition, qualified ownership, cause review, later crisis review, and handoff only.',
    simplification: 'Six accepted actions stand in for neurological, neurocritical, respiratory, nursing, airway, pharmacy, laboratory, imaging, infectious, swallowing, ventilation, treatment, and handoff work.',
    whereItMisleads: 'Equating button order with examination, respiratory testing, diagnosis, airway or ventilator management, IVIG or plasma exchange selection, procedure, team performance, weaning, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current local pathways, verified serial findings, individualized airway and treatment choices, and continuous reassessment.',
    briefIn: ['myasthenic-crisis-escalation'],
  },
  {
    id: 'no-live-myasthenia-exam-mechanics-test-diagnosis-drug-ventilation-airway-procedure-or-outcome',
    headline: 'The lab does not examine, measure mechanics, test, diagnose, prescribe, ventilate, manage an airway, perform a procedure, or report outcome.',
    simplification: 'No live history, examination, count, oximetry, capnography, blood gas, FVC, MIP, imaging, laboratory, microbiology, electrodiagnostic, antibody, swallowing, cough or secretion test, diagnosis, medicine, dose, route, access, oxygen, ventilation, suction, airway device, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Waiting for desaturation or severe hypercapnia, using one mechanics cutoff, treating an opacity as a proven trigger, copying fictional values into care, or reading completion as airway or crisis competence.',
    correctUnderstanding: 'Use direct verified serial findings, qualified neurology, critical-care, respiratory and airway teams, current guidance and local protocols, individualized treatment, and continuous reassessment.',
    briefIn: ['myasthenic-crisis-escalation'],
  },
  {
    id: 'gbs-clock-weakness-tests-mechanics-autonomic-and-later-state-are-authored',
    headline: 'The postinfectious clock, weakness, reflexes, bulbar and respiratory findings, tests, autonomic range, and later state are authored.',
    simplification: 'Fixed reports stand in for history, examination, oximetry, gas exchange, serial FVC, single-breath count and MIP, CSF, electrodiagnostic testing, swallowing and cough assessment, continuous cardiac monitoring, and reassessment.',
    whereItMisleads: 'Treating fictional serial values, preserved saturation, supportive CSF or electrodiagnostic findings, autonomic ranges, or named ownership as learner-acquired evidence, a proven diagnosis, one universal airway threshold, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires immediate verified serial multimodal assessment, qualified neurological, respiratory, critical-care and airway-capable teams, continuous monitoring when indicated, individualized diagnosis, airway and treatment decisions, and ongoing reassessment.',
    briefIn: ['guillain-barre-respiratory-decline'],
  },
  {
    id: 'gbs-controls-reconcile-review-recognize-activate-reassess-and-handoff-only',
    headline: 'The controls record trajectory reconciliation, evidence review, risk recognition, qualified ownership, later-report review, and handoff only.',
    simplification: 'Six accepted actions stand in for neurological, neurocritical, respiratory, nursing, airway, cardiac-monitoring, laboratory, electrodiagnostic, swallowing, treatment, rehabilitation, and handoff work.',
    whereItMisleads: 'Equating button order with examination, scoring, respiratory or autonomic testing, diagnosis, airway or ventilator management, IVIG or plasma exchange selection, rhythm or pressure treatment, procedure, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current local pathways, verified serial findings, individualized diagnostic, airway, monitoring and treatment choices, and continuous reassessment.',
    briefIn: ['guillain-barre-respiratory-decline'],
  },
  {
    id: 'no-live-gbs-exam-score-test-diagnosis-drug-ventilation-airway-procedure-or-outcome',
    headline: 'The lab does not examine, score, test, diagnose, prescribe, ventilate, manage an airway or dysautonomia, perform a procedure, or report outcome.',
    simplification: 'No live history, examination, score, monitoring interpretation, oximetry, capnography, blood gas, FVC, count, MIP, MEP, CSF, imaging, laboratory, microbiology, electrodiagnostic, swallowing, cough or secretion test, diagnosis, medicine, dose, route, access, fluid, oxygen, ventilation, suction, airway device, rhythm or pressure treatment, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Waiting for desaturation or severe hypercapnia, using one score or mechanics cutoff, treating supportive tests as independently diagnostic, automatically treating every labile heart rate or pressure, copying fictional values into care, or reading completion as competence.',
    correctUnderstanding: 'Use direct verified serial findings, qualified neurology, critical-care, respiratory, airway and cardiac-monitoring teams, current guidance and local protocols, individualized diagnosis and treatment, and continuous reassessment.',
    briefIn: ['guillain-barre-respiratory-decline'],
  },
  {
    id: 'meningitis-clock-exam-blood-lp-csf-treatment-and-later-state-are-authored',
    headline: 'The illness clock, examination, blood evidence, LP safety, CSF, qualified care, and later state are authored.',
    simplification: 'Fixed reports stand in for history, examination, monitoring, glucose, blood tests and cultures, LP safety assessment, imaging decision, lumbar puncture, CSF tests, qualified empiric and adjunctive treatment, and reassessment.',
    whereItMisleads: 'Treating fictional findings, inflammatory markers, absent warning signs, CSF values, supplied LP, or qualified care as learner-acquired evidence, permanent exclusions, a universal no-imaging rule, organism identification, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires immediate direct reassessment, verified data, qualified teams, current local infection-control and treatment pathways, patient-specific LP and imaging safety decisions, early appropriate therapy, and continuous neurological and systemic reassessment.',
    briefIn: ['acute-bacterial-meningitis-first-hour'],
  },
  {
    id: 'meningitis-controls-reconcile-activate-review-escalate-reassess-and-handoff-only',
    headline: 'The controls record trajectory reconciliation, qualified ownership, diagnostic-boundary review, care activation, later-report review, and handoff only.',
    simplification: 'Six accepted actions stand in for infection, neurological, emergency, nursing, laboratory, pharmacy, imaging, LP, antimicrobial, adjunctive, public-health, hearing, rehabilitation, and handoff work.',
    whereItMisleads: 'Equating button order with examination, LP or imaging safety assessment, test acquisition or interpretation, diagnosis, prescribing, procedure, treatment, infection control, contact management, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current local pathways, verified serial findings, individualized diagnostics and treatment, and continuous reassessment.',
    briefIn: ['acute-bacterial-meningitis-first-hour'],
  },
  {
    id: 'no-live-meningitis-exam-test-imaging-lp-diagnosis-drug-procedure-or-outcome',
    headline: 'The lab does not examine, test, image, perform LP, diagnose, prescribe, treat, manage contacts, perform a procedure, or report outcome.',
    simplification: 'No live history, examination, score, monitoring, glucose, blood, culture, CSF, PCR, imaging, EEG, hearing or another test, diagnosis, isolation equipment, oxygen, fluid, antimicrobial, corticosteroid, antiseizure medicine, drug, dose, route, access, airway care, LP, procedure, contact decision, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using a stable snapshot as a permanent safety clearance, ordering routine imaging in every case, waiting for tests before qualified empiric care, treating one CSF value as an organism, copying fictional values into care, or reading completion as competence.',
    correctUnderstanding: 'Use direct verified serial findings, qualified neurological, infection, emergency, airway, laboratory and public-health teams, current guidance and local protocols, individualized diagnostics and treatment, and continuous reassessment.',
    briefIn: ['acute-bacterial-meningitis-first-hour'],
  },
  {
    id: 'encephalitis-clock-exam-csf-mri-eeg-pcr-treatment-and-later-state-are-authored',
    headline: 'The illness clock, examination, focal seizure, CSF, MRI, EEG, PCR, qualified care, and later state are authored.',
    simplification: 'Fixed reports stand in for history, examination, monitoring, glucose, blood and CSF tests, lumbar puncture, MRI, specialist EEG, PCR, qualified empiric antiviral care, and reassessment.',
    whereItMisleads: 'Treating fictional findings, temporal localization, periodic discharges, the early negative PCR, supplied care, or absent sampled seizure as learner evidence, etiologic proof, durable exclusion, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires immediate verified assessment, qualified neurological, infection, neurocritical and airway-capable teams, prompt individualized empiric care, parallel diagnostics, repeat testing when indicated, and continuous reassessment.',
    briefIn: ['suspected-herpes-simplex-encephalitis'],
  },
  {
    id: 'encephalitis-controls-reconcile-activate-treat-review-reassess-and-handoff-only',
    headline: 'The controls record trajectory reconciliation, qualified ownership, early-care activation, diagnostic review, later-report review, and handoff only.',
    simplification: 'Six accepted actions stand in for neurological, infection, neurocritical, airway, nursing, pharmacy, laboratory, imaging, neurophysiology, treatment, rehabilitation, and handoff work.',
    whereItMisleads: 'Equating button order with examination, seizure assessment, test acquisition or interpretation, diagnosis, prescribing, procedure, treatment, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, current local pathways, verified serial findings, individualized diagnostics and treatment, and continuous reassessment.',
    briefIn: ['suspected-herpes-simplex-encephalitis'],
  },
  {
    id: 'no-live-encephalitis-exam-test-imaging-eeg-lp-diagnosis-drug-procedure-or-outcome',
    headline: 'The lab does not examine, test, image, interpret EEG, perform LP, diagnose, prescribe, treat, perform a procedure, or report outcome.',
    simplification: 'No live history, examination, score, monitoring, glucose, blood, culture, CSF, PCR, antibody, imaging, EEG or another test, diagnosis, oxygen, fluid, antiviral, antimicrobial, antiseizure or immune medicine, drug, dose, route, access, airway care, LP, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Treating one negative early PCR or sampled EEG as exclusion, copying fictional values into care, waiting for test certainty before qualified empiric care, or reading completion as competence.',
    correctUnderstanding: 'Use direct verified serial findings, qualified neurological, infection, neurocritical, airway, laboratory and neurophysiology teams, current guidance and local protocols, individualized diagnostics and treatment, and continuous reassessment.',
    briefIn: ['suspected-herpes-simplex-encephalitis'],
  },
  {
    id: 'raised-icp-clock-eye-exam-fields-imaging-lp-care-and-later-state-are-authored',
    headline: 'The clock, eye and neurological examinations, visual fields, imaging, LP, qualified care, and later state are authored.',
    simplification: 'Fixed specialist reports stand in for history, examination, fundus photography, OCT, perimetry, MRI, venography, laboratory tests, LP safety, opening pressure, CSF, qualified initial care, and reassessment.',
    whereItMisleads: 'Treating fictional papilledema, visual fields, imaging exclusions, one opening pressure, demographics, or supplied care as learner evidence, a proven idiopathic cause, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires verified specialist assessment, urgent secondary-cause exclusion, pressure interpreted in full context, serial visual function, individualized treatment, and continuous reassessment.',
    briefIn: ['raised-intracranial-pressure-visual-threat'],
  },
  {
    id: 'raised-icp-controls-reconcile-activate-review-reassess-and-handoff-only',
    headline: 'The controls record trajectory reconciliation, qualified ownership, eye and diagnostic review, later visual-threat review, and handoff only.',
    simplification: 'Six actions stand in for neurology, neuro-ophthalmology, radiology, procedural, nursing, pharmacy, disease, headache, and follow-up work.',
    whereItMisleads: 'Equating button order with examination, testing, diagnosis, LP, prescribing, procedure selection, treatment, visual rescue, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, verified serial findings, current local pathways, individualized decisions, and continuous reassessment.',
    briefIn: ['raised-intracranial-pressure-visual-threat'],
  },
  {
    id: 'no-live-raised-icp-exam-test-imaging-lp-diagnosis-drug-procedure-or-outcome',
    headline: 'The lab does not examine, test, image, perform LP, diagnose, prescribe, perform a procedure, treat, or report outcome.',
    simplification: 'No live eye or neurological examination, fundus, OCT, field, MRI, venography, blood, CSF, pressure or another test, diagnosis, drug, dose, route, access, weight or headache treatment, LP, fenestration, CSF diversion, stenting, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Relying on acuity alone, using demographics or one pressure cutoff as diagnosis, copying fictional values into care, or reading completion as sight-preservation competence.',
    correctUnderstanding: 'Use direct verified serial visual and neurological findings, qualified multidisciplinary teams, current guidance and local protocols, individualized cause and treatment decisions, and continuous reassessment.',
    briefIn: ['raised-intracranial-pressure-visual-threat'],
  },
  {
    id: 'herniation-clock-exam-imaging-care-and-later-state-are-authored',
    headline: 'The clock, neurological examination, CT, physiology, qualified care, and later state are authored.',
    simplification: 'Fixed reports stand in for history, GCS, pupil and motor examination, airway assessment, monitoring, glucose, CT, qualified airway and brain-rescue care, operating-room activation, and reassessment.',
    whereItMisleads: 'Treating fictional findings, anisocoria, mass effect, supplied care, or a later monitor change as learner evidence, a universal diagnosis, treatment effect, recovery, or predicted course.',
    correctUnderstanding: 'Real care requires immediate direct reassessment, verified serial findings, experienced emergency, airway, neurocritical and neurosurgical teams, current local pathways, individualized rescue, and definitive cause control.',
    briefIn: ['acute-transtentorial-herniation-pattern'],
  },
  {
    id: 'herniation-controls-reconcile-recognize-activate-review-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, boundary review, later-report review, and handoff only.',
    simplification: 'Six actions stand in for airway, neurocritical, neurosurgical, nursing, respiratory, pharmacy, imaging, operating-room, rescue, and handoff work.',
    whereItMisleads: 'Equating button order with examination, scoring, diagnosis, airway management, prescribing, imaging, pressure treatment, surgery, procedure, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, verified serial findings, current local protocols, individualized medical and surgical decisions, and continuous reassessment.',
    briefIn: ['acute-transtentorial-herniation-pattern'],
  },
  {
    id: 'no-live-herniation-exam-monitor-imaging-diagnosis-airway-drug-procedure-or-outcome',
    headline: 'The lab does not examine, monitor, image, diagnose, manage an airway, prescribe, operate, treat, or report outcome.',
    simplification: 'No live history, GCS, pupil or motor examination, monitoring, glucose, blood gas, imaging, ICP or another test, diagnosis, positioning, oxygen, ventilation, fluid, hyperosmolar or other drug, dose, route, access, airway device, drain, decompression, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Waiting for a complete triad, treating an isolated pupil as proof, copying fictional values into care, applying one drug or ventilation recipe universally, or reading completion as competence.',
    correctUnderstanding: 'Use the whole evolving pattern, direct verified assessment, immediate qualified rescue, patient-specific medical and surgical decisions, continuous reassessment, and definitive source control.',
    briefIn: ['acute-transtentorial-herniation-pattern'],
  },
  {
    id: 'mscc-clock-exam-imaging-care-and-later-state-are-authored',
    headline: 'The cancer, pain, neurological, bladder, imaging, qualified-care, and later reports are authored.',
    simplification: 'Fixed reports stand in for history, motor, reflex, sensory, gait and bladder examination, monitoring, stability assessment, whole-spine MRI, qualified early care, and reassessment.',
    whereItMisleads: 'Treating fictional findings, one symptom, supplied MRI, movement precautions, corticosteroid care, or persistent function as learner evidence, a universal diagnosis, treatment effect, recovery, or predicted course.',
    correctUnderstanding: 'Real care requires immediate direct reassessment, verified serial neurological findings, qualified spinal and oncology teams, current local pathways, individualized protection and treatment, and definitive care.',
    briefIn: ['metastatic-spinal-cord-compression'],
  },
  {
    id: 'mscc-controls-reconcile-recognize-activate-review-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, emergency recognition, qualified ownership, boundary review, later-report review, and handoff only.',
    simplification: 'Six actions stand in for spinal, oncology, radiology, radiotherapy, nursing, pharmacy, rehabilitation, pain, bladder, skin, thrombosis-prevention, and handoff work.',
    whereItMisleads: 'Equating button order with examination, movement or immobilization, diagnosis, prescribing, imaging, catheterization, surgery, radiotherapy, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, verified serial findings, current local protocols, individualized medical and definitive decisions, and continuous reassessment.',
    briefIn: ['metastatic-spinal-cord-compression'],
  },
  {
    id: 'no-live-mscc-history-exam-movement-imaging-diagnosis-drug-procedure-or-outcome',
    headline: 'The lab does not examine, move, image, diagnose, prescribe, perform a procedure, treat, or report outcome.',
    simplification: 'No live history, motor, sensory, reflex, gait, stability or bladder examination, monitoring, MRI, pathology, staging or another test, diagnosis, movement, immobilization, corticosteroid or other drug, dose, route, access, catheter, surgery, radiotherapy, biopsy, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Waiting for imaging despite a converging emergency pattern, treating one symptom as proof, copying fictional values into care, applying one movement or treatment recipe universally, or reading completion as competence.',
    correctUnderstanding: 'Use the whole evolving cord-level pattern, direct verified assessment, immediate qualified escalation, patient-specific protection and medical care, continuous reassessment, and definitive multidisciplinary treatment.',
    briefIn: ['metastatic-spinal-cord-compression'],
  },
  {
    id: 'delirium-baseline-clock-assessment-contributors-care-and-later-state-are-authored',
    headline: 'The baseline, clock, cognition, 4AT, diagnosis, contributor, qualified-care, and later reports are authored.',
    simplification: 'Fixed family and team reports stand in for history, examination, attention and orientation tasks, 4AT, diagnosis, capacity, physiology, tests, contributor review, qualified care, and reassessment.',
    whereItMisleads: 'Treating fictional fluctuation, a supplied score, contributor, or later improvement as learner evidence, one proven cause, dementia, capacity, treatment effect, recovery, or predicted course.',
    correctUnderstanding: 'Real care requires verified baseline and serial change, direct qualified assessment, decision-specific capacity review, individualized multicomponent care, and continuous reassessment.',
    briefIn: ['acute-delirium-reversible-causes'],
  },
  {
    id: 'delirium-controls-reconcile-recognize-activate-review-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, assessment-boundary recognition, qualified ownership, contributor review, later-report review, and handoff only.',
    simplification: 'Six actions stand in for medical, nursing, pharmacy, family, safety, capacity, mobility, pain, nutrition, bladder, bowel, sensory, sleep, safeguarding, and handoff work.',
    whereItMisleads: 'Equating button order with examination, score interpretation, diagnosis, capacity assessment, observation, restraint, prescribing, treatment, procedure, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the person, familiar support, trained teams, verified serial findings, current local protocols, individualized least-restrictive care, and reassessment.',
    briefIn: ['acute-delirium-reversible-causes'],
  },
  {
    id: 'no-live-delirium-history-exam-score-capacity-test-diagnosis-drug-restraint-procedure-or-outcome',
    headline: 'The lab does not examine, score, assess capacity, test, diagnose, restrain, prescribe, treat, perform a procedure, or report outcome.',
    simplification: 'No live history, cognitive or neurological examination, 4AT or another score, capacity assessment, observation, oxygenation, bladder, blood, urine, imaging, EEG or another test, diagnosis, reorientation, mobility, restraint, fluid, analgesic, antipsychotic, sedative or other drug, dose, route, access, catheter, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using one score as diagnosis or capacity, assigning one cause, overlooking hypoactive change, defaulting to restraint or medication, copying fictional values into care, or reading completion as competence.',
    correctUnderstanding: 'Use verified baseline and fluctuation, direct qualified assessment, a broad cause combination, familiar communication, individualized least-restrictive care, family partnership, and serial reassessment.',
    briefIn: ['acute-delirium-reversible-causes'],
  },
  {
    id: 'autonomic-dysreflexia-lesion-baseline-trigger-vitals-response-and-later-state-are-authored',
    headline: 'The lesion, baseline, symptoms, trigger, pressure and pulse transitions, drainage, and later report are authored.',
    simplification: 'Fixed reports and discrete canonical monitor states stand in for history, examination, pressure and pulse acquisition, rhythm review, trigger survey, qualified care, external-kink release, drainage, and reassessment.',
    whereItMisleads: 'Treating the fictional T4 lesion, 20 mmHg recognition convention, visible kink, pressure transition, or symptom improvement as learner evidence, a universal diagnosis, sole cause, individualized effect, durable resolution, or predicted course.',
    correctUnderstanding: 'Real care requires the person’s verified usual pressure, immediate serial assessment, qualified spinal-injury ownership, individualized trigger removal and treatment, complication review, and recurrence surveillance.',
    briefIn: ['autonomic-dysreflexia-authored-trigger'],
  },
  {
    id: 'autonomic-dysreflexia-controls-reconcile-recognize-support-review-release-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, immediate support, one supplied external-trigger release, reassessment, and handoff only.',
    simplification: 'Six actions stand in for spinal-injury, medical, nursing, urology, emergency, monitoring, trigger, complication, education, prevention, and handoff work.',
    whereItMisleads: 'Equating button order or releasing one visible external kink with examination, diagnosis, catheter care, bowel care, medication, treatment, complication exclusion, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, frequent verified pressure and pulse checks, a systematic cause search, current local protocols, individualized care, and continuous reassessment.',
    briefIn: ['autonomic-dysreflexia-authored-trigger'],
  },
  {
    id: 'no-live-spinal-injury-exam-diagnosis-catheter-technique-drug-procedure-or-outcome',
    headline: 'The lab does not accept a real lesion or baseline, examine, diagnose, teach catheter technique, prescribe, perform a procedure, or report outcome.',
    simplification: 'No live history, neurological, cardiopulmonary, abdominal, urinary, bowel or skin examination, pressure or pulse acquisition, ECG, bladder, urine, blood, imaging or another test, diagnosis, catheter insertion, disconnection, irrigation or replacement, bowel care, drug, dose, route, access, oxygen, fluid, device, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Diagnosing every hypertensive episode from one threshold, copying fictional values into care, manipulating a catheter from this rehearsal, assuming one trigger or pressure response, or reading completion as competence.',
    correctUnderstanding: 'Use verified individual baseline and serial findings, immediate qualified assessment, patient-specific trigger removal and medical care, local spinal-injury guidance, complication review, and recurrence planning.',
    briefIn: ['autonomic-dysreflexia-authored-trigger'],
  },
];
