/**
 * The obstetrics module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a obstetrics scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const OBSTETRICS_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'obstetric-atony-birth-loss-tone-and-response-pattern-are-authored',
    headline: 'The birth clock, measured loss, uterine-tone pattern, physiology, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for birth-record review, objective blood-loss measurement, history, examination, uterine and placental assessment, genital-tract and coagulation evaluation, laboratory acquisition, qualified bundled care, and reassessment.',
    whereItMisleads: 'Treating the fictional 650 mL loss, boggy uterus, placental report, vital signs, firmer uterus, or slower bleeding as learner evidence, a universal diagnostic threshold, one proven cause, treatment effect, durable hemostasis, recovery, or predicted course.',
    correctUnderstanding: 'Real care requires immediate objective loss and whole-patient assessment, parallel review of tone, trauma, tissue, thrombin, rupture, inversion and concealed bleeding, current local hemorrhage protocols, and serial response under qualified multidisciplinary ownership.',
    briefIn: ['postpartum-hemorrhage-uterine-atony'],
  },
  {
    id: 'obstetric-atony-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for obstetric, anesthesia, nursing, monitoring, blood-bank, operating-room, newborn-support, privacy, pain, communication, bundled-care, surveillance, escalation, and handoff work.',
    whereItMisleads: 'Equating button order with blood-loss measurement, history, examination, uterine or placental assessment, laboratory interpretation, diagnosis, prescribing, massage, fluid or blood delivery, procedure, disposition, recovery, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, objective measurement, current local protocols, simultaneous resuscitation and cause control, individualized medication and blood decisions, procedural escalation when needed, respectful communication, and serial maternal and newborn reassessment.',
    briefIn: ['postpartum-hemorrhage-uterine-atony'],
  },
  {
    id: 'no-live-obstetric-atony-measurement-exam-drug-fluid-blood-procedure-disposition-or-outcome',
    headline: 'The lab does not measure blood loss, examine a patient, give a drug, fluid or blood, perform a procedure, determine disposition, or report outcome.',
    simplification: 'No live history, blood-loss measurement, examination, uterine tone, placental or genital-tract assessment, monitoring or laboratory interpretation, calculation, diagnosis, differential exclusion, massage, oxygen, fluid, blood component, uterotonic, tranexamic acid, drug, dose, rate, route, access, device, tamponade, procedure, surgery, hysterectomy, transport, disposition, prognosis, fertility, safety decision, or maternal or newborn outcome is modeled.',
    whereItMisleads: 'Waiting for one threshold despite abnormal physiology; using tone, placenta, bleeding or one vital sign alone; copying fictional values into care; choosing medication, blood, massage or procedural care from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use verified serial objective loss, symptoms, perfusion, temperature, uterine, placental, genital-tract, coagulation, laboratory, concealed-bleeding, treatment and response evidence under qualified obstetric hemorrhage, anesthesia, nursing, blood-bank, operative and newborn-support ownership.',
    briefIn: ['postpartum-hemorrhage-uterine-atony'],
  },
  {
    id: 'maternal-sepsis-postpartum-infection-organ-and-response-pattern-are-authored',
    headline: 'The postpartum infection, organ-dysfunction pattern, and later response are authored.',
    simplification: 'Fixed reports stand in for history, examination, monitoring, cultures, lactate and laboratory acquisition, source and mimic evaluation, qualified immediate care, and reassessment.',
    whereItMisleads: 'Treating fever, lactate, uterine findings, one score, one presumed source, or modest later improvement as learner evidence, diagnosis, treatment effect, source control, organ recovery, or predicted course.',
    correctUnderstanding: 'Real care requires immediate serial whole-patient, infection, perfusion, organ, source and competing-cause assessment under qualified multidisciplinary ownership without waiting for one score or confirmation.',
    briefIn: ['maternal-sepsis-postpartum-deterioration'],
  },
  {
    id: 'maternal-sepsis-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, recognition, qualified ownership, review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for obstetric, critical-care, anesthesia, nursing, pharmacy, microbiology, organ-support, source-control, newborn, dignity, survivor-support and handoff work.',
    whereItMisleads: 'Equating button order with examination, screening, test interpretation, diagnosis, prescribing, resuscitation, source control, disposition, recovery, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, current local protocols, immediate individualized antimicrobial and resuscitation decisions, source control, serial organ assessment, respectful communication, and newborn and survivor support.',
    briefIn: ['maternal-sepsis-postpartum-deterioration'],
  },
  {
    id: 'no-live-maternal-sepsis-exam-score-test-drug-fluid-vasopressor-procedure-disposition-or-outcome',
    headline: 'The lab does not examine, score, test, prescribe, resuscitate, perform source control, determine disposition, or report outcome.',
    simplification: 'No live history, examination, score, monitoring, culture, laboratory, lactate, imaging, diagnosis, antimicrobial, oxygen, fluid, blood, vasopressor, drug, dose, target, route, access, drainage, evacuation, surgery, transport, disposition, prognosis, safety decision, or maternal or newborn outcome is modeled.',
    whereItMisleads: 'Waiting for fever or one score; copying fictional values into care; choosing antimicrobial, fluid, vasopressor, source-control or disposition care from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use verified serial infection, perfusion, neurologic, respiratory, kidney, hematologic, hepatic, source, mimic, treatment and response evidence under qualified obstetric sepsis and critical-care ownership.',
    briefIn: ['maternal-sepsis-postpartum-deterioration'],
  },
  {
    id: 'concealed-abruption-maternal-fetal-coagulation-and-response-pattern-are-authored',
    headline: 'The maternal-fetal pattern, coagulation findings, concealed loss, and later response are authored.',
    simplification: 'Fixed reports stand in for history, examination, visible and concealed blood-loss measurement, maternal and fetal monitoring, placental and uterine assessment, laboratory and coagulation acquisition, imaging, qualified resuscitation and delivery care, and reassessment.',
    whereItMisleads: 'Treating the fictional 80 mL or 120 mL visible loss, pain, uterine findings, fetal trace, laboratory values, operating-room readiness, or modest later improvement as learner evidence, diagnosis, total blood loss, treatment effect, fetal recovery, delivery, or predicted outcome.',
    correctUnderstanding: 'Real care requires direct serial maternal perfusion, fetal status, visible and concealed bleeding, coagulation, uterine and placental findings, competing causes, treatment response, delivery readiness, and maternal-newborn outcome assessment under qualified multidisciplinary ownership.',
    briefIn: ['concealed-placental-abruption-hemorrhage'],
  },
  {
    id: 'concealed-abruption-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, recognition, qualified ownership, review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for obstetric hemorrhage, anesthesia, nursing, blood-bank, operating-room, fetal surveillance, neonatal, dignity, bereavement, resuscitation, delivery, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, blood-loss measurement, fetal-trace or laboratory interpretation, diagnosis, prescribing, resuscitation, anesthesia, delivery, source control, disposition, recovery, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, current local protocols, simultaneous maternal resuscitation and fetal assessment, individualized blood and coagulation care, urgent delivery decisions when compromise is present, respectful communication, and serial maternal-newborn reassessment.',
    briefIn: ['concealed-placental-abruption-hemorrhage'],
  },
  {
    id: 'no-live-concealed-abruption-exam-trace-imaging-blood-drug-anesthesia-delivery-disposition-or-outcome',
    headline: 'The lab does not examine, interpret a fetal trace or image, give blood or a drug, provide anesthesia, deliver a baby, determine disposition, or report outcome.',
    simplification: 'No live history, examination, blood-loss measurement, uterine or placental assessment, fetal monitoring, ultrasound, laboratory or coagulation interpretation, diagnosis, differential exclusion, oxygen, fluid, blood component, medication, dose, rate, target, route, access, anesthesia, procedure, surgery, delivery, transport, disposition, prognosis, fertility, safety decision, bereavement need, or maternal or newborn outcome is modeled.',
    whereItMisleads: 'Using visible blood volume, pain, uterine tone, fetal status, one vital sign, ultrasound, or one laboratory value alone; copying fictional values into care; choosing blood, medication, anesthesia, delivery, or procedural care from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use verified serial maternal symptoms, perfusion, fetal status, total bleeding, uterine and placental findings, coagulation, competing-cause, treatment, delivery, and response evidence under qualified obstetric hemorrhage, anesthesia, nursing, blood-bank, operative, neonatal, and bereavement-support ownership.',
    briefIn: ['concealed-placental-abruption-hemorrhage'],
  },
  {
    id: 'postpartum-severe-preeclampsia-clock-symptom-pressure-organ-and-response-pattern-are-authored',
    headline: 'The postpartum clock, symptoms, pressures, organ findings, and later report are authored.',
    simplification: 'Fixed reports stand in for history, correctly obtained pressure measurement, examination, reflex and clonus assessment, urine, laboratory and imaging acquisition or interpretation, qualified immediate protocol care, newborn-care continuity, and reassessment.',
    whereItMisleads: 'Treating the fictional pressures, headache, visual spots, pain, platelets, creatinine, liver values, pending urine or hemolysis work, or single later pressure as learner evidence, every-cause diagnosis, a universal target, treatment effect, durable control, organ recovery, discharge readiness, or predicted course.',
    correctUnderstanding: 'Two persistent severe-range postpartum pressures require immediate protocol response while direct serial neurologic, pulmonary, hematologic, hepatic, renal, urine, medication, hemorrhage, infection, thrombotic and other-cause evaluation continues under qualified ownership.',
    briefIn: ['postpartum-severe-preeclampsia-warning-signs'],
  },
  {
    id: 'postpartum-severe-preeclampsia-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, emergency recognition, immediate protocol activation, parallel review, fixed later reassessment, and handoff only.',
    simplification: 'Six actions stand in for obstetric emergency, nursing, pharmacy, critical-care, neurologic, pulmonary, laboratory, seizure-prevention, newborn-care-continuity, feeding, communication, support, surveillance and handoff work.',
    whereItMisleads: 'Equating button order with pressure measurement, history, examination, test interpretation, diagnosis, prescribing, treatment, seizure or airway care, consultation need, newborn separation, feeding decisions, disposition, follow-up performance, recovery, or competence.',
    correctUnderstanding: 'Actual care activates the local severe-hypertension pathway immediately, treats within its urgent window, evaluates symptoms, organs and alternative causes in parallel, uses conditional specialist support, protects the maternal-newborn dyad, and reassesses serially.',
    briefIn: ['postpartum-severe-preeclampsia-warning-signs'],
  },
  {
    id: 'no-live-postpartum-preeclampsia-pressure-exam-test-drug-magnesium-airway-disposition-or-outcome',
    headline: 'The lab does not measure pressure, examine or test, select an antihypertensive or magnesium, manage an airway or seizure, determine disposition, or report outcome.',
    simplification: 'No live history, cuff or position choice, pressure measurement, examination, reflex, clonus, edema, volume, lung, fundal, abdominal or neurologic assessment, urine, blood, ECG, imaging or other test, calculation, diagnosis, differential exclusion, antihypertensive, magnesium, oxygen, fluid, diuretic, analgesic, antiseizure drug, dose, rate, target, route, access, airway, ventilation, procedure, separation, feeding, transfer, admission, discharge, follow-up, future-pregnancy care, prognosis, fertility, or maternal or newborn outcome is modeled.',
    whereItMisleads: 'Waiting for proteinuria or a broad review before urgent response; copying fictional values into care; selecting a product, dose, target, route, airway, seizure treatment, disposition or follow-up from this rehearsal; attributing the fixed later report; or reading completion as competence.',
    correctUnderstanding: 'Use correctly obtained serial pressures and direct whole-patient evidence with current local protocols, prompt protocol-based treatment, parallel severe-feature and alternative-cause assessment, individualized seizure-prevention and organ care, maternal-newborn support, and qualified disposition and follow-up ownership.',
    briefIn: ['postpartum-severe-preeclampsia-warning-signs'],
  },
  {
    id: 'eclampsia-seizure-recovery-pressure-organ-fetal-and-later-reports-are-authored',
    headline: 'The seizure, recovery, pressure, organ, fetal, and later reports are authored.',
    simplification: 'Fixed reports stand in for witnessed-event timing, injury protection, positioning, airway and breathing assessment, pressure and glucose measurement, examination, monitoring, organ and fetal evaluation, qualified protocol care, and reassessment.',
    whereItMisleads: 'Treating fictional seizure, pressure, glucose, laboratory, fetal, recovery, or seizure-free-window values as learner evidence, an exclusive diagnosis, treatment effect, durable control, fetal safety, delivery readiness, or predicted course.',
    correctUnderstanding: 'A new seizure in pregnancy requires immediate qualified maternal stabilization, eclampsia and severe-pressure response, recurrence readiness, fetal assessment, and parallel evaluation for neurologic and other dangerous causes.',
    briefIn: ['eclampsia-first-seizure-response'],
  },
  {
    id: 'eclampsia-controls-reconcile-recognize-activate-review-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, immediate qualified response, evidence review, fixed reassessment, and handoff only.',
    simplification: 'Six actions stand in for injury protection, airway-ready maternal stabilization, eclampsia and severe-pressure protocols, obstetric, anesthesia, nursing, pharmacy, critical-care, fetal, neonatal, laboratory, neurologic, communication, support, surveillance, birth-planning, postpartum, and handoff work.',
    whereItMisleads: 'Equating button order with seizure first aid, airway care, examination, testing, diagnosis, prescribing, treatment, fetal interpretation, anesthesia, birth planning, disposition, recovery, or competence.',
    correctUnderstanding: 'Actual care is simultaneous and team-based: stabilize the pregnant patient, treat the eclampsia and severe pressure under current local protocols, prepare for recurrence and airway compromise, assess fetal and organ status, keep alternative causes open, and plan birth after maternal stabilization.',
    briefIn: ['eclampsia-first-seizure-response'],
  },
  {
    id: 'no-live-eclampsia-seizure-airway-exam-test-drug-magnesium-delivery-disposition-or-outcome',
    headline: 'The lab does not perform seizure first aid, manage an airway, examine or test, give magnesium or another drug, deliver a baby, determine disposition, or report outcome.',
    simplification: 'No live seizure timing, injury protection, positioning, suction, oxygen, ventilation, access, pressure or glucose measurement, examination, monitoring or test interpretation, diagnosis, differential exclusion, magnesium, antihypertensive, antiseizure drug, calcium, fluid, dose, concentration, rate, target, route, device, procedure, anesthesia, birth timing or route, transfer, disposition, prognosis, or maternal or newborn outcome is modeled.',
    whereItMisleads: 'Delaying urgent response for testing or diagnosis; copying fictional values into care; selecting a maneuver, product, dose, route, airway, anesthesia, birth, or disposition from this rehearsal; attributing the fixed later report; or reading completion as competence.',
    correctUnderstanding: 'Use direct serial maternal, neurologic, airway, pulmonary, pressure, organ and fetal evidence with current local protocols and qualified obstetric, anesthesia, critical-care, nursing, pharmacy, fetal, neonatal, diagnostic, communication, and support ownership.',
    briefIn: ['eclampsia-first-seizure-response'],
  },
  {
    id: 'afe-birth-cardiorespiratory-coagulopathy-and-later-reports-are-authored',
    headline: 'The birth clock, cardiorespiratory collapse, bleeding, coagulation, newborn, and later reports are authored.',
    simplification: 'Fixed reports stand in for direct history, pulse and perfusion assessment, examination, monitoring, loss and uterine assessment, laboratory and cardiopulmonary evaluation, qualified emergency care, and reassessment.',
    whereItMisleads: 'Treating fictional timing, vitals, loss, uterine tone, coagulation, hemoglobin, lactate, oxygenation, responsiveness, or pulse as learner evidence, a confirmed diagnosis, a treatment effect, durable control, disposition, or predicted course.',
    correctUnderstanding: 'Sudden peripartum cardiorespiratory collapse with evolving coagulopathy requires immediate coordinated support and parallel evaluation; suspected amniotic fluid embolism remains a clinical pattern with dangerous alternatives and no single confirmatory test.',
    briefIn: ['suspected-amniotic-fluid-embolism-pattern'],
  },
  {
    id: 'afe-controls-reconcile-recognize-activate-review-reassess-and-handoff-only',
    headline: 'The controls activate coordinated help, reconcile, recognize, review, reassess, and hand off only.',
    simplification: 'Six actions stand in for simultaneous qualified cardiopulmonary, obstetric, anesthesia, critical-care, hemorrhage, coagulation, blood-bank, laboratory, newborn, communication, dignity, family, staff-support, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with examination, monitoring, diagnostic testing, AFE confirmation, research-criteria scoring, oxygenation, ventilation, circulation support, transfusion, coagulation treatment, procedure, arrest care, recovery, or competence.',
    correctUnderstanding: 'Actual response is simultaneous and team-based: activate qualified help first, support airway, breathing and circulation, prepare for arrest, assess and manage coagulation and hemorrhage early, keep alternative causes open, and reassess serially.',
    briefIn: ['suspected-amniotic-fluid-embolism-pattern'],
  },
  {
    id: 'no-live-afe-exam-test-diagnosis-treatment-airway-blood-arrest-delivery-procedure-disposition-or-outcome',
    headline: 'The lab does not examine or test, diagnose AFE, deliver treatment, perform arrest care or a procedure, determine disposition, or report outcome.',
    simplification: 'No live pulse, airway, breathing, circulation, uterus, genital tract, placenta, loss, monitoring, ECG, echo, laboratory, imaging, DIC score, diagnosis, differential exclusion, oxygen, ventilation, airway, fluid, vasoactive, pulmonary vasodilator, uterotonic, tranexamic acid, blood or coagulation product, drug, dose, route, target, access, CPR, defibrillation, ECMO, delivery, surgery, transfer, disposition, fertility, prognosis, or maternal or newborn outcome is modeled.',
    whereItMisleads: 'Delaying qualified response for diagnostic certainty; copying fictional values into care; applying research criteria as a bedside score; selecting a product, device, dose, airway, arrest step, delivery, procedure, or disposition from this rehearsal; or reading completion as competence.',
    correctUnderstanding: 'Use direct serial whole-patient evidence, current local maternal-collapse, hemorrhage and arrest pathways, and qualified obstetric, anesthesia, critical-care, cardiopulmonary, blood-bank, laboratory, newborn, communication, and support ownership.',
    briefIn: ['suspected-amniotic-fluid-embolism-pattern'],
  },
  {
    id: 'maternal-arrest-clock-pulse-rhythm-pregnancy-delivery-and-minute-four-reports-are-authored',
    headline: 'The arrest clock, pulse loss, supplied rhythm, pregnancy context, and minute-4 delivery-readiness report are authored.',
    simplification: 'Fixed reports stand in for direct responsiveness, breathing, pulse, fundal-height, circulation, rhythm, airway, pregnancy, cause, fetal-monitor, delivery-readiness, hemorrhage, newborn and resuscitation assessment.',
    whereItMisleads: 'Treating fictional timing, pulse loss, electrical rate, pregnancy context, persistent arrest, or delivery readiness as learner evidence, CPR quality, treatment effect, a universal delivery threshold, prognosis, or predicted outcome.',
    correctUnderstanding: 'Real maternal cardiac arrest requires immediate standard resuscitation, pregnancy-specific modifications, preparation for in-place resuscitative delivery from recognition when indicated, parallel reversible-cause work, and trained maternal, obstetric, anesthesia, newborn, hemorrhage and support teams.',
    briefIn: ['maternal-cardiac-arrest-coordinated-response'],
  },
  {
    id: 'maternal-arrest-controls-activate-reconcile-prepare-review-reassess-and-handoff-only',
    headline: 'The controls activate qualified response, reconcile context, review responsibilities and readiness, reassess, and hand off only.',
    simplification: 'Six actions stand in for qualified BLS/ALS, pregnancy-specific, airway, obstetric, anesthesia, nursing, pharmacy, surgical, delivery, neonatal, blood-bank, critical-care, communication, dignity, family, staff-support, surveillance and handoff work.',
    whereItMisleads: 'Equating button order with pulse or rhythm assessment, CPR, uterine displacement, airway care, access, monitoring, medication, shock, diagnosis, resuscitative delivery, neonatal care, hemorrhage care, termination, disposition, outcome, or competence.',
    correctUnderstanding: 'Actual response is simultaneous and team-based. Standard resuscitation continues while pregnancy modifications, reversible causes and in-place delivery readiness proceed without waiting for transfer or fetal monitoring.',
    briefIn: ['maternal-cardiac-arrest-coordinated-response'],
  },
  {
    id: 'no-live-maternal-arrest-cpr-airway-drug-monitor-delivery-procedure-disposition-or-outcome',
    headline: 'The lab does not assess a pulse, perform CPR, manage an airway, give a drug, operate monitoring, perform delivery, terminate care, determine disposition, or report outcome.',
    simplification: 'No live responsiveness, breathing, pulse, fundal-height, fetal, hemorrhage, ECG, capnography, ultrasound, laboratory or other assessment; compression, uterine displacement, oxygen, ventilation, airway, suction, access, fluid, blood, drug, dose, route, rate, target, defibrillation, pacing, fetal monitoring, ECMO, resuscitative delivery, anesthesia, surgery, neonatal resuscitation, transfer, termination, disposition, prognosis, or maternal or newborn outcome is modeled.',
    whereItMisleads: 'Copying fictional findings into care; delaying standard resuscitation or delivery preparation for a click or cause diagnosis; selecting a maneuver, dose, shock, procedure, transfer or termination action from this rehearsal; treating the minute-5 goal as biologic futility; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local protocols and trained multidisciplinary teams. Pregnancy modifies team roles and selected resuscitation steps but does not replace standard advanced life support or turn one authored rhythm into a fixed future course.',
    briefIn: ['maternal-cardiac-arrest-coordinated-response'],
  },
  {
    id: 'shoulder-dystocia-head-delivery-traction-failure-qualified-maneuvers-and-resolution-are-authored',
    headline: 'Head delivery, failed gentle traction, qualified maneuvers, completed birth, and every maternal or newborn report are authored.',
    simplification: 'Fixed reports stand in for direct obstetric assessment, emergency declaration, positioning, traction, pressure, internal findings, maneuvers, delivery, newborn transfer, examination, resuscitation, injury review, maternal assessment, and documentation.',
    whereItMisleads: 'Treating the fixed 2-minute-10-second case, selected posterior-arm delivery, stable maternal monitor, or absent newborn report as a universal sequence, deadline, treatment effect, proof of no injury, prognosis, or learner-acquired skill.',
    correctUnderstanding: 'Shoulder dystocia is unpredictable and requires rapid trained teamwork, situation-specific maneuvers, avoidance of force and fundal pressure, contemporaneous documentation, newborn readiness, and serial maternal and newborn assessment.',
    briefIn: ['shoulder-dystocia-cognitive-sequence'],
  },
  {
    id: 'shoulder-dystocia-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate the team and clock, reconcile context, review safety and escalation, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for simultaneous qualified birth-team, anesthesia, newborn, leadership, timekeeping, documentation, communication, dignity, family, staff-support, post-birth assessment, review, and handoff work.',
    whereItMisleads: 'Equating button order with diagnosis, positioning, traction, pressure, maneuver choice or performance, episiotomy, birth, newborn resuscitation, injury assessment, documentation quality, or team competence.',
    correctUnderstanding: 'Real response is physical, time-sensitive, flexible, and team-based. Cognitive rehearsal complements but cannot replace hands-on multidisciplinary simulation and assessed psychomotor practice.',
    briefIn: ['shoulder-dystocia-cognitive-sequence'],
  },
  {
    id: 'no-live-shoulder-dystocia-exam-traction-pressure-position-maneuver-procedure-injury-or-outcome',
    headline: 'The lab does not examine, pull, push, position, apply pressure, perform a maneuver or birth, assess injury, determine disposition, or report outcome.',
    simplification: 'No live maternal, fetal, newborn, pelvic or birth assessment; traction, pushing, McRoberts, suprapubic or fundal pressure, all-fours positioning, internal rotation, posterior arm or shoulder delivery, episiotomy, rare rescue, drug, dose, anesthesia, neonatal resuscitation, cord gas, hemorrhage, injury, repair, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as maneuver instructions, delaying immediate trained help for a click or time threshold, repeating an ineffective maneuver, copying the fixed sequence into another birth, or reading completion as procedural competence.',
    correctUnderstanding: 'Use direct findings, a current local protocol, trained multidisciplinary teams, situation-specific maneuver selection, respectful communication, and hands-on simulation with qualified feedback.',
    briefIn: ['shoulder-dystocia-cognitive-sequence'],
  },
  {
    id: 'cord-prolapse-membrane-rupture-exam-fetal-heart-pressure-relief-and-transfer-reports-are-authored',
    headline: 'Membrane rupture, fetal-heart change, qualified cord and labour examination, pressure relief, and theatre-transfer reports are authored.',
    simplification: 'Fixed reports stand in for direct maternal and fetal assessment, monitoring, vaginal examination, cord identification, dilation, presenting-part station, birth imminence, manual elevation, position, transfer, anesthesia, theatre, newborn, documentation, and support work.',
    whereItMisleads: 'Treating the fetal-heart values, 6-minute report, continued elevation, category-1 plan, stable maternal monitor, or absent birth report as learner findings, decompression effect, a universal time target, fetal prognosis, maternal safety, or predicted outcome.',
    correctUnderstanding: 'Cord prolapse is a time-critical fetal emergency requiring direct qualified assessment, immediate multidisciplinary response, temporary pressure relief without unnecessary delay, case-specific safest rapid birth, maternal safety, newborn readiness, communication, and documentation.',
    briefIn: ['umbilical-cord-prolapse-urgent-birth-coordination'],
  },
  {
    id: 'cord-prolapse-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate the response and clock, reconcile supplied context, review temporary bridges and birth coordination, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for simultaneous qualified obstetric, midwifery or nursing, theatre, anesthesia, newborn, leadership, timekeeping, documentation, communication, dignity, family, staff-support, surveillance, pressure-relief, transfer, birth, post-birth, review, and handoff work.',
    whereItMisleads: 'Equating button order with examination, diagnosis, fetal-trace interpretation, cord handling, decompression, medication, anesthesia, birth-mode selection, delivery, newborn care, documentation quality, or team competence.',
    correctUnderstanding: 'Real response is physical, concurrent, time-critical, team-based, and locally rehearsed. Cognitive sequence practice cannot replace hands-on multidisciplinary simulation or assessed clinical performance.',
    briefIn: ['umbilical-cord-prolapse-urgent-birth-coordination'],
  },
  {
    id: 'no-live-cord-prolapse-exam-monitor-interpretation-cord-handling-decompression-drug-anesthesia-delivery-or-outcome',
    headline: 'The lab does not examine, interpret fetal monitoring, handle the cord, relieve compression, choose medication or anesthesia, perform birth, determine disposition, or report outcome.',
    simplification: 'No live maternal, fetal, labour, cervical, presenting-part, cord, contraction, CTG, ultrasound, blood, gas, newborn, neurologic, or injury assessment; cord handling or replacement, manual elevation, bladder filling, positioning, oxygen, fluid, tocolytic, drug, dose, route, access, anesthesia, operative vaginal or caesarean birth, neonatal resuscitation, transfer, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as examination, monitoring, decompression, positioning, medication, anesthesia, delivery, or newborn-care instructions; delaying immediate trained help for a click; fixating on a time target over maternal safety; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, continuous qualified fetal assessment, the current local cord-prolapse protocol, trained multidisciplinary teams, temporary pressure relief without avoidable birth delay, case-specific birth and anesthesia planning, and hands-on simulation with qualified feedback.',
    briefIn: ['umbilical-cord-prolapse-urgent-birth-coordination'],
  },
  {
    id: 'suspected-uterine-rupture-scar-multisignal-trajectory-and-laparotomy-report-are-authored',
    headline: 'Scar history, pain, fetal-heart change, station loss, altered contractions, bleeding, maternal trajectory, and laparotomy-start report are authored.',
    simplification: 'Fixed reports stand in for direct maternal and fetal assessment, examination, CTG acquisition and interpretation, labour progress, bleeding and shock assessment, resuscitation, transfer, anesthesia, operative findings, birth, newborn care, documentation, explanation, and support.',
    whereItMisleads: 'Treating the supplied values, 7-minute trajectory, small visible loss, or start of laparotomy as learner findings, diagnostic proof, total hemorrhage, treatment effect, a universal time target, fetal location, completed birth, prognosis, or outcome.',
    correctUnderstanding: 'Suspected rupture is a clinical emergency recognized from the whole evolving pattern. Qualified maternal support, fetal surveillance, surgical access, anesthesia, hemorrhage readiness, newborn care, communication, and operative confirmation proceed together.',
    briefIn: ['suspected-uterine-rupture-recognition'],
  },
  {
    id: 'suspected-uterine-rupture-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate the response, connect supplied signals, review uncertainty and parallel readiness, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for simultaneous qualified obstetric, midwifery or nursing, theatre, anesthesia, blood-bank, hemorrhage, newborn, leadership, timekeeping, documentation, communication, dignity, family, staff-support, operative, post-birth, review, and handoff work.',
    whereItMisleads: 'Equating button order with examination, CTG interpretation, diagnosis, resuscitation, infusion change, anesthesia, operation, delivery, repair, hysterectomy, newborn care, documentation quality, or team competence.',
    correctUnderstanding: 'Real response is concurrent, physical, time-critical, team-based, and locally rehearsed. Cognitive sequence practice cannot replace direct care or hands-on multidisciplinary simulation with qualified feedback.',
    briefIn: ['suspected-uterine-rupture-recognition'],
  },
  {
    id: 'no-live-uterine-rupture-exam-monitor-interpretation-diagnosis-resuscitation-anesthesia-delivery-surgery-or-outcome',
    headline: 'The lab does not examine, interpret fetal monitoring, diagnose rupture, resuscitate, select anesthesia, perform birth or surgery, determine fertility or disposition, or report outcome.',
    simplification: 'No live maternal, fetal, abdominal, scar, cervical, presenting-part, contraction, CTG, ultrasound, blood, urine, laboratory, operative, newborn, neurologic, injury, or fertility assessment; infusion change, oxygen, fluid, blood, drug, dose, route, target, access, anesthesia, caesarean birth, laparotomy, repair, hysterectomy, neonatal resuscitation, transfer, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as examination, monitoring, resuscitation, anesthesia, delivery, surgical, fertility, or newborn-care instructions; delaying immediate trained response for diagnostic certainty or a click; underestimating concealed bleeding; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, continuous qualified fetal and maternal assessment, current local protocols, immediate multidisciplinary response, operative confirmation, situation-specific resuscitation and surgery, respectful communication, and hands-on simulation with qualified feedback.',
    briefIn: ['suspected-uterine-rupture-recognition'],
  },
  {
    id: 'magnesium-toxicity-exposure-renal-reflex-respiratory-level-and-response-reports-are-authored',
    headline: 'Magnesium exposure, renal decline, examination, respiratory pattern, level, and 5-minute response are authored.',
    simplification: 'Fixed reports stand in for medication reconciliation, infusion inspection, urine measurement, renal and electrolyte testing, airway and breathing assessment, reflex and neurological examination, ECG review, source control, respiratory support, calcium antidote, newborn consideration, communication, and serial reassessment.',
    whereItMisleads: 'Treating the supplied infusion history, urine output, creatinine, magnesium level, absent reflexes, monitor values, or partial respiratory change as learner findings, a universal toxicity threshold, calcium effect, complete reversal, safe restart, newborn safety, prognosis, or outcome.',
    correctUnderstanding: 'Recognize magnesium toxicity from the whole evolving clinical and exposure pattern. Direct assessment, source control, airway and ventilation support, antidote use, monitoring, renal review, newborn consideration, and alternatives remain qualified team care.',
    briefIn: ['magnesium-sulfate-toxicity-recognition'],
  },
  {
    id: 'magnesium-toxicity-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate qualified help, connect supplied findings, review uncertainty and readiness, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for simultaneous qualified obstetric, nursing, anesthesia and airway, critical-care, pharmacy, laboratory, renal, newborn, leadership, timekeeping, documentation, communication, dignity, family, staff-support, review, and handoff work.',
    whereItMisleads: 'Equating button order with examination, monitoring or laboratory interpretation, diagnosis, infusion operation, airway management, ventilation, calcium selection or delivery, medication safety, newborn assessment, documentation quality, or competence.',
    correctUnderstanding: 'Real response is concurrent, physical, time-critical, team-based, and locally protocolized. Cognitive sequence practice cannot replace direct care or hands-on multidisciplinary simulation with qualified feedback.',
    briefIn: ['magnesium-sulfate-toxicity-recognition'],
  },
  {
    id: 'no-live-magnesium-toxicity-exam-monitor-lab-interpretation-infusion-change-airway-drug-procedure-or-outcome',
    headline: 'The lab does not examine, interpret monitoring or tests, operate an infusion, manage an airway, give calcium or another drug, assess a newborn, determine disposition, or report outcome.',
    simplification: 'No live medication, pump, line, urine, fluid-balance, respiratory, airway, reflex, neurological, cardiovascular, postpartum, newborn, ECG, magnesium, renal, electrolyte, glucose, gas, imaging or other assessment; infusion stop or restart, oxygen, ventilation, airway device, calcium, fluid, diuretic, drug, dose, concentration, rate, route, target, access, seizure care, dialysis, procedure, transfer, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as toxicity diagnosis, serum-threshold, infusion, airway, ventilation, antidote, dose, renal-replacement, seizure, newborn, or disposition instructions; delaying immediate trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, exact medication and unit reconciliation, current local protocols, immediate airway-capable multidisciplinary response, qualified antidote and renal decisions, serial reassessment, respectful communication, and hands-on simulation.',
    briefIn: ['magnesium-sulfate-toxicity-recognition'],
  },
  {
    id: 'high-neuraxial-block-injection-level-maternal-fetal-and-qualified-support-reports-are-authored',
    headline: 'The injection, block findings, maternal and fetal pattern, and 4-minute qualified-support report are authored.',
    simplification: 'Fixed reports stand in for medication and catheter reconciliation, sensory and motor examination, airway and breathing assessment, maternal and fetal monitoring, uterine displacement, circulation support, vasopressor and fluid care, anesthesia, birth planning, reassurance, documentation, and serial review.',
    whereItMisleads: 'Treating the injection clock, C6 level, maternal or fetal values, partial change, or persistent weakness as learner findings, a universal progression, treatment effect, block recession, airway safety, fetal recovery, completed birth, prognosis, or outcome.',
    correctUnderstanding: 'High neuraxial block can progress rapidly and requires direct serial assessment, airway-capable help, maternal circulation support, pregnancy-specific positioning, fetal and birth planning, close reassurance, and trained multidisciplinary care.',
    briefIn: ['high-neuraxial-block-obstetric-coordination'],
  },
  {
    id: 'high-neuraxial-block-obstetric-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate qualified help, connect supplied findings, review progression and readiness, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for simultaneous qualified anesthesia and airway, obstetric, nursing, theatre, newborn, pharmacy, critical-care, leadership, timekeeping, documentation, communication, dignity, family, staff-support, post-event review, and handoff work.',
    whereItMisleads: 'Equating button order with examination, block assessment, monitoring interpretation, airway or ventilation skill, positioning, circulation support, medication choice, anesthesia, birth, newborn care, documentation quality, or competence.',
    correctUnderstanding: 'Real response is concurrent, physical, time-critical, team-based, and locally rehearsed. Cognitive sequence practice cannot replace direct care or hands-on multidisciplinary simulation with qualified feedback.',
    briefIn: ['high-neuraxial-block-obstetric-coordination'],
  },
  {
    id: 'no-live-high-neuraxial-block-exam-monitor-infusion-airway-circulation-drug-birth-procedure-or-outcome',
    headline: 'The lab does not assess a block, interpret monitoring, operate an infusion, manage an airway or circulation, give a drug, perform birth, determine disposition, or report outcome.',
    simplification: 'No live medication, catheter, line, sensory, motor, airway, breathing, circulation, consciousness, awareness, maternal, fetal, labour, newborn, ECG, pressure, oxygenation, capnography or other assessment; injection stop, position, uterine displacement, oxygen, ventilation, airway device, fluid, vasopressor, anticholinergic, hypnotic or other drug, dose, concentration, route, rate, target, anesthesia, delivery, procedure, transfer, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as block-height, airway, ventilation, circulation, positioning, vasopressor, dose, anesthesia, delivery, newborn, or disposition instructions; delaying immediate trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, exact medication and catheter reconciliation, current local protocols, immediate airway-capable multidisciplinary response, pregnancy-specific maternal and fetal care, respectful communication, and hands-on simulation.',
    briefIn: ['high-neuraxial-block-obstetric-coordination'],
  },
  {
    id: 'failed-obstetric-intubation-attempt-airway-device-maternal-fetal-and-qualified-course-reports-are-authored',
    headline: 'The attempts, rescue airway, maternal-fetal pattern, decision process, and 3-minute qualified report are authored.',
    simplification: 'Fixed reports stand in for laryngoscopy, device placement and seal, ventilation, capnography, oxygenation, aspiration and awareness review, maternal and fetal monitoring, staff and surgical context, wake-or-proceed decision-making, incision, documentation, and serial review.',
    whereItMisleads: 'Treating 2 attempts, the rescue device, displayed values, absent reported hazards, proceeding decision, or partial stability as learner findings, universal thresholds, technical success, treatment effect, fetal recovery, completed birth, prognosis, or outcome.',
    correctUnderstanding: 'Failed obstetric intubation requires immediate declaration, experienced help, oxygenation priority, limited attempts, readiness for CICO, individualized senior decision-making, and direct multidisciplinary care.',
    briefIn: ['failed-obstetric-intubation-oxygenation-first'],
  },
  {
    id: 'failed-obstetric-intubation-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate qualified help, connect supplied facts, review safety and decision boundaries, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified anesthesia and airway, obstetric, nursing, theatre, newborn, pharmacy, critical-care, leadership, timekeeping, documentation, communication, dignity, family, staff-support, post-event review, and handoff work.',
    whereItMisleads: 'Equating button order with examination, airway or ventilation skill, device placement, monitoring interpretation, wake-or-proceed judgement, anesthesia, surgery, birth, newborn care, documentation quality, or competence.',
    correctUnderstanding: 'Real response is concurrent, physical, time-critical, team-based, and locally rehearsed. Cognitive practice cannot replace direct care or hands-on multidisciplinary simulation with qualified feedback.',
    briefIn: ['failed-obstetric-intubation-oxygenation-first'],
  },
  {
    id: 'no-live-failed-obstetric-intubation-airway-monitor-anesthesia-drug-surgery-birth-procedure-or-outcome',
    headline: 'The lab does not manage an airway, interpret monitoring, choose anesthesia or wake-or-proceed strategy, operate, deliver, or report outcome.',
    simplification: 'No live airway examination, laryngoscopy, mask or device manipulation, cricoid-pressure change, oxygen, ventilation, suction, position, front-of-neck access, monitoring, drug, dose, fluid, blood, anesthesia, surgery, delivery, newborn care, procedure, transfer, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as airway-device, oxygenation, ventilation, aspiration, anesthetic, wake-or-proceed, surgery, birth, newborn, or disposition instructions; delaying trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use direct findings, current local protocols and equipment, immediate experienced airway and obstetric help, qualified individualized decisions, respectful communication, and hands-on simulation.',
    briefIn: ['failed-obstetric-intubation-oxygenation-first'],
  },
  {
    id: 'maternal-neonatal-handoff-maternal-fetal-birth-newborn-and-qualified-course-reports-are-authored',
    headline: 'The maternal, fetal, birth, newborn-resuscitation, and 5-minute qualified reports are authored.',
    simplification: 'Fixed reports stand in for antenatal and intrapartum record review, birth documentation, newborn examination and monitoring, timed resuscitation, response assessment, placental and cord-gas review, postresuscitation monitoring, maternal surgery, family communication, and serial review.',
    whereItMisleads: 'Treating the birth clock, heart-rate reports, ventilation response, displayed maternal values, absent supplied risks, pending tests, or planned monitored care as learner findings, universal thresholds, technical success, stable transition, diagnosis, prognosis, or outcome.',
    correctUnderstanding: 'Every birth needs a dedicated newborn-capable clinician; effective ventilation is prioritized when required, and infants needing more than initial steps need direct qualified observation, monitoring, structured transfer, and follow-up.',
    briefIn: ['maternal-to-neonatal-resuscitation-handoff'],
  },
  {
    id: 'maternal-neonatal-handoff-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls name owners, connect supplied facts, review response and transfer structure, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified maternal, newborn, anesthesia, obstetric, nursing, theatre, laboratory, placental, transport, leadership, timekeeping, documentation, communication, dignity, family, staff-support, debriefing, and handoff work.',
    whereItMisleads: 'Equating button order with maternal or newborn examination, monitoring interpretation, resuscitation skill, closed-loop communication quality, family counseling, transport readiness, documentation quality, or competence.',
    correctUnderstanding: 'Real resuscitation and transfer are concurrent, physical, time-critical, team-based, interruption-aware, locally rehearsed, and verified by the receiver. Cognitive practice cannot replace direct care or hands-on simulation with qualified feedback.',
    briefIn: ['maternal-to-neonatal-resuscitation-handoff'],
  },
  {
    id: 'no-live-maternal-neonatal-exam-monitor-resuscitation-oxygen-drug-procedure-transfer-disposition-or-outcome',
    headline: 'The lab does not examine, monitor, resuscitate, treat, transport, counsel, determine disposition, or report outcome.',
    simplification: 'No live maternal or newborn examination, Apgar scoring, monitoring, glucose, temperature, laboratory, cord-gas or placental assessment; drying, stimulation, suction, position, oxygen, ventilation, airway, compressions, access, fluid, blood, glucose, epinephrine or other drug or dose; maternal anesthesia, surgery, delivery, newborn care, transport, cooling, family counseling, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as resuscitation, oxygen, glucose, temperature, cooling, transfer, counseling, or disposition instruction; delaying immediate trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local neonatal-resuscitation and transfer protocols, immediate trained teams, explicit transfer of responsibility, respectful family communication, and hands-on multidisciplinary simulation.',
    briefIn: ['maternal-to-neonatal-resuscitation-handoff'],
  },
  {
    id: 'oxytocin-tachysystole-infusion-contraction-fetal-maternal-and-qualified-course-reports-are-authored',
    headline: 'The oxytocin exposure, contraction and fetal-heart pattern, maternal state, qualified response, and 6-minute report are authored.',
    simplification: 'Fixed reports stand in for infusion and line reconciliation, uterine and fetal monitoring, maternal assessment, position, signal verification, source stop, cause review, surveillance, escalation readiness, communication, and serial review.',
    whereItMisleads: 'Treating 6 contractions, fetal-heart features, displayed maternal values, absent supplied alternatives, early recovery, or qualified source stop as learner findings, universal action thresholds, diagnosis, treatment effect, restart eligibility, birth safety, prognosis, or outcome.',
    correctUnderstanding: 'Oxytocin-associated excessive contraction frequency must be assessed with the evolving fetal-heart pattern and whole maternal-fetal picture, with immediate qualified source reduction or stop and cause-specific response.',
    briefIn: ['oxytocin-associated-uterine-tachysystole'],
  },
  {
    id: 'oxytocin-tachysystole-controls-activate-reconcile-review-reassess-and-handoff-only',
    headline: 'The controls activate qualified help, connect supplied facts, review pattern and readiness, read a fixed report, and hand off only.',
    simplification: 'Six actions stand in for concurrent qualified obstetric, midwifery, anesthesia, newborn, pharmacy, theatre, leadership, timekeeping, documentation, communication, dignity, family, staff-support, surveillance, escalation, and handoff work.',
    whereItMisleads: 'Equating button order with examination, palpation, fetal-monitor interpretation, infusion management, positioning, medication choice, birth planning, documentation quality, or competence.',
    correctUnderstanding: 'Real response is concurrent, physical, time-critical, team-based, individualized, and locally rehearsed. Cognitive sequence practice cannot replace direct care or hands-on multidisciplinary simulation with qualified feedback.',
    briefIn: ['oxytocin-associated-uterine-tachysystole'],
  },
  {
    id: 'no-live-oxytocin-tachysystole-exam-monitor-infusion-position-oxygen-fluid-drug-birth-procedure-or-outcome',
    headline: 'The lab does not examine, interpret monitoring, operate oxytocin, position, give oxygen, fluid, or a drug, perform birth, determine disposition, or report outcome.',
    simplification: 'No live maternal or fetal examination, palpation, contraction or fetal-heart monitoring, signal verification, laboratory or placental assessment; infusion or line operation, position, oxygen, fluid, tocolytic or other drug, dose, fetal stimulation, amnioinfusion, anesthesia, surgery, delivery, newborn care, procedure, restart, birth-plan, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using the rehearsal as CTG, oxytocin, position, oxygen, fluid, tocolysis, birth, newborn, or disposition instruction; delaying immediate trained response for a click; or reading completion as competence.',
    correctUnderstanding: 'Use verified direct findings, current local protocols, immediate qualified obstetric review, cause-specific conservative measures, continuous communication and surveillance, and hands-on simulation.',
    briefIn: ['oxytocin-associated-uterine-tachysystole'],
  },
];
