/**
 * The oncology module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a oncology scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const ONCOLOGY_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'delayed-immune-event-presentation-and-service-response-are-authored',
    headline: 'One presentation, one telephone call, and a patient who does not deteriorate.',
    simplification: 'The case supplies a fixed set of observations, a stool count that rises once, and a treating service that answers sixty minutes after it is contacted with a fixed reply. No immune, mucosal, infective, or treatment-response model runs underneath, and no grade is assigned.',
    whereItMisleads: 'A learner concludes that a delayed immune-related event presents this calmly, that the treating service always answers, or that recognising the exposure is what kept this patient stable.',
    correctUnderstanding: 'Nothing the learner does in this rehearsal changes his course, because nothing was going to. The observations are held unremarkable so that the attribution problem is the only thing being tested, and a real presentation may be more unwell, may have another cause entirely, or may be both at once. The service reply is authored: in practice the call may not be answered, and the plan has to survive that.',
    briefIn: ['delayed-immune-event-a-drug-that-stopped-months-ago'],
  },
  {
    id: 'delayed-immune-event-controls-are-recording-and-escalation-only',
    headline: 'No drug is selected, no grade is assigned, and no test is ordered.',
    simplification: 'The learner records the completed exposure, records the course against the patient\u2019s own baseline, records infection evaluation as running alongside, contacts the treating service, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The bounded treatment-intent control is read as prescribing corticosteroids, or the infection-evaluation control is read as the learner ordering and interpreting stool tests.',
    correctUnderstanding: 'Grading, investigation including endoscopy, and every treatment decision belong to the qualified team, and this lesson exposes no drug, dose, route, threshold, or eligibility rule. Recording that a decision exists and belongs to somebody else is not making it.',
    briefIn: ['delayed-immune-event-a-drug-that-stopped-months-ago'],
  },
  {
    id: 'delayed-immune-event-series-figures-are-not-an-incidence',
    headline: 'Twenty-three collected cases cannot tell you how often this happens.',
    simplification: 'The case reports that the series naming delayed immune-related events found a median off-treatment interval of six months after a median of four doses, and that pharmacovigilance data attribute most reported anti-CTLA-4 fatalities to colitis.',
    whereItMisleads: 'A learner reads the six-month median as the expected timing, treats 23 cases as a risk estimate, or carries the anti-CTLA-4 colitis fatality figure onto an anti-PD-1 patient.',
    correctUnderstanding: 'The series is a literature collation of reported cases with no denominator: it establishes that these events occur late and are missed, not how likely they are in any patient. Its own argument is diagnostic rather than epidemiological. The fatality spectrum differs by drug class — anti-PD-1 and anti-PD-L1 fatalities were more often pneumonitis, hepatitis, and neurotoxic effects — so the colitis figure describes a class this patient did not receive.',
    briefIn: ['delayed-immune-event-a-drug-that-stopped-months-ago'],
  },
  {
    id: 'incidental-clot-presentation-and-service-response-are-authored',
    headline: 'One report, one telephone call, and a patient who stays well throughout.',
    simplification: 'The case supplies a fixed set of observations that never move, a patient who asks his question at a fixed time, and a treating service that answers sixty minutes after it is contacted with a fixed reply. No thrombosis, bleeding, or anticoagulation-response model runs underneath, and no decision is reached.',
    whereItMisleads: 'A learner concludes that an incidental pulmonary embolus is always this quiet, that the treating service always answers, or that patients reliably volunteer what matters to them.',
    correctUnderstanding: 'Nothing the learner does changes his course, because nothing was going to. He is held well so that the decision cannot be settled by a deterioration, and his question is authored so that the values input arrives at all. In practice the patient may be unwell, may never raise it, and the call may not be answered; the plan has to survive each of those.',
    briefIn: ['incidental-clot-a-decision-the-evidence-cannot-make'],
  },
  {
    id: 'incidental-clot-controls-are-recording-and-escalation-only',
    headline: 'No anticoagulant is selected, and no decision is reached.',
    simplification: 'The learner records the finding and how it was found, records the strength and certainty of the recommendation, records the benefit and the harm together, records this patient\u2019s bleeding risk, contacts the treating service, records the decision as shared, and reviews the boundaries.',
    whereItMisleads: 'The shared-decision control is read as obtaining consent or agreeing a plan, or the refusal of immediate anticoagulation is read as this lesson recommending observation.',
    correctUnderstanding: 'Nothing is agreed and nothing is administered. The lesson refuses both reflexes and reaches neither conclusion, because the guidance it rests on suggests treatment conditionally on very low certainty and says the individual risk of thrombosis and of major bleeding should decide after full discussion. Observation is a legitimate outcome of that discussion; so is anticoagulation. Neither is this learner\u2019s to declare.',
    briefIn: ['incidental-clot-a-decision-the-evidence-cannot-make'],
  },
  {
    id: 'incidental-clot-figures-are-population-estimates-on-very-low-certainty',
    headline: 'Every number in this lesson is a population estimate the panel itself rated very low.',
    simplification: 'The case reports about 89 fewer deaths, 77 fewer symptomatic emboli, and 128 more major bleeds per 1000 with treatment, a six-month mortality of about 37 percent, and an incidence of about 3 percent.',
    whereItMisleads: 'A learner reads the per-1000 figures as this patient\u2019s risks, treats the mortality figure as an effect of the clot or of the decision, or takes the direction of the estimates as settled.',
    correctUnderstanding: 'The effect estimates come from observational data with no randomised trial and no systematic review addressing the question, and the panel rated the certainty very low for risk of bias, inconsistency and imprecision. The 37 percent six-month mortality is the mortality of the population studied \u2014 people with advanced cancer \u2014 not a consequence of the embolus or of anticoagulating it. The registry cohort points the other way on bleeding, and its authors call the risk-benefit ratio uncertain.',
    briefIn: ['incidental-clot-a-decision-the-evidence-cannot-make'],
  },
  {
    id: 'normal-test-toxicity-presentation-and-service-response-are-authored',
    headline: 'One presentation, one dose falling due, and one telephone call.',
    simplification: 'The case supplies fixed observations, an evening dose that falls due at a fixed time and is taken unless the drug was withheld, and an acute oncology service that answers sixty minutes after it is contacted with a fixed reply. No enzyme, absorption, or toxicity-kinetics model runs underneath, and no grade is assigned.',
    whereItMisleads: 'A learner reads the taken dose as a modelled harm, concludes that severe fluoropyrimidine toxicity always looks like this, or expects the treating service to answer.',
    correctUnderstanding: 'The taken dose is recorded as a fact about what happened, not as a prediction about what it will do; the fixture models no consequence of it, because it cannot. A real presentation may be far more unwell, may involve fever or a low neutrophil count that this fixture does not supply, and the call may not be answered. The withholding has to happen regardless of any of that.',
    briefIn: ['normal-test-toxicity-the-dose-in-his-bag'],
  },
  {
    id: 'normal-test-toxicity-controls-are-withholding-and-escalation-only',
    headline: 'One drug is stopped here, and no drug is ever chosen.',
    simplification: 'The learner withholds the oral anticancer drug, records what the normal pre-treatment panel does and does not exclude, records the toxicity with its severity and cycle day, contacts acute oncology, records bounded qualified-team supportive intent, and reviews the boundaries.',
    whereItMisleads: 'The bounded supportive-intent control is read as prescribing fluids or an antidote, or the refusal to advise a halved dose is read as this lesson taking a position on dose modification.',
    correctUnderstanding: 'Stopping a drug and starting one are different acts, and only the first is exposed here. Grading, dose modification, supportive treatment, any specific antidotal treatment, and whether the drug is ever restarted all belong to the qualified team, and no agent, dose, route, fluid, or threshold appears anywhere in this lesson.',
    briefIn: ['normal-test-toxicity-the-dose-in-his-bag'],
  },
  {
    id: 'normal-test-toxicity-genotype-figures-are-not-this-patients-risk',
    headline: 'The genotype figures describe cohorts, and this patient is not a cohort.',
    simplification: 'The case reports severe toxicity in 23 percent of wild-type patients and 39 percent of dose-reduced variant carriers, severe toxicity in up to 30 percent of treated patients, and adjusted relative risks of roughly 2.9 to 4.4 for the screened variants.',
    whereItMisleads: 'A learner reads 23 percent as this patient\u2019s probability, treats the panel as useless because it did not predict him, or infers that he has an enzyme deficiency.',
    correctUnderstanding: 'These are cohort frequencies and adjusted relative risks, not individual probabilities, and the prospective analysis was a safety study rather than a randomised comparison. The panel is genuinely predictive, which is precisely why a wild-type result narrows the differential without closing it. Nothing in this lesson establishes why this patient became toxic; no enzyme activity was measured, and none is claimed.',
    briefIn: ['normal-test-toxicity-the-dose-in-his-bag'],
  },
  {
    id: 'prognosis-question-conversation-and-readback-are-authored',
    headline: 'One conversation, one repeated question, and one readback in a corridor.',
    simplification: 'The case supplies a patient who asks at a fixed time, states his reason at a fixed time, and repeats the answer back thirty minutes after it is given. What he repeats is decided by whether the direction of the error was stated. No survival, disease, or comprehension model runs underneath.',
    whereItMisleads: 'A learner reads the readback as evidence that saying the right thing reliably produces understanding, or that a patient who repeats three scenarios has accepted them.',
    correctUnderstanding: 'The readback is an authored contrast built to make one difference visible, not a measurement of comprehension. Real understanding is partial, moves between conversations, and often has to be rebuilt from the beginning next time. A patient may repeat a range accurately and still plan on the best case, and none of that is modelled here.',
    briefIn: ['prognosis-question-a-number-he-asked-for'],
  },
  {
    id: 'prognosis-question-controls-are-conversation-only',
    headline: 'Nothing is examined, ordered, prescribed, or predicted in this lesson.',
    simplification: 'The learner establishes what the question is for, records it, checks a belief, answers in scenarios, states the direction of the error, and reviews the boundaries. The observations are supplied and are deliberately irrelevant.',
    whereItMisleads: 'The scenario answer is read as this project generating a prognosis, or the typical figure is taken to be computed from the patient in front of the learner.',
    correctUnderstanding: 'No number here is derived from this patient. The lesson teaches the shape an honest answer takes and where its uncertainty comes from; the estimate a real answer is built around is a clinician\u2019s judgement, made with the patient\u2019s disease, treatment, and trajectory in front of them, and this simulator neither makes nor checks one.',
    briefIn: ['prognosis-question-a-number-he-asked-for'],
  },
  {
    id: 'prognosis-question-figures-describe-estimators-not-this-patient',
    headline: 'Every figure in this lesson describes the people answering, not the man asking.',
    simplification: 'The case reports that 20 percent of predictions were accurate to within a third, that 63 percent were over-optimistic by roughly fivefold, and that observed survival fell between half and double an estimate in 63 percent of patients.',
    whereItMisleads: 'A learner carries the fivefold optimism onto a patient on second-line treatment, or reads the scenario proportions as this patient\u2019s probabilities.',
    correctUnderstanding: 'The optimism cohort was 468 patients at hospice referral with a median survival of 24 days; what generalises from it is the direction of the error, which was consistent, not its size, which is not. The scenario proportions come from 114 patients of 21 oncologists and describe how often that method\u2019s brackets contained the truth, not how long anyone lived. Neither says anything about this man.',
    briefIn: ['prognosis-question-a-number-he-asked-for'],
  },
  {
    id: 'laboratory-tls-bloods-and-team-response-are-authored',
    headline: 'One set of bloods, one repeat, and a patient who stays well throughout.',
    simplification: 'The case supplies a laboratory picture that meets the definition, a repeat set thirty minutes later that has moved further, and a treating team that answers sixty minutes after it is contacted. The observations never change. No metabolic, renal, or tumour-burden model runs underneath.',
    whereItMisleads: 'A learner concludes that laboratory tumour lysis reliably stays laboratory, that a patient who is well at 18 hours will be well at 72, or that the repeat set moving is itself reassuring because he did not.',
    correctUnderstanding: 'The fixture holds him well so that the definition cannot be settled by a deterioration, which is the only way to keep the lesson about what a definition is for. It says nothing about whether this patient would cross over, and it models no consequence of the bloods it moves. A real patient may cross, quickly, and the window exists precisely because that cannot be read off how he looks.',
    briefIn: ['laboratory-tls-a-syndrome-he-does-not-have-yet'],
  },
  {
    id: 'laboratory-tls-controls-are-recording-and-escalation-only',
    headline: 'Nothing is given, corrected, prescribed, or ordered in this lesson.',
    simplification: 'The learner records which definition is met, what crossed and when, and what raises the risk of crossing over, contacts the treating team, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The refusal of "treat the potassium and stand down" is read as this lesson taking a position on whether the potassium should be treated, or the bounded-intent control is read as ordering fluids.',
    correctUnderstanding: 'What was refused is the standing down, not the treating: correcting one value and recording the problem as handled is how a laboratory picture becomes a clinical one unobserved. Hydration, hypouricaemic treatment, electrolyte management, monitoring frequency and any renal referral all belong to the qualified team, and no agent, dose, rate, or threshold appears anywhere in this lesson.',
    briefIn: ['laboratory-tls-a-syndrome-he-does-not-have-yet'],
  },
  {
    id: 'laboratory-tls-published-rates-disagree-and-none-is-his',
    headline: 'The published incidence figures disagree, and one is widely restated wrongly.',
    simplification: 'The case reports laboratory tumour lysis in 42 percent and clinical in 6 percent of one series, and hyperuricaemia in 18.9 percent of a second cohort with 27.8 percent of those meeting tumour-lysis criteria.',
    whereItMisleads: 'A learner reads either figure as this patient\u2019s probability of crossing over, or repeats the version of the second study that a 2024 review states, in which 18.9 percent is a laboratory tumour-lysis rate.',
    correctUnderstanding: 'The two studies used different definitions, populations and eras of prophylaxis, and neither is a risk estimate for an individual. The second measured hyperuricaemia, not laboratory tumour lysis, and its authors noted their rates were lower than earlier reports; a review restating it otherwise is the ordinary way a number drifts from what was measured. That drift is the reason this lesson records the finding in front of the learner rather than the name of a syndrome.',
    briefIn: ['laboratory-tls-a-syndrome-he-does-not-have-yet'],
  },
  {
    id: 'rare-early-myocarditis-presentation-and-conduction-are-authored',
    headline: 'One presentation, one conduction change, and a patient who looks well throughout.',
    simplification: 'The case supplies fixed observations, a supplied troponin and electrocardiogram, and a conduction change that appears twenty-five minutes after monitoring is arranged. No myocardial, conduction, or immune model runs underneath, and nothing deteriorates.',
    whereItMisleads: 'A learner concludes that checkpoint-inhibitor myocarditis presents this quietly, that conduction always moves within half an hour, or that a patient who still looks well is not in danger.',
    correctUnderstanding: 'He is held well and the change is held small so that the decision cannot be made for the learner by a collapse, which is the only way to keep the lesson about a threshold. Real presentations include fulminant heart failure, arrest and malignant arrhythmia, and the conduction may move far faster or not at all. Nothing here models what would have happened next.',
    briefIn: ['rare-early-myocarditis-a-base-rate-is-not-a-threshold'],
  },
  {
    id: 'rare-early-myocarditis-controls-are-monitoring-and-escalation-only',
    headline: 'No test is acquired here, and no treatment is chosen.',
    simplification: 'The learner records the exposure interval, records what is present that does not sound cardiac, arranges continuous rhythm monitoring, contacts both teams, records bounded qualified-team intent, and reviews the boundaries. The troponin and electrocardiogram are supplied.',
    whereItMisleads: 'Arranging monitoring is read as ordering investigations, or the refusal of the coronary pathway is read as this lesson ruling out a coronary syndrome.',
    correctUnderstanding: 'Monitoring is a decision to observe, not a test or a treatment, and it is the only intervention this lesson exposes. What was refused about the coronary pathway is stopping there, not considering it: nothing in this lesson excludes coronary disease, and imaging, further testing, immunosuppressive treatment, rhythm management and any restart all belong to the qualified teams.',
    briefIn: ['rare-early-myocarditis-a-base-rate-is-not-a-threshold'],
  },
  {
    id: 'rare-early-myocarditis-incidence-and-fatality-answer-different-questions',
    headline: 'The incidence and the fatality are about different things, and neither is about him.',
    simplification: 'The case reports a trial incidence of roughly 0.1 to 1 percent, a historical mortality of 30 to 50 percent, and the highest reported fatality of any checkpoint-inhibitor toxicity at 52 of 131 cases.',
    whereItMisleads: 'A learner combines the two into a risk for this patient, or reads the 161-patient series as describing everyone exposed to these drugs.',
    correctUnderstanding: 'The incidence describes how often the event occurs among people treated; the fatality describes what happens to those who have it, and comes from spontaneously reported cases, which over-represent severity. The series is retrospective and drawn from centres that see these patients, so it describes people already diagnosed. Multiplying them together produces a number that corresponds to nothing, and none of the three is a probability for the man in front of the learner.',
    briefIn: ['rare-early-myocarditis-a-base-rate-is-not-a-threshold'],
  },
  {
    id: 'lowering-the-count-presentation-and-deterioration-are-authored',
    headline: 'One presentation, one deterioration, and a supplied count that cannot change.',
    simplification: 'The case supplies a film taken an hour before, observations that worsen once at twenty minutes, and a haematology team that answers forty minutes after it is called. No leukocyte, viscosity, or cytoreduction model runs underneath.',
    whereItMisleads: 'A learner reads the deterioration as a consequence of being too slow, or expects a real presentation to deteriorate on this schedule and no faster.',
    correctUnderstanding: 'The deterioration is authored and follows from nothing the learner did or failed to do; the fixture models no relationship between any action and his trajectory, and the rehearsal ends the same way whatever is chosen. A real patient may deteriorate far faster, may arrest, or may be stable for hours. The urgency in this lesson comes from the published mortality, not from the fixture.',
    briefIn: ['lowering-the-count-a-number-that-can-be-moved'],
  },
  {
    id: 'lowering-the-count-controls-are-recording-and-escalation-only',
    headline: 'No cytoreduction is started here, and no route is chosen.',
    simplification: 'The learner records the clinical picture, records what the count licenses, calls haematology, records bounded qualified-team intent, and reviews the boundaries. The film and the count are supplied.',
    whereItMisleads: 'The refusal of apheresis is read as this lesson recommending against leukapheresis for this patient, or the bounded-intent control is read as starting cytoreduction.',
    correctUnderstanding: 'What was refused is standing down once the count is being lowered, not the route: the cited meta-analysis argues against routine use, and choosing between leukapheresis, hydroxyurea and chemotherapy is a qualified-team decision that this lesson deliberately does not make. Nothing here selects, gives, or withholds any treatment.',
    briefIn: ['lowering-the-count-a-number-that-can-be-moved'],
  },
  {
    id: 'lowering-the-count-absence-of-benefit-is-not-proof-of-uselessness',
    headline: 'A confidence interval that crosses one supports two wrong conclusions.',
    simplification: 'The case reports a meta-analytic risk ratio for early death with leukapheresis of 0.88, with a 95 percent confidence interval from 0.69 to 1.13, across 13 retrospective studies of 1,743 patients.',
    whereItMisleads: 'A learner concludes that leukapheresis has been shown not to work, or alternatively that a point estimate below one means it does.',
    correctUnderstanding: 'The interval contains a substantial possible benefit and a possible harm, so it establishes neither. The studies are retrospective and confounded by indication in a direction their own data show: patients in clinical leukostasis were about twice as likely to receive the intervention, which biases the estimate against it. What can honestly be said is that nobody has demonstrated a short-term mortality benefit, which is why the authors argue against routine rather than against any use.',
    briefIn: ['lowering-the-count-a-number-that-can-be-moved'],
  },
  {
    id: 'inherited-urgency-presentation-and-its-stability-are-authored',
    headline: 'One presentation, one offer, and a patient who does not change.',
    simplification: 'The case supplies imaging taken four hours before, observations that do not move, a radiation oncology registrar who offers a slot at twenty-five minutes, and an acute oncology team that answers forty minutes after it is called. No venous, oedema, or treatment-response model runs underneath.',
    whereItMisleads: 'A learner reads the stability as a property of the condition, and expects a real patient with this picture to stay as he is while a biopsy is arranged.',
    correctUnderstanding: 'The stability is authored, and it is authored deliberately so that the pressure to act comes from a phone call rather than from the patient. A real patient may develop stridor, become confused, or lose blood pressure, in which case the lesson\u2019s own boundary review says that is the group for whom emergent intervention is indicated. Nothing here models a relationship between any choice and his trajectory, and the rehearsal ends the same way whatever is chosen.',
    briefIn: ['inherited-urgency-an-emergency-that-mostly-is-not-one'],
  },
  {
    id: 'inherited-urgency-controls-are-recording-and-escalation-only',
    headline: 'No treatment is started here, withheld here, or chosen here.',
    simplification: 'The learner records the grading findings, records that the tissue decides the treatment, secures the diagnostic pathway, records bounded qualified-team intent, and reviews the boundaries. The imaging and every observation are supplied.',
    whereItMisleads: 'The refusal of tonight\u2019s radiotherapy is read as this lesson recommending against radiotherapy for this patient, or as a claim that treatment before biopsy is always wrong.',
    correctUnderstanding: 'What was refused is the order, not the treatment: the cited review says diagnosis and biopsy should precede emergent therapeutic intervention in most cases, and the same review names the cases that are the exception. Radiotherapy, stenting, systemic therapy, steroid and anticoagulation decisions are qualified-team decisions this lesson deliberately does not make, and no drug, dose, route, product, fraction, or procedure is selected or displayed.',
    briefIn: ['inherited-urgency-an-emergency-that-mostly-is-not-one'],
  },
  {
    id: 'inherited-urgency-a-proportion-is-not-this-patient',
    headline: 'Five percent is a proportion of a population, not a probability about him.',
    simplification: 'The case reports that only about 5 percent of patients with this syndrome present with the life-threatening grade, and that death is very rarely caused by the syndrome itself, with one death in a reported series of 1,986 patients.',
    whereItMisleads: 'A learner converts the proportion into a reason to stop looking, or reads the rarity of death as a reason this patient can be left unobserved; or, in the other direction, treats the same proportion as a reason that urgency is never warranted.',
    correctUnderstanding: 'The proportion describes who arrives with the grading findings, not how likely this patient is to develop them, and the lesson refuses sending him home for exactly that reason. It is the argument for making the diagnosis first, and the named findings \u2014 significant cerebral oedema, significant laryngeal oedema, significant haemodynamic compromise \u2014 are what override that default when they appear. Both halves are needed; either alone produces a different wrong answer.',
    briefIn: ['inherited-urgency-an-emergency-that-mostly-is-not-one'],
  },
  {
    id: 'trial-rule-presentation-and-the-document-are-authored',
    headline: 'One report, one arriving document, and a patient who does not change during it.',
    simplification: 'The case supplies a two-day-old restaging report, a three-week history given as a fixed account, and criteria that arrive on screen at twenty minutes. No tumour-growth, response, or treatment-effect model runs underneath.',
    whereItMisleads: 'A learner reads the arrival of the document as something they caused, or expects the decisive information in a real version of this to turn up on its own within the hour.',
    correctUnderstanding: 'The document arrives whatever the learner does, and it arrives because the lesson is about what happens to a decision once the cited rule is actually read. In practice nobody brings it to you. The trajectory is supplied as an account rather than measured, and nothing here models a relationship between any choice and her disease.',
    briefIn: ['trial-rule-a-rule-written-for-a-database'],
  },
  {
    id: 'trial-rule-controls-are-recording-and-escalation-only',
    headline: 'No treatment is continued, stopped, or changed here.',
    simplification: 'The learner records the trajectory, records what the criteria govern, calls the treating team, records bounded qualified-team intent, and reviews the boundaries. The report and every observation are supplied.',
    whereItMisleads: 'The refusal to continue is read as this lesson recommending that her immunotherapy stop, or the refusal to stop is read as recommending that it continue.',
    correctUnderstanding: 'Both were refused, and refused as the same error: deciding without her trajectory and without the team that holds her treatment record. Nothing in this lesson selects, continues, or withdraws any treatment, and no drug, dose, route, cycle, interval, or line of therapy is displayed. What the lesson takes a position on is who decides and on what evidence, not on what the answer is.',
    briefIn: ['trial-rule-a-rule-written-for-a-database'],
  },
  {
    id: 'trial-rule-neither-rate-decides-this-patient',
    headline: 'A rate under 10 percent and a rate up to 29 percent both describe populations.',
    simplification: 'The case reports that pseudoprogression rates do not exceed 10 percent and that hyperprogression is reported at between 4 and 29 percent, including 13.8 percent against 5.1 percent in one lung-cancer comparison.',
    whereItMisleads: 'A learner treats the lower rate as a reason pseudoprogression can be discounted, or treats the higher one as evidence that this patient is hyperprogressing.',
    correctUnderstanding: 'Neither number is about her. The hyperprogression range is wide because the studies define it differently and study different tumours, and the pseudoprogression series are small; both are contested measurements rather than settled ones. What distinguishes the two possibilities in an individual is the clinical course over time and the judgement of the team that knows her treatment, which is precisely why this lesson makes the escalation rather than the classification.',
    briefIn: ['trial-rule-a-rule-written-for-a-database'],
  },
];
