/**
 * The pediatrics module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a pediatrics scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const PEDIATRICS_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'pediatric-respiratory-distress-presentation-support-and-trajectory-are-authored',
    headline: 'The child, illness history, whole-child findings, experienced support, and serial deterioration are authored.',
    simplification: 'Fixed reports and scenario-specific state snapshots stand in for caregiver history, appearance and mental-status assessment, examination, pulse oximetry, qualified support, continuous monitoring, and serial bedside reassessment.',
    whereItMisleads: 'Treating the fictional saturation, respiratory rate, recession, air movement, or response as a universal threshold, disease prediction, learner-acquired finding, or validated sick-child physiology.',
    correctUnderstanding: 'Real pediatric assessment integrates verified appearance, work and quality of breathing, speech or cry, air movement, circulation, mental status, signal quality, age, trajectory, caregiver context, and repeated qualified review.',
    briefIn: ['pediatric-respiratory-distress'],
  },
  {
    id: 'pediatric-respiratory-distress-controls-review-escalate-reassess-and-handoff-only',
    headline: 'The controls record whole-child review, experienced support, serial reassessment, rescue ownership, and handoff only.',
    simplification: 'Six accepted actions and 4 nonmutating teaching choices stand in for pediatric emergency team activation, qualified oxygenation and monitoring, repeated assessment, rescue preparation, cause review, caregiver communication, and handoff.',
    whereItMisleads: 'Equating button order with examination, diagnosis, oxygen or airway support, treatment, procedural skill, team performance, caregiver communication, or pediatric emergency competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric and airway-capable teams, current guidance, local resources, patient-specific support, and continuous reassessment.',
    briefIn: ['pediatric-respiratory-distress'],
  },
  {
    id: 'no-live-pediatric-diagnosis-device-dose-procedure-treatment-disposition-or-outcome',
    headline: 'The lab does not diagnose a cause, choose pediatric equipment or doses, perform a procedure, deliver treatment, determine disposition, or predict outcome.',
    simplification: 'No live examination, oximetry, capnography, blood gas, imaging, score, diagnosis, oxygen source or interface, flow, FiO2, target, medication, dose, fluid, suction, airway maneuver, bag-mask ventilation, intubation, tube sizing, procedure, treatment, disposition, prognosis, durable recovery, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values or actions into care, inferring a disease label from excluded snapshots, or using completion as evidence of clinical, device, dosing, airway, procedural, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric guidance, weight- and context-specific local systems, qualified teams, caregiver input, and repeated patient-specific reassessment.',
    briefIn: ['pediatric-respiratory-distress'],
  },
  {
    id: 'bronchiolitis-infant-presentation-working-diagnosis-support-and-trajectory-are-authored',
    headline: 'The child, illness day, clinical pattern, feeding and hydration reports, support, and response are authored.',
    simplification: 'Fixed reports and scenario-specific snapshots stand in for caregiver history, examination, pulse oximetry, clinical diagnosis, qualified support, feeding and hydration assessment, and serial bedside review.',
    whereItMisleads: 'Treating the fictional age, saturation, respiratory rate, intake, urine frequency, diffuse findings, or response as a universal threshold, learner-acquired finding, or validated bronchiolitis physiology.',
    correctUnderstanding: 'Real bronchiolitis care integrates verified history, examination, signal quality, age and comorbidity risk, work of breathing, feeding, hydration, apnea, circulation, caregiver context, trajectory, and repeated qualified review.',
    briefIn: ['bronchiolitis'],
  },
  {
    id: 'bronchiolitis-controls-prioritize-reassess-escalate-and-handoff-only',
    headline: 'The controls record whole-infant review, supportive-care ownership, reassessment, contextual restraint, and handoff only.',
    simplification: 'Six accepted actions and 5 nonmutating teaching choices stand in for experienced pediatric support, oxygenation, monitoring, feeding and hydration review, contextual treatment restraint, caregiver communication, and handoff.',
    whereItMisleads: 'Equating button order with diagnosis, oxygen delivery, feeding or fluid support, suction, treatment, team performance, caregiver communication, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric teams, current local guidance, patient-specific support, and repeated reassessment.',
    briefIn: ['bronchiolitis'],
  },
  {
    id: 'no-live-bronchiolitis-exam-test-device-fluid-route-medicine-treatment-or-disposition',
    headline: 'The lab does not examine or test a child, choose a device, route, medicine, or suction technique, deliver treatment, determine disposition, or predict outcome.',
    simplification: 'No live examination, viral attribution, oximetry, imaging, laboratory test, oxygen device, flow, FiO2, target, feeding route, fluid type, rate or volume, medicine, dose, nebulized therapy, suction, chest physiotherapy, ventilation, airway procedure, treatment, admission, discharge, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values or contextual restraint into care, treating an absent current feature as permanently excluded, or using completion as evidence of clinical, equipment, medication, suction, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current bronchiolitis guidance, local resources, qualified teams, caregiver input, and patient-specific reassessment; context-dependent exceptions remain real clinical decisions.',
    briefIn: ['bronchiolitis'],
  },
  {
    id: 'pediatric-status-asthmaticus-history-care-nonresponse-and-partial-response-are-authored',
    headline: 'The child, asthma history, first-hour care, severe nonresponse, second-line care, and partial response are authored.',
    simplification: 'Fixed reports and scenario-specific snapshots stand in for caregiver and child history, whole-child assessment, pulse oximetry, qualified treatment, escalation, monitoring, and serial bedside review.',
    whereItMisleads: 'Treating the fictional age, saturation, respiratory rate, peak flow, care record, treatment response, or timing as a universal threshold, learner-acquired finding, or validated pediatric-asthma physiology.',
    correctUnderstanding: 'Real severe-asthma care integrates verified history and treatment, speech, mentation, work and quality of breathing, air entry, oxygenation, circulation, treatment toxicity, dangerous alternatives, patient and caregiver context, local guidance, and repeated qualified review.',
    briefIn: ['pediatric-status-asthmaticus'],
  },
  {
    id: 'pediatric-status-asthmaticus-controls-reconcile-escalate-record-reassess-and-handoff-only',
    headline: 'The controls record trajectory review, severe-nonresponse recognition, qualified escalation and intent, reassessment, and handoff only.',
    simplification: 'Six accepted actions and 4 nonmutating teaching choices stand in for experienced pediatric critical-care ownership, standard and second-line qualified care, contextual restraint, toxicity surveillance, caregiver communication, and handoff.',
    whereItMisleads: 'Equating button order with examination, diagnosis, peak-flow or score performance, medication or oxygen delivery, inhaler or nebulizer technique, intravenous access, airway skill, treatment, team performance, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric and airway-capable teams, current local guidance, patient-specific treatment and monitoring, and continuous reassessment.',
    briefIn: ['pediatric-status-asthmaticus'],
  },
  {
    id: 'no-live-pediatric-asthma-exam-score-test-drug-dose-device-airway-treatment-or-disposition',
    headline: 'The lab does not examine, score, test, choose or deliver treatment, perform airway care, determine disposition, or predict outcome.',
    simplification: 'No live examination, PEF, spirometry, severity score, oximetry, gas, laboratory test, image, diagnosis, oxygen target or setting, inhaler, spacer, nebulizer, drug, dose, concentration, route, interval, intravenous access, fluid, infusion, device, ventilation, airway maneuver, intubation, sedation, paralysis, procedure, treatment, admission, discharge, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values or timing into care, treating supplied negatives as permanently excluded, or using completion as evidence of clinical, medication, device, airway, procedural, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric asthma guidance, local medication and airway systems, qualified teams, caregiver input, and patient-specific reassessment; poor response, toxicity, fatigue, or red flags change the pathway.',
    briefIn: ['pediatric-status-asthmaticus'],
  },
  {
    id: 'croup-presentation-severity-treatment-intent-and-serial-response-are-authored',
    headline: 'The child, croup pattern, severity, qualified care, early improvement, and later recurrence are authored.',
    simplification: 'Fixed reports and scenario-specific snapshots stand in for caregiver history, appearance and breathing assessment, pulse oximetry, qualified treatment, observation, and serial bedside review.',
    whereItMisleads: 'Treating the fictional age, saturation, respiratory rate, stridor, recession, treatment response, or recurrence timing as a universal threshold, learner-acquired finding, or validated croup physiology.',
    correctUnderstanding: 'Real croup care integrates verified history, behavior, voice, stridor at rest, work and quality of breathing, air entry, color, perfusion, signal quality, dangerous alternatives, caregiver context, trajectory, local guidance, and repeated qualified review.',
    briefIn: ['croup'],
  },
  {
    id: 'croup-controls-reconcile-prioritize-reassess-escalate-and-handoff-only',
    headline: 'The controls record calm whole-child review, qualified care ownership, timed reassessment, recurrence escalation, and handoff only.',
    simplification: 'Six accepted actions and 4 nonmutating teaching choices stand in for caregiver-centered care, experienced pediatric and airway support, standard qualified treatment, observation, alternative-diagnosis awareness, and handoff.',
    whereItMisleads: 'Equating button order with examination, diagnosis, medication delivery, nebulizer or oxygen operation, airway skill, treatment, team performance, caregiver communication, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric and airway-capable teams, current local guidance, patient-specific support, and continuous reassessment.',
    briefIn: ['croup'],
  },
  {
    id: 'no-live-croup-exam-test-drug-dose-route-device-airway-procedure-treatment-or-disposition',
    headline: 'The lab does not examine or test a child, choose or deliver a drug or device, perform airway care, determine disposition, or predict outcome.',
    simplification: 'No live mouth or throat examination, severity score, oximetry, imaging, swab, laboratory test, diagnosis, drug, dose, route, concentration, repeat interval, oxygen target, flow, interface, nebulizer, humidification, airway maneuver, ventilation, intubation, procedure, treatment, admission, discharge, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values or timing into care, treating supplied negatives as permanently excluded, or using completion as evidence of clinical, medication, device, airway, procedural, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current croup guidance, local medication and airway systems, qualified teams, caregiver input, and patient-specific reassessment; poor response or red flags change the pathway.',
    briefIn: ['croup'],
  },
  {
    id: 'pediatric-sepsis-infection-organ-dysfunction-care-and-response-are-authored',
    headline: 'The child, suspected infection, coagulation dysfunction, score report, qualified care, and serial response are authored.',
    simplification: 'Fixed reports and scenario-specific snapshots stand in for caregiver history, examination, monitoring, specimen and laboratory work, expert classification, antimicrobial care, source review, organ surveillance, and serial bedside reassessment.',
    whereItMisleads: 'Treating the fictional age, temperature, rates, pressure, refill, lactate, platelet count, INR, score, care timing, or response as a universal threshold, learner-acquired finding, screening rule, or validated pediatric-sepsis physiology.',
    correctUnderstanding: 'Real pediatric sepsis care integrates verified infection context, organ function, mentation, breathing, circulation, urine, bleeding, source, treatment fit, caregiver context, local pathways, and frequent qualified reassessment.',
    briefIn: ['pediatric-sepsis'],
  },
  {
    id: 'pediatric-sepsis-controls-reconcile-distinguish-activate-review-reassess-and-handoff-only',
    headline: 'The controls record supplied-pattern review, shock distinction, qualified-care activation, source and organ review, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric sepsis evaluation, antimicrobial and supportive care, source work, organ surveillance, caregiver communication, escalation, and handoff.',
    whereItMisleads: 'Equating button order with screening, examination, diagnosis, score calculation, specimen or test work, medication, fluid, oxygen or device operation, source control, treatment, team performance, caregiver communication, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric teams, current local guidance, patient-specific evaluation and treatment, source expertise, and continuous reassessment for shock and organ change.',
    briefIn: ['pediatric-sepsis'],
  },
  {
    id: 'no-live-pediatric-sepsis-exam-score-test-drug-fluid-device-procedure-treatment-or-disposition',
    headline: 'The lab does not screen, examine, score, test, choose or deliver treatment, perform source control, determine disposition, or predict outcome.',
    simplification: 'No live examination, monitor interpretation, Phoenix, PEWS or SIRS calculation, culture, specimen, lactate, gas, laboratory or imaging acquisition or interpretation, source or pathogen diagnosis, antimicrobial, drug, dose, concentration, route, interval, access, fluid, bolus, volume, rate, vasoactive, oxygen, device, flow, ventilation, airway maneuver, source-control procedure, treatment, admission, discharge, prognosis, recovery, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values or timing into care, using Phoenix as an early screen, treating preserved pressure or falling lactate as low risk, or using completion as evidence of clinical, prescribing, procedural, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric sepsis guidance, local recognition and antimicrobial systems, qualified source and organ-support teams, caregiver input, and repeated patient-specific reassessment.',
    briefIn: ['pediatric-sepsis'],
  },
  {
    id: 'pediatric-septic-shock-infection-perfusion-care-and-response-are-authored',
    headline: 'The child, suspected source, shock pattern, congestion warnings, qualified care, and serial response are authored.',
    simplification: 'Fixed reports and scenario-specific snapshots stand in for caregiver history, examination, monitoring, imaging, laboratory work, expert Phoenix classification, antimicrobial care, fluid reassessment, vasoactive support, source-control planning, and serial bedside reassessment.',
    whereItMisleads: 'Treating the fictional age, pressure, refill, urine, lactate, GCS, fluid history, congestion signs, score, care timing, or response as a universal threshold, learner-acquired finding, causal treatment effect, or validated pediatric septic-shock physiology.',
    correctUnderstanding: 'Real care integrates verified infection and source context, mentation, breathing, circulation, urine, congestion, organ function, patient-specific treatment response, caregiver context, local systems, and continuous qualified reassessment.',
    briefIn: ['pediatric-septic-shock'],
  },
  {
    id: 'pediatric-septic-shock-controls-reconcile-recognize-activate-escalate-reassess-and-handoff-only',
    headline: 'The controls record trajectory review, shock recognition, parallel qualified rescue and source ownership, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric septic-shock recognition, critical-care and vasoactive coordination, source work, organ and congestion surveillance, caregiver communication, and handoff.',
    whereItMisleads: 'Equating button order with examination, diagnosis, Phoenix calculation, imaging or test interpretation, fluid or vasoactive delivery, source control, treatment, team performance, caregiver communication, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric, critical-care, nursing, pharmacy, laboratory, imaging, and source teams, current local guidance, patient-specific treatment, and continuous reassessment.',
    briefIn: ['pediatric-septic-shock'],
  },
  {
    id: 'no-live-pediatric-septic-shock-exam-score-test-drug-fluid-device-procedure-treatment-or-disposition',
    headline: 'The lab does not examine, score, test, choose or deliver resuscitation, perform source control, determine disposition, or predict outcome.',
    simplification: 'No live examination, monitor interpretation, Phoenix, PEWS or SIRS calculation, culture, specimen, lactate, gas, laboratory, ultrasound, point-of-care ultrasound or imaging acquisition or interpretation, source or pathogen diagnosis, antimicrobial, fluid, bolus, volume, rate, access, vasoactive, agent, dose, infusion, oxygen, device, ventilation, airway maneuver, source-control procedure, treatment, admission, discharge, prognosis, recovery, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values or timing into care, assuming a universal fluid total or MAP target, preferring one first-line vasoactive from this lab, attributing congestion or partial improvement to one intervention, or using completion as evidence of clinical or procedural competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric sepsis guidance, local antimicrobial and resuscitation systems, qualified source and organ-support teams, caregiver input, and repeated patient-specific reassessment with fluid stopped or changed when shock resolves or overload signs appear.',
    briefIn: ['pediatric-septic-shock'],
  },
  {
    id: 'pediatric-dehydration-losses-perfusion-care-and-response-are-authored',
    headline: 'The child, losses, intake, weight history, hydration signs, qualified care, and serial response are authored.',
    simplification: 'Fixed reports and scenario-specific snapshots stand in for caregiver history, examination, weighing, monitoring, oral tolerance, intake and output, laboratory review, rehydration support, and serial bedside reassessment.',
    whereItMisleads: 'Treating the fictional age, weight change, heart rate, urine history, hydration signs, care timing, or response as a universal percentage, severity threshold, learner-acquired finding, causal treatment effect, or validated pediatric fluid physiology.',
    correctUnderstanding: 'Real care integrates verified losses and intake, serial weights when reliable, consciousness, tears, mucosa, eyes, turgor, circulation, urine, oral tolerance, red flags, caregiver context, local guidance, and repeated qualified reassessment.',
    briefIn: ['pediatric-dehydration-with-hypovolemia'],
  },
  {
    id: 'pediatric-dehydration-controls-reconcile-recognize-coordinate-review-reassess-and-handoff-only',
    headline: 'The controls record trajectory review, compensated-dehydration recognition, parallel qualified rehydration and safety ownership, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric and nursing assessment, oral support, tolerance and loss monitoring, conditional tests and escalation, caregiver communication, and handoff.',
    whereItMisleads: 'Equating button order with examination, weighing, diagnosis, percentage or deficit calculation, laboratory work, fluid or feeding delivery, access or device operation, treatment, team performance, caregiver communication, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric teams, current local guidance, patient-specific rehydration and monitoring, and escalation when shock, deterioration, intolerance, or an alternative serious cause is present.',
    briefIn: ['pediatric-dehydration-with-hypovolemia'],
  },
  {
    id: 'no-live-pediatric-dehydration-exam-calculation-test-fluid-device-treatment-or-disposition',
    headline: 'The lab does not examine, weigh, calculate, test, choose or deliver rehydration, determine disposition, or predict outcome.',
    simplification: 'No live examination, weight measurement, dehydration score or percentage, deficit or maintenance calculation, glucose, electrolyte, renal, acid-base, urine, stool, culture or imaging acquisition or interpretation, diagnosis, oral or intravenous solution, route, bolus, volume, rate, electrolyte, glucose, access, device, drug, feeding plan, procedure, treatment, admission, discharge, prognosis, recurrence, recovery, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values into care, equating weight change with intravascular deficit, treating fixed negatives as permanent exclusions, assuming one universal fluid recipe, or using completion as evidence of clinical, prescribing, device, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current diarrhoea and pediatric fluid guidance, local rehydration systems, qualified teams, caregiver input, and repeated patient-specific reassessment; current no-shock findings do not remove the need to monitor for deterioration.',
    briefIn: ['pediatric-dehydration-with-hypovolemia'],
  },
  {
    id: 'pediatric-dka-presentation-care-laboratories-and-response-are-authored',
    headline: 'The child, biochemical pattern, qualified care, surveillance, and serial response are authored.',
    simplification: 'Fixed reports and scenario-specific snapshots stand in for caregiver history, examination, monitoring, glucose, ketone, acid-base, electrolyte and renal testing, fluid balance, treatment, and serial bedside reassessment.',
    whereItMisleads: 'Treating the fictional age, weight, symptoms, vital signs, laboratory values, care timing, or response as universal kinetics, learner-acquired findings, causal treatment effects, or validated pediatric DKA physiology.',
    correctUnderstanding: 'Real care integrates verified history, repeated neurological and circulatory assessment, glucose, ketones, gases, electrolytes, renal function, osmolality and fluid balance when indicated, precipitating causes, treatment, and repeated qualified reassessment.',
    briefIn: ['pediatric-diabetic-ketoacidosis'],
  },
  {
    id: 'pediatric-dka-controls-reconcile-recognize-coordinate-review-reassess-and-handoff-only',
    headline: 'The controls record pattern review, DKA recognition, parallel qualified care and safety ownership, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, diabetes, nursing, pharmacy, and laboratory assessment, treatment, surveillance, caregiver communication, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, diagnosis, severity or biochemical calculation, testing, fluid or insulin prescribing, electrolyte management, access or device operation, treatment, team performance, caregiver communication, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric DKA teams, current local guidance, patient-specific treatment, frequent neurological and biochemical monitoring, and immediate escalation when warning signs or deterioration appear.',
    briefIn: ['pediatric-diabetic-ketoacidosis'],
  },
  {
    id: 'no-live-pediatric-dka-exam-calculation-test-fluid-insulin-electrolyte-device-or-disposition',
    headline: 'The lab does not examine, calculate, test, prescribe or deliver DKA care, determine disposition, or predict outcome.',
    simplification: 'No live neurological or physical examination, severity, dehydration, sodium, osmolality, anion-gap, deficit, maintenance, dose or rate calculation, specimen or test acquisition or interpretation, diagnosis, fluid, insulin, dextrose, potassium, phosphate, bicarbonate, other drug, access, pump, device, procedure, treatment, admission, discharge, prognosis, recurrence, recovery, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values into care, using glucose or one warning sign alone, treating fixed negatives as permanent exclusions, assuming a universal treatment recipe, blaming one fluid strategy for cerebral injury, or using completion as evidence of clinical or prescribing competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric DKA guidance, local protocols, qualified teams, caregiver input, and repeated patient-specific neurological, circulatory, biochemical, electrolyte, renal, rhythm, input and output reassessment.',
    briefIn: ['pediatric-diabetic-ketoacidosis'],
  },
  {
    id: 'pediatric-hypoglycemic-seizure-presentation-care-glucose-and-response-are-authored',
    headline: 'The child, stopped convulsion, glucose results, qualified care, and serial response are authored.',
    simplification: 'Fixed reports and scenario-specific snapshots stand in for caregiver history, examination, monitoring, glucose acquisition and confirmation, airway-safety assessment, rescue, cause evaluation, and serial bedside reassessment.',
    whereItMisleads: 'Treating the fictional age, glucose values, vital signs, care timing, or response as a universal threshold, learner-acquired finding, causal treatment effect, predicted glucose kinetics, or validated pediatric physiology.',
    correctUnderstanding: 'Real care integrates verified whole-child and neurological assessment, airway and swallowing safety, confirmed glucose when feasible without delaying urgent care, repeated glucose and clinical reassessment, exposure and intake history, cause-directed testing, and qualified treatment.',
    briefIn: ['pediatric-hypoglycemic-seizure'],
  },
  {
    id: 'pediatric-hypoglycemic-seizure-controls-reconcile-recognize-coordinate-review-reassess-and-handoff-only',
    headline: 'The controls record whole-child review, recognition, parallel qualified rescue and cause ownership, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, nursing, pharmacy, laboratory, airway-capable, endocrine, safeguarding, and caregiver assessment, rescue, monitoring, evaluation, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, glucose measurement or interpretation, diagnosis, prescribing, rescue delivery, airway skill, cause evaluation, team performance, caregiver communication, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained pediatric teams, current local guidance, immediate patient-specific rescue, airway-safety and neurological monitoring, repeated glucose assessment, and investigation of unexplained or recurrent hypoglycemia.',
    briefIn: ['pediatric-hypoglycemic-seizure'],
  },
  {
    id: 'no-live-pediatric-hypoglycemic-seizure-exam-test-glucose-drug-airway-treatment-or-disposition',
    headline: 'The lab does not examine, test, choose or deliver rescue, manage an airway or seizure, determine disposition, or predict outcome.',
    simplification: 'No live examination, palpation, glucose or other specimen acquisition or interpretation, diagnosis, oral or parenteral glucose, dextrose, glucagon, carbohydrate, fluid, anticonvulsant, other drug, concentration, route, dose, rate, access, infusion, feeding plan, oxygen, device, airway maneuver, procedure, treatment, admission, discharge, prognosis, recurrence, recovery, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values into care, applying one glucose threshold without whole-child context, treating negative snapshots as permanent exclusions, assuming a universal rescue recipe, attributing improvement to one intervention, or using completion as evidence of clinical competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric hypoglycemia and seizure guidance, local rescue systems, qualified teams, caregiver and safeguarding context, repeated neurological and glucose reassessment, and cause-directed evaluation.',
    briefIn: ['pediatric-hypoglycemic-seizure'],
  },
  {
    id: 'pediatric-febrile-seizure-presentation-care-and-response-are-authored',
    headline: 'The child, fever, stopped seizure, qualified care, negative snapshots, and serial recovery are authored.',
    simplification: 'Fixed reports stand in for caregiver history, seizure characterization, examination, temperature and physiological monitoring, fever-source and serious-illness assessment, recovery observation, recurrence surveillance, caregiver education, and escalation.',
    whereItMisleads: 'Treating the fictional event, values, negative findings, recovery timing, or temperature change as learner-acquired evidence, modeled physiology, causal treatment effect, confirmed simple classification, or serious-infection exclusion.',
    correctUnderstanding: 'Real care integrates verified event history, whole-child and neurological examination, fever source, immunization and antimicrobial context, serious-illness red flags, locally indicated tests and treatment, serial return to baseline, recurrence, and caregiver needs.',
    briefIn: ['pediatric-febrile-seizure'],
  },
  {
    id: 'pediatric-febrile-seizure-controls-reconcile-recognize-coordinate-review-reassess-and-handoff-only',
    headline: 'The controls record event review, provisional pattern recognition, parallel qualified care and safety review, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, nursing, infection, neurological, airway-capable, safeguarding, and caregiver assessment, support, education, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, seizure timing, diagnosis, testing, prescribing, treatment, first-aid skill, team performance, caregiver communication, disposition, or pediatric competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, qualified teams, current fever and seizure guidance, patient-specific serious-illness assessment, locally indicated care, observation of recovery, recurrence planning, and safety-netting.',
    briefIn: ['pediatric-febrile-seizure'],
  },
  {
    id: 'no-live-pediatric-febrile-seizure-exam-test-drug-airway-treatment-or-disposition',
    headline: 'The lab does not examine, test, treat fever or seizure, assess first aid, determine disposition, or predict outcome.',
    simplification: 'No live examination, temperature measurement, seizure timing, glucose, urine, blood, culture, lumbar puncture, EEG, ECG or imaging acquisition or interpretation, diagnosis, antipyretic, antimicrobial, antiseizure or rescue medicine, fluid, oxygen, dose, route, access, device, airway maneuver, procedure, treatment, caregiver communication, admission, discharge, prognosis, recurrence, recovery, or outcome is modeled.',
    whereItMisleads: 'Calling the event confirmed simple or benign, treating fixed negatives as exclusions, using temperature response to judge serious illness, assuming prophylaxis prevents recurrence, copying values into care, or using completion as evidence of clinical or communication competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric fever and seizure guidance, qualified fever-source and dangerous-cause assessment, patient-specific testing and treatment when indicated, repeated neurological reassessment, caregiver education, and escalation for complex features or serious illness.',
    briefIn: ['pediatric-febrile-seizure'],
  },
  {
    id: 'pediatric-status-epilepticus-presentation-care-and-response-are-authored',
    headline: 'The seizure clock, first-line-care record, whole-child findings, qualified escalation, and later response are authored.',
    simplification: 'Fixed reports stand in for witness history, seizure timing, examination, monitoring, glucose acquisition, verification of prior care, active treatment, airway support, cause evaluation, and serial neurological reassessment.',
    whereItMisleads: 'Treating the fictional values, care times, prior-dose adequacy, negative snapshots, or visible-convulsion cessation as learner-acquired evidence, modeled physiology, causal treatment effect, electrographic control, or predicted recovery.',
    correctUnderstanding: 'Real pediatric convulsive status requires verified seizure and treatment timing, immediate concurrent resuscitation and seizure-control care, patient-specific monitoring, repeated airway and neurological assessment, dangerous-cause evaluation, and prompt escalation through qualified teams.',
    briefIn: ['pediatric-status-epilepticus'],
  },
  {
    id: 'pediatric-status-epilepticus-controls-reconcile-recognize-escalate-review-reassess-and-handoff-only',
    headline: 'The controls record trajectory review, recognition, parallel qualified escalation and safety work, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, neurology, nursing, pharmacy, airway-capable, critical-care, laboratory, imaging, safeguarding, and caregiver assessment, treatment, surveillance, escalation, and handoff.',
    whereItMisleads: 'Equating button order with seizure timing, examination, medication verification, prescribing, drug delivery, airway skill, testing, diagnosis, team performance, caregiver communication, or pediatric status competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained teams, verified prior therapy, current local pathways, immediate patient-specific seizure control, continuous physiologic support, repeated reassessment, cause-directed care, and refractory rescue capability.',
    briefIn: ['pediatric-status-epilepticus'],
  },
  {
    id: 'no-live-pediatric-status-epilepticus-exam-test-drug-airway-treatment-or-disposition',
    headline: 'The lab does not examine, test, prescribe or deliver seizure or airway care, determine disposition, or predict outcome.',
    simplification: 'No live seizure timing, examination, monitor or glucose acquisition, prior-dose verification, first-line or second-line product, concentration, route, dose, access, infusion, oxygen, suction, airway device or maneuver, ventilation, laboratory test, EEG, imaging, lumbar puncture, procedure, treatment, admission, discharge, prognosis, recurrence, recovery, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values into care, treating supplied prior therapy as a universal recipe, delaying second-line escalation for cause review, reading absent visible movement as seizure control, treating fixed negatives as exclusions, or using completion as clinical competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric seizure guidance, local medication and airway systems, qualified teams, continuous reassessment, EEG when indicated, cause-directed evaluation and treatment, and appropriate critical-care escalation.',
    briefIn: ['pediatric-status-epilepticus'],
  },
  {
    id: 'pediatric-anaphylaxis-presentation-care-and-response-are-authored',
    headline: 'The reported exposure, supplied first-line care, whole-child findings, escalation, and later response are authored.',
    simplification: 'Fixed reports stand in for witness and caregiver history, exposure timing, examination, monitoring, first-line-care verification, active treatment, airway and circulation support, trigger and alternative-cause evaluation, and serial reassessment.',
    whereItMisleads: 'Treating the fictional values, care times, prior-dose appropriateness, negative snapshots, or partial improvement as learner-acquired evidence, modeled physiology, diagnostic or trigger proof, causal treatment effect, durable resolution, or predicted recovery.',
    correctUnderstanding: 'Real pediatric anaphylaxis requires immediate clinical assessment and treatment, verified exposure and care history, continuous airway-breathing-circulation support, frequent reassessment, qualified repeat and refractory care when needed, and post-event allergy and caregiver follow-through.',
    briefIn: ['pediatric-anaphylaxis'],
  },
  {
    id: 'pediatric-anaphylaxis-controls-reconcile-recognize-escalate-review-reassess-and-handoff-only',
    headline: 'The controls record trajectory review, recognition, qualified escalation, safety review, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, emergency, nursing, pharmacy, airway-capable, critical-care, allergy, safeguarding, and caregiver assessment, treatment, monitoring, escalation, observation, planning, and handoff.',
    whereItMisleads: 'Equating button order with examination, diagnostic criteria, trigger confirmation, prescribing, injection, oxygen or fluid delivery, airway skill, testing, team performance, caregiver communication, observation, referral, disposition, or pediatric anaphylaxis competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained teams, current local pathways, immediate patient-specific first-line and supportive care, repeated assessment, escalation for persistent compromise, and risk-based observation and allergy follow-up.',
    briefIn: ['pediatric-anaphylaxis'],
  },
  {
    id: 'no-live-pediatric-anaphylaxis-exam-dose-device-treatment-observation-or-disposition',
    headline: 'The lab does not examine, dose, inject, operate a device, treat, choose observation or disposition, or predict outcome.',
    simplification: 'No live examination, monitoring, diagnosis, medicine, concentration, route, dose, weight calculation, injector or other device, preparation, injection, access, oxygen interface or flow, fluid type, volume or rate, bronchodilator, antihistamine, corticosteroid, infusion, vasopressor, airway maneuver or device, ventilation, CPR, tryptase, allergy test, procedure, observation duration, prescription, training, referral completion, admission, discharge, prognosis, recurrence, recovery, or outcome is modeled.',
    whereItMisleads: 'Copying fictional care into another child or region, delaying repeat escalation for additional review, using asthma medicine instead of urgent anaphylaxis care, treating absent skin findings as exclusion, reading improvement as resolution, or using completion as clinical or caregiver-communication competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric anaphylaxis and local resuscitation guidance, qualified medication and airway systems, continuous reassessment, escalation when symptoms persist, and risk-based observation, allergy referral, prescriptions, education, and safety planning.',
    briefIn: ['pediatric-anaphylaxis'],
  },
  {
    id: 'pediatric-svt-rhythm-perfusion-care-and-response-are-authored',
    headline: 'The rhythm, perfusion findings, qualified care, and serial response are authored.',
    simplification: 'Fixed reports stand in for symptom history, examination, pulse and perfusion assessment, monitoring, ECG acquisition and interpretation, active rhythm care, cause evaluation, and serial reassessment.',
    whereItMisleads: 'Treating the fictional rate, QRS duration, vital signs, negative snapshots, care timing, or response as learner-acquired evidence, a universal diagnostic cutoff, modeled pediatric physiology, causal treatment effect, durable rhythm control, or predicted recovery.',
    correctUnderstanding: 'Real pediatric tachyarrhythmia care integrates verified rhythm and symptom history, whole-child airway-breathing-circulation assessment, ECG evidence, repeated perfusion assessment, age and clinical context, prompt qualified care, and cause and recurrence evaluation.',
    briefIn: ['pediatric-supraventricular-tachycardia'],
  },
  {
    id: 'pediatric-svt-controls-reconcile-recognize-escalate-review-reassess-and-handoff-only',
    headline: 'The controls record trajectory review, recognition, qualified escalation, safety review, reassessment, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, emergency, cardiology, nursing, pharmacy, airway-capable, resuscitation, and caregiver assessment, monitoring, treatment, surveillance, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, pulse assessment, ECG interpretation, rhythm diagnosis, vagal-maneuver skill, prescribing, drug or electrical treatment, device operation, team performance, caregiver communication, disposition, or pediatric SVT competence.',
    correctUnderstanding: 'Actual care requires the child and caregiver, trained teams, current pediatric resuscitation pathways, verified patient-specific rhythm and perfusion assessment, immediate escalation for compromise, qualified treatment, continuous reassessment, and cardiology follow-through.',
    briefIn: ['pediatric-supraventricular-tachycardia'],
  },
  {
    id: 'no-live-pediatric-svt-exam-ecg-drug-device-cardioversion-treatment-or-disposition',
    headline: 'The lab does not examine, acquire or interpret an ECG, perform a maneuver, treat, operate a device, determine disposition, or predict outcome.',
    simplification: 'No live examination, palpation, pulse assessment, monitoring or ECG acquisition or interpretation, diagnosis, vagal maneuver, access, oxygen, drug, concentration, dose, route, flush, sedation, pad, synchronization, energy, cardioversion, refractory therapy, laboratory test, imaging, echocardiography, procedure, treatment, observation choice, admission, discharge, prognosis, recurrence, recovery, or outcome is modeled.',
    whereItMisleads: 'Using rate alone to diagnose SVT, treating measurable pressure as proof of adequate perfusion, copying fictional values into care, treating fixed negatives as exclusions, assuming one universal treatment pathway, attributing the later rhythm to a modality, or using completion as clinical competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric rhythm guidance, local resuscitation systems, qualified teams, whole-child perfusion rather than one number, continuous rhythm and circulation reassessment, and patient-specific cause, recurrence, and cardiology planning.',
    briefIn: ['pediatric-supraventricular-tachycardia'],
  },
  {
    id: 'pediatric-bradycardic-arrest-support-pulse-loss-and-rhythm-are-authored',
    headline: 'The breathing support, bradycardia, pulses, perfusion, PEA transition, and ongoing resuscitation are authored.',
    simplification: 'Fixed qualified reports stand in for airway and breathing support, examination, monitoring, pulse and perfusion assessment, CPR, rhythm review, cause evaluation, and serial arrest reassessment.',
    whereItMisleads: 'Treating the fictional values, effective-support record, negative snapshots, pulse findings, elapsed pulse loss, or PEA as learner-acquired evidence, modeled pediatric physiology, treatment effect, predicted arrest, or universal trajectory.',
    correctUnderstanding: 'Real care requires verified effective oxygenation and ventilation, repeated whole-child and pulse assessment, immediate qualified resuscitation for persistent compromised bradycardia, continuous arrest care, open-cause evaluation, and patient-specific reassessment.',
    briefIn: ['pediatric-bradycardic-arrest'],
  },
  {
    id: 'pediatric-bradycardic-arrest-controls-reconcile-recognize-escalate-review-and-handoff-only',
    headline: 'The controls record trajectory review, recognition, qualified escalation, pulse-loss review, and active-risk handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, nursing, airway-capable, resuscitation, pharmacy, critical-care, cardiology, and caregiver assessment, treatment, monitoring, cause review, and handoff.',
    whereItMisleads: 'Equating button order with airway or ventilation assessment, pulse checking, monitoring or rhythm interpretation, CPR, prescribing, drug delivery, device operation, cause treatment, team performance, caregiver communication, or pediatric resuscitation competence.',
    correctUnderstanding: 'Actual care requires the child, trained teams, current pediatric resuscitation pathways, verified support and pulse assessment, immediate patient-specific resuscitation, continuous reassessment, and parallel cause-directed care.',
    briefIn: ['pediatric-bradycardic-arrest'],
  },
  {
    id: 'no-live-pediatric-bradycardic-arrest-exam-cpr-drug-device-treatment-or-outcome',
    headline: 'The lab does not assess support or a pulse, perform CPR, choose a drug, operate a device, treat a cause, terminate care, or report outcome.',
    simplification: 'No live examination, palpation, pulse check, airway or ventilation assessment, oxygen delivery, monitor, ECG or capnography acquisition or interpretation, CPR mechanics, compression rate or depth, access, drug, concentration, dose, route, flush, pacing, shock, energy, device operation, procedure, cause-specific treatment, post-arrest care, termination, disposition, prognosis, ROSC, recovery, or outcome is modeled.',
    whereItMisleads: 'Using HR below 60/min without persistent compromise and effective-ventilation context, reading SpO₂ alone as effective ventilation, copying fictional values into care, delaying resuscitation until pulse loss, shocking PEA, treating negative snapshots as exclusions, or using completion as clinical competence.',
    correctUnderstanding: 'Use verified patient data, current pediatric resuscitation guidance, local systems, qualified teams, multiple concordant support and perfusion findings, immediate care when the full threshold is met, and continuous pulse, rhythm, support, and cause reassessment.',
    briefIn: ['pediatric-bradycardic-arrest'],
  },
  {
    id: 'pediatric-foreign-body-airway-obstruction-event-transitions-and-care-are-authored',
    headline: 'The eating event, cough branches, obstruction transitions, qualified care, and unresolved outcome are authored.',
    simplification: 'Fixed reports stand in for event history, cough and airflow assessment, whole-child examination, monitoring, object review, responsive obstruction care, unresponsive CPR and airway checks, and serial reassessment.',
    whereItMisleads: 'Treating the fictional values, reported grape, negative snapshots, elapsed deterioration, unreported pulse status, or care ownership as learner-acquired evidence, confirmed object or location, modeled pediatric physiology, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires direct rapid assessment, effective-versus-ineffective cough recognition, immediate qualified escalation, age- and region-appropriate current resuscitation pathways, repeated responsiveness and circulation checks, and patient-specific reassessment.',
    briefIn: ['pediatric-foreign-body-airway-obstruction'],
  },
  {
    id: 'pediatric-foreign-body-airway-obstruction-controls-reconcile-preserve-recognize-activate-and-handoff-only',
    headline: 'The controls record reconciliation, effective-cough preservation, transition recognition, qualified pathway activation, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, emergency, airway-capable, resuscitation, nursing, and caregiver assessment, treatment, monitoring, escalation, and handoff.',
    whereItMisleads: 'Equating button order with cough assessment, examination, pulse checking, maneuver or CPR skill, object visualization or removal, airway management, device operation, team performance, caregiver communication, disposition, or pediatric FBAO competence.',
    correctUnderstanding: 'Actual care requires the child, trained responders, current region-specific pediatric resuscitation guidance, direct findings, prompt qualified action when cough becomes ineffective, and immediate transition when responsiveness is lost.',
    briefIn: ['pediatric-foreign-body-airway-obstruction'],
  },
  {
    id: 'no-live-pediatric-foreign-body-airway-obstruction-exam-maneuver-cpr-device-treatment-or-outcome',
    headline: 'The lab does not assess the child, perform an obstruction maneuver or CPR, remove an object, operate a device, treat, or report outcome.',
    simplification: 'No live examination, cough or pulse assessment, monitoring, object visualization, blind or visible-object sweep, back blow, chest or abdominal thrust, suction, oxygen, ventilation, compression, CPR sequence, airway device, laryngoscopy, bronchoscopy, drug, procedure, treatment, disposition, prognosis, recovery, ROSC, or outcome is modeled.',
    whereItMisleads: 'Applying thrusts during an effective cough, delaying care after cough becomes ineffective, continuing responsive-child maneuvers after unresponsiveness, using a blind sweep, assuming one regional CPR opening sequence is universal, treating negative snapshots as exclusions, or using completion as clinical competence.',
    correctUnderstanding: 'Use direct patient findings, current local pediatric resuscitation guidance, qualified responders, effective-cough surveillance without harmful early maneuvers, rapid severe-obstruction care, and immediate unresponsive-child CPR and airway-check care.',
    briefIn: ['pediatric-foreign-body-airway-obstruction'],
  },
  {
    id: 'pediatric-injury-safeguarding-history-injuries-safety-and-later-state-are-authored',
    headline: 'The history, development, injuries, medical snapshots, safety state, qualified ownership, and later report are authored.',
    simplification: 'Fixed reports stand in for child-centered history, whole-child and skin examination, injury documentation, medical assessment, immediate-safety review, information gathering, safeguarding consultation, and serial reassessment.',
    whereItMisleads: 'Treating the fictional history, injury locations or sizes, negative snapshots, unsuitable-explanation statement, later stability, or named ownership as learner-acquired evidence, confirmed abuse, perpetrator attribution, a credibility ruling, occult-harm exclusion, or predicted outcome.',
    correctUnderstanding: 'Real care requires direct child-centered assessment, objective documentation, medical and injury evaluation, immediate-safety work, qualified safeguarding expertise, locally governed information sharing, and patient-specific reassessment without premature diagnosis.',
    briefIn: ['pediatric-injury-safeguarding-escalation'],
  },
  {
    id: 'pediatric-injury-safeguarding-controls-reconcile-recognize-activate-review-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, concern recognition, qualified ownership, bounded review, later safety review, and handoff only.',
    simplification: 'Six accepted actions stand in for experienced pediatric, emergency, nursing, child-protection, safeguarding, social-care, laboratory, imaging, legal, and caregiver assessment, support, information gathering, escalation, and handoff.',
    whereItMisleads: 'Equating button order with examination, interviewing, documentation quality, bruise recognition or dating, screening-rule use, diagnosis, investigation, referral, reporting, legal compliance, caregiver communication, team performance, disposition, or safeguarding competence.',
    correctUnderstanding: 'Actual care requires the child, trained teams, current local safeguarding procedures and law, verified patient-specific information, qualified medical and safety assessment, careful communication, appropriate information sharing, and continuous protected ownership.',
    briefIn: ['pediatric-injury-safeguarding-escalation'],
  },
  {
    id: 'no-live-pediatric-injury-safeguarding-exam-interview-diagnosis-reporting-procedure-disposition-or-outcome',
    headline: 'The lab does not examine or interview, diagnose abuse, submit a report, perform a procedure, decide disposition, or report outcome.',
    simplification: 'No live examination, interview, sensitive free text, photography, body map, bruise identification or dating, TEN-4-FACESp calculation, test or imaging acquisition or interpretation, diagnosis, perpetrator identification, credibility judgment, confrontation, caregiver separation, referral or report submission, jurisdiction or law selection, custody action, procedure, treatment, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Diagnosing abuse from a screening pattern, treating stable physiology as reassurance, inferring bruise age from color, treating fixed negatives as exclusions, confronting a caregiver, assuming one universal mandatory-reporting rule, or using completion as clinical or safeguarding competence.',
    correctUnderstanding: 'Use direct patient findings, objective records, qualified multidisciplinary safeguarding and medical teams, applicable local law and procedures, child-centered communication, immediate-safety planning, and locally governed reporting and information sharing.',
    briefIn: ['pediatric-injury-safeguarding-escalation'],
  },
];
