/**
 * The renal-electrolyte module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a renal-electrolyte scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const RENAL_ELECTROLYTE_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'renal-hypermagnesemia-antagonism',
    headline: 'Calcium can counter magnesium toxicity without removing magnesium.',
    simplification: 'Qualified calcium care produces a temporary authored circulation response. Respiratory support changes supported respiratory rate and saturation independently; neither intervention lowers the modeled magnesium.',
    whereItMisleads: 'An improved pulse, pressure, or supported breathing pattern is interpreted as magnesium clearance, spontaneous respiratory recovery, or permission to stop support.',
    correctUnderstanding: 'Separate respiratory and circulatory support from magnesium removal. Reassess the whole patient and magnesium with qualified teams; a temporary symptom response does not establish correction or replace renal-aware elimination care.',
    briefIn: ['hypermagnesemia-antagonism-and-removal'],
  },
  {
    id: 'renal-hypermagnesemia-authored-contrasts',
    headline: 'Response and recurrent toxicity use authored contrasts, not a calcium redosing clock.',
    simplification: 'The case uses a finite 30-minute calcium benefit and a selected 60-minute removal response. Clinical toxicity can recur without a magnesium rise. Supported breathing remains supported after partial improvement.',
    whereItMisleads: 'These clocks become expected drug durations, required waits, automatic calcium repeats, dialysis prescriptions, biochemical rebound, or guaranteed recovery.',
    correctUnderstanding: 'Clinical support and removal proceed independently of administrative or repeat-test gates. Repeat calcium requires qualified clinical review. No exact patient trajectory, dialysis kinetics, obligatory rebound, or validated outcome follows from this authored model.',
    briefIn: ['hypermagnesemia-antagonism-and-removal'],
  },
  {
    id: 'renal-hypermagnesemia-continuing-care',
    headline: 'A lower magnesium level does not close renal or respiratory care.',
    simplification: 'Stopping further intake does not instantly clear absorbed magnesium. The later partial response preserves residual weakness and respiratory-support needs; historical kidney and other laboratory values are not refreshed.',
    whereItMisleads: 'Constipation proves bowel obstruction, all renal impairment receives forced diuresis, or handoff requires normal magnesium and unnecessary late calcium after an observed removal response.',
    correctUnderstanding: 'Individualize exposure, bowel, urine-output, volume, elimination, and serial clinical review. Current full findings can support transfer with removal still pending. Handoff closes rehearsal, not ventilation, surveillance, or unresolved risk.',
    briefIn: ['hypermagnesemia-antagonism-and-removal'],
  },
  {
    id: 'renal-estimate-precision-bounds',
    headline: 'No measured filtration rate exists anywhere in this lesson.',
    simplification: 'Two estimates are supplied, 68 and 38 mL/min/1.73 m\u00b2, and every observation the engine can produce carries a null measured filtration rate. The disagreement is never resolved, and no equation, marker, or filtration model is implemented.',
    whereItMisleads: 'One of the two estimates is read as the true value, or the second marker is read as the correct one because it was requested later.',
    correctUnderstanding: 'The accuracy quoted here is a population statistic \u2014 85% or more within 30% of measured also means up to one value in seven outside even that band \u2014 and it comes from development and validation cohorts rather than from this patient. A learner waiting for the real number is meant to notice that nobody supplies one.',
    briefIn: ['estimated-filtration-a-number-she-was-never-measured-by'],
  },
  {
    id: 'renal-estimate-authored-contrasts',
    headline: 'The second estimate is authored, and the discordance is not a correction factor.',
    simplification: 'The case uses a selected 60-minute second-marker checkpoint returning a fixed 38, and a 5-minute contrast in which the reported estimate stands unexamined. Her confusion is a supplied finding with no cause established.',
    whereItMisleads: 'The size of the gap is taken as a rule, as a factor to adjust by, or as evidence that her filtration is low. The confusion is attributed to a medicine.',
    correctUnderstanding: 'The association between a discordance of this size and higher-than-predicted drug exposure comes from one retrospective cohort of one drug, in patients who were also older and longer in hospital \u2014 an association, not a rule and not a correction. Nothing here establishes her filtration, and nothing attributes her confusion.',
    briefIn: ['estimated-filtration-a-number-she-was-never-measured-by'],
  },
  {
    id: 'renal-estimate-continuing-care',
    headline: 'Nothing here selects a drug, a dose, an equation, or a marker.',
    simplification: 'The medicine decision is placed with the qualified team that has the whole picture. This lesson does not decide whether the medicine should be started, does not adjust it, and does not name either marker as the better one.',
    whereItMisleads: 'Refusing to dose on the reported estimate is read as saying the medicine is wrong for her, or the preference for a differently generated marker is read as a rule to send it.',
    correctUnderstanding: 'Refusing one basis for a decision supplies no other basis. Individualize the marker choice, the medicine, and any monitoring with the teams that own them. Handoff closes rehearsal, not the open question, and what is handed on is the uncertainty stated as uncertainty.',
    briefIn: ['estimated-filtration-a-number-she-was-never-measured-by'],
  },
  {
    id: 'renal-rhabdomyolysis-number-bounds',
    headline: 'The creatine kinase does not carry the risk, and neither does this lesson.',
    simplification: 'The observed distributions quoted here \u2014 about 3% for exercise, over 40% for compartment syndrome, nearly 60% after cardiac arrest \u2014 come from retrospective cohorts restricted to a creatine kinase above 5,000 U/L. The supplied value is one variable among eight in the model they came from.',
    whereItMisleads: 'A cohort percentage is read as this patient\u2019s probability, or the absence of a taught threshold is read as a threshold of its own.',
    correctUnderstanding: 'No score, threshold, cutoff, dialysis criterion, or discharge criterion is taught here, and refusing one is not a claim that this patient will never need replacement therapy. A compartment syndrome is a bedside finding that must be repeated; no laboratory value rules it in or out.',
    briefIn: ['rhabdomyolysis-a-number-that-does-not-carry-the-risk'],
  },
  {
    id: 'renal-rhabdomyolysis-authored-contrasts',
    headline: 'The frightening number rises and the kidney does not follow it, on purpose.',
    simplification: 'The case uses a selected 90-minute serial checkpoint at which the creatine kinase moves from 48,000 to 61,000 U/L while the creatinine holds at 88 \u00b5mol/L and urine output at 1.4 mL/kg/h, and a 5-minute contrast in which the limbs are still unexamined.',
    whereItMisleads: 'The rise is read as a modeled muscle-injury course, as deterioration, or as a prediction about a real patient. The checkpoint becomes an expected peak or a required wait.',
    correctUnderstanding: 'Both numbers are authored and inert; nothing the learner does bends either. The lesson is that the value which drove disposition in the series behind it was not the value that tracked the kidney \u2014 in one small series the two moved in opposite directions.',
    briefIn: ['rhabdomyolysis-a-number-that-does-not-carry-the-risk'],
  },
  {
    id: 'renal-rhabdomyolysis-continuing-care',
    headline: 'Nothing here selects a fluid, and nothing here rules an addition out.',
    simplification: 'Fluid ownership is recorded; the volume, rate, product, and targets belong to the team that takes it, and no measurement of what was given is supplied. Bicarbonate and mannitol are reviewed rather than banned.',
    whereItMisleads: 'The review of bicarbonate and mannitol is read as proof they do not work, or the support for fluid is read as a prescription.',
    correctUnderstanding: 'The review those findings come from rated its own evidence very low quality and mostly retrospective. Absence of demonstrated benefit is not demonstrated absence of benefit; it is a reason to leave the decision with the qualified team rather than to add by habit. Handoff closes rehearsal, not surveillance, and supplies no discharge criterion.',
    briefIn: ['rhabdomyolysis-a-number-that-does-not-carry-the-risk'],
  },
  {
    id: 'renal-contrast-attribution-bounds',
    headline: 'The lesson removes a label without supplying a cause.',
    simplification: 'The hypotension, the two nephrotoxic drugs, and the fever with a rising inflammatory marker are all competing explanations the written attribution left untouched, and all of them are still open when the rehearsal ends. No culture, biopsy, imaging, or nephrology opinion is supplied.',
    whereItMisleads: 'Refusing the contrast attribution is read as establishing one of the alternatives, or as a claim that contrast never injures a kidney.',
    correctUnderstanding: 'A rise after an exposure identifies no cause without a comparison group, and that argument cuts the same way against every candidate here. The consensus position that the risk has been overstated is discussed rather than settled, and a small group at genuine risk is retained in the source it comes from.',
    briefIn: ['contrast-attribution-a-label-that-stopped-the-search'],
  },
  {
    id: 'renal-contrast-authored-contrasts',
    headline: 'The creatinine rises whatever the learner does, on purpose.',
    simplification: 'The case uses a selected 60-minute chart-retrieval checkpoint and a 5-minute unexamined contrast. What the search changes is the record -- the full charts hold four hypotensive episodes rather than the ward summary\u2019s two -- and never the patient.',
    whereItMisleads: 'The rising creatinine is read as a modeled injury course, as evidence for or against any cause, or as a prediction about a real patient. The retrieval clock becomes a required wait.',
    correctUnderstanding: 'A lesson about attribution cannot reward good reasoning with a better number, or it teaches that reasoning is how numbers improve. The trend here is authored and inert; it confirms nothing, and a fall would confirm nothing either.',
    briefIn: ['contrast-attribution-a-label-that-stopped-the-search'],
  },
  {
    id: 'renal-contrast-continuing-care',
    headline: 'Nothing here decides whether anyone should receive contrast.',
    simplification: 'This lesson is about a sentence written in a set of notes after the fact. It prescribes and withholds no fluid, sets no threshold or eGFR cutoff, orders and cancels no imaging, and adopts no protocol.',
    whereItMisleads: 'The evidence review is taken as permission to give contrast to a particular patient, as a reason to stop prophylactic fluid, or as a rule about who may be scanned.',
    correctUnderstanding: 'Withdrawing exposures that are still running is the one thing here that changes anything, and it is not an attribution. Individualize every imaging, fluid, and access decision with the qualified teams that own them. Handoff closes rehearsal, not the search.',
    briefIn: ['contrast-attribution-a-label-that-stopped-the-search'],
  },
  {
    id: 'renal-hypomagnesemia-repletion',
    headline: 'The serum magnesium is not where this lesson\u2019s response appears.',
    simplification: 'Qualified repletion produces an authored change in potassium, ionized calcium, QT interval and bedside findings, while the modeled magnesium moves 0.78 to 0.81 mmol/L. No dose, route, rate, product, serum target, or total-body deficit is modeled.',
    whereItMisleads: 'A magnesium that barely moves is read as repletion having failed, or a potassium that finally rises is read as the deficit being corrected.',
    correctUnderstanding: 'Judge repletion by the patient and by the results that were refractory, not by the number that is sustained from body pools. Neither a moved potassium nor an unmoved magnesium establishes a corrected deficit; that requires qualified serial review this lesson does not model.',
    briefIn: ['hypomagnesemia-refractory-potassium-and-the-normal-number'],
  },
  {
    id: 'renal-hypomagnesemia-authored-contrasts',
    headline: 'The repletion and untreated intervals are teaching contrasts, not kinetics.',
    simplification: 'The case uses a selected 90-minute repletion checkpoint and a 5-minute untreated contrast in which cramping increases and the supplied QT interval lengthens. The fractional excretion of magnesium is supplied as a fixed value.',
    whereItMisleads: 'These clocks become expected repletion durations, required waits, deterioration predictions, or a rule for how quickly an untreated patient declines.',
    correctUnderstanding: 'Monitoring, exposure cessation, and repletion proceed independently of administrative or repeat-test gates. No expected time course, threshold, or outcome follows from this authored model, and the supplied fractional excretion separates loss routes rather than establishing a cause.',
    briefIn: ['hypomagnesemia-refractory-potassium-and-the-normal-number'],
  },
  {
    id: 'renal-hypomagnesemia-continuing-care',
    headline: 'An in-range magnesium closes neither the diagnosis nor the care.',
    simplification: 'Stopping the suspected acid-suppression exposure is recorded for review and does not attribute the depletion to it. The cause, the medication decision, and continuing QT surveillance all remain open at handoff.',
    whereItMisleads: 'A value inside a printed reference range is read as excluding depletion, or stopping a suspected drug is read as having established that it was responsible.',
    correctUnderstanding: 'A serum magnesium inside the reference range does not exclude depletion, because the concentration is sustained from body pools \u2014 and it does not establish depletion either; no threshold is taught here. Individualize the exposure review, the loss assessment, and serial follow-up. Handoff closes rehearsal, not surveillance or unresolved risk.',
    briefIn: ['hypomagnesemia-refractory-potassium-and-the-normal-number'],
  },
  {
    id: 'renal-hypocalcemia-measurement',
    headline: 'Albumin-adjusted total calcium is not a measured ionized-calcium result.',
    simplification: 'The case supplies discordant historical total and adjusted calcium alongside low measured ionized calcium at actual pH. No protein-binding, pH-correction, or laboratory-error solver is supplied.',
    whereItMisleads: 'A reassuring adjusted estimate erases symptoms and low ionized calcium, or a new ionized check silently refreshes albumin, pH, phosphate, kidney function, or QTc.',
    correctUnderstanding: 'Interpret calcium with symptoms, actual measurement conditions, and kidney context. Ionized measurement needs appropriate specimen handling. Historical values remain historical, and no formula replaces the supplied ionized result.',
    briefIn: ['hypocalcemia-ionized-calcium-and-ckd'],
  },
  {
    id: 'renal-hypocalcemia-authored-contrasts',
    headline: 'Calcium response and recurrence use authored contrasts, not drug or mineral kinetics.',
    simplification: 'Rescue, uncovered recurrence, and continuing calcium care produce selected 15-, 45-, and 60-minute observations. Continuing care can begin immediately after rescue; the early response does not have to be observed first.',
    whereItMisleads: 'A teaching checkpoint becomes a required wait, a predictable drug duration, a calcium dose, or a rapid activated-vitamin-D effect.',
    correctUnderstanding: 'Use qualified monitored rescue and individualized ongoing calcium care with renal-aware prescription and reassessment. Mineral-care and follow-up acknowledgments do not drive the modeled calcium response. No normal calcium, QT recovery, kidney recovery, or injury outcome is predicted.',
    briefIn: ['hypocalcemia-ionized-calcium-and-ckd'],
  },
  {
    id: 'renal-hypocalcemia-continuing-care',
    headline: 'Symptom relief does not end risk after denosumab in advanced kidney disease.',
    simplification: 'Perioral tingling and low ionized calcium persist through partial improvement. A full current assessment can support monitored transfer while a delivered treatment response remains pending.',
    whereItMisleads: 'Handoff becomes discharge clearance, normal magnesium requires automatic replacement, or denosumab is permanently stopped without a coordinated future-treatment plan.',
    correctUnderstanding: 'Preserve kidney-specific mineral care, continuing calcium, acute surveillance, and longer-term follow-up. Future medication decisions require qualified review and fracture-risk safeguards. Routine label follow-up intervals do not replace acute reassessment; a completed rehearsal is not durable recovery.',
    briefIn: ['hypocalcemia-ionized-calcium-and-ckd'],
  },
  {
    id: 'renal-hypernatremia-authored-contrasts',
    headline: 'Circulation and sodium changes are authored contrasts, not water-replacement kinetics.',
    simplification: 'A 15-minute circulation response leaves sodium high. Water-only care can partly lower sodium before recurrence with uncovered losses; combined care later produces another partial improvement. No dose, clearance, fluid-deficit, or injury model is supplied.',
    whereItMisleads: 'A clock becomes a required wait, a fixed sodium change predicts a patient response, or improved pressure proves resolved dehydration.',
    correctUnderstanding: 'Restore depleted circulation promptly, then individualize water and ongoing-loss replacement with serial reassessment. Authored checkpoints and session stops are not treatment deadlines, optimal correction rates, or outcome predictions.',
    briefIn: ['hypernatremia-water-access-and-losses'],
  },
  {
    id: 'renal-hypernatremia-individualized-care',
    headline: 'Reliable assisted water access supports continuity but is not a biochemical treatment gate.',
    simplification: 'Qualified access support includes safe route and assistance review without forcing oral intake. Delivered continuing-loss care does not instantly stop diarrhea; adequate water replacement can work before long-term access is secured.',
    whereItMisleads: 'An acknowledgment supplies water, every patient receives desmopressin, or concentrated urine excludes every renal cause of hypernatremia.',
    correctUnderstanding: 'Interpret urine findings with the full clinical context, assess route and swallowing suitability individually, and reconcile deficit, maintenance, ongoing losses, and all other intake. This case supplies no established desmopressin indication, diagnosis challenge, or universal regional prescription.',
    briefIn: ['hypernatremia-water-access-and-losses'],
  },
  {
    id: 'renal-hypernatremia-observed-findings',
    headline: 'Sodium-only and fluid-balance-only checks keep separate histories.',
    simplification: 'Partial observations do not refresh an older full panel. Handoff can transfer unresolved recurrence and a pending response after qualified care and current combined assessment.',
    whereItMisleads: 'A treatment request or timer becomes an observed response, or a newer sodium result silently updates urine output and continuing losses.',
    correctUnderstanding: 'Request current combined findings and hand off ongoing replacement, assisted access, monitoring, and escalation. Neither an earlier partial improvement nor completed rehearsal proves durable correction, renal recovery, or discharge readiness.',
    briefIn: ['hypernatremia-water-access-and-losses'],
  },
  {
    id: 'renal-hyponatremia-authored-contrasts',
    headline: 'Sodium changes are authored assessment contrasts, not treatment kinetics.',
    simplification: 'Selected qualified rescue yields authored 118-to-123 and then 124 mmol/L checkpoints after 60 and 30 minutes. No dose, clearance, urine-loss, or delayed-injury model is supplied.',
    whereItMisleads: 'A fixed change predicts a patient response, a clock becomes a required wait, or a +6 mmol/L handoff becomes an automatic treatment stop.',
    correctUnderstanding: 'Individualize symptom-led treatment and close sodium, neurologic, urine-output, and fluid-balance surveillance. The selected 2022 Society for Endocrinology pathway is not a universal regional schedule; correction limits are ceilings, not routine targets.',
    briefIn: ['hyponatremia-symptoms-and-reassessment'],
  },
  {
    id: 'renal-hyponatremia-persistent-symptoms',
    headline: 'A better sodium number does not resolve the supplied neurologic symptoms.',
    simplification: 'Confusion, headache, and nausea persist through both authored response checkpoints. Qualified alternative-cause evaluation is available at any time but generates no diagnosis or cure.',
    whereItMisleads: 'Numeric improvement becomes neurologic recovery, concentrated urine during thiazide exposure proves SIAD, or recent symptoms prove acute duration.',
    correctUnderstanding: 'Continue expert treatment decisions and investigate unresolved symptoms. Interpret contemporaneous pretreatment specimens with medications and alternative causes, preserve the original correction window, and do not infer severe malnutrition from poor intake alone.',
    briefIn: ['hyponatremia-symptoms-and-reassessment'],
  },
  {
    id: 'renal-hyponatremia-observed-findings',
    headline: 'Partial sodium or neurologic checks do not refresh the older full assessment.',
    simplification: 'Each requested partial and full observation keeps its own timestamp; care acknowledgments and elapsed time do not acquire results.',
    whereItMisleads: 'A newer sodium result silently updates symptoms, or an old full panel authorizes further treatment or completed handoff after a changed response.',
    correctUnderstanding: 'Request current combined findings and transfer unresolved symptoms, cumulative correction, surveillance, investigation, and escalation. Handoff ends rehearsal, not clinical care, and establishes neither discharge readiness nor durable safety.',
    briefIn: ['hyponatremia-symptoms-and-reassessment'],
  },
  {
    id: 'renal-hypokalemia-authored-contrasts',
    headline: 'Replacement and recurrent losses use authored contrasts, not potassium or magnesium kinetics.',
    simplification: 'Separate potassium and magnesium care can produce partial observations before combined improvement. Continuing unmanaged losses can cause an authored recurrence; the 30-, 60-, and 120-minute checkpoints are not clinical waits or grading deadlines.',
    whereItMisleads: 'Fixed laboratory changes become expected patient responses, magnesium is made a prerequisite to urgent potassium treatment, or a teaching stop predicts arrhythmia or death.',
    correctUnderstanding: 'Treat severe deficiency promptly with qualified monitoring and individualized replacement. Magnesium deficiency can make potassium correction difficult, but potassium-only care is not necessarily ineffective. No dose, clearance, arrhythmia, or renal-recovery solver is supplied.',
    briefIn: ['hypokalemia-magnesium-and-ongoing-losses'],
  },
  {
    id: 'renal-hypokalemia-individualized-care',
    headline: 'Continuing-loss care is delivered support, not instant diarrhea cessation or a universal medication rule.',
    simplification: 'Potassium, magnesium, and individualized continuing-loss management are independent qualified care requests. Loss management alone does not replenish deficits or prove the underlying illness has ended.',
    whereItMisleads: 'A planning acknowledgment stops losses, an unchanged usual replacement fits every patient, or improved serum findings establish replenished body stores.',
    correctUnderstanding: 'Coordinate ongoing-loss replacement and contributor management with kidney, volume, medication, and clinical reassessment. Avoid unmonitored rapid potassium administration and continue appropriate electrolyte and cardiac surveillance.',
    briefIn: ['hypokalemia-magnesium-and-ongoing-losses'],
  },
  {
    id: 'renal-hypokalemia-observed-findings',
    headline: 'A potassium-only or ECG-only check cannot refresh older magnesium findings.',
    simplification: 'Partial and full observations retain separate timestamps. The waveform selects qualitative T-wave flattening only; it supplies no U waves or quantitative QT/QU measurement and cannot establish electrolyte concentrations.',
    whereItMisleads: 'A better waveform, one potassium value, or an elapsed response clock becomes proof of corrected magnesium, restored stores, or durable rhythm safety.',
    correctUnderstanding: 'Request fresh combined findings when needed and transfer unresolved deficits, recurrent-loss history, and continuing surveillance. Handoff ends rehearsal, not replacement needs, and grants no discharge or competence certification.',
    briefIn: ['hypokalemia-magnesium-and-ongoing-losses'],
  },
  {
    id: 'renal-hyperkalemia-authored-contrasts',
    headline: 'Cardiac protection, shifting, removal, and rebound use fictional contrasts, not treatment kinetics.',
    simplification: 'Calcium has a finite 45-minute ECG benefit; shifting, delivered removal care, and rebound use 30-, 60-, and 150-minute checkpoints. No dose response, arrhythmia, arrest, or kidney-recovery model is supplied.',
    whereItMisleads: 'An authored clock becomes a safe waiting interval, a normal ECG establishes potassium safety, or a fixed response predicts a patient outcome.',
    correctUnderstanding: 'Treat promptly and reassess according to qualified clinical judgment. Calcium does not lower potassium, shifting does not remove total-body potassium, and ECG morphology is qualitative rather than a calibrated potassium or QRS measurement.',
    briefIn: ['hyperkalemia-cardioprotection-and-rebound'],
  },
  {
    id: 'renal-hyperkalemia-individualized-care',
    headline: 'A removal plan is not delivered elimination, and delivered care is not automatic dialysis.',
    simplification: 'Qualified calcium, insulin-glucose care, and delivered individualized elimination are dose-free requests. Support, context, monitoring, and planning do not themselves lower potassium.',
    whereItMisleads: 'A consultation instantly clears potassium, a binder alone becomes emergency rescue, or all patients receive identical dialysis, diuresis, or medication cessation.',
    correctUnderstanding: 'Individualize treatment and elimination with renal or critical-care expertise, including kidney trajectory, volume, urine output, contributors, and refractory disease. Preserve glucose prevention and surveillance; hypoglycemia is a risk, not an inevitable simulated event.',
    briefIn: ['hyperkalemia-cardioprotection-and-rebound'],
  },
  {
    id: 'renal-hyperkalemia-observed-findings',
    headline: 'ECG-only and glucose-only checks do not refresh historical potassium findings.',
    simplification: 'Requested observations retain separate timestamps. Accepted care and elapsed response clocks do not disclose new laboratory results. Observed rebound remains part of the learning history after later care.',
    whereItMisleads: 'An improved waveform or old potassium result justifies ending monitoring, or handoff is mistaken for durable correction or discharge.',
    correctUnderstanding: 'Repeat ECG, potassium, glucose, and bedside assessment as indicated; hand off unresolved risks, elimination progress, and continuing surveillance. A bounded teaching stop does not certify clinical safety or competence.',
    briefIn: ['hyperkalemia-cardioprotection-and-rebound'],
  },
];
