/**
 * The respiratory-medicine module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a respiratory-medicine scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const RESPIRATORY_MEDICINE_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'acute-severe-asthma-treatment-trajectory-and-tests-are-authored',
    headline: 'The prior therapy, serial findings, tests, and severe-obstruction waveform cue are bounded teaching reports.',
    simplification: 'One fixed record stands in for medication administration records, repeated examination, respiratory monitoring, PEF effort, specimen collection, blood-gas analysis, imaging, and team communication; a generic obstruction waveform supports pattern rehearsal rather than patient-specific capnography.',
    whereItMisleads: 'Treating the falling respiratory rate as improvement, one gas value as a universal threshold, negative snapshots as permanent exclusions, or completion as diagnostic skill.',
    correctUnderstanding: 'Real reassessment integrates treatment timing, trajectory, mentation, speech, effort, air movement, oxygenation, objective airflow when feasible, gas exchange when indicated, dangerous alternatives, verified monitoring, and repeated expert review.',
    briefIn: ['acute-severe-asthma'],
  },
  {
    id: 'acute-severe-asthma-controls-record-recognition-escalation-review-and-handoff-only',
    headline: 'The controls record trajectory review, respiratory-failure recognition, escalation, bounded risk review, and handoff; they do not deliver care.',
    simplification: 'Five clicks stand in for urgent multidisciplinary reassessment, critical-care and airway mobilization, alternative-cause review, ventilation planning, communication, and handoff.',
    whereItMisleads: 'Equating button order with examination, test interpretation, airway judgment, prescribing, treatment delivery, ventilation, or critical-care competence.',
    correctUnderstanding: 'Actual care requires continuous bedside reassessment, experienced respiratory and critical-care teams, local emergency pathways, monitored treatment, and readiness for rapid deterioration.',
    briefIn: ['acute-severe-asthma'],
  },
  {
    id: 'no-live-acute-severe-asthma-treatment-ventilation-procedure-disposition-or-outcome',
    headline: 'The lab does not repeat treatment, select ventilation, perform an airway procedure, determine disposition, or predict outcome.',
    simplification: 'No live bronchodilator, antimuscarinic, oxygen, steroid, magnesium, antibiotic, epinephrine, fluid, device trial, intubation, sedation, neuromuscular blockade, ventilator setting, procedure, disposition, prognosis, response, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as a treatment or ventilation recipe or using completion as evidence of prescribing, airway, ventilation, procedural, disposition, or prognostic competence.',
    correctUnderstanding: 'Use current acute-asthma guidance, verified patient data, device instructions, qualified airway and ventilation expertise, local protocols, and continuous patient-specific reassessment.',
    briefIn: ['acute-severe-asthma'],
  },
  {
    id: 'copd-transition-baseline-treatment-tests-and-function-are-authored',
    headline: 'The baseline, hospital treatment, blood gases, oximetry, imaging, corridor report, and inhaler-technique report are authored.',
    simplification: 'Fixed reports stand in for longitudinal records, examination, testing, respiratory-therapy assessment, medication reconciliation, and multidisciplinary communication.',
    whereItMisleads: 'Treating one exertional saturation as a long-term oxygen qualification, improvement as readiness, or fixed reports as learner-acquired clinical skill.',
    correctUnderstanding: 'Real transition decisions require verified baseline and serial data, patient-centered functional assessment, local oxygen pathways, qualified teams, and repeated review after the acute illness.',
    briefIn: ['copd-exacerbation-transition-reassessment'],
  },
  {
    id: 'copd-transition-controls-record-review-coordination-and-handoff-only',
    headline: 'The controls record recovery review, residual-needs review, medication ownership, coordination, and handoff only.',
    simplification: 'Five clicks stand in for multidisciplinary transition assessment, education, referral work, access planning, and communication.',
    whereItMisleads: 'Equating button order with examination, testing, prescribing, inhaler education, rehabilitation enrollment, discharge planning, or longitudinal-care competence.',
    correctUnderstanding: 'Actual transition care requires patient participation, verified technique teaching, local services, access-sensitive planning, named clinical owners, and longitudinal reassessment.',
    briefIn: ['copd-exacerbation-transition-reassessment'],
  },
  {
    id: 'no-live-copd-transition-testing-treatment-prescribing-discharge-or-outcome',
    headline: 'The lab does not test, treat, prescribe, qualify oxygen, enroll rehabilitation, discharge, or predict outcome.',
    simplification: 'No live oximetry or gas acquisition, exercise testing, oxygen or medication delivery, inhaler selection, technique grading, appointment booking, home assessment, discharge, prognosis, readmission risk, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as qualification or prescribing rules or using completion as evidence of clinical, educational, transition, or prognostic competence.',
    correctUnderstanding: 'Use current COPD guidance, verified patient data, device instructions, local qualification and rehabilitation pathways, qualified respiratory teams, and patient-specific follow-up.',
    briefIn: ['copd-exacerbation-transition-reassessment'],
  },
  {
    id: 'cap-hypoxemia-presentation-imaging-gas-and-laboratory-reports-are-authored',
    headline: 'The symptoms, observations, oximetry, blood gas, imaging, laboratory reports, and criteria are authored teaching data.',
    simplification: 'One fixed record stands in for history, examination, signal validation, sampling, imaging, laboratory review, and multidisciplinary communication.',
    whereItMisleads: 'Treating the fixed pattern as diagnostic skill, a pathogen diagnosis, or a universal threshold for support or location of care.',
    correctUnderstanding: 'Real assessment requires verified patient data, repeated whole-patient review, current guidance, qualified teams, and local escalation pathways.',
    briefIn: ['community-acquired-pneumonia-hypoxemia-reassessment'],
  },
  {
    id: 'cap-controls-record-review-support-testing-treatment-intent-and-handoff-only',
    headline: 'The controls record review, support intent, escalation, testing and treatment ownership, and handoff only.',
    simplification: 'Five clicks stand in for urgent respiratory teamwork, clinical judgment, stewardship, reassessment, and communication.',
    whereItMisleads: 'Equating button order with examination, test interpretation, diagnosis, prescribing, oxygen delivery, airway management, or team competence.',
    correctUnderstanding: 'Actual care requires continuous bedside reassessment, qualified respiratory and critical-care teams, local protocols, and individualized treatment.',
    briefIn: ['community-acquired-pneumonia-hypoxemia-reassessment'],
  },
  {
    id: 'no-live-cap-testing-treatment-device-selection-disposition-or-outcome',
    headline: 'The lab does not test, prescribe or deliver treatment, select respiratory support, determine disposition, or predict outcome.',
    simplification: 'No live test, score, oxygen device, flow, FiO₂, ventilation, fluid, antibiotic, steroid, vasopressor, procedure, treatment response, disposition, prognosis, pathogen, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as a treatment or disposition rule or using completion as evidence of diagnostic, prescribing, respiratory-support, procedural, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current CAP and oxygen guidance, local resistance data, device instructions, qualified teams, and patient-specific reassessment.',
    briefIn: ['community-acquired-pneumonia-hypoxemia-reassessment'],
  },
  {
    id: 'post-pe-course-function-and-evaluation-reports-are-authored',
    headline: 'The acute event, anticoagulation course, function, walk, oximetry, echo, and perfusion findings are authored.',
    simplification: 'One fixed record stands in for longitudinal history, adherence and bleeding review, examination, exercise assessment, monitoring, imaging, and multidisciplinary communication.',
    whereItMisleads: 'Treating persistent symptoms or one abnormal report as diagnostic proof, treating negative snapshots as permanent exclusions, or treating the record as learner-acquired skill.',
    correctUnderstanding: 'Real post-PE assessment requires verified longitudinal data, patient-centered function, repeated safety review, qualified testing, and pulmonary-vascular expertise.',
    briefIn: ['post-pulmonary-embolism-persistent-dyspnea'],
  },
  {
    id: 'post-pe-controls-record-review-referral-ownership-and-handoff-only',
    headline: 'The controls record trajectory, safety, evidence, referral, ownership, and handoff; they do not diagnose or treat.',
    simplification: 'Five clicks stand in for longitudinal assessment, multidisciplinary diagnostic work, shared planning, and communication.',
    whereItMisleads: 'Equating button order with examination, testing, imaging interpretation, anticoagulation management, diagnosis, or pulmonary-vascular competence.',
    correctUnderstanding: 'Actual care requires qualified teams, current pathways, patient participation, verified treatment safety, and longitudinal reassessment.',
    briefIn: ['post-pulmonary-embolism-persistent-dyspnea'],
  },
  {
    id: 'no-live-post-pe-testing-diagnosis-treatment-procedure-or-outcome',
    headline: 'The lab does not test, diagnose CTEPD or CTEPH, select treatment or a procedure, determine disposition, or predict outcome.',
    simplification: 'No live walk, oximetry, ECG, laboratory, echo, V/Q, CT, CPET, catheterization, anticoagulant, dose, duration, oxygen, rehabilitation, pulmonary-hypertension therapy, surgery, balloon procedure, operability decision, disposition, prognosis, recurrence, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as a diagnostic or treatment rule or using completion as evidence of clinical, imaging, prescribing, procedural, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current PE and pulmonary-hypertension guidance, qualified pulmonary-vascular teams, local pathways, and patient-specific judgment.',
    briefIn: ['post-pulmonary-embolism-persistent-dyspnea'],
  },
  {
    id: 'ape-support-course-and-failure-evidence-are-authored',
    headline: 'The pulmonary edema course, delivered care, support, examination, monitoring, blood gas, and imaging reports are authored.',
    simplification: 'One fixed record stands in for serial bedside assessment, treatment verification, respiratory-support review, sampling, testing, and multidisciplinary communication.',
    whereItMisleads: 'Treating one rate, saturation, gas, pressure, or negative snapshot as a universal failure rule, diagnosis, permanent exclusion, or learner-acquired skill.',
    correctUnderstanding: 'Real support reassessment requires continuous whole-patient review, verified device delivery, qualified testing, hemodynamic monitoring, and current local pathways.',
    briefIn: ['acute-pulmonary-edema-respiratory-support-reassessment'],
  },
  {
    id: 'ape-support-controls-record-review-escalation-and-handoff-only',
    headline: 'The controls record trajectory review, failure recognition, whole-patient review, escalation, and handoff only.',
    simplification: 'Five clicks stand in for urgent respiratory, critical-care, airway, nursing, pharmacy, and cause-focused teamwork.',
    whereItMisleads: 'Equating button order with examination, device operation, test interpretation, diagnosis, prescribing, airway management, or team competence.',
    correctUnderstanding: 'Actual care requires qualified bedside teams, real-time rescue capability, verified support, patient-specific decisions, and repeated reassessment.',
    briefIn: ['acute-pulmonary-edema-respiratory-support-reassessment'],
  },
  {
    id: 'no-live-ape-testing-device-treatment-airway-procedure-or-outcome',
    headline: 'The lab does not test, operate support, prescribe or deliver treatment, perform an airway procedure, determine disposition, or predict outcome.',
    simplification: 'No live monitor, blood gas, ECG, imaging, ultrasound, oxygen, interface, flow, FiO₂, pressure, PEEP, mode, drug, dose, ventilation, intubation, procedure, response, disposition, prognosis, resolution, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as device or airway instructions or using completion as evidence of clinical, respiratory-support, prescribing, procedural, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current heart-failure and ventilation guidance, device instructions, qualified respiratory and airway teams, and patient-specific judgment.',
    briefIn: ['acute-pulmonary-edema-respiratory-support-reassessment'],
  },
  {
    id: 'post-tension-course-drain-and-complication-reports-are-authored',
    headline: 'The tension event, emergency drainage, examination, current observations, radiograph, drain record, and complication screen are authored.',
    simplification: 'One fixed record stands in for emergency care, serial bedside assessment, pleural-system observation, imaging, multidisciplinary review, and patient communication.',
    whereItMisleads: 'Treating improvement, drain swing or bubbling, one radiograph, or a quiet complication snapshot as proof of patency, full re-expansion, durable resolution, or learner-acquired skill.',
    correctUnderstanding: 'Real post-drainage care requires repeated whole-patient and drain-system assessment, verified imaging when appropriate, qualified pleural teams, and immediate escalation for recurrent tension physiology.',
    briefIn: ['spontaneous-tension-pneumothorax-post-drainage-reassessment'],
  },
  {
    id: 'post-tension-controls-record-review-planning-ownership-and-handoff-only',
    headline: 'The controls record trajectory, safety, drain-system, complication, cause, planning, ownership, and handoff review only.',
    simplification: 'Five clicks stand in for serial pleural assessment, emergency safety-netting, shared decisions, multidisciplinary planning, and communication.',
    whereItMisleads: 'Equating button order with examination, drain inspection or management, imaging interpretation, diagnosis, procedure selection, treatment, or pleural-team competence.',
    correctUnderstanding: 'Actual care requires qualified bedside teams, current pathways, patient participation, explicit drain safety practices, and repeated reassessment.',
    briefIn: ['spontaneous-tension-pneumothorax-post-drainage-reassessment'],
  },
  {
    id: 'no-live-pleural-examination-testing-drain-procedure-treatment-or-outcome',
    headline: 'The lab does not examine, test, manage a drain, select or perform a pleural procedure, deliver treatment, determine disposition, or predict outcome.',
    simplification: 'No live examination, monitoring, imaging, ultrasound, pleural-pressure or laboratory testing, oxygen, medication, aspiration, decompression, drain inspection or manipulation, suction, clamping, flushing, removal, replacement, pleurodesis, thoracoscopy, surgery, disposition, prognosis, recurrence, resolution, or outcome is modeled.',
    whereItMisleads: 'Copying fictional observations as drain instructions or using completion as evidence of clinical, imaging, procedural, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient and drain data, current pleural guidance, local equipment and escalation pathways, qualified pleural and thoracic teams, and patient-specific judgment.',
    briefIn: ['spontaneous-tension-pneumothorax-post-drainage-reassessment'],
  },
  {
    id: 'large-effusion-presentation-imaging-fluid-and-response-are-authored',
    headline: 'The symptoms, examination claims, imaging, ultrasound window, aspiration, response, fluid values, classification, and negative findings are authored.',
    simplification: 'Fixed reports stand in for history, examination, safety review, thoracic ultrasound, image-guided aspiration, paired sampling, laboratory work, imaging, and serial multidisciplinary reassessment.',
    whereItMisleads: 'Treating size or appearance as a cause or urgency rule, 850 mL as a target, improvement as cure, or the fixed reports as learner-acquired examination, imaging, procedural, or interpretive skill.',
    correctUnderstanding: 'Real pleural evaluation requires verified whole-patient data, qualified thoracic ultrasound and procedures, symptom-led stopping, correct paired samples, local pathways, and repeated reassessment.',
    briefIn: ['large-unilateral-pleural-effusion-reassessment'],
  },
  {
    id: 'large-effusion-controls-record-review-intent-ownership-and-handoff-only',
    headline: 'The controls record review, experienced-team intent, an authored checkpoint, result ownership, and handoff only.',
    simplification: 'Six clicks stand in for whole-patient assessment, procedural safety planning, diagnostic sampling, response review, etiologic work, shared decisions, and communication.',
    whereItMisleads: 'Equating button order with examination, ultrasound, aspiration, sample handling, fluid calculation, diagnosis, procedure choice, treatment, or pleural-team competence.',
    correctUnderstanding: 'Actual care requires qualified teams, patient participation, current guidance, local equipment and laboratory processes, and patient-specific reassessment.',
    briefIn: ['large-unilateral-pleural-effusion-reassessment'],
  },
  {
    id: 'no-live-pleural-testing-calculation-procedure-treatment-diagnosis-or-outcome',
    headline: 'The lab does not examine, test, calculate, diagnose, perform aspiration or another procedure, deliver treatment, determine disposition, or predict outcome.',
    simplification: 'No live examination, monitoring, imaging, ultrasound, laboratory, cytology, microbiology, pleural-fluid acquisition or interpretation, criteria calculation, site or device selection, aspiration, drain, suction, biopsy, catheter, pleurodesis, surgery, medication, oxygen, systemic therapy, disposition, prognosis, recurrence, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as procedural or diagnostic rules or using completion as evidence of clinical, imaging, laboratory, procedural, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient and pleural data, current guidance, qualified pleural, radiology, pathology, microbiology, thoracic, and longitudinal teams, and patient-specific judgment.',
    briefIn: ['large-unilateral-pleural-effusion-reassessment'],
  },
  {
    id: 'bronchiectasis-mucus-presentation-imaging-and-response-are-authored',
    headline: 'The baseline, symptoms, cough, secretions, examination claims, imaging, team-delivered care, and response are authored.',
    simplification: 'Fixed reports stand in for longitudinal history, examination, cough and secretion assessment, oxygenation review, radiograph and CT acquisition and interpretation, respiratory physiotherapy, airway clearance, and serial multidisciplinary reassessment.',
    whereItMisleads: 'Treating focal collapse or endobronchial material as etiologic proof, improvement as complete clearance, or the reports as learner-acquired examination, imaging, airway-clearance, or respiratory-therapy skill.',
    correctUnderstanding: 'Real bronchiectasis deterioration requires verified whole-patient data, qualified imaging, experienced respiratory physiotherapy, individualized and tolerated airway clearance, and repeated reassessment.',
    briefIn: ['bronchiectasis-mucus-plugging-reassessment'],
  },
  {
    id: 'bronchiectasis-mucus-controls-record-review-intent-escalation-and-handoff-only',
    headline: 'The controls record review, individualized team intent, an authored response, escalation, ownership, and handoff only.',
    simplification: 'Six clicks stand in for assessment, imaging review, shared airway-clearance planning, response review, specialist evaluation, and communication.',
    whereItMisleads: 'Equating button order with examination, cough or sputum assessment, imaging interpretation, technique selection, secretion clearance, diagnosis, procedure choice, treatment, or team competence.',
    correctUnderstanding: 'Actual care requires qualified respiratory and airway teams, patient preference and tolerance, current guidance, local resources, explicit response goals, and patient-specific reassessment.',
    briefIn: ['bronchiectasis-mucus-plugging-reassessment'],
  },
  {
    id: 'no-live-airway-clearance-suction-bronchoscopy-treatment-diagnosis-or-outcome',
    headline: 'The lab does not examine, test, clear an airway, suction, perform bronchoscopy, diagnose, deliver treatment, determine disposition, or predict outcome.',
    simplification: 'No live examination, cough test, sputum assessment, monitoring, imaging, microbiology, airway-clearance technique or device, position, pressure, duration, frequency, humidification, saline, oxygen, medication, suction, bronchoscopy, lavage, biopsy, surgery, disposition, prognosis, resolution, recurrence, or outcome is modeled.',
    whereItMisleads: 'Copying fictional findings as a technique or procedure rule or using completion as evidence of clinical, imaging, respiratory-therapy, prescribing, procedural, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current bronchiectasis guidance, qualified respiratory physiotherapy and airway teams, local pathways, and patient-specific judgment.',
    briefIn: ['bronchiectasis-mucus-plugging-reassessment'],
  },
  {
    id: 'chronic-opioid-hypoventilation-exposure-and-sleep-reports-are-authored',
    headline: 'The opioid exposure, symptoms, awake findings, blood gas, sleep study, carbon-dioxide pattern, and specialist interpretation are authored.',
    simplification: 'Fixed reports stand in for longitudinal history, medication and substance reconciliation, examination, blood-gas sampling, attended polysomnography, carbon-dioxide monitoring, scoring, interpretation, and multidisciplinary reassessment.',
    whereItMisleads: 'Treating one awake saturation as proof of adequate sleep ventilation, the fixed pattern as learner interpretation, or chronic opioid exposure as proof of a single cause.',
    correctUnderstanding: 'Real evaluation requires verified patient and medication data, qualified attended testing when indicated, specialist interpretation, competing-cause review, and patient-specific reassessment.',
    briefIn: ['chronic-opioid-related-hypoventilation-reassessment'],
  },
  {
    id: 'chronic-opioid-hypoventilation-controls-review-and-coordinate-only',
    headline: 'The controls record longitudinal review, 2 evidence lanes, shared ownership, and handoff only.',
    simplification: 'Five clicks stand in for careful history, testing review, medication and alternate-cause assessment, shared decisions, safety education, follow-up planning, and communication.',
    whereItMisleads: 'Equating button order with examination, study scoring or interpretation, diagnosis, prescribing, tapering, reversal, device selection, treatment, or multidisciplinary competence.',
    correctUnderstanding: 'Actual care requires the patient, current guidance, qualified prescriber, sleep, respiratory, pharmacy, pain, and primary-care teams, and locally supported follow-through.',
    briefIn: ['chronic-opioid-related-hypoventilation-reassessment'],
  },
  {
    id: 'no-live-study-interpretation-diagnosis-opioid-change-pap-selection-treatment-or-outcome',
    headline: 'The lab does not interpret a study, diagnose, change opioids, select positive-pressure support, deliver treatment, determine disposition, or predict outcome.',
    simplification: 'No live examination, blood gas, sleep study, oximetry, capnography, spirometry, scoring, diagnosis, morphine-equivalent calculation, medication selection, abrupt stop, taper, naloxone intervention, oxygen, PAP mode or setting, ventilation, treatment, disposition, prognosis, response, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as diagnostic or treatment thresholds or using completion as evidence of clinical, sleep-study, prescribing, device, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current sleep and opioid guidance, qualified teams, local pathways, patient goals, and repeated patient-specific review.',
    briefIn: ['chronic-opioid-related-hypoventilation-reassessment'],
  },
  {
    id: 'neuromuscular-respiratory-failure-presentation-tests-and-trends-are-authored',
    headline: 'The ALS history, examination claims, mechanics, cough flow, blood gas, imaging, and serial trends are authored.',
    simplification: 'Fixed reports stand in for longitudinal history, examination, spirometry, respiratory-muscle and cough testing, blood-gas sampling, imaging, neurologic and bulbar assessment, test-quality review, and multidisciplinary reassessment.',
    whereItMisleads: 'Treating preserved awake saturation as adequate ventilation, one mechanics value as a universal rule, the fixed pattern as learner interpretation, or ALS as proof that no other cause matters.',
    correctUnderstanding: 'Real evaluation requires verified whole-patient and longitudinal data, qualified testing and interpretation, active alternative-cause review, and patient-specific reassessment.',
    briefIn: ['neuromuscular-respiratory-failure-reassessment'],
  },
  {
    id: 'neuromuscular-respiratory-failure-controls-review-escalate-coordinate-and-handoff-only',
    headline: 'The controls record trajectory review, recognition, parallel escalation and cause review, shared ownership, and handoff only.',
    simplification: 'Six clicks stand in for repeated assessment, respiratory-physiology review, urgent specialist connection, cough and bulbar review, patient-centered planning, and communication.',
    whereItMisleads: 'Equating button order with examination, test performance or interpretation, diagnosis, support or airway selection, secretion management, treatment, or multidisciplinary competence.',
    correctUnderstanding: 'Actual care requires the patient and caregivers, qualified respiratory, neurology, critical-care, airway, speech, nutrition, physiotherapy, nursing, and longitudinal teams, current guidance, local resources, and repeated review.',
    briefIn: ['neuromuscular-respiratory-failure-reassessment'],
  },
  {
    id: 'no-live-mechanics-bulbar-cough-testing-device-selection-treatment-procedure-or-outcome',
    headline: 'The lab does not perform respiratory, cough, bulbar, or sleep testing; choose support; deliver treatment; perform a procedure; or predict outcome.',
    simplification: 'No live examination, mechanics, oximetry, capnography, blood gas, imaging, swallowing, cough, secretion, neurologic or sleep testing, diagnosis, oxygen, ventilation interface or settings, airway-clearance or cough-assistance technique, suction, drug, nutrition, intubation, tracheostomy, disposition, prognosis, response, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as universal diagnostic or treatment thresholds or using completion as evidence of clinical, testing, respiratory-support, airway, procedural, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current neuromuscular guidance, qualified teams, local pathways, the patient’s priorities, and repeated patient-specific review.',
    briefIn: ['neuromuscular-respiratory-failure-reassessment'],
  },
  {
    id: 'obesity-hypoventilation-presentation-and-evidence-are-authored',
    headline: 'The symptoms, function, BMI, bicarbonate, awake gas, sleep study, imaging, spirometry, thyroid, and examination claims are authored.',
    simplification: 'Fixed reports stand in for longitudinal history, examination, body measurement, chemistry, blood-gas sampling, attended sleep testing and scoring, oximetry and carbon-dioxide monitoring, imaging, spirometry, neurologic review, medication reconciliation, and multidisciplinary reassessment.',
    whereItMisleads: 'Treating BMI, bicarbonate, awake saturation, PaCO₂, or AHI alone as diagnostic, or treating fixed qualified reports as learner-acquired testing or interpretation.',
    correctUnderstanding: 'Real evaluation integrates verified obesity, awake hypercapnia, sleep-disordered breathing, test quality, and exclusion of other causes through qualified patient-specific assessment.',
    briefIn: ['obesity-hypoventilation-reassessment'],
  },
  {
    id: 'obesity-hypoventilation-controls-review-recognize-coordinate-and-handoff-only',
    headline: 'The controls record person-centered review, 2 evidence lanes, bounded pattern recognition, shared ownership, and handoff only.',
    simplification: 'Six clicks stand in for history, current-safety review, awake and sleep evidence review, exclusion work, multidisciplinary planning, and communication.',
    whereItMisleads: 'Equating button order with examination, test acquisition or interpretation, diagnosis, PAP or oxygen choice, weight-health treatment, counseling, or multidisciplinary competence.',
    correctUnderstanding: 'Actual care requires the person, qualified respiratory, sleep, primary-care, cardiometabolic, and weight-health teams, current guidance, local resources, preferences, access, and repeated review.',
    briefIn: ['obesity-hypoventilation-reassessment'],
  },
  {
    id: 'no-live-bmi-gas-sleep-test-diagnosis-pap-weight-intervention-treatment-or-outcome',
    headline: 'The lab does not calculate BMI or AHI, perform or interpret testing, diagnose, select PAP or a weight intervention, deliver treatment, or predict outcome.',
    simplification: 'No live examination, body measurement, bicarbonate, blood gas, oximetry, capnography, spirometry, imaging, polygraphy, polysomnography, diagnosis, oxygen, CPAP, NIV, interface, mode, pressure, backup rate, drug, nutrition plan, weight target, bariatric procedure, driving advice, treatment, disposition, prognosis, response, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as universal screening, diagnostic, or treatment thresholds or using completion as evidence of clinical, testing, sleep, device, prescribing, weight-health, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current OHS guidance, qualified teams, local pathways, respectful shared decisions, and patient-specific follow-through.',
    briefIn: ['obesity-hypoventilation-reassessment'],
  },
  {
    id: 'noninvasive-ventilation-selection-presentation-care-and-response-are-authored',
    headline: 'The COPD baseline, initial care, suitability findings, gases, support delivery, and first-hour response are authored.',
    simplification: 'Fixed reports stand in for history, examination, controlled oxygen and COPD treatment, blood-gas and imaging acquisition and interpretation, goals discussion, monitoring, rescue preparation, qualified NIV application, interface tolerance, and serial reassessment.',
    whereItMisleads: 'Treating one pH, PaCO₂, respiratory rate, saturation, contraindication, or early change as a universal support, intubation, success, or disposition rule, or treating reported care as learner-delivered care.',
    correctUnderstanding: 'Real support selection integrates verified whole-patient trajectory, cause, airway protection, cooperation, secretions, hemodynamics, preferences, local capability, repeated response, and rapid rescue access.',
    briefIn: ['noninvasive-ventilation-selection'],
  },
  {
    id: 'noninvasive-ventilation-selection-controls-review-intent-reassess-and-handoff-only',
    headline: 'The controls record review, a bounded bilevel-support intent, reassessment, failure guards, and handoff only.',
    simplification: 'Six accepted actions and 2 nonmutating teaching choices stand in for multidisciplinary assessment, support selection, qualified delivery, continuous monitoring, serial blood gases, rescue planning, and communication.',
    whereItMisleads: 'Equating button choice or order with examination, blood-gas interpretation, device selection or operation, NIV application, treatment, intubation judgment, or acute respiratory-care competence.',
    correctUnderstanding: 'Actual care requires the patient, experienced respiratory and airway-capable teams, current guidance, local protocols and equipment, patient-specific settings and tolerance work, and repeated bedside reassessment.',
    briefIn: ['noninvasive-ventilation-selection'],
  },
  {
    id: 'no-live-niv-interface-settings-operation-treatment-intubation-disposition-or-outcome',
    headline: 'The lab does not choose NIV hardware or settings, operate a device, deliver treatment, intubate, determine disposition, or predict outcome.',
    simplification: 'No live examination, blood gas, imaging, oximetry, capnography, oxygen selection, interface or fit, pressure, PEEP, backup rate, trigger, cycle, flow, FiO₂, medication, sedation, suction, mask ventilation, intubation, procedure, treatment, weaning, disposition, prognosis, durable success, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as prescriptions or universal thresholds, or using completion as evidence of clinical, testing, device, airway, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current respiratory-support guidance, qualified staff, local pathways and rescue capacity, patient preferences, and continuous patient-specific reassessment.',
    briefIn: ['noninvasive-ventilation-selection'],
  },
  {
    id: 'high-flow-oxygen-presentation-support-and-response-are-authored',
    headline: 'The bilateral air-space disease, conventional oxygen, suitability findings, gases, qualified HFNO delivery, and 30-minute response are authored.',
    simplification: 'Fixed reports stand in for history, examination, oxygen-source and device verification, blood-gas and imaging acquisition and interpretation, preferences, monitoring, rescue preparation, qualified HFNO application, tolerance, and serial reassessment.',
    whereItMisleads: 'Treating reservoir-mask flow as precise delivered FiO₂, calculating a false ratio from it, or using one saturation, gas, respiratory rate, ROX value, suitability fact, or early change as a universal support, failure, intubation, success, or disposition rule.',
    correctUnderstanding: 'Real support selection integrates verified delivery, whole-patient trajectory, cause, airway protection, work, gas exchange, hemodynamics, preferences, local capability, repeated response, and rapid rescue access.',
    briefIn: ['high-flow-nasal-oxygen-escalation'],
  },
  {
    id: 'high-flow-oxygen-controls-review-select-monitor-and-handoff-only',
    headline: 'The controls record review, bounded HFNO intent, reassessment, failure guards, and handoff only.',
    simplification: 'Six accepted actions and 4 nonmutating teaching choices stand in for multidisciplinary assessment, support selection, qualified delivery, continuous monitoring, serial blood gases, rescue planning, and communication.',
    whereItMisleads: 'Equating button choice or order with examination, test interpretation, device selection or operation, HFNO application, oxygen titration, treatment, intubation judgment, or acute respiratory-care competence.',
    correctUnderstanding: 'Actual care requires the patient, experienced respiratory and airway-capable teams, current guidance, local protocols and equipment, patient-specific setup and tolerance work, and repeated bedside reassessment.',
    briefIn: ['high-flow-nasal-oxygen-escalation'],
  },
  {
    id: 'no-live-hfno-device-settings-operation-treatment-intubation-disposition-or-outcome',
    headline: 'The lab does not choose HFNO hardware or settings, operate a device, deliver oxygen or treatment, intubate, determine disposition, or predict outcome.',
    simplification: 'No live examination, blood gas, imaging, oximetry, capnography, source or device check, cannula or fit, flow, temperature, humidification, FiO₂, oxygen target, ROX or ratio calculation, NIV setting, medication, suction, proning, mask ventilation, intubation, procedure, treatment, weaning, disposition, prognosis, durable success, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values as prescriptions or universal thresholds, or using completion as evidence of clinical, testing, device, airway, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, current respiratory-support guidance, qualified staff, local pathways and rescue capacity, patient preferences, and continuous patient-specific reassessment.',
    briefIn: ['high-flow-nasal-oxygen-escalation'],
  },
  {
    id: 'oxygen-device-failure-presentation-path-and-response-are-authored',
    headline: 'The transport state, saturation trend, portable-source path, alternate support, and 3-minute response are authored.',
    simplification: 'Fixed reports stand in for whole-person assessment, pulse-oximetry quality review, oxygen-delivery tracing, qualified equipment checks, alternate support, and serial reassessment.',
    whereItMisleads: 'Treating the fictional depleted source as learner diagnosis, assuming every saturation fall is an equipment problem, or inferring that an attached interface and selected number prove oxygen delivery.',
    correctUnderstanding: 'Real care starts with the patient, corroborates the signal, supports oxygenation without delaying for a label, and uses qualified context-specific review of the complete delivery path and alternate causes.',
    briefIn: ['oxygen-device-failure'],
  },
  {
    id: 'oxygen-device-failure-controls-review-bridge-restore-reassess-and-handoff-only',
    headline: 'The controls record review, urgent bridge intent, fixed path review, checked restoration intent, reassessment, and handoff only.',
    simplification: 'Six clicks stand in for immediate team response, patient assessment, equipment-independent backup, source-to-patient troubleshooting, oxygen-delivery verification, transport planning, incident learning, and communication.',
    whereItMisleads: 'Equating button order with oxygen administration, equipment inspection or operation, cylinder handling, repair, technical competence, transport clearance, or multidisciplinary performance.',
    correctUnderstanding: 'Actual care requires the patient, trained clinical and technical teams, local device-specific procedures, verified oxygen sources and reserves, continuous monitoring, backup plans, and repeated reassessment.',
    briefIn: ['oxygen-device-failure'],
  },
  {
    id: 'no-live-cylinder-inspection-operation-oxygen-delivery-repair-transport-decision-or-outcome',
    headline: 'The lab does not inspect or operate oxygen equipment, deliver oxygen, repair a device, clear transport, or predict outcome.',
    simplification: 'No live examination, saturation or flow measurement, blood gas, imaging, diagnosis, cylinder-duration calculation, valve or connector handling, source, interface, flow, FiO\u2082, target, prescription, oxygen, ventilation, drug, procedure, repair, transport, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Copying fictional values or steps as equipment instructions or using completion as evidence of oxygen-delivery, cylinder, technical, clinical, transport, disposition, or prognostic competence.',
    correctUnderstanding: 'Use verified patient data, trained staff, current guidance, manufacturer instructions, local medical-gas and transport systems, independent backup, and patient-specific reassessment.',
    briefIn: ['oxygen-device-failure'],
  },
  {
    id: 'acute-tracheostomy-obstruction-anatomy-device-path-and-response-are-authored',
    headline: 'The airway anatomy, declared tracheostomy, obstruction, qualified device pathway, canonical gas flow, and response are authored.',
    simplification: 'Fixed reports and one scenario-scoped patency state stand in for bedhead-plan review, whole-person assessment, device identification, airflow and waveform assessment, experienced-team airway care, and serial reassessment.',
    whereItMisleads: 'Treating absent capnography alone as diagnostic, the fictional inner-cannula obstruction as learner diagnosis, the restored path as durable safety, or this branch as applicable to laryngectomy or every tracheostomy.',
    correctUnderstanding: 'Real care requires verified anatomy and device facts, the patient and both possible airways, qualified teams, current local emergency algorithms, continuous oxygenation, and repeated reassessment.',
    briefIn: ['acute-tracheostomy-obstruction'],
  },
  {
    id: 'acute-tracheostomy-obstruction-controls-review-support-qualified-restoration-reassess-and-handoff-only',
    headline: 'The controls record anatomy and patency review, urgent support, a fixed device branch, qualified restoration, reassessment, and handoff only.',
    simplification: 'Six clicks and 4 nonmutating teaching choices stand in for emergency team activation, oxygenation of both possible airways, patient- and device-specific review, experienced airway care, recurrence planning, and communication.',
    whereItMisleads: 'Equating button order with examination, oxygen delivery, capnography interpretation, device inspection or handling, catheter passage, suction, ventilation, tube exchange, procedure, or multidisciplinary competence.',
    correctUnderstanding: 'Actual care requires the patient, trained respiratory and airway teams, the current local algorithm, patient-specific anatomy and equipment, oxygenation, immediate rescue capacity, and repeated review.',
    briefIn: ['acute-tracheostomy-obstruction'],
  },
  {
    id: 'no-laryngectomy-fresh-stoma-device-generalization-live-airway-care-procedure-or-outcome',
    headline: 'The lab does not generalize to laryngectomy or other airway devices, provide live airway care, perform a procedure, or predict outcome.',
    simplification: 'No live examination, oximetry, capnography, imaging, diagnosis, oxygen or humidification selection, cap or valve removal, cannula or tube handling, catheter passage, suction, cuff change, tube exchange, face or stoma ventilation, intubation, bronchoscopy, treatment, disposition, prognosis, durable resolution, or outcome is modeled.',
    whereItMisleads: 'Copying fictional findings or actions into another airway, or using completion as evidence of clinical, respiratory, device, suction, airway, procedural, treatment, disposition, or prognostic competence.',
    correctUnderstanding: 'Distinguish tracheostomy from laryngectomy, verify stoma maturity, tube design, cuff and upper-airway facts, and use current device- and patient-specific emergency guidance with qualified teams.',
    briefIn: ['acute-tracheostomy-obstruction'],
  },
];
