/**
 * The surgery and trauma module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fifteen modules'. An entry is filed here if a surgery-trauma scenario names it through
 * `briefIn` or declares it in its own metadata. The complete register is assembled in
 * `../limitations.ts`.
 */

import type { Limitation } from './types';

export const SURGERY_TRAUMA_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'negative-scan-presentation-and-team-response-are-authored',
    headline: 'One ward round, one telephone call, and a patient who never deteriorates.',
    simplification: 'The case supplies a fixed set of observations that do not move, one repeat round at which he has vomited once and still passed no flatus, and an operating team that answers sixty minutes after it is contacted with a fixed reply. No perfusion, contamination, inflammatory, or healing model runs underneath, and no leak is ever confirmed or excluded.',
    whereItMisleads: 'A learner concludes that an anastomotic leak always looks this calm, that the operating team always answers, or that escalating is what kept this patient stable.',
    correctUnderstanding: 'Nothing the learner does in this rehearsal changes his course, because nothing was going to. The observations are held almost still so that reading a trajectory is the only thing being tested; a real patient may deteriorate quickly, may have another cause entirely, or may have nothing wrong at all. The team reply is authored: in practice the call may not be answered, and the plan has to survive that.',
    briefIn: ['negative-scan-a-scan-that-cannot-say-no'],
  },
  {
    id: 'negative-scan-controls-are-recording-and-escalation-only',
    headline: 'No investigation is ordered, no drug is selected, and no operation is chosen.',
    simplification: 'The learner records the operative course, records the failure to progress against it, records what the reported scan does and does not exclude, contacts the operating team, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The bounded surgical-intent control is read as booking a return to theatre, or the scan-limits control is read as the learner re-reporting the imaging.',
    correctUnderstanding: 'Re-imaging, direct assessment of the anastomosis, and any decision to reoperate belong to the qualified surgical team, and this lesson exposes no investigation, drug, dose, route, or operation. Recording that a decision exists and belongs to somebody else is not making it.',
    briefIn: ['negative-scan-a-scan-that-cannot-say-no'],
  },
  {
    id: 'negative-scan-single-centre-figures-are-not-a-decision-rule',
    headline: 'Three small single-centre studies, pointing two ways, and none of them about this abdomen.',
    simplification: 'The lesson quotes a positive predictive value of 4 to 11 percent for any aberrant vital sign in 452 bowel resections, computed-tomography sensitivities of 0.59 and 73 percent with negative predictive values of 0.70 and 88 percent, and mortality after a false-negative scan of 62.5 percent in eight patients and 45.5 against 4.2 percent in another series.',
    whereItMisleads: 'A learner treats these as a decision rule — a threshold at which to escalate, or a probability that this patient has a leak.',
    correctUnderstanding: 'These are single-centre cohorts with different populations, different imaging protocols, different leak rates, and small numerators; the two imaging series disagree with each other on sensitivity by fourteen points. They establish only the shape of the problem: that one observation cannot establish a leak and this scan cannot exclude one. They do not give a probability for this patient, and no figure here should be carried to the bedside as one.',
    briefIn: ['negative-scan-a-scan-that-cannot-say-no'],
  },
  {
    id: 'rising-requirement-presentation-and-team-response-are-authored',
    headline: 'One ward, one telephone call, and observations that never move.',
    simplification: 'The case supplies a fixed set of entirely normal observations, one authored worsening at which he asks a fourth time and passive extension stops him mid-sentence, and an on-call team that answers twenty minutes after it is called with a fixed reply. No perfusion, compartment, muscle or ischaemia model runs underneath, and no diagnosis is ever confirmed or excluded.',
    whereItMisleads: 'A learner concludes that this always progresses this slowly, that the pulse and the observations always stay normal for this long, that the team always answers within twenty minutes, or that calling is what preserved the limb.',
    correctUnderstanding: 'Nothing the learner does changes his course, because nothing was going to. The observations are held normal so that reading a trajectory is the only thing being tested; a real limb may declare itself faster, may lose its pulse, or may have nothing wrong with it. The reply is authored: in practice the call may not be answered, and the plan has to survive that.',
    briefIn: ['rising-requirement-a-number-that-under-calls'],
  },
  {
    id: 'rising-requirement-controls-are-recording-and-escalation-only',
    headline: 'No measurement is taken, no drug is selected, and no limb is decompressed.',
    simplification: 'The learner records the injury and its clock, records the rising requirement, records what one pressure reading cannot decide, calls the team, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The bounded intent control is read as booking a fasciotomy, the pressure control is read as the learner taking or interpreting a measurement, or the refusal of extra analgesia is read as withholding pain relief.',
    correctUnderstanding: 'Repeat assessment, any further measurement, and any decision to decompress belong to the qualified surgical team, and this lesson exposes no drug, dose, route, threshold, incision, or dressing. The analgesia refusal objects to deferring the decision until morning, not to treating his pain, and the lesson says so in the refusal itself.',
    briefIn: ['rising-requirement-a-number-that-under-calls'],
  },
  {
    id: 'rising-requirement-tibial-fracture-figures-are-not-a-threshold',
    headline: 'Tibial-fracture data from single centres, quoted for its direction rather than its number.',
    simplification: 'The lesson quotes clinical findings at 13 to 19 percent sensitivity with 97 to 98 percent specificity and negative predictive value, a probability near 25 percent with one finding and 93 with three, 53 of 116 monitored patients above an absolute 30 mmHg against three cases, and continuous differential monitoring at 94 percent sensitivity and 98 percent specificity in 850 fractures.',
    whereItMisleads: 'A learner carries these to the bedside as a rule: a percentage for this patient, a pressure at which to act, or a count of findings that settles it.',
    correctUnderstanding: 'All of it is tibial-fracture data from single centres with small numerators, and the syndrome occurs at other sites and after other causes where none of it has been measured. The figures are quoted to show which direction each measure fails in — one misses most cases, the other over-calls — and not to supply a probability or a threshold for any individual patient.',
    briefIn: ['rising-requirement-a-number-that-under-calls'],
  },
  {
    id: 'unfinished-survey-presentation-and-team-response-are-authored',
    headline: 'One intensive care bed, one telephone call, and a patient who never deteriorates.',
    simplification: 'The case supplies a fixed set of stable observations that do not move, one authored sedation window at which he localises on the right, does not move the left arm and grimaces when the left forearm is handled, and a trauma team that answers twenty-five minutes after it is asked with a fixed reply. No injury, healing, sedation, or neurological model runs underneath, and no missed injury is ever confirmed or excluded.',
    whereItMisleads: 'A learner concludes that the sedation window always produces a finding, that keeping the question open is what caused the left arm to declare itself, or that a trauma team always answers.',
    correctUnderstanding: 'Nothing the learner does changes his course, because nothing was going to. The window is authored and arrives whether or not anybody was waiting for it; in practice sedation may not be lightened that night, the examination may show nothing at all, and the call may not be answered. The lesson is that the assessment was incomplete before any of that was known, which is the only state the learner is ever actually in.',
    briefIn: ['unfinished-survey-a-patient-who-cannot-be-asked'],
  },
  {
    id: 'unfinished-survey-controls-are-recording-and-escalation-only',
    headline: 'No examination is performed, no imaging is ordered, and no disposition is decided.',
    simplification: 'The learner records why the examination behind the record was limited, records what the injury list rests on, records that no tertiary survey has been done, asks the trauma team to complete it, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The bounded survey-intent control is read as booking imaging or a referral, or the escalation control is read as the learner refusing the step-down.',
    correctUnderstanding: 'Reexamination, re-review of the admission imaging, further films, specialty referral, and any operation belong to the qualified trauma team, and this lesson exposes no investigation, drug, dose, route, or procedure. The learner never decides where he sleeps tonight; the objection recorded is to calling him fully assessed, not to moving him.',
    briefIn: ['unfinished-survey-a-patient-who-cannot-be-asked'],
  },
  {
    id: 'unfinished-survey-observational-figures-are-not-a-decision-rule',
    headline: 'Observational studies that disagree about whether the step they measure works.',
    simplification: 'The lesson quotes 41 missed injuries in 36 of 399 patients (9 percent against a registry 2), a systematic review putting injuries found by the survey at 4.3 percent and those still missed at 1.5, and a before-and-after cohort of 487 patients in which formalising the survey raised performance from 27 to 42 percent without changing missed injury rates.',
    whereItMisleads: 'A learner treats 9 percent as this patient\u2019s probability of a missed injury, or reads the negative before-and-after result as evidence that the tertiary survey is not worth performing.',
    correctUnderstanding: 'These are observational cohorts from single centres across more than twenty years, with different populations, different definitions of missed injury, and different follow-up; the review that pooled them says none was randomized, none reported long-term health outcomes, and risk of bias varied considerably. Together they establish that examinations of patients who cannot take part miss things and that formalising a checklist did not by itself fix that. They give no probability for this patient, and the reason to complete the survey here is that his assessment is demonstrably unfinished, not that a percentage says so.',
    briefIn: ['unfinished-survey-a-patient-who-cannot-be-asked'],
  },
  {
    id: 'transient-response-presentation-and-team-response-are-authored',
    headline: 'One resuscitation room, one telephone call, and two authored blood pressures.',
    simplification: 'The case supplies two fixed observation sets and moves between them once, five minutes in, when the pressure falls a third time; and an operating team that answers eight minutes after it is called with a fixed reply. No perfusion, haemorrhage, coagulation, or fluid-response model runs underneath, no bolus can be given, and no injury is ever confirmed or excluded.',
    whereItMisleads: 'A learner concludes that a transient responder always deteriorates on this schedule, that the fall always waits five minutes, that the theatre team always answers in eight, or that calling is what kept him talking.',
    correctUnderstanding: 'Nothing the learner does changes his course, because nothing was going to. The two states exist so that the falling pattern is legible; a real patient may crash in the first minute, may hold for an hour, or may not be bleeding at all. The reply is authored: in practice the call may not be answered, the theatre may not be free, and the plan has to survive both.',
    briefIn: ['transient-response-a-patient-who-will-not-stay-up'],
  },
  {
    id: 'transient-response-controls-are-recording-and-escalation-only',
    headline: 'No fluid is given, no blood is ordered, no scan is requested, and no operation is chosen.',
    simplification: 'The learner records the mechanism and its clock, records the response to volume as a shape, records what a picture can and cannot do here, calls the operating team, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The bounded operative-intent control is read as booking an operation, the refusal of another bolus is read as withholding resuscitation, or the refusal to scan first is read as an argument against imaging trauma patients.',
    correctUnderstanding: 'The transfer, any imaging on the way or not at all, transfusion, and every operative decision belong to the qualified team, and this lesson exposes no drug, dose, route, fluid, blood product, incision, or threshold. The bolus refusal objects to spending a third interval watching the same answer shrink, not to the two boluses already given; the scan refusal objects to the interval and the room for this patient, and says so in the refusal itself.',
    briefIn: ['transient-response-a-patient-who-will-not-stay-up'],
  },
  {
    id: 'transient-response-retrospective-figures-are-not-a-stopwatch',
    headline: 'Three retrospective studies, two of them about somebody else, pointing in opposite directions.',
    simplification: 'The lesson quotes a probability of death rising by as much as 0.35 percent a minute among 165 of 243 registry patients, a hazard ratio of 1.89 (1.10 to 3.26) beyond ten minutes and 2.67 (0.97 to 7.34) below a systolic of 70 in 309 hypotensive torso gunshot wounds, and standardised mortality ratios of 0.745 against 1.023 favouring early whole-body imaging in 4,621 blunt trauma patients.',
    whereItMisleads: 'A learner carries these to the bedside as a clock — ten minutes, ninety minutes, a percentage per minute — or reads the imaging result as licence to scan this patient, or reads the delay results as an argument against scanning anyone.',
    correctUnderstanding: 'None of the three is randomised. Two are about penetrating injury or injury isolated to the abdomen, and the registry series reverses direction beyond ninety minutes because the patients who lasted that long were a different group. The gunshot-wound paper\u2019s own conclusion describes its 1.89 hazard ratio as almost threefold, which the ratio does not say, and the lesson keeps the ratio. Together they establish only the shape: that intervals cost something here, and that imaging is generally good for injured patients and still cannot stop bleeding. They give no threshold and no probability for this patient.',
    briefIn: ['transient-response-a-patient-who-will-not-stay-up'],
  },
  {
    id: 'quiet-chest-presentation-and-team-response-are-authored',
    headline: 'One evening, one telephone call from a daughter, and a chart that never moves.',
    simplification: 'The case supplies a fixed set of entirely normal resting observations that do not change at any point, one authored telephone call at 15 minutes in which her daughter says she cannot stay tonight, and an admitting team that answers thirty minutes after it is asked with a fixed reply. No respiratory, pain, healing, or complication model runs underneath, and no complication is ever confirmed or excluded.',
    whereItMisleads: 'A learner concludes that these patients always stay comfortable for the first evening, that a social problem always appears to justify admission, that the admitting team always answers, or that asking for the bed is what prevented a complication.',
    correctUnderstanding: 'Nothing the learner does changes her course, because nothing was going to. The observations are held normal so that reading a count and an age is the only thing being tested; a real patient may be in obvious difficulty on arrival, may have a haemothorax that declares itself overnight, or may be entirely fine all week. The daughter\u2019s call is authored and arrives whether or not anybody was waiting for it, and in practice no such convenient reason to admit turns up — the count and the age have to be enough on their own.',
    briefIn: ['quiet-chest-an-injury-whose-severity-is-not-yet-visible'],
  },
  {
    id: 'quiet-chest-controls-are-recording-and-escalation-only',
    headline: 'No analgesia is chosen, no block is requested, and no admission is booked.',
    simplification: 'The learner records the fall and what it broke with the age beside the count, records what being comfortable at rest does and does not measure, records what the count and the age predict, asks the admitting team for a bed and a plan over the right interval, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The bounded admission-intent control is read as booking a bed, the refusal of discharge is read as refusing to let her go home, or the boundary review is read as a recommendation for continuous epidural analgesia.',
    correctUnderstanding: 'The analgesia plan and its route, the observation interval, any respiratory or physiotherapy input, and the timing of discharge belong to the qualified team, and this lesson exposes no drug, dose, route, block, oxygen target, or discharge date. The discharge refusal objects to the one-week interval and to recording her this evening as a minor injury safely managed at home, not to her going home, and it says so in the refusal itself. The epidural evidence is quoted precisely because it does not support an intervention.',
    briefIn: ['quiet-chest-an-injury-whose-severity-is-not-yet-visible'],
  },
  {
    id: 'quiet-chest-retrospective-cohorts-are-not-an-admission-rule',
    headline: 'Two retrospective single-centre cohorts, one of which disagrees with itself.',
    simplification: 'The lesson quotes 31 percent pneumonia against 17 and 22 percent mortality against 10 in 277 patients aged 65 and over against 187 younger ones at matched fracture count and injury severity, five times the adjusted odds of death in 113 of 405 registry patients, and no significant difference in mortality, pneumonia or ventilation days across six randomised trials of continuous epidural analgesia totalling 223 patients at high risk of bias.',
    whereItMisleads: 'A learner carries the figures to the bedside as an admission rule — a fracture count at which to admit, or a percentage risk for this patient — or reads the epidural review as evidence that admission itself does not help.',
    correctUnderstanding: 'Both cohorts are retrospective and single-centre, covering different eras and different populations, and the first reports the odds of pneumonia per additional rib as 1.16 in its results while its conclusion states 27 percent, which do not match; the figures are quoted for direction rather than for magnitude. The epidural review is about one analgesic technique and says nothing about whether observation helps, because nobody has randomised that. Together they establish that this injury is more dangerous in older patients than its first evening suggests, and they give no threshold and no probability for this patient.',
    briefIn: ['quiet-chest-an-injury-whose-severity-is-not-yet-visible'],
  },
  {
    id: 'unowned-delay-presentation-and-team-response-are-authored',
    headline: 'One ward round, one lost theatre evening, and one telephone call that works.',
    simplification: 'The case supplies a fixed set of observations identical to the admission set that never change, one authored loss of the evening list at 10 minutes which makes a third cancellation and nineteen fasted hours, and a list team that answers twelve minutes after it is asked with a fixed reply and a named slot. No physiological, fasting, or scheduling model runs underneath, and no operation ever happens.',
    whereItMisleads: 'A learner concludes that the list team always answers, always answers quickly, always has a slot, or that one telephone call reliably fixes a delay of this kind.',
    correctUnderstanding: 'The reply is authored and generous on purpose, so that the lesson is about naming the wait rather than about winning an argument. In practice the call may not be answered, the person who holds the list may have nothing to give, and the honest outcome may be a delay that is still a delay but is now somebody\u2019s. Nothing the learner does changes her physiology, because nothing was going to.',
    briefIn: ['unowned-delay-a-wait-that-nobody-decided'],
  },
  {
    id: 'unowned-delay-controls-are-recording-and-escalation-only',
    headline: 'No operation is booked, no investigation is cancelled, and no fasting rule is set.',
    simplification: 'The learner records the fracture with its clock, records what each delay was for and who asked, records what is still actually outstanding, calls the team that owns the list and asks it to own the wait, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The escalation control is read as booking a slot or overriding a list, the echocardiogram refusal is read as the learner cancelling an investigation, or the fasting refusal is read as the learner setting a fasting rule.',
    correctUnderstanding: 'The scheduling and the order of the list, whether any preoperative investigation is actually wanted, the anaesthetic assessment, and the fasting instruction that follows a real slot all belong to the qualified teams, and this lesson exposes no operation, time, technique, drug, dose, route, or investigation. The echocardiogram refusal objects to treating an unbooked request with no documented consequence as a fitness gate, not to the test; the list refusal objects to filing a wait under nobody, not to the constraint, and both say so in the refusal itself.',
    briefIn: ['unowned-delay-a-wait-that-nobody-decided'],
  },
  {
    id: 'unowned-delay-the-randomised-trial-does-not-license-the-wait',
    headline: 'A large observational signal, and a randomised trial that did not reproduce it.',
    simplification: 'The lesson quotes complications rising beyond a 24-hour wait in 42,230 population-cohort patients with matched 30-day mortality of 6.5 against 5.8 percent, an adjusted relative risk of death of 0.81 with earlier surgery across sixteen observational studies covering 13,478 patients, and a randomised trial of 2,970 patients in which moving the median wait from 24 hours to 6 produced mortality of 9 against 10 percent with no difference in major complications.',
    whereItMisleads: 'A learner reads the observational figures as a causal target and treats 24 hours as a deadline, or reads the randomised trial as evidence that waiting does not matter and that this delay is therefore harmless.',
    correctUnderstanding: 'The observational studies cannot separate delay from the reasons patients are delayed, and the randomised trial tested something narrower than the lesson: it accelerated an already prompt pathway from a median of 24 hours to 6, in patients who were being operated on. Neither design speaks to a patient in her third day for whom no clinical question is documented. The lesson draws no threshold from any of them; what it asserts is only that a wait with no author is not a plan, which is a statement about accountability rather than about hours.',
    briefIn: ['unowned-delay-a-wait-that-nobody-decided'],
  },
  {
    id: 'third-attendance-presentation-and-team-response-are-authored',
    headline: 'One department, one colleague passing the door, and observations that never move.',
    simplification: 'The case supplies a fixed set of very nearly normal observations that do not change, one authored interruption at 12 minutes in which the clinician who saw her on Tuesday says she was fine then and asks kindly whether anything is different, and a surgical team that answers forty minutes after it is asked with a fixed reply. No inflammatory, pain, or disease model runs underneath, and no diagnosis is ever confirmed or excluded.',
    whereItMisleads: 'A learner concludes that a challenging colleague always appears, that colleagues who challenge are the obstacle, that a surgical team always answers, or that asking is what changed the outcome.',
    correctUnderstanding: 'The interruption is authored, arrives whether or not anybody was expecting it, and is written as a decent colleague behaving reasonably, because that is the version worth rehearsing. Nothing the learner does changes her course, because nothing was going to; a real patient may deteriorate quickly, may have another cause entirely, or may have nothing wrong at all. The reply is authored and deliberately slow: in practice the call may not be answered, and the plan has to survive that.',
    briefIn: ['third-attendance-a-question-two-people-have-already-answered'],
  },
  {
    id: 'third-attendance-controls-are-recording-and-escalation-only',
    headline: 'No examination is performed, no investigation is ordered, and no diagnosis is named.',
    simplification: 'The learner records the three attendances with what each found, records what a previous assessment can and cannot say, records the change between the examinations, asks the surgical team to see her, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The escalation control is read as a complaint about two colleagues, the discharge refusal is read as refusing to let her go home, or the lesson as a whole is read as teaching that previous clinicians should be distrusted.',
    correctUnderstanding: 'The examination, any investigation or imaging, any operation and the disposition belong to the qualified team, and this lesson exposes no investigation, score, drug, dose, route, or operation. Both previous entries are accurate and both clinicians behaved reasonably; the lesson is about how a record is read on a third occasion, not about how it was written on the first two, and the escalation text says so explicitly. The discharge refusal objects to reissuing an instruction she has already followed, not to her going home.',
    briefIn: ['third-attendance-a-question-two-people-have-already-answered'],
  },
  {
    id: 'third-attendance-a-return-visit-is-not-evidence-of-error',
    headline: 'One of the three sources argues directly against the instinct this case produces.',
    simplification: 'The lesson quotes a potentially missed diagnosis in 6.0 percent of 101,375 adults later diagnosed with appendicitis with an adjusted odds ratio of 1.68 for women with abdominal pain, a paediatric series in which a nonspecific triage complaint carried 8.8 percent missed against 3.8, and an analysis of more than nine million attendances in which patients admitted on a return visit had lower in-hospital mortality than those admitted at their first visit, 1.85 against 2.48 percent.',
    whereItMisleads: 'A learner treats a return visit as evidence that something was missed, carries the 6 percent to the bedside as this patient\u2019s probability, or applies the paediatric anchoring figures to an adult as a rate.',
    correctUnderstanding: 'The paediatric series is a single-centre study of children and is quoted for its mechanism rather than its rate; the adult cohort is administrative claims data, which identifies patterns rather than errors, and its 6 percent is conditioned on eventually having the diagnosis. The return-visit analysis says plainly that admissions after a return visit do not adequately capture deficits in care, and those patients did better, not worse. Returning is common and is not a verdict on anybody. Nothing here gives a probability for this patient, and the reason to look again is that a third examination has not been done.',
    briefIn: ['third-attendance-a-question-two-people-have-already-answered'],
  },
  {
    id: 'deferred-step-presentation-and-team-response-are-authored',
    headline: 'One night shift, one telephone call from theatre, and observations that never move.',
    simplification: 'The case supplies a fixed set of entirely normal observations that never change, one authored slip at 8 minutes in which theatre says the registrar will not be free until half past five, and a team that answers six minutes after it is called and agrees to decide without seeing her. No infection, healing, wound, or pharmacological model runs underneath, no antibiotic is ever given, and no infection is ever confirmed or excluded.',
    whereItMisleads: 'A learner concludes that the review always slips, that whoever is called always answers in minutes, that a decision like this is always given over the telephone, or that asking is what prevented an infection.',
    correctUnderstanding: 'The reply is authored and deliberately generous, so that the lesson is about noticing the attachment rather than about winning an argument; in practice the call may not be answered, the answer may be to wait, and the plan has to survive both. The slip is authored and arrives whether or not anybody was watching for it — and the deferral was already the problem before it happened, which is why the worked example calls first. Nothing the learner does changes her physiology, because nothing was going to.',
    briefIn: ['deferred-step-a-decision-attached-to-a-person'],
  },
  {
    id: 'deferred-step-controls-are-recording-and-escalation-only',
    headline: 'Nothing is prescribed, nothing is given, no dressing is chosen, and no operation is booked.',
    simplification: 'The learner records the injury against the clock the published thresholds use, records the outstanding step as outstanding, records what the interval is attached to, calls the team that can decide and asks for a decision rather than a visit, records bounded qualified-team intent, and reviews the boundaries.',
    whereItMisleads: 'The escalation control is read as the learner prescribing or giving an antibiotic, the refusals are read as criticism of the registrar in theatre, or the morning-chart refusal is read as an objection to written prescribing.',
    correctUnderstanding: 'Whether an antibiotic is given, which one, at what dose and by what route, the wound dressing and any photography, and the debridement and its timing all belong to the qualified team, and this lesson exposes no agent, dose, route, interval, or dressing. Nobody in the case has done anything wrong: the registrar is operating and the board entry is an ordinary sentence. The finding is that a step with a window measured in minutes was attached to a person becoming free, and the refusals object to that attachment rather than to any individual or to the real constraint on theatre time.',
    briefIn: ['deferred-step-a-decision-attached-to-a-person'],
  },
  {
    id: 'deferred-step-two-thresholds-measured-from-two-clocks',
    headline: 'Two retrospective series, two different thresholds, and two different starting points.',
    simplification: 'The lesson quotes an odds ratio of 3.78 (95% CI 1.16-12.31) for deep infection beyond 66 minutes from injury in 137 type III open tibial fractures, with 1 infection in 36 when neither antibiotics nor coverage were delayed against 17 in 42 when both were; a 2.4-fold hazard of surgical site infection beyond 120 minutes from emergency department arrival in 230 open fractures, whose underlying median comparison of 61 against 83 minutes reached only p=0.053; and an older series of 1,104 open fracture wounds with 77 infections naming early antibiotics as the single most important factor without any threshold.',
    whereItMisleads: 'A learner carries either number to the bedside as a deadline, mixes the two clocks by measuring from arrival against the 66-minute figure, or reads the older series as supplying a target it does not report.',
    correctUnderstanding: 'Both modern series are retrospective and single-centre, they define their windows from different moments — one from injury, one from arrival — and they disagree by nearly an hour; the second reports a significant modelled hazard while its own median comparison did not reach significance. The 1989 series reports no threshold at all in its indexed abstract and none is quoted from it. Together they establish only that the interval is not free, which is a reason not to attach it to somebody\u2019s arrival, and not a stopwatch for this patient.',
    briefIn: ['deferred-step-a-decision-attached-to-a-person'],
  },
];
