/**
 * The toxicology module's limitations.
 *
 * Split out of the single register so a module's cockpit chunk carries its own entries and not the
 * other fourteen modules'. An entry is filed here if a toxicology scenario names it through `briefIn`
 * or declares it in its own metadata; a few entries are named by scenarios in two modules and are
 * filed in both. The complete register is assembled in `../limitations.ts`.
 */

import type { Limitation } from './types';

export const TOXICOLOGY_LIMITATIONS: readonly Limitation[] = [
  {
    id: 'methemoglobinemia-exposure-saturation-gap-cooximetry-and-response-are-authored',
    headline: 'The exposure, symptoms, saturation discordance, blood observation, co-oximetry, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, pulse-oximetry acquisition, arterial sampling, blood-gas analysis, co-oximetry, qualified treatment, and reassessment.',
    whereItMisleads: 'Treating benzocaine exposure, SpO2 near 85%, chocolate-brown blood, a saturation gap, methemoglobin percentage, or later improvement as learner evidence, a universal diagnosis, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires direct assessment, verified multiwavelength co-oximetry, exposure and medication review, current toxicology guidance, serial reassessment, and individualized treatment.',
    briefIn: ['methemoglobinemia-saturation-gap'],
  },
  {
    id: 'methemoglobinemia-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, support, hazard review, bounded antidote intent with reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, poison-center, critical-care, nursing, respiratory, laboratory, pharmacy, transfusion, hyperbaric, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with examination, diagnosis, co-oximeter operation, eligibility review, prescribing, treatment delivery, rescue, disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, trained teams, verified serial findings, contraindication and interaction review, current local protocols, individualized treatment, and continuous reassessment.',
    briefIn: ['methemoglobinemia-saturation-gap'],
  },
  {
    id: 'no-live-dyshemoglobin-diagnosis-gas-calculation-antidote-dose-delivery-rescue-or-outcome',
    headline: 'The lab does not examine, diagnose, calculate blood gases, prescribe or deliver an antidote, perform rescue, or report outcome.',
    simplification: 'No live history, examination, monitoring, arterial sample, blood gas, co-oximetry, laboratory or other test, saturation-gap calculation, diagnosis, oxygen selection, methylene-blue product, dose, route, preparation, access or infusion, exchange transfusion, hyperbaric treatment, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Diagnosing from one SpO2 value or gap, copying fictional values into care, overlooking G6PD or serotonergic hazards, treating the fixed response as causality, or reading completion as competence.',
    correctUnderstanding: 'Use direct verified clinical and co-oximetry evidence, poison-center or medical-toxicology guidance, patient-specific contraindication review, qualified treatment and rescue planning, and serial reassessment.',
    briefIn: ['methemoglobinemia-saturation-gap'],
  },
  {
    id: 'carbon-monoxide-exposure-cooximetry-clinical-transition-and-response-are-authored',
    headline: 'The shared exposure, symptoms, conventional pulse oximetry, co-oximetry, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure investigation, pulse-oximetry acquisition, blood sampling, co-oximetry, qualified oxygen, and reassessment.',
    whereItMisleads: 'Treating a generator history, normal SpO2, COHb percentage, syncope, or later improvement as learner evidence, a universal diagnosis, a severity score, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires source safety, direct assessment of every exposed person, verified co-oximetry with elapsed-time context, serial neurologic and cardiac assessment, and individualized treatment.',
    briefIn: ['carbon-monoxide-reassuring-monitor'],
  },
  {
    id: 'carbon-monoxide-controls-reconcile-recognize-support-review-consult-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, recognition, source and patient safety, severity review, selected-patient consultation with reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, poison-center, public-safety, nursing, respiratory, laboratory, cardiology, hyperbaric, transport, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with examination, diagnosis, co-oximeter operation, oxygen delivery, hyperbaric eligibility, transport, treatment, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, verified serial findings, poison-center or medical-toxicology guidance, current local capability, individualized decisions, and continuous reassessment.',
    briefIn: ['carbon-monoxide-reassuring-monitor'],
  },
  {
    id: 'no-live-exposure-diagnosis-cooximetry-oxygen-selection-hyperbaric-eligibility-treatment-or-outcome',
    headline: 'The lab does not investigate an exposure, examine, diagnose, operate co-oximetry, select oxygen or hyperbaric care, transfer, treat, or report outcome.',
    simplification: 'No live history, examination, monitoring, blood sample, co-oximetry, laboratory, ECG, imaging or another test, diagnosis, oxygen interface or setting, drug, route, access, chamber, transport, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using normal SpO2 to exclude poisoning, using one COHb value as a universal severity or hyperbaric threshold, copying fictional values into care, or reading improvement or completion as competence.',
    correctUnderstanding: 'Use direct clinical evidence, verified timed co-oximetry, serial neurologic and cardiac assessment, source control, current specialist guidance, and patient-specific treatment and follow-up planning.',
    briefIn: ['carbon-monoxide-reassuring-monitor'],
  },
  {
    id: 'acetaminophen-exposure-clock-level-nomogram-position-labs-and-response-are-authored',
    headline: 'The product, ingestion clock, concentration, nomogram position, laboratory evidence, qualified care, and later report are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, product reconciliation, timing verification, monitoring, sampling, nomogram plotting, qualified antidote care, safety assessment, and reassessment.',
    whereItMisleads: 'Treating the fictional quantity, 6-hour level, supplied plot, laboratory values, or later improvement as learner evidence, a universal treatment rule, treatment effect, automatic stopping decision, or predicted course.',
    correctUnderstanding: 'Real care requires verified product and timing, direct assessment, poison-center or medical-toxicology guidance, appropriate serial testing, individualized treatment, stopping review, and compassionate safety care.',
    briefIn: ['acetaminophen-clock-and-nomogram'],
  },
  {
    id: 'acetaminophen-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, nomogram-boundary recognition, qualified ownership, evidence review, bounded antidote intent with reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, poison-center, laboratory, pharmacy, nursing, liver-failure, transplant, mental-health, safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, nomogram calculation, diagnosis, decontamination, prescribing, infusion delivery, stopping, safety disposition, or competence.',
    correctUnderstanding: 'Actual care requires the patient, verified timing and serial findings, trained teams, current poison-center and local protocols, individualized treatment, compassionate safety assessment, and continuous reassessment.',
    briefIn: ['acetaminophen-clock-and-nomogram'],
  },
  {
    id: 'no-live-ingestion-assessment-nomogram-calculation-antidote-dose-delivery-stopping-or-outcome',
    headline: 'The lab does not assess a real ingestion, calculate a nomogram, diagnose, prescribe or deliver an antidote, decide stopping, determine safety, or report outcome.',
    simplification: 'No live history, examination, monitoring, blood sample, laboratory or other test, nomogram plotting, diagnosis, charcoal, acetylcysteine product, dose, route, preparation, access or infusion, adverse-reaction management, dialysis, transplant decision, safety disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using a pre-4-hour, unknown-time, repeated, extended-release, delayed-absorption, coingested, or late exposure as if it fit this fixture; copying fictional values into care; stopping by elapsed time alone; or reading completion as competence.',
    correctUnderstanding: 'Use verified product, timing, serial acetaminophen and liver evidence, poison-center or medical-toxicology guidance, patient-specific treatment and stopping criteria, liver-failure escalation, and nonjudgmental safety care.',
    briefIn: ['acetaminophen-clock-and-nomogram'],
  },
  {
    id: 'salicylate-exposure-serial-level-acid-base-clinical-transition-and-response-are-authored',
    headline: 'The exposure, serial concentration, acid-base evidence, clinical transition, qualified care, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, timing and product verification, monitoring, blood gas and chemistry acquisition, qualified alkalinization and dialysis preparation, and reassessment.',
    whereItMisleads: 'Treating the fictional concentration, pH, anion gap, tachypnea, or later deterioration as learner evidence, tissue concentration, a universal severity or dialysis threshold, treatment effect, or predicted course.',
    correctUnderstanding: 'Real care requires verified acute-versus-chronic exposure, product and units, direct serial clinical and laboratory assessment, toxicology and nephrology guidance, and individualized treatment and extracorporeal decisions.',
    briefIn: ['salicylate-falling-number'],
  },
  {
    id: 'salicylate-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, mixed-pattern recognition, qualified ownership, evidence review, bounded alkalinization and dialysis preparedness, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, critical-care, nephrology, laboratory, pharmacy, nursing, respiratory, dialysis, safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with examination, blood-gas calculation, diagnosis, fluid or electrolyte prescribing, airway management, dialysis eligibility or delivery, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, verified serial clinical and laboratory findings, current poison-center and local protocols, patient-specific treatment, and continuous reassessment.',
    briefIn: ['salicylate-falling-number'],
  },
  {
    id: 'no-live-salicylate-diagnosis-gas-calculation-alkalinization-airway-dialysis-or-outcome',
    headline: 'The lab does not assess or diagnose poisoning, calculate a blood gas, prescribe alkalinization, manage an airway, select dialysis, or report outcome.',
    simplification: 'No live history, examination, monitoring, blood gas, chemistry, urine, ECG, imaging or another test, acid-base or anion-gap calculation, diagnosis, charcoal, bicarbonate, potassium, glucose, fluid, dose, route, access, infusion, airway device, ventilation, dialysis, transport, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using one concentration, unit, pH, or anion gap alone; copying fictional values into care; suppressing compensatory ventilation; assigning dialysis from this rehearsal; or reading completion as competence.',
    correctUnderstanding: 'Use the whole serial clinical state with verified concentrations and units, acid-base, CNS, pulmonary, renal, volume, glucose, and electrolyte evidence under toxicology, critical-care, and nephrology ownership.',
    briefIn: ['salicylate-falling-number'],
  },
  {
    id: 'tricyclic-exposure-electrical-perfusion-cns-transition-and-response-are-authored',
    headline: 'The exposure, electrical pattern, perfusion, CNS state, qualified care, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure verification, ECG and laboratory acquisition and interpretation, seizure assessment, qualified resuscitation, and reassessment.',
    whereItMisleads: 'Treating the fictional QRS, aVR finding, hypotension, seizure, anticholinergic clues, or later improvement as learner evidence, a universal diagnosis or severity threshold, treatment effect, durable stability, or predicted course.',
    correctUnderstanding: 'Real care requires direct serial clinical, ECG, perfusion, neurological, acid-base, and electrolyte assessment with poison-center or medical-toxicology and resuscitation-team ownership.',
    briefIn: ['tricyclic-sodium-channel-cardiotoxicity'],
  },
  {
    id: 'tricyclic-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded bicarbonate and rescue intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, critical-care, nursing, pharmacy, airway, seizure, cardiac, perfusion, rescue, safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, ECG interpretation, diagnosis, prescribing, airway or rhythm management, rescue eligibility or delivery, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, continuous verified cardiac and perfusion surveillance, serial neurological and laboratory assessment, current local protocols, individualized treatment, and reassessment.',
    briefIn: ['tricyclic-sodium-channel-cardiotoxicity'],
  },
  {
    id: 'no-live-tricyclic-diagnosis-ecg-interpretation-bicarbonate-airway-rescue-or-outcome',
    headline: 'The lab does not diagnose poisoning, interpret an ECG, prescribe bicarbonate, manage an airway or rhythm, perform rescue, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, blood gas, chemistry or another test, interval or axis calculation, diagnosis, charcoal, bicarbonate, electrolyte, fluid, vasopressor, seizure drug, dose, route, access, infusion, airway, ventilation, shock, pacing, antiarrhythmic, lipid, ECLS, transport, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using one QRS interval or aVR finding alone, copying fictional values into care, selecting an airway or refractory rescue from this rehearsal, attributing the fixed response, or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified exposure, serial ECG, perfusion, CNS, seizure, acid-base, electrolyte, temperature, and coingestion trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['tricyclic-sodium-channel-cardiotoxicity'],
  },
  {
    id: 'beta-blocker-exposure-perfusion-metabolic-prior-care-transition-and-response-are-authored',
    headline: 'The exposure, perfusion and metabolic pattern, prior care, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure verification, ECG, cardiac-function and laboratory acquisition and interpretation, qualified resuscitation, and reassessment.',
    whereItMisleads: 'Treating the fictional pulse, pressure, PR interval, contractility, glucose, prior-care response, or later improvement as learner evidence, a universal diagnostic threshold, treatment effect, durable stability, or predicted course.',
    correctUnderstanding: 'Real care requires direct serial perfusion, rhythm, neurological, glucose, electrolyte, acid-base, volume, and organ assessment with poison-center or medical-toxicology and resuscitation-team ownership.',
    briefIn: ['beta-blocker-cardiogenic-shock'],
  },
  {
    id: 'beta-blocker-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded rescue intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, critical-care, nursing, pharmacy, cardiac, metabolic, airway, perfusion, rescue, safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, ECG or imaging interpretation, diagnosis, prescribing, glucose or electrolyte management, pacing, rescue eligibility or delivery, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, continuous verified cardiac and perfusion surveillance, protocolized glucose, potassium and volume monitoring, current local protocols, individualized treatment, and reassessment.',
    briefIn: ['beta-blocker-cardiogenic-shock'],
  },
  {
    id: 'no-live-beta-blocker-diagnosis-treatment-pacing-dialysis-rescue-or-outcome',
    headline: 'The lab does not diagnose poisoning, prescribe treatment, pace, dialyze, perform rescue, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, cardiac imaging, blood gas, chemistry or another test, diagnosis, decontamination, glucose, electrolyte, fluid, vasopressor, glucagon, insulin, dose, rate, target, route, access, infusion, airway, ventilation, pacing, dialysis, lipid, ECLS, transport, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using one pulse, interval, glucose value, or exposure statement alone; copying fictional values into care; treating pacing as perfusion rescue; selecting a product, dose, dialysis, or extracorporeal rescue from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified product and formulation, serial rhythm, perfusion, contractility, CNS, glucose, electrolyte, acid-base, volume, renal, coingestion, prior-care, and response trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['beta-blocker-cardiogenic-shock'],
  },
  {
    id: 'calcium-channel-blocker-exposure-perfusion-metabolic-prior-care-transition-and-response-are-authored',
    headline: 'The exposure, mixed shock and metabolic pattern, prior care, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure verification, ECG, cardiac-function and laboratory acquisition and interpretation, qualified resuscitation, and reassessment.',
    whereItMisleads: 'Treating the fictional pulse, pressure, AV block, contractility, vascular tone, glucose, prior-care response, or later improvement as learner evidence, a universal diagnostic threshold, treatment effect, completed absorption, durable stability, or predicted course.',
    correctUnderstanding: 'Real care requires direct serial perfusion, rhythm, neurological, glucose, electrolyte, acid-base, volume, and organ assessment with poison-center or medical-toxicology and resuscitation-team ownership.',
    briefIn: ['calcium-channel-blocker-shock'],
  },
  {
    id: 'calcium-channel-blocker-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded rescue intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, critical-care, nursing, pharmacy, cardiac, metabolic, airway, perfusion, rescue, safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, ECG or imaging interpretation, diagnosis, prescribing, glucose or electrolyte management, pacing, decontamination, rescue eligibility or delivery, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, continuous verified cardiac and perfusion surveillance, protocolized glucose, potassium and volume monitoring, current local protocols, individualized treatment, and reassessment through the prolonged-release risk window.',
    briefIn: ['calcium-channel-blocker-shock'],
  },
  {
    id: 'no-live-calcium-channel-blocker-diagnosis-treatment-pacing-decontamination-rescue-or-outcome',
    headline: 'The lab does not diagnose poisoning, prescribe treatment, pace, decontaminate, perform rescue, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, cardiac imaging, blood gas, chemistry or another test, diagnosis, decontamination, glucose, electrolyte, fluid, vasopressor, calcium, insulin, dose, rate, target, route, access, infusion, airway, ventilation, pacing, lipid, methylene blue, ECLS, transport, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using one pulse, interval, glucose value, or exposure statement alone; copying fictional values into care; treating pacing as perfusion rescue; selecting a product, dose, decontamination, or extracorporeal rescue from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified product and formulation, serial rhythm, perfusion, contractility, vascular tone, CNS, glucose, electrolyte, acid-base, volume, renal, coingestion, prior-care, absorption, and response trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['calcium-channel-blocker-shock'],
  },
  {
    id: 'digoxin-exposure-rhythm-potassium-level-prior-care-transition-and-response-are-authored',
    headline: 'The exposure, rhythm-potassium pattern, level timing, prior care, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure verification, ECG, digoxin-level and laboratory acquisition and interpretation, qualified resuscitation, and reassessment.',
    whereItMisleads: 'Treating the fictional rhythm, pressure, potassium, timed level, prior-care response, or later improvement as learner evidence, a universal diagnostic threshold, treatment effect, durable stability, or predicted course.',
    correctUnderstanding: 'Real care requires direct serial perfusion, rhythm, neurological, potassium, magnesium, acid-base, renal, assay, and organ assessment with poison-center or medical-toxicology and resuscitation-team ownership.',
    briefIn: ['digoxin-rhythm-potassium'],
  },
  {
    id: 'digoxin-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded Fab intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, critical-care, nursing, pharmacy, cardiac, electrolyte, airway, perfusion, antidote, rescue, safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, ECG or level interpretation, diagnosis, prescribing, electrolyte management, pacing, antidote or rescue eligibility or delivery, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, continuous verified cardiac and perfusion surveillance, serial potassium and renal monitoring, correctly timed and assay-aware laboratory interpretation, current local protocols, individualized treatment, and reassessment.',
    briefIn: ['digoxin-rhythm-potassium'],
  },
  {
    id: 'no-live-digoxin-diagnosis-fab-dosing-electrolyte-pacing-dialysis-rescue-or-outcome',
    headline: 'The lab does not diagnose poisoning, calculate or deliver Fab, prescribe electrolyte care, pace, dialyze, perform rescue, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, digoxin level, blood gas, chemistry or another test, diagnosis, charcoal, glucose, electrolyte, fluid, Fab, vial count, dose, rate, target, route, access, infusion, airway, ventilation, pacing, dialysis, cardioversion, antiarrhythmic, transport, procedure, disposition, prognosis, or outcome is modeled.',
    whereItMisleads: 'Using one rhythm, potassium, level, or exposure statement alone; copying fictional values into care; using a post-Fab total level as activity; selecting a product, vial count, electrolyte treatment, pacing, dialysis, or rescue from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified product, clock, GI and visual, serial rhythm, perfusion, potassium, magnesium, acid-base, renal, coingestion, sample-timing, assay, prior-care, antidote, and response trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['digoxin-rhythm-potassium'],
  },
  {
    id: 'cholinergic-exposure-respiratory-neuromuscular-cns-decontamination-transition-and-response-are-authored',
    headline: 'The exposure, respiratory, neuromuscular and CNS pattern, decontamination, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure verification, respiratory and neuromuscular assessment, cholinesterase and laboratory acquisition and interpretation, qualified contamination control, care, and reassessment.',
    whereItMisleads: 'Treating fictional wet clothing, secretions, pupil, pulse, gas exchange, fasciculations, weakness, cholinesterase report, decontamination, or later improvement as learner evidence, a universal diagnostic threshold, treatment effect, complete decontamination, durable ventilation, or predicted course.',
    correctUnderstanding: 'Real care requires appropriate PPE, direct serial airway, ventilation, secretion, strength, CNS, exposure, laboratory, co-worker, contamination, and organ assessment with poison-center or medical-toxicology and resuscitation-team ownership.',
    briefIn: ['cholinergic-pesticide-respiratory-failure'],
  },
  {
    id: 'cholinergic-controls-reconcile-recognize-safety-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, safety ownership, evidence review, bounded qualified intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for PPE, contamination, decontamination, emergency, toxicology, critical-care, nursing, pharmacy, airway, respiratory, occupational, co-worker, antidote, seizure, surveillance, safety, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, cholinesterase or gas interpretation, diagnosis, PPE selection, clothing removal, washing, prescribing, airway or seizure management, treatment delivery, disposition, workplace clearance, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, context-appropriate PPE, contamination control, direct airway and ventilation support, current local protocols, individualized antidote and seizure care, serial neuromuscular assessment, and reassessment for recurrence and intermediate syndrome.',
    briefIn: ['cholinergic-pesticide-respiratory-failure'],
  },
  {
    id: 'no-live-cholinergic-diagnosis-decontamination-atropine-pralidoxime-airway-seizure-care-or-outcome',
    headline: 'The lab does not diagnose poisoning, perform decontamination, prescribe antidotes, manage an airway or seizure, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, blood gas, cholinesterase, chemistry or another test, diagnosis, clothing removal, irrigation, decontamination, oxygen, suction, glucose, electrolyte, fluid, atropine, pralidoxime, benzodiazepine, drug, dose, rate, target, route, access, infusion, airway, ventilation, neuromuscular blocker, transport, procedure, disposition, prognosis, workplace clearance, or outcome is modeled.',
    whereItMisleads: 'Using one pupil, pulse, secretion, mnemonic, cholinesterase report, or exposure statement alone; copying fictional values into care; selecting PPE, a washing method, product, dose, airway technique, or seizure treatment from this rehearsal; equating dry secretions with strength recovery; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified product and route, serial airway, ventilation, secretion, bronchospasm, neuromuscular, CNS, seizure, contamination, co-worker, laboratory, antidote, decontamination, prior-care, and response trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['cholinergic-pesticide-respiratory-failure'],
  },
  {
    id: 'anticholinergic-exposure-delirium-hyperthermia-retention-ecg-and-response-are-authored',
    headline: 'The exposure, delirium, hyperthermia, retention, ECG, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure verification, core-temperature measurement, ECG, urinary, renal, CK and laboratory acquisition and interpretation, qualified supportive care, and reassessment.',
    whereItMisleads: 'Treating fictional exposure purity, delirium, pupil, dry skin, temperature, pulse, retention, QRS, CK, cooling, sedation, or later improvement as learner evidence, a universal diagnostic threshold, antidote eligibility, treatment effect, durable cooling, or predicted course.',
    correctUnderstanding: 'Real care requires direct serial airway, mental-state, core-temperature, cardiac, urine, renal, muscle-injury, exposure, coingestion, competing-cause and organ assessment with poison-center or medical-toxicology and resuscitation-team ownership.',
    briefIn: ['anticholinergic-hyperthermia-delirium'],
  },
  {
    id: 'anticholinergic-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, critical-care, nursing, pharmacy, cooling, airway, monitoring, laboratory, renal, bladder, sedation, seizure, antidote, compassionate-safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, core-temperature, ECG or laboratory interpretation, diagnosis, differential exclusion, cooling, restraint, catheterization, prescribing, antidote eligibility or delivery, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, rapid verified cooling and resuscitation, least-restrictive compassionate safety, current local protocols, individualized supportive, agitation, seizure and bladder care, toxicologist-led antidote decisions, and serial reassessment.',
    briefIn: ['anticholinergic-hyperthermia-delirium'],
  },
  {
    id: 'no-live-anticholinergic-diagnosis-cooling-restraint-sedation-physostigmine-bladder-care-or-outcome',
    headline: 'The lab does not diagnose poisoning, cool or restrain a patient, prescribe sedation or physostigmine, manage retention, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, temperature, blood gas, chemistry, CK, urine or another test, diagnosis, differential exclusion, cooling, fluid, restraint, catheter, sedation, physostigmine, drug, dose, rate, target, route, access, infusion, airway, ventilation, transport, procedure, disposition, prognosis, safety decision, or outcome is modeled.',
    whereItMisleads: 'Using one mnemonic, pupil, dry surface, temperature, pulse, ECG interval, laboratory value, or exposure statement alone; copying fictional values into care; selecting a cooling method, restraint, catheter, product, dose, airway, seizure treatment, or antidote from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified product and clock, serial CNS, airway, temperature, sweating, neuromuscular, ECG, urinary, renal, CK, coingestion, exposure-purity, competing-cause, supportive-care and response trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['anticholinergic-hyperthermia-delirium'],
  },
  {
    id: 'serotonin-interaction-mental-autonomic-neuromuscular-hyperthermia-and-response-are-authored',
    headline: 'The interaction, mental, autonomic, neuromuscular, hyperthermia, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, medication reconciliation, core-temperature measurement, ECG, renal, CK and laboratory acquisition and interpretation, qualified supportive care, and reassessment.',
    whereItMisleads: 'Treating fictional interaction completeness, clonus, reflexes, sweating, bowel activity, tone, temperature, pulse, QRS, CK, source cessation, cooling, sedation, or later improvement as learner evidence, a universal diagnostic rule, rescue eligibility, treatment effect, durable cooling, neuromuscular recovery, or predicted course.',
    correctUnderstanding: 'Real care requires direct serial airway, mental-state, core-temperature, autonomic, neuromuscular, cardiac, renal, muscle-injury, exposure, coingestion, competing-cause and organ assessment with poison-center or medical-toxicology and resuscitation-team ownership.',
    briefIn: ['serotonin-toxicity-hyperthermia-clonus'],
  },
  {
    id: 'serotonin-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, critical-care, nursing, pharmacy, cooling, airway, monitoring, laboratory, renal, sedation, seizure, rescue, compassionate-safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, medication reconciliation, Hunter-rule application, temperature, ECG or laboratory interpretation, diagnosis, differential exclusion, cooling, restraint, prescribing, airway care, rescue eligibility or delivery, disposition, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, rapid verified cooling and resuscitation, least-restrictive compassionate safety, current local protocols, individualized source, supportive, agitation and seizure care, specialist rescue decisions, and serial neuromuscular reassessment.',
    briefIn: ['serotonin-toxicity-hyperthermia-clonus'],
  },
  {
    id: 'no-live-serotonin-diagnosis-cooling-sedation-antagonist-airway-seizure-care-or-outcome',
    headline: 'The lab does not diagnose serotonin toxicity, cool or sedate a patient, prescribe an antagonist, manage an airway or seizure, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, temperature, blood gas, chemistry, CK or another test, medication reconciliation, diagnosis, differential exclusion, cooling, fluid, restraint, sedation, cyproheptadine, drug, dose, rate, target, route, access, infusion, airway, ventilation, neuromuscular blocker, transport, procedure, disposition, prognosis, safety decision, or outcome is modeled.',
    whereItMisleads: 'Using one Hunter rule, clonus finding, temperature, pulse, medication list, ECG interval, laboratory value, or interaction statement alone; copying fictional values into care; selecting a cooling method, restraint, sedative, antagonist, airway, neuromuscular blocker, or seizure treatment from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified exposure and clock, serial CNS, autonomic, neuromuscular, airway, temperature, ECG, renal, CK, coingestion, competing-cause, supportive-care and response trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['serotonin-toxicity-hyperthermia-clonus'],
  },
  {
    id: 'sympathomimetic-exposure-mental-autonomic-hyperthermia-and-response-are-authored',
    headline: 'The exposure, mental and autonomic pattern, hyperthermia, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure verification, core-temperature measurement, ECG, toxicology screen, renal, CK and laboratory acquisition and interpretation, qualified supportive care, and reassessment.',
    whereItMisleads: 'Treating fictional exposure purity, behavior, pupils, sweating, temperature, pressure, pulse, QRS, CK, de-escalation, cooling, sedation, or later improvement as learner evidence, a universal diagnostic threshold, adjunct eligibility, treatment effect, durable control, psychiatric or cardiac safety, or predicted course.',
    correctUnderstanding: 'Real care requires direct serial airway, mental-state, psychiatric-safety, core-temperature, autonomic, cardiac, renal, muscle-injury, exposure, coingestion, competing-cause and organ assessment with poison-center or medical-toxicology and resuscitation-team ownership.',
    briefIn: ['sympathomimetic-hyperadrenergic-hyperthermia'],
  },
  {
    id: 'sympathomimetic-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, toxicology, critical-care, nursing, pharmacy, de-escalation, cooling, cardiac, airway, monitoring, laboratory, renal, psychiatric, sedation, seizure, adjunct, compassionate-safety, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, toxicology-screen, temperature, ECG or laboratory interpretation, diagnosis, differential exclusion, restraint, cooling, prescribing, airway care, adjunct eligibility or delivery, disposition, psychiatric safety, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, least-restrictive compassionate de-escalation, rapid verified cooling and resuscitation, current local protocols, individualized agitation, cardiovascular and seizure care, specialist adjunct decisions, and serial medical and psychiatric reassessment.',
    briefIn: ['sympathomimetic-hyperadrenergic-hyperthermia'],
  },
  {
    id: 'no-live-sympathomimetic-diagnosis-restraint-cooling-sedation-cardiovascular-airway-seizure-care-or-outcome',
    headline: 'The lab does not diagnose stimulant toxicity, restrain, cool or sedate a patient, prescribe cardiovascular care, manage an airway or seizure, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, temperature, toxicology screen, blood gas, chemistry, CK or another test, diagnosis, differential exclusion, restraint, cooling, fluid, sedation, antihypertensive, vasodilator, drug, dose, rate, target, route, access, infusion, airway, ventilation, transport, procedure, disposition, prognosis, safety decision, or outcome is modeled.',
    whereItMisleads: 'Using one screen, pupil, pressure, temperature, pulse, behavior, ECG interval, laboratory value, or exposure statement alone; copying fictional values into care; selecting restraint, cooling, sedation, cardiovascular therapy, airway or seizure treatment from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified exposure and clock, serial mental, psychiatric, autonomic, airway, temperature, cardiac, renal, CK, coingestion, competing-cause, supportive-care and response trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['sympathomimetic-hyperadrenergic-hyperthermia'],
  },
  {
    id: 'methanol-exposure-visual-acidosis-gaps-and-response-are-authored',
    headline: 'The methanol source, visual-acidosis pattern, complementary gaps, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, exposure verification, visual and neurologic assessment, blood-gas, chemistry, osmolality, ethanol, renal, ECG, concentration and laboratory acquisition or interpretation, qualified care, and reassessment.',
    whereItMisleads: 'Treating the fictional source, timing, symptom, pH, anion gap, osmolar gap, concentration context, antidote intent, extracorporeal preparation, or later improvement as learner evidence, a diagnostic shortcut, universal threshold, treatment effect, clearance, recovery, or predicted course.',
    correctUnderstanding: 'Real care requires verified serial airway, neurologic, visual, acid-base, osmolar, electrolyte, renal, exposure, coingestion and competing-cause assessment with poison-center or medical-toxicology, critical-care and nephrology ownership.',
    briefIn: ['methanol-visual-acidosis-gaps'],
  },
  {
    id: 'methanol-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, critical-care, nursing, pharmacy, airway, toxicology, laboratory, nephrology or extracorporeal, ophthalmic, antidote, cofactor, acid-base, electrolyte, surveillance, and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, blood-gas or laboratory interpretation, gap calculation, diagnosis, differential exclusion, prescribing, airway care, extracorporeal eligibility or delivery, disposition, recovery, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, current local protocols, verified data, individualized antidote and supportive care, urgent specialist extracorporeal decisions, and serial visual, neurologic, metabolic, renal and airway reassessment.',
    briefIn: ['methanol-visual-acidosis-gaps'],
  },
  {
    id: 'no-live-methanol-diagnosis-calculation-antidote-acid-base-airway-dialysis-or-outcome',
    headline: 'The lab does not diagnose methanol poisoning, calculate a gap, prescribe an antidote, manage acid-base or airway care, select dialysis, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, blood gas, chemistry, osmolality, concentration or another test, calculation, diagnosis, differential exclusion, source control, antidote, cofactor, fluid, buffer, electrolyte, drug, dose, rate, target, route, access, infusion, airway, ventilation, transport, extracorporeal modality, procedure, stopping decision, disposition, prognosis, safety decision, or outcome is modeled.',
    whereItMisleads: 'Using one source, symptom, pH, concentration or gap alone; copying fictional values into care; choosing an antidote, dose, buffer, airway or extracorporeal threshold from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified exposure and clock plus serial visual, neurologic, airway, acid-base, osmolar, electrolyte, renal, coingestion, competing-cause, treatment and response trajectory under qualified toxicology, critical-care and nephrology ownership.',
    briefIn: ['methanol-visual-acidosis-gaps'],
  },
  {
    id: 'delayed-last-source-cns-cardiac-pattern-and-response-are-authored',
    headline: 'The catheter source, delayed CNS-cardiac pattern, and later response are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, source and pump verification, seizure and airway assessment, ECG, blood-gas, electrolyte and laboratory acquisition or interpretation, qualified rescue care, and reassessment.',
    whereItMisleads: 'Treating the fictional catheter, timing, prodrome, seizure, breathing, ECG, perfusion, lipid intent, or later improvement as learner evidence, a universal sequence or threshold, treatment effect, durable seizure or rhythm control, source completeness, recovery, or predicted course.',
    correctUnderstanding: 'Real care requires direct serial source-delivery, airway, neurologic, seizure, rhythm, conduction, perfusion, acid-base, electrolyte, coexposure and competing-cause assessment with qualified toxicology, resuscitation, pharmacy and refractory-rescue ownership.',
    briefIn: ['delayed-local-anesthetic-cns-cardiac-toxicity'],
  },
  {
    id: 'delayed-last-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, critical-care, nursing, pharmacy, source, airway, seizure, cardiac, poison-center or medical-toxicology, lipid, acid-base, surveillance, ECLS and handoff work.',
    whereItMisleads: 'Equating button order with catheter or pump inspection, history, examination, monitoring or test interpretation, diagnosis, prescribing, airway or rhythm care, rescue eligibility or delivery, disposition, recovery, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, immediate verified source control, current local LAST protocols and cognitive aids, individualized airway, seizure, lipid and modified-resuscitation care, refractory rescue, and serial reassessment.',
    briefIn: ['delayed-local-anesthetic-cns-cardiac-toxicity'],
  },
  {
    id: 'no-live-delayed-last-diagnosis-catheter-airway-seizure-lipid-resuscitation-ecls-or-outcome',
    headline: 'The lab does not diagnose LAST, handle a catheter, manage an airway or seizure, dose lipid, perform resuscitation or ECLS, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, blood gas, laboratory or source-delivery test, diagnosis, differential exclusion, catheter, reservoir, pump or line handling, oxygen, ventilation, seizure care, lipid, fluid, buffer, vasopressor, antiarrhythmic, drug, dose, rate, target, route, access, airway, pacing, cardioversion, ECLS, transport, procedure, disposition, prognosis, safety decision, or outcome is modeled.',
    whereItMisleads: 'Using a classic sequence, clock, symptom, seizure, ECG interval, drug record or laboratory value alone; copying fictional values into care; choosing catheter, oxygen, seizure, lipid, cardiac or ECLS treatment from this rehearsal; attributing the fixed response; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified source and clock plus serial CNS, seizure, airway, ECG, perfusion, acid-base, electrolyte, coingestion, competing-cause, treatment and response trajectory under qualified toxicology and resuscitation ownership.',
    briefIn: ['delayed-local-anesthetic-cns-cardiac-toxicity'],
  },
  {
    id: 'opioid-xylazine-exposure-rescue-response-and-coexposure-pattern-are-authored',
    headline: 'The unknown exposure, prehospital rescue, persistent-sedation pattern, and later respiratory report are authored.',
    simplification: 'Fixed reports and canonical monitor states stand in for history, examination, product verification, breathing and airway assessment, ECG, blood-gas, chemistry, toxicology screening, skin review, qualified supportive care, and reassessment.',
    whereItMisleads: 'Treating fictional pupils, wounds, routine screening, naloxone exposure, persistent sedation, cardiovascular depression, or later respiratory improvement as learner evidence, proof of one agent, naloxone resistance, treatment effect, durable recovery, or predicted course.',
    correctUnderstanding: 'Real care requires immediate airway and breathing support plus serial neurologic, respiratory, perfusion, temperature, skin, co-exposure, withdrawal and complication assessment under qualified emergency and toxicology ownership.',
    briefIn: ['opioid-xylazine-persistent-sedation'],
  },
  {
    id: 'opioid-xylazine-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
    headline: 'The controls record reconciliation, pattern recognition, qualified ownership, evidence review, bounded intent, reassessment, and handoff only.',
    simplification: 'Six actions stand in for emergency, airway, respiratory, nursing, monitoring, toxicology, addiction, wound, supportive, surveillance, harm-reduction and handoff work.',
    whereItMisleads: 'Equating button order with history, examination, product identification, monitoring or test interpretation, diagnosis, airway or breathing care, prescribing, wound care, addiction care, disposition, recovery, or competence.',
    correctUnderstanding: 'Actual care requires trained teams, immediate effective ventilation, current opioid-overdose protocols, continued supportive care for persistent effects, individualized complication and withdrawal care, and compassionate addiction and harm-reduction follow-through.',
    briefIn: ['opioid-xylazine-persistent-sedation'],
  },
  {
    id: 'no-live-opioid-xylazine-exam-airway-oxygen-drug-screen-wound-withdrawal-disposition-or-outcome',
    headline: 'The lab does not examine, ventilate, give oxygen or naloxone, identify an adulterant, treat a wound or withdrawal, determine disposition, or report outcome.',
    simplification: 'No live history, examination, monitoring, ECG, blood gas, chemistry, toxicology screening, skin assessment, product identification, diagnosis, differential exclusion, oxygen, ventilation, opioid antagonist, veterinary antagonist, fluid, vasopressor, glucose, rewarming, wound care, drug, dose, rate, target, route, access, airway, transport, procedure, observation, disposition, prognosis, safety decision, or outcome is modeled.',
    whereItMisleads: 'Using pupils, naloxone response, persistent sedation, wounds, routine screening, street-drug context or one vital sign alone; copying fictional values into care; choosing a drug, airway, wound or withdrawal treatment from this rehearsal; attributing the fixed report; or reading completion as competence.',
    correctUnderstanding: 'Use the complete verified exposure and rescue history plus serial breathing, oxygenation, ventilation, neurologic, perfusion, temperature, skin, coingestion, competing-cause, complication, withdrawal, treatment and response trajectory under qualified emergency, toxicology and addiction ownership.',
    briefIn: ['opioid-xylazine-persistent-sedation'],
  },
];
