/** Progressive respiratory failure after initial acute pulmonary edema support. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const ACUTE_PULMONARY_EDEMA_RESPIRATORY_SUPPORT_REASSESSMENT: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'acute-pulmonary-edema-respiratory-support-reassessment', version: '0.1.0', maturity: 'preview',
    title: 'Pulmonary edema support reassessment', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 8, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-ape-initial-care-and-trajectory', statement: 'Reconcile the authored acute pulmonary edema presentation, experienced-team initial care, and serial respiratory trajectory.', measure: 'Delivered care and worsening physiology were reviewed without attributing treatment or examination skill to the learner.' },
      { id: 'review-ape-progressive-respiratory-failure', statement: 'Recognize progressive respiratory failure despite reported noninvasive support from the whole mentation, effort, oxygenation, ventilation, and acid-base pattern.', measure: 'The falling respiratory rate was recognized as fatigue rather than improvement without applying one automatic threshold.' },
      { id: 'review-ape-pressure-perfusion-congestion-and-causes', statement: 'Review pressure, perfusion, persistent congestion, dangerous alternatives, and open precipitants in parallel.', measure: 'Respiratory escalation remained coupled to hemodynamic and cause review without assigning one cause.' },
      { id: 'activate-ape-airway-capable-escalation', statement: 'Activate respiratory, critical-care, and airway-capable experienced help for progressive failure despite noninvasive support.', measure: 'Escalation and rescue readiness were recorded without selecting settings, drugs, an airway procedure, or treatment.' },
      { id: 'handoff-ape-respiratory-support-reassessment', statement: 'After elapsed time, hand off active respiratory failure, current support, hemodynamics, open causes, triggers, and named owners.', measure: 'The handoff preserved unresolved care without inventing a response, disposition, prognosis, or outcome.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'McDonagh TA, Metra M, Adamo M, et al. 2021 ESC Guidelines for the diagnosis and treatment of acute and chronic heart failure. Eur J Heart Fail. 2022;24:4-131.',
        'Rochwerg B, Brochard L, Elliott MW, et al. Official ERS/ATS clinical practice guidelines: noninvasive ventilation for acute respiratory failure. Eur Respir J. 2017;50:1602426.',
      ] },
    limitations: ['ape-support-course-and-failure-evidence-are-authored',
      'ape-support-controls-record-review-escalation-and-handoff-only',
      'no-live-ape-testing-device-treatment-airway-procedure-or-outcome'],
  },
  patient: { ageYears: 69, sex: 'female', heightCm: 164, weightKg: 76, asaClass: 4,
    diagnosis: 'Authored progressive respiratory failure during initial support for acute pulmonary edema',
    procedure: 'Acute pulmonary edema respiratory-support reassessment',
    comorbidities: ['Hypertension', 'Heart failure with preserved ejection fraction'],
    medications: ['Initial syndrome treatment managed by the experienced team'],
    allergies: ['No known drug allergies'], fasting: 'Not established during active emergency care',
    baseline: { heartRateBpm: 104, meanArterialMmHg: 81, strokeVolumeMl: 54,
      hemoglobinGPerDl: 12.6, bloodVolumeMl: 4850, coreTemperatureC: 36.8,
      arterialStiffness: 1.3, baroreflexGain: 0.8, fixedStrokeVolume: false },
    airway: { difficulty: 0.2, difficultMaskVentilation: false,
      assessment: 'Drowsy but rousable, speaking short words, with shallow effort during reported noninvasive support' },
    respiratory: { profile: 'moderately-ill' } },
  equipment: { monitoring: ['ecg', 'nibp', 'capnography', 'pulse-oximetry', 'temperature'],
    airwayDevice: 'facemask', ventilator: { mode: 'pressure-control', fio2: 0.6,
      tidalVolumeMl: 330, respiratoryRateBpm: 12,
      freshGasFlowLPerMin: 15, delivering: true } },
  formulary: [],
  timeline: [
    { id: 'ape-support-initial-course', type: 'narrative',
      target: 'acute-pulmonary-edema-respiratory-support-reassessment', atTick: 0, severity: 'critical',
      message: 'A 69-year-old woman arrived 30 minutes ago with abrupt severe dyspnea, orthopnea, diffuse crackles, elevated jugular venous pressure, HR 118/min, RR 34/min, BP 196/118 mmHg, and pulse-coherent room-air SpO₂ 82%. Fixed ECG, radiograph, and focused-ultrasound reports support a hypertensive acute pulmonary edema pattern without ST elevation, pneumothorax, or pericardial effusion. The experienced team placed her upright, started monitored noninvasive positive-pressure support with titrated oxygen, and delivered loop-diuretic and pressure-appropriate vasodilator therapy. No care was learner-delivered.' },
    { id: 'ape-support-current-failure', type: 'narrative',
      target: 'acute-pulmonary-edema-respiratory-support-reassessment', atTick: 0, severity: 'critical',
      message: 'Thirty minutes later she is drowsy but rousable and speaks only short words. Effort is shallow, RR is 12/min, HR 104/min, BP 108/68 mmHg (MAP 81), and pulse-coherent SpO₂ is 86% during documented noninvasive support in an authored nominal FiO₂ 0.60 condition. A fixed interface-sampling report shows a continuous waveform with EtCO₂ 60 mmHg; fixed blood gas reports pH 7.18, PaCO₂ 68 mmHg, and PaO₂ 58 mmHg. She has a pulse, warm central perfusion, and capillary refill 2 seconds, but diffuse crackles and fixed bilateral edema findings persist. The lower respiratory rate is fatigue, not improvement.' },
    { id: 'ape-support-open-causes', type: 'narrative',
      target: 'acute-pulmonary-edema-respiratory-support-reassessment', atTick: 0, severity: 'warning',
      message: 'Progressive hypoxemic, hypercapnic, acidemic respiratory failure despite reported noninvasive support requires prompt airway-capable escalation. Ischemia, rhythm, acute valve or other mechanical disease, infection, pulmonary embolism, treatment effect, renal and medication factors, and other causes remain open. Current reports do not establish shock, arrest, vomiting, or pneumothorax and do not permanently exclude change.' },
    { id: 'ape-support-boundary', type: 'narrative',
      target: 'acute-pulmonary-edema-respiratory-support-reassessment-boundary', atTick: 0, severity: 'advisory',
      message: 'Reconcile initial care and trajectory; recognize progressive respiratory failure from mentation, effort, oxygenation, ventilation, and acid-base evidence; review pressure, perfusion, congestion, dangerous alternatives, and precipitants; activate respiratory, critical-care, and airway-capable experienced help; then complete a strictly later handoff. The controls do not examine; acquire or interpret monitoring, blood gas, ECG, imaging, or ultrasound data; select or change an oxygen device, flow, FiO₂, interface, mode, pressure, PEEP, or ventilator setting; start or operate noninvasive support; select, dose, titrate, or deliver a drug, fluid, oxygen, ventilation, or treatment; intubate or perform an airway procedure; determine disposition, prognosis, response, resolution, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'ape-support-trajectory', objectiveId: 'reconcile-ape-initial-care-and-trajectory', question: 'Which arrival, delivered-care, and current facts established the respiratory trajectory?' },
    { id: 'ape-support-failure', objectiveId: 'review-ape-progressive-respiratory-failure', question: 'Which mentation, effort, oxygenation, ventilation, and acid-base findings show progressive failure rather than improvement?' },
    { id: 'ape-support-whole-patient', objectiveId: 'review-ape-pressure-perfusion-congestion-and-causes', question: 'Which pressure, perfusion, congestion, alternative, and precipitant questions remained active?' },
    { id: 'ape-support-escalation', objectiveId: 'activate-ape-airway-capable-escalation', question: 'Which experienced teams and rescue capabilities were needed without choosing settings, drugs, or an airway procedure?' },
    { id: 'ape-support-handoff', objectiveId: 'handoff-ape-respiratory-support-reassessment', question: 'Which failure evidence, support, hemodynamics, causes, triggers, and owners remained active at handoff?' },
  ] },
};
