/** Chronic prescribed-opioid exposure with authored sleep-related hypoventilation evidence. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const CHRONIC_OPIOID_RELATED_HYPOVENTILATION_REASSESSMENT: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'chronic-opioid-related-hypoventilation-reassessment', version: '0.1.0', maturity: 'draft',
    title: 'Chronic opioid-related hypoventilation', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 8, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-chronic-opioid-related-hypoventilation-exposure-and-trajectory', statement: 'Reconcile the authored chronic prescribed-opioid exposure, sleep symptoms, daytime function, breathing, oxygenation, and perfusion.', measure: 'The longitudinal pattern was recognized without recasting a stable clinic visit as acute overdose or proving opioid-only causality.' },
      { id: 'review-chronic-opioid-related-hypoventilation-awake-and-sleep-evidence', statement: 'Review the fixed awake and attended sleep-study reports, including carbon-dioxide monitoring.', measure: 'Sustained sleep-related hypoventilation evidence was separated from a quiet awake snapshot without acquiring, scoring, or interpreting the study.' },
      { id: 'review-chronic-opioid-related-hypoventilation-contributors-and-alternatives', statement: 'Review medication, sleep, pulmonary, neurologic, chest-wall, cardiac, endocrine, and other contributors.', measure: 'Chronic opioid exposure remained an important contributor while co-sedatives, obstructive and central events, and nonopioid causes stayed open.' },
      { id: 'coordinate-chronic-opioid-related-hypoventilation-prescriber-sleep-and-respiratory-plan', statement: 'Coordinate patient-centered prescriber, sleep, respiratory, pharmacy, and primary-care ownership.', measure: 'The plan preserved pain goals, medication safety, diagnostic ownership, education, and reassessment without choosing a drug, dose, taper, naloxone intervention, device, mode, or setting.' },
      { id: 'handoff-chronic-opioid-related-hypoventilation-reassessment', statement: 'After elapsed time, hand off the fixed evidence, open contributors, safety concerns, pending work, and named owners.', measure: 'The handoff preserved uncertainty and continuity without inventing diagnosis, treatment response, disposition, prognosis, or outcome.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'Rosen IM, Aurora RN, Kirsch DB, et al. Chronic opioid therapy and sleep: an American Academy of Sleep Medicine position statement. J Clin Sleep Med. 2019;15:1671-1673.',
        'Kapur VK, Auckley DH, Chowdhuri S, et al. Clinical practice guideline for diagnostic testing for adult obstructive sleep apnea. J Clin Sleep Med. 2017;13:479-504.',
        'Dowell D, Ragan KR, Jones CM, Baldwin GT, Chou R. CDC clinical practice guideline for prescribing opioids for pain — United States, 2022. MMWR Recomm Rep. 2022;71:1-95.',
      ] },
    limitations: ['chronic-opioid-hypoventilation-exposure-and-sleep-reports-are-authored',
      'chronic-opioid-hypoventilation-controls-review-and-coordinate-only',
      'no-live-study-interpretation-diagnosis-opioid-change-pap-selection-treatment-or-outcome'],
  },
  patient: { ageYears: 61, sex: 'female', heightCm: 168, weightKg: 67, asaClass: 3,
    diagnosis: 'Authored chronic prescribed-opioid exposure with sleep-related hypoventilation working pattern',
    procedure: 'Chronic opioid-related sleep and breathing reassessment',
    comorbidities: ['Chronic noncancer pain'],
    medications: ['Long-term prescribed extended-release opioid', 'Nighttime gabapentin'],
    allergies: ['No known drug allergies'], fasting: 'Not relevant to this outpatient respiratory reassessment',
    baseline: { heartRateBpm: 76, meanArterialMmHg: 91, strokeVolumeMl: 67,
      hemoglobinGPerDl: 12.8, bloodVolumeMl: 4400, coreTemperatureC: 36.7,
      arterialStiffness: 1.0, baroreflexGain: 1.0, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Alert, speaking comfortably, with no artificial airway or acute upper-airway concern' },
    respiratory: { profile: 'moderately-ill' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'],
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 430,
      respiratoryRateBpm: 10, freshGasFlowLPerMin: 0.5, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'chronic-opioid-hypoventilation-presentation', type: 'narrative',
      target: 'chronic-opioid-related-hypoventilation-reassessment', atTick: 0, severity: 'advisory',
      message: 'A 61-year-old woman is seen in a respiratory and sleep clinic after 8 years of prescribed opioid therapy for chronic noncancer pain. Over 6 months her partner has noticed shallow, irregular breathing during sleep; she reports morning headaches, unrefreshing sleep, and increasing daytime sleepiness. She is alert and comfortable with HR 76/min, RR 10/min, BP 124/74 mmHg (MAP 91), pulse-coherent room-air SpO₂ 94%, warm extremities, and full-sentence speech. There is no authored recent dose escalation, illicit exposure, postoperative recovery, acute intoxication, rescue reversal, hemodynamic instability, or immediate ventilatory failure. The quiet daytime snapshot does not exclude sleep-related ventilatory impairment.' },
    { id: 'chronic-opioid-hypoventilation-evidence', type: 'narrative',
      target: 'chronic-opioid-related-hypoventilation-reassessment', atTick: 0, severity: 'warning',
      message: 'Fixed experienced-team reports show an awake room-air blood gas with pH 7.39, PaCO₂ 44 mmHg, PaO₂ 76 mmHg, and bicarbonate 26 mmol/L. An attended polysomnogram with transcutaneous carbon-dioxide monitoring documents a rise from 46 mmHg awake to 58 mmHg during sleep, sustained for 24 minutes, with associated oxygen desaturation and separately reported intermittent central and obstructive events. The sleep specialist records a sleep-related hypoventilation pattern requiring integrated review. The learner does not acquire, score, or interpret the blood gas or sleep study, and one awake SpO₂ does not rule out nocturnal hypoventilation.' },
    { id: 'chronic-opioid-hypoventilation-contributors', type: 'narrative',
      target: 'chronic-opioid-related-hypoventilation-reassessment', atTick: 0, severity: 'advisory',
      message: 'Medication reconciliation confirms stable long-term prescribed opioid use and nighttime gabapentin; alcohol, nonprescribed substances, and other sedatives still require patient-centered review. BMI is 23.7 kg/m². Fixed office spirometry shows no obstructive ventilatory defect, and the authored examination report shows no focal weakness, but obesity, upper-airway obstruction, central sleep apnea, chronic lung disease, neuromuscular or chest-wall disease, cardiac disease, endocrine causes, medication interactions, and other contributors are not permanently excluded. Chronic opioid exposure is an important contributor, not proof of a single cause.' },
    { id: 'chronic-opioid-hypoventilation-boundary', type: 'narrative',
      target: 'chronic-opioid-related-hypoventilation-reassessment-boundary', atTick: 0, severity: 'advisory',
      message: 'Reconcile exposure, symptoms, daytime state, and safety; review the fixed awake and attended sleep evidence; review contributors and alternatives in either order; then coordinate prescriber, sleep, respiratory, pharmacy, and primary-care ownership around pain goals, medication safety, education, diagnostic work, and reassessment. After a strictly later engine tick, hand off the evidence, open contributors, safety concerns, pending work, and owners. The controls do not examine; acquire, score, or interpret a blood gas, sleep study, capnography, oximetry, spirometry, or another test; diagnose hypoventilation, central or obstructive sleep apnea, or a cause; calculate morphine equivalents; choose, stop, substitute, or taper a drug; select or deliver naloxone, oxygen, positive-airway-pressure mode or settings, ventilation, or treatment; determine disposition or prognosis; or predict response or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'chronic-opioid-hypoventilation-trajectory', objectiveId: 'reconcile-chronic-opioid-related-hypoventilation-exposure-and-trajectory', question: 'Which exposure, sleep, daytime-function, breathing, oxygenation, and perfusion facts established the longitudinal concern without creating an acute overdose?' },
    { id: 'chronic-opioid-hypoventilation-evidence', objectiveId: 'review-chronic-opioid-related-hypoventilation-awake-and-sleep-evidence', question: 'How did the fixed awake and attended sleep reports reveal a problem that one daytime SpO₂ could miss?' },
    { id: 'chronic-opioid-hypoventilation-alternatives', objectiveId: 'review-chronic-opioid-related-hypoventilation-contributors-and-alternatives', question: 'Which medication, sleep, pulmonary, neurologic, chest-wall, cardiac, endocrine, and other contributors remained open?' },
    { id: 'chronic-opioid-hypoventilation-plan', objectiveId: 'coordinate-chronic-opioid-related-hypoventilation-prescriber-sleep-and-respiratory-plan', question: 'How did shared ownership protect pain goals and respiratory safety without selecting a taper, reversal, or device?' },
    { id: 'chronic-opioid-hypoventilation-handoff', objectiveId: 'handoff-chronic-opioid-related-hypoventilation-reassessment', question: 'Which evidence, contributors, safety questions, pending work, and owners remained active?' },
  ] },
};
