/** COPD exacerbation recovery-versus-readiness transition reassessment. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const COPD_EXACERBATION_TRANSITION_REASSESSMENT: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'copd-exacerbation-transition-reassessment', version: '0.1.0', maturity: 'preview',
    title: 'COPD exacerbation: recovery and transition reassessment', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 8, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-copd-exacerbation-recovery-and-readiness', statement: 'Reconcile verified hospital treatment with baseline, admission, and current symptoms, physiology, function, and support.', measure: 'Improvement was separated from readiness, and prior care was not attributed to the learner.' },
      { id: 'review-copd-exacerbation-residual-respiratory-and-oxygen-needs', statement: 'Review residual resting and exertional respiratory and oxygen uncertainty without declaring long-term oxygen eligibility.', measure: 'The authored rest, activity, recovery, and blood-gas reports remained inputs to later reassessment rather than a prescription.' },
      { id: 'review-copd-exacerbation-maintenance-and-acute-medication-plan', statement: 'Review maintenance treatment, technique-correction ownership, and acute-course boundaries without selecting a regimen.', measure: 'Medication reconciliation preserved patient-specific review without choosing an inhaler, device, drug, dose, or duration.' },
      { id: 'coordinate-copd-exacerbation-rehabilitation-self-management-and-follow-up', statement: 'Coordinate pulmonary rehabilitation, self-management teaching, comorbidity review, and early and later follow-up ownership.', measure: 'The plan recorded referrals and owners without guaranteeing access, enrollment, attendance, or outcome.' },
      { id: 'handoff-copd-exacerbation-transition-reassessment', statement: 'After elapsed time, hand off unresolved respiratory, functional, medication, rehabilitation, and follow-up work.', measure: 'The handoff preserved recovery uncertainty and named owners without determining discharge, prognosis, or outcome.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'Global Initiative for Chronic Obstructive Lung Disease. Global Strategy for Prevention, Diagnosis and Management of COPD: 2026 Report. Version 1.3; Chapter 4, Figure 4.10; pp. 108-110.',
        'Rochester CL, Alison JA, Carlin B, et al. Pulmonary Rehabilitation for Adults with Chronic Respiratory Disease: An Official American Thoracic Society Clinical Practice Guideline. Am J Respir Crit Care Med. 2023;208:e7-e26.',
      ] },
    limitations: ['copd-transition-baseline-treatment-tests-and-function-are-authored',
      'copd-transition-controls-record-review-coordination-and-handoff-only',
      'no-live-copd-transition-testing-treatment-prescribing-discharge-or-outcome'],
  },
  patient: { ageYears: 72, sex: 'female', heightCm: 163, weightKg: 66, asaClass: 4,
    diagnosis: 'Authored improving COPD exacerbation with unresolved transition needs',
    procedure: 'Hospital-day-3 COPD recovery-versus-readiness transition reassessment',
    comorbidities: ['COPD with one prior exacerbation admission', 'Former tobacco smoking'],
    medications: ['Tiotropium inhaler', 'Salbutamol inhaler as needed'],
    allergies: ['No known drug allergies'], fasting: 'Not relevant to this transition reassessment',
    baseline: { heartRateBpm: 88, meanArterialMmHg: 91, strokeVolumeMl: 64,
      hemoglobinGPerDl: 14.4, bloodVolumeMl: 4600, coreTemperatureC: 36.8,
      arterialStiffness: 1.15, baroreflexGain: 0.9, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Alert, speaking full sentences, and breathing without acute upper-airway concern' },
    respiratory: { profile: 'moderately-ill' } },
  equipment: { monitoring: ['ecg', 'nibp', 'capnography', 'pulse-oximetry', 'temperature'],
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 430,
      respiratoryRateBpm: 20, freshGasFlowLPerMin: 0.5, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'copd-transition-obstruction', type: 'obstruction', value: 0.55,
      durationTicks: 36000, atTick: 0, severity: 'advisory',
      message: 'A generic residual lower-airway-obstruction waveform cue is active for this authored COPD state. Its shape supports pattern rehearsal but is not a quantitative measurement, examination, or patient-specific capnography model.' },
    { id: 'copd-transition-presentation', type: 'narrative',
      target: 'copd-exacerbation-transition-reassessment', atTick: 0, severity: 'warning',
      message: 'A 72-year-old woman with established COPD was independent before admission, walked about 200 m, had resting room-air SpO₂ 92%, and did not use home oxygen. She arrived with increased dyspnea and purulent sputum, HR 112/min, RR 32/min, room-air SpO₂ 84%, pH 7.29, PaCO₂ 66 mmHg, and PaO₂ 50 mmHg. A fixed chest-radiograph report showed hyperinflation without focal opacity, pulmonary-edema pattern, or pneumothorax. The verified experienced-team record includes controlled oxygen, inhaled short-acting bronchodilator plus antimuscarinic therapy, systemic corticosteroid, antibiotic treatment for the authored indication, and 12 hours of noninvasive ventilation. None was learner-delivered.' },
    { id: 'copd-transition-current', type: 'narrative',
      target: 'copd-exacerbation-transition-reassessment', atTick: 0, severity: 'warning',
      message: 'On hospital day 3, after 24 hours off noninvasive ventilation, she is alert and speaks full sentences with HR 88/min, RR 20/min, BP 126/74 mmHg (MAP 91), temperature 36.8°C, room-air SpO₂ 91%, pH 7.38, PaCO₂ 54 mmHg, and PaO₂ 62 mmHg. During a fixed respiratory-therapy corridor assessment she pauses after 30 m with marked dyspnea; SpO₂ falls to 86% and returns to 91% after 3 minutes at rest. Symptoms and gas exchange improved, but function and oxygen needs have not returned to the documented baseline. This acute snapshot does not establish long-term oxygen eligibility.' },
    { id: 'copd-transition-open-work', type: 'narrative',
      target: 'copd-exacerbation-transition-reassessment', atTick: 0, severity: 'advisory',
      message: 'Medication reconciliation shows preadmission tiotropium plus rescue salbutamol, no finalized maintenance transition plan, and unresolved end points for the acute corticosteroid and antibiotic courses. An experienced respiratory therapist reports important inhaler-technique errors; the learner does not perform or grade technique. Pulmonary rehabilitation, self-management planning, comorbidity review, and early and later respiratory follow-up remain unarranged. Access, appointment timing, and local oxygen-reassessment pathways are not guaranteed.' },
    { id: 'copd-transition-boundary', type: 'narrative',
      target: 'copd-exacerbation-transition-reassessment-boundary', atTick: 0, severity: 'advisory',
      message: 'Reconcile recovery versus readiness; review residual respiratory, functional, and oxygen uncertainty; review medication and technique-correction ownership; and coordinate rehabilitation, self-management, comorbidity review, and follow-up. After a strictly later engine tick, hand off unresolved work and named owners. The controls do not examine; acquire or interpret blood gas, oximetry, imaging, spirometry, or exercise testing; deliver oxygen, medication, noninvasive ventilation, or treatment; select oxygen flow or qualification, a long-term oxygen prescription, inhaler class or device, drug, dose, or duration; perform or score inhaler technique; enroll the patient in rehabilitation; guarantee appointments; determine home safety, discharge readiness, disposition, prognosis, readmission risk, recovery, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'copd-transition-readiness', objectiveId: 'reconcile-copd-exacerbation-recovery-and-readiness', question: 'Which baseline, admission, treatment, current, and functional findings separated improvement from readiness?' },
    { id: 'copd-transition-respiratory-needs', objectiveId: 'review-copd-exacerbation-residual-respiratory-and-oxygen-needs', question: 'Which rest, activity, recovery, and gas findings remained unresolved without proving long-term oxygen eligibility?' },
    { id: 'copd-transition-medications', objectiveId: 'review-copd-exacerbation-maintenance-and-acute-medication-plan', question: 'Which maintenance, technique, and acute-course questions needed ownership without prescribing a regimen?' },
    { id: 'copd-transition-coordination', objectiveId: 'coordinate-copd-exacerbation-rehabilitation-self-management-and-follow-up', question: 'Which rehabilitation, teaching, comorbidity, and follow-up work needed coordination?' },
    { id: 'copd-transition-handoff', objectiveId: 'handoff-copd-exacerbation-transition-reassessment', question: 'Which respiratory, functional, medication, rehabilitation, and follow-up uncertainties remained active at handoff?' },
  ] },
};
