/** Symptomatic large unilateral pleural effusion with authored aspiration response. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const LARGE_UNILATERAL_PLEURAL_EFFUSION_REASSESSMENT: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'large-unilateral-pleural-effusion-reassessment', version: '0.1.0', maturity: 'draft',
    title: 'Large unilateral pleural effusion', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 9, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-large-unilateral-pleural-effusion-trajectory', statement: 'Reconcile the authored symptom trajectory, current safety, unilateral examination claims, and fixed imaging pattern.', measure: 'The large unilateral effusion was held beside breathing and perfusion without making size alone an emergency threshold or granting examination or imaging skill.' },
      { id: 'record-large-unilateral-pleural-effusion-pleural-team-and-drainage-intent', statement: 'Record experienced pleural-team, image-guided diagnostic-sampling, and slow symptom-relief aspiration intent.', measure: 'The plan was symptom limited and carried stop triggers without selecting a site, device, technique, rate, or target volume.' },
      { id: 'review-large-unilateral-pleural-effusion-drainage-response', statement: 'After elapsed time, review the authored aspiration checkpoint and stop at new symptoms.', measure: 'Cough and chest tightness outranked a volume target, and improvement did not become proof of cause, complete drainage, or durable response.' },
      { id: 'review-large-unilateral-pleural-effusion-fluid-pattern-and-causes', statement: 'Review the fixed paired-fluid classification while preserving the broad cause differential and pending results.', measure: 'The authored exudative pattern informed evaluation without learner calculation or a malignant, infectious, or other etiologic diagnosis.' },
      { id: 'coordinate-large-unilateral-pleural-effusion-definitive-evaluation', statement: 'Coordinate result ownership and individualized pleural evaluation for the unresolved unilateral effusion.', measure: 'Qualified evaluation was connected without choosing biopsy, bronchoscopy, an indwelling catheter, pleurodesis, surgery, or cause-specific treatment.' },
      { id: 'handoff-large-unilateral-pleural-effusion-reassessment', statement: 'After elapsed time, hand off response, residual effusion, open causes, pending results, complications, recurrence questions, and named owners.', measure: 'The handoff preserved unresolved work without inventing diagnosis, disposition, prognosis, recurrence, or outcome.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'Roberts ME, Rahman NM, Maskell NA, et al. British Thoracic Society Guideline for pleural disease. Thorax. 2023;78(Suppl 3):s1-s42.',
        'Asciak R, Bedawi EO, Bhatnagar R, et al. British Thoracic Society Clinical Statement on pleural procedures. Thorax. 2023;78(Suppl 3):s43-s68.',
      ] },
    limitations: ['large-effusion-presentation-imaging-fluid-and-response-are-authored',
      'large-effusion-controls-record-review-intent-ownership-and-handoff-only',
      'no-live-pleural-testing-calculation-procedure-treatment-diagnosis-or-outcome'],
  },
  patient: { ageYears: 63, sex: 'female', heightCm: 165, weightKg: 68, asaClass: 3,
    diagnosis: 'Authored symptomatic large undiagnosed left pleural effusion',
    procedure: 'Large unilateral pleural-effusion reassessment',
    comorbidities: ['Hypertension'], medications: ['Amlodipine'],
    allergies: ['No known drug allergies'], fasting: 'Not relevant to this acute respiratory assessment',
    baseline: { heartRateBpm: 104, meanArterialMmHg: 93, strokeVolumeMl: 61,
      hemoglobinGPerDl: 12.4, bloodVolumeMl: 4450, coreTemperatureC: 36.8,
      arterialStiffness: 1.1, baroreflexGain: 0.95, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Alert, speaking full sentences, with no acute upper-airway concern' },
    respiratory: { profile: 'moderately-ill' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'],
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 390,
      respiratoryRateBpm: 26, freshGasFlowLPerMin: 0.5, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'large-effusion-presentation', type: 'narrative',
      target: 'large-unilateral-pleural-effusion-reassessment', atTick: 0, severity: 'warning',
      message: 'A 63-year-old woman reports 6 weeks of progressive exertional dyspnea, dry cough, and left chest heaviness and is now breathless walking across a room. The fixed current report gives alert full-sentence speech, HR 104/min, RR 26/min, BP 128/76 mmHg (MAP 93), pulse-coherent room-air SpO₂ 91%, warm extremities, and capillary refill 2 seconds. Left chest movement and basal air entry are markedly reduced while right air entry is present. There is no authored shock, tension physiology, fever, purulent sputum, diffuse pulmonary-edema pattern, acute respiratory fatigue, recent trauma, or recent pleural procedure; these snapshots do not permanently exclude change or another cause.' },
    { id: 'large-effusion-imaging', type: 'narrative',
      target: 'large-unilateral-pleural-effusion-reassessment', atTick: 0, severity: 'warning',
      message: 'A fixed radiograph report shows a large left pleural effusion occupying about two-thirds of the hemithorax with adjacent compressive atelectatic change, no pneumothorax, no contralateral effusion, and no marked mediastinal shift. A fixed thoracic-ultrasound report in the intended procedure position shows a large predominantly free-flowing collection, no dense septation or definite pleural nodularity, and a suitable image-guided access window identified by an experienced operator. Imaging appearance and size do not establish urgency, safety, malignancy, infection, or another cause by themselves.' },
    { id: 'large-effusion-later-report', type: 'narrative',
      target: 'large-unilateral-pleural-effusion-reassessment', atTick: 0, severity: 'advisory',
      message: 'Only after qualified image-guided aspiration intent and elapsed time may the fixed experienced-team checkpoint be reviewed: 850 mL amber fluid was removed slowly, and drainage stopped when persistent cough and mild chest tightness developed. The 850 mL is a case fact, not a target or maximum. HR is 92/min, RR 20/min, BP 124/74 mmHg (MAP 91), room-air SpO₂ 95%, and dyspnea and heaviness are improved. A fixed radiograph reports a smaller residual effusion and improved left-lung expansion without pneumothorax or a re-expansion-pulmonary-edema pattern. This does not prove complete drainage, cause, durable response, recurrence risk, or outcome.' },
    { id: 'large-effusion-fluid-report', type: 'narrative',
      target: 'large-unilateral-pleural-effusion-reassessment', atTick: 0, severity: 'advisory',
      message: 'The fixed experienced laboratory and pleural-team report classifies the paired sample as exudative: pleural protein 4.2 g/dL with serum protein 6.8 g/dL, pleural LDH 310 U/L with serum LDH 420 U/L, pleural pH 7.39, glucose 92 mg/dL, and a lymphocyte-predominant differential. The learner does not acquire, calculate, or interpret these data. Cytology, microbiology, and selected cause-directed studies remain pending. The pattern does not diagnose malignancy, tuberculosis, pulmonary embolism, autoimmune disease, infection, or another cause.' },
    { id: 'large-effusion-boundary', type: 'narrative',
      target: 'large-unilateral-pleural-effusion-reassessment-boundary', atTick: 0, severity: 'advisory',
      message: 'Reconcile breathing, perfusion, examination claims, and imaging; record qualified pleural-team, image-guided diagnostic and slow symptom-relief aspiration intent with symptom-led stop triggers and no target volume; after elapsed time review the authored checkpoint; review the fixed paired-fluid classification and open causes; coordinate pending-result and definitive-evaluation ownership; then complete a strictly later handoff. The controls do not examine; acquire or interpret monitoring, radiograph, CT, ultrasound, laboratory, cytology, microbiology, or pleural-fluid data; calculate criteria; diagnose; select a site, needle, catheter, drain, bottle, suction, clamp, volume, rate, oxygen device, drug, dose, biopsy, bronchoscopy, indwelling catheter, pleurodesis, thoracoscopy, surgery, systemic therapy, or treatment; aspirate or perform a procedure; determine disposition or prognosis; or predict recurrence, durable benefit, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'large-effusion-trajectory', objectiveId: 'reconcile-large-unilateral-pleural-effusion-trajectory', question: 'Which symptom, breathing, perfusion, unilateral, and imaging facts established the pattern and urgency?' },
    { id: 'large-effusion-intent', objectiveId: 'record-large-unilateral-pleural-effusion-pleural-team-and-drainage-intent', question: 'How did the plan preserve image guidance, slow symptom-limited drainage, diagnostic sampling, and experienced ownership without teaching a procedure?' },
    { id: 'large-effusion-response', objectiveId: 'review-large-unilateral-pleural-effusion-drainage-response', question: 'Why did cough and chest tightness prompt stopping, and what did improvement not prove?' },
    { id: 'large-effusion-fluid', objectiveId: 'review-large-unilateral-pleural-effusion-fluid-pattern-and-causes', question: 'What did the authored paired-fluid classification add, and which causes and results remained open?' },
    { id: 'large-effusion-evaluation', objectiveId: 'coordinate-large-unilateral-pleural-effusion-definitive-evaluation', question: 'Which results and specialist-evaluation work needed named owners without choosing a procedure or cause-specific treatment?' },
    { id: 'large-effusion-handoff', objectiveId: 'handoff-large-unilateral-pleural-effusion-reassessment', question: 'Which response, residual disease, causes, results, complications, recurrence questions, and owners remained active?' },
  ] },
};
