/** Motor neuron disease with authored progressive respiratory-muscle failure evidence. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const NEUROMUSCULAR_RESPIRATORY_FAILURE_REASSESSMENT: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'neuromuscular-respiratory-failure-reassessment', version: '0.1.0', maturity: 'preview',
    title: 'Neuromuscular respiratory failure', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 9, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-neuromuscular-respiratory-failure-trajectory', statement: 'Reconcile the authored functional baseline, symptom progression, breathing, cough, bulbar, gas-exchange, and perfusion trajectory.', measure: 'Serial whole-patient change was recognized without granting examination or respiratory-test skill.' },
      { id: 'recognize-neuromuscular-respiratory-failure', statement: 'Recognize the authored progressive neuromuscular ventilatory-failure pattern without relying on oxygen saturation or one mechanics cutoff.', measure: 'Orthopnea, sleep and daytime symptoms, shallow breathing, supine paradox, hypercapnia, and serial respiratory-muscle decline were integrated.' },
      { id: 'activate-neuromuscular-respiratory-failure-escalation', statement: 'Activate experienced respiratory-ventilation, critical-care, and airway-capable evaluation without waiting for complete cause review.', measure: 'Persistent ventilation, cough, secretion, and bulbar risk received urgent ownership without selecting oxygen, a support device, settings, or an airway procedure.' },
      { id: 'review-neuromuscular-respiratory-failure-bulbar-cough-and-alternatives', statement: 'Review cough, secretion and bulbar safety, test reliability, deterioration triggers, and open neuromuscular and nonneuromuscular contributors.', measure: 'The motor neuron disease trajectory remained central while infection, aspiration, lung, cardiac, metabolic, medication, central, and measurement alternatives stayed open.' },
      { id: 'coordinate-neuromuscular-respiratory-failure-goals-and-ownership', statement: 'Coordinate patient-centered respiratory, neurology, speech and swallowing, nutrition, physiotherapy, nursing, primary-care, and caregiver ownership.', measure: 'Communication, preferences, symptom goals, respiratory-support and secretion-management evaluation, and follow-up were preserved without choosing a device, technique, procedure, treatment, or outcome.' },
      { id: 'handoff-neuromuscular-respiratory-failure-reassessment', statement: 'After elapsed time, hand off the trajectory, current evidence, active risks, open causes, patient priorities, pending work, triggers, and named owners.', measure: 'The handoff preserved urgent unresolved work without inventing diagnosis, treatment response, disposition, prognosis, or outcome.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'Khan A, Frazer-Green L, Amin R, et al. Respiratory Management of Patients With Neuromuscular Weakness: An American College of Chest Physicians Clinical Practice Guideline and Expert Panel Report. Chest. 2023;164:394-413.',
        'National Institute for Health and Care Excellence. Motor neurone disease: assessment and management. NICE guideline NG42. Updated 2019.',
      ] },
    limitations: ['neuromuscular-respiratory-failure-presentation-tests-and-trends-are-authored',
      'neuromuscular-respiratory-failure-controls-review-escalate-coordinate-and-handoff-only',
      'no-live-mechanics-bulbar-cough-testing-device-selection-treatment-procedure-or-outcome'],
  },
  patient: { ageYears: 58, sex: 'male', heightCm: 178, weightKg: 72, asaClass: 4,
    diagnosis: 'Authored motor neuron disease with progressive neuromuscular ventilatory-failure pattern',
    procedure: 'Neuromuscular respiratory-failure reassessment',
    comorbidities: ['Established amyotrophic lateral sclerosis with mild bulbar symptoms'],
    medications: ['Usual medication regimen not represented'], allergies: ['No known drug allergies'],
    fasting: 'Not relevant to this urgent respiratory reassessment',
    baseline: { heartRateBpm: 96, meanArterialMmHg: 91, strokeVolumeMl: 63,
      hemoglobinGPerDl: 13.4, bloodVolumeMl: 4700, coreTemperatureC: 36.8,
      arterialStiffness: 1.0, baroreflexGain: 0.95, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Alert with mild dysarthria, weak cough, and no artificial airway or acute upper-airway obstruction claim' },
    respiratory: { profile: 'moderately-ill' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'],
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 340,
      respiratoryRateBpm: 24, freshGasFlowLPerMin: 0.5, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'neuromuscular-respiratory-failure-presentation', type: 'narrative',
      target: 'neuromuscular-respiratory-failure-reassessment', atTick: 0, severity: 'warning',
      message: 'A 58-year-old man with established amyotrophic lateral sclerosis has lost walking endurance and cough strength over 3 months. During the last 2 weeks he has developed orthopnea, fragmented sleep, morning headaches, daytime sleepiness, breathlessness while speaking, and increasing difficulty clearing saliva. He is alert with mild dysarthria and short-phrase speech, HR 96/min, shallow RR 24/min, BP 122/76 mmHg (MAP 91), pulse-coherent room-air SpO₂ 94%, warm extremities, and capillary refill 2 seconds. An experienced examination report describes reduced chest expansion, supine abdominal paradox, a weak cough, mild bulbar weakness, and no stridor or unilateral absent breath sounds. A preserved awake saturation does not establish adequate ventilation.' },
    { id: 'neuromuscular-respiratory-failure-mechanics', type: 'narrative',
      target: 'neuromuscular-respiratory-failure-reassessment', atTick: 0, severity: 'warning',
      message: 'Qualified respiratory-physiology reports show seated FVC falling from 68% to 46% predicted over 3 months, current supine FVC 30% predicted, SNIP falling from 50 to 28 cmH₂O, and peak cough flow falling from 340 to 210 L/min. The team documents acceptable interfaces and repeatability for this case. A fixed room-air blood gas reports pH 7.34, PaCO₂ 52 mmHg, PaO₂ 68 mmHg, and bicarbonate 28 mmol/L. The combined symptomatic trend, respiratory-muscle decline, cough impairment, and hypercapnia establishes the authored progressive ventilatory-failure pattern; no one value is presented as a universal isolated threshold. The learner does not perform or interpret mechanics, cough testing, oximetry, or blood gas.' },
    { id: 'neuromuscular-respiratory-failure-alternatives', type: 'narrative',
      target: 'neuromuscular-respiratory-failure-reassessment', atTick: 0, severity: 'advisory',
      message: 'A fixed radiograph report shows low lung volumes without focal consolidation, pulmonary-edema pattern, pleural effusion, or pneumothorax. Temperature is 36.8°C, glucose 102 mg/dL, and the experienced neurologic report describes no abrupt focal change. These snapshots narrow but do not permanently exclude aspiration, infection, mucus retention, atelectasis, pulmonary embolism, obstructive or restrictive lung disease, cardiac disease, metabolic or endocrine disturbance, medication effect, another neuromuscular process, central hypoventilation, poor test performance, or rapid deterioration. Bulbar function, swallowing, communication, cough, secretions, nutrition, and patient and caregiver priorities remain active parts of respiratory planning.' },
    { id: 'neuromuscular-respiratory-failure-boundary', type: 'narrative',
      target: 'neuromuscular-respiratory-failure-reassessment-boundary', atTick: 0, severity: 'advisory',
      message: 'Reconcile the serial whole-patient trajectory, then recognize the authored progressive neuromuscular ventilatory-failure pattern. Immediately connect respiratory-ventilation, critical-care, and airway-capable evaluation while reviewing bulbar, cough, secretion, testing, trigger, and alternative-cause evidence in parallel. After both lanes, coordinate patient-centered respiratory, neurology, speech and swallowing, nutrition, physiotherapy, nursing, primary-care, caregiver, communication, preference, and follow-up ownership. After a strictly later engine tick, hand off active risk and unresolved work. The controls do not examine; count speech or breaths; acquire, perform, score, or interpret oximetry, capnography, blood gas, spirometry, FVC, VC, SNIP, MIP, MEP, peak cough flow, sleep testing, imaging, swallowing, cough, secretion, or neurologic testing; diagnose; select or deliver oxygen, noninvasive or invasive ventilation, interface, mode, pressure, volume, backup rate, humidification, cough-assistance or airway-clearance technique or settings, suction, drug, nutrition, or treatment; intubate, place a tracheostomy, perform a procedure, determine disposition or prognosis, or predict response or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'neuromuscular-respiratory-failure-trajectory', objectiveId: 'reconcile-neuromuscular-respiratory-failure-trajectory', question: 'Which functional, symptom, breathing, cough, bulbar, gas-exchange, and perfusion changes established the trajectory?' },
    { id: 'neuromuscular-respiratory-failure-recognition', objectiveId: 'recognize-neuromuscular-respiratory-failure', question: 'How did the whole pattern establish progressive ventilatory failure without relying on awake SpO₂ or one mechanics cutoff?' },
    { id: 'neuromuscular-respiratory-failure-escalation', objectiveId: 'activate-neuromuscular-respiratory-failure-escalation', question: 'Why could experienced respiratory-ventilation, critical-care, and airway evaluation not wait for complete cause review?' },
    { id: 'neuromuscular-respiratory-failure-review', objectiveId: 'review-neuromuscular-respiratory-failure-bulbar-cough-and-alternatives', question: 'Which cough, secretion, bulbar, test-quality, trigger, and alternate-cause concerns remained active?' },
    { id: 'neuromuscular-respiratory-failure-ownership', objectiveId: 'coordinate-neuromuscular-respiratory-failure-goals-and-ownership', question: 'How did shared ownership preserve communication, preferences, respiratory and secretion-management evaluation, and follow-up without selecting treatment?' },
    { id: 'neuromuscular-respiratory-failure-handoff', objectiveId: 'handoff-neuromuscular-respiratory-failure-reassessment', question: 'Which trajectory, active risks, causes, priorities, pending work, triggers, and owners remained unresolved at handoff?' },
  ] },
};
