/** Portable oxygen source interruption, with bounded rescue, trace, and reassessment. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const OXYGEN_DEVICE_FAILURE: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'oxygen-device-failure', version: '0.1.1', maturity: 'preview',
    title: 'Portable oxygen source failure', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 7, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-oxygen-device-failure-patient-signal-and-delivery', statement: 'Reconcile the authored person, pulse-coherent saturation trend, spontaneous breathing, circulation, and expected oxygen delivery.', measure: 'True deterioration was recognized without treating an attached cannula or selected flow as proof that oxygen reached the patient.' },
      { id: 'activate-oxygen-device-failure-immediate-bridge-and-help', statement: 'Record immediate experienced-team help and oxygen from a separate verified source before waiting for a final fault label.', measure: 'Patient support took priority over troubleshooting, another test, or continuing transport.' },
      { id: 'review-oxygen-device-failure-source-to-patient-path', statement: 'Review the fixed source, regulator and flow, tubing, cannula, patient, and important alternative-cause report.', measure: 'The authored depleted-source no-flow state was localized without learner inspection, manipulation, device operation, or blame.' },
      { id: 'record-oxygen-device-failure-restoration-and-backup-intent', statement: 'Record qualified restoration of the established prescribed pathway from a checked replacement source with independent backup.', measure: 'No device, flow, oxygen fraction, target, connector, valve sequence, repair, or treatment technique was selected.' },
      { id: 'review-oxygen-device-failure-delivery-and-patient-response', statement: 'After elapsed time, review the fixed whole-person response and confirmation that oxygen is reaching the patient.', measure: 'Improvement toward baseline supported restoration, not resolution of lung disease, transport readiness, durable success, or outcome.' },
      { id: 'handoff-oxygen-device-failure-reassessment', statement: 'After another elapsed interval, hand off the active oxygen need, verified source, reserve, backup, response, open causes, monitoring, and named owners.', measure: 'The handoff preserved transport-system learning without assigning blame or declaring the patient safe to move.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.1', sources: [
        'NHS England. Use of oxygen cylinders where patients do not have access to medical gas pipeline systems. National Patient Safety Alert NatPSA/2023/001/NHSPS. 2023.',
        'O\u2019Driscoll BR, Howard LS, Earis J, Mak V. BTS guideline for oxygen use in adults in healthcare and emergency settings. BMJ Open Respir Res. 2017;4:e000170. PMID 28883921. doi:10.1136/bmjresp-2016-000170.',
        'World Health Organization. Technical specifications for health facility based medical oxygen systems. 2024. ISBN 978-92-4-010161-6.',
      ] },
    limitations: ['oxygen-device-failure-presentation-path-and-response-are-authored',
      'oxygen-device-failure-controls-review-bridge-restore-reassess-and-handoff-only',
      'no-live-cylinder-inspection-operation-oxygen-delivery-repair-transport-decision-or-outcome'],
  },
  patient: { ageYears: 67, sex: 'female', heightCm: 164, weightKg: 68, asaClass: 3,
    diagnosis: 'Authored fibrotic interstitial lung disease with an established supplemental-oxygen need',
    procedure: 'Portable oxygen source-failure recognition and reassessment',
    comorbidities: ['Fibrotic interstitial lung disease', 'No established chronic hypercapnic respiratory failure'],
    medications: ['The established oxygen prescription and other care are not represented'],
    allergies: ['No known drug allergies'],
    fasting: 'Not relevant to this spontaneously breathing transport-system lesson',
    baseline: { heartRateBpm: 106, meanArterialMmHg: 94, strokeVolumeMl: 64,
      hemoglobinGPerDl: 13.2, bloodVolumeMl: 4500, coreTemperatureC: 36.9,
      arterialStiffness: 1, baroreflexGain: 1, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Awake, frightened, short sentences, patent upper airway, spontaneous chest movement, and no artificial airway in the fixed report' },
    respiratory: { profile: 'moderately-ill' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'],
    ventilator: { mode: 'manual', fio2: 0.4, tidalVolumeMl: 400,
      respiratoryRateBpm: 30, freshGasFlowLPerMin: 0.5, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'oxygen-device-failure-baseline', type: 'narrative', target: 'oxygen-device-failure', atTick: 0, severity: 'warning',
      message: 'A 67-year-old retired librarian with fibrotic interstitial lung disease is traveling from the respiratory ward to scheduled imaging. Before departure, a fixed qualified report on verified wall oxygen describes alert full-sentence speech, RR 20/min, HR 84/min, BP 126/72 mmHg, and pulse-coherent SpO\u2082 93% on her established prescribed low-flow pathway. A recent fixed gas reports pH 7.43 and PaCO\u2082 35 mmHg without an acute hypercapnic pattern. Oxygen qualification, prescription, target, and imaging decisions are not part of this lab.' },
    { id: 'oxygen-device-failure-current-state', type: 'narrative', target: 'oxygen-device-failure', atTick: 0, severity: 'critical',
      message: 'Four minutes after transfer to a portable source whose selector is reported at the established 4 L/min, she is alert but frightened and dyspneic in short sentences with RR 30/min, HR 106/min, BP 130/76 mmHg (MAP 94), warm perfusion, spontaneous bilateral chest movement, and a strong regular pleth accompanying SpO\u2082 84%. The cannula remains in place. The person and pulse-coherent trend make the deterioration credible; an attached interface and selected number do not prove delivered oxygen. The monitor\u2019s nominal FiO\u2082 0.40 is an authored display proxy, not a measured patient dose.' },
    { id: 'oxygen-device-failure-qualified-path', type: 'narrative', target: 'oxygen-device-failure', atTick: 0, severity: 'warning',
      message: 'After a separate verified oxygen bridge is activated, the fixed qualified source-to-patient review reports the cannula correctly positioned, tubing and cannula patent and unkinked, no remaining pressure at the portable source, and no downstream oxygen flow despite the selector position. Bilateral breathing and the earlier examination pattern are otherwise unchanged, with no apnea, arrest, shock, new unilateral pain, airway-obstruction claim, or monitor incoherence. This localizes an authored depleted-source delivery interruption without permanently excluding another clinical cause if recovery is incomplete.' },
    { id: 'oxygen-device-failure-boundary', type: 'narrative', target: 'oxygen-device-failure-boundary', atTick: 0, severity: 'advisory',
      message: 'Begin with the person and credible signal, then call experienced help and bridge to a separate verified oxygen source before waiting for a final equipment label. Review the fixed source-to-patient path, record qualified restoration of the established pathway from a checked replacement source with independent backup, allow elapsed time, review the fixed 3-minute delivery and whole-person response, then complete another strictly elapsed handoff. The controls do not examine; measure saturation or flow; acquire or interpret a blood gas, imaging, monitor, or test; diagnose; inspect, open, close, attach, detach, reconnect, replace, repair, or operate a cylinder, valve, regulator, flowmeter, tubing, cannula, or other device; calculate cylinder duration; select a device, source, interface, flow, FiO\u2082, oxygen target, prescription, drug, ventilation, or treatment; deliver oxygen or perform a procedure; decide transport readiness, disposition, or prognosis; or predict durable restoration or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'oxygen-device-failure-recognition', objectiveId: 'reconcile-oxygen-device-failure-patient-signal-and-delivery', question: 'Which person, signal, breathing, circulation, and prior-support findings showed that the deterioration was credible and delivery needed checking?' },
    { id: 'oxygen-device-failure-bridge', objectiveId: 'activate-oxygen-device-failure-immediate-bridge-and-help', question: 'Why did verified alternate oxygen and experienced help come before a final fault label?' },
    { id: 'oxygen-device-failure-path', objectiveId: 'review-oxygen-device-failure-source-to-patient-path', question: 'How did the fixed full-path report localize no flow from the depleted source while preserving important alternatives?' },
    { id: 'oxygen-device-failure-restoration', objectiveId: 'record-oxygen-device-failure-restoration-and-backup-intent', question: 'What did checked restoration and independent backup mean without claiming device operation or oxygen-delivery skill?' },
    { id: 'oxygen-device-failure-response', objectiveId: 'review-oxygen-device-failure-delivery-and-patient-response', question: 'Which fixed delivery and whole-person changes supported restoration without proving resolution or transport readiness?' },
    { id: 'oxygen-device-failure-handoff', objectiveId: 'handoff-oxygen-device-failure-reassessment', question: 'Which oxygen need, source, reserve, backup, monitoring, response, open-cause, incident, and ownership work remained active?' },
  ] },
};
