/** Persistent dyspnea after pulmonary embolism reassessment. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const POST_PULMONARY_EMBOLISM_PERSISTENT_DYSPNEA: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'post-pulmonary-embolism-persistent-dyspnea', version: '0.1.0', maturity: 'preview',
    title: 'Persistent dyspnea after pulmonary embolism', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 8, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-post-pe-symptoms-and-anticoagulation-course', statement: 'Reconcile the confirmed acute PE, at least 3 months of verified therapeutic anticoagulation, prior function, and persistent symptom trajectory.', measure: 'The authored course was separated from learner prescribing, adherence verification, and a claim of resolution.' },
      { id: 'review-post-pe-functional-limitation-and-current-safety', statement: 'Review resting stability, fixed exertional limitation, oxygenation change, and current recurrence and bleeding warning signs.', measure: 'Whole-patient safety and function were reviewed without declaring recurrence absent or acquiring a test.' },
      { id: 'review-post-pe-ctepd-evidence-and-alternatives', statement: 'Integrate fixed cardiac, perfusion, and exercise reports while preserving CTEPD uncertainty and alternative causes.', measure: 'The evidence justified expert evaluation without making a CTEPD or CTEPH diagnosis.' },
      { id: 'activate-post-pe-pulmonary-vascular-referral', statement: 'Record pulmonary-vascular expert-pathway intent and continued anticoagulation ownership pending evaluation.', measure: 'Referral and treatment ownership were coordinated without choosing a drug, duration, test, procedure, or therapy.' },
      { id: 'handoff-post-pe-persistent-dyspnea-reassessment', statement: 'After elapsed time, hand off symptoms, evidence, anticoagulation and bleeding review, open causes, triggers, and named owners.', measure: 'The handoff preserved unresolved evaluation without inventing diagnosis, prognosis, recovery, or outcome.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'Creager MA, Barnes GD, Giri J, et al. 2026 Guideline for the Evaluation and Management of Acute Pulmonary Embolism in Adults. Circulation. 2026;153:e977-e1051.',
        'Humbert M, Kovacs G, Hoeper MM, et al. 2022 ESC/ERS Guidelines for the diagnosis and treatment of pulmonary hypertension. Eur Heart J. 2022;43:3618-3731.',
      ] },
    limitations: ['post-pe-course-function-and-evaluation-reports-are-authored',
      'post-pe-controls-record-review-referral-ownership-and-handoff-only',
      'no-live-post-pe-testing-diagnosis-treatment-procedure-or-outcome'],
  },
  patient: { ageYears: 56, sex: 'female', heightCm: 166, weightKg: 72, asaClass: 3,
    diagnosis: 'Authored persistent exertional dyspnea 4 months after confirmed pulmonary embolism',
    procedure: 'Post-pulmonary-embolism persistent-dyspnea reassessment',
    comorbidities: ['Pulmonary embolism 4 months earlier'],
    medications: ['Therapeutic anticoagulation managed by the experienced team'],
    allergies: ['No known drug allergies'], fasting: 'Not relevant to this respiratory clinic reassessment',
    baseline: { heartRateBpm: 88, meanArterialMmHg: 91, strokeVolumeMl: 66,
      hemoglobinGPerDl: 12.8, bloodVolumeMl: 4700, coreTemperatureC: 36.8,
      arterialStiffness: 1.05, baroreflexGain: 1, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false,
      assessment: 'Alert, speaking full sentences, and without acute upper-airway concern' },
    respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'],
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 430,
      respiratoryRateBpm: 18, freshGasFlowLPerMin: 0.5, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'post-pe-course', type: 'narrative',
      target: 'post-pulmonary-embolism-persistent-dyspnea-reassessment', atTick: 0, severity: 'warning',
      message: 'A 56-year-old woman returns to respiratory clinic 4 months after objectively confirmed acute pulmonary embolism. Before the event she walked 2 miles and climbed 2 flights without stopping. The experienced-team record documents continuous therapeutic anticoagulation for 4 months without reported missed doses, major bleeding, or early discontinuation; this is not learner prescribing or adherence verification. She now stops after about 150 m or 1 flight because of exertional dyspnea and fatigue.' },
    { id: 'post-pe-current', type: 'narrative',
      target: 'post-pulmonary-embolism-persistent-dyspnea-reassessment', atTick: 0, severity: 'warning',
      message: 'She is alert and comfortable at rest with HR 88/min in sinus rhythm, RR 18/min, BP 122/76 mmHg (MAP 91), room-air SpO₂ 96%, warm extremities, and capillary refill 2 seconds. A fixed supervised 6-minute-walk report records 280 m, SpO₂ 96% to 91%, and HR 88 to 116/min with limiting dyspnea but no syncope or chest pain. No current hypotension, rest hypoxemia, syncope, hemoptysis, new unilateral leg swelling, fever, pulmonary-edema pattern, or major bleeding is reported. These snapshots do not permanently exclude recurrence or another cause.' },
    { id: 'post-pe-evaluation', type: 'narrative',
      target: 'post-pulmonary-embolism-persistent-dyspnea-reassessment', atTick: 0, severity: 'advisory',
      message: 'A fixed transthoracic-echo report shows preserved LV systolic function, mild RV enlargement and reduced RV systolic function, tricuspid-regurgitation velocity 3.2 m/s, and no pericardial effusion. A fixed V/Q SPECT report shows multiple bilateral segmental mismatched perfusion defects. These reports raise concern for chronic thromboembolic pulmonary disease but do not diagnose CTEPD or CTEPH. No right-heart catheterization, chronic-clot anatomic adjudication, pulmonary vascular exercise-limitation determination, or expert multidisciplinary conclusion is supplied.' },
    { id: 'post-pe-boundary', type: 'narrative',
      target: 'post-pulmonary-embolism-persistent-dyspnea-reassessment-boundary', atTick: 0, severity: 'advisory',
      message: 'Reconcile the post-acute course, persistent symptoms, function, and verified anticoagulation; review current safety; integrate fixed echo, perfusion, and exercise reports while preserving recurrent PE, left-heart disease, parenchymal lung disease, anemia, deconditioning, and other causes; coordinate pulmonary-vascular expert evaluation and continued anticoagulation ownership pending evaluation; then complete a strictly later handoff. The controls do not examine; acquire or interpret walk testing, oximetry, ECG, laboratory, echo, V/Q, CT, CPET, or catheterization data; categorize acute PE severity; select, dose, stop, switch, or set duration for anticoagulation; adjudicate bleeding risk; select oxygen, rehabilitation, pulmonary-hypertension therapy, surgery, balloon angioplasty, or another treatment; perform a procedure; diagnose CTEPD or CTEPH; decide operability, disposition, prognosis, recovery, recurrence, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'post-pe-course-review', objectiveId: 'reconcile-post-pe-symptoms-and-anticoagulation-course', question: 'Which acute-course, treatment, baseline, and symptom facts established the post-PE trajectory?' },
    { id: 'post-pe-safety-review', objectiveId: 'review-post-pe-functional-limitation-and-current-safety', question: 'Which resting, exertional, recurrence, and bleeding findings required whole-patient review?' },
    { id: 'post-pe-evidence-review', objectiveId: 'review-post-pe-ctepd-evidence-and-alternatives', question: 'Which fixed reports raised CTEPD concern, and which causes remained open?' },
    { id: 'post-pe-referral', objectiveId: 'activate-post-pe-pulmonary-vascular-referral', question: 'Which evaluation and anticoagulation owners were needed without diagnosing or choosing therapy?' },
    { id: 'post-pe-handoff', objectiveId: 'handoff-post-pe-persistent-dyspnea-reassessment', question: 'Which symptoms, evidence, risks, causes, triggers, and owners remained active at handoff?' },
  ] },
};
