/** Pleural reassessment after experienced-team drainage of a spontaneous tension pneumothorax. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const SPONTANEOUS_TENSION_PNEUMOTHORAX_POST_DRAINAGE_REASSESSMENT: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'spontaneous-tension-pneumothorax-post-drainage-reassessment', version: '0.1.0', maturity: 'preview',
    title: 'After tension pneumothorax drainage', author: 'Open Sim Lab', license: 'CC BY-SA 4.0',
    estimatedMinutes: 8, difficulty: 'intermediate', objectives: [
      { id: 'reconcile-spontaneous-tension-pneumothorax-trajectory-and-prior-care', statement: 'Reconcile the authored spontaneous tension-pneumothorax presentation, experienced-team emergency drainage, and current trajectory.', measure: 'The tension event and reported response were reviewed without crediting the learner with diagnosis, examination, drainage, oxygen, or treatment.' },
      { id: 'review-spontaneous-tension-pneumothorax-drainage-response', statement: 'Review current safety and the fixed response to emergency pleural drainage.', measure: 'Symptoms, oxygenation, perfusion, unilateral findings, and the drain report were reviewed without declaring durable resolution.' },
      { id: 'review-spontaneous-tension-pneumothorax-drain-system-and-complications', statement: 'Review the authored pleural-drain system, persistent air leak, and change triggers.', measure: 'Drain and complication evidence was reviewed without inspecting, manipulating, clamping, flushing, applying suction, or removing the drain.' },
      { id: 'review-spontaneous-tension-pneumothorax-etiology-recurrence-and-definitive-planning', statement: 'Review secondary causes, recurrence-prevention priorities, and pleural and thoracic ownership.', measure: 'Definitive planning and patient priorities were recorded without choosing a procedure or predicting recurrence.' },
      { id: 'handoff-spontaneous-tension-pneumothorax-post-drainage-reassessment', statement: 'After elapsed time, hand off the prior tension event, current safety, unresolved pleural work, triggers, and named owners.', measure: 'The handoff preserved uncertainty without inventing disposition, prognosis, recurrence, resolution, or outcome.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED',
      competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01',
      contentVersion: '0.1.0', sources: [
        'Roberts ME, Rahman NM, Maskell NA, et al. British Thoracic Society Guideline for pleural disease. Thorax. 2023;78(Suppl 3):s1-s42.',
        'Walker S, Hallifax R, Ricciardi S, et al. Joint ERS/EACTS/ESTS clinical practice guidelines on adults with spontaneous pneumothorax. Eur Respir J. 2024;63:2300797.',
      ] },
    limitations: ['post-tension-course-drain-and-complication-reports-are-authored',
      'post-tension-controls-record-review-planning-ownership-and-handoff-only',
      'no-live-pleural-examination-testing-drain-procedure-treatment-or-outcome'],
  },
  patient: { ageYears: 68, sex: 'male', heightCm: 176, weightKg: 70, asaClass: 4,
    diagnosis: 'Authored secondary spontaneous tension pneumothorax after emergency drainage',
    procedure: 'Post-drainage pleural reassessment',
    comorbidities: ['Chronic obstructive pulmonary disease with emphysema'],
    medications: ['Usual respiratory therapy managed by the experienced team'],
    allergies: ['No known drug allergies'], fasting: 'Not relevant to this respiratory-ward reassessment',
    baseline: { heartRateBpm: 96, meanArterialMmHg: 79, strokeVolumeMl: 58,
      hemoglobinGPerDl: 13.2, bloodVolumeMl: 4550, coreTemperatureC: 36.7,
      arterialStiffness: 1.15, baroreflexGain: 0.9, fixedStrokeVolume: false },
    airway: { difficulty: 0.2, difficultMaskVentilation: false,
      assessment: 'Alert, speaking full sentences, and without an acute upper-airway concern' },
    respiratory: { profile: 'moderately-ill' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'],
    ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 410,
      respiratoryRateBpm: 22, freshGasFlowLPerMin: 0.5, delivering: false } },
  formulary: [],
  timeline: [
    { id: 'post-tension-pneumothorax-course', type: 'narrative',
      target: 'spontaneous-tension-pneumothorax-post-drainage-reassessment', atTick: 0, severity: 'critical',
      message: 'Six hours ago, a 68-year-old man with emphysema developed abrupt right-sided chest pain and severe dyspnea. The fixed experienced-team record reports HR 132/min, RR 36/min, BP 76/44 mmHg, pulse-coherent SpO₂ 82%, confusion, cool skin, markedly reduced right chest movement and air entry, and left air entry present. There was no penetrating trauma, positive-pressure ventilation, arrest, or procedure preceding the event. The experienced team treated the reported spontaneous tension-pneumothorax pattern immediately and placed a right pleural drain. No diagnosis, examination, oxygen, drainage, or treatment was learner-performed.' },
    { id: 'post-tension-pneumothorax-current', type: 'narrative',
      target: 'spontaneous-tension-pneumothorax-post-drainage-reassessment', atTick: 0, severity: 'warning',
      message: 'The current fixed report shows less pain and work of breathing, alert full-sentence speech, HR 96/min, RR 22/min, BP 108/64 mmHg (MAP 79), pulse-coherent SpO₂ 93% on room air, warm extremities, and capillary refill 2 seconds. Right air entry remains reduced but is improved from presentation. A fixed post-drainage radiograph report shows partial right-lung re-expansion with the drain projecting in the pleural space and no new contralateral pneumothorax or large pleural collection. These snapshots do not establish durable drain function, complete re-expansion, or resolution.' },
    { id: 'post-tension-pneumothorax-pleural-work', type: 'narrative',
      target: 'spontaneous-tension-pneumothorax-post-drainage-reassessment', atTick: 0, severity: 'warning',
      message: 'The authored pleural observation record reports an upright bottle below the insertion site, an intact visible connection, respiratory swing, and intermittent bubbling at 6 hours. The site dressing is intact without reported enlarging subcutaneous emphysema or external bleeding. Persistent air leak, drain position and patency over time, failure of re-expansion, infection, recurrence prevention, surgical fitness, the patient’s priorities, and the definitive pleural strategy remain unresolved and require named pleural and thoracic ownership.' },
    { id: 'post-tension-pneumothorax-boundary', type: 'narrative',
      target: 'spontaneous-tension-pneumothorax-post-drainage-reassessment-boundary', atTick: 0, severity: 'advisory',
      message: 'Reconcile the spontaneous tension event, experienced-team emergency drainage, and current trajectory; review current safety and fixed drainage response; review the authored drain system, persistent-air-leak questions, complications, and deterioration triggers; review secondary causes, recurrence-prevention priorities, patient preferences, and pleural and thoracic ownership; then complete a strictly later handoff. The controls do not examine; acquire or interpret monitoring, imaging, ultrasound, pleural-pressure, or laboratory data; diagnose a real patient; inspect, manipulate, unkink, reconnect, clamp, flush, apply suction to, remove, replace, or insert a drain; select a device, size, site, technique, oxygen target, drug, dose, aspiration, pleurodesis, thoracoscopy, surgery, or treatment; perform decompression or another procedure; determine disposition, prognosis, recurrence, repair, resolution, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'post-tension-course', objectiveId: 'reconcile-spontaneous-tension-pneumothorax-trajectory-and-prior-care', question: 'Which presentation, prior-care, and current facts established the trajectory?' },
    { id: 'post-tension-response', objectiveId: 'review-spontaneous-tension-pneumothorax-drainage-response', question: 'Which current patient and fixed drainage findings support improvement without proving resolution?' },
    { id: 'post-tension-system', objectiveId: 'review-spontaneous-tension-pneumothorax-drain-system-and-complications', question: 'Which drain-system, air-leak, complication, and deterioration questions remain active?' },
    { id: 'post-tension-planning', objectiveId: 'review-spontaneous-tension-pneumothorax-etiology-recurrence-and-definitive-planning', question: 'Which cause, recurrence-prevention, preference, and specialist-planning questions need owners?' },
    { id: 'post-tension-handoff', objectiveId: 'handoff-spontaneous-tension-pneumothorax-post-drainage-reassessment', question: 'Which trajectory, unresolved pleural work, triggers, and owners remained active at handoff?' },
  ] },
};
