import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { FOCAL_MOTOR_STATUS_EPILEPTICUS_ESCALATION } from './scenarios/focal-motor-status-epilepticus-escalation';
import { FOCAL_MOTOR_STATUS_FIXTURES } from './focal-motor-status-epilepticus-escalation-fixtures';
import { FOCAL_MOTOR_STATUS_TUTOR_VERSION } from './tutor/focal-motor-status-epilepticus-escalation-guidance';
import { FOCAL_MOTOR_STATUS_DEMONSTRATION_VERSION } from './demo/focal-motor-status-epilepticus-escalation-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * `observable-objectives` is deliberately not answered here. This scenario
 * declares six objectives against a cap of five, which is a content-design
 * decision affecting scenarios across several modules rather than something
 * this file may settle on its own. The shared audit keeps naming it.
 */
export function focalMotorStatusCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'neurology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== FOCAL_MOTOR_STATUS_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || FOCAL_MOTOR_STATUS_FIXTURES.contentVersion !== '0.1.0'
    || FOCAL_MOTOR_STATUS_FIXTURES.seed !== 6269
    || FOCAL_MOTOR_STATUS_TUTOR_VERSION !== '0.1.0' || FOCAL_MOTOR_STATUS_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(FOCAL_MOTOR_STATUS_EPILEPTICUS_ESCALATION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['focal-motor-status-epilepticus-escalation-fixtures.ts binds seed 6269 and content 0.1.0 to expert, quieter-therefore-better error, recovery, and no-action paths. The presentation, the witnessed evolution, the supplied observations and glucose, and the fixed minute-26 report are authored constants; no seizure, rescue-drug, or electrographic model is claimed, and no outcome follows from any choice. tests/integration/focal-motor-status-epilepticus-escalation-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, two of them time-gated: the later visible-motor review refuses until simulated time has passed since the safety review, and the handoff refuses until time has passed since that. What does not move is the seizure — visible clonus continues at minute 26 with no meaningful recovery — which is the progression this lesson is about.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions count one continuous event rather than episodes, say that quieter is not stopped while overt focal clonus continues, escalate qualified seizure, resuscitation and airway-capable ownership on visible movement without waiting for an EEG, run the airway, glucose, cause and injury review alongside that escalation rather than instead of it, compare a fixed minute-26 report, and hand off active risk. Order is enforced rather than suggested, and refusal names the missing step. The lesson takes no history, examines nobody, times no seizure, acquires no monitoring, glucose, EEG, imaging or laboratory test, and selects no drug, dose, route, access, oxygen, airway device, or procedure.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at active-risk handoff. Later actions cannot restart an ended branch, and the ending certifies no proven cause, no movement cessation, no electrographic control, no treatment effect, no durable neurologic recovery or airway protection, no disposition, and no outcome.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that moved to the workup because the room had calmed can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['focal-motor-status-epilepticus-escalation-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 6269 for deterministic replay through the shared engine, including the two time-gated checkpoints.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${FOCAL_MOTOR_STATUS_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent and coached withholds the single non-urgent beat. Worked example ${FOCAL_MOTOR_STATUS_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. Both are built on the sentence the lesson exists for: less dramatic movement is not seizure resolution. The bilateral convulsions became less dramatic after qualified rescue care, and stereotyped left face and arm clonus is still running with no meaningful recovery — one continuous event at eighteen minutes rather than a seizure that ended. A partial response that removes the most alarming part of the picture is the moment this gets missed, because the room relaxes while the clock keeps running, so both say it before anything else moves. Both escalate on visible movement rather than on an EEG that does not exist here, because waiting for electrographic confirmation before calling anyone converts a visible emergency into a scheduling problem. The airway, the glucose and the search for a cause run alongside that call rather than instead of it, which is why the review comes after it, and the glucose of 104 removes one fast reversible cause and nothing else. The ending hands off a seizure that is still going. A test asserts nothing anywhere times the seizure, interprets an EEG, or claims movement stopped. tests/unit/focal-motor-status-epilepticus-escalation-demonstration.test.ts and tests/ui/neurology-focal-motor-status-epilepticus-escalation.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
