import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { GUILLAIN_BARRE_RESPIRATORY_DECLINE } from './scenarios/guillain-barre-respiratory-decline';
import { GBS_FIXTURES } from './guillain-barre-respiratory-decline-fixtures';
import { GBS_TUTOR_VERSION } from './tutor/guillain-barre-respiratory-decline-guidance';
import { GBS_DEMONSTRATION_VERSION } from './demo/guillain-barre-respiratory-decline-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * `observable-objectives` is deliberately not answered here. This scenario
 * declares six objectives against a cap of five, which is a content-design
 * decision affecting scenarios across several modules rather than something
 * this file may settle on its own. The shared audit keeps naming it.
 */
export function gbsCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'neurology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== GBS_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || GBS_FIXTURES.contentVersion !== '0.1.0'
    || GBS_FIXTURES.seed !== 6392
    || GBS_TUTOR_VERSION !== '0.1.0' || GBS_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(GUILLAIN_BARRE_RESPIRATORY_DECLINE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['guillain-barre-respiratory-decline-fixtures.ts binds seed 6392 and content 0.1.0 to expert, skipped-the-mimic error, recovery, and no-action paths. The presentation, the serial mechanics and single-breath counts, the fixed blood gas, CSF and nerve-conduction reports, the monitored autonomic hour, and the fixed 4-hour report are authored constants; no neuromuscular, autonomic or ventilation model is claimed, and no outcome follows from any choice. tests/integration/guillain-barre-respiratory-decline-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The lesson advances through six recorded steps on the shared simulation clock, two of them time-gated: the later respiratory, bulbar and autonomic review refuses until simulated time has passed since the ownership activation, and the handoff refuses until time has passed since that. Three axes move together — the vital capacity falls, the bulbar failure deepens, and the autonomic range widens — while the saturation stays above 96%.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six declared decisions measure the ascent in days rather than findings, ask what else does this before the obvious answer is allowed to close, call a high-risk respiratory decline while the saturation is still 98% and while no score or single cutoff is treated as the threshold, bring neurocritical, respiratory, airway-capable and cardiac-monitoring ownership in together, compare a fixed later report, and hand off active risk. Order is enforced rather than suggested, and refusal names the missing step. The lesson takes no history, examines nobody, calculates no score, acquires no respiratory mechanics, blood gas or CSF, interprets no electrodiagnostic or cardiac-monitoring record, and selects no drug, dose, route, access, oxygen, ventilation, airway device, rhythm or pressure treatment.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at active-risk handoff. Later actions cannot restart an ended branch, and the ending certifies no proven diagnosis, no treatment effect, no durable neurologic recovery, no disposition, and no outcome. No respiratory arrest is authored.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps all six objectives to accepted engine events; the no-action path meets none and the expert path meets all six. Refused out-of-order attempts stay visible in the transcript after a correct recovery, which is the authored counterfactual: the same run that accepted the textbook story without asking what else does this can still reach a correct handoff.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['guillain-barre-respiratory-decline-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways to seed 6392 for deterministic replay through the shared engine, including the two time-gated checkpoints.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${GBS_TUTOR_VERSION} read the learner's own recorded steps; unassisted is silent and coached withholds the single non-urgent beat. Worked example ${GBS_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to handoff. This lesson shares the saturation trap with the myasthenic lesson next door and adds two things that one does not have. The first is a mimic that must be excluded before the obvious answer is allowed to close: ascending weakness with areflexia is also what a cord lesion looks like, so both the tutor and the example say out loud what argues against it here — preserved sensation, no sensory level, no extensor plantar — rather than assuming it. The CSF protein of 86 with 3 cells and the demyelinating nerve-conduction pattern support the picture without making any one test diagnostic. The second is dysautonomia as a third axis of risk, where the instruction is to monitor rather than chase: a monitored hour ranging from 48 to 138 beats and 88/52 to 188/110 is a reason for cardiac ownership and continuous watching, not a list of values to correct one at a time, and provoking or automatically treating each one is named as the failure mode. The respiratory call is made on the slope — 3.6 to 2.4 litres, a single-breath count from 28 to 18, MIP -45 to -30 in twelve hours — with the gas normal because in neuromuscular failure it is normal until it is not. The ending hands off three problems rather than one. A test asserts nothing anywhere measures mechanics, interprets the monitor, proves the diagnosis, or treats a rhythm. tests/unit/guillain-barre-respiratory-decline-demonstration.test.ts and tests/ui/neurology-guillain-barre-respiratory-decline.test.tsx verify observed response, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
