/** Timed acute acetaminophen-ingestion recognition and bounded antidote transition. */

import type { Scenario } from '@anesthesia/scenarios/types';

export const ACETAMINOPHEN_CLOCK_AND_NOMOGRAM: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'acetaminophen-clock-and-nomogram', version: '0.1.0', maturity: 'preview',
    title: 'Acetaminophen: the clock changes the meaning', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: [
      { id: 'reconcile-toxicology-acetaminophen-product-ingestion-window-clock-symptoms-and-whole-patient', statement: 'Reconcile the product, ingestion window, clock, symptoms, and whole patient.', measure: 'The supplied immediate-release acetaminophen-only exposure, witnessed completion time, 6-hour clock, nausea, stable physiology, unreliable reported quantity, and whole-patient state were connected without learner history, examination, monitoring, sampling, or calculation.' },
      { id: 'recognize-toxicology-acetaminophen-acute-timed-pattern-and-nomogram-applicability-boundary', statement: 'Recognize the acute timed pattern and the nomogram-applicability boundary.', measure: 'The case was recognized as a timed acute ingestion eligible for qualified nomogram use while pre-4-hour, unknown-time, repeated, extended-release, delayed-absorption, and coingestion pathways remained distinct.' },
      { id: 'activate-toxicology-acetaminophen-poison-center-emergency-monitoring-and-nonjudgmental-safety-ownership', statement: 'Activate poison-center, emergency, monitoring, and nonjudgmental safety ownership.', measure: 'Poison-center or medical-toxicology consultation, emergency and laboratory ownership, supportive monitoring, exposure reconciliation, and compassionate self-harm safety ownership were recorded without learner decontamination, drug, dose, route, or procedure selection.' },
      { id: 'review-toxicology-acetaminophen-supplied-timed-level-nomogram-position-liver-and-coingestion-boundary', statement: 'Review the supplied timed level, qualified nomogram position, liver evidence, and coingestion boundary.', measure: 'The supplied 6-hour acetaminophen 132 µg/mL and qualified above-treatment-line position were integrated with baseline AST, ALT, INR, creatinine, glucose, product, timing, and coingestion limits without learner plotting or diagnosis.' },
      { id: 'record-toxicology-acetaminophen-bounded-qualified-team-acetylcysteine-intent-and-strict-later-review', statement: 'Record bounded qualified-team acetylcysteine intent, then review a strict later report.', measure: 'Qualified-team acetylcysteine intent was recorded without product, dose, route, preparation, access, infusion, or delivery; the fixed later acetaminophen and liver-risk report was reviewed after elapsed time without an automatic course-length or stopping decision.' },
      { id: 'handoff-toxicology-acetaminophen-serial-level-liver-failure-stopping-safety-and-active-risk', statement: 'Hand off serial level, liver-failure, stopping, safety, and active risk.', measure: 'The handoff preserved exposure timing, serial acetaminophen and liver evidence, individualized continuation and stopping review, hepatic deterioration, coingestion, compassionate safety, disposition, and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: [
      'Dart RC, et al. Management of Acetaminophen Poisoning in the US and Canada: A Consensus Statement. JAMA Netw Open. 2023;6(8):e2327739. PMID:37552484.',
      'American College of Medical Toxicology. Duration of Intravenous Acetylcysteine Therapy following Acetaminophen Overdose: 2026 update. Approved 2026-01.',
      'DailyMed. ACETADOTE acetylcysteine injection prescribing information. Set ID 472f158a-5ab9-4308-8e49-1116e6ea3d39. Revised 2024-11.',
    ] },
    limitations: ['acetaminophen-exposure-clock-level-nomogram-position-labs-and-response-are-authored',
      'acetaminophen-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only',
      'no-live-ingestion-assessment-nomogram-calculation-antidote-dose-delivery-stopping-or-outcome'],
  },
  patient: {
    ageYears: 24, sex: 'female', heightCm: 168, weightKg: 64, asaClass: 2,
    diagnosis: 'Authored suspected potentially toxic timed acute acetaminophen ingestion pattern',
    procedure: 'calm clock, nomogram-boundary, bounded antidote-intent, reassessment, and handoff practice',
    comorbidities: ['Supplied intentional ingestion prompts compassionate qualified safety assessment'],
    medications: ['Exact home medicines, coingestants, and total reported quantity remain qualified-team work'],
    allergies: ['No known drug allergies'], fasting: 'Not relevant to the toxicology fixture',
    baseline: { heartRateBpm: 92, meanArterialMmHg: 91, strokeVolumeMl: 66, hemoglobinGPerDl: 13.1, bloodVolumeMl: 4_600, coreTemperatureC: 36.8, arterialStiffness: 1, baroreflexGain: 0.8, fixedStrokeVolume: false },
    airway: { difficulty: 0.1, difficultMaskVentilation: false, assessment: 'Alert, conversant, and handling secretions in the supplied fixture' },
    respiratory: { profile: 'healthy' },
  },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 430, respiratoryRateBpm: 12, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'acetaminophen-clock-and-nomogram-presentation', type: 'narrative', target: 'acetaminophen-clock-and-nomogram-transition', atTick: 0, severity: 'critical', message: 'A 24-year-old woman presents exactly 6 hours after a witnessed intentional ingestion completed within one hour. The supplied package review identifies immediate-release acetaminophen only; the reported tablet quantity is uncertain and is not treated as a reliable treatment guide. She has nausea but is alert and conversant. Authored monitor state is sinus rhythm 92/min, BP 122/76 mmHg (MAP 91), RR 16/min, room-air SpO2 99%, and T 36.8°C. There is no authored vomiting, abdominal tenderness, jaundice, hypoglycemia, acidosis, altered mental status, shock, or coingestant syndrome.' },
    { id: 'acetaminophen-clock-and-nomogram-evidence', type: 'narrative', target: 'acetaminophen-clock-and-nomogram-transition', atTick: 0, severity: 'warning', message: 'A supplied 6-hour serum acetaminophen concentration is 132 µg/mL. A qualified toxicology plot places it above the acute-ingestion treatment line and below the high-risk line. Baseline supplied AST is 24 U/L, ALT 21 U/L, INR 1.1, creatinine 0.8 mg/dL, and glucose 96 mg/dL. The learner does not plot or calculate. Nomogram meaning depends on a timed acute ingestion and a sample at least 4 hours after ingestion; unknown-time, repeated, extended-release, delayed-absorption, coingestion, late, and liver-injury pathways require different qualified evaluation.' },
    { id: 'acetaminophen-clock-and-nomogram-boundary', type: 'narrative', target: 'acetaminophen-clock-and-nomogram-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile product, ingestion window, clock, symptoms, reported-quantity limits, and whole patient; recognize the timed acute-ingestion and nomogram-applicability boundary; activate poison-center or medical-toxicology, emergency, laboratory, monitoring, and compassionate self-harm safety ownership; then review the supplied timed level, qualified nomogram position, baseline liver, coagulation, renal, glucose, product, timing, and coingestion evidence. The learner may record only bounded qualified-team acetylcysteine intent; no product, dose, route, preparation, access, infusion, adverse-reaction management, or delivery is exposed. After elapsed simulated time, a strict fixed 22-hour-post-ingestion report supplies acetaminophen below 10 µg/mL, AST 27 U/L, ALT 24 U/L, INR 1.2, creatinine 0.8 mg/dL, normal glucose, stable mentation, and easing nausea. This does not authorize an automatic 20- or 21-hour stop, prove individualized treatment effect, exclude delayed absorption or evolving liver injury, determine safety or disposition, or predict outcome. Qualified teams retain serial acetaminophen, aminotransferase, INR, renal, acid-base, lactate, glucose, mental-status, coingestion, adverse-reaction, continuation, stopping, liver-failure, transplant-center, and safety decisions. After another elapsed interval, hand off the clock, serial evidence, antidote status, stopping review, hepatic deterioration, coingestion, compassionate safety, disposition, and outcome uncertainty. Controls do not take history; examine; acquire or interpret monitoring, laboratory, ECG, imaging, or another test; plot or calculate a nomogram; diagnose; select or deliver charcoal, acetylcysteine, a drug, dose, route, access, infusion, fluid, or device; manage an adverse reaction; perform dialysis or another procedure; determine stopping, eligibility, disposition, prognosis, or safety; or predict response, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'acetaminophen-trajectory', objectiveId: 'reconcile-toxicology-acetaminophen-product-ingestion-window-clock-symptoms-and-whole-patient', question: 'Which product, ingestion-window, clock, symptom, quantity-limit, and whole-patient findings established the trajectory?' },
    { id: 'acetaminophen-recognition', objectiveId: 'recognize-toxicology-acetaminophen-acute-timed-pattern-and-nomogram-applicability-boundary', question: 'Why was qualified nomogram use applicable here, and which common exposure patterns would make it inapplicable or incomplete?' },
    { id: 'acetaminophen-support', objectiveId: 'activate-toxicology-acetaminophen-poison-center-emergency-monitoring-and-nonjudgmental-safety-ownership', question: 'Which toxicology, emergency, laboratory, monitoring, and compassionate safety owners needed to begin together?' },
    { id: 'acetaminophen-evidence', objectiveId: 'review-toxicology-acetaminophen-supplied-timed-level-nomogram-position-liver-and-coingestion-boundary', question: 'How did the clock, supplied level and plot, baseline labs, product, and coingestion boundary travel together?' },
    { id: 'acetaminophen-reassessment', objectiveId: 'record-toxicology-acetaminophen-bounded-qualified-team-acetylcysteine-intent-and-strict-later-review', question: 'What did bounded antidote intent and the strict later report establish without authorizing an automatic stop?' },
    { id: 'acetaminophen-handoff', objectiveId: 'handoff-toxicology-acetaminophen-serial-level-liver-failure-stopping-safety-and-active-risk', question: 'Which serial level, liver, stopping, coingestion, safety, disposition, and outcome risks required handoff?' },
  ] },
};
