/** Anticholinergic hyperthermia, delirium, and reassessment. */
import type { Scenario } from '@anesthesia/scenarios/types';

export const ANTICHOLINERGIC_HYPERTHERMIA_DELIRIUM: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'anticholinergic-hyperthermia-delirium', version: '0.1.0', maturity: 'preview',
    title: 'Anticholinergic poisoning: cool the patient, not the clues', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: [
      { id: 'reconcile-toxicology-anticholinergic-product-clock-delirium-temperature-dryness-retention-ecg-and-whole-patient', statement: 'Reconcile product, clock, delirium, temperature, dryness, retention, ECG, and the whole patient.', measure: 'The declared benztropine-only exposure, 3-hour clock, severe delirium, mydriasis, dry flushed skin and mucosa, urinary retention, reduced bowel sounds, hyperthermia, tachycardia, supplied ECG and whole-patient state were connected without learner history, examination, monitoring, testing, or diagnosis.' },
      { id: 'recognize-toxicology-anticholinergic-central-and-peripheral-pattern-without-mnemonic-temperature-or-pupil-only-closure', statement: 'Recognize the central and peripheral anticholinergic pattern without mnemonic-, temperature-, pupil-, or dryness-only closure.', measure: 'Declared exposure, severe central delirium, peripheral antimuscarinic findings, hyperthermia and tachycardia were recognized together while one mnemonic, pupil, dry surface, temperature, pulse, ECG interval, or laboratory value remained insufficient alone.' },
      { id: 'activate-toxicology-anticholinergic-resuscitation-cooling-airway-toxicology-monitoring-and-compassionate-safety-ownership', statement: 'Activate resuscitation, cooling, airway, toxicology, monitoring, and compassionate safety ownership.', measure: 'Qualified emergency, critical-care, nursing, pharmacy, cooling, airway, poison-center or medical-toxicology, laboratory, bladder, renal, monitoring and compassionate-safety ownership were recorded without learner restraint, cooling, catheter, drug, dose, route, access, or procedure selection.' },
      { id: 'review-toxicology-anticholinergic-supplied-temperature-cns-ecg-renal-ck-retention-and-differential-boundary', statement: 'Review supplied temperature, CNS, ECG, renal, CK, retention, and differential evidence.', measure: 'The supplied core temperature, mental state, sweating, neuromuscular findings, ECG, acid-base, lactate, renal, CK, urinary-retention, coingestion and competing-syndrome boundaries were integrated without learner acquisition, calculation, interpretation, diagnosis, exclusion, or eligibility.' },
      { id: 'record-toxicology-anticholinergic-bounded-qualified-cooling-support-sedation-seizure-surveillance-and-physostigmine-eligibility-intent-with-strict-later-review', statement: 'Record bounded qualified cooling, support, sedation, surveillance, and antidote-eligibility intent, then review a strict later report.', measure: 'Qualified rapid cooling, supportive care, sedation or seizure care if needed, serial temperature, renal, CK and bladder surveillance, and toxicologist-led physostigmine eligibility intent were recorded without method, product, dose, rate, target, route, access, catheter, restraint, or delivery; the fixed later report was reviewed after elapsed time.' },
      { id: 'handoff-toxicology-anticholinergic-rebound-delirium-hyperthermia-retention-rhabdomyolysis-seizure-coingestion-and-active-risk', statement: 'Hand off rebound delirium, hyperthermia, retention, rhabdomyolysis, seizure, coingestion, and active risk.', measure: 'The handoff preserved serial temperature, mental-state, airway, ECG, urine, renal, CK, seizure, coingestion, exposure-purity, rebound, compassionate safety, disposition and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: [
      'American Heart Association. 2025 Guidelines for CPR and ECC. Part 10, Section 16.2, Adults with Life-Threatening Hyperthermia. Consulted 2026-08-26.',
      'National Library of Medicine. StatPearls: Anticholinergic Toxicity. Consulted 2026-08-26.',
    ] },
    limitations: ['anticholinergic-exposure-delirium-hyperthermia-retention-ecg-and-response-are-authored', 'anticholinergic-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-anticholinergic-diagnosis-cooling-restraint-sedation-physostigmine-bladder-care-or-outcome'],
  },
  patient: {
    ageYears: 29, sex: 'female', heightCm: 166, weightKg: 64, asaClass: 2,
    diagnosis: 'Authored suspected isolated anticholinergic hyperthermia-delirium pattern', procedure: 'calm hyperthermia, delirium, ECG, supportive-care, antidote-boundary, reassessment, and handoff practice',
    comorbidities: ['Supplied severe agitated delirium requires qualified compassionate safety ownership'], medications: ['No regular medicines supplied; exact amount and exposure purity remain qualified-team work'], allergies: ['No known drug allergies'], fasting: 'Not relevant to the toxicology fixture',
    baseline: { heartRateBpm: 138, meanArterialMmHg: 96, strokeVolumeMl: 62, hemoglobinGPerDl: 13.8, bloodVolumeMl: 4_400, coreTemperatureC: 40.3, arterialStiffness: 1, baroreflexGain: 0.35, fixedStrokeVolume: true },
    airway: { difficulty: 0.15, difficultMaskVentilation: false, assessment: 'Severely delirious and agitated with dry mucosa; breathing spontaneously and handling secretions' }, respiratory: { profile: 'healthy' },
  },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 450, respiratoryRateBpm: 12, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'anticholinergic-hyperthermia-rhythm', type: 'rhythm-change', target: 'sinus-tachycardia', atTick: 0, severity: 'critical', message: 'The bedside teaching trace shows authored sinus tachycardia. It is not a diagnostic 12-lead ECG or a sodium-bicarbonate, physostigmine, rate-control, or cardioversion instruction.' },
    { id: 'anticholinergic-hyperthermia-presentation', type: 'narrative', target: 'anticholinergic-hyperthermia-delirium-transition', atTick: 0, severity: 'critical', message: 'A 29-year-old woman arrives 3 hours after a supplied benztropine-only ingestion. Qualified observation supplies severe agitated delirium with picking behavior and incoherent speech, bilaterally dilated pupils, dry mouth, hot flushed dry skin, reduced bowel sounds, a palpable distended bladder, and no urine since the exposure. Monitor state is sinus tachycardia 138/min, BP 132/78 mmHg (MAP 96), RR 24/min, room-air SpO2 98%, and core T 40.3°C. There is no authored diaphoresis, clonus, hyperreflexia, rigidity, fasciculation, secretion excess, seizure, trauma, focal deficit, or cardiac arrest.' },
    { id: 'anticholinergic-hyperthermia-evidence', type: 'narrative', target: 'anticholinergic-hyperthermia-delirium-transition', atTick: 0, severity: 'warning', message: 'A qualified 12-lead ECG report supplies sinus tachycardia, QRS 86 ms, and no terminal rightward QRS pattern in aVR. Qualified blood gas and laboratory reports supply pH 7.36, PCO2 38 mmHg, bicarbonate 21 mmol/L, lactate 3.2 mmol/L, sodium 142 mmol/L, potassium 3.8 mmol/L, glucose 118 mg/dL, creatinine 1.1 mg/dL, and CK 820 U/L. Exact amount, formulation, coingestants, pregnancy status, infection, environmental exposure, endocrine cause, and exposure purity remain qualified-team work. One pupil, dry surface, temperature, pulse, mnemonic, ECG interval, or laboratory value does not independently diagnose, exclude alternatives, grade severity, or establish antidote eligibility.' },
    { id: 'anticholinergic-hyperthermia-boundary', type: 'narrative', target: 'anticholinergic-hyperthermia-delirium-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile product, 3-hour clock, severe delirium, mydriasis, dry flushed surfaces, absent sweating, urinary retention, reduced bowel sounds, temperature, tachycardia, ECG, complications, and whole patient; recognize the central and peripheral anticholinergic pattern without mnemonic-, temperature-, pupil-, or dryness-only closure; activate emergency, critical-care, nursing, pharmacy, rapid-cooling, airway, poison-center or medical-toxicology, laboratory, renal, bladder, monitoring, and compassionate-safety ownership; then review supplied temperature, CNS, sweating, neuromuscular, ECG, acid-base, lactate, renal, CK, retention, coingestion, exposure-purity, and competing-syndrome boundaries. The learner may record only bounded qualified rapid cooling and supportive care, sedation or seizure care if needed, serial temperature, renal, CK and bladder surveillance, and toxicologist-led physostigmine eligibility intent. No cooling method, fluid, sedative, physostigmine product, dose, rate, target, route, access, restraint, catheter, airway, ventilation, or delivery is exposed. After elapsed simulated time, a strict fixed 30-minute qualified-team report supplies active cooling and supportive care, qualified sedation, T 38.6°C, HR 106/min, BP 124/72 mmHg (MAP 89), calmer but still confused mentation, and persistent urinary retention. This authored response does not prove individualized treatment effect, exposure purity, durable temperature control, renal safety, rhabdomyolysis exclusion, seizure exclusion, safe disposition, or outcome. After another elapsed interval, hand off rebound delirium, hyperthermia, airway, ECG, urinary retention, renal and CK injury, seizure, coingestion, exposure purity, compassionate safety, disposition, and outcome risk. Controls do not take history; examine; acquire, calculate, or interpret monitoring, ECG, temperature, blood gas, chemistry, CK, urine or another test; diagnose or exclude; select or deliver cooling, fluid, sedation, physostigmine, drug, dose, route, access, restraint, catheter, airway, ventilation, transport, or procedure; determine antidote eligibility, disposition, prognosis, or safety; or predict response, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'anticholinergic-trajectory', objectiveId: 'reconcile-toxicology-anticholinergic-product-clock-delirium-temperature-dryness-retention-ecg-and-whole-patient', question: 'Which product, clock, delirium, temperature, dryness, retention, ECG, and whole-patient findings established the trajectory?' },
    { id: 'anticholinergic-recognition', objectiveId: 'recognize-toxicology-anticholinergic-central-and-peripheral-pattern-without-mnemonic-temperature-or-pupil-only-closure', question: 'Why was this a coupled central and peripheral pattern rather than a mnemonic, temperature, pupil, or dry surface alone?' },
    { id: 'anticholinergic-support', objectiveId: 'activate-toxicology-anticholinergic-resuscitation-cooling-airway-toxicology-monitoring-and-compassionate-safety-ownership', question: 'Which resuscitation, cooling, airway, toxicology, monitoring, bladder, renal, and compassionate-safety owners needed to begin together?' },
    { id: 'anticholinergic-evidence', objectiveId: 'review-toxicology-anticholinergic-supplied-temperature-cns-ecg-renal-ck-retention-and-differential-boundary', question: 'How did temperature, CNS, ECG, renal, CK, retention, coingestion, and competing-syndrome evidence remain coupled?' },
    { id: 'anticholinergic-reassessment', objectiveId: 'record-toxicology-anticholinergic-bounded-qualified-cooling-support-sedation-seizure-surveillance-and-physostigmine-eligibility-intent-with-strict-later-review', question: 'What did bounded qualified support and antidote-eligibility intent plus the strict later report establish without proving durable safety or treatment effect?' },
    { id: 'anticholinergic-handoff', objectiveId: 'handoff-toxicology-anticholinergic-rebound-delirium-hyperthermia-retention-rhabdomyolysis-seizure-coingestion-and-active-risk', question: 'Which rebound delirium, temperature, urinary, renal, CK, seizure, coingestion, safety, and outcome risks stayed open?' },
  ] },
};
