/** Beta-blocker cardiogenic-shock recognition, qualified rescue, and reassessment. */
import type { Scenario } from '@anesthesia/scenarios/types';

export const BETA_BLOCKER_CARDIOGENIC_SHOCK: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'beta-blocker-cardiogenic-shock', version: '0.1.0', maturity: 'preview',
    title: 'Beta-blocker toxicity: perfusion is more than pulse rate', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: [
      { id: 'reconcile-toxicology-beta-blocker-product-clock-pulse-perfusion-mentation-glucose-ecg-and-whole-patient', statement: 'Reconcile product, clock, pulse, perfusion, mentation, glucose, ECG, and the whole patient.', measure: 'The declared metoprolol exposure, 2-hour clock, bradycardia, shock, drowsiness, vomiting, low glucose, supplied ECG, oxygenation, and whole-patient state were connected without learner history, examination, monitoring, testing, ECG interpretation, or diagnosis.' },
      { id: 'recognize-toxicology-beta-blocker-cardiogenic-shock-pattern-without-pulse-only-closure', statement: 'Recognize beta-blocker cardiogenic shock without pulse-only closure.', measure: 'Declared exposure, bradycardia, hypotension, impaired mentation, low glucose, conduction delay, and reduced contractility were recognized together while one pulse, interval, glucose value, or history statement remained insufficient alone.' },
      { id: 'activate-toxicology-beta-blocker-poison-center-resuscitation-cardiac-glucose-airway-and-safety-ownership', statement: 'Activate toxicology, resuscitation, cardiac, glucose, airway, and safety ownership.', measure: 'Qualified toxicology, emergency, critical-care, nursing, pharmacy, cardiac, glucose, airway-capable, perfusion-monitoring, and compassionate safety ownership were recorded without learner fluid, drug, dose, route, access, airway, pacing, or procedure selection.' },
      { id: 'review-toxicology-beta-blocker-supplied-ecg-perfusion-contractility-glucose-electrolyte-prior-care-and-rescue-boundary', statement: 'Review supplied ECG, perfusion, contractility, glucose, electrolyte, prior-care, and rescue evidence.', measure: 'The supplied ECG, pressure, mental state, cardiac-function report, glucose, acid-base, lactate, electrolytes, renal state, prior atropine and vasopressor care, coingestion limits, phenotype, and rescue boundary were integrated without learner acquisition, calculation, interpretation, diagnosis, or eligibility.' },
      { id: 'record-toxicology-beta-blocker-bounded-qualified-vasopressor-glucagon-insulin-euglycemia-and-rescue-intent-with-strict-later-review', statement: 'Record bounded qualified rescue intent, then review a strict later report.', measure: 'Qualified-team vasopressor, glucagon, high-dose-insulin/euglycemia, glucose-electrolyte-volume surveillance, and refractory-rescue preparedness were recorded without product, dose, rate, target, access, fluid, airway, pacing, lipid, ECLS, or delivery; the fixed later perfusion and metabolic report was reviewed after elapsed time.' },
      { id: 'handoff-toxicology-beta-blocker-recurrent-shock-bradycardia-hypoglycemia-electrolyte-volume-rescue-and-active-risk', statement: 'Hand off recurrent shock, bradycardia, hypoglycemia, electrolyte, volume, rescue, and active risk.', measure: 'The handoff preserved serial perfusion, rhythm, mentation, glucose, potassium, volume, coingestion, recurrence, rescue, compassionate safety, disposition, and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: [
      'American Heart Association. Part 10: Adult and Pediatric Special Circumstances of Resuscitation. Section 21.4, life-threatening beta-blocker poisoning. Consulted 2026-08-26.',
      'DailyMed. Metoprolol tartrate tablets prescribing information. Set ID 809c6386-0039-42ff-a03e-e42733e229b8. Overdosage section. Revised 2023.',
    ] },
    limitations: ['beta-blocker-exposure-perfusion-metabolic-prior-care-transition-and-response-are-authored', 'beta-blocker-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-beta-blocker-diagnosis-treatment-pacing-dialysis-rescue-or-outcome'],
  },
  patient: {
    ageYears: 38, sex: 'female', heightCm: 168, weightKg: 72, asaClass: 2,
    diagnosis: 'Authored suspected metoprolol beta-blocker cardiogenic-shock pattern', procedure: 'calm perfusion, metabolic-risk, rescue-boundary, reassessment, and handoff practice',
    comorbidities: ['Supplied intentional ingestion prompts compassionate qualified safety assessment'], medications: ['Declared immediate-release metoprolol tartrate exposure; exact quantity and coingestants remain qualified-team work'], allergies: ['No known drug allergies'], fasting: 'Not relevant to the toxicology fixture',
    baseline: { heartRateBpm: 42, meanArterialMmHg: 51, strokeVolumeMl: 42, hemoglobinGPerDl: 13.4, bloodVolumeMl: 4_800, coreTemperatureC: 36.5, arterialStiffness: 1, baroreflexGain: 0.25, fixedStrokeVolume: true },
    airway: { difficulty: 0.1, difficultMaskVentilation: false, assessment: 'Drowsy but arousable after vomiting, breathing spontaneously, and handling secretions initially' }, respiratory: { profile: 'healthy' },
  },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 430, respiratoryRateBpm: 12, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'beta-blocker-cardiogenic-shock-rhythm', type: 'rhythm-change', target: 'sinus-bradycardia', atTick: 0, severity: 'critical', message: 'The bedside teaching trace shows the authored sinus bradycardia. It is not a diagnostic 12-lead ECG or a pacing indication.' },
    { id: 'beta-blocker-cardiogenic-shock-presentation', type: 'narrative', target: 'beta-blocker-cardiogenic-shock-transition', atTick: 0, severity: 'critical', message: 'A 38-year-old woman is brought 2 hours after a witnessed intentional immediate-release metoprolol-tartrate-only ingestion. Exact quantity and coingestants remain qualified-team work. She is drowsy but arousable after vomiting. Monitor state is sinus bradycardia 42/min, BP 72/40 mmHg (MAP 51), RR 18/min, room-air SpO2 97%, and T 36.5°C. She breathes spontaneously and handles secretions. There is no authored seizure, pulmonary edema, bronchospasm, trauma, focal deficit, or cardiac arrest.' },
    { id: 'beta-blocker-cardiogenic-shock-evidence', type: 'narrative', target: 'beta-blocker-cardiogenic-shock-transition', atTick: 0, severity: 'warning', message: 'A qualified 12-lead ECG report supplies sinus bradycardia, PR 220 ms, and QRS 92 ms. Qualified focused cardiac assessment supplies globally reduced LV systolic contraction without pulmonary edema. Glucose is 62 mg/dL, pH 7.31, bicarbonate 19 mmol/L, lactate 3.8 mmol/L, sodium 138 mmol/L, potassium 4.2 mmol/L, and creatinine 0.8 mg/dL. A fixed treating-team report supplies protocol-selected atropine and initial vasopressor care with persistent shock. The learner does not acquire, calculate, interpret, select, or deliver them. Product, formulation, clock, perfusion, rhythm, glucose, acid-base, electrolytes, renal state, coingestants, and phenotype remain coupled.' },
    { id: 'beta-blocker-cardiogenic-shock-boundary', type: 'narrative', target: 'beta-blocker-cardiogenic-shock-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile product, clock, pulse, perfusion, mentation, glucose, supplied ECG, oxygenation, and whole patient; recognize the beta-blocker cardiogenic-shock pattern without pulse-only or pacing-only closure; activate poison-center or medical-toxicology, emergency, critical-care, nursing, pharmacy, cardiac, glucose, airway-capable, perfusion, and compassionate safety ownership; then review supplied ECG, contractility, pressure, mental state, glucose, acid-base, lactate, electrolyte, renal, prior-care, coingestion, phenotype, and rescue boundaries. The learner may record only bounded qualified vasopressor, glucagon, high-dose-insulin/euglycemia, glucose-electrolyte-volume surveillance, and refractory-rescue intent. No product, dose, rate, target, access, fluid, airway, pacing, dialysis, lipid, ECLS, or delivery is exposed. After elapsed simulated time, a strict fixed 45-minute report supplies clearer mentation, HR 58/min, BP 98/60 mmHg (MAP 73), glucose 104 mg/dL, potassium 3.5 mmol/L, lactate 2.8 mmol/L, and no new hypoxemia or pulmonary edema. This authored response does not prove individualized treatment effect, durable perfusion, glucose or electrolyte stability, coingestant exclusion, safe disposition, or outcome. After another elapsed interval, hand off recurrent shock, bradycardia, AV block, hypoglycemia, hypokalemia, volume overload, rescue, safety, disposition, and outcome risk. Controls do not take history; examine; acquire, calculate, or interpret monitoring, ECG, imaging, blood gas, chemistry, or another test; diagnose; select or deliver decontamination, glucose, electrolyte, fluid, drug, dose, route, access, infusion, airway, ventilation, pacing, dialysis, lipid, ECLS, transport, or procedure; determine eligibility, disposition, prognosis, or safety; or predict response, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'beta-blocker-trajectory', objectiveId: 'reconcile-toxicology-beta-blocker-product-clock-pulse-perfusion-mentation-glucose-ecg-and-whole-patient', question: 'Which product, clock, pulse, perfusion, mentation, glucose, ECG, and whole-patient findings established the trajectory?' },
    { id: 'beta-blocker-recognition', objectiveId: 'recognize-toxicology-beta-blocker-cardiogenic-shock-pattern-without-pulse-only-closure', question: 'Why was this a beta-blocker cardiogenic-shock pattern rather than a pulse or pacing problem alone?' },
    { id: 'beta-blocker-support', objectiveId: 'activate-toxicology-beta-blocker-poison-center-resuscitation-cardiac-glucose-airway-and-safety-ownership', question: 'Which toxicology, resuscitation, cardiac, metabolic, airway, and safety owners needed to begin together?' },
    { id: 'beta-blocker-evidence', objectiveId: 'review-toxicology-beta-blocker-supplied-ecg-perfusion-contractility-glucose-electrolyte-prior-care-and-rescue-boundary', question: 'How did supplied ECG, perfusion, contractility, glucose, electrolytes, prior care, and rescue evidence remain coupled?' },
    { id: 'beta-blocker-reassessment', objectiveId: 'record-toxicology-beta-blocker-bounded-qualified-vasopressor-glucagon-insulin-euglycemia-and-rescue-intent-with-strict-later-review', question: 'What did bounded qualified rescue intent and the strict later report establish without proving durable safety or treatment effect?' },
    { id: 'beta-blocker-handoff', objectiveId: 'handoff-toxicology-beta-blocker-recurrent-shock-bradycardia-hypoglycemia-electrolyte-volume-rescue-and-active-risk', question: 'Which recurrent shock, rhythm, glucose, electrolyte, volume, rescue, safety, and outcome risks stayed open?' },
  ] },
};
