/** Calcium-channel-blocker mixed-shock recognition, qualified rescue, and reassessment. */
import type { Scenario } from '@anesthesia/scenarios/types';

export const CALCIUM_CHANNEL_BLOCKER_SHOCK: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'calcium-channel-blocker-shock', version: '0.1.0', maturity: 'preview',
    title: 'Calcium-channel blocker toxicity: read the glucose with the shock', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: [
      { id: 'reconcile-toxicology-calcium-channel-blocker-product-formulation-clock-perfusion-rhythm-glucose-and-whole-patient', statement: 'Reconcile product, formulation, clock, perfusion, rhythm, glucose, and the whole patient.', measure: 'The declared extended-release diltiazem exposure, 5-hour clock, bradycardia, AV block, shock, drowsiness, hyperglycemia, supplied ECG, oxygenation, and whole-patient state were connected without learner history, examination, monitoring, testing, ECG interpretation, or diagnosis.' },
      { id: 'recognize-toxicology-calcium-channel-blocker-mixed-shock-pattern-without-glucose-or-pulse-only-closure', statement: 'Recognize the calcium-channel-blocker mixed-shock pattern without glucose- or pulse-only closure.', measure: 'Declared exposure, bradycardia, complete AV block, hypotension, impaired mentation, hyperglycemia, reduced contractility, and vasodilation were recognized together while one glucose, pulse, interval, or history statement remained insufficient alone.' },
      { id: 'activate-toxicology-calcium-channel-blocker-poison-center-resuscitation-cardiac-metabolic-airway-and-safety-ownership', statement: 'Activate toxicology, resuscitation, cardiac, metabolic, airway, and safety ownership.', measure: 'Qualified toxicology, emergency, critical-care, nursing, pharmacy, cardiac, metabolic, airway-capable, perfusion-monitoring, and compassionate safety ownership were recorded without learner fluid, drug, dose, route, access, airway, pacing, or procedure selection.' },
      { id: 'review-toxicology-calcium-channel-blocker-supplied-ecg-perfusion-contractility-glucose-electrolyte-prior-care-and-rescue-boundary', statement: 'Review supplied ECG, perfusion, contractility, glucose, electrolyte, prior-care, and rescue evidence.', measure: 'The supplied ECG, pressure, mental state, cardiac-function report, glucose, acid-base, lactate, electrolytes, renal state, prior care, prolonged-release risk, coingestion limits, phenotype, and rescue boundary were integrated without learner acquisition, calculation, interpretation, diagnosis, or eligibility.' },
      { id: 'record-toxicology-calcium-channel-blocker-bounded-qualified-vasopressor-calcium-insulin-euglycemia-and-rescue-intent-with-strict-later-review', statement: 'Record bounded qualified rescue intent, then review a strict later report.', measure: 'Qualified-team vasopressor, calcium, high-dose-insulin/euglycemia, glucose-electrolyte-volume surveillance, and refractory-rescue preparedness were recorded without product, dose, rate, target, access, fluid, airway, pacing, lipid, ECLS, or delivery; the fixed later perfusion and metabolic report was reviewed after elapsed time.' },
      { id: 'handoff-toxicology-calcium-channel-blocker-recurrent-shock-av-block-hyperglycemia-electrolyte-volume-rescue-and-active-risk', statement: 'Hand off recurrent shock, AV block, hyperglycemia, electrolyte, volume, rescue, and active risk.', measure: 'The handoff preserved serial perfusion, rhythm, mentation, glucose, potassium, volume, prolonged absorption, coingestion, recurrence, rescue, compassionate safety, disposition, and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: [
      'American Heart Association. Part 10: Adult and Pediatric Special Circumstances of Resuscitation. Section 21.5, life-threatening calcium-channel-blocker poisoning. Consulted 2026-08-26.',
      'DailyMed. Diltiazem hydrochloride extended-release capsules prescribing information. Set ID 11b43a17-8038-462b-8902-259431ad5256. Overdosage section. Revised 2023.',
    ] },
    limitations: ['calcium-channel-blocker-exposure-perfusion-metabolic-prior-care-transition-and-response-are-authored', 'calcium-channel-blocker-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-calcium-channel-blocker-diagnosis-treatment-pacing-decontamination-rescue-or-outcome'],
  },
  patient: {
    ageYears: 56, sex: 'male', heightCm: 178, weightKg: 84, asaClass: 3,
    diagnosis: 'Authored suspected extended-release diltiazem mixed-shock pattern', procedure: 'calm perfusion, conduction, metabolic-risk, rescue-boundary, reassessment, and handoff practice',
    comorbidities: ['Supplied intentional ingestion prompts compassionate qualified safety assessment'], medications: ['Declared extended-release diltiazem exposure; exact quantity and coingestants remain qualified-team work'], allergies: ['No known drug allergies'], fasting: 'Not relevant to the toxicology fixture',
    baseline: { heartRateBpm: 34, meanArterialMmHg: 47, strokeVolumeMl: 38, hemoglobinGPerDl: 13.8, bloodVolumeMl: 5_200, coreTemperatureC: 36.3, arterialStiffness: 0.8, baroreflexGain: 0.2, fixedStrokeVolume: true },
    airway: { difficulty: 0.1, difficultMaskVentilation: false, assessment: 'Drowsy but answers briefly, breathing spontaneously, and handling secretions initially' }, respiratory: { profile: 'healthy' },
  },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 480, respiratoryRateBpm: 12, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'calcium-channel-blocker-shock-rhythm', type: 'rhythm-change', target: 'complete-heart-block', atTick: 0, severity: 'critical', message: 'The bedside teaching trace shows the authored complete AV block with a slow escape rhythm. It is not a diagnostic 12-lead ECG or a pacing indication.' },
    { id: 'calcium-channel-blocker-shock-presentation', type: 'narrative', target: 'calcium-channel-blocker-shock-transition', atTick: 0, severity: 'critical', message: 'A 56-year-old man is brought 5 hours after a witnessed intentional extended-release diltiazem-only ingestion. Exact quantity and coingestants remain qualified-team work. He is drowsy but answers briefly. Monitor state is a slow escape rhythm 34/min, BP 68/36 mmHg (MAP 47), RR 18/min, room-air SpO2 97%, and T 36.3°C. He breathes spontaneously and handles secretions. His extremities are warm. There is no authored seizure, pulmonary edema, bronchospasm, trauma, focal deficit, or cardiac arrest.' },
    { id: 'calcium-channel-blocker-shock-evidence', type: 'narrative', target: 'calcium-channel-blocker-shock-transition', atTick: 0, severity: 'warning', message: 'A qualified 12-lead ECG report supplies complete AV block with atrial rate 78/min, ventricular escape 34/min, and QRS 104 ms. Qualified focused cardiac assessment supplies globally reduced LV systolic contraction without pulmonary edema and low systemic vascular tone. Glucose is 238 mg/dL, pH 7.29, bicarbonate 18 mmol/L, lactate 4.6 mmol/L, sodium 137 mmol/L, potassium 4.1 mmol/L, and creatinine 1.0 mg/dL. A fixed treating-team report supplies protocol-selected atropine and initial vasopressor care with persistent shock. The learner does not acquire, calculate, interpret, select, or deliver them. Product, formulation, clock, prolonged absorption, perfusion, conduction, glucose, acid-base, electrolytes, renal state, coingestants, and phenotype remain coupled.' },
    { id: 'calcium-channel-blocker-shock-boundary', type: 'narrative', target: 'calcium-channel-blocker-shock-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile product, formulation, clock, perfusion, rhythm, mentation, glucose, supplied ECG, oxygenation, and whole patient; recognize the calcium-channel-blocker mixed-shock pattern without glucose-only, pulse-only, or pacing-only closure; activate poison-center or medical-toxicology, emergency, critical-care, nursing, pharmacy, cardiac, metabolic, airway-capable, perfusion, and compassionate safety ownership; then review supplied ECG, contractility, vascular tone, pressure, mental state, glucose, acid-base, lactate, electrolyte, renal, prior-care, prolonged-release, coingestion, phenotype, and rescue boundaries. The learner may record only bounded qualified vasopressor, calcium, high-dose-insulin/euglycemia, glucose-electrolyte-volume surveillance, and refractory-rescue intent. No product, dose, rate, target, access, fluid, airway, pacing, decontamination, lipid, methylene blue, ECLS, or delivery is exposed. After elapsed simulated time, a strict fixed 45-minute report supplies clearer mentation, sinus rhythm 64/min, BP 96/58 mmHg (MAP 71), glucose 176 mg/dL, potassium 3.4 mmol/L, lactate 3.0 mmol/L, and no new hypoxemia or pulmonary edema. This authored response does not prove individualized treatment effect, durable perfusion, glucose or electrolyte stability, completed absorption, coingestant exclusion, safe disposition, or outcome. After another elapsed interval, hand off recurrent shock, bradycardia, AV block, hyperglycemia or hypoglycemia, hypokalemia, volume overload, prolonged absorption, rescue, safety, disposition, and outcome risk. Controls do not take history; examine; acquire, calculate, or interpret monitoring, ECG, imaging, blood gas, chemistry, or another test; diagnose; select or deliver decontamination, glucose, electrolyte, fluid, drug, dose, route, access, infusion, airway, ventilation, pacing, lipid, methylene blue, ECLS, transport, or procedure; determine eligibility, disposition, prognosis, or safety; or predict response, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'calcium-channel-blocker-trajectory', objectiveId: 'reconcile-toxicology-calcium-channel-blocker-product-formulation-clock-perfusion-rhythm-glucose-and-whole-patient', question: 'Which product, formulation, clock, perfusion, rhythm, glucose, and whole-patient findings established the trajectory?' },
    { id: 'calcium-channel-blocker-recognition', objectiveId: 'recognize-toxicology-calcium-channel-blocker-mixed-shock-pattern-without-glucose-or-pulse-only-closure', question: 'Why was this a calcium-channel-blocker mixed-shock pattern rather than a glucose, pulse, or pacing problem alone?' },
    { id: 'calcium-channel-blocker-support', objectiveId: 'activate-toxicology-calcium-channel-blocker-poison-center-resuscitation-cardiac-metabolic-airway-and-safety-ownership', question: 'Which toxicology, resuscitation, cardiac, metabolic, airway, and safety owners needed to begin together?' },
    { id: 'calcium-channel-blocker-evidence', objectiveId: 'review-toxicology-calcium-channel-blocker-supplied-ecg-perfusion-contractility-glucose-electrolyte-prior-care-and-rescue-boundary', question: 'How did supplied ECG, perfusion, contractility, glucose, electrolytes, prior care, and prolonged-release evidence remain coupled?' },
    { id: 'calcium-channel-blocker-reassessment', objectiveId: 'record-toxicology-calcium-channel-blocker-bounded-qualified-vasopressor-calcium-insulin-euglycemia-and-rescue-intent-with-strict-later-review', question: 'What did bounded qualified rescue intent and the strict later report establish without proving durable safety or treatment effect?' },
    { id: 'calcium-channel-blocker-handoff', objectiveId: 'handoff-toxicology-calcium-channel-blocker-recurrent-shock-av-block-hyperglycemia-electrolyte-volume-rescue-and-active-risk', question: 'Which recurrent shock, conduction, glucose, electrolyte, volume, absorption, rescue, safety, and outcome risks stayed open?' },
  ] },
};
