/** Organophosphate cholinergic respiratory-failure recognition, safety, and reassessment. */
import type { Scenario } from '@anesthesia/scenarios/types';

export const CHOLINERGIC_PESTICIDE_RESPIRATORY_FAILURE: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'cholinergic-pesticide-respiratory-failure', version: '0.1.0', maturity: 'draft',
    title: 'Cholinergic poisoning: protect the team, then clear the air', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: [
      { id: 'reconcile-toxicology-cholinergic-product-route-secondary-contamination-secretions-breathing-weakness-cns-and-whole-patient', statement: 'Reconcile product, route, secondary contamination, secretions, breathing, weakness, CNS, and the whole patient.', measure: 'The declared organophosphate exposure, wet clothing, miosis, secretions, bronchospasm, hypoxemia, bradycardia, vomiting, fasciculations, weakness, confusion, and whole-patient state were connected without learner history, examination, monitoring, testing, or diagnosis.' },
      { id: 'recognize-toxicology-cholinergic-muscarinic-nicotinic-and-cns-pattern-without-mnemonic-or-cholinesterase-only-closure', statement: 'Recognize the muscarinic, nicotinic, and CNS pattern without mnemonic- or cholinesterase-only closure.', measure: 'Declared exposure, parasympathetic excess, fasciculations and weakness, and altered mentation were recognized together while one mnemonic, pupil, pulse, secretion, or cholinesterase result remained insufficient alone.' },
      { id: 'activate-toxicology-cholinergic-ppe-decontamination-airway-resuscitation-poison-center-and-safety-ownership', statement: 'Activate PPE, decontamination, airway, resuscitation, toxicology, and safety ownership.', measure: 'Qualified PPE, contamination control, decontamination, emergency, critical-care, nursing, pharmacy, airway, respiratory, poison-center or medical-toxicology, and occupational-safety ownership were recorded without learner clothing removal, washing, airway, drug, dose, route, access, or procedure selection.' },
      { id: 'review-toxicology-cholinergic-supplied-respiratory-neuromuscular-cns-exposure-cholinesterase-and-airway-boundary', statement: 'Review supplied respiratory, neuromuscular, CNS, exposure, cholinesterase, and airway evidence.', measure: 'The supplied gas exchange, secretions, bronchospasm, fasciculation, weakness, mental state, exposure route, coformulant limits, laboratory cholinesterase report, secondary-contamination risk, and early-airway boundary were integrated without learner acquisition, calculation, interpretation, diagnosis, or eligibility.' },
      { id: 'record-toxicology-cholinergic-bounded-qualified-atropine-pralidoxime-benzodiazepine-airway-and-surveillance-intent-with-strict-later-review', statement: 'Record bounded qualified antidote, airway, seizure, and surveillance intent, then review a strict later report.', measure: 'Qualified-team atropine, organophosphate-specific pralidoxime, benzodiazepine-if-needed, early airway and ventilation, decontamination, and respiratory-neuromuscular surveillance intent were recorded without product, dose, rate, target, access, technique, device, neuromuscular blocker, or delivery; the fixed later report was reviewed after elapsed time.' },
      { id: 'handoff-toxicology-cholinergic-recurrent-secretions-bronchospasm-weakness-intermediate-syndrome-exposure-seizure-and-active-risk', statement: 'Hand off recurrent secretions, bronchospasm, weakness, intermediate syndrome, exposure, seizure, and active risk.', measure: 'The handoff preserved serial airway and ventilation, secretions, bronchospasm, strength, CNS, seizure, secondary exposure, decontamination, recurrence, intermediate-syndrome, compassionate safety, disposition, and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: [
      'American Heart Association. Part 10: Adult and Pediatric Special Circumstances of Resuscitation. Section 21.12, life-threatening organophosphate or carbamate poisoning. Consulted 2026-08-26.',
      'US Environmental Protection Agency. Recognition and Management of Pesticide Poisonings. Sixth edition, Chapter 5, Organophosphates. 2013.',
    ] },
    limitations: ['cholinergic-exposure-respiratory-neuromuscular-cns-decontamination-transition-and-response-are-authored', 'cholinergic-controls-reconcile-recognize-safety-support-review-intent-reassess-and-handoff-only', 'no-live-cholinergic-diagnosis-decontamination-atropine-pralidoxime-airway-seizure-care-or-outcome'],
  },
  patient: {
    ageYears: 46, sex: 'male', heightCm: 175, weightKg: 79, asaClass: 2,
    diagnosis: 'Authored suspected organophosphate cholinergic respiratory-failure pattern', procedure: 'calm contamination, airway, secretion, neuromuscular-risk, antidote-boundary, reassessment, and handoff practice',
    comorbidities: ['Supplied occupational exposure prompts qualified workplace and co-worker safety review'], medications: ['No regular medicines supplied; exact pesticide formulation and coformulants remain qualified-team work'], allergies: ['No known drug allergies'], fasting: 'Not relevant to the toxicology fixture',
    baseline: { heartRateBpm: 48, meanArterialMmHg: 62, strokeVolumeMl: 48, hemoglobinGPerDl: 14.2, bloodVolumeMl: 5_100, coreTemperatureC: 36.7, arterialStiffness: 1, baroreflexGain: 0.2, fixedStrokeVolume: true },
    airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Confused, copiously salivating, vomiting, tiring, and not reliably protecting the airway' }, respiratory: { profile: 'healthy' },
  },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 460, respiratoryRateBpm: 12, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'cholinergic-pesticide-rhythm', type: 'rhythm-change', target: 'sinus-bradycardia', atTick: 0, severity: 'critical', message: 'The bedside teaching trace shows authored sinus bradycardia. It is not a diagnostic 12-lead ECG or an atropine-dose or pacing instruction.' },
    { id: 'cholinergic-pesticide-presentation', type: 'narrative', target: 'cholinergic-pesticide-respiratory-failure-transition', atTick: 0, severity: 'critical', message: 'A 46-year-old greenhouse worker is found 45 minutes after an organophosphate insecticide concentrate splashed across his clothing during mixing in an enclosed area. He arrives in still-wet work clothes before formal decontamination. Qualified observation supplies confusion, pinpoint pupils, diaphoresis, lacrimation, copious salivation and bronchial secretions, vomiting, wheeze, diffuse muscle fasciculations, and weak neck flexion. Monitor state is sinus bradycardia 48/min, BP 86/50 mmHg (MAP 62), RR 30/min with shallow tiring breaths, room-air SpO2 86%, and T 36.7°C. There is no authored seizure, trauma, focal deficit, thermal injury, or cardiac arrest.' },
    { id: 'cholinergic-pesticide-evidence', type: 'narrative', target: 'cholinergic-pesticide-respiratory-failure-transition', atTick: 0, severity: 'warning', message: 'Qualified respiratory assessment supplies bronchorrhea, bronchospasm, weak cough, shallow tiring ventilation, and no isolated structural airway obstruction. A qualified laboratory report supplies plasma cholinesterase markedly below its laboratory reference interval, pH 7.27, PCO2 52 mmHg, bicarbonate 23 mmol/L, lactate 3.6 mmol/L, sodium 139 mmol/L, potassium 4.0 mmol/L, glucose 112 mg/dL, and creatinine 0.9 mg/dL. Product label, exact concentration, coformulants, additional routes, co-worker exposure, and red-cell acetylcholinesterase remain qualified-team work. One pupil, pulse, secretion, mnemonic, or cholinesterase report does not independently diagnose or grade the case.' },
    { id: 'cholinergic-pesticide-boundary', type: 'narrative', target: 'cholinergic-pesticide-respiratory-failure-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile product, route, wet-clothing secondary-contamination risk, secretions, breathing, weakness, CNS, oxygenation, circulation, and whole patient; recognize the muscarinic, nicotinic, and CNS cholinergic pattern without mnemonic-only or cholinesterase-only closure; activate appropriate PPE, contamination control, qualified clothing removal and dermal decontamination, emergency, critical-care, nursing, pharmacy, airway, respiratory, poison-center or medical-toxicology, occupational-safety, and co-worker ownership; then review supplied gas exchange, secretions, bronchospasm, fasciculation, weakness, mental state, exposure, coformulant, cholinesterase, secondary-contamination, and early-airway boundaries. The learner may record only bounded qualified immediate atropine, organophosphate-specific pralidoxime, benzodiazepine-if-needed, early airway and ventilation, decontamination, and respiratory-neuromuscular surveillance intent. No product, dose, rate, target, access, clothing removal, washing method, device, technique, neuromuscular blocker, airway, ventilation setting, or delivery is exposed. After elapsed simulated time, a strict fixed 30-minute qualified-team report supplies completed clothing removal and dermal decontamination, active qualified airway support and assisted ventilation without a supplied device or setting, markedly reduced bronchial secretions and wheeze, SpO2 96%, HR 82/min, BP 104/64 mmHg (MAP 77), and clearer mentation, while fasciculations and proximal weakness persist. Drying secretions does not prove neuromuscular recovery. This authored response does not prove individualized treatment effect, complete decontamination, durable ventilation, co-worker safety, seizure exclusion, strength recovery, safe disposition, or outcome. After another elapsed interval, hand off recurrent secretions, bronchospasm, hypoxemia, weakness, delayed intermediate syndrome, CNS or seizure change, secondary exposure, decontamination, antidote and airway contingencies, safety, disposition, and outcome risk. Controls do not take history; examine; acquire, calculate, or interpret monitoring, ECG, blood gas, cholinesterase, chemistry, or another test; diagnose; select or deliver clothing removal, irrigation, decontamination, oxygen, suction, fluid, atropine, pralidoxime, benzodiazepine, drug, dose, route, access, infusion, airway, ventilation, neuromuscular blocker, transport, or procedure; determine eligibility, disposition, prognosis, workplace clearance, or safety; or predict response, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'cholinergic-trajectory', objectiveId: 'reconcile-toxicology-cholinergic-product-route-secondary-contamination-secretions-breathing-weakness-cns-and-whole-patient', question: 'Which product, route, contamination, secretion, breathing, weakness, CNS, and whole-patient findings established the trajectory?' },
    { id: 'cholinergic-recognition', objectiveId: 'recognize-toxicology-cholinergic-muscarinic-nicotinic-and-cns-pattern-without-mnemonic-or-cholinesterase-only-closure', question: 'Why was this a coupled muscarinic, nicotinic, and CNS pattern rather than a mnemonic or cholinesterase result alone?' },
    { id: 'cholinergic-safety', objectiveId: 'activate-toxicology-cholinergic-ppe-decontamination-airway-resuscitation-poison-center-and-safety-ownership', question: 'Which PPE, contamination, decontamination, airway, resuscitation, toxicology, occupational, and safety owners needed to begin together?' },
    { id: 'cholinergic-evidence', objectiveId: 'review-toxicology-cholinergic-supplied-respiratory-neuromuscular-cns-exposure-cholinesterase-and-airway-boundary', question: 'How did respiratory, neuromuscular, CNS, exposure, cholinesterase, coformulant, and airway evidence remain coupled?' },
    { id: 'cholinergic-reassessment', objectiveId: 'record-toxicology-cholinergic-bounded-qualified-atropine-pralidoxime-benzodiazepine-airway-and-surveillance-intent-with-strict-later-review', question: 'What did bounded qualified antidote, airway, seizure, and surveillance intent plus the strict later report establish without proving durable safety or treatment effect?' },
    { id: 'cholinergic-handoff', objectiveId: 'handoff-toxicology-cholinergic-recurrent-secretions-bronchospasm-weakness-intermediate-syndrome-exposure-seizure-and-active-risk', question: 'Which recurrent respiratory, neuromuscular, CNS, exposure, antidote, safety, and outcome risks stayed open?' },
  ] },
};
