/** Digoxin rhythm-potassium recognition, bounded Fab intent, and reassessment. */
import type { Scenario } from '@anesthesia/scenarios/types';

export const DIGOXIN_RHYTHM_POTASSIUM: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'digoxin-rhythm-potassium', version: '0.1.0', maturity: 'draft',
    title: 'Digoxin toxicity: read the rhythm and potassium together', author: 'Open Sim Lab',
    license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced', objectives: [
      { id: 'reconcile-toxicology-digoxin-product-clock-gi-visual-perfusion-rhythm-potassium-and-whole-patient', statement: 'Reconcile product, clock, GI and visual clues, perfusion, rhythm, potassium, and the whole patient.', measure: 'The declared acute digoxin exposure, 7-hour clock, vomiting, visual disturbance, bradycardia, AV block, shock, hyperkalemia, supplied ECG, oxygenation, and whole-patient state were connected without learner history, examination, monitoring, testing, ECG interpretation, or diagnosis.' },
      { id: 'recognize-toxicology-digoxin-life-threatening-pattern-without-level-rhythm-or-potassium-only-closure', statement: 'Recognize the life-threatening digoxin pattern without level-, rhythm-, or potassium-only closure.', measure: 'Declared exposure, GI and visual symptoms, bradycardia, complete AV block, hypotension, hyperkalemia, and properly timed supplied level were recognized together while one level, rhythm, potassium value, or history statement remained insufficient alone.' },
      { id: 'activate-toxicology-digoxin-poison-center-resuscitation-cardiac-electrolyte-airway-and-safety-ownership', statement: 'Activate toxicology, resuscitation, cardiac, electrolyte, airway, and safety ownership.', measure: 'Qualified toxicology, emergency, critical-care, nursing, pharmacy, cardiac, electrolyte, airway-capable, perfusion-monitoring, and compassionate safety ownership were recorded without learner drug, dose, route, access, airway, pacing, or procedure selection.' },
      { id: 'review-toxicology-digoxin-supplied-ecg-level-timing-potassium-renal-coingestion-and-antidote-boundary', statement: 'Review supplied ECG, level timing, potassium, renal, coingestion, and antidote evidence.', measure: 'The supplied ECG, pressure, mental state, properly timed pre-Fab digoxin level, potassium, magnesium, acid-base, lactate, renal state, prior care, coingestion limits, and antidote boundary were integrated without learner acquisition, calculation, interpretation, diagnosis, or eligibility.' },
      { id: 'record-toxicology-digoxin-bounded-qualified-immune-fab-surveillance-and-rescue-intent-with-strict-later-review', statement: 'Record bounded qualified immune-Fab and rescue intent, then review a strict later report.', measure: 'Qualified-team digoxin-immune-Fab, rhythm-potassium surveillance, and refractory-arrhythmia rescue preparedness were recorded without product, vial count, dose, rate, target, access, electrolyte, pacing, dialysis, or delivery; the fixed later perfusion and electrolyte report was reviewed after elapsed time.' },
      { id: 'handoff-toxicology-digoxin-recurrent-arrhythmia-potassium-shift-level-interference-renal-rescue-and-active-risk', statement: 'Hand off recurrent arrhythmia, potassium shift, level interference, renal, rescue, and active risk.', measure: 'The handoff preserved serial perfusion, rhythm, potassium, renal function, Fab-associated level interference, recurrence, rescue, compassionate safety, disposition, and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: [
      'American Heart Association. Part 10: Adult and Pediatric Special Circumstances of Resuscitation. Section 21.8, life-threatening digoxin and cardiac-glycoside poisoning. Consulted 2026-08-26.',
      'DailyMed. Digoxin tablets prescribing information. Set ID 42d079a7-def1-4220-b71f-db2651966ffe. Overdosage section. Revised 2025.',
      'DailyMed. DigiFab digoxin immune Fab prescribing information. Set ID c05ee6a5-c98b-45f4-83fd-40781639d653. Warnings and laboratory-tests sections. Revised 2025.',
    ] },
    limitations: ['digoxin-exposure-rhythm-potassium-level-prior-care-transition-and-response-are-authored', 'digoxin-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-digoxin-diagnosis-fab-dosing-electrolyte-pacing-dialysis-rescue-or-outcome'],
  },
  patient: {
    ageYears: 67, sex: 'female', heightCm: 164, weightKg: 68, asaClass: 3,
    diagnosis: 'Authored suspected acute digoxin rhythm-potassium toxicity pattern', procedure: 'calm electrical, perfusion, electrolyte-risk, antidote-boundary, reassessment, and handoff practice',
    comorbidities: ['Supplied intentional ingestion prompts compassionate qualified safety assessment'], medications: ['Declared immediate-release digoxin exposure; exact quantity and coingestants remain qualified-team work'], allergies: ['No known drug allergies'], fasting: 'Not relevant to the toxicology fixture',
    baseline: { heartRateBpm: 36, meanArterialMmHg: 53, strokeVolumeMl: 40, hemoglobinGPerDl: 13.1, bloodVolumeMl: 4_700, coreTemperatureC: 36.4, arterialStiffness: 1.1, baroreflexGain: 0.2, fixedStrokeVolume: true },
    airway: { difficulty: 0.1, difficultMaskVentilation: false, assessment: 'Drowsy but answers briefly after repeated vomiting, breathing spontaneously, and handling secretions initially' }, respiratory: { profile: 'healthy' },
  },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 410, respiratoryRateBpm: 12, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'digoxin-rhythm-potassium-rhythm', type: 'rhythm-change', target: 'complete-heart-block', atTick: 0, severity: 'critical', message: 'The bedside teaching trace shows the authored complete AV block with a slow escape rhythm. It is not a diagnostic 12-lead ECG or a pacing indication.' },
    { id: 'digoxin-rhythm-potassium-presentation', type: 'narrative', target: 'digoxin-rhythm-potassium-transition', atTick: 0, severity: 'critical', message: 'A 67-year-old woman is brought 7 hours after a witnessed intentional immediate-release digoxin-only ingestion. Exact quantity and coingestants remain qualified-team work. She has repeated vomiting, yellow-tinted blurred vision, and drowsiness but answers briefly. Monitor state is a slow escape rhythm 36/min, BP 76/42 mmHg (MAP 53), RR 18/min, room-air SpO2 98%, and T 36.4°C. She breathes spontaneously and handles secretions. There is no authored seizure, pulmonary edema, trauma, focal deficit, or cardiac arrest.' },
    { id: 'digoxin-rhythm-potassium-evidence', type: 'narrative', target: 'digoxin-rhythm-potassium-transition', atTick: 0, severity: 'warning', message: 'A qualified 12-lead ECG report supplies complete AV block with atrial rate 84/min, ventricular escape 36/min, QRS 108 ms, and frequent ventricular ectopy without sustained ventricular tachycardia. A qualified pre-antidote sample drawn 7 hours after the last dose supplies digoxin 8.6 ng/mL. Potassium is 6.1 mmol/L, magnesium 1.9 mg/dL, pH 7.32, bicarbonate 19 mmol/L, lactate 3.4 mmol/L, glucose 103 mg/dL, and creatinine 1.1 mg/dL. A fixed treating-team report supplies protocol-selected atropine and initial supportive vasopressor care with persistent shock. The learner does not acquire, calculate, interpret, select, or deliver them. Product, clock, sampling time, perfusion, rhythm, potassium, renal state, coingestants, and phenotype remain coupled.' },
    { id: 'digoxin-rhythm-potassium-boundary', type: 'narrative', target: 'digoxin-rhythm-potassium-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile product, clock, GI and visual clues, perfusion, rhythm, mentation, potassium, supplied ECG, oxygenation, and whole patient; recognize the life-threatening digoxin pattern without level-only, rhythm-only, potassium-only, or pacing-only closure; activate poison-center or medical-toxicology, emergency, critical-care, nursing, pharmacy, cardiac, electrolyte, airway-capable, perfusion, and compassionate safety ownership; then review supplied ECG, pre-antidote level timing, potassium, magnesium, acid-base, lactate, glucose, renal, prior-care, coingestion, phenotype, antidote, and rescue boundaries. The learner may record only bounded qualified digoxin-immune-Fab, rhythm-potassium surveillance, and refractory-arrhythmia rescue intent. No product, vial count, dose, rate, target, access, glucose, electrolyte, fluid, airway, pacing, dialysis, cardioversion, antiarrhythmic, or delivery is exposed. After elapsed simulated time, a strict fixed 60-minute report supplies clearer mentation, sinus rhythm 62/min, BP 100/62 mmHg (MAP 75), potassium 4.7 mmol/L, lactate 2.1 mmol/L, no sustained ventricular arrhythmia, and no new hypoxemia or pulmonary edema. Standard total digoxin concentration is deliberately not repeated because Fab can make it clinically misleading. This authored response does not prove individualized treatment effect, durable perfusion, potassium stability, coingestant exclusion, safe disposition, or outcome. After another elapsed interval, hand off recurrent arrhythmia, bradycardia, AV block, rapid potassium decline, hypokalemia, renal impairment, Fab-associated assay interference, rescue, safety, disposition, and outcome risk. Controls do not take history; examine; acquire, calculate, or interpret monitoring, ECG, digoxin level, blood gas, chemistry, or another test; diagnose; select or deliver charcoal, glucose, electrolyte, fluid, drug, vial count, dose, route, access, infusion, airway, ventilation, pacing, dialysis, cardioversion, antiarrhythmic, transport, or procedure; determine eligibility, disposition, prognosis, or safety; or predict response, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'digoxin-trajectory', objectiveId: 'reconcile-toxicology-digoxin-product-clock-gi-visual-perfusion-rhythm-potassium-and-whole-patient', question: 'Which product, clock, GI and visual, perfusion, rhythm, potassium, and whole-patient findings established the trajectory?' },
    { id: 'digoxin-recognition', objectiveId: 'recognize-toxicology-digoxin-life-threatening-pattern-without-level-rhythm-or-potassium-only-closure', question: 'Why was this a life-threatening digoxin pattern rather than a level, rhythm, potassium, or pacing problem alone?' },
    { id: 'digoxin-support', objectiveId: 'activate-toxicology-digoxin-poison-center-resuscitation-cardiac-electrolyte-airway-and-safety-ownership', question: 'Which toxicology, resuscitation, cardiac, electrolyte, airway, and safety owners needed to begin together?' },
    { id: 'digoxin-evidence', objectiveId: 'review-toxicology-digoxin-supplied-ecg-level-timing-potassium-renal-coingestion-and-antidote-boundary', question: 'How did supplied ECG, level timing, potassium, renal, coingestion, prior-care, and antidote evidence remain coupled?' },
    { id: 'digoxin-reassessment', objectiveId: 'record-toxicology-digoxin-bounded-qualified-immune-fab-surveillance-and-rescue-intent-with-strict-later-review', question: 'What did bounded qualified Fab and rescue intent plus the strict later report establish without proving durable safety or treatment effect?' },
    { id: 'digoxin-handoff', objectiveId: 'handoff-toxicology-digoxin-recurrent-arrhythmia-potassium-shift-level-interference-renal-rescue-and-active-risk', question: 'Which recurrent rhythm, potassium, assay, renal, rescue, safety, and outcome risks stayed open?' },
  ] },
};
