/** Suspected opioid poisoning with persistent sedation and possible xylazine co-exposure. */
import type { Scenario } from '@anesthesia/scenarios/types';

export const OPIOID_XYLAZINE_PERSISTENT_SEDATION: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'opioid-xylazine-persistent-sedation', version: '0.1.0', maturity: 'draft',
    title: 'Opioid poisoning: breathing can improve before sedation does', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced',
    objectives: [
      { id: 'reconcile-toxicology-opioid-xylazine-exposure-rescue-breathing-sedation-perfusion-and-whole-patient', statement: 'Reconcile exposure uncertainty, prehospital rescue, breathing, sedation, perfusion, and the whole patient.', measure: 'Unknown-powder exposure, bystander naloxone and rescue breathing, severe hypoventilation, hypoxemia, hypercapnia, persistent sedation, bradycardia, hypotension, hypothermia, pupils and whole-patient state were connected without learner history, examination, monitoring, testing, or diagnosis.' },
      { id: 'recognize-toxicology-opioid-xylazine-opioid-emergency-and-possible-adulterant-without-pupil-naloxone-response-or-screen-only-closure', statement: 'Recognize the opioid respiratory emergency and possible adulterant without pupil-, naloxone-response-, or screen-only closure.', measure: 'The opioid-compatible emergency remained actionable while persistent sedation and cardiovascular depression reopened co-exposure, without treating pupils, response, routine screening, street-drug history or one vital sign as diagnostic.' },
      { id: 'activate-toxicology-opioid-xylazine-ventilation-oxygen-monitoring-toxicology-addiction-wound-and-dignity-ownership', statement: 'Activate ventilation, oxygen, monitoring, toxicology, addiction, wound, and dignity-centered ownership.', measure: 'Qualified emergency, airway, respiratory, nursing, monitoring, poison-center or medical-toxicology, addiction, wound and person-centered ownership was recorded without learner examination, airway, oxygen, drug, dose, route, access, wound care, or disposition selection.' },
      { id: 'review-toxicology-opioid-xylazine-supplied-respiratory-response-circulation-temperature-glucose-ecg-screen-wound-and-differential-boundary', statement: 'Review supplied respiratory response, circulation, temperature, glucose, ECG, screening, wound, and differential evidence.', measure: 'Supplied prehospital care, breathing, gas exchange, perfusion, temperature, glucose, ECG, routine-screen limitation, skin, coingestion and competing-cause boundaries were integrated without learner acquisition, interpretation, diagnosis, exclusion, or eligibility.' },
      { id: 'record-toxicology-opioid-xylazine-bounded-qualified-continued-support-opioid-antagonist-symptomatic-care-no-veterinary-antagonist-and-strict-later-review', statement: 'Record bounded qualified continued support, opioid-antagonist and symptomatic-care intent, avoid veterinary antagonists, then review a strict later report.', measure: 'Qualified ventilation and oxygenation, opioid-antagonist, perfusion, temperature, glucose, aspiration, rhabdomyolysis and serial-surveillance intent was recorded while veterinary antagonists remained excluded; the fixed later report was reviewed without a product, dose, route, device setting, procedure, delivery, or treatment-effect claim.' },
      { id: 'handoff-toxicology-opioid-xylazine-recurrent-depression-persistent-sedation-shock-hypothermia-wound-withdrawal-addiction-and-outcome-risk', statement: 'Hand off recurrent respiratory depression, persistent sedation, shock, hypothermia, wound, withdrawal, addiction, and outcome risk.', measure: 'The handoff preserved recurrent hypoventilation, aspiration, pulmonary, perfusion, temperature, skin, withdrawal, co-exposure, toxicology-testing, addiction, harm-reduction, disposition and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Centers for Disease Control and Prevention. Xylazine: Clinical Management and Harm Reduction Strategies for Patients. 2024.', 'US Food and Drug Administration. FDA alerts health care professionals of risks to patients exposed to xylazine in illicit drugs. 2022.'] },
    limitations: ['opioid-xylazine-exposure-rescue-response-and-coexposure-pattern-are-authored', 'opioid-xylazine-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-opioid-xylazine-exam-airway-oxygen-drug-screen-wound-withdrawal-disposition-or-outcome'],
  },
  patient: { ageYears: 44, sex: 'female', heightCm: 166, weightKg: 68, asaClass: 4, diagnosis: 'Authored suspected opioid poisoning with persistent sedation and possible non-opioid adulterant exposure', procedure: 'partial-response, persistent-sedation, co-exposure, supportive-care, reassessment, and handoff practice', comorbidities: ['Supplied opioid use disorder; treatment status not yet established'], medications: ['No verified prescribed-medication list; product identity and co-exposures remain uncertain'], allergies: ['No known drug allergies'], fasting: 'Not relevant to the toxicology fixture', baseline: { heartRateBpm: 50, meanArterialMmHg: 61, strokeVolumeMl: 58, hemoglobinGPerDl: 13.4, bloodVolumeMl: 4_500, coreTemperatureC: 35.5, arterialStiffness: 1.0, baroreflexGain: 0.35, fixedStrokeVolume: true }, airway: { difficulty: 0.2, difficultMaskVentilation: false, assessment: 'Deeply drowsy, localizes to pressure, breathes slowly and shallowly, and has no authored vomit or obstruction' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'capnography', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 300, respiratoryRateBpm: 6, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'opioid-xylazine-rhythm', type: 'rhythm-change', target: 'sinus-bradycardia', atTick: 0, severity: 'critical', message: 'The bedside teaching trace shows authored sinus bradycardia. It is not a diagnostic ECG or an instruction for opioid-antagonist, fluid, vasopressor, pacing, or another treatment.' },
    { id: 'opioid-xylazine-presentation', type: 'narrative', target: 'opioid-xylazine-persistent-sedation-transition', atTick: 0, severity: 'critical', message: 'A 44-year-old woman is found beside an unlabeled powder packet. A bystander reports two community naloxone administrations and intermittent rescue breathing before EMS; the product, amount, route, time and co-exposures are unknown. Arrival state is sinus bradycardia 50/min, BP 86/48 mmHg (MAP 61), RR 6/min shallow, pulse-coherent room-air SpO2 84%, authored end-tidal CO2 62 mmHg, and T 35.5°C. She localizes to pressure but does not answer, with supplied 2 mm pupils. There is no authored pulse loss, seizure, focal deficit, major trauma, vomiting, airway obstruction, pulmonary edema, or severe skin wound.' },
    { id: 'opioid-xylazine-evidence', type: 'narrative', target: 'opioid-xylazine-persistent-sedation-transition', atTick: 0, severity: 'warning', message: 'Qualified reports supply glucose 103 mg/dL, sinus bradycardia with QRS 92 ms and QTc 448 ms, pH 7.25, PCO2 61 mmHg, bicarbonate 26 mmol/L, lactate 2.7 mmol/L, sodium 138 mmol/L, potassium 3.8 mmol/L, creatinine 1.0 mg/dL and creatine kinase 310 U/L. The limited skin survey supplies scattered healed extremity scars without an open, necrotic, infected or limb-threatening wound. Product identity, fentanyl or another opioid, xylazine or another sedative, alcohol, benzodiazepine, clonidine, hypoglycemia, head injury, infection and other causes remain qualified-team work. Routine immunoassay screening does not establish or exclude xylazine exposure. Pupils, naloxone response, persistent sedation, street-drug context, routine screening, wounds or one vital sign cannot independently diagnose an agent, prove resistance, grade severity, or establish treatment eligibility.' },
    { id: 'opioid-xylazine-boundary', type: 'narrative', target: 'opioid-xylazine-persistent-sedation-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile exposure uncertainty, bystander rescue, breathing, oxygenation, carbon dioxide, sedation, pupils, perfusion, temperature and whole patient; recognize an opioid-compatible respiratory emergency plus possible non-opioid adulterant without pupil-, naloxone-response-, screen-, wound- or single-agent closure; activate emergency, airway, respiratory, nursing, monitoring, poison-center or medical-toxicology, addiction, wound and dignity-centered ownership; then review supplied respiratory, circulation, temperature, glucose, ECG, blood-gas, chemistry, routine-screen, skin, coingestion and competing-cause boundaries. The learner may record only bounded qualified continued airway support, oxygenation and ventilation, opioid-antagonist intent for possible opioid effects, perfusion, temperature and glucose support, aspiration and rhabdomyolysis review, serial reassessment and supportive care for persistent effects. No veterinary alpha-2 antagonist is selected or used. No product, dose, formula, threshold, rate, target, route, access, airway device or setting, fluid, vasopressor, rewarming method, wound product, test order, procedure, or delivery is exposed. After elapsed simulated time, a strict fixed 10-minute qualified-team report supplies continued ventilation and oxygenation plus opioid-antagonist and supportive care; sinus rhythm 54/min, BP 90/52 mmHg (MAP 65), RR 14/min, SpO2 97% on supplied support, end-tidal CO2 43 mmHg, and persistent drowsiness that localizes to pressure without answering. This improved respiratory report does not prove a specific agent, naloxone resistance, xylazine exposure, treatment effect, neurologic or airway recovery, durable ventilation or perfusion, absence of aspiration, safe temperature, wound safety, withdrawal safety, disposition, or outcome. After another elapsed interval, hand off recurrent respiratory depression, aspiration, pulmonary injury, persistent sedation, bradycardia, hypotension, hypothermia, skin and wound care, withdrawal, co-exposure, specialized testing, addiction treatment, harm reduction, disposition and outcome risk. Controls do not take history; examine; acquire, calculate, or interpret monitoring, ECG, blood gas, chemistry, toxicology screening, skin or another test; diagnose or exclude; identify a street product; select or deliver oxygen, ventilation, naloxone, veterinary antagonist, fluid, vasopressor, glucose, rewarming, wound care, drug, dose, route, access, airway, transport or procedure; determine eligibility, observation, disposition, prognosis or safety; or predict response, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'opioid-xylazine-trajectory', objectiveId: 'reconcile-toxicology-opioid-xylazine-exposure-rescue-breathing-sedation-perfusion-and-whole-patient', question: 'Which exposure, rescue, breathing, gas-exchange, sedation, perfusion, temperature, and whole-patient findings established the trajectory?' },
    { id: 'opioid-xylazine-recognition', objectiveId: 'recognize-toxicology-opioid-xylazine-opioid-emergency-and-possible-adulterant-without-pupil-naloxone-response-or-screen-only-closure', question: 'Why did the opioid-compatible emergency stay actionable while persistent sedation reopened co-exposure rather than proving resistance or xylazine?' },
    { id: 'opioid-xylazine-support', objectiveId: 'activate-toxicology-opioid-xylazine-ventilation-oxygen-monitoring-toxicology-addiction-wound-and-dignity-ownership', question: 'Which respiratory, toxicology, addiction, wound, and person-centered owners needed to begin together?' },
    { id: 'opioid-xylazine-evidence', objectiveId: 'review-toxicology-opioid-xylazine-supplied-respiratory-response-circulation-temperature-glucose-ecg-screen-wound-and-differential-boundary', question: 'How did supplied physiology, routine-screen limits, skin findings, coingestion and competing causes stay coupled?' },
    { id: 'opioid-xylazine-reassessment', objectiveId: 'record-toxicology-opioid-xylazine-bounded-qualified-continued-support-opioid-antagonist-symptomatic-care-no-veterinary-antagonist-and-strict-later-review', question: 'What did continued qualified support and the strict later report establish without proving an agent, response mechanism, or durable safety?' },
    { id: 'opioid-xylazine-handoff', objectiveId: 'handoff-toxicology-opioid-xylazine-recurrent-depression-persistent-sedation-shock-hypothermia-wound-withdrawal-addiction-and-outcome-risk', question: 'Which recurrent respiratory, sedation, perfusion, temperature, wound, withdrawal, addiction, and outcome risks stayed open?' },
  ] },
};
