/** Serotonin toxicity with hyperthermia, clonus, and reassessment. */
import type { Scenario } from '@anesthesia/scenarios/types';

export const SEROTONIN_TOXICITY_HYPERTHERMIA_CLONUS: Scenario = {
  schemaVersion: 1,
  metadata: {
    id: 'serotonin-toxicity-hyperthermia-clonus', version: '0.1.0', maturity: 'draft',
    title: 'Serotonin toxicity: cool the heat, follow the clonus', author: 'Open Sim Lab', license: 'CC BY-SA 4.0', estimatedMinutes: 6, difficulty: 'advanced',
    objectives: [
      { id: 'reconcile-toxicology-serotonin-agents-clock-mental-autonomic-neuromuscular-temperature-and-whole-patient', statement: 'Reconcile agents, clock, mental, autonomic, neuromuscular, temperature, and whole-patient findings.', measure: 'The declared linezolid-sertraline interaction, 6-hour clock, agitation, confusion, diaphoresis, diarrhea, clonus, hyperreflexia, tremor, hypertonicity, hyperthermia, tachycardia, supplied ECG and whole-patient state were connected without learner history, examination, monitoring, testing, or diagnosis.' },
      { id: 'recognize-toxicology-serotonin-coupled-pattern-without-hunter-clonus-temperature-or-medication-list-only-closure', statement: 'Recognize the coupled serotonergic pattern without Hunter-, clonus-, temperature-, or medication-list-only closure.', measure: 'Declared exposure plus mental-state, autonomic and neuromuscular findings were recognized together while one rule, clonus finding, temperature, pulse, medication list or laboratory value remained insufficient alone.' },
      { id: 'activate-toxicology-serotonin-resuscitation-cooling-airway-toxicology-monitoring-and-compassionate-safety-ownership', statement: 'Activate resuscitation, cooling, airway, toxicology, monitoring, and compassionate safety ownership.', measure: 'Qualified emergency, critical-care, nursing, pharmacy, cooling, airway, poison-center or medical-toxicology, laboratory, renal, monitoring and compassionate-safety ownership were recorded without learner cooling, restraint, drug, dose, route, access, airway, or procedure selection.' },
      { id: 'review-toxicology-serotonin-supplied-cns-autonomic-neuromuscular-temperature-ecg-renal-ck-and-differential-boundary', statement: 'Review supplied CNS, autonomic, neuromuscular, temperature, ECG, renal, CK, and differential evidence.', measure: 'Supplied mental state, diaphoresis, bowel, clonus, reflex, tone, temperature, ECG, acid-base, lactate, renal, CK, coingestion and competing-syndrome boundaries were integrated without learner acquisition, interpretation, diagnosis, exclusion, or eligibility.' },
      { id: 'record-toxicology-serotonin-bounded-qualified-source-cessation-cooling-support-sedation-seizure-surveillance-airway-and-antagonist-intent-with-strict-later-review', statement: 'Record bounded qualified source, cooling, support, sedation, surveillance, airway, and rescue intent, then review a strict later report.', measure: 'Qualified implicated-agent cessation, rapid cooling and support, sedation or seizure care if needed, serial temperature, renal and CK surveillance, airway preparedness, and specialist-led serotonin-antagonist rescue intent were recorded without method, product, dose, rate, target, route, access, device, neuromuscular blocker, or delivery; the fixed later report was reviewed after elapsed time.' },
      { id: 'handoff-toxicology-serotonin-rebound-hyperthermia-clonus-rigidity-seizure-rhabdomyolysis-coingestion-airway-and-active-risk', statement: 'Hand off rebound hyperthermia, clonus, rigidity, seizure, rhabdomyolysis, coingestion, airway, and active risk.', measure: 'The handoff preserved serial temperature, mental state, clonus, tone, airway, ECG, renal, CK, seizure, coingestion, recurrence, compassionate safety, disposition and outcome uncertainty.' },
    ],
    clinicalReview: { reviewer: 'UNSIGNED', credential: 'UNSIGNED', institution: 'UNSIGNED', competingInterests: 'None declared', reviewedOn: '1970-01-01', reviewBy: '1970-01-01', contentVersion: '0.1.0', sources: ['Dunkley EJC et al. The Hunter Serotonin Toxicity Criteria. QJM. 2003;96(9):635-642. PMID 12925718.', 'US National Library of Medicine. DailyMed: linezolid tablets prescribing information, Section 5.3. Updated 2026-07-09.', 'American Heart Association. 2025 Guidelines for CPR and ECC. Part 10, Section 16.2.'] },
    limitations: ['serotonin-interaction-mental-autonomic-neuromuscular-hyperthermia-and-response-are-authored', 'serotonin-controls-reconcile-recognize-support-review-intent-reassess-and-handoff-only', 'no-live-serotonin-diagnosis-cooling-sedation-antagonist-airway-seizure-care-or-outcome'],
  },
  patient: { ageYears: 37, sex: 'female', heightCm: 168, weightKg: 67, asaClass: 2, diagnosis: 'Authored suspected serotonin-toxicity hyperthermia-clonus pattern', procedure: 'calm interaction, hyperthermia, clonus, airway-risk, rescue-boundary, reassessment, and handoff practice', comorbidities: ['Supplied agitation requires qualified compassionate safety ownership'], medications: ['Stable sertraline and first supplied linezolid dose; exact adherence and other exposures remain qualified-team work'], allergies: ['No known drug allergies'], fasting: 'Not relevant to the toxicology fixture', baseline: { heartRateBpm: 128, meanArterialMmHg: 105, strokeVolumeMl: 64, hemoglobinGPerDl: 13.6, bloodVolumeMl: 4_500, coreTemperatureC: 40.1, arterialStiffness: 1, baroreflexGain: 0.35, fixedStrokeVolume: true }, airway: { difficulty: 0.15, difficultMaskVentilation: false, assessment: 'Agitated and confused with increasing leg tone; breathing spontaneously and handling secretions' }, respiratory: { profile: 'healthy' } },
  equipment: { monitoring: ['ecg', 'nibp', 'pulse-oximetry', 'temperature'], airwayDevice: 'facemask', ventilator: { mode: 'manual', fio2: 0.21, tidalVolumeMl: 460, respiratoryRateBpm: 12, freshGasFlowLPerMin: 2, delivering: false } }, formulary: [],
  timeline: [
    { id: 'serotonin-toxicity-rhythm', type: 'rhythm-change', target: 'sinus-tachycardia', atTick: 0, severity: 'critical', message: 'The bedside teaching trace shows authored sinus tachycardia. It is not a diagnostic 12-lead ECG or a rate-control, bicarbonate, cardioversion, or rescue-drug instruction.' },
    { id: 'serotonin-toxicity-presentation', type: 'narrative', target: 'serotonin-toxicity-hyperthermia-clonus-transition', atTick: 0, severity: 'critical', message: 'A 37-year-old woman develops rapidly progressive symptoms 6 hours after her first supplied linezolid dose while continuing stable sertraline. Qualified observation supplies agitation, confusion, diaphoresis, tremor, ocular clonus, inducible ankle clonus, lower-limb hyperreflexia, increased leg tone, hyperactive bowel sounds, and diarrhea. Monitor state is sinus tachycardia 128/min, BP 146/84 mmHg (MAP 105), RR 26/min, room-air SpO2 97%, and core T 40.1°C. There is no authored dry skin, urinary retention, miosis, secretion excess, fasciculation, lead-pipe rigidity, focal deficit, trauma, seizure, or cardiac arrest.' },
    { id: 'serotonin-toxicity-evidence', type: 'narrative', target: 'serotonin-toxicity-hyperthermia-clonus-transition', atTick: 0, severity: 'warning', message: 'A qualified ECG report supplies sinus tachycardia and QRS 88 ms. Qualified reports supply pH 7.34, PCO2 35 mmHg, bicarbonate 19 mmol/L, lactate 3.8 mmol/L, sodium 140 mmol/L, potassium 3.9 mmol/L, glucose 116 mg/dL, creatinine 1.0 mg/dL, and CK 640 U/L. Exact adherence, doses, additional agents, coingestants, infection, withdrawal, environmental, endocrine, neurologic and mixed causes remain qualified-team work. Hunter-pattern findings organize supplied evidence but no rule, clonus, temperature, medication list, ECG interval, or laboratory value independently diagnoses, excludes alternatives, grades severity, or establishes rescue eligibility.' },
    { id: 'serotonin-toxicity-boundary', type: 'narrative', target: 'serotonin-toxicity-hyperthermia-clonus-transition-boundary', atTick: 0, severity: 'warning', message: 'Reconcile agents, 6-hour clock, mental state, diaphoresis, bowel activity, clonus, reflexes, tremor, tone, temperature, tachycardia, ECG, complications, and whole patient; recognize the coupled mental, autonomic, and neuromuscular pattern without Hunter-, clonus-, temperature-, or medication-list-only closure; activate emergency, critical-care, nursing, pharmacy, rapid-cooling, airway, poison-center or medical-toxicology, laboratory, renal, monitoring, and compassionate-safety ownership; then review supplied CNS, autonomic, neuromuscular, temperature, ECG, acid-base, lactate, renal, CK, coingestion, interaction, and competing-syndrome boundaries. The learner may record only bounded qualified implicated-agent cessation, rapid cooling and support, sedation or seizure care if needed, serial temperature, renal and CK surveillance, airway preparedness, and specialist-led serotonin-antagonist rescue intent. No cooling method, fluid, restraint, sedative, cyproheptadine product, dose, rate, target, route, access, airway device, ventilation, neuromuscular blocker, or delivery is exposed. After elapsed simulated time, a strict fixed 30-minute qualified-team report supplies implicated-agent cessation, active cooling, supportive care and qualified sedation, T 38.7°C, HR 104/min, BP 132/76 mmHg (MAP 95), calmer mentation, and persistent inducible clonus and hyperreflexia. This authored response does not prove individualized treatment effect, exposure completeness, durable temperature control, neuromuscular recovery, renal safety, rhabdomyolysis or seizure exclusion, safe disposition, or outcome. After another elapsed interval, hand off rebound hyperthermia, clonus, rigidity, airway, ECG, renal and CK injury, seizure, coingestion, recurrence, compassionate safety, disposition, and outcome risk. Controls do not take history; examine; acquire, calculate, or interpret monitoring, ECG, temperature, laboratory or another test; diagnose or exclude; select or deliver cooling, fluid, restraint, sedation, antagonist, drug, dose, route, access, airway, ventilation, neuromuscular blocker, transport, or procedure; determine eligibility, disposition, prognosis, or safety; or predict response, survival, or outcome.' },
  ],
  debrief: { rubric: [
    { id: 'serotonin-trajectory', objectiveId: 'reconcile-toxicology-serotonin-agents-clock-mental-autonomic-neuromuscular-temperature-and-whole-patient', question: 'Which agents, clock, mental, autonomic, neuromuscular, temperature, and whole-patient findings established the trajectory?' },
    { id: 'serotonin-recognition', objectiveId: 'recognize-toxicology-serotonin-coupled-pattern-without-hunter-clonus-temperature-or-medication-list-only-closure', question: 'Why was this a coupled pattern rather than a Hunter rule, clonus finding, temperature, or medication list alone?' },
    { id: 'serotonin-support', objectiveId: 'activate-toxicology-serotonin-resuscitation-cooling-airway-toxicology-monitoring-and-compassionate-safety-ownership', question: 'Which cooling, resuscitation, airway, toxicology, monitoring, renal, and compassionate-safety owners needed to begin together?' },
    { id: 'serotonin-evidence', objectiveId: 'review-toxicology-serotonin-supplied-cns-autonomic-neuromuscular-temperature-ecg-renal-ck-and-differential-boundary', question: 'How did CNS, autonomic, neuromuscular, temperature, ECG, renal, CK, coingestion, and competing-syndrome evidence remain coupled?' },
    { id: 'serotonin-reassessment', objectiveId: 'record-toxicology-serotonin-bounded-qualified-source-cessation-cooling-support-sedation-seizure-surveillance-airway-and-antagonist-intent-with-strict-later-review', question: 'What did bounded qualified support and rescue intent plus the strict later report establish without proving neuromuscular recovery or treatment effect?' },
    { id: 'serotonin-handoff', objectiveId: 'handoff-toxicology-serotonin-rebound-hyperthermia-clonus-rigidity-seizure-rhabdomyolysis-coingestion-airway-and-active-risk', question: 'Which rebound temperature, neuromuscular, airway, renal, CK, seizure, coingestion, safety, and outcome risks stayed open?' },
  ] },
};
