import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { ARTERIAL_PRESSURE_TRANSDUCER_ARTIFACT } from './scenarios/arterial-pressure-transducer-artifact';
import { ARTERIAL_PRESSURE_TRANSDUCER_ARTIFACT_FIXTURES } from './arterial-pressure-transducer-artifact-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { ARTERIAL_TRANSDUCER_DEMONSTRATION_VERSION } from './demo/arterial-transducer-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function arterialPressureTransducerArtifactCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== ARTERIAL_PRESSURE_TRANSDUCER_ARTIFACT_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || ARTERIAL_PRESSURE_TRANSDUCER_ARTIFACT_FIXTURES.contentVersion !== '0.1.0'
    || ARTERIAL_PRESSURE_TRANSDUCER_ARTIFACT_FIXTURES.seed !== 9310
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || ARTERIAL_TRANSDUCER_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(ARTERIAL_PRESSURE_TRANSDUCER_ARTIFACT)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['arterial-pressure-transducer-artifact-fixtures.ts binds seed 9310 and content 0.1.0 to expert, treated-the-display error, full-sequence recovery, and no-action paths over 3,600 ticks. The numbers are solver output on the shared artifact model: a true mean arterial pressure of 78 mmHg held for the entire case on every path, a displayed 63 while the transducer is 20 cm high, and the same 78 reported by the independent cuff whenever it is cycled. tests/integration/anesthesia-arterial-transducer-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['A one-drug formulary, the crystalloid bolus, and four bounded arterial-line actions: cycle the cuff, level and zero, assess the waveform, restore the dynamic response. Two of those are ordered by the engine -- the damping correction is refused until the waveform has been assessed -- and one is ordered by the rubric, since the cuff must precede any patient-changing action to earn its objective outright. The fluid is deliberately available and unguarded: nothing stops a learner treating a displayed 63, and the transcripts measure what that costs.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['Both artifacts arrive at tick 600 and the transcripts end at 3,600, at the scenario\'s own case-end prompt. That is long enough for the independent cuff cycle to complete and report, for both corrections to be applied and observed, and for the no-action path to end with the display still reading 63 against a true 78 -- which is the state this lesson is about a learner sitting in.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all three objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is treatment given to arithmetic. The error path gives 1,000 mL of balanced crystalloid to a displayed mean arterial pressure of 63 and only then cycles the cuff and levels the transducer. Measured, it is PARTLY MET, met, not met -- and the reason the first objective falls is worth stating precisely, because it is not lateness. The cuff completes 60 seconds after the display changed, inside its window, and reports 78 mmHg. It is downgraded because a patient-changing action came first. The measure is about order, and the order encodes the lesson: the independent reading costs half a minute and settles whether there is anything to treat. The expert path meets all three; the recovery path keeps the litre, completes the whole sequence, and reads partly met, met, met.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['arterial-pressure-transducer-artifact-fixtures.ts binds exact-content expert, treated-the-display error, full-sequence recovery, and no-action pathways to seed 9310 for deterministic replay through the shared engine. Three readings are pinned by tests. The first is the premise, asserted across every path including the one that gives fluid: the true mean arterial pressure is 78 mmHg at every tick of every transcript, so the display was wrong and the patient never was. The 15 mmHg discrepancy is exactly the hydrostatic column implied by a 20 cm offset, and the cuff reports 78 whenever it is asked. The second is that the first objective is graded on ORDER rather than latency -- a run whose cuff is timely and correct is still downgraded for having given fluid first -- which a reader of the objective statement alone would be likely to miss. The third is that the damping correction is refused before the waveform is assessed, and that this refusal follows the module\'s usual rule rather than the blood-bank exception: a run that is refused and then assesses and corrects properly earns the objective in full. The two artifacts are also genuinely independent, which a test asserts by correcting the level alone and finding the trace still over-damped.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None tells a learner to doubt a monitor, which is the correct division: deciding that a measurement rather than a patient has changed is the judgement this lesson exists to build. Worked example ${ARTERIAL_TRANSDUCER_DEMONSTRATION_VERSION} is the module's thirty-second observed-state one and the eighth to open with a beat that deliberately does nothing. Its closing gate requires both corrections AND the latched waveform assessment, because a cleared artifact is also the state before the fault arrives -- the trap documented by the two lessons bound before it. It also carries a no-dispatch beat while the cuff inflates, the same shape as the laryngoscopy-in-progress hold: without it the example re-requests a cycle already running and is refused. Its verify beat states the ordering requirement before a learner could breach it, and its assess beat points out that correcting one artifact does not reveal the other. Its closing beat declines the credit the demonstration would take by reporting that the pressure was 78 throughout and that the 15 mmHg gap was a column of water. tests/unit/anesthesia-arterial-transducer-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
