import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { CAPNOGRAPHY_SAMPLING_LINE_OBSTRUCTION } from './scenarios/capnography-sampling-line-obstruction';
import { CAPNOGRAPHY_SAMPLING_LINE_OBSTRUCTION_FIXTURES } from './capnography-sampling-line-obstruction-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { CAPNOGRAPHY_LINE_DEMONSTRATION_VERSION } from './demo/capnography-line-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function capnographySamplingLineObstructionCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== CAPNOGRAPHY_SAMPLING_LINE_OBSTRUCTION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || CAPNOGRAPHY_SAMPLING_LINE_OBSTRUCTION_FIXTURES.contentVersion !== '0.1.0'
    || CAPNOGRAPHY_SAMPLING_LINE_OBSTRUCTION_FIXTURES.seed !== 6602
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || CAPNOGRAPHY_LINE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(CAPNOGRAPHY_SAMPLING_LINE_OBSTRUCTION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['capnography-sampling-line-obstruction-fixtures.ts binds seed 6602 and content 0.1.0 to expert, laryngoscopy error, ventilator-takeover recovery, and no-action paths over 3,600 ticks. The numbers the counterfactual turns on are solver output rather than authored figures: an untouched patient holding a spontaneous rate of 14 a minute and a saturation of 98% through the whole fault, a rate of zero and a lowest saturation of 96% once a laryngoscope is used, and a machine rate of 12 with 98% once the ventilator is taken over. tests/integration/anesthesia-capnography-sampling-line-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['A one-drug formulary and two bounded line actions -- cross-check ventilation, reconnect -- alongside the ordinary airway and ventilator controls that the middle objective exists to discourage. That is the design worth naming: the tray offers a learner every way of intervening on a patient who does not need intervening on, and the rubric scores the restraint rather than the engine refusing the actions. Both line actions are gated on the obstruction being present, which has a consequence the transcripts pin: once the line is reconnected, the cross-check can no longer be recorded at all.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The line blocks at tick 1,200 and the transcripts end at 3,600, at the scenario\'s own case-end prompt and long past the point where every path has settled -- the untouched paths hold a rate of 14 and 98% saturation to the end, and the instrumented path has returned to a machine rate of 12. The middle objective is evaluated over the window before restoration, so the run must be long enough for that window to contain the learner\'s response and for its consequences to be visible afterwards.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all three objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is harm caused entirely by the response. The error path answers a flat capnogram with a laryngoscope, then cross-checks and reconnects. Measured, it is met, NOT MET, met -- and the middle objective is not a bookkeeping loss: the spontaneous respiratory rate falls to zero and the lowest saturation to 96%, so the apnoea the learner feared is the one they produced. The recovery path is the same reflex in its milder form, taking over the ventilator rather than the airway: partly met rather than not met, with a rate of 12 and a saturation of 98%. The expert path meets all three, and the patient is identical to the one who was left alone.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['capnography-sampling-line-obstruction-fixtures.ts binds exact-content expert, laryngoscopy error, ventilator-takeover recovery, and no-action pathways to seed 6602 for deterministic replay through the shared engine. Three readings are pinned by tests. The first and sharpest: the no-action path earns the middle objective IN FULL. It is scored not met, MET, not met -- the only objective a completely passive learner receives credit for is the one that rewards not acting, and that is credit rather than an accident of the rubric, because the correct response to a monitor fault in a well patient is to leave the patient alone. The second is the gradient inside that objective, which the objective statement does not describe: instrumenting the airway is not met while commandeering the ventilator is partly met, and the transcripts contain both so the difference is visible rather than asserted. The third is an irreversibility. Reconnecting the line before cross-checking clears the artifact, and the cross-check is then refused with capnography-cross-check-refused because there is no longer a fault to check ventilation against -- so the first objective is lost permanently, in a lesson where every other mistake is recoverable. That is the second such trap in the module after the recorded CIED plan, and it is stated rather than left to be discovered.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None of them tells a learner to wait, which is the correct division: a rule that said "this is probably the monitor" would answer the question the lesson is asking. Worked example ${CAPNOGRAPHY_LINE_DEMONSTRATION_VERSION} is the module's thirtieth observed-state one and the only one whose central instruction is to do less. Its closing gate reads the artifact having CLEARED together with the latched cross-check flag, which cannot both hold before the fault -- the trap the two lessons bound before it document. Its cross-check beat names the three independent signs that do not travel down the sampling line, and its restore beat states the ordering consequence before the learner could meet it. Its closing beat declines the credit the demonstration would take by reporting that a run doing nothing at all earns the objective this example worked for. tests/unit/anesthesia-capnography-line-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
