import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { CIRCLE_SYSTEM_REBREATHING } from './scenarios/circle-system-rebreathing';
import { CIRCLE_SYSTEM_REBREATHING_FIXTURES } from './circle-system-rebreathing-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { CIRCLE_SYSTEM_REBREATHING_DEMONSTRATION_VERSION } from './demo/circle-system-rebreathing-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function circleSystemRebreathingCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== CIRCLE_SYSTEM_REBREATHING_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || CIRCLE_SYSTEM_REBREATHING_FIXTURES.contentVersion !== '0.1.0'
    || CIRCLE_SYSTEM_REBREATHING_FIXTURES.seed !== 5133
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || CIRCLE_SYSTEM_REBREATHING_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(CIRCLE_SYSTEM_REBREATHING)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['circle-system-rebreathing-fixtures.ts binds seed 5133 and content 0.1.0 to expert, bridged-not-fixed error, late-replacement recovery, and no-action paths over 5,400 ticks. The numbers the counterfactual turns on are solver output on the bounded circuit trajectory the scenario declares: a modelled inspired carbon dioxide rising to 8.0 mmHg on failure, settling at 2.86 where high flow is the only response, and reaching zero once the absorbent is changed. tests/integration/anesthesia-circle-system-rebreathing-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['A one-drug formulary and three controls: the capnogram assessment, the fresh-gas flow on the ventilator, and the absorbent replacement. The engine enforces one ordering itself -- replacement is refused until the capnogram has been assessed, which is the difference between changing a canister on suspicion and changing it on evidence -- and the rubric enforces the other, scoring the flow bridge only when it precedes the definitive correction. This is the module\'s only equipment failure, and its metadata is explicit that both circuit actions are screen intent rather than physical exchange.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The absorbent exhausts at tick 1,800 and the transcripts end at 5,400, at the scenario\'s own case-end prompt and well past the point where every path has settled: the repaired paths hold an inspired carbon dioxide of zero, the bridged path holds 2.86 mmHg, and the untreated path holds 8.0 with an end-tidal value still drifting upward. The third objective reads the washout back after replacement, so the run must continue long enough for its absence to be unambiguous.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all three objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is a correct action held in place of the correct sequence. The error path reads the capnogram at 10 seconds, opens the fresh gas to 10 L/min at 20, and stops. Measured, it is met, met, NOT MET, and its inspired carbon dioxide falls from 8.0 to 2.86 mmHg and stays there for the remaining fifty simulated minutes. The bridge is genuinely worth something -- roughly two thirds of the rebreathed load -- and it is not a repair, which is the distinction the lesson exists to draw. The expert path meets all three and reaches zero; the recovery path adds the replacement at tick 2,600, inside the 90-second window, and also meets all three.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['circle-system-rebreathing-fixtures.ts binds exact-content expert, bridged-not-fixed error, late-replacement recovery, and no-action pathways to seed 5133 for deterministic replay through the shared engine. Three readings are pinned by tests. The first is the bridge measured as a partial mitigation rather than described as one: 8.0 mmHg untreated, 2.86 bridged, zero repaired. The second cuts the other way and is the reading a learner is least likely to expect: a run that assesses and then goes STRAIGHT to the absorbent, skipping the flow entirely, loses the bridging objective and produces a patient indistinguishable from the expert path -- the same end-tidal carbon dioxide at the same ticks and the same washout to zero. In this bounded model the bridge buys nothing once the repair is already coming, and the evidence states that rather than implying the objective tracks a benefit the model shows. It scores a habit that protects a patient when the repair turns out to be slow, which is a defensible thing for a rubric to do and is not the same as measuring an effect. The third is that replacing before assessing is refused with circuit-absorbent-replacement-refused and costs nothing once heeded: the module\'s usual rule, holding here. A fourth observation is recorded without a dedicated test because it holds trivially on every path: the oxygen saturation reads 100% throughout, including on the untreated run, so the only instrument that moves in this lesson is the inspired baseline of the capnogram.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None addresses the breathing circuit, which is worth stating: this is the module's only equipment failure and the tutor has nothing to say about it, so the guidance a learner gets here is the worked example alone. Worked example ${CIRCLE_SYSTEM_REBREATHING_DEMONSTRATION_VERSION} is the module's twenty-ninth observed-state one and the sixth to open with a beat that deliberately does nothing, since both circuit actions are refused before the failure. Its closing gate reads the latched absorbentReplaced flag rather than the inspired carbon dioxide, because that value is also zero BEFORE the failure and a gate on it would end the example at tick one -- the same trap the post-extubation lesson bound alongside it fell into and now documents. Its bridge beat names itself a bridge and not a treatment before the learner watches it fall short, and its closing beat declines the credit the demonstration would take by reporting that skipping the bridge entirely would have produced the same patient. tests/unit/anesthesia-circle-system-rebreathing-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
