import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { DIFFICULT_AIRWAY_SUPRAGLOTTIC_RESCUE } from './scenarios/difficult-airway-supraglottic-rescue';
import { DIFFICULT_AIRWAY_SUPRAGLOTTIC_RESCUE_FIXTURES } from './difficult-airway-supraglottic-rescue-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { SUPRAGLOTTIC_RESCUE_DEMONSTRATION_VERSION } from './demo/supraglottic-rescue-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function difficultAirwaySupraglotticRescueCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== DIFFICULT_AIRWAY_SUPRAGLOTTIC_RESCUE_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || DIFFICULT_AIRWAY_SUPRAGLOTTIC_RESCUE_FIXTURES.contentVersion !== '0.1.0'
    || DIFFICULT_AIRWAY_SUPRAGLOTTIC_RESCUE_FIXTURES.seed !== 2277
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || SUPRAGLOTTIC_RESCUE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(DIFFICULT_AIRWAY_SUPRAGLOTTIC_RESCUE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['difficult-airway-supraglottic-rescue-fixtures.ts binds seed 2277 and content 0.1.0 to expert, no-reserve-two-attempts error, preoxygenated-two-attempts recovery, and no-action paths over 6,000 ticks. The saturations are solver output rather than authored figures: 100% on both preoxygenated paths and 54% on the error path, with end-tidal oxygen fractions of 0.92 and 0.16 at induction. The transcripts are deliberately built to the same shape as the repeated-laryngoscopy-harm ones so the two lessons can be read against each other. tests/integration/anesthesia-difficult-airway-supraglottic-rescue-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['A two-drug formulary -- propofol and rocuronium, whose course the metadata declares a teaching model -- and four controls: the ventilator, the syringes, the help request, and the two airway procedures. As in the sibling lesson the engine does not gate the error: a second and third laryngoscopy are accepted without complaint, refusing only overlapping attempts and attempts after a device is placed. When to stop looking is left to the learner and measured afterwards rather than prevented.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The transcripts end at 6,000 ticks, past the scenario\'s own case-end prompt at 5,400 and past the point where every path holds a settled saturation through a working rescue device. The fourth objective needs thirty continuous seconds of adequate gas exchange after placement, so the run must continue well beyond the rescue rather than stopping at it; the error path places its device at tick 3,000 and the trace still has fifty simulated minutes left.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all four objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual isolates one variable: the recovery path is the error path with a single preoxygenation prepended and nothing else changed. Both look twice, both call for help 34 seconds after the failed attempt, both rescue at the same tick. Measured, the error path is not met, not met, partly met, partly met with a lowest post-rescue saturation of 54%; the recovery path is met, not met, partly met, MET, and holds 100%. The expert path -- reserve, one attempt, help during it, rescue, proof -- meets all four. The no-action path reports not-exercised four times, because the whole rubric is downstream of an accepted induction dose.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['difficult-airway-supraglottic-rescue-fixtures.ts binds exact-content expert, no-reserve-two-attempts error, preoxygenated-two-attempts recovery, and no-action pathways to seed 2277 for deterministic replay through the shared engine. Three behaviours are pinned by tests, and two of them are properties of the escalation objective that its wording does not convey. The first: help requested 49 seconds after the failed attempt scores PARTLY MET, and requesting no help at all also scores partly met -- the two are indistinguishable in the outcome, differing only in the finding text, so there is no gradient between late and never and the attempt count dominates that objective. The second: the objective\'s declared measure describes a window running from the start of the failed attempt through 30 seconds after it, and a request made 96 seconds BEFORE the attempt is nonetheless scored met. The implementation has no lower bound, so the stated measure is narrower than the check it describes. That is a documentation mismatch rather than a defect -- nothing is unearnable and the clinically better habit is the one that scores -- but it is recorded rather than left for a reader to discover. The third pins the preoxygenation result across a second lesson: two attempts without reserve reach 54% and the identical two with it hold 100%, reproducing at two attempts what the sibling lesson shows at three.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here, and the preoxygenation ladder is again the load-bearing one: it addresses exactly the step whose absence separates these transcripts. All are silent on the unassisted setting and suppressed while any alarm is active. Worked example ${SUPRAGLOTTIC_RESCUE_DEMONSTRATION_VERSION} is the module's twenty-fifth observed-state one and the sibling of the repeated-laryngoscopy example. It carries the same no-dispatch beat while an attempt is in progress, for the same reason -- the attempt count is still zero until the procedure completes, so the read-backwards chain would otherwise fall through to an earlier gate and re-emit it. Its escalate beat fires at the failed attempt, inside the window the measure describes, and its closing beat declines three credits: it reports that the two looks it did not take would have cost this patient nothing at full reserve, that late help and no help score identically, and that the measure's stated window is narrower than the check, so calling early is the better habit and is not penalised. tests/unit/anesthesia-supraglottic-rescue-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
