import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { DILUTIONAL_COAGULOPATHY } from './scenarios/dilutional-coagulopathy';
import { DILUTIONAL_COAGULOPATHY_FIXTURES } from './dilutional-coagulopathy-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { DILUTIONAL_COAGULOPATHY_DEMONSTRATION_VERSION } from './demo/dilutional-coagulopathy-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function dilutionalCoagulopathyCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== DILUTIONAL_COAGULOPATHY_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || DILUTIONAL_COAGULOPATHY_FIXTURES.contentVersion !== '0.1.0'
    || DILUTIONAL_COAGULOPATHY_FIXTURES.seed !== 4471
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || DILUTIONAL_COAGULOPATHY_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(DILUTIONAL_COAGULOPATHY)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['dilutional-coagulopathy-fixtures.ts binds seed 4471 and content 0.1.0 to expert, reached-for-plasma-first error, same-opening recovery, and no-action paths over 3,600 ticks. Nothing the objectives are scored on is authored. The sixty-seven-year-old woman of 70 kg is a set of baseline parameters carrying the result of a dilution that happened before the case starts, and the prothrombin ratio, the fibrinogen concentration and their response to plasma all come out of the shared engine: the panel reports 1.67 × normal and 1.8 g/L before, and 1.48 and 2.0 after. The continuing loss is declared once as 90 mL per minute for 4,200 ticks, and it matters mechanically rather than atmospherically — the panel, the product release and the plasma are all refused by the engine unless modelled bleeding is running. tests/integration/anesthesia-dilutional-coagulopathy-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['No tray of its own: a bounded coagulation panel, a blood-bank request, and a fresh-frozen-plasma release of three or four units to a ceiling of four. What makes the choice real here is that the lesson\'s central argument is enforced by the engine rather than scored by the rubric — the first lab in this module where that is true. Plasma is refused outright until a panel has been reported, so "use the abnormal panel, not the volume lost" is a precondition of the action rather than an opinion about it. A learner who reaches for plasma on the strength of the oozing gets a refusal and a message, and pays for it in the seconds the first objective is counting. The lesson transfuses nobody, gives no real product, models neither platelets nor cryoprecipitate nor a massive-transfusion protocol, and predicts no outcome for any person.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The transcripts end at 3,600 ticks, past the scenario\'s own reassessment prompt at 3,000 and past the repeat panel on every path that orders one. The modelled bleeding runs to 4,200 and is deliberately not finished when the run stops: this case takes over mid-operation and hands back mid-operation, source control is explicitly outside it, and the closing evidence does not claim the coagulopathy was corrected — only that it was measured, treated once within the bounded response, and measured again.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all three objectives from the replayed state trace and the engine event log rather than from a score kept during the run. The error and recovery paths share an identical opening, and the opening is the lesson: both reach for plasma at tick 700 on the strength of the oozing and the volume already lost, and the engine refuses it because no panel has been reported. That refusal is the mechanism rather than a penalty, and what it costs is the seventy seconds that follow — the first objective allows sixty, so it is partly met on both paths and stays that way. The two then differ in exactly one action, whether the panel is repeated after the plasma, and that single difference is the whole of the third objective. The expert path asks first and has nothing refused at any point.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['dilutional-coagulopathy-fixtures.ts binds exact-content expert, reached-for-plasma-first error, same-opening recovery, and no-action pathways to seed 4471 for deterministic replay through the shared engine. Scored through the real debrief, the expert path meets all three; the error path is partly met, met, not met; the recovery path is partly met, met, met; and the no-action path is not met, not met, not exercised. Two readings worth stating. give-lab-guided-plasma is met on the error path as well, because by the time it gives plasma it does have an abnormal panel — the objective asks whether the lab guided the product, not whether the learner reached for it first, and the evidence does not claim the error path was disciplined. And reassess-coagulation-response reports "not exercised" rather than "not met" on the idle path, because there was no accepted plasma response to reassess; the distinction between a step skipped and a step never reached is one this rubric makes and the evidence preserves.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts are the module's shared induction ladder, and none of them fires in this lesson: it takes over mid-case under neuraxial anaesthesia, so there is no induction, no airway and no apnoea for them to speak about. That is stated rather than papered over — the guidance this lesson actually relies on is the engine's own refusal message, which names the missing panel at the moment a learner reaches past it. Worked example ${DILUTIONAL_COAGULOPATHY_DEMONSTRATION_VERSION} is the module's eighth observed-state one, and it is the first that needs something the equipment snapshot does not carry. Ordering a coagulation panel changes no modelled state at all — it reports numbers the solver was already computing — so a second panel is invisible to every field on the snapshot and an example gated on those fields cannot tell "I have rechecked" from "I have not". The count of accepted panels is therefore derived from the session's own event log and passed in, which is the only honest way to observe an action whose entire effect is on the observer. Everything ordering the example is monotone: the panel count and the plasma units only ever rise, and neither the prothrombin ratio nor the fibrinogen is used to sequence anything, because both change in the instant the plasma is accepted and would let the example skip the recheck it exists to demonstrate. It carries no pre-cue beat, and that is a measurement rather than an omission: this scenario’s blood-loss event starts at tick 0, so any beat gated on the absence of bleeding is unreachable. tests/unit/anesthesia-dilutional-coagulopathy-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover of the refused opening, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
