import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { EARLY_MALIGNANT_HYPERTHERMIA_DURING_VOLATILE_ANESTHESIA } from './scenarios/early-malignant-hyperthermia-during-volatile-anesthesia';
import { EARLY_MH_FIXTURES } from './early-malignant-hyperthermia-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { MALIGNANT_HYPERTHERMIA_DEMONSTRATION_VERSION } from './demo/malignant-hyperthermia-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function earlyMalignantHyperthermiaCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== EARLY_MH_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || EARLY_MH_FIXTURES.contentVersion !== '0.1.0'
    || EARLY_MH_FIXTURES.seed !== 3308
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || MALIGNANT_HYPERTHERMIA_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(EARLY_MALIGNANT_HYPERTHERMIA_DURING_VOLATILE_ANESTHESIA)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['early-malignant-hyperthermia-fixtures.ts binds seed 3308 and content 0.1.0 to expert, unrecognised-pattern error, late-recognition recovery, and no-action paths over 7,200 ticks. Nothing the objectives are scored on is authored, and the trigger least of all: this crisis is LATENT rather than scheduled, firing on genuine end-tidal volatile exposure, so the tick at which rigidity appears is produced by the learner turning a vaporizer on rather than by the timeline. The carbon dioxide, the rigidity fraction and the temperature trajectory all come out of the shared engine — peak end-tidal carbon dioxide is 39 mmHg on the expert path, 53 on the recovery path and 109 on the error path, and peak rigidity 0.37, 0.42 and 0.91. tests/integration/anesthesia-malignant-hyperthermia-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['No tray of its own: the anaesthetic machine — vaporizer, inspired fraction, fresh-gas flow, tidal volume and rate — and a bounded 2.5 mg/kg intravenous dantrolene the engine accepts at that dose and no other. What makes the choices real here is that the first one is invisible as a choice. Starting 2% sevoflurane on a 2 L/min circle is competent volatile maintenance and is also the trigger, and nothing in the cockpit marks it. The rescue objective then reads four machine settings together rather than one, because turning the vaporizer off does not empty a circle that is full of agent — the flow is what washes it out. The lesson gives no real drug, triggers nothing in anyone, and predicts no outcome for any person.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The transcripts end at 7,200 ticks, past the scenario\'s own reassessment prompt at 5,400 and past the 120-second reassessment window on every path that gives dantrolene. This is an initial-response case: there is no cooling protocol, no repeat dosing schedule, no laboratory workup and no disposition, and the briefing does not offer one. The run stops because that slice is over rather than because the patient reached a state.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all four objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is how early the pattern is read, on an identical opening: every path except the idle one starts the same 2% sevoflurane maintenance, and the error path simply never reads the pattern. Measured, it reaches an end-tidal carbon dioxide of 109 mmHg and a rigidity fraction of 0.91 while its core temperature is still 38.95°C — which is the argument the lesson exists to make, since a clinician waiting for a fever would still be waiting. The recovery path makes the identical opening, recognises it seventy-two seconds in rather than two, and treats completely: partly met, not met, partly met, met.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['early-malignant-hyperthermia-fixtures.ts binds exact-content expert, unrecognised-pattern error, late-recognition recovery, and no-action pathways to seed 3308 for deterministic replay through the shared engine. Scored through the real debrief, the expert path meets all four; the error path fails all four; the recovery path is partly met, not met, partly met, met; and the no-action path reports not exercised on all four. Two readings need stating. The no-action result is correct rather than a gap: the trigger is latent, so a session in which nobody delivers volatile never develops rigidity and there is no malignant hyperthermia to respond to — the finding text says exactly that. And the expert path meets reassess-mh-response on a trace where end-tidal carbon dioxide goes from 39 to 39. Treating within two seconds means there was never anything to reverse, so it is the RECOVERY path that actually demonstrates the physiology, falling from 53 to 49 across its window. Fast enough to prevent and fast enough to show are not the same thing, and a test pins both numbers rather than letting the expert transcript imply a response it did not need.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts are the module's shared induction ladder, and none of them fires here: this lesson is a volatile maintenance rather than an induction, so there is no preoxygenation, no bolus sequence and no apnoea for them to speak about. That is stated rather than papered over, and it matters more in this lesson than in the others — there is no prompt anywhere that names the rising carbon dioxide, because reading that divergence is the entire thing being assessed. Worked example ${MALIGNANT_HYPERTHERMIA_DEMONSTRATION_VERSION} is the module's twelfth observed-state one and the only one that has to CAUSE the crisis it then treats: the trigger is latent, so an example that skipped the maintenance beat would sit in an uneventful anaesthetic forever with nothing to demonstrate. Its first beat therefore starts the sevoflurane and says plainly that this is the beat that causes what follows. It is sequenced on the dantrolene total, which is the only quantity here that cannot go back down — the rigidity fraction climbs before treatment and falls after it, so a beat gated on it fires again on the way down. Its closing beat argues with its own temperature reading, pointing out that the number is barely above baseline and that a clinician waiting for a fever would still be waiting, and it also declines the credit its own reassessment would take. tests/unit/anesthesia-malignant-hyperthermia-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
