import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { HYPOTENSION_AFTER_INDUCTION } from './scenarios/hypotension-after-induction';
import { HYPOTENSION_AFTER_INDUCTION_FIXTURES } from './hypotension-after-induction-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { HYPOTENSION_AFTER_INDUCTION_DEMONSTRATION_VERSION } from './demo/hypotension-after-induction-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function hypotensionAfterInductionCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== HYPOTENSION_AFTER_INDUCTION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || HYPOTENSION_AFTER_INDUCTION_FIXTURES.contentVersion !== '0.1.0'
    || HYPOTENSION_AFTER_INDUCTION_FIXTURES.seed !== 7714
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || HYPOTENSION_AFTER_INDUCTION_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(HYPOTENSION_AFTER_INDUCTION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['hypotension-after-induction-fixtures.ts binds seed 7714 and content 0.1.0 to expert, treat-the-number error, read-the-mechanism recovery, and no-action paths over 7,800 ticks. Nothing the objectives are scored on is authored. The seventy-eight-year-old woman of 54 kg is a set of baseline parameters — a 3,100 mL circulating volume that is about 15% below her predicted one, a 42 mL stroke volume defended by a rate of 96, and a baroreflex gain of 0.55 for an elderly patient who took an ACE inhibitor this morning — and the pressure, the pulse pressure, the saturation and the response to every bag come out of the shared engine. The modelled losses are declared once in the scenario timeline as 240 mL per minute for 3,600 ticks and the solver does the arithmetic. tests/integration/anesthesia-hypotension-after-induction-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['No tray of its own and no lesson-specific action: the flowmeter, two syringes, a fluid bag, a vasopressor, a laryngoscope and the ventilator, all available from the first tick. Two choices carry the lesson. The first is the propofol dose: the formulary offers a 2 mg/kg preset that gives 108 mg on this patient, and the scenario\'s own comment says the preset "is there to be resisted"; the expert transcript gives the 40 mg preset instead, which is 0.74 mg/kg. The second is the mechanism, and the cockpit refuses to answer it — a vasopressor and a bag both raise the number, they are both on the tray from the first tick, and nothing labels either one correct. What separates them is the pulse pressure, which is narrow and swinging with the ventilator, and the duration of the response, which the learner has to watch for rather than be told. The lesson intubates nobody, gives no real drug, and predicts no outcome for any person.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The transcripts end at 7,800 ticks, which is where the modelled bowel handling ends and the last declared timeline event has run out. There is no maintenance, emergence or end of operation in this scenario and the briefing does not offer one: the slice is the induction and the first thirteen minutes of the laparotomy, and the run stops because that slice is over rather than because the patient reached a state.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all four objectives from the replayed state trace and the engine event log rather than from a score kept during the run. The counterfactual is the mechanism, and the recovery path is deliberately built to lose. It gives 4,500 mL of crystalloid — 500 mL MORE than the expert path — and starts within a minute of the pressure falling, and manage-hypotension still fails: 279 seconds below 65 mmHg against the error path\'s 658, a nadir of 48.1 mmHg against 28.6. Volume is the right treatment, it halves the exposure, and it cannot undo a dose that was wrong before it was given. The error path is the same patient treated as a number: four vasopressor doses, no fluid at all, and a pressure that comes back up after each one and goes down again. Measured, that is the entire difference — same drugs, same airway, same clock.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['hypotension-after-induction-fixtures.ts binds exact-content expert, treat-the-number error, read-the-mechanism recovery, and no-action pathways to seed 7714 for deterministic replay through the shared engine. Scored through the real debrief, the expert path meets all four; the error path is not met, not met, not met, met; the recovery path is partly met, not met, met, met; and the no-action path is not exercised, not met, not met, met. Two of those readings are worth naming. The no-action path already fails manage-hypotension — 133 seconds below 65 with a nadir of 49.9 — because the losses run whether or not anyone induces, so this objective is not a test of the induction alone and the evidence does not claim it is. And ventilate-before-desaturation is met on all four paths, including the one where nothing is done: the saturation never goes below 95.7% in any of them. That is a property of the case rather than of the transcripts. She is not the desaturating patient and the lesson does not pretend she is; the objective is exercised, not stressed.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here, and the one written for this patient is the map-below-60 rule: it names the reading rather than the treatment — "ask what is holding it down before you treat the number" — and points at the Why panel rather than at a bag, so it cannot hand over the answer the lesson exists to leave open. It reads mean arterial pressure the engine produced anyway, is suppressed while any alarm is active, and is silent on the unassisted setting. Worked example ${HYPOTENSION_AFTER_INDUCTION_DEMONSTRATION_VERSION} is the module's second observed-state one and it adds something the first did not have: a beat that repeats on the pressure. Volume here is not one decision, it is a decision taken again every time the pressure sags, so the replacement beat carries the engine's accepted crystalloid total in its own id and fires as often as the pressure asks. How many times that is cannot be known in advance, which is the point — an example that fixed the count would have answered the question the lesson leaves open. The example never reaches for the vasopressor, and says so in its closing beat rather than leaving it unexplained. It also stops: at four litres it refuses to give a fifth and names why, because a pressure that has not answered four litres in a seventy-eight-year-old with stage 3 kidney disease is asking a different question. Reading the accepted total rather than a list of dispatches is what makes it resumable — driven from the error path's opening it picks up mid-case and reaches the same place. tests/unit/anesthesia-hypotension-after-induction-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
