import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { HYPOTHERMIA_AND_REWARMING } from './scenarios/hypothermia-and-rewarming';
import { HYPOTHERMIA_AND_REWARMING_FIXTURES } from './hypothermia-and-rewarming-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { HYPOTHERMIA_REWARMING_DEMONSTRATION_VERSION } from './demo/hypothermia-rewarming-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function hypothermiaAndRewarmingCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== HYPOTHERMIA_AND_REWARMING_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || HYPOTHERMIA_AND_REWARMING_FIXTURES.contentVersion !== '0.1.0'
    || HYPOTHERMIA_AND_REWARMING_FIXTURES.seed !== 2946
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || HYPOTHERMIA_REWARMING_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(HYPOTHERMIA_AND_REWARMING)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['hypothermia-and-rewarming-fixtures.ts binds seed 2946 and content 0.1.0 to expert, fluids-warmed-only error, late-surface-warming recovery, and no-action paths over 9,000 ticks. Every temperature the counterfactual turns on is solver output on the fixed cooling course the scenario declares: a start at 36.7°C, an untreated floor of 35.51, a surface-warmed recovery through 36.5 to 36.60, and nadirs of 36.36 on the expert path against 35.83 on the recovery. tests/integration/anesthesia-hypothermia-rewarming-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['A one-drug formulary and three bounded thermal responses: confirm the core temperature, start forced-air surface warming, record warmed bulk fluids. The engine orders them, refusing either warming action until a confirmation is on record, which is the distinction between a number drifting on a screen and a temperature someone has taken responsibility for. The two warming actions are presented as peers by the tray and by the objective list, and the transcripts exist largely to measure whether they are peers in the model. They are not.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The cooling course starts at tick 100 and the transcripts end at 9,000, past the scenario\'s own reassessment prompt at 7,200 and well past the point where each path has settled -- the warmed paths plateau at 36.60°C from roughly tick 4,000 and the unwarmed ones sit at 35.51 for the remainder. The fourth objective asks whether 36.5°C was reached at all, so the run must be long enough for its absence on the unwarmed paths to be conclusive rather than merely pending.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all four objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is an earned objective with no thermal effect whatsoever. The error path confirms the core temperature properly and then warms the fluids and nothing else. Measured, it is met, not met, MET, not met -- and its temperature trace is identical to the untreated run at every tick, bottoming at 35.51°C and never recovering. The expert path meets all four and plateaus at 36.60. The recovery path adds surface warming at tick 2,400 and also meets all four, with a nadir of 35.83°C against the expert path\'s 36.36: the score cannot tell those two runs apart and the patient can.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['hypothermia-and-rewarming-fixtures.ts binds exact-content expert, fluids-warmed-only error, late-surface-warming recovery, and no-action pathways to seed 2946 for deterministic replay through the shared engine. Three readings are pinned by tests. The first isolates the two warming objectives against each other and is exact rather than approximate: a run that confirms and starts ONLY surface warming produces the expert path\'s temperatures to the digit at every sampled tick, and a run that confirms and warms ONLY the fluids produces the untreated path\'s temperatures to the digit. Surface warming carries the whole trajectory; the bulk-fluid intent moves the modelled temperature by exactly zero. The evidence does not conclude the fluid objective should not exist -- the reason to warm fluids is the heat a cold litre removes, which this bounded model does not represent, and the scenario says as much in its own metadata -- but a learner comparing scores would otherwise be entitled to infer that both interventions worked, and only one did. The second is the nadir the rubric cannot see: all four objectives are met whether surface warming starts at tick 700 or 2,400, and the temperature floor differs by half a degree. The third is that warming before confirming is refused with thermal-order-refused and costs nothing once heeded, which is the module\'s usual rule rather than the blood-bank exception.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None of them names temperature, which is worth stating plainly: a slow continuous drift is the kind of change a prompt would be most useful for and least likely to be authored for, and the guidance a learner gets in this lesson is the worked example alone. Worked example ${HYPOTHERMIA_REWARMING_DEMONSTRATION_VERSION} is the module's thirty-third observed-state one and the ninth to open with a beat that deliberately does nothing. All three of its gates are latched ticks, so none can walk backwards even though the quantity they are about falls and then rises -- a gate on the temperature itself would reverse mid-run. Its fluids beat says outright that the simulator will not show the action working, before the learner watches it not work. Its closing beat declines the credit the demonstration would take: it reports that surface warming alone reproduces the numbers just watched to the digit, that warmed fluids alone reproduce the untreated patient, and that a late start costs half a degree the score does not record. tests/unit/anesthesia-hypothermia-rewarming-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
