import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { OPIOID_INDUCED_VENTILATORY_IMPAIRMENT } from './scenarios/opioid-induced-ventilatory-impairment';
import { OPIOID_INDUCED_VENTILATORY_IMPAIRMENT_FIXTURES } from './opioid-induced-ventilatory-impairment-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { OPIOID_VENTILATORY_IMPAIRMENT_DEMONSTRATION_VERSION } from './demo/opioid-ventilatory-impairment-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function opioidInducedVentilatoryImpairmentCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== OPIOID_INDUCED_VENTILATORY_IMPAIRMENT_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || OPIOID_INDUCED_VENTILATORY_IMPAIRMENT_FIXTURES.contentVersion !== '0.1.0'
    || OPIOID_INDUCED_VENTILATORY_IMPAIRMENT_FIXTURES.seed !== 8123
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || OPIOID_VENTILATORY_IMPAIRMENT_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(OPIOID_INDUCED_VENTILATORY_IMPAIRMENT)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['opioid-induced-ventilatory-impairment-fixtures.ts binds seed 8123 and content 0.1.0 to expert, oxygen-without-support error, late-rescue recovery, and no-action paths over 3,000 ticks. The numbers the counterfactual turns on are solver output rather than authored figures: the saturation of 100% that the error path holds for its whole length, the 96% the no-action path reads at the same tick, the respiratory rate of 4 a minute common to both, and the end-tidal carbon dioxide rising to 50 mmHg all come out of the shared engine on the fixed central-drive model the scenario declares. tests/integration/anesthesia-opioid-induced-ventilatory-impairment-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['An empty formulary and three controls: the help request, the ventilator, and two bounded responses -- hold further opioid, record naloxone titration intent. The ventilator is where the lesson lives, because it offers two things that look adjacent and are not: raising the inspired oxygen fraction, and delivering breaths. The second objective reads active breath DELIVERY at 95% oxygen or more, so setting the oxygen to 100% without delivering scores nothing while changing the most-watched number on the monitor. The engine also orders the two drug responses, refusing naloxone intent until further opioid has been held.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The scripted impairment begins at tick 100 and the transcripts end at 3,000, which is five simulated minutes after it. That is long enough for the last objective to be readable -- it requires breath delivery to be stopped and spontaneous rate, breath size, carbon dioxide and saturation then read together -- and long enough for the error path to be measured at a point where nothing is left ambiguous. The run stops because the reassessment has been made, not because the patient reached a state, and the no-action path ends with a rate of 4 a minute and no intervention at all.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all five objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is the briefing\'s own warning, made measurable, and it is the sharpest in the module because the error is worse than inaction in the only place the learner is looking. The error path turns the inspired oxygen to 100% without starting breath delivery. Measured at tick 2,900: saturation 100%, respiratory rate 4 a minute, end-tidal carbon dioxide 50 mmHg. The no-action path at the same tick: saturation 96%, the same rate, the same carbon dioxide. The run that did nothing has the WORSE monitored number. The intervention did not help the patient and did hide the deterioration, and the debrief scores the error path not met on all five. The expert path meets all five; the recovery path is not met, partly met, met, met, met.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['opioid-induced-ventilatory-impairment-fixtures.ts binds exact-content expert, oxygen-without-support error, late-rescue recovery, and no-action pathways to seed 8123 for deterministic replay through the shared engine. Three behaviours are pinned by tests. The first is the comparison above, asserted directly on both traces at the same tick, so the claim that supplemental oxygen manufactures reassurance rests on the model rather than on the narration. The second is that recognition is graded as a gradient rather than a pass: help at 10 seconds is met, at 50 seconds partly met, and beyond 60 not met, and breath delivery is met to 45 seconds and partly met to 90 -- the recovery path is bound to sit in the partial band on both, so all three points on the gradient appear in the transcripts. The third is that the last objective cannot be earned while the machine is breathing for the patient: a run that does everything else correctly and never stops delivery is scored not met on reassessment, because the rate and breath size on the screen are the machine\'s. That is a rubric behaviour rather than a physiological one and a learner reading the objective statement would not predict it.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None names the saturation trap, which is correct: recognising that a reassuring number is being manufactured is what the lesson exists to teach rather than something to supply at the moment it would give the answer away. Worked example ${OPIOID_VENTILATORY_IMPAIRMENT_DEMONSTRATION_VERSION} is the module's twenty-second observed-state one. It gates on latched ticks and on whether the machine is delivering, and never on the saturation -- a design choice the lesson forces, since the saturation reads 100% both when the patient is supported and when they are merely receiving oxygen while breathing four times a minute. Its first beat does nothing at all, and that is a finding rather than padding: every objective here is timed FROM the scripted onset, so a help request made before the pattern appears is not merely early -- the rubric searches only events at or after onset and does not see it. An earlier draft of the example acted immediately and had its opioid hold refused as inactive, which is how the behaviour was found. Its support beat states the distinction before the learner acts on it: breaths delivered, not oxygen supplied. Its closing beat declines the credit the demonstration would take, reporting the error path's better saturation beside the no-action path's worse one, and naming two limits -- naloxone here is recorded intent rather than a dose or a pharmacological response, and the trace ends at one recovery while recurrent depression after a short-acting reversal is precisely what monitoring exists for and is not simulated. tests/unit/anesthesia-opioid-ventilatory-impairment-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
