import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PERIOPERATIVE_ANAPHYLAXIS_AFTER_ANTIBIOTIC } from './scenarios/perioperative-anaphylaxis-after-antibiotic';
import { PERIOPERATIVE_ANAPHYLAXIS_FIXTURES } from './perioperative-anaphylaxis-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { ANAPHYLAXIS_DEMONSTRATION_VERSION } from './demo/anaphylaxis-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function perioperativeAnaphylaxisCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PERIOPERATIVE_ANAPHYLAXIS_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || PERIOPERATIVE_ANAPHYLAXIS_FIXTURES.contentVersion !== '0.1.0'
    || PERIOPERATIVE_ANAPHYLAXIS_FIXTURES.seed !== 8842
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || ANAPHYLAXIS_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PERIOPERATIVE_ANAPHYLAXIS_AFTER_ANTIBIOTIC)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['perioperative-anaphylaxis-fixtures.ts binds seed 8842 and content 0.1.0 to expert, treated-as-ordinary-collapse error, same-reflex recovery, and no-action paths over 4,200 ticks. Nothing the objectives are scored on is authored. The forty-seven-year-old woman of 70 kg is a set of baseline parameters, and the pressure trajectory, the saturation and the response to every drug come out of the shared engine: her mean pressure never falls below 90.5 mmHg before the cefazolin at tick 1,800 and reaches 75 within ten seconds of it. The pressure nadirs the counterfactual turns on — 56.3, 54.8 and 47.5 mmHg — are solver output rather than authored figures. tests/integration/anesthesia-anaphylaxis-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['No tray of its own: the ventilator, a fluid bag, a vasopressor and an epinephrine bolus. The choice that carries the lesson is which of the last two to reach for, and the cockpit refuses to answer it — both are available from the first tick, both raise a collapsed pressure on the monitor, and nothing labels either one correct. That is the point rather than an omission: reaching for a vasopressor and a bag is entirely reasonable behaviour for every other cause of an abrupt intraoperative collapse, and this is the one where it treats the number and leaves the mechanism running. The lesson gives no real drug and predicts no outcome for any person.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The transcripts end at 4,200 ticks, past the scenario\'s own reassessment prompt at 3,000 and past the point where the pressure has reached its nadir and begun to recover on every path that treats. This is an initial-response case: there is no second-line antihistamine or steroid, no infusion, no tryptase and no disposition, and the briefing does not offer one. The run stops because that slice is over rather than because the patient reached a state.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all four objectives from the replayed state trace and the engine event log rather than from a running tally. The counterfactual isolates one substitution. The error and the recovery share an identical opening — the ventilator prepared at tick 120, a vasopressor at 1,900, a litre of crystalloid at 2,000 — and differ in exactly one action at tick 2,600: another vasopressor, or 50 micrograms of epinephrine. Measured, that single substitution is worth 7.3 mmHg of pressure nadir, 47.5 against 54.8, and it moves two of the four objectives. Because everything else is identical, nothing else can be credited with it.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['perioperative-anaphylaxis-fixtures.ts binds exact-content expert, treated-as-ordinary-collapse error, same-reflex recovery, and no-action pathways to seed 8842 for deterministic replay through the shared engine. Scored through the real debrief, the expert path meets all four; the error path is not met, not met, met, met; the recovery path is partly met, partly met, met, met; and the no-action path is not met, not met, not met, partly met. Two readings need stating. support-anaphylaxis-circulation is met on the ERROR path, because that path does give a litre of crystalloid inside the window — the objective asks whether volume was given, not whether the right drug accompanied it, and the evidence does not claim the error path resuscitated well. And support-anaphylaxis-oxygenation is met on the error path too, earned entirely by a ventilator setting made at tick 120, before the exposure existed: the measure explicitly counts settings established beforehand. Two of the four objectives are therefore insensitive to the substitution this lesson is about, which is why the transcripts report the pressure nadir alongside them.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here, and the map-below-60 rule is the one this patient triggers. It names the reading rather than the treatment — ask what is holding the pressure down before treating the number — and points at the Why panel rather than at a syringe, so it cannot supply the drug choice the lesson exists to leave open. Worked example ${ANAPHYLAXIS_DEMONSTRATION_VERSION} is the module's thirteenth observed-state one. The engine's own anaphylaxis severity is private and not on the snapshot, so the example triggers on the collapse itself, which is the better reading anyway: it is the observation the learner actually has, and nothing in this lesson announces an allergy. Its treatment branch is latched on epinephrine having been given rather than on the pressure alone, because the drug lifts the mean pressure back over the trigger threshold for a while and a gate on the collapse by itself walks the example back into its waiting beat between the drug and the volume — which is how that was found. It never reaches for the vasopressor, and its closing beat states what happens to a run that does rather than leaving the comparison implicit. tests/unit/anesthesia-anaphylaxis-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover of the reflex, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
