import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PERIOPERATIVE_HYPERGLYCEMIA } from './scenarios/perioperative-hyperglycemia';
import { PERIOPERATIVE_HYPERGLYCEMIA_FIXTURES } from './perioperative-hyperglycemia-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { PERIOPERATIVE_HYPERGLYCEMIA_DEMONSTRATION_VERSION } from './demo/perioperative-hyperglycemia-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function perioperativeHyperglycemiaCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PERIOPERATIVE_HYPERGLYCEMIA_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.1'
    || PERIOPERATIVE_HYPERGLYCEMIA_FIXTURES.contentVersion !== '0.1.1'
    || PERIOPERATIVE_HYPERGLYCEMIA_FIXTURES.seed !== 7405
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || PERIOPERATIVE_HYPERGLYCEMIA_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PERIOPERATIVE_HYPERGLYCEMIA)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['perioperative-hyperglycemia-fixtures.ts binds seed 7405 and content 0.1.1 to expert, repeated-too-early error, waited-and-repeated recovery, and no-action paths over 19,200 ticks -- the longest replay in the module, because the third objective cannot be exercised until 18,000 ticks have elapsed after the insulin intent. The values are authored rather than solver output, and the evidence says so plainly: a fixed 238 mg/dL point-of-care result and a fixed 174 mg/dL repeat. tests/integration/anesthesia-perioperative-hyperglycemia-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['A one-drug formulary and three bounded glycemic responses in an order the engine enforces twice over: the insulin response is refused until the point-of-care value has been confirmed, and the repeat check is refused until thirty simulated minutes have passed since that response. The second gate is the unusual one, because it makes waiting an action. There is no dose to choose -- the metadata states that insulin action is intent without dose or delivery -- so what the lesson offers a learner is a sequence and an interval rather than a treatment decision.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The glucose course starts at tick 100 and the transcripts end at 19,200, past the scenario\'s own reassessment prompt at 18,100 and past the earliest tick at which the expert path\'s repeat becomes available. The run length is set by the rubric rather than by physiology: nothing about this patient changes across those 19,200 ticks, and the only reason the trace must be that long is that the third objective is gated on an interval.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all three objectives from the recorded actions and the replayed trace rather than from a score kept during the run. The counterfactual is impatience rather than ignorance, which makes it a more useful error than a careless one. The error path confirms the glucose correctly, records institutional insulin-protocol intent correctly, and then asks for the repeat at fifteen minutes. The engine declines it with repeat-glucose-too-early and nobody asks again. Measured, it is met, met, NOT MET: the objective is lost to a check made too soon rather than to one never made. The recovery path is that identical transcript with a second attempt after the interval has genuinely elapsed, and it meets all three. The expert path meets all three, and the no-action path meets none.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['perioperative-hyperglycemia-fixtures.ts binds exact-content expert, repeated-too-early error, waited-and-repeated recovery, and no-action pathways to seed 7405 for deterministic replay through the shared engine. Three readings are pinned by tests. The first is the most important limit in this lesson: THE REPEAT VALUE IS AUTHORED. It is 174 mg/dL on every path that obtains it, and 174 sits inside the declared 100-180 target, so the third objective grades whether the check was made and never what it found. No sequence of learner actions can produce a repeat outside the target, and none can produce a worse one by responding worse -- there is no dose to get wrong. A reader who saw only the objective text might reasonably think the reassessment measures a response; it measures an act. The second is that both engine-enforced orderings follow the module\'s usual rule rather than the blood-bank exception: recording insulin before confirming is refused and costs nothing once heeded, and repeating too early is refused and costs nothing once the learner waits, which is exactly what separates the error path from the recovery path. The third is that no monitored physiological variable moves anywhere in this lesson on any path; it is a documentation exercise, and the evidence would rather say that than let a reader infer a glycemic model that does not exist.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None of them names glucose, and none could usefully: the value arrives as a point-of-care result rather than as a trace, so there is no observable a rule could watch. Worked example ${PERIOPERATIVE_HYPERGLYCEMIA_DEMONSTRATION_VERSION} is the module's thirty-fourth observed-state one and the tenth to open with a beat that deliberately does nothing. It also carries the module's longest hold: a no-dispatch waiting beat that spans thirty simulated minutes after the insulin intent, because asking early is refused and the interval is what the objective is about. It reads repeatEligible from the engine rather than recomputing the interval itself. Its closing beat declines the credit the demonstration would take, stating that the 174 mg/dL it just recorded is authored, that no path can produce a different value, and that the run it did not take failed on impatience rather than neglect. tests/unit/anesthesia-perioperative-hyperglycemia-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
