import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PERSISTENT_VF_CARDIAC_ARREST } from './scenarios/persistent-vf-cardiac-arrest';
import { PERSISTENT_VF_CARDIAC_ARREST_FIXTURES } from './persistent-vf-cardiac-arrest-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { PERSISTENT_VF_CARDIAC_ARREST_DEMONSTRATION_VERSION } from './demo/persistent-vf-cardiac-arrest-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function persistentVfCardiacArrestCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PERSISTENT_VF_CARDIAC_ARREST_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || PERSISTENT_VF_CARDIAC_ARREST_FIXTURES.contentVersion !== '0.1.0'
    || PERSISTENT_VF_CARDIAC_ARREST_FIXTURES.seed !== 5217
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || PERSISTENT_VF_CARDIAC_ARREST_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PERSISTENT_VF_CARDIAC_ARREST)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['persistent-vf-cardiac-arrest-fixtures.ts binds seed 5217 and content 0.1.0 to expert, shocked-without-epinephrine error, drug-then-second-shock recovery, and no-action paths over 3,000 ticks. The conversion is deterministic rather than sampled -- the engine states as much in its own event text -- so what the transcripts pin is which combinations of conditions produce it: return of spontaneous circulation at tick 900 on the expert path and 1,300 on the recovery, and never on the error or no-action paths. tests/integration/anesthesia-persistent-vf-cardiac-arrest-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['A one-drug formulary -- which the emergency-medicine lesson of the same shape forbids, its guard requiring an empty one, so the two can never answer for each other -- and three bounded arrest controls: fixed-rate chest compressions with an explicit start or stop, exactly 1 mg of intravenous or intraosseous epinephrine, and biphasic defibrillation at a selected energy. All three are refused unless the scripted arrest is active, which has a consequence the transcripts pin: once return of spontaneous circulation ends the arrest, further shocks are declined rather than scored. The energy is a free numeric choice rather than a preset, and only 200 J converts.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['Ventricular fibrillation begins at tick 300 and the transcripts end at 3,000, past the scenario\'s own reassessment prompt at 2,100 and well past the conversion on both paths that achieve one. The run continues long enough after the recovery path\'s second shock at tick 1,300 for the organized rhythm to be unambiguous, and long enough on the error path for the absence of conversion to be conclusive rather than pending.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all four objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is the reflex to shock a shockable rhythm. The error path starts compressions promptly and delivers a correct 200 J biphasic shock, and gives no epinephrine. Measured, it is met, not met, PARTLY MET, met: the shock is delivered and counted and does not convert, and the debrief reports that one accepted shock did not meet the declared conversion conditions. The expert path meets all four with conversion at tick 900. The recovery path gives the drug afterwards and shocks again, converting at 1,300 -- both shocks accepted, only the second one working.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['persistent-vf-cardiac-arrest-fixtures.ts binds exact-content expert, shocked-without-epinephrine error, drug-then-second-shock recovery, and no-action pathways to seed 5217 for deterministic replay through the shared engine. Two readings are pinned by tests. The first is that the conversion is CONJUNCTIVE: it requires the declared 200 J exactly, at least 1 mg of accepted epinephrine, and compressions recently running, and dropping any one of the three leaves the shock delivered, counted, and inert. Tests exercise each failure separately -- 360 J with everything else correct, 200 J with no epinephrine, and 200 J after compressions were explicitly stopped -- so the conjunction is measured rather than asserted from the objective text. The second is more uncomfortable: THE FOURTH OBJECTIVE CANNOT BE FAILED. It asks that no shock be delivered to a non-shockable rhythm, and this scenario contains no non-shockable rhythm to deliver one to -- the single scripted rhythm change is to ventricular fibrillation, and once conversion ends the arrest the engine refuses defibrillation outright rather than scoring it. A test drives six shocks including two after return of spontaneous circulation and the objective is still met, exactly as it is on the path that does nothing at all. The principle is a real one and this scenario cannot test it; the evidence says so rather than letting a met outcome read as evidence of judgement.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None addresses arrest, which is the correct division for a lesson whose whole content is a bounded algorithm. Worked example ${PERSISTENT_VF_CARDIAC_ARREST_DEMONSTRATION_VERSION} is the module's thirty-sixth observed-state one and the eleventh to open with a beat that deliberately does nothing, since every arrest control is refused before the rhythm changes. It is a separate demonstration from the emergency-medicine lesson of the same shape, because that lesson's guard checks its own scenario id and neither can drive the other. Its compressions beat states why they come before the defibrillator rather than after -- stopping them to prepare a shock is the reliable way to make the shock fail -- and its closing beat declines the credit the demonstration would take by naming the fourth objective as one this scenario cannot test. tests/unit/anesthesia-persistent-vf-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
