import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE } from './scenarios/pneumothorax-under-positive-pressure';
import { PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE_FIXTURES } from './pneumothorax-under-positive-pressure-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE_DEMONSTRATION_VERSION } from './demo/pneumothorax-under-positive-pressure-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function pneumothoraxUnderPositivePressureCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE_FIXTURES.contentVersion !== '0.1.0'
    || PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE_FIXTURES.seed !== 5504
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['pneumothorax-under-positive-pressure-fixtures.ts binds seed 5504 and content 0.1.0 to expert, ventilate-harder error, late-sequence recovery, and no-action paths over 4,000 ticks. The numbers the lesson turns on are solver output on the shared tension model: a mean arterial pressure falling from 65.5 to 33 mmHg as the fraction rises, a saturation falling from 99% to 84%, and the post-decompression recovery topping out at 64.71 mmHg. tests/integration/anesthesia-pneumothorax-under-positive-pressure-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['An empty formulary and three controls: two bounded pleural responses (assess bilateral ventilation, decompress the left chest), the help request in its tension-pneumothorax context, and the ventilator. The ventilator is where the error lives, because it is the control a falling saturation invites a learner to reach for, and the two things it offers are not equivalent: raising the inspired oxygen fraction buys margin, while raising the rate adds breaths to a space that cannot empty. The engine records decompression as intent -- technique, site, equipment and complications are outside this lesson, and its metadata says so.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The scripted pleural event begins at tick 600 and the transcripts end at 4,000, which is more than five simulated minutes after it and well past the point where every path has reached its steady value: the expert path is at its post-decompression plateau from roughly tick 1,800 onward and does not move again, and the error and no-action paths hold a mean arterial pressure of 33 mmHg for the remainder. The run stops because nothing further changes, not because the patient reached a state.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all five objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is the reflex the lesson exists to interrupt. The error path answers the falling saturation by setting the oxygen to 100% and the rate to 20 and doing nothing else -- no assessment, no help, no decompression. Measured, it scores not met, not met, MET, not met, not met: it earns the oxygenation objective, because 100% oxygen with active delivery is exactly what that objective asks for, and it earns nothing else while the mean arterial pressure sits at 33 mmHg for the rest of the run. The one thing the reflex does buy is the one thing the rubric can credit it for. The expert path meets the first four; the recovery path is partly met, partly met, met, met.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['pneumothorax-under-positive-pressure-fixtures.ts binds exact-content expert, ventilate-harder error, late-sequence recovery, and no-action pathways to seed 5504 for deterministic replay through the shared engine. THIS LESSON CARRIES A DEFECT AND THE TRANSCRIPTS RECORD IT RATHER THAN WORKING AROUND IT: the fifth objective, reassess-pneumothorax-recovery, cannot be earned by any transcript. It requires a mean arterial pressure of at least 65 mmHg after accepted decompression, and the maximum the model reaches after decompression is 64.71 mmHg -- a shortfall of 0.29. A perfect run therefore scores four of five. Three measurements locate the fault, and a test pins each. The patient\'s own pre-event mean arterial pressure is 65.52 mmHg, so the threshold is not absurd for this patient: they cleared it before the event and the post-decompression trajectory returns them to 0.81 mmHg below where they started. The engine is not at fault: the emergency-medicine lesson obstructive-shock-tension-pneumothorax scores this same rubric branch and meets all five, so the shared tension model and the shared threshold both work as intended elsewhere. What is left is this scenario\'s own parameters, where an anaesthetised steady state sits fractionally under an endpoint written for it. The fix is a content decision -- raise the patient\'s baseline, or restate the objective\'s endpoint -- and is deliberately not made here, because both choices are clinical-review matters on a scenario whose reviewer field still reads UNSIGNED. Binding the lesson with the defect measured and named is more useful than leaving it unbound or quietly tuning the physiology until the score came out right.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None names the pleural pattern, which is correct: the differential is what the lesson exists to teach. Worked example ${PNEUMOTHORAX_UNDER_POSITIVE_PRESSURE_DEMONSTRATION_VERSION} is the module's twenty-third observed-state one and the second to open with a beat that deliberately does nothing, for the same reason as the opioid lesson -- every objective is timed from the scripted event, and the rubric does not see an action taken before it. Its oxygen beat states the distinction the error path gets wrong, raising the oxygen while explicitly leaving the rate alone. Its closing beat declines two credits: it reports the error path's score including the one objective that path does earn, and it tells the learner plainly that the fifth objective cannot be earned, by how much, and that this is recorded rather than hidden. tests/unit/anesthesia-pneumothorax-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
