import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { PREECLAMPSIA_URGENT_DELIVERY } from './scenarios/preeclampsia-urgent-delivery';
import { PREECLAMPSIA_URGENT_DELIVERY_FIXTURES } from './preeclampsia-urgent-delivery-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { PREECLAMPSIA_URGENT_DELIVERY_DEMONSTRATION_VERSION } from './demo/preeclampsia-urgent-delivery-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function preeclampsiaUrgentDeliveryCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== PREECLAMPSIA_URGENT_DELIVERY_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || PREECLAMPSIA_URGENT_DELIVERY_FIXTURES.contentVersion !== '0.1.0'
    || PREECLAMPSIA_URGENT_DELIVERY_FIXTURES.seed !== 4471
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || PREECLAMPSIA_URGENT_DELIVERY_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(PREECLAMPSIA_URGENT_DELIVERY)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['preeclampsia-urgent-delivery-fixtures.ts binds seed 4471 and content 0.1.0 to expert, prophylaxis-alone error, labetalol-added recovery, and no-action paths over 6,000 ticks. The pressures the objectives turn on come out of the shared engine rather than being authored into the transcripts: 165/120 mmHg at confirmation and 136/99 mmHg after labetalol are solver output on the bounded response the lesson declares. The scenario says in its own metadata that this response is a teaching trajectory rather than individual pharmacokinetics, and the evidence repeats it rather than quietly presenting the numbers as a prediction. tests/integration/anesthesia-preeclampsia-urgent-delivery-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Three bounded actions and an empty formulary: repeat the pressure, labetalol 20 mg IV, magnesium sulfate 4 g IV. Each drug is a single-dose teaching branch, so there is no titration to hide behind — the decision is which drug, and whether the pressure was confirmed first. The engine enforces the confirmation rather than advising it: either drug reached for before a repeat reading is refused outright with preeclampsia-treatment-before-confirmation and nothing is given. The lesson stops before anaesthesia and delivery, which its metadata states, and no baby is delivered here.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The transcripts end at 6,000 ticks, past the last accepted action on every path — the expert reassesses at 2,400 and the recovery at 4,200, after two extra actions. Six thousand ticks is ten simulated minutes, which is worth stating precisely because the treatment objective carries a sixty-minute window: at this run length that window cannot be missed, so the timing clause is satisfied on every path rather than discriminating between them. The run stops because both drugs are in and the pressure has been read again, not because the patient reached a state.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all four objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is the cleanest in the module because nothing on the error path is done badly. That path confirms the pressure, gives magnesium sulfate for seizure prophylaxis, waits thirty simulated minutes, and reads the pressure again — and the reading is 165/120 mmHg, identical to the confirming one to the digit. Measured outcomes are met, not met, MET, not exercised. The third objective is credited in full: the prophylaxis was correct and correctly indicated. What did not happen is that anything was treated. The expert path meets all four, reading 136/99 mmHg after labetalol, and the no-action path meets none.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['preeclampsia-urgent-delivery-fixtures.ts binds exact-content expert, prophylaxis-alone error, labetalol-added recovery, and no-action pathways to seed 4471 for deterministic replay through the shared engine. Three behaviours are pinned by tests. The first is the one above, measured directly: a test asserts that the systolic and diastolic pressures thirty simulated minutes after magnesium are unchanged from the confirming reading, so the claim that magnesium is not an antihypertensive rests on the model rather than on the narration. The second is the fourth objective\'s outcome on that path, which is not-exercised rather than not-met — a fourth outcome value the rubric uses to decline grading a reassessment when there was no antihypertensive response to reassess, and one a learner reading only the objective statements would not predict. The third is the sixty-minute window described above: a test pins that labetalol given at tick 4,200 is still read as inside it, which documents the window as unfalsifiable at these run lengths rather than leaving a reader to assume it discriminates. The recovery path adds the missing labetalol to the identical error transcript and meets all four, so nothing here is spent by being done in the wrong order.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and none of them fires: they address airway, depth and haemodynamics during an anaesthetic, and this lesson stops before one begins. No rule names magnesium or labetalol, which is the correct division — the distinction between the two drugs is what the lesson exists to teach rather than something to supply. Worked example ${PREECLAMPSIA_URGENT_DELIVERY_DEMONSTRATION_VERSION} is the module's twenty-first observed-state one. It gates on a count of accepted pressure checks and two cumulative doses, all of which only rise, because the pressure itself is not monotone once labetalol is given and a beat keyed on it would walk backwards. Its magnesium beat states plainly that the drug will not move the pressure at all, before the learner watches it not do so. Its closing beat declines the credit the demonstration would otherwise take: it reports the exact scoring of the prophylaxis-alone run including the pressure that did not change, names the not-exercised outcome, and repeats that the response just watched is a bounded trajectory rather than a prediction for a person. tests/unit/anesthesia-preeclampsia-urgent-delivery-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
