import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { RAPID_SEQUENCE_INDUCTION } from './scenarios/rapid-sequence-induction';
import { RAPID_SEQUENCE_INDUCTION_FIXTURES } from './rapid-sequence-induction-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { RAPID_SEQUENCE_INDUCTION_DEMONSTRATION_VERSION } from './demo/rapid-sequence-induction-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function rapidSequenceInductionCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== RAPID_SEQUENCE_INDUCTION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.2.0' || RAPID_SEQUENCE_INDUCTION_FIXTURES.contentVersion !== '0.2.0'
    || RAPID_SEQUENCE_INDUCTION_FIXTURES.seed !== 3120
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || RAPID_SEQUENCE_INDUCTION_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(RAPID_SEQUENCE_INDUCTION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['rapid-sequence-induction-fixtures.ts binds seed 3120 and content 0.2.0 to expert, hurried-induction error, same-reserve recovery, and no-action paths over 7,200 ticks. Nothing the objectives are scored on is authored. The forty-one-year-old woman of 74 kg is a set of baseline parameters and a healthy respiratory profile, and the end-tidal oxygen fraction, the saturation, the train-of-four count and ratio, the post-tetanic count and the laryngoscopic view all come out of the shared engine. The block in particular is a Wierda-anchored teaching model rather than a script: the count reaches zero about thirty-five seconds after 0.6 mg/kg and the post-tetanic count returns roughly forty-eight minutes of simulated time later, and the transcripts record what the model did rather than asserting a schedule. tests/integration/anesthesia-rapid-sequence-induction-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['No tray of its own and no lesson-specific action: the flowmeter, three syringes, a laryngoscope, the ventilator and the reversal control, all available from the first tick. Two choices carry the lesson. The first is the order, and the cockpit does not enforce it — rocuronium can be given before the propofol, the engine accepts it, and the only thing that reports it is the debrief afterwards, which is the point. The second is the rocuronium dose: the syringe offers 0.6, 1.0 and 1.2 mg/kg, the larger doses give a block this bounded model does not bring back inside the case, and the transcripts take 0.6 so that the reversal objective can be exercised at all. That is a trade the scenario leaves open and the evidence names rather than hides. The lesson intubates nobody, paralyses nobody, gives no real drug, and predicts no outcome for any person.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The transcripts end at 7,200 ticks, which is well past the last declared timeline event at 3,000 and past the point where the expert path\'s train-of-four ratio has recovered to 1.00. There is no maintenance, emergence or end of operation in this scenario and the briefing does not offer one: the slice is the induction, the airway and the reversal, and the run stops because that slice is over rather than because the patient reached a state.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all five objectives from the replayed state trace and the engine event log rather than from a score kept during the run. The counterfactual holds the missing reserve constant and changes the order. The error path gives no oxygen at all, gives rocuronium before the propofol, instruments at tick 1,400 and does not resume ventilation until 2,600: measured, the saturation reaches 72% and the depth-index alarm fires at tick 3,801 — she is paralysed and light, which is the harm the wrong order causes and which no objective here scores. The recovery path keeps the identical missing reserve, gives the hypnotic first, waits for the count to reach zero, instruments at 1,250 and ventilates a hundred ticks later. It recovers eight points of saturation, 80% against 72%, and preoxygenate-before-induction is not met on either path and stays that way, because a reserve that was never built cannot be built afterwards.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['rapid-sequence-induction-fixtures.ts binds exact-content expert, hurried-induction error, same-reserve recovery, and no-action pathways to seed 3120 for deterministic replay through the shared engine. Scored through the real debrief, the expert path meets all five; the error path is not met, not met, not met, met, not exercised; the recovery path is not met, met, not met, met, met; and the no-action path is not exercised, not exercised, met, not exercised, not exercised. Two readings are worth naming. protect-the-apnea-margin is met on the no-action path, because she is a healthy forty-one-year-old who simply keeps breathing when nobody induces her — the objective is meaningful only once an induction has happened, and the evidence claims it is exercised rather than that idleness passed it. And reverse-observed-block is the only objective in this module so far that the engine can refuse outright: sugammadex is rejected at 2 mg/kg with no twitches, at 4 mg/kg without a post-tetanic count, and at any dose while the block is still deepening, so the error path\'s "not exercised" is the absence of an attempt and not a rejected one.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here, and the two that matter in this patient are the preoxygenation ladder — which reads the inspired fraction and the recorded boluses, so it speaks before the first drug and not after — and the apnoea-after-bolus prompt. Both are silent on the unassisted setting and suppressed while any alarm is active. No rule names the drug order, which is deliberate: the order is the thing this lesson exists to leave to the learner, and a prompt that gave it away would remove the only decision the debrief can report on. Worked example ${RAPID_SEQUENCE_INDUCTION_DEMONSTRATION_VERSION} is the module's third observed-state one, and its hardest gate is a direction rather than a level. Reversal is refused unless the block is receding, and the post-tetanic count cannot establish that on its own: it reads 3 while the block is deepening and 1 again while it wears off, so a beat gated on the count fires on the wrong limb and is rejected. What separates the limbs is the pair of rocuronium curves — during onset the plasma runs ahead of the effect site, during offset the effect site is the higher of the two — so the example gates on the crossover and narrates it, which is the same hysteresis the module's explainer is about. Two beats dispatch nothing: the wait for the count to reach zero, and the wait for the block to recede. Both are the ones a learner is tempted to skip. A confirmation beat was written and cut before it shipped, because the ratio reaches 0.9 on the tick after an accepted reversal and the beat was unreachable; what it had to say is in the closing narration instead. tests/unit/anesthesia-rapid-sequence-induction-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover of the error path's opening, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
