import type { Scenario } from './scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { ROUTINE_INHALATIONAL_MAINTENANCE } from './scenarios/routine-inhalational-maintenance';
import { ROUTINE_INHALATIONAL_MAINTENANCE_FIXTURES } from './routine-inhalational-maintenance-fixtures';
import { TUTOR_RULES } from './tutor/guidance';
import { INHALATIONAL_MAINTENANCE_DEMONSTRATION_VERSION } from './demo/inhalational-maintenance-demonstration';

/** The tutor version this evidence is bound at: every rule carries the same one. */
const TUTOR_VERSION = TUTOR_RULES[0]?.version ?? 'unbound';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function routineInhalationalMaintenanceCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'anesthesia' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== ROUTINE_INHALATIONAL_MAINTENANCE_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0'
    || ROUTINE_INHALATIONAL_MAINTENANCE_FIXTURES.contentVersion !== '0.1.0'
    || ROUTINE_INHALATIONAL_MAINTENANCE_FIXTURES.seed !== 8158
    || TUTOR_VERSION !== '0.1.0'
    || TUTOR_RULES.some((rule) => rule.version !== TUTOR_VERSION)
    || INHALATIONAL_MAINTENANCE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(ROUTINE_INHALATIONAL_MAINTENANCE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['routine-inhalational-maintenance-fixtures.ts binds seed 8158 and content 0.1.0 to expert, deepened-and-left error, late-withdrawal recovery, and no-action paths over 5,400 ticks. Every number is solver output on the shared volatile and remifentanil models: a 19.5% pressure rise on the expert path against 27.3% untreated, depth traces spending 100%, 33% and 74% of the scored window in band, and scenario endings at 68, 43 and 67 mmHg. tests/integration/anesthesia-routine-inhalational-maintenance-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['The module\'s only continuous titration problem. There are no bounded response actions at all: a volatile percentage the engine accepts anywhere from 0 to 8, and a remifentanil infusion rate, against a stimulus at a known tick. That makes the decision space genuinely large rather than a list, and the transcripts had to be found by searching it -- the expert path was located by sweeping start ticks, volatile levels and withdrawal ticks and keeping the profile that satisfied all three objectives at once. Its window is narrow: deepening at tick 2,350 to 4.0% and withdrawing at 2,600.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The dissection runs from tick 2,400 to 3,600 and the transcripts end at 5,400, at the scenario\'s own case-end prompt. The third objective reads the scenario end directly -- a pressure of at least 65 mmHg and a depth back between 40 and 60 -- so the run must continue long enough after the stimulus for a withdrawal to have taken effect, or for its absence to be visible. That is what separates the error path\'s ending of 43 mmHg from the recovery path\'s 67.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx derives all three objectives from the replayed state trace and the recorded actions rather than from a score kept during the run. The counterfactual is a crisis handled correctly and a case finished badly. The error path anticipates exactly as the expert path does -- the same infusion, the same volatile step at the same tick -- and simply never brings the volatile back down. Measured, it is NOT MET, met, partly met: it earns the stimulus objective outright, and the depth trace spends 33% of the scored window in band while the case ends at 43 mmHg with a depth index of 20. The recovery path withdraws at tick 3,000 rather than 2,600 and reads partly met, met, met, ending at 67 mmHg. Getting the stimulus right is not the same as finishing the case, and the objectives are arranged so that a learner can see the difference.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['routine-inhalational-maintenance-fixtures.ts binds exact-content expert, deepened-and-left error, late-withdrawal recovery, and no-action pathways to seed 8158 for deterministic replay through the shared engine. Three readings are pinned by tests, and the first is the reason this lesson is worth binding. ACTING EARLIER SCORES WORSE, AND WORSE THAN NOT ACTING. Take the expert path\'s four actions and move the volatile step 550 ticks earlier, changing nothing else: the measured pressure rise goes from 19.5% to 29.6%, against 27.3% on a path that does nothing at all. The rise is measured from the pressure immediately before the stimulus, so an early deepening lowers its own denominator -- the drug is spent, the baseline falls, and the percentage the objective scores gets larger. A learner told to "get ahead of the stimulus" would reliably produce the worse number. The second is that the remifentanil rate is nearly inert for that objective: a sixteen-fold range from 0.05 to 0.8 moves the scored rise by a tenth of a percentage point, against the 10.1 points that the volatile\'s TIMING moves it. What the measure effectively reads is that an infusion was running, plus what the volatile did and when. The evidence says so rather than letting a reader infer an opioid dose-response the model does not contain. The third is that the no-action path EARNS the depth objective outright, because the scenario\'s baseline settings hold the depth index at 60 -- the top of the band -- for the whole case; the first objective is lost by acting badly rather than by not acting.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`The nine authored tutor rules at version ${TUTOR_VERSION} in tutor/guidance.ts apply here and are silent on the unassisted setting and suppressed while any alarm is active. None of them names the stimulus timing, which is correct: when to deepen is the judgement this lesson exists to build, and a prompt would give away the one thing worth discovering. Worked example ${INHALATIONAL_MAINTENANCE_DEMONSTRATION_VERSION} is the module's thirty-fifth observed-state one and the only one gated on the CLOCK rather than on latched state -- forced by the lesson, since nothing observable distinguishes "too early" from "just right" except the time itself. Its phases are half-open tick windows so no beat can be re-entered, which was found by failing: an earlier draft gated only on the tick and the volatile percentage, and re-emitted its deepen beat after the withdrawal had brought the percentage back down -- in the cockpit that would have re-dispatched 4% sevoflurane onto a patient who had just been lightened. A test now pins that every beat id appears exactly once. It holds deliberate waiting beats while the infusion runs and the stimulus is still minutes away, and its deepen beat states before acting that doing the same thing four minutes earlier is measurably worse rather than more cautious. Its closing beat declines the credit the demonstration would take by reporting the 29.6% figure and naming the denominator effect that produces it. tests/unit/anesthesia-inhalational-maintenance-worked-example.test.ts drives every beat through the real engine from both a fresh start and a handover, and tests/unit/worked-example-offer.test.ts pins that what this audit claims is what the product actually offers.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
