import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { ACUTE_PULMONARY_EDEMA } from './scenarios/acute-pulmonary-edema';
import { ACUTE_PULMONARY_EDEMA_FIXTURES } from './acute-pulmonary-edema-fixtures';
import { ACUTE_PULMONARY_EDEMA_TUTOR_VERSION } from './tutor/acute-pulmonary-edema-guidance';
import { ACUTE_PULMONARY_EDEMA_DEMONSTRATION_VERSION } from './demo/acute-pulmonary-edema-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other —
 * including respiratory medicine's separate pulmonary-edema support lesson.
 */
export function acutePulmonaryEdemaCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'emergency-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== ACUTE_PULMONARY_EDEMA_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || ACUTE_PULMONARY_EDEMA_FIXTURES.contentVersion !== '0.1.0'
    || ACUTE_PULMONARY_EDEMA_FIXTURES.seed !== 5150
    || ACUTE_PULMONARY_EDEMA_TUTOR_VERSION !== '0.1.0'
    || ACUTE_PULMONARY_EDEMA_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(ACUTE_PULMONARY_EDEMA)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['acute-pulmonary-edema-fixtures.ts binds seed 5150 and content 0.1.0 to expert, diuretic-alone error, recovery, and no-action paths. The seventy-two-year-old woman of 74 kg with abrupt dyspnoea and orthopnoea, short-phrase speech, respiratory rate 32/min, SpO2 90%, blood pressure 188/112 mmHg, diffuse crackles and a raised jugular venous pressure; the authored ECG showing sinus tachycardia without ST elevation, the radiograph showing a bilateral perihilar interstitial-alveolar pattern and the focused ultrasound showing diffuse B-lines with preserved left ventricular contraction; the bounded FiO2 0.40 and PEEP 8 cmH2O teaching display; and the post-treatment monitor at RR 22/min, SpO2 96% and 146/86 mmHg are authored constants. No edema, diuresis, vasodilator, ventilation or treatment-response model is claimed, and no outcome follows from any choice. tests/integration/emergency-acute-pulmonary-edema-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is a single narrative boundary with no non-narrative state event. The progression lives in the engine\'s gates across five recorded steps, and the shape of those gates is the lesson: the whole-patient review is gated ahead of all treatment, the three initial treatments are gated against nothing at all and may be recorded in any order, and the reassessment is gated behind all three plus one further engine tick. Both the order refusal and the too-early reassessment refusal are exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five recorded decisions against four declared objectives: review the respiratory, congestion, pressure and perfusion findings together with the authored ECG, radiograph and ultrasound, the immediate mimics they exclude and the precipitants they do not; record early noninvasive positive pressure with titrated oxygen; record an intravenous loop-diuretic intent for the authored congestion; record an intravenous vasodilator intent on a systolic pressure safely above 110 mmHg; and reassess breathing, oxygenation, pressure and perfusion after a further tick. The three treatments are unordered because none is a prerequisite for the others. The lesson examines nobody, acquires and interprets no test or image, sets up no interface, prepares and delivers no drug, titrates nothing, treats no precipitant, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment against an authored monitor: RR 22/min, SpO2 96%, blood pressure 146/86 mmHg. Later actions cannot restart an ended branch. Those numbers are authored constants rather than a modelled response, and the lesson says so where a learner will read it, so the ending hands over a prompt to look again rather than a claim that the treatment worked.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps the declared objectives to accepted engine events; the no-action path meets none and the expert path meets all four. The counterfactual is the one that ranks the three treatments: the common-error path reviews the pattern, records the loop-diuretic intent alone because that is the word filed under pulmonary edema, and then reaches for the reassessment with positive pressure and the vasodilator never recorded. It is refused, and the two objectives that turn on them stay unmet. The recovery path reaches for support before the pattern review and is refused, reaches for the reassessment on the same tick as the last of the three treatments and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['acute-pulmonary-edema-fixtures.ts binds exact-content expert, diuretic-alone error, recovery, and no-action pathways to seed 5150 for deterministic replay through the shared engine, including the order refusal and the time-gated reassessment refusal.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${ACUTE_PULMONARY_EDEMA_TUTOR_VERSION} read the learner's own recorded steps. The reflex the lesson works against is rank: three initial treatments are open at once and none waits on the others, but one of the three is the word most people have filed under "pulmonary edema" and it is the slowest of the three at what the next few minutes need. Because the three lanes are unordered, the claim the lesson turns on lives in the beat for the state where none of them has been recorded, which is the only such beat every path passes through — preserved contraction and a systolic of 188 point at redistribution rather than an accumulation of litres, so positive pressure is the fastest lever and recording the diuretic does not buy the other two. The pressure beat names the qualifying systolic and reads afterload reduction as the same problem seen from the other end. The diuretic beat is honest about when natriuresis starts to matter. The reassessment beat says why it is gated behind a further tick, and that the numbers that come back are authored rather than modelled. Worked example ${ACUTE_PULMONARY_EDEMA_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine, takes the fastest treatment first and the most familiar last to make the absence of a rank visible, and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere sets up the interface, names a dose, titrates a drug, or claims the treatment worked. tests/unit/emergency-acute-pulmonary-edema-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/emergency-acute-pulmonary-edema.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
