import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { ACUTE_AORTIC_SYNDROME } from './scenarios/acute-aortic-syndrome';
import { ACUTE_AORTIC_SYNDROME_FIXTURES } from './acute-aortic-syndrome-fixtures';
import { ACUTE_AORTIC_SYNDROME_TUTOR_VERSION } from './tutor/acute-aortic-syndrome-guidance';
import { ACUTE_AORTIC_SYNDROME_DEMONSTRATION_VERSION } from './demo/acute-aortic-syndrome-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other.
 *
 * The first emergency-medicine sidecar. Five objectives, so the shared audit
 * satisfies the observable-objectives cap; meaningful-progression is supplied
 * by hand, because the timeline is two narratives with no state event and the
 * progression lives in the engine's five order refusals instead.
 */
export function acuteAorticSyndromeCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'emergency-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== ACUTE_AORTIC_SYNDROME_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || ACUTE_AORTIC_SYNDROME_FIXTURES.contentVersion !== '0.1.0'
    || ACUTE_AORTIC_SYNDROME_FIXTURES.seed !== 7481
    || ACUTE_AORTIC_SYNDROME_TUTOR_VERSION !== '0.1.0'
    || ACUTE_AORTIC_SYNDROME_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(ACUTE_AORTIC_SYNDROME)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['acute-aortic-syndrome-fixtures.ts binds seed 7481 and content 0.1.0 to expert, escalate-before-the-repeat-exam error, recovery, and no-action paths. The fifty-eight-year-old hypertensive man with abrupt severe chest pain maximal at onset 18 minutes ago and now interscapular, at HR 104/min and SpO2 96% on room air with initial arm pressures of 198/106 and 194/104 mmHg, symmetric pulses, perfusion and neurology and a nondiagnostic ECG; the authored six-minute evolution to left-arm 202/108 against right-arm 166/92 mmHg, a 36 mmHg difference, a newly weak right radial, a cool left foot with diminished pedal pulse and delayed refill, new mild left-arm drift with clear speech and glucose 112 mg/dL; the recorded targets of HR 60-80/min and systolic below 120 mmHg only where perfusion is preserved; and the pre-imaging repeat at HR 82/min with left-arm 156/88 and right-arm 132/78 mmHg are authored constants. No aortic, haemodynamic or imaging model is claimed, the scan never results, and no outcome follows from any choice. tests/integration/acute-aortic-syndrome-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s five order refusals across six recorded steps, and the second step carries the lesson: the first examination is authored symmetric, and the engine makes repeating it a recorded action gated ahead of every pathway decision, so a suspicion becomes three disagreeing territories before anything is escalated or given. The anti-impulse intent is in turn gated ahead of the imaging priority, and the closing repeat behind both. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six recorded decisions against five declared objectives: synthesize the incomplete initial pain, ECG, bilateral pressure, pulse, perfusion and neurologic pattern while keeping acute coronary and other dangerous chest-pain causes plausible and recording no default antithrombotic pathway; repeat bilateral pressures, pulses, limb perfusion and neurologic findings to reveal the authored evolving asymmetry without claiming a diagnosis; escalate to multidisciplinary aortic and critical-care teams while explicitly pausing routine coronary anticoagulation or thrombolysis and isolated stroke thrombolysis pending urgent evaluation; record ICU-level monitoring, arterial-line intent, titrated analgesia and local-protocol intravenous rate control before any vasodilator, with HR 60-80/min and systolic below 120 mmHg qualified by preserved end-organ perfusion; prioritize urgent definitive CT of the aorta and branch vessels while the patient is transportable, with TEE or MRI as a context-dependent alternative and the result explicitly unavailable; and repeat the serial assessment and hand off the uncertainty. The lesson examines nobody, gives no drug and selects no dose, places no line, acquires and interprets no image, consults, transfers and operates on nobody, makes no diagnosis, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded serial reassessment and handoff — pain still present, HR 82/min, left-arm 156/88 and right-arm 132/78 mmHg, persistent weak right radial and left pedal pulses, a still-cool left foot and unchanged mild left-arm drift with clear speech — with the scan explicitly not available. Later actions cannot restart an ended branch. The ending hands over the times, trends, recorded intents, competing diagnoses, malperfusion concern and the missing result rather than a label, and no diagnosis, image result, procedure, transfer, disposition or outcome is simulated.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps the declared objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one a symmetric first examination invites: the common-error path reviews the initial pattern and escalates on the strength of the story alone, without repeating the pulses that turn a suspicion into three disagreeing territories, and is refused because the engine gates it. The recovery path reaches for the repeat examination before the initial pattern has been reviewed and is refused, reaches for the imaging priority before the anti-impulse intent it travels with and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['acute-aortic-syndrome-fixtures.ts binds exact-content expert, escalate-before-the-repeat-exam error, recovery, and no-action pathways to seed 7481 for deterministic replay through the shared engine, including all five order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${ACUTE_AORTIC_SYNDROME_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step. The reflex the lesson works against is the default pathway: a hypertensive man with crushing chest pain and a nondiagnostic ECG is an acute coronary syndrome until proven otherwise, and the treatment for that is the drug you would least like to have given a dissecting aorta. The initial beat picks out "maximal at onset" as the word that separates this from most cardiac pain, which builds, and makes the step's value what it declines to start. The evolution beat says a symmetric examination is a fact about a moment rather than a promise, reads an arm, a leg and a brain as one process at a branch point rather than three diagnoses, and notes the glucose of 112 removes the cheapest explanation for the drift. The escalation beat names both paused pathways and distinguishes pausing from ruling out. The anti-impulse beat explains why the order is the content — a vasodilator at a heart rate of 104 increases the force of each ejection, which is the thing tearing the aorta — and puts a ceiling on chasing the targets, because a lower pressure that starves a cool foot or a drifting arm is not a better number. The imaging beat prioritises CT because he is transportable now and may not stay so, and states plainly that the scan has not resulted. Worked example ${ACUTE_AORTIC_SYNDROME_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine to the handoff and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere gives an antithrombotic, names a rate-control drug or dose, reads the CT, or states the diagnosis. tests/unit/acute-aortic-syndrome-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/emergency-acute-aortic-syndrome.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
