import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { ADULT_ASTHMA } from './scenarios/adult-asthma';
import { ADULT_ASTHMA_FIXTURES } from './adult-asthma-fixtures';
import { ADULT_ASTHMA_TUTOR_VERSION } from './tutor/adult-asthma-guidance';
import { ADULT_ASTHMA_DEMONSTRATION_VERSION } from './demo/adult-asthma-demonstration';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function adultAsthmaCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'emergency-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== ADULT_ASTHMA_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || ADULT_ASTHMA_FIXTURES.contentVersion !== '0.1.0'
    || ADULT_ASTHMA_FIXTURES.seed !== 3412
    || ADULT_ASTHMA_TUTOR_VERSION !== '0.1.0'
    || ADULT_ASTHMA_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(ADULT_ASTHMA)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['adult-asthma-fixtures.ts binds seed 3412 and content 0.1.0 to expert, deferred-corticosteroid error, recovery, and no-action paths. The forty-one-year-old woman of 68 kg with known asthma and one prior admission, speaking single words with accessory-muscle use, respiratory rate 34/min, SpO2 91% on room air and a peak expiratory flow of 32% predicted; the absent urticaria, angioedema, focal air-entry loss, fever and oedema that the authored review records; the fixed six-puff salbutamol and four-puff ipratropium pressurised-inhaler-and-spacer bundle; the fixed adult oxygen target band of 92 to 95%; and the authored repeat peak flow of 55% predicted are authored constants. No airway-obstruction, bronchodilator, corticosteroid or treatment-response model is claimed beyond the shared obstruction event present on arrival, and no outcome follows from any choice. tests/integration/emergency-adult-asthma-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The progression lives in the engine\'s gates across five recorded steps, and the shape of those gates is the lesson: the severity and mimic review is gated ahead of all treatment, the three initial treatments are gated against nothing at all and may be recorded in any order, and the reassessment is gated behind all three plus one further engine tick. Both the order refusal and the too-early reassessment refusal are exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five recorded decisions against four declared objectives: review the authored severity findings, the two that carry a number and the immediate alternative causes the review excludes; record controlled oxygen against a target band rather than a direction of travel; give the fixed conservative inhaled bronchodilator bundle by pressurised inhaler and spacer; record systemic-corticosteroid intent within the first hour; and reassess symptoms, signs, oxygenation, waveform and peak flow after a further tick. The three treatments are unordered because none is a prerequisite for the others. The lesson examines nobody, performs no spirometry, blood gas or imaging, prepares and delivers no drug, teaches no inhaler technique, sets no device, individualises no dose, repeats no cycle, determines no disposition, writes no prescription, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment against an authored repeat peak flow of 55% predicted. Later actions cannot restart an ended branch. That number is an authored constant rather than a modelled response, and the lesson says so where a learner will read it, so the ending hands over a prompt to look again rather than a claim that the treatment worked or a decision about disposition.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps the declared objectives to accepted engine events; the no-action path meets none and the expert path meets all four. The counterfactual is the one that saves the slow drug for after the verdict: the common-error path reviews severity, records oxygen and the inhaled bundle, and then reaches for the reassessment intending to decide about corticosteroid once the nebulised treatment has been judged. It is refused, and the objective that pairs the two treatment intents stays unmet. The recovery path reaches for the inhaled bundle before the severity review and is refused, reaches for the reassessment on the same tick as the last of the three treatments and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['adult-asthma-fixtures.ts binds exact-content expert, deferred-corticosteroid error, recovery, and no-action pathways to seed 3412 for deterministic replay through the shared engine, including the order refusal and the time-gated reassessment refusal.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${ADULT_ASTHMA_TUTOR_VERSION} read the learner's own recorded steps. The reflex the lesson works against is the verdict: three initial treatments are open at once and none waits on another, but they act on three different clocks, and the slowest of the three is the one whose entire advantage is being given early — so it is the one held back until the fast treatment has been judged, which is the only deferral here that cannot be recovered in the same visit. Because the three lanes are unordered, that claim lives in the beat for the state where none of them has been recorded, the only such beat every path passes through. The severity beat names speech and peak flow as the two findings that grade it and says a quiet chest here would be worse rather than better. The oxygen beat reads the 92 to 95% band as a target that can be missed in both directions rather than a direction of travel. The bronchodilator beat says why a spacer is not the budget option at this severity and why ipratropium is in a severe-exacerbation bundle specifically. The reassessment beat says why a second treatment cycle should follow a second look rather than a clock, why the reassessment is gated behind a further tick, and that the numbers that come back are authored rather than modelled. Worked example ${ADULT_ASTHMA_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine, deliberately records the hours-away drug before the minutes-away one to make the absence of a rank visible, and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere teaches inhaler technique, names an individualised dose, opens the oxygen without a ceiling, or claims the treatment worked. tests/unit/emergency-adult-asthma-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/emergency-adult-asthma.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
