import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { COPD_EXACERBATION } from './scenarios/copd-exacerbation';
import { COPD_EXACERBATION_FIXTURES } from './copd-exacerbation-fixtures';
import { COPD_EXACERBATION_TUTOR_VERSION } from './tutor/copd-exacerbation-guidance';
import { COPD_EXACERBATION_DEMONSTRATION_VERSION } from './demo/copd-exacerbation-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other —
 * including respiratory medicine's separate COPD transition lesson.
 */
export function copdExacerbationCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'emergency-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== COPD_EXACERBATION_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || COPD_EXACERBATION_FIXTURES.contentVersion !== '0.1.0'
    || COPD_EXACERBATION_FIXTURES.seed !== 2857
    || COPD_EXACERBATION_TUTOR_VERSION !== '0.1.0'
    || COPD_EXACERBATION_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(COPD_EXACERBATION)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['copd-exacerbation-fixtures.ts binds seed 2857 and content 0.1.0 to expert, no-indication error, recovery, and no-action paths. The increased dyspnoea, short-phrase speech, respiratory rate 28/min, heart rate 104/min, accessory-muscle use, diffuse wheeze, increased sputum purulence and SpO2 90% on room air; the authored arrival gas of pH 7.36, PaCO2 52 mmHg and PaO2 58 mmHg; the absent focal consolidation, oedema, pneumothorax, abrupt pleuritic onset and new unilateral leg finding; the fixed 88 to 92% oxygen target; the fixed air-driven short-acting beta-agonist plus anticholinergic bundle; the 40 mg prednisone-equivalent five-day course; the purulence antibiotic indication; and the authored repeat pH of 7.38 are authored constants. No airway-obstruction, bronchodilator, corticosteroid, antibiotic or gas-exchange response model is claimed beyond the shared sustained-obstruction event present on arrival, and no outcome follows from any choice. tests/integration/emergency-copd-exacerbation-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The progression lives in the engine\'s gates across six recorded steps: the severity, mimic and blood-gas review is gated ahead of all treatment, the four initial treatments are gated against nothing at all and may be recorded in any order, and the reassessment is gated behind all four plus one further engine tick. Both the order refusal and the too-early reassessment refusal are exercised by a reference transcript, and a test replays four different orderings of the four treatments to show none of them is refused.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six recorded decisions against five declared objectives: review the authored severity findings together with the arrival blood gas and the immediate alternative causes the review excludes; record controlled oxygen against an 88 to 92% target with serial gases rather than a direction of travel; give the fixed air-driven inhaled bronchodilator bundle; record a five-day systemic-corticosteroid intent; record the antibiotic indication by name, which is authored sputum purulence; and reassess symptoms, gas and ventilatory need after a further tick. The four treatments are unordered because none is a prerequisite for the others. The lesson examines nobody, samples no blood, acquires no image, ECG or culture, prepares and delivers no drug, sets up no device or non-invasive ventilation, individualises and repeats no dose, selects no antibiotic agent, writes no prescription, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment against an authored repeat pH of 7.38 with immediate non-invasive ventilation not selected in this improving vignette. Later actions cannot restart an ended branch. Those numbers are authored constants rather than a modelled response, and the lesson says so where a learner will read it, so the ending hands over the comparison the repeat gas exists to make rather than a claim that the treatment worked.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps the declared objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one that never names an indication: the common-error path reviews severity, records oxygen, the bronchodilators and the corticosteroid course, and then reaches for the reassessment without recording what the antibiotic would be for. It is refused, and the antibiotic-indication objective stays unmet. The recovery path reaches for oxygen before the blood gas has been read and is refused, reaches for the reassessment on the same tick as the last of the four treatments and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['copd-exacerbation-fixtures.ts binds exact-content expert, no-indication error, recovery, and no-action pathways to seed 2857 for deterministic replay through the shared engine, including the order refusal and the time-gated reassessment refusal.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Seven observed-state prompts at version ${COPD_EXACERBATION_TUTOR_VERSION} read the learner's own recorded steps. The reflex the lesson works against is generosity with oxygen, and its least-expected consequence: because the four treatments are unordered, the claim lives in the beat for the state where none of them has been recorded, the only such beat every path passes through — a PaCO2 of 52 puts a ceiling on the oxygen, and the same fact is why the bronchodilator control says air-driven, since a nebuliser run off wall oxygen is an oxygen delivery device nobody wrote a target for. The gas carrying the drug is itself a dose. The severity beat reads a nearly normal pH beside a raised carbon dioxide as evidence that the retention is chronic rather than an hour old. The oxygen beat names the pairing to be afraid of: a saturation that looks better while the pH falls. The bronchodilator beat says what to do if he needs oxygen during the treatment. The corticosteroid beat says why five days and why not tapering. The antibiotic beat is named after the indication rather than a drug, because reaching for one on the diagnosis alone treats a population for what a subset has. The reassessment beat says the number that decides ventilatory support is the pH rather than the carbon dioxide. Worked example ${COPD_EXACERBATION_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere runs the nebuliser on oxygen, opens the flowmeter, names an antibiotic agent, or claims the treatment worked. tests/unit/emergency-copd-exacerbation-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/emergency-copd-exacerbation.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding alongside the pre-existing tests/ui/copd-exacerbation.test.tsx.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
