import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { HYPERKALEMIA_WITH_ECG_CHANGE } from './scenarios/hyperkalemia-with-ecg-change';
import { HYPERKALEMIA_WITH_ECG_CHANGE_FIXTURES } from './hyperkalemia-with-ecg-change-fixtures';
import { HYPERKALEMIA_WITH_ECG_CHANGE_TUTOR_VERSION } from './tutor/hyperkalemia-with-ecg-change-guidance';
import { HYPERKALEMIA_WITH_ECG_CHANGE_DEMONSTRATION_VERSION } from './demo/hyperkalemia-with-ecg-change-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other —
 * including the cardiology hyperkalemic-conduction lesson and the renal
 * cardioprotection-and-rebound lesson.
 */
export function hyperkalemiaWithEcgChangeCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'emergency-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== HYPERKALEMIA_WITH_ECG_CHANGE_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || HYPERKALEMIA_WITH_ECG_CHANGE_FIXTURES.contentVersion !== '0.1.0'
    || HYPERKALEMIA_WITH_ECG_CHANGE_FIXTURES.seed !== 7183
    || HYPERKALEMIA_WITH_ECG_CHANGE_TUTOR_VERSION !== '0.1.0'
    || HYPERKALEMIA_WITH_ECG_CHANGE_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(HYPERKALEMIA_WITH_ECG_CHANGE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['hyperkalemia-with-ecg-change-fixtures.ts binds seed 7183 and content 0.1.0 to expert, stopped-at-the-better-tracing error, recovery, and no-action paths. The sixty-seven-year-old with stage 4 chronic kidney disease, two days of diarrhoea and poor intake, lisinopril and a new trimethoprim-sulfamethoxazole course, alert with HR 48/min and BP 104/68 mmHg; the non-haemolysed repeat panel of potassium 7.1 mmol/L, glucose 108 mg/dL, bicarbonate 17 mmol/L and creatinine 3.8 mg/dL; the authored arrival ECG of bradycardia, peaked T waves, P-wave flattening and QRS 140 ms; the authored later treating-team report of HR 62/min, visible P waves and QRS 104 ms with potassium unchanged at 7.1 mmol/L; and the one-hour panel of potassium 5.8 mmol/L, glucose 92 mg/dL, HR 68/min and QRS 98 ms are authored constants. No potassium kinetic, calcium, insulin, beta-agonist or removal response model is claimed, the engine records that no treatment was learner-delivered and that the intent click changes neither ECG nor potassium, and no outcome follows from any choice. tests/integration/emergency-hyperkalemia-with-ecg-change-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s gates across seven recorded steps: the confirmed-potassium and driver review is gated ahead of everything, the calcium intent ahead of all four lanes, the four lanes are gated against each other not at all, and the final panel sits behind all four. Two separate time gates then carry the honesty of the lesson — the post-calcium ECG report cannot be read on the same tick the calcium intent was recorded, and the one-hour panel cannot be read on the same tick as the last lane, because a result drawn at the instant of a decision reports the clock rather than the patient. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Seven recorded decisions against five declared objectives: review the confirmed non-haemolysed potassium, the ECG toxicity, the glucose, the renal function and the four additive drivers; record an immediate local-protocol intravenous calcium-salt intent for membrane protection; read the authored later treating-team ECG report alongside the unchanged potassium; record insulin-glucose with baseline and structured post-treatment glucose surveillance; record an adjunct nebulised beta-2 agonist as one temporary shifting lane rather than sole therapy; hold lisinopril and trimethoprim and record kidney-injury evaluation, renal consultation, a local potassium-removal strategy and a dialysis contingency; and reassess the one-hour potassium, glucose and ECG against rebound risk. The four lanes are unordered because none is a prerequisite for the others. The lesson acquires no specimen, interprets no real ECG, selects no calcium salt, agent or dose, delivers nothing, gives no fluid, dialyses nobody, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded one-hour reassessment: potassium 5.8 mmol/L, glucose 92 mg/dL, HR 68/min, QRS 98 ms, no new instability. Later actions cannot restart an ended branch. The engine event states in the same breath that severe toxicity improved and that chronic kidney disease plus temporary shifting create rebound risk, so the ending hands over continued ECG, potassium, glucose, renal, removal and recurrence surveillance rather than a resolution. Dialysis, later course, disposition and outcome are explicitly outside it.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps the declared objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one the lesson is built around: the common-error path reviews the pattern, records calcium, reads a post-team ECG showing the QRS back at 104 ms, and reaches for the final panel with the potassium still 7.1 mmol/L and nothing recorded that would shift or remove it. It is refused, and the three objectives from shifting onward stay unmet. The recovery path reaches for calcium before the review and is refused, reads the ECG report on the same tick as the calcium intent and is refused again, reaches for the final panel on the same tick as the last lane and is refused a third time, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['hyperkalemia-with-ecg-change-fixtures.ts binds exact-content expert, stopped-at-the-better-tracing error, recovery, and no-action pathways to seed 7183 for deterministic replay through the shared engine, including both order refusals and both time-gated refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Eight observed-state prompts at version ${HYPERKALEMIA_WITH_ECG_CHANGE_TUTOR_VERSION} read the learner's own recorded steps. The reflex the lesson works against is believing the tracing: calcium changes the electrocardiogram without changing the chemistry, so the most reassuring thing that happens in the next few minutes is also the least informative — the QRS comes back from 140 ms to 104 ms with the potassium still reading exactly 7.1. Because the four lanes are unordered, that pairing lives in the beat for the state where none of them has been recorded, the only such beat every path passes through, together with the frame that protect, shift and remove are three different jobs and only one of them lowers the total. The recognition beat reads the widening QRS as a conduction system failing in the order it always fails in, and names trimethoprim as a potassium-sparing diuretic wearing an antibiotic label — a distal sodium-channel blocker like amiloride, prescribed alongside an ACE inhibitor in stage 4 disease. The calcium beat says not one millimole leaves the body. The insulin beat makes the glucose surveillance part of the order rather than a courtesy, since the hypoglycaemia arrives an hour later after the team has moved on and chronic kidney disease slows insulin clearance. The beta-agonist beat says why it is an adjunct and not a therapy. The removal beat names the two prescriptions a clinician can stop in the department as the difference between treating an episode and preventing the next one. The reassessment beat says most of the fall is potassium sitting inside cells on a promise. Worked example ${HYPERKALEMIA_WITH_ECG_CHANGE_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere claims the potassium fell after calcium, treats the beta-agonist as sufficient, reads a real ECG, or calls the episode over. tests/unit/emergency-hyperkalemia-with-ecg-change-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/emergency-hyperkalemia-with-ecg-change.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding alongside the pre-existing tests/ui/hyperkalemia-with-ecg-change.test.tsx.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
