import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { OPIOID_TOXICITY } from './scenarios/opioid-toxicity';
import { OPIOID_TOXICITY_FIXTURES } from './opioid-toxicity-fixtures';
import { OPIOID_TOXICITY_TUTOR_VERSION } from './tutor/opioid-toxicity-guidance';
import { OPIOID_TOXICITY_DEMONSTRATION_VERSION } from './demo/opioid-toxicity-demonstration';

/** Exact-version evidence for one lesson, and no claim about any other. */
export function opioidToxicityCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'emergency-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== OPIOID_TOXICITY_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || OPIOID_TOXICITY_FIXTURES.contentVersion !== '0.1.0'
    || OPIOID_TOXICITY_FIXTURES.seed !== 6407
    || OPIOID_TOXICITY_TUTOR_VERSION !== '0.1.0'
    || OPIOID_TOXICITY_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(OPIOID_TOXICITY)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['opioid-toxicity-fixtures.ts binds seed 6407 and content 0.1.0 to expert, antidote-before-the-bag error, recovery, and no-action paths. The unresponsive patient with a definite pulse at 58/min, respirations 4/min, SpO2 78%, end-tidal CO2 68 mmHg, pinpoint pupils, glucose 102 mg/dL and a reported fentanyl exposure with no authored trauma, focal deficit, seizure or arrest and co-exposure still possible; the initial response panel of respirations 14/min, SpO2 97% on oxygen, end-tidal CO2 43 mmHg, pulse 72/min and response to voice with persistent drowsiness; and the twenty-five-minute panel of respirations 7/min, SpO2 90% on oxygen, end-tidal CO2 58 mmHg, deeper drowsiness and a pulse at 64/min are authored constants. No opioid, antagonist, receptor or ventilation-response model is claimed, and no outcome follows from any choice. tests/integration/emergency-opioid-toxicity-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s five order refusals across six recorded steps in one strict chain with no time gates, and two of those gates carry the lesson: the naloxone intent is refused until ventilation is recorded, and the safety plan is refused until the twenty-five-minute recurrence panel has been read. The recurrence panel itself is the progression the lesson turns on, because it moves in the wrong direction after a correct response. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Six recorded decisions against five declared objectives: confirm a pulse and review responsiveness, breathing, oxygenation, carbon dioxide, glucose, exposure and immediate mimics; record emergency activation with airway opening, oxygen, effective bag-mask ventilation, monitoring, access and glucose review; record a local-protocol naloxone intent while ventilation continues, titrated toward normal spontaneous breathing and protective reflexes rather than mandatory full arousal; read the authored initial response panel; read the authored twenty-five-minute recurrence panel; and record renewed support, a repeat antagonist intent, prolonged-antagonist and higher-acuity contingencies, co-exposure evaluation, monitored observation to a clinical endpoint, and take-home naloxone with use instructions and treatment linkage. The lesson examines nobody, confirms no pulse, ventilates nobody, selects no product, route or dose, delivers and dispenses nothing, sets no observation duration, counsels nobody, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded response to recurrence and a safety plan, deliberately not at the good panel. Later actions cannot restart an ended branch. Observation runs to a stated clinical endpoint — low recurrence risk with normal consciousness and vital signs — rather than to a number of hours, and delivery, later response, observation duration, counselling, dispensing, disposition and outcome are explicitly outside the lesson. Both panels are authored constants rather than modelled responses.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps the declared objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one that reaches for the antidote as though it were the airway: the common-error path reviews the pattern and records the naloxone intent with nobody ventilating a patient breathing four times a minute. It is refused with the reason named — support airway and breathing rather than waiting for an antagonist to work — and the four objectives downstream stay unmet. The recovery path reaches for ventilation before a pulse has been established and is refused, reaches for the safety plan before the recurrence panel that motivates it and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['opioid-toxicity-fixtures.ts binds exact-content expert, antidote-before-the-bag error, recovery, and no-action pathways to seed 6407 for deterministic replay through the shared engine, including all five order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Six observed-state prompts at version ${OPIOID_TOXICITY_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step. The reflex the lesson works against is the antidote: naloxone is the thing everyone knows about this diagnosis and it is neither the first treatment nor the durable one. The recognition beat puts the pulse first because it decides which algorithm you are in, and reads the end-tidal carbon dioxide of 68 as the number that speaks most plainly — saturation reports oxygen, which supplemental oxygen can paper over, while carbon dioxide reports breathing, which nothing but ventilation fixes. The ventilation beat says nothing about naloxone is faster than a bag-mask and that a hypoxic arrest during syringe preparation is a preventable one. The antagonist beat aims at breathing rather than arousal and says why chasing full wakefulness buys vomiting, agitation and a patient who leaves before the opioid has worn off. The initial-response beat names which number the learner is allowed to be pleased about, and why persistent drowsiness is not a failure of the dose. The recurrence beat is the lesson: naloxone has a short duration of action and fentanyl does not, so the antagonist wears off while the agonist is still bound, and the person most at risk is the one who woke up well and was allowed to walk out. The plan beat treats take-home naloxone and treatment linkage as care for the overdose nobody in the department will ever see. Worked example ${OPIOID_TOXICITY_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine, deliberately does not end at the good panel, and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere gives the antagonist before ventilating, chases full arousal, names a dose, or discharges the patient. tests/unit/emergency-opioid-toxicity-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/emergency-opioid-toxicity.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding alongside the pre-existing tests/ui/opioid-toxicity.test.tsx.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
