import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { SEVERE_HYPONATREMIA_WITH_SEIZURE } from './scenarios/severe-hyponatremia-with-seizure';
import { SEVERE_HYPONATREMIA_FIXTURES } from './severe-hyponatremia-with-seizure-fixtures';
import { SEVERE_HYPONATREMIA_TUTOR_VERSION } from './tutor/severe-hyponatremia-with-seizure-guidance';
import { SEVERE_HYPONATREMIA_DEMONSTRATION_VERSION } from './demo/severe-hyponatremia-with-seizure-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other —
 * including the renal and endocrine hyponatraemia lessons.
 */
export function severeHyponatremiaCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'emergency-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== SEVERE_HYPONATREMIA_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || SEVERE_HYPONATREMIA_FIXTURES.contentVersion !== '0.1.0'
    || SEVERE_HYPONATREMIA_FIXTURES.seed !== 1128
    || SEVERE_HYPONATREMIA_TUTOR_VERSION !== '0.1.0'
    || SEVERE_HYPONATREMIA_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(SEVERE_HYPONATREMIA_WITH_SEIZURE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['severe-hyponatremia-with-seizure-fixtures.ts binds seed 1128 and content 0.1.0 to expert, stopped-when-she-woke-up error, recovery, and no-action paths. The witnessed generalised seizure that has stopped with deep somnolence persisting; the repeat sodium of 112 mmol/L, glucose 96 mg/dL and measured serum osmolality of 238 mOsm/kg with no authored ongoing convulsion, trauma, hyperglycaemia or exogenous osmole; the first-hour target rise of 5 mmol/L; the first-hour panel of sodium 117 mmol/L with eyes opening, simple answers, residual confusion, spontaneous breathing, no recurrent seizure and urine output risen from 35 to 180 mL/h; and the handoff ceilings of 10 mmol/L in the first twenty-four hours and 8 mmol/L per twenty-four hours thereafter are authored constants. No sodium, osmolality, diuresis or treatment-response kinetic model is claimed, and no outcome follows from any choice. tests/integration/emergency-severe-hyponatremia-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The shared audit records this requirement as missing because the timeline is two narratives with no non-narrative state event. The progression lives in the engine\'s four order refusals across five recorded steps in one strict chain with no time gates, and the shape of it is the lesson: stabilisation is gated ahead of any sodium-directed intent, the hypertonic saline ahead of the first-hour panel, and the guardrails behind that panel — so nobody can write the correction ceilings without having seen the urine output that makes them necessary. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Five recorded decisions against five declared objectives: review the neurologic state, the sodium, the glucose, the measured osmolality and the immediate exclusions; record parallel injury protection, airway and breathing support, oxygen and suction readiness, monitoring, access, glucose review and expert escalation; record an immediate local-protocol intermittent hypertonic-saline bolus intent in a close-monitoring environment against a first-hour 5 mmol/L target; read the authored first-hour neurologic, sodium and urine-output panel; and stop the saline while recording correction ceilings, serial sodium and urine review, a chlorthalidone hold, paired serum and urine cause evaluation, thyroid and adrenal review, and a specialist plan to halt or reverse overcorrection. The lesson examines nobody, validates no sample, selects no concentration, bolus volume or fluid, prepares and delivers nothing, diagnoses no cause, gives no desmopressin or free water, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded stop of the hypertonic saline with correction ceilings handed off, not at a corrected sodium. Later actions cannot restart an ended branch. The engine event names the maximum rises, the chlorthalidone hold and a specialist plan to halt or reverse overcorrection, and places testing, diagnosis, fluid selection, desmopressin or free-water treatment, later course, disposition and outcome outside the lesson — so the ending hands over a patient who is autocorrecting and a set of limits rather than a resolution.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps the declared objectives to accepted engine events; the no-action path meets none and the expert path meets all five. The counterfactual is the one that stops when the patient wakes up: the common-error path reviews the pattern, records stabilisation and hypertonic saline, and reaches for the guardrails without reading the first-hour panel — so it never sees the urine output climb from 35 to 180 mL/h, which is the entire warning. It is refused, and the last two objectives stay unmet. The recovery path reaches for the sodium-directed intent before anyone has protected the patient and is refused twice on that gate, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['severe-hyponatremia-with-seizure-fixtures.ts binds exact-content expert, stopped-when-she-woke-up error, recovery, and no-action pathways to seed 1128 for deterministic replay through the shared engine, including all four order refusals.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Five observed-state prompts at version ${SEVERE_HYPONATREMIA_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step. This lesson has two dangers pointing in opposite directions about an hour apart, and the tutor is built around the turn. The recognition beat makes "symptomatic" the load-bearing word, since the same 112 found on a routine panel in someone chatting to you is a different problem with a different tempo, and explains why a measured osmolality is on the panel at all — it closes the artefact loophole. The stabilisation beat says the postictal patient with a sodium of 112 may seize again while the treatment for the first seizure is being drawn up. The hypertonic beat names two counterintuitive things: the first-hour goal is a safe sodium rather than a normal one, and boluses beat an infusion because a bolus is a dose you have finished giving. The reassessment beat is the turn — the sodium result is exactly what was wanted and only half the panel, because the urine output has gone from 35 to 180 mL/h, which is a water diuresis, which means the kidneys have taken the correction over and will not stop where you would have. The number that warned was not the sodium. The guardrails beat gives the ceilings, holds the thiazide as the commonest drug cause of this picture, and names deliberate reversal of an overcorrection as a real and effective thing to do. Worked example ${SEVERE_HYPONATREMIA_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere names a concentration or volume, targets a normal sodium, runs an infusion, or claims the sodium is corrected. tests/unit/emergency-severe-hyponatremia-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/emergency-severe-hyponatremia.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding alongside the pre-existing tests/ui/severe-hyponatremia-with-seizure.test.tsx.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
