import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { UNSTABLE_BRADYCARDIA } from './scenarios/unstable-bradycardia';
import { UNSTABLE_BRADYCARDIA_FIXTURES } from './unstable-bradycardia-fixtures';
import { UNSTABLE_BRADYCARDIA_TUTOR_VERSION } from './tutor/unstable-bradycardia-guidance';
import { UNSTABLE_BRADYCARDIA_DEMONSTRATION_VERSION } from './demo/unstable-bradycardia-demonstration';

/**
 * Exact-version evidence for one lesson, and no claim about any other —
 * including cardiology's symptomatic sinus bradycardia lesson.
 */
export function unstableBradycardiaCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'emergency-medicine' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== UNSTABLE_BRADYCARDIA_FIXTURES.scenarioId
    || scenario.metadata.version !== '0.1.0' || UNSTABLE_BRADYCARDIA_FIXTURES.contentVersion !== '0.1.0'
    || UNSTABLE_BRADYCARDIA_FIXTURES.seed !== 3846
    || UNSTABLE_BRADYCARDIA_TUTOR_VERSION !== '0.1.0'
    || UNSTABLE_BRADYCARDIA_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(UNSTABLE_BRADYCARDIA)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['unstable-bradycardia-fixtures.ts binds seed 3846 and content 0.1.0 to expert, straight-to-the-drug error, recovery, and no-action paths. The regular sinus bradycardia at 38/min with a palpable pulse, BP 78/46 mmHg, drowsiness, ischaemic chest discomfort, cool mottled extremities, delayed capillary refill and SpO2 91% on room air with a patent airway and spontaneous breathing; the fixed 1 mg intravenous atropine intent; and the post-atropine panel of sinus rhythm at 68/min, BP 112/70 mmHg, SpO2 96%, alert mentation, resolving discomfort, warm extremities and improved refill are authored constants. No conduction, vagal, atropine or perfusion response model is claimed beyond the shared rhythm-change event present on arrival, the cause is deliberately not diagnosed, and no outcome follows from any choice. tests/integration/emergency-unstable-bradycardia-runs.test.ts replays every path frame-for-frame across all three guidance levels and both practice regions.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['The progression lives in the engine\'s three refusals across four recorded steps in one strict chain: the rate, rhythm, pulse and compromise review is gated ahead of everything, the support bundle ahead of the atropine intent, and the reassessment one further engine tick behind the drug. That last gate is the honest one — a rhythm asked about at the instant an intent is recorded reports the clock rather than the patient. Every refusal is exercised by a reference transcript.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['Four recorded decisions against four declared objectives: review the rate, rhythm, palpable pulse and the cardiopulmonary compromise that makes the rate matter; confirm the patent airway and spontaneous breathing and record oxygen, help, continuous cardiorespiratory and pulse monitoring and vascular access, with positive-pressure ventilation deliberately not selected because breathing remains adequate; record a fixed 1 mg intravenous atropine intent for persistent bradycardia with compromise; and reassess after a further tick. The lesson examines nobody, delivers no oxygen, drug or fluid, places no line, operates no equipment, paces nobody, gives no adrenergic infusion, diagnoses no cause, determines no disposition, and predicts no outcome.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The branch ends at a recorded reassessment showing an improved rate, pressure, mentation and perfusion — and the engine event states in the same breath that reversible-cause evaluation and escalation remain necessary, with repeated atropine, pacing, adrenergic infusions, definitive diagnosis, recurrence, disposition and outcome all outside the lesson. Later actions cannot restart an ended branch. The ending hands over a patient who is better and undiagnosed rather than a resolution.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['src/modules/anesthesia/ui/Debrief.tsx maps the declared objectives to accepted engine events; the no-action path meets none and the expert path meets all four. The counterfactual is the one that treats the number: the common-error path reviews the rate and the compromise and reaches straight for atropine with no oxygen, no monitor and no access recorded. It is refused, and the two objectives downstream stay unmet. The recovery path reaches for the support bundle before anyone established that the rate is the problem and is refused, reaches for the reassessment on the same tick as the atropine and is refused again, and still completes from the same positions.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['unstable-bradycardia-fixtures.ts binds exact-content expert, straight-to-the-drug error, recovery, and no-action pathways to seed 3846 for deterministic replay through the shared engine, including both order refusals and the time-gated reassessment refusal.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Four observed-state prompts at version ${UNSTABLE_BRADYCARDIA_TUTOR_VERSION} read the learner's own recorded steps — one per recorded step. The reflex the lesson works against is treating the number: a rate of 38 in a sleeping endurance athlete is a normal finding and the same number here is an emergency, and the entire difference is in the pressure, the drowsiness and the skin. The support beat gives a better reason than order for the gate the engine enforces — hypoxia is itself a cause of bradycardia and this patient is at 91% on room air, so the oxygen may be treating the rhythm rather than accompanying it, and a bradycardia that improves on oxygen alone tells you something no dose of atropine could. It also names what is deliberately not selected: positive-pressure ventilation, because his breathing is adequate and ventilating him here costs preload he cannot spare. The atropine beat says what the drug buys — vagal blockade at the sinus and atrioventricular nodes, unreliable when the block is below the node or the myocardium is ischaemic — and that arranging pacing and adrenergic infusions is the thing to do while giving it. The reassessment beat reads the panel through mentation and skin rather than the rate, says why it waits a tick, and says a good panel is not permission to stop because the cause was never diagnosed. Worked example ${UNSTABLE_BRADYCARDIA_DEMONSTRATION_VERSION} drives the ordinary controls through the real engine and asks the tutor for its narration rather than storing a copy. A test asserts that no beat anywhere gives the drug before the support, ventilates an adequately breathing patient, names a cause, or calls the episode resolved. tests/unit/emergency-unstable-bradycardia-worked-example.test.ts verifies every beat and every refusal against the real engine, and tests/ui/emergency-unstable-bradycardia.test.tsx verifies the tray, silence when unassisted, stable controls while watching, and version binding alongside the pre-existing tests/ui/unstable-bradycardia.test.tsx.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Automated UI, observed-state and replay checks exist. Exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation remains pending.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['The scenario inherits the shared report control and has an exact-version Worker catalog record. Complete four-surface runtime evidence is not yet bound.'] },
  ];
}
