import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { objectiveFindings } from '@anesthesia/ui/Debrief';
import type { EngineEvent } from '@platform/kernel/protocol';
import { DIABETIC_KETOACIDOSIS } from '../../src/modules/emergency-medicine/scenarios/diabetic-ketoacidosis';
import { DKA_RESOLUTION_TRANSITION as SCENARIO } from '../../src/modules/endocrine-metabolic/scenarios/dka-resolution-transition';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4701) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'dka-resolution-transition-response', payload: { action, ...extras } as never });

describe('Endocrine DKA resolution contract', () => {
  it('validates, follows the fixed resolution report, and keeps learner care and outcome claims false', () => { expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 94, meanArterialMmHg: 86, respiratoryRateBpm: 18, spo2Percent: 98 }); expect(frame.equipment.resuscitation.endocrineDkaResolutionAssessment).toMatchObject({ supportAtTick: null, authoredLateTreatmentUnresolvedDka: true, biochemicalResolutionReported: false }); for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 88, meanArterialMmHg: 86, respiratoryRateBpm: 16, spo2Percent: 98 }); expect(frame.equipment.resuscitation.endocrineDkaResolutionAssessment).toMatchObject({ authoredQualifiedResolutionAndBasalOverlapReport: true, biochemicalResolutionReported: true, historyTakenOrPatientExaminedByLearner: false, glucoseKetoneElectrolyteGasOrTestObtainedCalculatedOrInterpretedByLearner: false, fluidElectrolyteDextroseInsulinBicarbonateOrDrugSelectedOrDeliveredByLearner: false, doseConcentrationRateRouteOrAccessSelectedByLearner: false, infusionOperatedByLearner: false, nutritionPrescribedOrDeliveredByLearner: false, medicationOrTransitionPerformedByLearner: false, precipitantTreatedEducationAccessOrFollowUpArrangedByLearner: false, diagnosisMadeByLearner: false, procedurePerformedByLearner: false, universalDoseOrTreatmentEffectProven: false, independentInsulinSafetyProven: false, durableGlucoseOrPotassiumStabilityProven: false, precipitantResolved: false, dischargeReadinessProven: false, safetyDispositionDetermined: false, outcomePredicted: false }); });
  it('requires serial order and elapsed checkpoints and scores the exact completed transcript', () => { const subject = make(SCENARIO, 4710); const events: EngineEvent[] = [...subject.step().events]; apply(subject, ACTIONS[1]); events.push(...subject.step().events); expect(subject.equipment().resuscitation.endocrineDkaResolutionAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); events.push(...subject.step().events); expect(subject.equipment().resuscitation.endocrineDkaResolutionAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); events.push(...subject.step().events); apply(subject, ACTIONS[5]); events.push(...subject.step().events); expect(subject.equipment().resuscitation.endocrineDkaResolutionAssessment?.handoffAtTick).not.toBeNull(); expect(objectiveFindings(SCENARIO, [], 0, 0, [], events).map(({ outcome }) => outcome)).toEqual(['met', 'met', 'met', 'met', 'met', 'met']); expect(objectiveFindings(SCENARIO, [], 0, 0, [], []).map(({ outcome }) => outcome)).toEqual(['not-met', 'not-met', 'not-met', 'not-met', 'not-met', 'not-met']); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4720); const control = make(SCENARIO, 4720); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { patientName: 'Private Example', notes: 'private note' }); for (const [type, payload] of [['bolus', { drugId: 'insulin', amount: 100, unit: 'units' }], ['fluid', { type: 'crystalloid', volumeMl: 1000 }], ['dka-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'cardiac-arrest-non-shockable' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Private Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'dka-resolution-transition-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4721); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.endocrineDkaResolutionAssessment).toBeUndefined(); } const neighbor = make(DIABETIC_KETOACIDOSIS, 4722); const neighborControl = make(DIABETIC_KETOACIDOSIS, 4722); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
