import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { NEONATAL_SEPSIS } from '../../src/modules/neonatology/scenarios/neonatal-sepsis';
import { THERMOREGULATION_FAILURE as SCENARIO } from '../../src/modules/neonatology/scenarios/thermoregulation-failure';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4611) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'neonatal-thermoregulation-response', payload: { action, ...extras } as never });
describe('Neonatology thermoregulation-failure contract', () => {
  it('validates, follows the fixed qualified report, and keeps every learner care and outcome claim false', () => { expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 126, meanArterialMmHg: 42, respiratoryRateBpm: 48, spo2Percent: 97, coreTemperatureC: 35.5 }); expect(frame.equipment.resuscitation.neonatologyThermoregulationAssessment).toMatchObject({ supportAtTick: null, authoredUnintentionalNeonatalHypothermia: true, authoredQualifiedFortyFiveMinuteReport: false }); for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 134, meanArterialMmHg: 42, respiratoryRateBpm: 44, spo2Percent: 97, coreTemperatureC: 36.3 }); expect(frame.equipment.resuscitation.neonatologyThermoregulationAssessment).toMatchObject({ authoredQualifiedFortyFiveMinuteReport: true, historyTakenByLearner: false, newbornExaminedOrScoredByLearner: false, temperatureGlucoseOrTestsObtainedOrInterpretedByLearner: false, diagnosisMadeByLearner: false, warmingCoolingSkinToSkinOrDeviceCarePerformedByLearner: false, setPointOrRewarmingRateSelectedByLearner: false, feedingPerformedByLearner: false, glucoseFluidOrDrugDeliveredByLearner: false, accessObtainedByLearner: false, oxygenOrRespiratorySupportDeliveredByLearner: false, ventilationOrAirwayManagedByLearner: false, resuscitationPerformedByLearner: false, transportOrProcedurePerformedByLearner: false, prescribedRewarmingRateClaimed: false, treatmentEffectProven: false, causeDetermined: false, infectionOrOtherIllnessExcluded: false, durableThermalStabilityProven: false, durableGlucoseStabilityProven: false, feedingSuccessProven: false, safetyDispositionDetermined: false, newbornOutcomePredicted: false, parentOutcomePredicted: false, outcomePredicted: false }); });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4620); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.neonatologyThermoregulationAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyThermoregulationAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyThermoregulationAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.neonatologyThermoregulationAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4630); const control = make(SCENARIO, 4630); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { newbornName: 'Baby Example', notes: 'private note' }); for (const [type, payload] of [['active-cooling', { active: true }], ['bolus', { drugId: 'dextrose', amount: 2, unit: 'mL/kg' }], ['neonatal-sepsis-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'neonatal-apnea' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Baby Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'thermoregulation-failure-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4631); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.neonatologyThermoregulationAssessment).toBeUndefined(); } const neighbor = make(NEONATAL_SEPSIS, 4632); const neighborControl = make(NEONATAL_SEPSIS, 4632); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
