import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { PRETERM_RESPIRATORY_DISTRESS } from '../../src/modules/neonatology/scenarios/preterm-respiratory-distress';
import { NEONATAL_HYPOGLYCEMIA as SCENARIO } from '../../src/modules/neonatology/scenarios/neonatal-hypoglycemia';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4551) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'neonatal-hypoglycemia-response', payload: { action, ...extras } as never });
describe('Neonatology neonatal-hypoglycemia contract', () => {
  it('validates, follows the fixed qualified report, and keeps every learner care and outcome claim false', () => { expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 146, meanArterialMmHg: 46, respiratoryRateBpm: 46, spo2Percent: 97, coreTemperatureC: 36.6 }); expect(frame.equipment.resuscitation.neonatologyHypoglycemiaAssessment).toMatchObject({ supportAtTick: null, authoredSymptomaticConfirmedLowGlucosePattern: true, authoredQualifiedThirtyMinuteReport: false }); for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 140, respiratoryRateBpm: 46, spo2Percent: 97, coreTemperatureC: 36.7 }); expect(frame.equipment.resuscitation.neonatologyHypoglycemiaAssessment).toMatchObject({ authoredQualifiedThirtyMinuteReport: true, historyTakenByLearner: false, newbornExaminedOrScoredByLearner: false, monitoringGlucoseOrTestsObtainedOrInterpretedByLearner: false, diagnosisMadeByLearner: false, feedingPerformedByLearner: false, glucoseGelIvDextroseFluidOrDrugDeliveredByLearner: false, accessObtainedByLearner: false, thermalCarePerformedByLearner: false, deviceHandledByLearner: false, oxygenOrVentilationDeliveredByLearner: false, airwayPlacedOrManagedByLearner: false, resuscitationPerformedByLearner: false, transportOrProcedurePerformedByLearner: false, universalInjuryThresholdClaimed: false, causeDetermined: false, infectionExcluded: false, endocrineOrMetabolicDiseaseExcluded: false, treatmentEffectProven: false, durableGlucoseStabilityProven: false, neurologicSafetyProven: false, feedingSuccessProven: false, safetyDispositionDetermined: false, newbornOutcomePredicted: false, parentOutcomePredicted: false, outcomePredicted: false }); });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4560); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.neonatologyHypoglycemiaAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyHypoglycemiaAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyHypoglycemiaAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.neonatologyHypoglycemiaAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4570); const control = make(SCENARIO, 4570); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { newbornName: 'Baby Example', notes: 'private note' }); for (const [type, payload] of [['bolus', { drugId: 'dextrose', amount: 2, unit: 'mL/kg' }], ['fluid', { type: 'crystalloid', volumeMl: 10 }], ['preterm-respiratory-distress-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'neonatal-apnea' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Baby Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'neonatal-hypoglycemia-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4571); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.neonatologyHypoglycemiaAssessment).toBeUndefined(); } const neighbor = make(PRETERM_RESPIRATORY_DISTRESS, 4572); const neighborControl = make(PRETERM_RESPIRATORY_DISTRESS, 4572); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
