import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { TERM_NEWBORN_TRANSITION } from '../../src/modules/neonatology/scenarios/term-newborn-transition';
import { NEONATAL_APNEA as SCENARIO } from '../../src/modules/neonatology/scenarios/neonatal-apnea';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4401) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'neonatal-apnea-response', payload: { action, ...extras } as never });

describe('Neonatology neonatal-apnea contract', () => {
  it('validates, follows the fixed response, and keeps every learner care and outcome claim false', () => {
    expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 92, meanArterialMmHg: 44, respiratoryRateBpm: 0, spo2Percent: 72, coreTemperatureC: 36.6 });
    expect(frame.equipment.resuscitation.neonatologyApneaAssessment).toMatchObject({ supportAtTick: null, authoredApneaAndHeartRatePattern: true, authoredQualifiedEarlyResponse: false });
    for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 126, respiratoryRateBpm: 28, spo2Percent: 90 });
    expect(frame.equipment.resuscitation.neonatologyApneaAssessment).toMatchObject({ authoredQualifiedEarlyResponse: true, newbornExaminedOrScoredByLearner: false, monitoringOrTestsInterpretedByLearner: false, diagnosisMadeByLearner: false, positioningDryingWarmingSuctionOrStimulationPerformedByLearner: false, oxygenOrVentilationDeliveredByLearner: false, airwayManagedByLearner: false, ventilationCorrectiveStepsPerformedByLearner: false, compressionsAccessFluidGlucoseOrDrugDeliveredByLearner: false, feedingPerformedByLearner: false, resuscitationPerformedByLearner: false, transportOrProcedurePerformedByLearner: false, durableBreathingProven: false, stableTransitionProven: false, neurologicSafetyProven: false, causeDetermined: false, safetyDispositionDetermined: false, newbornOutcomePredicted: false, parentOutcomePredicted: false, outcomePredicted: false });
  });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4410); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.neonatologyApneaAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyApneaAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyApneaAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.neonatologyApneaAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4420); const control = make(SCENARIO, 4420); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { newbornName: 'Baby Example', notes: 'private note' }); for (const [type, payload] of [['ventilator', { fio2: 1 }], ['bolus', { drugId: 'epinephrine', amount: 0.03, unit: 'mg' }], ['term-newborn-transition-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'neonatal-apnea' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Baby Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'neonatal-apnea-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4421); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.neonatologyApneaAssessment).toBeUndefined(); } const neighbor = make(TERM_NEWBORN_TRANSITION, 4422); const neighborControl = make(TERM_NEWBORN_TRANSITION, 4422); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
