import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { INEFFECTIVE_VENTILATION_CORRECTION } from '../../src/modules/neonatology/scenarios/ineffective-ventilation-correction';
import { NEONATAL_BRADYCARDIA as SCENARIO } from '../../src/modules/neonatology/scenarios/neonatal-bradycardia';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4461) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'neonatal-bradycardia-response', payload: { action, ...extras } as never });

describe('Neonatology neonatal-bradycardia contract', () => {
  it('validates, follows the fixed qualified response, and keeps every learner care and outcome claim false', () => {
    expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 48, meanArterialMmHg: 34, respiratoryRateBpm: 0, spo2Percent: 62, coreTemperatureC: 36.4 });
    expect(frame.equipment.resuscitation.neonatologyBradycardiaAssessment).toMatchObject({ supportAtTick: null, authoredSevereBradycardiaAfterAdequateVentilation: true, authoredQualifiedCompressionResponse: false });
    for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 74, meanArterialMmHg: 37, respiratoryRateBpm: 0, spo2Percent: 71 });
    expect(frame.equipment.resuscitation.neonatologyBradycardiaAssessment).toMatchObject({ authoredQualifiedCompressionResponse: true, newbornExaminedOrScoredByLearner: false, monitoringOrTestsInterpretedByLearner: false, diagnosisMadeByLearner: false, maskOrDeviceHandledByLearner: false, pressureRatePeepOrOxygenSelectedByLearner: false, oxygenOrVentilationDeliveredByLearner: false, airwayPlacedOrVerifiedByLearner: false, compressionPerformedByLearner: false, accessFluidBloodGlucoseOrDrugDeliveredByLearner: false, feedingPerformedByLearner: false, resuscitationPerformedByLearner: false, transportOrProcedurePerformedByLearner: false, durableCirculationProven: false, durableBreathingProven: false, stableTransitionProven: false, neurologicSafetyProven: false, causeDetermined: false, treatmentEffectProven: false, safetyDispositionDetermined: false, newbornOutcomePredicted: false, parentOutcomePredicted: false, outcomePredicted: false });
  });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4470); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.neonatologyBradycardiaAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyBradycardiaAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyBradycardiaAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.neonatologyBradycardiaAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4480); const control = make(SCENARIO, 4480); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { newbornName: 'Baby Example', notes: 'private note' }); for (const [type, payload] of [['ventilator', { fio2: 0.21 }], ['bolus', { drugId: 'epinephrine', amount: 0.03, unit: 'mg' }], ['ineffective-ventilation-correction-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'cardiac-arrest-non-shockable' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Baby Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'neonatal-bradycardia-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4481); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.neonatologyBradycardiaAssessment).toBeUndefined(); } const neighbor = make(INEFFECTIVE_VENTILATION_CORRECTION, 4482); const neighborControl = make(INEFFECTIVE_VENTILATION_CORRECTION, 4482); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
