import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { NEONATAL_APNEA } from '../../src/modules/neonatology/scenarios/neonatal-apnea';
import { INEFFECTIVE_VENTILATION_CORRECTION as SCENARIO } from '../../src/modules/neonatology/scenarios/ineffective-ventilation-correction';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4431) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'ineffective-ventilation-correction-response', payload: { action, ...extras } as never });

describe('Neonatology ineffective-ventilation-correction contract', () => {
  it('validates, follows the fixed correction response, and keeps every learner care and outcome claim false', () => {
    expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 78, meanArterialMmHg: 42, respiratoryRateBpm: 0, spo2Percent: 68, coreTemperatureC: 36.5 });
    expect(frame.equipment.resuscitation.neonatologyIneffectiveVentilationAssessment).toMatchObject({ supportAtTick: null, authoredIneffectiveVentilationPattern: true, authoredQualifiedCorrectionResponse: false });
    for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 118, respiratoryRateBpm: 24, spo2Percent: 76 });
    expect(frame.equipment.resuscitation.neonatologyIneffectiveVentilationAssessment).toMatchObject({ authoredQualifiedCorrectionResponse: true, newbornExaminedOrScoredByLearner: false, monitoringOrTestsInterpretedByLearner: false, diagnosisMadeByLearner: false, maskOrDeviceHandledByLearner: false, positioningDryingWarmingSuctionOrStimulationPerformedByLearner: false, pressureRatePeepOrOxygenSelectedByLearner: false, oxygenOrVentilationDeliveredByLearner: false, ventilationCorrectiveStepsPerformedByLearner: false, airwayPlacedByLearner: false, compressionsAccessFluidGlucoseOrDrugDeliveredByLearner: false, feedingPerformedByLearner: false, resuscitationPerformedByLearner: false, transportOrProcedurePerformedByLearner: false, durableBreathingProven: false, stableTransitionProven: false, airwayOrLungDiseaseExcluded: false, neurologicSafetyProven: false, causeDetermined: false, safetyDispositionDetermined: false, newbornOutcomePredicted: false, parentOutcomePredicted: false, outcomePredicted: false });
  });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4440); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.neonatologyIneffectiveVentilationAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyIneffectiveVentilationAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyIneffectiveVentilationAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.neonatologyIneffectiveVentilationAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4450); const control = make(SCENARIO, 4450); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { newbornName: 'Baby Example', notes: 'private note' }); for (const [type, payload] of [['ventilator', { fio2: 1 }], ['bolus', { drugId: 'epinephrine', amount: 0.03, unit: 'mg' }], ['neonatal-apnea-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'neonatal-apnea' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Baby Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'ineffective-ventilation-correction-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4451); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.neonatologyIneffectiveVentilationAssessment).toBeUndefined(); } const neighbor = make(NEONATAL_APNEA, 4452); const neighborControl = make(NEONATAL_APNEA, 4452); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
