import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { DELIVERY_ROOM_TO_NICU_HANDOFF } from '../../src/modules/neonatology/scenarios/delivery-room-to-nicu-handoff';
import { NEONATAL_TENSION_PNEUMOTHORAX as SCENARIO } from '../../src/modules/neonatology/scenarios/neonatal-tension-pneumothorax';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4621) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'neonatal-tension-pneumothorax-response', payload: { action, ...extras } as never });

describe('Neonatology neonatal-tension-pneumothorax contract', () => {
  it('validates, follows the fixed qualified response, and keeps every learner treatment and outcome claim false', () => { expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 92, meanArterialMmHg: 31, spo2Percent: 71, coreTemperatureC: 36.6 }); expect(frame.equipment.resuscitation.neonatologyTensionPneumothoraxAssessment).toMatchObject({ supportAtTick: null, authoredSuddenAsymmetricCardiopulmonaryDeterioration: true, authoredQualifiedTwoMinutePostdecompressionReport: false }); for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 138, meanArterialMmHg: 40, spo2Percent: 91 }); expect(frame.equipment.resuscitation.neonatologyTensionPneumothoraxAssessment).toMatchObject({ authoredQualifiedTwoMinutePostdecompressionReport: true, historyTakenByLearner: false, newbornExaminedByLearner: false, monitoringImagingOrTestsObtainedOrInterpretedByLearner: false, circuitAirwayVentilatorOxygenOrDeviceCheckedOrOperatedByLearner: false, pressureVolumeRateOxygenPeepEquipmentOrSiteSelectedByLearner: false, oxygenationVentilationOrAirwayManagedByLearner: false, decompressionOrDrainPerformedByLearner: false, accessAnalgesiaFluidBloodOrDrugDeliveredByLearner: false, resuscitationPerformedByLearner: false, transportCommunicationDocumentationOrCounselingPerformedByLearner: false, procedurePerformedByLearner: false, diagnosisConfirmed: false, alternativeCauseExcluded: false, airLeakResolved: false, durableOxygenationOrCirculationProven: false, safetyDispositionDetermined: false, newbornOutcomePredicted: false, parentOutcomePredicted: false, outcomePredicted: false }); });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4630); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.neonatologyTensionPneumothoraxAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyTensionPneumothoraxAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyTensionPneumothoraxAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.neonatologyTensionPneumothoraxAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4640); const control = make(SCENARIO, 4640); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { newbornName: 'Baby Example', notes: 'private note' }); for (const [type, payload] of [['ventilator', { fio2: 1, peep: 8 }], ['bolus', { drugId: 'morphine', amount: 100, unit: 'mg' }], ['delivery-room-to-nicu-handoff-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'tension-pneumothorax' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Baby Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'neonatal-tension-pneumothorax-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4641); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.neonatologyTensionPneumothoraxAssessment).toBeUndefined(); } const neighbor = make(DELIVERY_ROOM_TO_NICU_HANDOFF, 4642); const neighborControl = make(DELIVERY_ROOM_TO_NICU_HANDOFF, 4642); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
