import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { THERMOREGULATION_FAILURE } from '../../src/modules/neonatology/scenarios/thermoregulation-failure';
import { DELIVERY_ROOM_TO_NICU_HANDOFF as SCENARIO } from '../../src/modules/neonatology/scenarios/delivery-room-to-nicu-handoff';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4641) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'delivery-room-to-nicu-handoff-response', payload: { action, ...extras } as never });
describe('Neonatology delivery-room-to-NICU handoff contract', () => {
  it('validates, follows the fixed receiver report, and keeps every learner care and outcome claim false', () => { expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 142, meanArterialMmHg: 40, respiratoryRateBpm: 58, spo2Percent: 93, coreTemperatureC: 36.5 }); expect(frame.equipment.resuscitation.neonatologyNicuHandoffAssessment).toMatchObject({ supportAtTick: null, authoredPostresuscitationTransfer: true, authoredReceiverCheckBackAndTenMinuteArrivalReport: false }); for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step(); expect(frame.state).toMatchObject({ heartRateBpm: 140, meanArterialMmHg: 40, respiratoryRateBpm: 54, spo2Percent: 94, coreTemperatureC: 36.4 }); expect(frame.equipment.resuscitation.neonatologyNicuHandoffAssessment).toMatchObject({ authoredReceiverCheckBackAndTenMinuteArrivalReport: true, historyTakenByLearner: false, newbornExaminedOrScoredByLearner: false, recordOrMonitoringObtainedOrInterpretedByLearner: false, diagnosisMadeByLearner: false, warmingCoolingCpapOxygenOrDeviceOperatedByLearner: false, respiratorySupportVentilationOrAirwayManagedByLearner: false, accessGlucoseFluidBloodOrDrugDeliveredByLearner: false, feedingPerformedByLearner: false, resuscitationPerformedByLearner: false, transportPositioningOrSupportPerformedByLearner: false, communicationDocumentationCounselingOrCheckBackPerformedByLearner: false, procedurePerformedByLearner: false, sharedUnderstandingProven: false, treatmentEffectProven: false, diagnosisOrCauseDetermined: false, durableStabilityProven: false, feedingSafetyProven: false, safetyDispositionDetermined: false, newbornOutcomePredicted: false, parentOutcomePredicted: false, outcomePredicted: false }); });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4650); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.neonatologyNicuHandoffAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyNicuHandoffAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyNicuHandoffAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.neonatologyNicuHandoffAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4660); const control = make(SCENARIO, 4660); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { newbornName: 'Baby Example', notes: 'private note' }); for (const [type, payload] of [['ventilator', { fio2: 1, peep: 8 }], ['fluid', { type: 'crystalloid', volumeMl: 21 }], ['neonatal-thermoregulation-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'neonatal-apnea' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Baby Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'delivery-room-to-nicu-handoff-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4661); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.neonatologyNicuHandoffAssessment).toBeUndefined(); } const neighbor = make(THERMOREGULATION_FAILURE, 4662); const neighborControl = make(THERMOREGULATION_FAILURE, 4662); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
