import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { NEONATAL_BRADYCARDIA } from '../../src/modules/neonatology/scenarios/neonatal-bradycardia';
import { MECONIUM_STAINED_TRANSITION as SCENARIO } from '../../src/modules/neonatology/scenarios/meconium-stained-transition';
const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4491) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'meconium-stained-transition-response', payload: { action, ...extras } as never });

describe('Neonatology meconium-stained-transition contract', () => {
  it('validates, follows the fixed observation report, and keeps every learner care and outcome claim false', () => {
    expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 138, meanArterialMmHg: 46, respiratoryRateBpm: 44, coreTemperatureC: 36.8 });
    expect(frame.equipment.resuscitation.neonatologyMeconiumTransitionAssessment).toMatchObject({ supportAtTick: null, authoredVigorousMeconiumTransition: true, authoredQualifiedThirtyMinuteReport: false });
    for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 132, respiratoryRateBpm: 44, spo2Percent: 96, coreTemperatureC: 36.7 });
    expect(frame.equipment.resuscitation.neonatologyMeconiumTransitionAssessment).toMatchObject({ authoredQualifiedThirtyMinuteReport: true, newbornExaminedOrScoredByLearner: false, monitoringOrTestsInterpretedByLearner: false, diagnosisMadeByLearner: false, positioningDryingWarmingOrStimulationPerformedByLearner: false, suctionPerformedByLearner: false, deviceHandledByLearner: false, oxygenOrVentilationDeliveredByLearner: false, airwayPlacedOrManagedByLearner: false, compressionsAccessFluidGlucoseOrDrugDeliveredByLearner: false, feedingPerformedByLearner: false, resuscitationPerformedByLearner: false, transportOrProcedurePerformedByLearner: false, meconiumAspirationExcluded: false, otherRespiratoryDiseaseExcluded: false, durableSafetyProven: false, feedingSuccessProven: false, safetyDispositionDetermined: false, newbornOutcomePredicted: false, parentOutcomePredicted: false, outcomePredicted: false });
  });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4500); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.neonatologyMeconiumTransitionAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyMeconiumTransitionAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.neonatologyMeconiumTransitionAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.neonatologyMeconiumTransitionAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4510); const control = make(SCENARIO, 4510); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { newbornName: 'Baby Example', notes: 'private note' }); for (const [type, payload] of [['ventilator', { fio2: 1 }], ['bolus', { drugId: 'epinephrine', amount: 0.03, unit: 'mg' }], ['neonatal-bradycardia-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'neonatal-apnea' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Baby Example|private note/); for (const scenario of [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'meconium-stained-transition-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]) { const subject = make(scenario, 4511); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.neonatologyMeconiumTransitionAssessment).toBeUndefined(); } const neighbor = make(NEONATAL_BRADYCARDIA, 4512); const neighborControl = make(NEONATAL_BRADYCARDIA, 4512); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
