import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { MATERNAL_TO_NEONATAL_RESUSCITATION_HANDOFF } from '../../src/modules/obstetrics/scenarios/maternal-to-neonatal-resuscitation-handoff';
import { OXYTOCIN_ASSOCIATED_UTERINE_TACHYSYSTOLE as SCENARIO } from '../../src/modules/obstetrics/scenarios/oxytocin-associated-uterine-tachysystole';

const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4201) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'oxytocin-associated-uterine-tachysystole-response', payload: { action, ...extras } as never });

describe('Obstetrics oxytocin-tachysystole contract', () => {
  it('validates, follows the fixed course, and keeps every learner care and outcome claim false', () => {
    expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 92, systolicMmHg: 122, diastolicMmHg: 68, meanArterialMmHg: 86, respiratoryRateBpm: 18, spo2Percent: 98, coreTemperatureC: 36.9 });
    expect(frame.equipment.resuscitation.obstetricsOxytocinTachysystoleAssessment).toMatchObject({ supportAtTick: null, authoredOxytocinTachysystolePattern: true, authoredQualifiedEarlyRecovery: false });
    for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step();
    expect(frame.equipment.resuscitation.obstetricsOxytocinTachysystoleAssessment).toMatchObject({ authoredQualifiedEarlyRecovery: true, patientExaminedOrPalpatedByLearner: false, monitoringOrTestsInterpretedByLearner: false, diagnosisMadeByLearner: false, infusionOperatedByLearner: false, positionChangedByLearner: false, oxygenOrFluidDeliveredByLearner: false, drugOrDoseSelectedByLearner: false, fetalStimulationOrAmnioinfusionPerformedByLearner: false, anesthesiaSurgeryOrDeliveryPerformedByLearner: false, newbornCarePerformedByLearner: false, fetalRecoveryProven: false, restartEligibilityDetermined: false, birthPlanDetermined: false, newbornSafetyProven: false, safetyDispositionDetermined: false, maternalOutcomePredicted: false, newbornOutcomePredicted: false, outcomePredicted: false });
  });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4210); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.obstetricsOxytocinTachysystoleAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.obstetricsOxytocinTachysystoleAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.obstetricsOxytocinTachysystoleAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.obstetricsOxytocinTachysystoleAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4220); const control = make(SCENARIO, 4220); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { patientName: 'Patient Example', notes: 'private note' }); for (const [type, payload] of [['infusion', { drugId: 'oxytocin', rate: 0, unit: 'mu/min' }], ['ventilator', { fio2: 1 }], ['bolus', { drugId: 'terbutaline', amount: 0.25, unit: 'mg' }], ['maternal-to-neonatal-resuscitation-handoff-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'fetal-distress' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Patient Example|private note/); const malformed = [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'oxytocin-associated-uterine-tachysystole-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]; for (const scenario of malformed) { const subject = make(scenario, 4221); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.obstetricsOxytocinTachysystoleAssessment).toBeUndefined(); } const neighbor = make(MATERNAL_TO_NEONATAL_RESUSCITATION_HANDOFF, 4222); const neighborControl = make(MATERNAL_TO_NEONATAL_RESUSCITATION_HANDOFF, 4222); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
