import { describe, expect, it } from 'vitest';
import { AnesthesiaEngine } from '@anesthesia/engine';
import { validateScenario } from '@anesthesia/scenarios/schema';
import { HIGH_NEURAXIAL_BLOCK_OBSTETRIC_COORDINATION } from '../../src/modules/obstetrics/scenarios/high-neuraxial-block-obstetric-coordination';
import { FAILED_OBSTETRIC_INTUBATION_OXYGENATION_FIRST as SCENARIO } from '../../src/modules/obstetrics/scenarios/failed-obstetric-intubation-oxygenation-first';

const ACTIONS = SCENARIO.metadata.objectives.map(({ id }) => id);
const make = (scenario = SCENARIO, seed = 4001) => new AnesthesiaEngine({ scenario, seed, practiceRegion: 'US' });
const apply = (subject: AnesthesiaEngine, action: unknown, extras = {}) => subject.apply({ tick: subject.tick, type: 'failed-obstetric-intubation-oxygenation-first-response', payload: { action, ...extras } as never });

describe('Obstetrics failed-intubation contract', () => {
  it('validates, follows the fixed course, and keeps every learner treatment and outcome claim false', () => {
    expect(validateScenario(SCENARIO)).toEqual([]); const subject = make(); let frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 112, systolicMmHg: 106, diastolicMmHg: 64, meanArterialMmHg: 78, respiratoryRateBpm: 12, spo2Percent: 97, coreTemperatureC: 36.7 });
    expect(frame.equipment.resuscitation.obstetricsFailedIntubationAssessment).toMatchObject({ supportAtTick: null, authoredFailedIntubationPattern: true, authoredQualifiedProceedingCourse: false });
    for (const action of ACTIONS.slice(0, 4)) { apply(subject, action); frame = subject.step(); } apply(subject, ACTIONS[4]); frame = subject.step();
    expect(frame.state).toMatchObject({ heartRateBpm: 108, systolicMmHg: 110, diastolicMmHg: 66, meanArterialMmHg: 81, respiratoryRateBpm: 12, spo2Percent: 98 });
    expect(frame.equipment.resuscitation.obstetricsFailedIntubationAssessment).toMatchObject({ authoredQualifiedProceedingCourse: true, patientExaminedByLearner: false, monitoringInterpretedByLearner: false, diagnosisMadeByLearner: false, airwayManagedByLearner: false, oxygenDeliveredByLearner: false, ventilationDeliveredByLearner: false, airwayDeviceSelectedOrManipulatedByLearner: false, positionChangedByLearner: false, suctionOrFrontOfNeckAccessPerformedByLearner: false, drugDoseDeviceAnesthesiaOrBirthPlanSelectedByLearner: false, wakeOrProceedDecisionMadeByLearner: false, surgeryPerformedByLearner: false, deliveryPerformedByLearner: false, newbornAssessedByLearner: false, airwaySafetyProven: false, aspirationExcluded: false, awarenessExcluded: false, fetalRecoveryProven: false, treatmentEffectProven: false, newbornSafetyProven: false, safetyDispositionDetermined: false, maternalOutcomePredicted: false, newbornOutcomePredicted: false, outcomePredicted: false });
  });
  it('requires serial order and elapsed checkpoints', () => { const subject = make(SCENARIO, 4010); subject.step(); apply(subject, ACTIONS[1]); expect(subject.step().equipment.resuscitation.obstetricsFailedIntubationAssessment?.contextAtTick).toBeNull(); for (const action of ACTIONS.slice(0, 4)) apply(subject, action); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.obstetricsFailedIntubationAssessment?.reassessmentAtTick).toBeNull(); apply(subject, ACTIONS[4]); expect(subject.step().equipment.resuscitation.obstetricsFailedIntubationAssessment?.reassessmentAtTick).not.toBeNull(); apply(subject, ACTIONS[5]); expect(subject.step().equipment.resuscitation.obstetricsFailedIntubationAssessment?.handoffAtTick).not.toBeNull(); });
  it('fails closed for hostile, physical, malformed, and neighboring actions', () => { const hostile = make(SCENARIO, 4020); const control = make(SCENARIO, 4020); hostile.step(); control.step(); for (const action of [null, {}, '__proto__', 'x'.repeat(10_000)]) apply(hostile, action, { patientName: 'Patient Example', notes: 'private note' }); for (const [type, payload] of [['airway-device', { device: 'tracheal-tube' }], ['airway-maneuver', { maneuver: 'jaw-thrust' }], ['ventilator', { fio2: 1 }], ['bolus', { drugId: 'propofol', amount: 100, unit: 'mg' }], ['high-neuraxial-block-obstetric-coordination-response', { action: ACTIONS[0] }], ['inject-crisis', { crisisId: 'failed-intubation' }]] as const) hostile.apply({ tick: -999, type, payload: payload as never }); const refused = hostile.step(); expect(refused.state).toEqual(control.step().state); expect(JSON.stringify(refused.events)).not.toMatch(/Patient Example|private note/); const malformed = [{ ...SCENARIO, metadata: { ...SCENARIO.metadata, id: 'failed-obstetric-intubation-oxygenation-first-lookalike' } }, { ...SCENARIO, timeline: SCENARIO.timeline.slice(0, 1) }, { ...SCENARIO, timeline: [...SCENARIO.timeline, SCENARIO.timeline[0]!] }]; for (const scenario of malformed) { const subject = make(scenario, 4021); subject.step(); apply(subject, ACTIONS[0]); expect(subject.step().equipment.resuscitation.obstetricsFailedIntubationAssessment).toBeUndefined(); } const neighbor = make(HIGH_NEURAXIAL_BLOCK_OBSTETRIC_COORDINATION, 4022); const neighborControl = make(HIGH_NEURAXIAL_BLOCK_OBSTETRIC_COORDINATION, 4022); neighbor.step(); neighborControl.step(); apply(neighbor, ACTIONS[0]); expect(neighbor.step().equipment.resuscitation).toEqual(neighborControl.step().equipment.resuscitation); });
});
