import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { INHERITED_URGENCY_AN_EMERGENCY_THAT_MOSTLY_IS_NOT_ONE } from './scenarios/inherited-urgency-an-emergency-that-mostly-is-not-one';
import { INHERITED_URGENCY_FIXTURES } from './inherited-urgency-fixtures';

export function inheritedUrgencyCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'oncology' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== INHERITED_URGENCY_FIXTURES.scenarioId || scenario.metadata.version !== '0.1.0'
    || INHERITED_URGENCY_FIXTURES.contentVersion !== '0.1.0' || INHERITED_URGENCY_FIXTURES.seed !== 2806
    || JSON.stringify(scenario) !== JSON.stringify(INHERITED_URGENCY_AN_EMERGENCY_THAT_MOSTLY_IS_NOT_ONE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['inherited-urgency-fixtures.ts binds seed 2806 and content 0.1.0 to expert, incomplete-care, recovery, and no-action contrasts. No venous, oedema, radiotherapy-response, or tumour-shrinkage model is claimed, and no outcome follows from any choice.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['inherited-urgency.ts runs two authored transitions, and this is the only lesson in this module where nothing about the patient moves. At 25 minutes a treatment slot is offered for tonight while the observations, the absent stridor, and the conscious level are unchanged, because what arrives is an offer rather than a deterioration. Acute oncology answers 40 minutes after the pathway is secured, accepts him, books and flags the biopsy, tells the ward which findings to call about, takes ownership of radiotherapy, stenting, systemic therapy, steroid and anticoagulation decisions, and states that the histology determines which of those he gets. The offer is authored and follows from nothing the learner did.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['The learner records the three findings that would grade this as life-threatening and whether each is present, records that the tissue decides the treatment, secures the diagnostic pathway, records bounded qualified-team treatment intent, and reviews the boundaries in both directions. Starting radiotherapy tonight before the biopsy, grading the presentation by the swelling, sending him home to await the biopsy, and giving a diuretic for the distended veins are each refused, the first for the sequence rather than for the treatment.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The recorded grading findings, the recorded tissue-decides reasoning, the secured pathway, bounded intent, the boundary review, and a current assessment permit handoff with the diagnosis and the treatment open. Instructor takeover bounds a run with no secured pathway at 180 minutes, longer than this module’s hyperleukocytosis lesson because this presentation does wait, or an unfinished session at eight hours.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['Seven event-bound objectives distinguish grading by findings rather than by appearance, the histology as the treatment decision rather than a delay before it, securing a pathway as the active alternative to treating, refusing a sequence rather than a treatment, bounded qualified-team intent, reading a proportion in both directions, and handing off what would change the answer overnight. Refused shortcuts remain visible, and no diagnosis, treatment effect, or outcome is certified.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['inherited-urgency-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways for deterministic replay through the shared engine, including the authored treatment offer.'] },
    { id: 'guidance-and-demonstration', status: 'missing', evidence: ['This slice ships no observed-state tutor prompt or worked example for this scenario version.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Local checks do not complete exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['Shared report controls and local privacy tests do not establish full inclusive coverage or production Turnstile/D1 verification for this version.'] },
  ];
}
