import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { DEFERRED_STEP_A_DECISION_ATTACHED_TO_A_PERSON } from './scenarios/deferred-step-a-decision-attached-to-a-person';
import { DEFERRED_STEP_FIXTURES } from './deferred-step-fixtures';
import { DEFERRED_STEP_DEMONSTRATION_VERSION } from './demo/deferred-step-demonstration';

export function deferredStepCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'surgery-trauma' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== DEFERRED_STEP_FIXTURES.scenarioId || scenario.metadata.version !== '0.1.0'
    || DEFERRED_STEP_FIXTURES.contentVersion !== '0.1.0' || DEFERRED_STEP_FIXTURES.seed !== 4870
    || DEFERRED_STEP_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(DEFERRED_STEP_A_DECISION_ATTACHED_TO_A_PERSON)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['deferred-step-fixtures.ts binds seed 4870 and content 0.1.0 to expert, incomplete-care, recovery, and no-action contrasts. No infection, healing, wound, or pharmacological model is claimed; both transitions are authored and neither is a patient event.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['deferred-step.ts runs two authored transitions and neither changes the patient. At 4 minutes theatre rings to say the registrar’s case has become more complicated and the review will not happen before half past five, so the step attached to that review moves with it and the clock reaches 55 minutes from injury; the foot, the pulses and every observation are identical either side. The team that can prescribe answers 6 minutes after it is called — the fastest reply in this module, because what is asked for is a decision on a telephone rather than a visit — states that the step does not have to wait for their review, and takes ownership of the prescription, the dressing and photography, and the debridement and its timing. Nothing arrives uncalled.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['The learner records the injury against the clock that the published thresholds use, records the outstanding step as outstanding, records what the interval is attached to together with the fact that nobody in the sentence is at fault, calls the team that can decide and asks for a decision rather than a visit, records bounded qualified-team intent, and reviews the boundaries. Leaving the step attached to the review, reading her stability as time in hand, deferring it to the morning drug chart, and waiting for theatre are each refused; the morning-chart refusal names the specific harm of converting an outstanding step into completed administration, and the theatre refusal names it as the same error at a longer interval.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The recorded injury and clock, the recorded outstanding step, the recorded attachment, the call for a decision, bounded prescribing intent, the boundary review, and a current full assessment permit handoff with the prescription, the dressing and the debridement all open. Instructor takeover bounds a run with no escalation at 30 minutes — the shortest interval in this module, because the window the lesson is about is measured in minutes from an injury that had already happened before the rehearsal began — or an unfinished session at three hours.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['Eight event-bound objectives distinguish recording an injury against the correct clock, recording an outstanding step as outstanding, recognising a timed step attached to somebody’s arrival, recording the attachment without blaming a person, asking for a decision rather than a visit, bounded qualified-team intent, evidence that disagrees about both threshold and starting point, and accountable handoff of a step no longer waiting on an arrival. Refused shortcuts remain visible, and no infection, effect, or outcome is certified.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['deferred-step-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways for deterministic replay through the shared engine.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Observed-state guidance and learner-paused example ${DEFERRED_STEP_DEMONSTRATION_VERSION} use ordinary recorded actions. Unassisted mode is silent and coached withholds the two non-urgent beats. The prompts read only the learner’s own recorded steps, never name an agent or a dose, never assert that she will become infected, and never blame the registrar in theatre, because a learner who leaves believing the answer is to be cross with orthopaedics has learned the wrong thing. The example is driven through the real engine in tests rather than asserted as a script, and it calls before the review slips, because one that acted only when the review moved would teach that the deferral became wrong at the moment it became inconvenient.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Local checks do not complete exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['Shared report controls and local privacy tests do not establish full inclusive coverage or production Turnstile/D1 verification for this version.'] },
  ];
}
