import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { NEGATIVE_SCAN_A_SCAN_THAT_CANNOT_SAY_NO } from './scenarios/negative-scan-a-scan-that-cannot-say-no';
import { NEGATIVE_SCAN_FIXTURES } from './negative-scan-fixtures';

export function negativeScanCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'surgery-trauma' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== NEGATIVE_SCAN_FIXTURES.scenarioId || scenario.metadata.version !== '0.1.0'
    || NEGATIVE_SCAN_FIXTURES.contentVersion !== '0.1.0' || NEGATIVE_SCAN_FIXTURES.seed !== 6841
    || JSON.stringify(scenario) !== JSON.stringify(NEGATIVE_SCAN_A_SCAN_THAT_CANNOT_SAY_NO)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['negative-scan-fixtures.ts binds seed 6841 and content 0.1.0 to expert, incomplete-care, recovery, and no-action contrasts. No leak, perfusion, or healing model is claimed.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['negative-scan.ts runs two authored transitions. At 45 minutes the observations are repeated unchanged, he has vomited once, and he has still passed no flatus, so the only thing that has moved is how long this has been true. The operating team answers 60 minutes after it is contacted, confirms the procedure, the anastomosis and the findings from its own record, states that a report of no evidence of a leak is not the same as no leak, and takes ownership of re-imaging, direct assessment, and any return to theatre. Nothing arrives uncontacted, because the failure being taught is a ward re-reading a report instead of ringing the surgeons. The patient deliberately never deteriorates: a crash would make the decision for the learner.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['The learner records the operation and the course it predicts, records the failure to progress against that course with its duration, records what the reported scan does and does not exclude, contacts the operating team, records bounded qualified-team surgical intent, and reviews the boundaries. Excluding a leak because the scan was negative, dismissing the observations as routine after bowel surgery, repeating the scan tomorrow, and treating the numbers overnight are each refused, and the refusal of the dismissal accepts its premise while rejecting the inference.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The recorded operative course, the recorded failure to progress, the recorded limits of the scan, contact with the operating team, bounded surgical intent, the boundary review, and a current full assessment permit handoff with the diagnosis and the operative decision open. Instructor takeover bounds a run with no escalation at 180 minutes, or an unfinished session at eight hours.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['Seven event-bound objectives distinguish reading a patient against the course his own operation predicts, a trajectory from a single reading, a report of no evidence from an exclusion, returning the patient to the team that made the anastomosis, bounded qualified-team intent, what two small single-centre literatures pointing opposite ways each license, and accountable handoff. Refused shortcuts remain visible, and no leak, operative decision, or outcome is certified.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['negative-scan-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways for deterministic replay through the shared engine.'] },
    { id: 'guidance-and-demonstration', status: 'missing', evidence: ['This lesson opens the module and does not yet carry observed-state guidance or a learner-paused worked example. Nothing in the product offers one for it, so the audit and the offer agree.'] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Local checks do not complete exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['Shared report controls and local privacy tests do not establish full inclusive coverage or production Turnstile/D1 verification for this version.'] },
  ];
}
