import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { QUIET_CHEST_AN_INJURY_WHOSE_SEVERITY_IS_NOT_YET_VISIBLE } from './scenarios/quiet-chest-an-injury-whose-severity-is-not-yet-visible';
import { QUIET_CHEST_FIXTURES } from './quiet-chest-fixtures';
import { QUIET_CHEST_DEMONSTRATION_VERSION } from './demo/quiet-chest-demonstration';

export function quietChestCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'surgery-trauma' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== QUIET_CHEST_FIXTURES.scenarioId || scenario.metadata.version !== '0.1.0'
    || QUIET_CHEST_FIXTURES.contentVersion !== '0.1.0' || QUIET_CHEST_FIXTURES.seed !== 8419
    || QUIET_CHEST_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(QUIET_CHEST_AN_INJURY_WHOSE_SEVERITY_IS_NOT_YET_VISIBLE)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['quiet-chest-fixtures.ts binds seed 8419 and content 0.1.0 to expert, incomplete-care, recovery, and no-action contrasts. No respiratory, pain, healing, or complication model is claimed.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['quiet-chest.ts runs two authored transitions and neither is a clinical finding. At 15 minutes her daughter telephones to say she cannot stay tonight, and the rate, the saturation and the comfort are identical either side of the call — the only lesson in this module whose authored beat is a social fact rather than a physiological or examination one. The admitting team answers 30 minutes after it is asked, confirms the fracture count and the age from its own record, states that it is admitting her for the next two to three days rather than for tonight, and takes ownership of the analgesia plan, the observation interval, any respiratory input, and the timing of discharge. Nothing arrives uncalled and nothing ever deteriorates.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['The learner records the fall and what it broke with the age beside the count, records what being comfortable at rest does and does not measure, records what the count and the age predict, asks the admitting team for a bed and a plan over the right interval, records bounded qualified-team intent, and reviews the boundaries. Discharging on normal observations, reasoning from the absence of a pneumothorax, taking her report of manageable pain as reassurance, and sending her home with tablets and a review in a week are each refused, and the discharge refusal objects to the interval and to recording her as a minor injury rather than to her going home at all.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The recorded fall and count, the recorded limits of a resting chart, the recorded prediction, the request to the admitting team, bounded admission intent, the boundary review, and a current full assessment permit handoff with the complication, the analgesia plan and the discharge date all open. Instructor takeover bounds a run with no escalation at 120 minutes, or an unfinished session at eight hours.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['Eight event-bound objectives distinguish recording a count beside an age, recording what a resting observation measures, refusing a normal chart and a clean film as evidence of a small injury, recording what the count predicts with its figures, asking for admission over the interval the risk lives in, bounded qualified-team intent, a real risk with no proven remedy, and accountable handoff of a plan sized to the third day. Refused shortcuts remain visible, and no complication, discharge date, or outcome is certified.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['quiet-chest-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways for deterministic replay through the shared engine.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Observed-state guidance and learner-paused example ${QUIET_CHEST_DEMONSTRATION_VERSION} use ordinary recorded actions. Unassisted mode is silent and coached withholds the two non-urgent beats. The prompts read only the learner's own recorded steps and never assert that she will develop a complication, because nothing available in the lesson can establish that and asserting it would remove the difficulty. The example is driven through the real engine in tests rather than asserted as a script, and it asks for admission before the daughter telephones, because an example that waited for the social problem would teach that the fracture count was not enough on its own.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Local checks do not complete exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['Shared report controls and local privacy tests do not establish full inclusive coverage or production Turnstile/D1 verification for this version.'] },
  ];
}
