import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { RISING_REQUIREMENT_A_NUMBER_THAT_UNDER_CALLS } from './scenarios/rising-requirement-a-number-that-under-calls';
import { RISING_REQUIREMENT_FIXTURES } from './rising-requirement-fixtures';
import { RISING_REQUIREMENT_DEMONSTRATION_VERSION } from './demo/rising-requirement-demonstration';

export function risingRequirementCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'surgery-trauma' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== RISING_REQUIREMENT_FIXTURES.scenarioId || scenario.metadata.version !== '0.1.0'
    || RISING_REQUIREMENT_FIXTURES.contentVersion !== '0.1.0' || RISING_REQUIREMENT_FIXTURES.seed !== 4219
    || RISING_REQUIREMENT_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(RISING_REQUIREMENT_A_NUMBER_THAT_UNDER_CALLS)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['rising-requirement-fixtures.ts binds seed 4219 and content 0.1.0 to expert, incomplete-care, recovery, and no-action contrasts. No perfusion, compartment, or ischaemia model is claimed.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['rising-requirement.ts runs two authored transitions. At 10 minutes, while the learner is still waiting for the team, he asks a fourth time and passive extension stops him mid-sentence, while the pulse, capillary refill, sensation and every monitored observation stay exactly as they were, so the only thing that moves is the requirement and the clock. The surgical team answers 20 minutes after it is called — sooner than this module’s first lesson, because what is escalated is time-critical rather than uncertain — confirms the fracture and its timing from its own record, states that a single reading neither establishes nor excludes this, and takes ownership of repeat assessment, further measurement, and the decision to decompress. Nothing arrives uncalled.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['The learner records the injury with its elapsed hours, records the rising requirement as a trajectory, records what one pressure reading cannot decide, calls the team that owns the decision, records bounded qualified-team intent, and reviews the boundaries. Reasoning from a present pulse to an intact compartment, excluding on a remembered cut-off, increasing the analgesia and reviewing in the morning, and waiting for a repeat pressure before calling are each refused, and the analgesia refusal objects to the deferral rather than to comfort.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The recorded injury and clock, the recorded requirement, the recorded limits of the reading, the call to the surgical team, bounded decompression intent, the boundary review, and a current full assessment permit handoff with the diagnosis and the operative decision open. Instructor takeover bounds a run with no escalation at 90 minutes — half this module’s first lesson, because here the harm is the delay — or an unfinished session at eight hours.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['Eight event-bound objectives distinguish carrying the clock on a limb, reading a requirement as a finding, refusing an artery as evidence about a compartment, refusing one reading as the discriminating quantity, calling before the number, bounded qualified-team intent, two measures that fail in opposite directions, and accountable handoff. Refused shortcuts remain visible, and no diagnosis, operative decision, or outcome is certified.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['rising-requirement-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways for deterministic replay through the shared engine.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Observed-state guidance and learner-paused example ${RISING_REQUIREMENT_DEMONSTRATION_VERSION} use ordinary recorded actions. Unassisted mode is silent and coached withholds the two non-urgent beats. The prompts read only the learner’s own recorded steps and never say whether this is compartment syndrome, because no measure available in the lesson can settle that. The example is driven through the real engine in tests rather than asserted as a script, and it calls the team before any further number is sought, because the interval spent obtaining one is the harm being taught.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Local checks do not complete exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['Shared report controls and local privacy tests do not establish full inclusive coverage or production Turnstile/D1 verification for this version.'] },
  ];
}
