import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { UNFINISHED_SURVEY_A_PATIENT_WHO_CANNOT_BE_ASKED } from './scenarios/unfinished-survey-a-patient-who-cannot-be-asked';
import { UNFINISHED_SURVEY_FIXTURES } from './unfinished-survey-fixtures';
import { UNFINISHED_SURVEY_DEMONSTRATION_VERSION } from './demo/unfinished-survey-demonstration';

export function unfinishedSurveyCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'surgery-trauma' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== UNFINISHED_SURVEY_FIXTURES.scenarioId || scenario.metadata.version !== '0.1.0'
    || UNFINISHED_SURVEY_FIXTURES.contentVersion !== '0.1.0' || UNFINISHED_SURVEY_FIXTURES.seed !== 5137
    || UNFINISHED_SURVEY_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(UNFINISHED_SURVEY_A_PATIENT_WHO_CANNOT_BE_ASKED)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['unfinished-survey-fixtures.ts binds seed 5137 and content 0.1.0 to expert, incomplete-care, recovery, and no-action contrasts. No injury, healing, sedation, or neurological model is claimed.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['unfinished-survey.ts runs two authored transitions. At 10 minutes sedation is lightened for the routine neurological assessment and he localises to the right, does not move the left arm, and grimaces when the left forearm is handled, while the ventilator, drain, pressures and every monitored number stay exactly as they were and the ward asks a second time about the bed — so the only thing that changes is how much of him can be examined. The trauma team answers 25 minutes after it is asked — longer than this module’s second lesson, because what is requested is a deliberate reassessment rather than a time-critical decision — confirms from its own record that no tertiary survey has been documented, states that the secondary survey entry records an examination rather than an absence of injury, and takes ownership of completing the survey, re-reviewing the imaging against it, and anything that follows. Nothing arrives uncalled.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['The learner records why the examination behind the record was limited, records what the injury list rests on, records that no tertiary survey has been performed or documented, asks the team that owns the survey to complete it, records bounded qualified-team intent, and reviews the boundaries. Treating the documented secondary survey as the assessment, leaning on the whole-body imaging to exclude the rest, reading his silence as reassurance, and clearing him now to review if something appears are each refused, and the clearing refusal objects to recording him as fully assessed rather than to the step-down itself.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The recorded examination limits, the recorded basis of the injury list, the recorded absence of a tertiary survey, the request to the trauma team, bounded survey intent, the boundary review, and a current full assessment permit handoff with the survey and any missed injury open. Instructor takeover bounds a run with no escalation at 180 minutes — this module’s first lesson’s interval rather than its second’s, because here the harm is not measured minute to minute — or an unfinished session at twelve hours.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['Eight event-bound objectives distinguish recording what a patient could contribute to his own examination, reading an injury list as a record of findings rather than an exclusion, refusing a complete record of a limited examination as an assessment, recording an unfinished survey as a live finding, asking the team that owns the step to take it, bounded qualified-team intent, a step worth taking whose evidence does not show it works, and accountable handoff of an assessment recorded as unfinished. Refused shortcuts remain visible, and no missed injury, disposition, or outcome is certified.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['unfinished-survey-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways for deterministic replay through the shared engine.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Observed-state guidance and learner-paused example ${UNFINISHED_SURVEY_DEMONSTRATION_VERSION} use ordinary recorded actions. Unassisted mode is silent and coached withholds the two non-urgent beats. The prompts read only the learner’s own recorded steps and never assert that a missed injury exists, because nothing available in the lesson can establish that and asserting it would remove the difficulty the lesson is about. The example is driven through the real engine in tests rather than asserted as a script, and it asks for the survey while the patient is still sedated and there is nothing to show, because an example that waited for the sedation window would teach that the finding is what justifies the position.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Local checks do not complete exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['Shared report controls and local privacy tests do not establish full inclusive coverage or production Turnstile/D1 verification for this version.'] },
  ];
}
