import type { Scenario } from '@anesthesia/scenarios/types';
import type { CompletionRequirementAudit } from '@platform/catalog/scenario-completion';
import { UNOWNED_DELAY_A_WAIT_THAT_NOBODY_DECIDED } from './scenarios/unowned-delay-a-wait-that-nobody-decided';
import { UNOWNED_DELAY_FIXTURES } from './unowned-delay-fixtures';
import { UNOWNED_DELAY_DEMONSTRATION_VERSION } from './demo/unowned-delay-demonstration';

export function unownedDelayCompletionEvidence(scenario: Scenario, capabilityVersion: string, moduleId: string): readonly CompletionRequirementAudit[] {
  if (moduleId !== 'surgery-trauma' || capabilityVersion !== '0.1.0-alpha.48'
    || scenario.metadata.id !== UNOWNED_DELAY_FIXTURES.scenarioId || scenario.metadata.version !== '0.1.0'
    || UNOWNED_DELAY_FIXTURES.contentVersion !== '0.1.0' || UNOWNED_DELAY_FIXTURES.seed !== 7304
    || UNOWNED_DELAY_DEMONSTRATION_VERSION !== '0.1.0'
    || JSON.stringify(scenario) !== JSON.stringify(UNOWNED_DELAY_A_WAIT_THAT_NOBODY_DECIDED)) return [];
  return [
    { id: 'deterministic-seed-policy', status: 'satisfied', evidence: ['unowned-delay-fixtures.ts binds seed 7304 and content 0.1.0 to expert, incomplete-care, recovery, and no-action contrasts. No physiological, fasting, or scheduling model is claimed; the two states are authored.'] },
    { id: 'meaningful-progression', status: 'satisfied', evidence: ['unowned-delay.ts runs two authored transitions and neither changes the patient. At 10 minutes the emergency theatre takes another case, which makes tomorrow the third day, this the third cancellation and nineteen the fasted hours, while every monitored number stays exactly what it was on admission. The team that owns the list answers 12 minutes after it is asked — the fastest reply in the module after the transient-response lesson, and deliberately so, because the uncomfortable finding is that the delay was never anybody refusing: they had not known she was still waiting. Nothing arrives uncalled.'] },
    { id: 'meaningful-actions-and-choices', status: 'satisfied', evidence: ['The learner records the fracture with its clock, records what each delay was for and who asked, records what is still actually outstanding as distinct from what is merely still written down, calls the team that owns the list and asks for a named slot with a named person, records bounded qualified-team intent, and reviews the boundaries. Treating the unbooked echocardiogram as a fitness gate, filing the full list as out of anybody’s hands, offering one more night as a reason, and keeping her fasted against a slot that does not exist are each refused, and every refusal objects to the wait having no author rather than to the constraint being real.'] },
    { id: 'bounded-stop-condition', status: 'satisfied', evidence: ['The recorded fracture and clock, the recorded reasons and their missing authors, the recorded distinction between outstanding and merely written down, the call to the list team, bounded scheduling intent, the boundary review, and a current full assessment permit handoff with the operation, the slot and the investigation all open. Instructor takeover bounds a run with no escalation at 60 minutes, or an unfinished session at six hours.'] },
    { id: 'debrief-and-counterfactual', status: 'satisfied', evidence: ['Eight event-bound objectives distinguish recording a total in hours, recording each delay with its author or the absence of one, refusing an organisational delay wearing a clinical label, separating outstanding clinical questions from outstanding paperwork, giving a wait an owner rather than escalating a concern, bounded qualified-team intent, evidence in which the observational signal and the randomised test disagree, and accountable handoff of a wait that now has an author. Refused shortcuts remain visible, and no operation, theatre time, or outcome is certified.'] },
    { id: 'reference-transcripts', status: 'satisfied', evidence: ['unowned-delay-fixtures.ts binds exact-content expert, common-error, recovery, and no-action pathways for deterministic replay through the shared engine.'] },
    { id: 'guidance-and-demonstration', status: 'satisfied', evidence: [`Observed-state guidance and learner-paused example ${UNOWNED_DELAY_DEMONSTRATION_VERSION} use ordinary recorded actions. Unassisted mode is silent and coached withholds the two non-urgent beats. The prompts read only the learner’s own recorded steps and never assert that the delay has harmed her, because nothing in the lesson can establish that and the randomised evidence carried here would not support it. The example is driven through the real engine in tests rather than asserted as a script, and it calls the list team before the evening is lost, because an example that acted only after a third cancellation would teach that the wait needed to get worse before it counted.`] },
    { id: 'inclusive-runtime-verification', status: 'missing', evidence: ['Local checks do not complete exact-version assistive-technology, keyboard, phone, zoom, reduced-motion, offline, and performance validation.'] },
    { id: 'report-control-coverage', status: 'missing', evidence: ['Shared report controls and local privacy tests do not establish full inclusive coverage or production Turnstile/D1 verification for this version.'] },
  ];
}
